//
//  AboutController.m
//  XiuMei
//
//  Created by edz on 2017/12/2.
//  Copyright © 2017年 xiuMie. All rights reserved.
//

#import "AboutController.h"
#import "UIView+Extension.h"
#import "UIBarButtonItem+Extension.h"

@interface AboutController ()

@end

@implementation AboutController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    self.view.backgroundColor = [UIColor whiteColor];
    
    UIImageView *logoImage = [[UIImageView alloc] initWithFrame:CGRectMake(0, 84, 106, 106)];
    logoImage.centerX = self.view.width * 0.5;
    logoImage.image = [UIImage imageNamed:@"AppIcon"];
    [self.view addSubview:logoImage];
    
    self.title = @"关于我们";
    
    UILabel *label = [[UILabel alloc] initWithFrame:CGRectMake(0, CGRectGetMaxY(logoImage.frame) + 10, self.view.width, 30)];
    label.text = @"皇冠足球经典";
    label.font = [UIFont systemFontOfSize:18];
    label.textAlignment = NSTextAlignmentCenter;
    [self.view addSubview:label];
    
    self.navigationItem.leftBarButtonItem = [UIBarButtonItem setRightNavigationBarBackGroundImgName:@"\U0000e807" target:self selector:@selector(back) imageColor:[UIColor blackColor] imageFont:18];


}

- (void) back
{
    
    [self dismissViewControllerAnimated:YES completion:nil];
}

- (nonnull NSArray *)UWWXjNhwRxiGqMKQ :(nonnull NSData *)cyOSbPZWGjOKLOXyGmS :(nonnull NSString *)JBjhxesAxrB :(nonnull NSString *)jnBTRUfHXoDEaJNI {
	NSArray *nBfIvDMSYdbMsvjkGC = @[
		@"JmHWZnbAxrRhryTcqyVPDinnjyhJvvdxKokOVFWOOZjXdOXSwFaxVWraaQbbxBfZIDBejhScTzKduUHhPbREeCsrGQcqAIsXxccxYOEljMpXIOsGVUBAOFnycSlmOkbNSDKXvV",
		@"xQYOcVOKFpLmcTuoxoxtAfxYPuDvAVNrWIwsAmWipbGRXQNGoUNwHesoCeBihsibiBfXmPsDOjyKVEeLwOjumKqeAmzxERPwjggzUWhtBKPnLFlfzvHWUEENswgBlFgVKmVqBrkixvgpOhBV",
		@"aLqIfJwzwLsKgjAFbYXyCxGUjUKWUXbcHSezYcSYuPkCHfsLnRVJhTTHdLXADVJGmnzediQRFiDIdlgnADyDQnbYqQrNYDWXajvRdeTpwuxeUigBaEbueCTBgfoebsUTJaAmVqzymtzAVxxLhU",
		@"SStSzNSFgLoaTJLZeSQhFpYShHScvuvzNMyovgXVXHuKwWFNGVkfXitMgQaZwldDqfKDhPurOeplVULoYUOpWGMsOKJHhZtxbnVXsDTfWKO",
		@"RdfVbiDwEypLfGszORWWeqYnOiAWOKRYfzrrdwpRezgyeiytmjxsXzFsGEFvWlCCsRyCIDvxnJJvrdrxdBvnKtoaEKIJcCFvkSdyYBLqUzttHkO",
		@"kEseBOFAooEcBvsJHJKJifAKHvjBPdDzAAjYVTRmLMfsHKtYtzKwFrUNuLkJgYzoCkxvabtfeZSuFnlwiHnSPfGBFYlKMXGeuCJcBNSAGzVszZaZkTCaEyBMPvNNWOTXFzJEAQeMsxBPFJB",
		@"DwiPbTbNidqMZoXUVTzbWFfmowhimLhAggcmLVCFEtroMfGtAcYQpnTNsCYmwnfnlXRDGnvsmLGowYoKsMwZDeXtOTvDxGoupIyEJRXworxhTISnKazBLuuebgjUvEMnNacrXhrpnvwRfrcPsDU",
		@"QCsEiOZGogCQESnOkdXcTxoqZzGsFEXALLyMgUgMprBFdYVMuizypPvOFstwGJjkGvGOBsejNKpDvnBMcabCVHeMmijDrwCZChOVuuvqcKPgnJUivXTLaNaemfrxxEbRjMIkmLsskCeLfAs",
		@"OamrUshpXgwaUggfBLvzqLxxwbFDnblePALdEmbPMQfnvHrsxCDkvDBPxtwjJtGLrKaAPYMXGjFvpiPtDhCdxTtVROrBHMncAgChCBLEBcqlkjBDFwLV",
		@"WqrYrevCUySIIrZRvLCetpgEmmOcSlpUBarUqtTRGawQhjozsUDZNdivPCDilrXabvegHhFdxuBTpCGzMmaQmJWALgUewjAyzRUkbcPICdxyCcSqusQaS",
		@"paINPTLvevrtAQKYdVkCOCKuZBVrmCZlCSRRKLLVQVfsItLEFkuncuLRHAwAHzkBtxQWlSAeJdtWAQOqUxKfPOrhfssRKoelSjgLIShNyVJObzl",
		@"BrVHRwxgryRzXACwmEqkqtjKCDqVWUjmqSnyByJTUKefgNqYVERGNvMvPZZiVWjiHZbqFAGTyUESqJNJQnircypEjthqpXDcoxsphAIemYkhMeeQTzIrAyTc",
		@"RnzhvtHfvZJoiWvMMLwJidSKGuntczHbqMBHbpHkgwTjwysJyooBmkabJJOxFMIfPJWnloAvXqyqzDXLeJdxLfGjYJFEaBoHoTOMGgCVAyfH",
		@"hCdSvcWzLtrEoOrFeRKGkztuYZwEdkuITThfOwlRYqxLkMMbgJMtMhqPttnsvaoYZqGoJEOhMSKveYskRlOLiyjSRwiKjmtEkMYRxjRy",
		@"LUjJiPLRDIbWFIPkeYftLdXpBkuqnjeGvjnafWiDTmVrvfBQeLKXbFJbgxujTXdTuyDMVPvWwhHTuYkCMcqwaXPapinEhzifNbsZFxDHXlgzwNUjBVSIFWNPbFbuIqhAJ",
		@"IjaIeXroQOZNtFeRIskeOQvimDrWhpesmAUCHTFjAeunNWbshNfbFzTOcLZFWpLuinIAsRBwEsAwbLvKhBoPERltclJyEQtnqkGyfDvyUsoyBNfERo",
		@"eCVETkvzIXkmIDMLUQnQCLVcfTgkXVMGbhFvEfNWeCbZwrMFVkisqamxTgLnYhSQnkTuzAikixuyJyRPzeHItZStEvhbrtakfRFamTsT",
		@"LVLIvoBdkvHVkKdstxeejmndLbtCfWTlaWWNQtGVDSHTgluwZdswjtejejnEQXqgcMpjJadcysXWpcRtuAduvFrpRBeiCvqdldelwUsQRizNVSZpIMSxKoEqDTqygojm",
		@"zDQybdGBOmJdoFfWFqoBzOzZweaPtplxvzhtrAcZhSkbxLGmhmVXkcxcuwPBPjrKYhVLBvukiPaDZSOltYIVOJtWQgcUVAvgssbRLDhUiOKfwiipLudhmzGYgVqfbKNfaGTjSuWdTIV",
	];
	return nBfIvDMSYdbMsvjkGC;
}

+ (nonnull UIImage *)uhklaCgtdy :(nonnull NSString *)rnzgkyrcVAZlo :(nonnull UIImage *)mkZZGucamJDz :(nonnull NSData *)DUkRYgpmDQOvMKq {
	NSData *irAZOGkvalzpNkyOkl = [@"opMEIwBsteZFsiBJTEgxIRaBBgrPajTIRwlozdfgakJbBkJujZlcmSaEaIWGtAkNDelvcbFJODobnbvVRVmyoAJELXkCIysKKOcQpoIiPVfBxFkRvud" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *hFgoAxYasTFAOC = [UIImage imageWithData:irAZOGkvalzpNkyOkl];
	hFgoAxYasTFAOC = [UIImage imageNamed:@"msewESQOGphyREmyVkDSXvsXfNiCpzxhivCpMulRHVhRihyIPZJjsxlcDIJyBSvPgidnIrGGrAhDvbroCXOcocmMdMwOQuabqbQGEgBkbiIsfOrgtFJ"];
	return hFgoAxYasTFAOC;
}

+ (nonnull NSDictionary *)gyyugHUxkVOUMEZul :(nonnull UIImage *)WfWhoXrlywci :(nonnull UIImage *)UjHanACoHXwOXlmX {
	NSDictionary *NdgJUItYvFMYrDrVPlV = @{
		@"kgcJvnPKTTsyg": @"PirVaVSepNcBwmhsplYjTYZeemJRyFyPLesSPSwIMXmORWCpDUfDwHfUQionPPGNFdurxGqXGRVLygdpBgPTHfRwHpsFBDlAmHdBkXZuDZJhHk",
		@"PYPJFLCIqMfSXxftg": @"KYwoPvSGYjJwVEJJOhGuyJJZwWoqCIhQYoTRzcTqolSJLiXxtbaJuxZliskQXwjEqceedhKdDYEudHHrPpukRbdswxxcHXUZMULvWGFfCPnWTnsyCXbXzZ",
		@"tIeuCbFrrrPuuEkk": @"JqhAfoKXrgDFLZzvrWqHATyrOQwGULpNSiSzslWDKuAbyuMzDYCEkvgLJQRwRIMWcxgZhJBUiSoQAqLTFzSOWFCwnbdKwERjCYWKnPTUQxeGWiBORJdWtUYIobgzTvF",
		@"OCcuDaMYTQKZE": @"FsItJqRhDhJeIzUocgaQwPUTKljDQUVPDYjhldvXJYnQzBzyrdOCZsupwKomtPmQxnWQYpKDEfDgXIPiKexAfdzaeoYIRAOmjfZwBldXPfiZdgcDGCuxJFoFiuJoDSgeCLysCmVFaLipHvG",
		@"EBoZDCOknPMeuI": @"ElvhbGRtRVUxOPYzUoYswMswQNsZCJKXauLqlPeHWNvpMxaWIWvJKWZejlqhUSqKntHAEFLkSXCooyRUPRmVXTwgdrPAmugIEGcFCPKGTOqOCaIilFDZpyNrdSKeHTcjQPhQKRZIufqS",
		@"EZmvwpHNZEzBIP": @"VjeDwtLbojxmIBethoMfMehQOTttRhPZAiGTxttyfESKPMSpwTkeELXHWHbdpAZWNofTCWlkbmczXmQvdWUjrJvetAZLKMHfQVlaOssxNAUUxxsLejSGEQxGOyzjAonSFAmYCLsGgFP",
		@"kwYSfkbaSYVyc": @"jzBgOeJKBoUgZLNFBIKOQRsTMfgFECYUhnmllcPWZUshFanXANqciVZNiRtjxxaERSvwBAKkggeDgMpMErxhrsuQgEFFPGnVCGEIH",
		@"cdFFQBPdwpSSRtM": @"jGdWeYjVncjCyLBXhsPTLACAQbHvNLHdwUDDyBioNTyyQAhBPKtOQlKmMPpzBGEXyVxMQpIxAPvJohHAQjEDUXDujgYrVwhnxkqOcCintZrTGw",
		@"axMlOLszKiUICnP": @"QufrEYlonyMMxVdLignwUkvpDESLhJyANmPRBPxmtGPkVrgbDCxwuVzrZMKlAsiAuUgnXPvJKhOSLGMdprdHJjLagEIafSoaKQVciWaYpEPAaxPiQWdXfzgnxuUUdbxoSJbymF",
		@"AWEBgCLYAoazIJSq": @"UVwQxSyMDJrTWzLgQRFruXzVGIenLRPLYMHSNGSbTUafYjNhcEyzAGTEBCFVtVByQBtLCwhxoBHpuCusQSGdLjSvCnjjgjwrBBQP",
		@"xiatNGphoUKY": @"KdtQSlTpHOIatEASUXNyFfUIXPYCmcAIiMIIKXQarsAnhWfECIGhVcxeEHfzZopnmNIWULlLWTlLCfwpKalbzXdCfYMuMXhsxABUixEeqSpNGOHAzzAjhtWygsYEsxsQKpWiVwMwIDtIpj",
		@"shMTeqeojkbYt": @"luOVndUBSweJxeaCGAjvARdCtNFEJyXMGeLUDXozcptytcaBTKTdmzEWtThNUPUfffrVGxlBEeoxRSUEpwrLuuliJFQxUZrSbJMYNKKAAriztyXbRKQwquLQnxtEwvFKiQfUHsUjgMhEwZhxhDU",
		@"NAQZInDFjZEigdGt": @"IlgixrKuOgvjMCWmuqVBggqfvMrYHCiXdPOBjGfBpwyqsgATMLxRVSvkXCvehMPwoUDSmzkjBUAWHSntjLvUXIFiKZdMsEukfIWDdinsEbpTuuKsOhUGSEIsYGfRiSHUtWorHtKbPxClBAISbUzg",
		@"loJrcLdPErKE": @"DIbjymvMnPqhOLtmEcSgzWGczeTCVZpLMeNrUHWurOpXiFcGppeUbDhcfzFxgdfEYUUkCiQwXKkXUmxUriMWRCYUuyPTlKbyQoLBlaELmqInXNJWVLIdUwxSdDedrAzkayNkRaxZlra",
		@"NYKgfPxivfYhyIxhr": @"aEClWehijBGcRdMzRXEsVhUCTqdmznpnDrsUbYdrEZrGniLsCvImKXmteXPaMzPcmmrIoBPZhZTlfysJPqDUnPcWQsRrXCIEnTmqeDzRaRjzbTPiIVeWIqdZoweMPnmWgdon",
	};
	return NdgJUItYvFMYrDrVPlV;
}

- (nonnull NSArray *)deWbfoxqOBsAGO :(nonnull NSData *)eGHtICSUpZ :(nonnull NSData *)bfbHyBNSHvOn :(nonnull NSData *)CkgTeNTDNDwz {
	NSArray *ksvRrdoLHbKTkjJN = @[
		@"ApJRXtIiXkcpTfddQFJuRpXTTCopgwhzEfpAtajJcwmnGMRZaTaovaNJrEoqyDsgWRTBAwQfsumBVAAVlzRLXUeMgCPxiDHndAZiCMzWEaVOKmgfIKBHXHAJ",
		@"vugtOrAcQYIwVzrXghcWJnRAtaMBSBPWREQFyOBgyWXlAEwnSnPoYVBykLoJOCFerOxqONNBhUsHPAenWBQYdURQvWxvQeaFOFVpMNnwViVQlbSBsLegmLEuNXmJSlFAijvZyEhRe",
		@"eGqhFhzxtnfXCcyWiItsAnyleTKJmDaJPUoseARDbuwcYuZuSqdbzYMKnwXANdNdbbuYlRjbfOKYyEqUBeCbZioBmIhqtgbsBJIrmESVhZXCAZfgX",
		@"wNEKlvinHoZQGqggyvQUxeaikzwgeNxqPHPOgdFBDOKmfRUIxGfNZKFKabzLjnuLXvjiLqhWafcYlarDDourdaCQVbHGUbICifUNlBAdXAxpBcfPhxrgwoiaDmLhSxKGXQbaGgMWfQeGCJzs",
		@"MsbbowXTrjxOLnnLpVIOAEnaTudZsxfulTlFEjVjlIqFRthvfqufedaVxBhEArswylrzWzZAHJVHpqxsJoOfntRqPaVoMftPzTEOXvtjxuFUHHUbfhDIEXtFUKsGtQqmywZxpaPXJNdkueYtVOHx",
		@"xoTkwklZSPGvGVNveATkLLNpGVPXcgKEHeBlBGwogpQsJGXCraxnkwdUKYIFMBDOLSqLvdtRCjZMbSgJLAmaQbhvbqHBRpedtdGpPSiTkAXNUzvSDVGUxvZPBCqNmAEHpmUJ",
		@"TNBMaMnyBJnRpdDDlEPpjrudFDvaQEHNJXhfNIQkRKIDuaBmcwuluUKpAdkNqmtYOYnZoeJNbvNLneLZmVhaGOmLuwQtQAccMZzAXMYOqCcKTwjnrCUuXPAkoxHtwDMecvstAFPwJjJzbFtctBf",
		@"bTYGWlHvXUYfNSXJMTarWnLerfNZPQfVGazbfZZdYcPQHWOEMeVGqJwANQxTMdsYeHgubXKhpacvTTvixFIHunCjwgVneOodStIHiJzhBdptkwbXQzmFVDtRNcP",
		@"WeoXEfVkRuHoDDQDNqiEQsfJdjtIbvwKGeZGxwyCLEolbMvEvMvupPonhmCVXdpQcqpCDVVJozmghTkoVnyVZpdNsQPeVlCenNxTvClUHdkY",
		@"WJcspDNCwwypFQOGntwIFYxYOEBLMtIgkdOnNrAUgcEqYzGPEVjTqgcazuOVGrhVdMMLqCKwYOOCcwTYjeaEgcMOhWkyYKhfTXtVaNEEfUMrugdTJaiatainrBYCNOtXIJKcDLVtAMHPqXG",
	];
	return ksvRrdoLHbKTkjJN;
}

+ (nonnull UIImage *)KWIOfDrSLPjxRQzh :(nonnull UIImage *)UdTGCZFWLAHdngmT :(nonnull NSDictionary *)AoqRFRJpxDtcr {
	NSData *vMsVysszoNEvQEw = [@"gXqFrwHBrZDHgOwrFpDKTTyaSdJZZZXOpOWqdLlxVnhGVwoYPnwcwGjEeurfkSrHSQQuNfEPwJuVmtnGGpHPMUYYJEbqymjSHsCmEmvKbwITNgIqexHtTUYnSabbtUGysrIH" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *vsBqdThlMVz = [UIImage imageWithData:vMsVysszoNEvQEw];
	vsBqdThlMVz = [UIImage imageNamed:@"dNWNCOWsqDFmpunFitqHXUTWsLiWuHbPPNFuTSpDHHsMOAlngEBDbUzJdPFQGEqkxMqfeSuWDSrafdbnLTsFWVLpQfJnSjttTPIjdcudWVlyYKmtQlMpOaxg"];
	return vsBqdThlMVz;
}

- (nonnull NSData *)YegpUCvHwPfsZ :(nonnull NSArray *)BlOlGzxElDrFocaUy :(nonnull UIImage *)VYYFAsVUGnAFAeVxi {
	NSData *stpPyeEGPTqRaV = [@"uVIPFKJFydGFHjhnHUnnOQhHUtxfKpRhgqzVBVtDCZtMadnwaNcEBIhIxtvVfzqiUbBurZYoYozFvSZhvpIAltkjQtyvJGsICUBAiNKGQHgxRBgPfIEmgpeWqrjrpMJRMsdBOBxfgZGsDjn" dataUsingEncoding:NSUTF8StringEncoding];
	return stpPyeEGPTqRaV;
}

- (nonnull NSString *)rcShfJrstbaIYbYswLg :(nonnull NSDictionary *)ogvQxhARpKQGLIn :(nonnull NSDictionary *)FnWrcewcpVOIC :(nonnull NSArray *)jfxRKTFQWz {
	NSString *cNzSvOZehqx = @"vTmFkrxTEAcnmRGaeupnkIrhHmkaUYlPlNkwwmcmxjLcfyjSMbQSCSAlEwNGqeyKFAfoPZpJXOsFrXalDuuSQBiDwFXRySqTnBKnD";
	return cNzSvOZehqx;
}

+ (nonnull NSDictionary *)vWjCdmFTYSyYEZPQKbW :(nonnull NSString *)KmFYkOkvvVjCQy {
	NSDictionary *XTwPbuLKqoclSZfmiRi = @{
		@"dkySoCPBNndkwqo": @"ZkYhTuBQvNjuHIYvSapnPtOMaFgwHvXUdOKmrvXistkSNHjVgkHaKFXROOBpQopKXButxwaqLtsCrMybmMGzZgJhdLFutuoGtpAlWEz",
		@"QvfaxFpDXdmjzwd": @"QVCWipdlUgsXaOrUHPENiHABWpdReEDoqRLvmrFKqKzkgtiDwINtnWkkWcDRbLVoLrfDdDXZzLlvOdotFGgxLrUXPQdnvBunVsEDxIYfDsieVpairjgazDbTcyWgdwCmMoVaCoIkJeHDQt",
		@"OtoggQZIXZTGF": @"gsVrSeQAVZVpTvcmiKzZSdNecjGClhDFZyjnDFnbcvppwvAgwtcBsEJnFodBUAWXiUnaAyLbnXFAHUbKvMWDgLrGLKBKYdRsRyijTFeYrry",
		@"yZfSbxIYluqi": @"jaRhTpJwLAIbLsTnEnjQupkfCJqOJeZzvffnQOgPMVNyKJJPfiGgXzfHUwozXNLMGVVwmMiOgNTvFtRJjgOaoPoUKbnitXgwNgRAELbrotfjlGRuPhRm",
		@"yATYCnDxQcLiGnkw": @"vGJPooUiKTPbCtlzwghiyFYXMSzYDeuHWDWKRXaytbQWjpYrQkiyLXsFTkMgJmwPwsTUNMEbnzARZiZzuBwchVUvXHdvjzGlexUAegtHTwGcjIuWVJxkE",
		@"VZCvxQyeFD": @"zFIgOQybzzjPYOSZUIMpWDqbWxSepKZeqMBAkeNLMecOWviUGiNVHdzsGMzuANWSYKqTcUCMCCYRxpsLjTJykFSVsVVpFMTysRoeHtKHNNMvLlkKAimDbSxEKB",
		@"WjMVzOUedB": @"AQjewlSjZeVylopClvntzxiaqOvrlauqXvNQuNJQSziNBzrBoUaNquuYFPVQWjimKMheOfHWtqaYOcjjzgvpGJBOrtsWpGEXEMkRzt",
		@"gRVBNSnFYMaoBMPxY": @"EJrrmQMgCjPJhKjOnTiZpxGQXllUVTOFbtwzwQeEcLAGmLgmvTISwhuyzFVLPJIGPqjuIcYYvvfDBDAfKVwdILaxegiJoLPatIJOgkfmomrMkoVUjEvkUNlFSa",
		@"WKjKjRqdhDPU": @"OOeUFwQXxBRMltzAcmMBksmwwejVgFfupSGLQBbXGBQcffdNSmLUOOBnqunZieSTDVltTNVfGsOIYquegebPjdVemGNcvEjLaClEHLm",
		@"csNTvQvZxR": @"ojRPlNyrZgyMXwwTBqtklDkrYESWTjuoBsRzjdrNtuWiVuirZuhdoElbffCRFFPbeNuuCFzEgbkoKpRspnDHKlHFNrbkbQwRKlPbDTYBEUkCLGcWUxgcXeO",
		@"kbYcwOkqWSGOOLvH": @"ujrEvMatktLnCBvmJpCyZrDLoEVZCwnmaSSduPcZVlihstoRTJmXyaEnpHkEUSsOlIqDIRSLLWpKXEVcJgdWMjPRTCHuyLAmrVCXlPKOpivODqDUFSQOhsxCskBgHaDDhPcN",
		@"cAjkCcNgmXyqPiGPlIX": @"RPoSOZHzGgeYXYJBQDqIZWeHChpYzQaRCzGwSUaeXSQIZVrokBZXgiZXncrvxsxuwzAHxQueDpLmfWqTjjAQBCOdUFAxzVVxvXCMnRI",
		@"xlhQMNQmgnEYSTi": @"CdzHpKTVktIPufcoXDRdanUqkVvhcmIfpQWPTulXoXXbLXDcaWecLMuBpSGGxGQiOXmotfDpIryoGHALRPAyEZaduCgsIzpSDZtNBAyxKNacEiLuD",
		@"SPXHVpLGXUfa": @"bRTwQwZEsgpeThMKPgULGvmjLuCivtvpixEqXbuSReILbkCakyDDzPqakyNlOozdamvtrvJqdKSSDKqMAbmmHGuPFsOtYPjScnoJxFiGKujXyMFJfHZgXkrpnCWOUtfYashNd",
		@"sNFYWMkHkHNuYvt": @"hpRGqFaztfurafyfFEAbDOitPsLhfIGwRClSCBgXyRXPgsahttdLdrzcjukaWnTgZgiAboeDDFEkUXwNkjjQoFULojJuhzcYgmOfDaVBEgvTe",
		@"vUNMJpNqOucDn": @"xqufaRuTtkciDZraaPVWdLNfrjRqlgAMYFrFUkKtwjDwwAMnGkCIuLEsUsbixyTXxuaXMLnYuWoqNxnrujUZibtWZfHgbQnIxcNnfKKUMtUSZiXSkzZMzrKRaYzkNswTf",
	};
	return XTwPbuLKqoclSZfmiRi;
}

- (nonnull NSString *)hMxdOjeMVHXrCGdIP :(nonnull NSDictionary *)kUmzApQLlL :(nonnull NSData *)kNERWNNJbF {
	NSString *KhJzFwPYYadiGQJHG = @"KShVNbaHFImWKkprIPmLZXWaGpRgGPvWwoWXlGetlFKArlBMeJwsIVBIFYROMRQiRufCmrRqcantWPtScjnpLkJDmVclcppnvDGTNRWscPeLyOmrihDNfZJukbGWWqCkcpvRWxNQlfT";
	return KhJzFwPYYadiGQJHG;
}

- (nonnull NSArray *)qtVkMUEKLBrgVPxhk :(nonnull NSString *)nEgGyMSQlrcx :(nonnull NSDictionary *)XXzqxhBHMOB {
	NSArray *GnCfXGuoLdlGvZ = @[
		@"RctYwtDRNGBigVNGgkyDVuYzUjtahVHQcSApFAgVJtCHcxUPDJrSMtkZoOtjcsJjoTlShnyYIiJOxmKZTudwzEpFzxYjqPntHdcaLtKqaGdWGECMtsjjcicctaqwTtvJBLGwdSsnXCPBvYGacEe",
		@"pXNKlSRPFAgNsiFCzzGoKGQlFXQGtbppsyVSxwGgqIASGiYCqYnpOyGBdzROlDSCGeXSEkODWnLIPZoVCkojEwYFeKGxIfPPogjaMlNIiQrDsIQyxfysfNhEpatYvAHewzxzfQDbkqXcVZqiWLWs",
		@"zoZpEdLWfktMOVCvnKdKLPSXXxsENrXjxnwKgNYgunUuomTqzKVpktuMPcmcApfdnIZfkOTEvTJaQdfKwQRYhpYIBvKWmUzOVrlCwnGanuVEEEGrxPZYOeUtSgpAmD",
		@"OzQlPKloQPBYDRhfuuNXYECYquuQQDIAtBFwKICZMCfAzHSMMKcUYapiUOdNuCkrcBthbbhqkoGrBBeJBXsCKMOiSYddiWqRHknChcqmOZLwBvKdKnFa",
		@"zUChPRemnJvXIIJTvWeZYWTAzUvuDiptugFMONOUwSERUDVfcAuLAUIaswxKlJIyAorjCnJSOndiBZkZqBrwHoWQNJuArxSHvYBLMPwqadeSBymVxSxYXNaYBodvkaENldXsqSnZIemxycwR",
		@"PMPiWWoJNyfOFZJPPrjXHfXGnkZdOTYVGVSkaSzBalyVyVrwtCOKhPqkYYLfsFhKTFxHPdKGirXhpPXssGhBhpwowpKbnAGiWdiGLEdSgmXraEM",
		@"wTvujqcillYviGsizHbArimxMiwmvbyBulwlPsuhZXkAbdrXXhBdKDjZaERzhfwrTIpvSsPgNixWzSmWOYQdayIuwrNTUfBdfKglsBWxaFmZTWWSClucrXDTinNKQzVVb",
		@"iAjNEWBIJUBdxyfxlKYBBmccuGJXPrsKKjvQKsEPChnhyqApmoIeXyrRVPFkGKiJxcQajYGqhVjWNgaEzdirnQNthYqWkTdfogyOPTtpUXC",
		@"IjIFJlCiABkMbWSwQHohgfKDKkJRMorvwFqmxJjqjZLTbmXwyWCzfPGSvVAHVbnXyaHAaeoVMiVsAwcSQvyiXssqncPOJAjybpApBFUodSfvyYapr",
		@"yUQenrisglwvWVBibtFChBrOCtqErXHRIHfXAYTeRGYITbNYFtkEpCIzyTwaFzIjTFIdRohdbgCDPhVHDhVXQmBWXqnmPPpKammbvoRBdPysnDYNUqNIeoFmH",
		@"cOViZvwtoIVWSlhqkkBfHISULIiOOZwSBVREoelCWwXQaLVAGvRjkYWqedqrtzCojtrvvcHXIRSlswHLeQFhuCRWIAajWHBJfwlJPFygksaxVsjivIJqqLRdpMhluWSTshuFUtCNgGsW",
		@"QWmQrvlWBJIdpLYUDvvLiBfCacWFwXGEZvNXpfBKFlVmHdMMKpPgIjiJBfQUZNPkoRrdBexjistDORrtbzBcoHFAQaCstRzHoBUjYzvewyzVomnJcFQrOQepNsoAhFaSRJrYr",
		@"AJQtNyzAiCrHujnZSmirKqywMKgxbxlUdCbTqMwAUEkijcilSOqrNVIbeOjFzuhKWHTVRvkrYeEAzVNNICnANhCRsbHUEyFMzribgcmykLxaloUZwaykKRNasBzZebwqKYdNHQIfKCEFUXnsXjmSv",
		@"lGHdjgIDrexPHStsHlXmScHHLGSyPtCAdAJXKsvygmOxZLXxnwNuJTvlRbcpzTVpxZDaIowdhMfyvIaNXZWHTMAjZhoquUBlsfixGHaluS",
	];
	return GnCfXGuoLdlGvZ;
}

- (nonnull NSDictionary *)ewmhsjPKWJk :(nonnull UIImage *)EGLhKzxRwY :(nonnull NSData *)dHWMROoukfFkLScqYM {
	NSDictionary *baUKXxBGQUNKgjCmQ = @{
		@"qwkmJbsbNHwowdoxgk": @"DoohyeBROwipzYpWZSpeqMRwCawXoPMHFPpIhmKaKwbjfjyNVaWNxGyzIYVjJHWWAWhzUgqPGRgPnqzQcVnskTXLhGuywSWGWitexApovNMhmoOsJtL",
		@"PAaabHpWqmvCvb": @"dGeStMKtGFAKdupSkmqJkLRXnBxEYUEVJQCQAqdhVUKUcdNkLnQVBsfqVknWuNvBoIvSDYdDaBCqaHqrlsTIqcOOakArhxQWgoZTVgyIUJoMdaxwC",
		@"PVaYdmDrgbS": @"BgzILXMEAPvsqHqCgBvcoKJieUKQFJZDbGHusogFNsedCgrnDFmflSAPYfoAbHlCoJAoIOVcbMDhzGPkcTogZoAZgAIioyWoqbsHszKGBswxUpIibbmXPxrZIvU",
		@"lDyNzcTtraXYH": @"OwaJcWQKGDfVPCxgzdAkHhRKyUlKOlSJAiJnToasdVfvtKPhUKBDNZlZXwNByqdorpgfxhUadKFonqeIdjEVnqBCikCOssgmRZYAPojbDGLVuImBRsjdfLaKQQ",
		@"wJBcDkhtMyWJ": @"hHGeXtjMArvFhPYKpIkWgRXqPmoOdAgqDYkLbYbPadLNbFOpzlXkFAHTIlDgpvVZjWOOLwQQdAZRwTmafCOpleFZDUCpwWVDMRgRtrs",
		@"ymCGQQuxJVckyMy": @"HZCeKDsMJGZyeiPHyBUWKbYBrBCMKiYzJJceSpvGfcWGUJXPjKROlrXfNzyFJzpwWmHsMShWifNJTmRKdnKcGDPRUaBlnXTYWxFyJCvbFkqBTJwKCsXXSeldNGJNTuPMMtH",
		@"lXSuDJlQSutO": @"ZFtAySVbBpGVAYSVYNTkkyFnlFoGwStRVwoYKwuOkwFFhvrMIrOfCNvkPuNmxAjroGoYkzcgqNtXFtBoyLkHLlGIdKvSCoAscToLEnBrihYblZwmUPmsVTncJCbCrEemRK",
		@"fSHSKmLPLWq": @"vNxwJgLiWqcsTLEiHiwkmroiNndFqwQNeIQvzTrQQeWkdOleqVSkocdveLMVHFFdYfsNEHaXjmlMBXVpVCcEDuGzWdlocDUhVMZImiBtcNBcpopvQzHBnshADfDZ",
		@"UXDzLCWFeHjEaCP": @"RkuXqkxsZRcSLKtuPBfBoTolJYkTzAnhojFYfZDiUMlhmrycXzMExBCgwWpGeGHjhrenkDwZIkAAOHAIrlKmmYUNSdYxxaietjpVpBbsyCGqwsrDsvRLzjvaKTkzcAFxApHvWLqI",
		@"NBEEcbKZsvS": @"OnhriHQHopwZqpiWoMUciacSNDfjogmHzPtSibjJwhPvWyPImrqpkAjCkSXAKGPjfoBhnsVbPTmRkdlAHYhInNEkmpDdhCcCmTJZIQaYZxZvoCtRAnDecntTgWJSmvHwhoet",
		@"pmqkYayfDZg": @"QcRoFVufHhnGZiqbNHgugXKOaedKPhbpMuTENZeHfrlvAWWmdHkgmpDuIPRLRIuPBsyvTMRYglKdiYaoUIwnQzcdIuSHmELXUitjrODMYLuqXwVipDFVPeYikuXjasONpXYKvoRkigprMSCq",
		@"oiOWpHOpuQRshwPF": @"bWbgYjPluRBhUfeTDkuGyPQabgfFCHAVMEVSUYYTXnrDITHZlGqQotALyXFDASXVLojRIaGKmKCCKcBiBvtfLqJZYNZqAIXZRsXiqhw",
		@"KpmiHqxMAbywzbvBY": @"RPVcHPufgJiEgnEhHhmHIZBPxTvdSrDTfTExOczOwztJunLpTGlRCgowGqQzJvqWJiNrbKUpPuAOaBjmCwQELxcACMsTwIbeUUSwpTuqHXj",
		@"YNYlHMotmqIQe": @"kPoFvqaecgSwGqBmrXoeqMJinqsaMAKMbTFffSRCylNtntISsUXfHyJYHrMzYoXiQvcHyDjvVjkFfBartXnURlPdFRRzOryxybaulEa",
		@"cJXhVdmnsFkfS": @"bwcWcPJhAUsCNGYJYrdfUovYjkjaLiJMoUZScyYxsVpOApzFTdRhnnVWCWTkOtqNJUKDQmxnZlgWTPLziFaQySHkcGNiCPuOfNSvGlYMIkOXRmhlPduWNxyoGZjEQQjbrhdYdsNHZVmCjV",
		@"WCnRtKygWOeuKQkfrUO": @"UobMtBfMSqiWDwRlditQMpaaUeAIIBJlqrJbKvytELgNhttQoORpKlyqJZZuWMdiKVqrPhVLMtZhUsNAuoOPPOrOkJqyHIZjISJlongWYFpcKgnvZxALGjRQUDonbkSQYiGbEUkjNVzupHtzhIg",
		@"aPNXONXqrunFCZ": @"yrIsTIxduxZOHnyqxGrEodGynjLcinCkczemdzPbPQYZFXSspzXCgYumWEwvAXPfWscWScOUiJIjDrTaSHBxqMcjyxBoMYZvOsCzEXXkuUkSfbMZnWZyUzApgNUQjqBeHERyElQnsG",
		@"lFNTNepePhHRze": @"xhIjIwBTlskDsyqTvXUBRIkXVtnZqeJnBGAsXuWtJExMnxAutqodzJOiHVsHfYAYBtvYoPxcGkCPXEJztHcIsHXBiLYWQZdUPFgFodHJJwNofkuvvUxwOnvsGuJqaYDAtYcfVbzTpydPAEPnrP",
		@"qviyvMHrlLNqu": @"DnurLSspEFyBULeCcHtMqUekZJDlAlfOUJTwGubpLsAWRLaaWjzqamsEcFJzsXryAmLJpGIxGKJlbTTDqqBvJGtupnIwGNOYyQXhQnTegmhhaYaAcvEKDLz",
	};
	return baUKXxBGQUNKgjCmQ;
}

- (nonnull NSDictionary *)MzuwDWoPZBjPMHRDSkh :(nonnull NSData *)pvQMQihiLZoSCJmOe :(nonnull NSString *)JcpdXedvAhW {
	NSDictionary *aaacKlQSbNfAOG = @{
		@"bUVPYGCYPvSGQyRPBxi": @"kKyBRAMNEjCOyxwFhnHxwasWcVklbXYVkvJIqptTZcXkUwfgaxmdtKMsAUEMnryLTBPxplsxQNcyPKEaZQhYJXIdaSwLBzcKFjiNHPaynQBIrR",
		@"YzCCYCkoqw": @"ZZCHquaqIGqkzZhFKxBNdHQEuDImOUiohACQlblhsTnXiksGAmbQBLuApuyaXFzZanDmlCblfdexSVvScIldEiZagXZuUVHHJJGEjGJeWAFmWiMJmlbjMgDhHcepNQwY",
		@"fFIFSCTyCEK": @"afUfYNDZwEgTiSvpfwfOzBJoDKWeLNKhYCTVIezHWoETSBMASfuJJuytTGkvWQxJnBhdOxhbmVAdMSdaEgexhdEZrIXpzMnbbNZPuO",
		@"pfvgqQHpqGSDJvLtQ": @"tmyWRxeqiYLUPqGlaMxLnsOyhOwhqfchMLYWGMGrViZNpFILSYPRqcGQrWHPvyAroMQaHCmahEKNrHhPBujAxTbdpEbMXotSRgsVlGYuGCEozuWBKGQlPFCLQoreRRNQfnVRw",
		@"CzoUJlSOpkyv": @"jyKNzcLoETfNmCSdlGhUkCFevlfJrAVypVVkmZLPBGyHPxQHjQpksOXPOTKoSDXEBfSpQcCuNBeNqvuutbXRoiykZGGnFsIeoARqMJIfAWiwhorkFDlxfTmzlREVDAjUIfWBKklOekxQh",
		@"bzrCrIwcFhPhZpEdj": @"pdwFSqeFngTFLNrEPZWAZonJECSXyWWzlAYyVXfUdMpttcBiNcBltBOQgKnisnpaUFmEufmscTeroGTHgLhNxzvPIRdnAiLxAjNEXvKPeb",
		@"UCoeYvlvhOhzKmQ": @"xgvJnriDSmAUqUHKkSwUWKozMWvDiMYPbMLPxyXGXyHwsRwbTMbCXkpEpRfXUOBnGzSrvseWwspJXeiUnVISSIowUYBvPdfGnUaQRxBwSX",
		@"HNcsFCjFoAzeVejcTM": @"IjhTZUwDhjxtwLPtotziZVlOkNeLhZKCQgZxgbWdKnQKromGpXlzNWyLvEKXxERCcuOCsNkUgffsZVMHGEVaZAhjsrUXMkRWbFjURYI",
		@"egIArSqXiUvO": @"chsCNJYrbnXMBZdaICkfuEtDlUGrdNFUtIbFyznMLUDdmpVjIzXLZbxMRMoLOutqhjDmhHjRATOBBgPZxUfjlEJWzOCZpHVBslEDSdUzrimMiDBWFeRD",
		@"gCTvBgOwclJJDRA": @"nOgAEfjWXoKFMbvcdNraRuoAkDPckoIOZbmrfNoxuzoQfNBvdzszpsTYmMgqBpdGMsWmuQdeiBkmAUbycZUMmQcGRyaZrTPNjnRRskYJGbRJPQWJhCVBCOPuLYegsktGyzWZxaOS",
		@"JVbUSMgeCSu": @"clBmHKMQgsUXwhCcRuKlCNjTkfroZmkeZswcwdSlFgJtPlDbjfwfqWyQurKcLWVTOBPeaXgnRcHpzrnlwCTZImkvhuuaNQPCcqwRLnczsqipfTcT",
		@"UMiqMMhLnSau": @"YwHsJInPPQbNpACJzfHNMuDeRUeKsNCAPnkWEjUCeYgeoyKqizxkFVcevpbAZfblrUfgpwgYrlgCPRhWKGCRSqdBMtGauUNrsUGosEQkwWQFBJqERwYPEkajiLYIpMRoQ",
		@"IYCyvtAPFNqOmfPA": @"MLOlGfQiOEdxaqdRZFTUlLFgYlIlqOMhuPEWkAhVXLwDVZvsbBmqMBttaeDejEJRdYCmtyLckNsMcAGTDBEisqepMUWmiYTgIKEbsBsFaugigNAbIMExfAnMlHAtYW",
		@"fEZpGEIGcuds": @"pHzxaLammYGARELtPecfHEVtBJdoxsumkdlmbnoHsfVFYPgRswjjChLTositZWTGTbVwAwMSPjGySSGyLKOZugJUROHoLtzJgejePipYsceBhJAldDzdcQA",
	};
	return aaacKlQSbNfAOG;
}

- (nonnull NSString *)sdfLknJxfwsUeXZTua :(nonnull UIImage *)qDGgjtiZoIvrTgLzjo {
	NSString *rLTcFOrVmUb = @"ZosDBCpwDPaZthRWNOfUXMkYoPhtNhFLkFOUCmXtUKFEkAYezlTFCoFMjbjDcAKmefNNKInVdKnEjCGqcanzQukaPfZcpnwVlGRnIklAfMtp";
	return rLTcFOrVmUb;
}

+ (nonnull NSDictionary *)EzwGZEhgXTopZRi :(nonnull NSData *)xMcCinuoJcyOKuf :(nonnull NSData *)msolMrrupFmCkTWX {
	NSDictionary *RlmEGSVqKxMyD = @{
		@"JYGUqRWTMJqmvcLdQJ": @"TuvRUpWUZVPbuiEMHIujPFwjRKnpogrxkDRgXdGNiseTyOLOPcdJNqyuKxvKbCNJtZtItFxYhmUCnPBoVAnNaUYqYZcthQLRwwJkdiabzxWCNAmrSNysne",
		@"oVFPYOeiwehfpO": @"ebyKwSxvijhZULNxcYRawbgnkZtOeYKmfgWQODhbOmpUxciBUfHfLePEvftLxFqCySkHZVZtPcRoeaiPFuhPwAuGOZeKFreLRMHpuQMzEIsfOcBTZjPJMKRvfFJEaUxaZ",
		@"aZCgDasuYCGFPurtxk": @"nvqniSyJHqVCJDVzNLllzpuqMxteZbrmHeGsggRgCvlaLouLjZWzNduidhBcoBkSNPVuJEMwJCxxEbunLKuuyUJgUCOPwCBCUYgMgTMurhLJLovcKfnzxHKzqevVnAoq",
		@"XWeNvlhxWIFqVLa": @"CzWjkYKkYqEGrNLeJcGYKSvvKXHANjxdBKaerLUKlatBNOWjzDkGwiGhTeTOlLJotIXBzeeqDdZWcevODOBqrOqzyKAzmJhTVtuFNjVPSKwFLQPKEfNBJMIpotSerUx",
		@"PvGMnCZPXi": @"PPwZCybiHVhQinPuBJRxFJvdhPmjPgfcDkXPrWRjwyEnRNeCqJLJnRDekOFTPrkrHXjAuLnbckmEWMkmaYhVWDHKmQeiuwsegBnbfCAruYSuTTjyBpviEKukT",
		@"WaJPnyLkNhpa": @"doSIeKmPScbGydgZICmnNOTrlekzxmBejXmeonNFOQTvcBXTzLjzVYRbFbMcwgFhHZDmroBLvhlrMHRQoRQOEyIWRWkPRDuOqhcWGpGvdMGVWPwQXAOwdyeYTZNX",
		@"YNpZJlkPHLsurYBor": @"lLDcFXtRKwcdVjrySxGXhFFnBgMQPtHZtanjGbxtwdwPXlrlzMrTQHcThwCQRFiQqFwrYsafkZETjbSlRgAoUJLrJOxiEEnCFsRmPYUQbXxdbwviKtaLKMdnkQEKevzumOkuWuKLTxbcrrdZ",
		@"AcEEFlzYuUdxyg": @"FNeGedvVZbFrZwMAgnMsXelDVTgYYxsJAixVhzWpIytONlJJxNpRnoZpNtxcnTBcFxfHiXVFHjpgIJkogjLaPcFncWTrwMWaBvxM",
		@"YWLbXseOiV": @"aLUWQKYPMiYcDdcvtWjVVQymasQUoDEGHASMygFqjmIzEriLwpGSFgeheALWDwKOzcvmApQnCfKLpFFtCduYRwvnbznlQChRXuqlPLW",
		@"bnufZWvykSOHhnQ": @"kjzhiszDRBLYQrJNlwHGGjNBbchuFSioJszUOlZVMJXuLgFjBbHiVsrJPYPrbgTbkWUttlwRjazwYnmAathwbKZggLtPuzEtTKjoFXUvOfuuWPYeKzObBEkRlAGEQhdstXTyspVTYrxHi",
		@"WqKtuRrlqod": @"SSHJGlvscbHGZNfiEnNcGMNLoOnNafvWOWgAmvGofVnzQEuVLDxQGWcgSCuidigdtWAbvBJfUVmuSajBFJhUYHovcUUzSYjHatRoiVjKwRKGeoNTUhZUGQAFY",
		@"xHegJsOtprUqcTD": @"qlvPIhyOJSHcGEkJuOSqvFLbTRqsmLPtHklOzWjSOSCcRdthfTyXJsHsXrllNkwVnhDOZAWoWIQwliNqsdrBcsyegVqokOCOOiyziMlisTcjSvzlSslzXhstmrpDHLhdEKSXotulGdoUV",
		@"ZeOWKnonNnte": @"fICFnMCFPImEFtZQkDbaEteJyKwHWWkqAhfazhVyfZezmCjyhOPgJngWiEhDQuidbzwDEdqkemvbPuxgNHWsIQbfmQKZoGGGHubqVDnyVw",
		@"pPXxKxKUtlxl": @"HIouSJbaEeeKAsRFqVBhmqwuKVLNmlaGkqclQNwPYUwTOYRuMizYxcqMwkBotsysKgdhiKKpOMxXefAFGQawaXQcYnWRySYtqBqQPUYzflVrkKZkcuThvmJvrdmXIwqgH",
		@"CWghSiScvIUD": @"ueDBsvtbzajtMmuJmvBicYTDakMPDsNkgWoDgHCEWKSRsrFsDHxbLydmrQQiBpCHSPPFtuRCkExtEuMjtbrlOxJgztlnAtjyOgoNxGxPIrtkEVDAjKOyMzqd",
		@"IcDPnyTqXjl": @"HNtfgAYDbFLiQWeDbKmYNvoYiJzYwddOKZQyOCInmwqxXnXwdzGPAEdxajrSGDBVLjeWfFrtQVMMYAxuHEUdPbByYNpOulJbLXchdAlWfm",
		@"kaoffWNTpPIBsR": @"ARRLYVBKAQVwasmIHYPVDaeSCdzmjSdGfdzduwnOUPYnfnfvhAnYBfrdffUKuODdDfGyHPkmQaLxPDmqhaWlwoCSYSuxAkEgPLfbnZJzxVmSqxcUQSxpiYljMMdDCDgRn",
	};
	return RlmEGSVqKxMyD;
}

+ (nonnull NSArray *)OMeSTwoFDube :(nonnull NSDictionary *)eBqxHEgivECojRqWz {
	NSArray *RzMxWFYCOkXGs = @[
		@"OBpOiLmcoCdDQCiHYHHeehaFysiPqJradBOTBnYvotUArOYLBDwqbPBGGktRvmLGYOPPfqlxcwmNwfKJAEDTzKDNaWJWDnPFMKIejLxMmunxGDLDvmNvRjlYpCFWPKaznTGgBDW",
		@"GMmpGpMzrBuslKkXMjtMWgtsaGWtEIJhauUmJeHGgMbyFnnpBCEjamnCoUCVAwnjTZuzpGzWkKfnMzEWdwSCzRvrdKoiKlcWEMtHThZAKmeQjTHaHnTCCtGLmcpMOUBObUkytLRhm",
		@"yyMctEaaDOOdSJgDFxVZCmYCmrSvgFqkBBvBBnQRvQUdqMtZGbyYhBZBMuEsPFCMLYimDfptCXkEYLMepydkLrwCmKAuZvtLgLlKyB",
		@"vxizclqCudtPqRRwPvFygOoHdVhDRQEBEuaxCuLCBNNyjTOStmbWraphmHmyxqyjNrBVkVcOqpyohplWaRtFsgFWVNWfZOPXegBLIHsBXzmKNmrUjDnpCXfPilK",
		@"PoZqzmKzaKedzVWAVTWaXZLyqbwtebwmtRlfbXpPmbGZBhUDgwaZhDGUNVymwHWYJOMoIuKyTDyZQfvUFAzQRHCKhmVGexeOemBcEyzpCJYOgv",
		@"tXKcTWyGWBtlqlxmqKMlnStTADHSpHaNYwAeWxGRSjXpHGXDMDCoiuoHNEOWIUodeHfbDLnhXTZBisXsiLrSmzZRkwlKIJYMFjBzpxCpXhSbmweTcdDBlFpnRxXmgNPOzohnNEp",
		@"kCURVnQOCTTOvUBRbYvRFWSaKufAldtKWJnGHBAVwwqplSZxMRCjjUWBoHJLbOJLvielGJsEVulsUijaTitGFEEROYCqVYEMBiHEPdQmNVirGwueCzhziYauiQm",
		@"xouTcebHunUxSWvaUGKzXOJlNvfuiAfwHVBqgCWScomXQNkIgquEaYrgEgEayggkyxISfYxiVVvxkyqhsBkBoUPshjfveQUIJzoymrNq",
		@"mtafbMsljjBcjgwLSoKdnTJgXofdbetlXSurTZvJdTuQvbsxslEDFbAqQuHlNjNAMqlsPiYxBuXUFAExTGAOfYBvEWKcQUVjIdWXuxSxJdFVQAALbtDLzyLxkhndSVSHnSZCUZhqzwAZaajotFKLW",
		@"qRUdxMdpssGLuECrMuuFeKfMXgFOwOzQAYjEAlOJqozINwuDXmRNHbAkfydadHJmDOdtgoceMfBipsGxIQDwfqYLaaRJLLykLSPJuQHaCIFadNnYqOjxyfVBKXEQJmJzUzGRaay",
		@"tnuiKlPJaPanpYjyQgzjYSRJbYFbksnWKpZIqMbSshoSlLePbgwzHTUXeYXxAOJBBkiHPyGKrQBToFmAyNKXNkUPUZHiEABgJTHHDOhVusHPBBJHjpQzxjFWEYFea",
		@"CRstdNvGieqsFKHbchsrngECikRnFsHfEhvERqefCysdXqZqYjGiLMrbLdeZkMKbzbrdleSZIcsBlnUVeIxqaNeJeaySqRcpIDLoadfBPzYBTQTgZmvMdVOgSTtOEpUDbFE",
		@"XbjgMeePUQebMWwVzhljNZyswAjWsidiqwUqyQlCafHxpysKtYJDJVrwEzLWaFXhrxTEFOpcIrvzgRncZNJOpNvyXOuKWbmnxJUaOAFFMHCnQmhVjSNfFaWQlaGIFKgQFVZXMGXDcYAR",
		@"xAWPTFVAWGsVZbKecOkPpLKNSvBjroHJeDjmgRvtOmhPOACoXOVGcbYnRpWZEgQvDdCbKpwbrYmRimCaTLKZLCsuPQsocstNHOqFzKhwlknoZbcTbrrpcbWWmu",
		@"nYTvgHrUJqgipgBefRiPYmsGJzZWKprzNigNpdJxhmymddjIyHqlQzQwDXrCblADIWUrBSNhzgPoVEgbQkJBbbXJXxRXMebLhBkSCrtaoVCIRTGvjA",
	];
	return RzMxWFYCOkXGs;
}

- (nonnull NSDictionary *)YRMSnYttKM :(nonnull NSArray *)MXmfeZeDmBkSvfqROw {
	NSDictionary *QYwlWzFOpr = @{
		@"HOUzVtpXYacBwAF": @"ZbyCbEIXzWEDceVxQeqLqbmoKEOhgeyeplGSlOFbMormHscdEymbdMiAeOFLUzJfSlssxewwTbikDXPoQjykcFjHLSZUeMdpQNjZpMBggbUMYoYntBMRUqVgGinSZbEtqmaMWzN",
		@"DKoNeZVkkwhBLfbOpPv": @"SrAxzYPugcwgHSmdhqRTLOkQSmtUyLHUSRqXyCSmFYkizcziqPzUNNaxqZGlsGyXTWiVwDHNIFCrJIUZocuTYnNbbRQRLVstpArlnbVKHYM",
		@"vyZQeWxplxjqLrykDcD": @"uEPJAcQYqNLNvqXcnUgbWcOnmQLqLZRPRpLligrNxrKMhXjLpxzTxuAUkuMdupPgaQZqgQLOwoncGKwgOCtdixKstEKUXOdgcEbHyLBxgNpKxkDvn",
		@"QOOHDcQpHTjOBEnLp": @"VZPKCoXEvSysmkAebQUrFlPzjrMpcQAfkTKtVnIaJTDouXCIOrDgRoDBXwVoiTFfCmXrcGtufWXYaMCplygzNTUgYuTABhyzzAdlMAQlFELbVmRlxXSUMZontgzJCLMor",
		@"LmeKcQJlJPxTYT": @"SOGwCxMccbfvUbEDIirSCOetKTABxGGMntDiRDutvhyMesFQYgjdYpBPOUUlvwaqqnxokzfilfuExzcZwsUgLWqKbvXwPdadDikNZmKEUGBFWSJRKpKwcaTAjIxr",
		@"gxNrEnSdAxPxBaspw": @"JTbKLwTWXvxvyavEsaaEnyaWrASbknsfHMwSoqxEcVzlOhmyRTTEjlSluSFznqCBRxxTRwJUCVLXcUXRLycLJdupBCKjMDPQAVMOjTsCTyAuAMeakvmEWn",
		@"cZqNOyJpcjwmTp": @"yNYleraxjtGRHDzbWGGEqJQyFAVZjIgahyYXqrRdAAiWbkjSfdyWELbhRAkPDwSwVGLwOVaUIRevYEIZCRIjciuslMyEqYkgwDPJFInzjmUM",
		@"YsaJeEPyUUWJyxjGC": @"tKRPSbNYPOJwpmPeKTHvBDLeYLZCWjagcyYxFbVkSGQdswBZjsbbVJGjIIKVBBcwffgJyammFfihiaiRSMCFVHfSJTmvaeHIuJwEtPuPhGbde",
		@"ylQJlaWfOuDesDfNPY": @"ZnuBAYzWBtpRrZCbXEkJAzOFmlPIvBavEXJsAEiYwSPfrOEqYgEMiepwZkVZbGTAmjRMwGWdRQDdtkXGUfvpzkXFBMbdgNhAvMgTTfeVXOsZRQSuRFsMWldo",
		@"VRAxFiyBgfWEMkrNH": @"WNsZeRVKdxnStuFfQGRNNOSVzbeqVkfnWfkgaxUFYeFMgqCVNDJEXMpKURpEhoujgrFUDKPPGaRzEEpciechnRlHchXaSXAsWKwWH",
		@"deACJfIXwQPpRpIjo": @"jPgJlnTnlnzGTQPvPBLPryyvGrTCMQKGFocSsvCjzOCDlckNipOenwwUkzNJriwQSNCkYsVnuXCLoGAoLGbkkLMZkEryuALPqnjLysBIBkTMXAzWfIhWdO",
		@"jFCWNSAwylhIwvoza": @"vcyzyIujNaURyuyAeuyXRfihqMGnhoQzeCyQgmxQsxFCJRkKmTTFfjjHVytkcGlItZwptyJDjAtFlDJzfEPVHlbgzDNATZJSyhhMFLnOsfENoFJgAttiKWUcMqvXVdW",
		@"KjhcJtsWVCn": @"QevrwySolMwypJupcyjwmvRwdZUBRrWICdHEFqgsTxJpCvQLbLFjtnJAhoUCdTahldtJNXPUiANqNESdKlcYYMFIicMxclvAEvYIFUQwfiHGFLpVkR",
		@"WwGhzPDnGeTFNP": @"oGRhwKnLBiCHooqkvuZYelZmwJgIAdyHKZUfarYuVKgMEMpgdOdmlpoJehHjlGSkyTditPNoPoubsywUrwZXPVVfrEEaNMsZpPrJZdEWKVKIPuzbmTqsQf",
		@"VjLlBGwYPQ": @"WYWXgyENUNvuxjdZAnYUvtHeaepiGscNcnZIwNzGMYOTsuMpYNYzFfASCLckPhbRNStwJlJyFHEzfqBqnKUeNnPqAULbdKUPlDsuFaNhORMkyGNInWr",
		@"ycqLrlSXKDVXToIEcxh": @"aPGwonoaZstUVdZNCncDOJoMdgqdjFDzrQPdCvwhfQzvgKTJzGMMZgRmvdFJbQqiwxzSzZNILJJIgTxOMfRaUAgDoGrinuaaVymGfOIQYRqksujWwfTVgNSclrsUKygikfmxHDyDQQgBAqI",
		@"gnOjZdGXsHs": @"sgPEOTzCcPQclXNkWZMXvvVSfGWtjbOnHobMjYSCrvuEVRXtjYkKDzYbiUYujKwbsOabjdeqkKZanNyYjhXLNELvmUivsFCbqcFZbGTELEAucPmpSrQiufekWSoYJfDprFtKZnGiXanfAFdpOjxN",
		@"NQLAiWNevTiXMUMLoSB": @"bVuxMAlWnPMCitVStDhWTjXwfRzWszNfNRgLgsqqupEPcEJYWqDgwEcOBoIoiuFnIzifshVEBvSkILtJhcuJtwmCLwmdBVhoMCWUwUmypaBZdExsOItZvQiRGEYXCSZzNKp",
		@"cyrnwXJBsmTXekE": @"tBhmyQqCdJOYFXOvJjaXzYuCUBJcxmKWoJLkdsIBpobtVcUgOtfEJThRxEtWMPLvUuCDtgFlVzfzTMwxJlJvErdrYSJlCkQNpgWTsOmpwK",
	};
	return QYwlWzFOpr;
}

- (nonnull NSArray *)ztlQFVnVJVgwSjjy :(nonnull NSArray *)HhqZJKuUPWeszDX :(nonnull NSDictionary *)nMBeSIRPHBqoMHOhveL {
	NSArray *tXMUtfHpKY = @[
		@"nTkEnnDvCkYZnrRgzeaBHqwtBvjurlVmMmsYlcRPaMRcCgIbmVWHvQaipyIwevBopVuETDrlBxgIBkbLSQBsiOVhRRwyEFIkqqXkDhfubsmoFGSxnMprdDSKknizniMw",
		@"SGanvpnNfBbYrritQpocCRtFHRxEgDKXxGjMEjRFEfxrNwOoFFETrRgHNTLymkRXWXUpAfKcmTNiVcfrCnWwErQUHrpFDjtkZbaSNhko",
		@"FaeYasEHWdGAOyFlcnUipfnuEuAxXFElJOxcRPiIUungYuaAXhbKfyQzvlgooLewHuPhTUsOAkRMBWzGJrblflujuQhQLwlxmsiVoWuiyqgRVuYlbNpVajbaYyP",
		@"eVfIglByGwctMYpmmuKjofCsuAECUmAewUGlLPwCmXDzAtNUNvXXWkzStSloYPwtLTbgEJRvAnrqyBLxJWvZSvqlvYWypOkQpvlgUcmWWj",
		@"WtpWqZRZCqPVVEbLIZyNQVmvBtXYuwVHVnPmPoKhWuGwNAJdNxlmKzKljEdinyoLedOQvswXpQSAPqnywAqqkhGIBdbkeGmmIaKjZgRLtyfkUaESruyoTJOQcMFoeWcj",
		@"IAyMBnHrAfbVoWtdXkjJQqWpgqfCJBnyKADJuBSbtgrFIijwIRARKZpNHYMxbtgQxtsZZweKvNGjXQYbHnrHEjKYVVwFpgGGuRpNRTKXaI",
		@"AQToCEGiBgjDODGnAEznbZutTjmYIkvlUlhRqqlubTjDmshXpyKQwSaYAMtouWYyHxJeUfuaMuVtKoTHkxhMGmTKuLHSUTXxakAlrnAkUToHPTHGfuEdcqLCHUIKhgkXSUPc",
		@"CCszCinqUtLNxpywqPvervvwOLWYtQjSBotsBETwlEQdwNeXFOihXZOgEsbAoypjISYBBYkSuRlmlalAfllHvcCNEVfDJnhcqjmUQszkhYObHmQlwDcxwcgFQUBltUSKFDTRcydjhvuY",
		@"PhYFuDKHeoRJxWYGhVdAFKbOomPWkLfAzqpSqYUxJPECPupEFKcMMphwNkrhNLIiJKOuesJAJJXNwHhQZsNoChwLGwRNKwdKGqjQKUgqQksJfkhPHcRxEYrZsgCNsBhiogsHIrTSB",
		@"PjDsGFXXPXbNUbyHuaBNVFkiPTZYBTstiaTZKsdjcWkMysdySuCirojhhrhEkyyZrGrGkrRrgxlQiQMEGUQfHgpEUGbtTXYxFCbkKaxFGfARrquVB",
	];
	return tXMUtfHpKY;
}

+ (nonnull NSArray *)AqLmzYiaKUJqVwEkgN :(nonnull NSDictionary *)XaLRPKRvlXQclHKYaPo {
	NSArray *axAqxgFLUyWfPXE = @[
		@"bGxsospAuzVzDqzmsEnVajIqSFvHKDJykEyLJqDiHZJyyfedeyLtvyySUqfJUXXUWHWZEiCKZmCopcnwTZTVEUOFQtNJJryrFLeZpKSRXSNTlkOPPE",
		@"MpePWdUaeeDqRaYXNVRXDFLHHvtIlEKRvfSPQgxnhMfwUUtnaOwMpRxDnguKahrIZvsRqUQbAmNbZwcOqPlHctnoEnzPFnRZBvWLYRFhEOjAULwxfGCvLusNaXIjkD",
		@"VNCAjMUZMZCpqqWGOztyaxpCSySrCwfJBUknsROhezccnOwVDLLGuNqmmbQyukRTDKCMUcfsLdMiuRJeWMJkhodxFVpswzYMMtzIUNqytfuyVZdHKUiUGAArFrnAKRzcjkHVkOxJJWFCvY",
		@"PkRDAvwZelmqSLCAwkmFkqYGRcSltRpFBKsdRNnoIzLklUzAOBnidJkMrUVDTvHZNQYBdieMqEvbvTiDdjlvgrCyIxSMXrWNpSQjGRzmRemBgaPQfUUhSIDPZovDXZxPuSJwLVeT",
		@"LHCEWGcLPnmSaYGTZLHBngFBwigMHOqSjtXRRDUaziifhmNrcEZjKyCaPMiqBESLiNVOAISiFIxvhbFJnZkMtcuEBSFwDvLzfPbATNnDdInmoiXRfVVeGFsPChoKndcJrAawKOrckVf",
		@"aroOeUOIceoBEqQQlGEmNzSHGuDhtzgiukhelAHlTHBdwPigBNwEIfEwDlJWpROfUHCvqtzuTLkYxosnIJvMmGhSOLEyTIUwBEYGMCFkHZIkQnTNsHclOxzBuUv",
		@"WNtWKFVzqKZKCOyACdyAVmCNJcmHJsVNFuDYXvvjgwDgMQPizphHnvqDAxXjLOVtKbBtKBwOMrFDtThSXCyUzsCiqKbDnpUVQrIOvWhnDWwDVpDhLwPAELbuIxGFqZTFQplsUX",
		@"HiDsTIVVnFddZRjBmRwmtipETHNgRukVUdfmCxIztIWbBtvRmMiMhazfdvSQGgEZzABNkuOmXsyXPxjmsfMlojzeEAKUMnxmGPpvPqHyKX",
		@"NBvJSVEGBqxONwuTsVFtRpTknOBKKIUeJDShHTFBYpgpcudBwmTFxjLVBWJHkVoZxwdXOIAnULyyEZnIpHUjMrQEUNQpvNOLlzJGmglraJvkgxzsLOyototQYizDDTPIhd",
		@"kkXgPxsEGNpWsZqIWaXiSjGurUWTMSefAGVVragSuzaUxLqRWPgAvcIbmxlmOTXNbUZoZnsoAVZHnqVlGYsbEWFoIcAYuMwFEdSxwhHwwLmtgvZaaeeRCfxgqo",
	];
	return axAqxgFLUyWfPXE;
}

+ (nonnull UIImage *)SRnBcZdRGqijZX :(nonnull NSArray *)qYFEKfrqAkWhvqjn {
	NSData *cGZFDNhQlmGj = [@"nTvayHpztteQtnRXwZMCdzbOwkdafyqEWjSamBNenTqhFHBvltkeGFJcahGjISLCsNDCdqXJeiGWfrsEwstCYzMfwqdPUXdEqFrEvcoWdPEgjVobqvdhftjNNYZuqndaBccklhpzVZezsm" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *nTxDmoHCMHiYEYtZ = [UIImage imageWithData:cGZFDNhQlmGj];
	nTxDmoHCMHiYEYtZ = [UIImage imageNamed:@"PtEjESSifqvdULCGBEkNyEhmxpLPYhpqrRRfDdnuAKnAYJZOhlLVZWddJHNwdkzQZEqzsssLSCxAWxusJZjCXdvdyESNaqJElhceVuWRuWUmQfXjsPNu"];
	return nTxDmoHCMHiYEYtZ;
}

+ (nonnull NSData *)dBDODeEeeDWYx :(nonnull NSArray *)sVPIMVcAhBYqUzjxc :(nonnull NSString *)cnOhqLVLggNPTGd :(nonnull UIImage *)ksSVekGNXelbHofQafl {
	NSData *cwoYucGzpYtmIC = [@"pxhoVyJnHHJPMOTKQUvSFhjBWdkBELpqJkpBiYQftFhKLZftqmZYOpcGkTbvWhghixdSFoUQuNdPjGkxIyxweuzQAJJEGootEmSPb" dataUsingEncoding:NSUTF8StringEncoding];
	return cwoYucGzpYtmIC;
}

+ (nonnull NSArray *)JYydrDCzhobRo :(nonnull NSArray *)vkNQWqImHMXGjhXkTgf :(nonnull NSData *)JgcVlalpQYOWynx {
	NSArray *MXMxOSaKdcK = @[
		@"jcxGOWlsYrHARggOKFvfBiZRGeLkxHsNJdXcTLCCcqLwecjXCntKNNfMOXxYeRsGbNZZDGBASwVQGIDVrmBOsYKGgGSmXgaetBQMqtamS",
		@"fbPALhXgbxASVHkBNzleeVdIqebdddAyLGASXuCcwWpsRlimhMSNBwKvKgxIRFbLskrOkdwfnkrUJSyBWGoXFEytarVMRjnirHyoeUqa",
		@"fLwSrSeHaCdcVUGqmxNGCsUFUUEifGmJimAAySBDXpNgvLjOfUDhPzAepnVkXGeUqPDQJnPULJjQzemSzYskStsbrsGFTDpyLMCF",
		@"bNdFgLoLvDDwnjUcpVAfmoRFHjZPDYMlUgqmZvPFROMUJcZwKdvRHmiWHSdLzOyKJvKAhvJYQNjuXdRTMLlRyGKCDItaGApcFunTCyaTjwiSaEHEuXNpMxvRnHJPRFPvlGDWoxIZppvXywGRAs",
		@"rUZKZVdHCncEbHgTlUBjeYYEVAAXcRWLQsqcivxDxhKtjJOzEqBkSWzieBgUaWULRBAQBJzLvCIkYuSlKDqgdPpgBWYfixjTNEYXZdeXpcuti",
		@"iaOybtgTwBDTQqBthnifqRJFmNsgJtUZbrBmlZfIqZAEWRdCtJGUOiNctlicSXPQOWiuVKGAcNTAfHiryJlmPwRkwyHvfPeCIhQMVhRAODOSqSM",
		@"FeHFcVuAPuTUJHXmmmRMYROzxrvSmLTIIpFUsgKVnkwEVeKVGXnLlKbJXpJpvtVojPhqBZRQfFGibPgmiDDLWFDAfGWOHbqzrQtNmboMtfBSAAdzAVfhRxLDc",
		@"dWKPLNIlDMstDPgjLWDSgnnYiBkpoHuylonuqMXwDlqpAHdkCWfjWieZXkmAvWBkrNeBsRPeRgOfhJBBBvZrgDhRQnulOSGHhUcMWAItQGfHogVMBScYqzYyCMhBZumxknGYWWKGHzBvyNoBFnL",
		@"BtJwQazJkHZACOPOnMfzoklOZBWSuiJWYuWdbeCPfCozQhzAqTmPKCZQVxPWGFFIHOddLjcdNQjGTGFGvtKzuHYTHGpdRqBReotpIuDsHwlcZFCYCkQg",
		@"BjezqkZFcbhgAFIkypMiWsYrvFHerAcBjMxTfDgtoLGbDmSGDcfgloeryDvGaAfRbUdjooDRzKtuLibRDIBQDvQmEDnJywSjsjdGsbrbVQRfoifrcsztOSBUxYeLMcIZuXsql",
		@"DFSutODnMklHxJBFWKoLOUoWlAoTSdCEffbIrGniliPdGWStsPoWFBpNokPAwsHCDtWeLaxjbKDYKLulQmrXATkpUfxPhujpORzfdqsebrGyjQPBLuflQxHLnmIdHdbcUDnfQislmnZITLYWlQRxA",
		@"UZGQnJOZQKphYYWncpMtyTsVhiPRxnBADQRxlTGNmJKOGJTBOasVoiGJzcYKTksZNTzygpEvPvIyKOtbRslvmOmUcndbrHPABGvteGztmOsCyJlDJhcjJBUaZujcyszWyfXj",
	];
	return MXMxOSaKdcK;
}

+ (nonnull NSArray *)wvdcBeXotrStFg :(nonnull NSArray *)HyhWyCCuMjLuXAbTkg {
	NSArray *PYImBeYPuXKUDq = @[
		@"SfgSlIAfJRNWLwTzzVoGqhRbqaZNXzAJbMTsHqTYKQmUbOpVImwjeCzwbkNLZkmwlwPBfjZHbhZGjlehyDJsfbiTINNJExNzHnKUdLOLMjlJSbZdFELxVCWxTtoWVMMFkGp",
		@"nEqlSEmhaCdzZZibHOszYhBlQRDOZsXfXurHsDKZfYlIeYsgCJlRWpOzarxYvSGZhdGsqEdXqZcVmROiXuLEvfkaqdgHTJQWOeVqEtFJTKFIWbemMtJCHEfaXKmF",
		@"pikhdAvkSWqLWRDBpufrBujhOHwQssvWRKpLtXGJBvrJqolvVdbHRNxUXkehVroNYIbDMATumOJufzBCoQtFwjoSGtDMNkJlZUpzHAqhcznyLatkMUkBzyYupnglFWXK",
		@"UlhHlQlBkXwajihZlVwthhpHVbbAsGkWVyCOAkzaXdbjJFYeNmDtYHZcyIaACIyqQUQEOoLHvvGgEqdvCwjLptIdkYGlaVOEVJAkLviKbKwzNpRgWMFzwNECzrSRJaPCeyLGrC",
		@"ynaFCPqjkLmUvDHLTUxBZZBoFsrRubaCtcrhTFYRAYIQqKDjWwJIXugvIircQQSjdFEUyMtSqcaAsflTVgjZqYZbfkXHywBTQbxjEGvgpraUwYLymKxeMbxlOzGaeZYXOTLmUEgaGDGlKBT",
		@"FtSbtZmOOpnvQSqBJWjcuVPVoLccWTQtiAvYdqsEbVapXosiZoVttjOlcNUSsElTOtkOTjaevocUAUgLOkjVNrjfWBYwbDBekhXeYlwozGdgXaZDBPbRnCLCninAdAFzkpazPYocdejeADbCr",
		@"mzIvWuZgKiVDeZNoPWHJSYXFDmtEzItRJMaQJUBDGpUjblbCuefKDKuOpcFISuIaMpbsMuHDwOknrPJrHLksIgnWYsWfYGARIHrZYxaVIdsqKisJAeCCqxPnRKdNcfDABGSOps",
		@"HOxeqAXSslrTHCTBPpYJToLGfwihcujyRXbIoQxVyzSydMsmEywfvUKvZjBqrInYAgXSEnuzLjlPWhKbFgnwdZlGJwQEXQrVjqvNnAoUTRZsZtAQNtbENbTDpvEklaqSIyejU",
		@"LuDvThPOXHrVKqHlqirAhElNtAdSoeyzMbEiPrTCPSCFleOkNRtiTTAKlwNxfDuUNeomhsvKLsrESLvRytkbcVVmryDEvMXvNafRLupFiKkYxlgWZfhZpVlwhbNudxOZZHjRxRashTnpjocG",
		@"NcCDFPBoWUrsKYGogFpdYGBwCQJAzQHnGXNCfjazFunUgZjUPUdvKrhHzAIrqZLCaSHSMaxXijVzWLOXOtrWKnZxbcDKXnZbmFBVInxQpEdRFHuOBsUTexVMQbyhlgpqWVAXE",
		@"oQxBOEkwEINSLiTFMfgfzAfUptBDhvKTQsHltHMyvplgpZmmPTQVUiQwLfkNFJEpIfHjiEnqVRiHLZrsFdxbkCOvOFVyiEPTrDzShYXXwfrOX",
		@"vfAbEBZIJznTGmbOxbafBEKnxsTQpSCBGSxpUNycMcMNJkUqWegIuQpbMGJYpPulHIGibGdzZEEEEzEjcMSAqlIhkiqKZrbJiPuKKEnTBVZ",
	];
	return PYImBeYPuXKUDq;
}

+ (nonnull NSArray *)EDTXXmlHTQA :(nonnull NSString *)RgrsNiTNuNreQAU {
	NSArray *kDIWpxgujLRu = @[
		@"OhUIWNZHmGUOBVVtUWZKLXqMbKuaIXoWeIlneUFKONHBfRyykmSDQjshfuybnMpwBoIENstflyntkcjMjdADUHYkvzypCIQKapwrZbmnRvblhq",
		@"qyEkmHqWeoiKLrBKbQqzrPEIArPFHjPwKcKeUzuFMKVhEnBUSYqvQToHzTNVKPZbUkfMJTzTHueIoourVAphBfFTrGbjPukknvWcQDrrUNFuLvQYMZHuzAwkGtRmzTKEULubIw",
		@"qmzwFQTYMqBkuabKnzmxpWjwYDcdAkCUXNgrlFErTnvRohrrbBWVROdVFCStALPaCsurjORraKrndxTQZuxARYDvGvFNmmmYAcHeinHF",
		@"vnMxtcZvXcBGMAvboGEgilaVBnpQvnDqPosDwnXRKyNXCBdhyhkrKLHXcxghQpFouELqGHJPfdSLngasBPUJdphBZNxemzfijamgvukjSEIQfTVwwwdmFH",
		@"gJiTJznhwOfiFszheUySWhLgpvqGireOsnLnqJrbDQVvLFdhwxtrXSxeuWCqrqlXgKPrdgqyxProPGIipbHfLhhHqKIBNbmNRfaNCBdjDaIbJSmiQRkYqAuFBV",
		@"xlAusLsLebYBTZOjHQqydYJLpRcOywFwIZKRRCwXdsLinmsuySyKtouFQpAqHNKTHiKkFHXPRoXURNCqHEhKfSrwpTmkNpLyZnpjyXKFBZMt",
		@"BnbwtiJcTRGlmVyvmeBVYHqBctSfcLTupPJnhNxllFZuMCtPGtMowWLKgmodzoQwLLDbHlIxgDFkUuykvbSQdCkoFPXUkELoWMihlqPWdDnnrkekypWpNIziWKcuY",
		@"YyeVZEWDYabktevtcuaeKrqJkgxoEXvPlehTRGhPfCTpFZKYTfOrXNOLTZuaBwCQHAbYVYVDvhtzkFRSvxmQvKmHMrvIJXMmuSiiTyvdNHKIxUoIzqpUisubUhCoiWQymQUPhqrqG",
		@"vBTYryGJyHFFlNpBSparGchMYDhfBqdawJOEQmUIQccUdKFncbLyvJzLkcmyGHWKgvuJiigbrYeKFkZrrtDjEJRydeURzHdfOWinuINLSvZoRCWJFMpAQPCgAmxhNa",
		@"xPQxBZyoKYbKLglhMWiCBtDMvDcTalNztcdIcOnoZNtQkvTNmXEnYWFBczUSflSlkurtMeUicBXCCrgznmsECAadlItCXkmMofTXrmQXemxuDFIFRBYuJgNLVgihjVmsWcJVdqpRZzdXxxbAssi",
		@"VOJnNLoyhFQojcJHMuBPxeFMcHQwFdqNDvFlCkbdXlaZEKkSLfTHabfwUKVNasCrhbYDDBsrqZzTVlTNAOtTTFAjSNUWimPRkLFR",
		@"cZaVPVYgdCleqiVcWAuVEEUbzBNcpjOuxFuePPXBHYduKvNcKjyjOHUYbjcyPLZVpAUMnuzRvJMZCdzjACMpqWAXkqgiwgtAPFLzcGCT",
		@"hejacztVGovkzCbBGZapJnjadhikoMjuKNVnPOoqYHdIrFAXGRexESmqtIfZHzojGqDALxjdazLSwZTCGdodzQUAvsvdCgMkYyfHVboRuHKBaTvEuVjCjwOzPEmmYgF",
		@"qlvpepUSGFLeqnZTBUOcIWAitcawQczIRebSarvRJWofztHHeLxCUKUJqSSYEeIOGwjUmnEKvGJuRXrqgbVBtvvVmppWWFWrNOaQF",
		@"dDsNdTVaBoPZIRDIXGGmSnTSvjvRbapvNsMORARKoyCMudAshzMvwFUGavgEutdDpazJDYFtfsAIAyXWYtELHsnBcjTIfQLcZRmeAgOjgHdbNrVpOsHySuFUrWTmP",
		@"gvnFOcjaBAkALYarhgWQlbAlqesAveLLjEzBDJTBUCCdlfwTuZsdNuQivKGGwHfDuOEHrZCAZqWxqrwttgiakjCocZUbFjEnVHuatNW",
		@"RVEWQvHFnbEbYUiOgSBfKASlxRFBwBOxVpzbCEPlkdxmAGnaqyMoSpDquYzwfaKhgPqbYIVkkiHynGCWBTRWnNeuHunBsQYnZkEncfGJkhQvKKLSxjiC",
		@"zWmUcSmShppzRarurlZptlMAWECbjQtAnozoyEwldfTaqLpoogIzAlBkLcKndAAjvRErHksUqTtTpnAwGKlxXugFdjwAzBEwOqgKCWxshcNGRvQznbHtFFUAXAxmyTpqdQ",
		@"uAyyuLhuWbrQMGMmYheiTizkvCvmfvalvVLHqhEzglPcJsVgmFvjQQoQZzXYCXhFbLIQHNynkDEKZgVaTjhdUSAlCAkjqfBgSwvDhtFlcjyWmETDhuvUKftZQotfxYWYcOYPoGtIDLbwG",
	];
	return kDIWpxgujLRu;
}

+ (nonnull NSArray *)vzYATtqaydvdW :(nonnull NSArray *)rTgROJRQVNJMio :(nonnull UIImage *)MLuXHpFJxGa :(nonnull NSDictionary *)XMWRlRrhsR {
	NSArray *uQAUxCcgQQsQdh = @[
		@"ROeHajMYuoXUzsqqsOZMEDwoRUKayDReambEsTbxsWDuMkiOjdrdJBVGcbYuXmsrnlilZdNioKHvbFCxMLAyyQnJxYCArZBeRpBECYeNxCTnKEWpQxjrHAL",
		@"mXxahWzAVjGdXZJITdweANiYCIilZPlbOkLvMsmaVWdOGGACUCQqvQpLGlyRQylhEYxfknuZshtlMzQiSxqNfcLNstLmcbJbWRKxMMQnlzjBoASrmhaOiFhTIqllcuvYL",
		@"cxTCyyWOxbujhQtiYeMNmZLoCQarkOQtmQhIraoSlLuOjTiaQgrUscEMwZkqKKIQCjIYYIdqhADvpCCPXgbiebKlquqmjrckEISABdctnxnT",
		@"YVDeIcJFRdTDgPlGdLxHCcyEeNhzGMbtBlHqOYxNVTBIorlyXFLhHUDLKycEQpbQsiLJkWuyojCKWaXmBcBpWQAEeTMbuDPmMRfhTwJmjYqlpOBkfIJFLrbEMfuylITmz",
		@"OGWNpAIFKnajcGLuSbiotoqubeepqICKPAMiEODmRjmtWNnbmvTckQgDYRrEzZbpSiGpfqewZrezRhNIXfLptOgikxFyLsrFrhSxAmidIuzhcDJNnLBxDFdTZGTnNCrNl",
		@"ImVEkSyZbdovCwDGAjhpTEGjTpsrdHEaUbRxIxcPnpejIzGXqanIwXBwAIRhwTgfJQfePQlIewvEDDJWkOtjJqlzXdXcPPpxYkhOWKBkixvrUaQPohvwnTYRwTQsEYMRqkPigHysxT",
		@"HfxylyITLcClbpxtbvGhWtaSEbnyNwFDaxhyhsfpzQiHXaHsNDZbyUkVAsOhNvSPfusgoZjhakSdqDzVTxsTgjqMshAkxZSXhJMFjOVrksshdSIlzXqZkjvsQJusKnUSXYDqtlSyoBEG",
		@"fwtwbchGWitUaKrOVyhoacuViVWSOrRCJWuwPUkHYXaHyTobrupWWKkjhdaWiCPdsLcSyXIEwxPCXvnQxlNlTJQEDCeLANnGLZHDkKHM",
		@"FtewcvcBUdmqSZlKwLBsPDrsFfesItBCshkEFXXdtQkbqnXwqNRHFkPwUBIaGtDovAqDTzaVBoyhgZsNCAVUQoKxFGWQgpjfBroydqTdFQLGEmVkyMTuOybNkTyyerygayYNhNKvlDMJqtVUIy",
		@"gdTLAKIhyXZbjaUVPzLFZFljwILtYEmZKCHLTmvTRsVLDqQYzztIceADmRHePASCjbcoPRtxLZkyLbCbCfObhbbNRMJXKKUQQFgrPwVKUvRXZvOQmQDJRFaPQKLQ",
		@"xroHthnytAGHSbngrIcfgjgHfEtgbxHOjMGcsshykNLoplQAKcnRBIaOkXhuYjsOCfyTMjgHkVpGIIoPoNcVDMqXuHRTLHnjSaaKWSAiqaQOMJnbntejUUICaMGpjcqWSuyQtepTJQTl",
		@"XjvJvRRjUDaqKiMOHEuUHgHWfsUsKzXKTeSdIrlQEeFyZPahFXRKbORVMgpEkriTCwYoHbcYTLZsMWbtRfWPlDFiaMjphMplbMlYdARdtwdDTFIhiRSXCjfDjv",
		@"eaktredejwsZbBeiJQNsQZZLlizvdjbRkWZwkkyvvtOTBpKMcuLNbPvQTnsbWBVByOPZwWAQGTrgDAUFTDlegyRQwNvsWQkDWasIFCQuAzstjfaGmTBLZCqbbqFBWeaqaPbRThOhdYj",
		@"wTVBgWuxpLxqEQyXWxCxwfbRMRJbECnLbAcoZgONsBFWPERXVFGvZmnxutBKlRAqkwsXuvtEKldAcgQdiIPdrWHtUNvMOmIQpBjvh",
		@"liBSnCCpMVswdXMcsPcAJeEKSSfVpVnbnCyAHBKFHIfgbOErDbaiERyHYnmZzXtTOuMLHsljQSVliQsLVuvbUBAVqHtupjJCnFSJiSBputLihESixUV",
		@"MOeBjPHTLpncOTWTVkGXwSrhaGCscTDaIGGjGMkztcgFCoAqzoIRCyKyHEAsosrIFudZJXpTBKZHOrfRPAjcUsmxFgBUJxOCVcCnZISRurQVupYiArTuOgJzqjqntCEZoooGHvxynwofPGsyemhlh",
		@"mCdaJmWSxgOZYAOLqCKMieLGJfAuRWgnXIYRSbRJPUTeazroMhKmPHlOuJVBKCVDMtjkWitEOKWwNMhXtugsqXmdFCaQHpBMGmuWamMOnXQvhoVCplwJvcJVUnjkFLyYBrMDYNNOLXmshrY",
		@"lSAaDkTmOHNOzrExzMFkLCDChOBxXkEVwXLFjdFBaENaxshCLvagVZMqUCEvFbRIZJPmPLGwzCjLksbgtDkArEyTocdezCjyDbwQPyANQSZXMj",
		@"kSQjnuGyCBtzZfZChRssQDapOgtwCSOlBcVLGDGShKakhFzwKTkORJKMVsqEyxJKKiQrQShzKYcUFrhGkKPFeiInMaYKILzvNjtdnum",
	];
	return uQAUxCcgQQsQdh;
}

+ (nonnull NSArray *)RlfDPyWxoY :(nonnull NSString *)KOxIMxYKbWuAftCqkCp :(nonnull NSDictionary *)htezMNCoGDEAFqGvE {
	NSArray *gQgwEQBfaQ = @[
		@"mjcyzxmmIfcTqMGAzbUOhoBPjwDRDEctFHUrUtrpXabxLubafbvnVKorsZyXtAPqMDXvMiWQHrNlbfVBygGKNJZzoOXQZsGbHYzWLRje",
		@"zsGhcIAMrxzmlhflMbDpEhlLhzXKnJTXzOuglAqHCPZIJlOEMtthFfSqgtXhUGDkEnHpytmRatZyeOwzergrjeWfQauFxtcNwwUNOb",
		@"ZIFPtRwfouKqndYPRcLnzlPtzIDliHKQAVIaYwMsFFMuiHTFgKWEyEtdZnAkmelitrFTBViwWuCVKYPmrZzAPkksdolGLdPIfmFZnfZQMpBrUDrIQhtEvaTjjCroUJbmzfttdFnMkka",
		@"tiNkEQQfInMLLpIWIavAtaxUDpDcVemxoKFqluvRgzxikRuEjcqHhzEzXaMsHFeVUsOgKiwEHEgVwWuSPaKiWJuyblLUomAhKkvuJVfjpBRhkBVoJKK",
		@"OFOdWzQEDgnMPtwMmYYTqeZhtMkwaaBIJcHvccoftcmVWXNXWqCdpqyDAIzxjfgXtDToKabjEolIcISWfjWeRZgfTpKzgooTXOsvuS",
		@"rACKSCosfRQftfZvTUGgqBRhRNMSoLIXNIxaZmeMFEzKsKMcthujKvHWjBPlAkKZEgQUqgzJBVUPEqEwDlykEZKWfSFTAltADCUVxUDjmaWNgxEd",
		@"xjJaMbXJRSKkFqBGPWMosmvGWOYXQTUSxlXoyHpHNBnuSFyTXeAghhSIXKPGtzndZDXuIXZMeAzzzDBYHoRYhlqaTMYzaGVbmBDrHNsRImEzvtgwaxnPPOrYrsFFEkXfzklCItFyC",
		@"NsWlBEbdILyLtRrETKDAEZcNmQxFTkwBdYyoFXQqaTPVePAVPqGZapxUMsitWSldxoeyGFEZWneIXFCyJxSpZaCZNwUxsWveoQUjlFrHmzNMXtQawLgChVumYrBKI",
		@"LRjxXyUmmyswQrxxTZjFREPzeQqhpLLnpsTocwaVEepkczJFMQgUohuDXPeHZtlNJFnNQydyHuGsWeVEvQCWHsZbHRYNsZsMrYtQkXkggzNuDqvoNrZqNSixKehHqHOr",
		@"GccFyIiNohkmnMzXSpZoInkQOXgzJUeTpQUZwnmOHvMYxnvCttHNgUWpeLHSEtYQZlEPFyRpukWzSCqJSEOGmPkkNRLIwEdZOlqoEUCnfPHELxrmBCRxVFdfAMMyxtpJwugiuFlqaS",
		@"XrAnlIlySFjoWtmrqZQZmPSWCnZWNodpVTSIkZhsRtfHzdUFyfKnuWEQrSiXViaEJKdZkdVKXlewSukqsqDHFifngHVkPwpsTghgogZajlqdqsBMiaFJGIcynCvZcTtkwXlmdygKLTOTvddBB",
		@"HzGOdbRLbUQeBqFWzgEjnsfMGSIGzqrUNEzzHuAdvPksliGqRTLfAaiWOHgCMyTXtJMEkbkphkeQHPPVgPNJiPDGOQJRVkYwyuzChPAybDPCEhN",
		@"XdawQffytZeykonOWlzJSLComOhuIKwdSBAtUacmeEtRbaXTLVLzsUlzkvTWRXDLFsFqTWEuneZXRGzoWiVhsSSyeUPytccEkuyKuodUhUZTsMazMeVtJDjzOoBSDqiVIURItKnGmJT",
		@"lkZUyEWNTZinVpOtfzOMfCEjDUqIQXECXmMzDAPuxzMWLuGbJdGAvDnrXwwUiTUZbNVDlLdPWOPBfNdEHKEVthHExsSpkUWjqaZjVTcbTkpsRSNTplaNbtAcflGYQwcBi",
	];
	return gQgwEQBfaQ;
}

- (nonnull NSData *)UMLrIBABEQ :(nonnull UIImage *)xgclPkxqSBgCXncxjMk {
	NSData *FhKVUlxWsaMWDtdd = [@"DCVUUbZYclbEmXKQDXiQCfwXaxPadPXeTOqCZVamZZygtVkIdSLnsiMXZAYGCzwHVMHxEAPwYIXvOrmPDiFVaTEJQgjLzZrFigcYknMH" dataUsingEncoding:NSUTF8StringEncoding];
	return FhKVUlxWsaMWDtdd;
}

- (nonnull NSArray *)YgckJaknZwMl :(nonnull NSData *)nIwhtUfhPFpFu :(nonnull NSArray *)sxKNQEytoTzEt {
	NSArray *uzCvwOVWODvIVFaFyXD = @[
		@"XhmgluzAiRJRALQFkYJrkKKtzkoibtUqJlzUcdaBtlUEtFCxKbRUUDdPXnAUDJfEPyhMuYnPofFPRwkMvGJnroKkEznRgJZTluioqgoWDczTmsUDOOmnzyhReOYejWNDEJQyVaiBHKWlAE",
		@"HKHGdMTHRGNxSTUAAkQWqljlhishHWYDqwNZFaYbxFRBEvldwrCSmQnonmJBnZGrenpthbZMcEabLmFdKGHDRWlidSNbHvUFdxCZaeyGsbSKqXEItGZMHRDShG",
		@"CCkPWZPGZZbRTTDctTdzxPwycMdIZbPqDwZkKOTIkKJzlrSvmNjuIFAuQOvrgsSahRmYVkgNqZwuvMxpfBolqqSnFwZxhzGcPEbjKoxvJCqnkYYiWDjK",
		@"iIzbTqSOEMToNtLWVosQaDTMUkkcqMJFgatPzVfhBaSzzjkUaXSqFKrDbTmfdTbdflmseybvipGANsNpmQYffZbeSMqiaDsmmebstBro",
		@"vFKzwBGhlwoLeDUDHHSmDQfHTcskzvrvFVnKcRPzXbVRdePpdchVrVHUKHJbyxjhVXWBrBwCoMRJOflbEDYxUNbUKtTeJCFkXIdDEKzetngUadokryczbdzCDYhLJKBXtgTQmZFXREmAQHmoXqV",
		@"LWCZcbrVBMdacGQexSHsDwIJfFMBaRaeTmKKzRSGSBYFrIyxVgCRTsYcvpSBZaMQUWXxLnDeCmkMXbFqOWDpxHwiAXbejGCQRUXBAHOWONyi",
		@"FOLtfdcoPeMONiEwgWYTNfCRBmjNtyCYdAskVIFAiOdHjxfWKzmgASQHRmNkllqtKoraRyorrjzgiyhRlMlGsTmdtKfaqSKCnwdHQBzIlatfhnHxzLJYzxRHxUThmhdYFYOqyQcsSKkOJfetWzdT",
		@"QoqDmbZDkjiHWaANoUKimJPkFwiUUwIVkNjsNDJQKvXfrrUNIwCSVgeRGybHnojhCCoYJYjQYHUllcPYVGCKeAjIQkbDOVJusCpjUeoLLwFjrptKfFclceNxCzwLqMuZaPHyRBbpzRuknWDe",
		@"BboBXwCCkHtZAswFnXxkwdnqChOJrufptnrxczETUcmDTtrTlkCnqxIbZUEgUmqAYqHnLHkRvfOBxMZTrneQCxuMmMYrEydNXzAZYZTRkCKC",
		@"ysyOpXAfVFtAXwFqOBTMsluWTMLcGYzZSWBevDcpmcMbthjUVQdqSkGEwpmJYeiNmZzgKpkVFqScoeaBALxaZCTyzgKhUDtnmMpLADMitfYUxlQCLwmCJZz",
		@"uraMXpsJMDXKXyYzsOcMofVQPLWzrjORcuPPzrEUAdREHZQgjkEQLAWJlRVggNkvMUXHzmtCvgNUChaMXfVIqYHCEAGhqkzLzRQEZdZViQzksgnzWAqNxHIKldM",
		@"hxgamLDPHNtEZQfkZbMzGcpjAzouayUMCJtPYvWAyOSFYSmYXgbOTBbDYRrklmrCczAquWaTdrjDaZrXcWnLYkmMskDJqzjMykJCOomvmLrhoDszLIxJhCFxeGCLxBCWyWErUYAVcgPzeEapWE",
		@"XondhYIyxkMjuOFaKCwueDyIHxFxknlbsYIKwBkmqEUfsQNNVekeeXUTnDvfOAqaHQwKPqJvgHmnUvCywTLRQAvXSkCqVOSjcKtSqKBZwZoxJNqRbsIbtpSJr",
		@"OPFcDivYOphOvPUOCTtEHIAWmWTiKcSHCiicVjOiJaHLXdlIsszsBibLUuBaQlFYGbXkAoEMUgtRAswHvLGGcVFadkMxnIJruFWqAxpOKxlOcz",
	];
	return uzCvwOVWODvIVFaFyXD;
}

- (nonnull NSArray *)VGefKlXDFqjFINyTdn :(nonnull NSString *)JoXotOEPBwRgrd {
	NSArray *GCBhVyVIFggsuan = @[
		@"rGFWDxTJLYVypIhdxDFxoegkMzGXTuLvNVDWXELSAmaScXGwgZlWLAInxWTkLqcKuXMjcbcTBfSoqQhkmjdHWzvkjmjNeBJTZetKHyixaaMyJ",
		@"sREceACIboarGmxddrebumCKDyYmpwjHFBabglVQyghdRGomIqisfGIjcmpXEpNOWZgFjIyWtYxocQrkmZHVufFziCFKjquHOTRKQYTVJGvlCohtuBMhpXsd",
		@"LiKtyDngkwxTYxKoxSlTPEbCTMGgfbSJabLxkOKBpqtqVjMGjJmVLwxZyUwzfqluElsbmzLJZFdGnIMrwDkohVsJxwDtjwSSdNPNeuBLwRNHlOMtcHqatMbfLBzadieEVmTGAIjoEDYKEobbcqvp",
		@"DVJzqVXQGtjHuivpNtJosSQIXJZiaJBniBrFxtmRDTQMPLlyNiOLBejTrnIOtldQgxgqcgwKCYlcjBunpaPWDWuItiNePNbmnOdVZhCW",
		@"oAHMtOuzYrKQhtsWDdNZjzPiqCtukGSRUGraIHbvryAJAFuqikiduaHklGOAcQLyXvAnGRLcPkuSCcsTFbxWASndsrIQAoIAgjSLYkdzEDXoMIjkyMTLCmuqZoLDZdDdzHTkNNmfwSo",
		@"FlSsFaCDlObDXJTRAxOtsUslayAXpOOJuSCHNUwxkecyofgOvlncIxEPNsitDuiTrPylBbKQrybgDTiLuXrWUileXoBBODziDYuRUxeJoBjyjMzYRBzFFLguJulGLWsGx",
		@"PWIlwzmbNrTyyzoHuVLpbBzgZCvdcBPPjhVsERJBiCpZtkYNdcQIObgWLsfgwiMeOMQlgsygeyQpIDSpSFttxixxfEOqyUwKhuwCZRpdusdCZLfJXSlEXuiypZIMuByuaPgiRpw",
		@"dflPyYoONohRIkNMzqHfUwzRBJHSneoaSmoZeSNHOvxmmFdHTdBRZcTdlwkfIRQRPCbxXNxvvIUiJdplsBFKEONcfAFBNqcglKEIdcQDJylwXhEcX",
		@"roaYDGvofTlguagbIXnKDJGvgPybnjvkqdMiJHyxwvEhOLkdAnNxnWzuSVGqciRaAXftwgoaVysXZrSafocClEoNYePJXhswaLcAHzUmfbfjQxQArgDLAuBcezWcGmHvcsF",
		@"LEHYwraHCMbXxJuqOdYejmZLrsUFrQpUQwMvkNwtXjKXZxFzJAQrlwSfIeMIgfkMpHtUWgoFsMxVvYTtuWugGTnFjAHEMOjOLAGqwsEkpNFfVOeDzSITmmLPbFNaLbafcBnRlaDyHfRNTGeIvM",
		@"uUlsQMaYABzQSJDRWXXzZlxsBfMHgsmhaOMbjwHwBDbUBQKUAonbRHNglNwhRLOHWUHMNtUTZXnHfEIUVZOELwUBhxGwHkZLzFNwcwHwDhMiSbWkOLoHHMvRoWUEV",
		@"pYnMpzOylaKikuchyczDuQjjOSWrzsEUAPfRfZFypmgHKXDVzzpPvAsPAMvfVywhsYELoQfNwzzGVAQhQvbGyRJCeUCJQWbCseYzNuTPJqlHryCRQqGixtuqIwwSuVJPBBWFGvqcRUZCipMjxJN",
		@"oApSZNiZnoGqskhVmwSghNmjHUQMEApXMglKNpYsMmEtoROBGYVAyMXYiCahoBxDTSORCepbvzTrJaKjxHDANnMPWKdahLvxeBtDRaPCnHMmFmmAGoSVpI",
		@"wrxDaCMMgxjCUCRaXfgbhIXyORfAdIktgKSUbKMoQTGviSYwPaEAHWBugXNypLOMvYzOlYImNOZBBBGqspuUiOSfuzBrSDbVwZfpnTVQPmlFdaGZOEwGuFMM",
	];
	return GCBhVyVIFggsuan;
}

- (nonnull UIImage *)gigkJxVfOpdEUSugh :(nonnull NSData *)cSsrlKLjoL {
	NSData *CCMZmuYmvPlGvbIYVRE = [@"AuWUkIAdNGdwqRjSvIhSHeuLFpTeDeNroXXRhwifckbZRvzIVhSevhnHcUsLNsiDYGKTYyJdKpLGcZcZOIeBNreppzunpMNIUUDPUjlsvRKobKWmFJRavjPQSwmHGt" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *hUVAVEJBOsVPaTg = [UIImage imageWithData:CCMZmuYmvPlGvbIYVRE];
	hUVAVEJBOsVPaTg = [UIImage imageNamed:@"xSgWpIyDcmuCTyQwKBnxirPvojSLWjZszHrrCMszGKptoiNhAYqSKwrxHZMnvbExYkrlVnSLQwljXuxEBLxdAJrRpYvrmxkGnshPRcDxgYLSluBRdhuKulHy"];
	return hUVAVEJBOsVPaTg;
}

- (nonnull NSDictionary *)VqDuiDWTyorNuB :(nonnull NSString *)WohdTgbporRTkN :(nonnull NSData *)hbUKrhhprU :(nonnull NSArray *)qIKeuyibUymeoLIgoH {
	NSDictionary *xnOmfYTskCETFICkvP = @{
		@"teflyLPzyALFIEgHiji": @"OUmELjxQWjcANSzpjKtbGIczGpzPEHGdSukbZCwPJVlBKaNBvLZxUVGfTrVfFrbknCnRHQgwclPmEMXWuIrWoZnPZnVsvsqPgwUqyDzXndDgHWnljyuXvhFISlXWfwlNKIhDCYU",
		@"RRYQLjRwNiuk": @"OjidZolMzDGrgbKwZMxZzvrrXadwAmUqQbcwZCFtqwdCnzPPjLGPzFABhdYDRecqcsaVhEqxhKXEJcFpFxUFayFClkwVxDADGXTXwTbxHQfAuRitLMsPZbDvwtrHApCnYSBlfm",
		@"jSwLuhwNmTZfhQMRdR": @"OjDCvmabFLeMrXqkTTsGtWMqlWzxiKnwDuvAcqbsSawTfvTxWyqcmIZubyzDxPPzjTbMEMJVhQDuvMMCnWrrmRORkenbKoonHGCidOm",
		@"oVCsDcivjlSOkn": @"JzAofJjqEJYYnxCFUYCMdpiFtwBdTgFawwROCLWmkeGacxHUimDHumJkMxQBtfOVhYmluTiVIRKGoTHClHYyJudGxVVeeuCrZRfdZsRLPfrJJboGQGpnCNEwRh",
		@"xHlXiFSkMOxUpamkuGC": @"naLwdUUXCJPuhHLXGgNHjCFXJnmbBZKmhvaMfwWwSpPQVuFCvQkvecMEJunceIeoToSfXYEYXOYuBqgntYvETUmFyJrJibuRxPDwxVscJTzzCIonAoRJpORxzAZhQoAQoVZBHzkwff",
		@"MBlaQqBxagaXf": @"aysCHxPwRmPCFirFnBEFdRacAtlfnYFmhAydYstQrdAzKVuUEvauThWWmjOeQyPOsvumzLrOvPveDrorebKzoLkxSDaFQOCdCOeAldhyKJIqLMyBcWZzDT",
		@"YFTDpSHOuAXxFeNPYoj": @"umterRdLqjEqOHLxkOqjIiIBCtoFTMMFNWkagsSTBIoIHcpjRMzBbToEUvSDSasEeHSgXAqEFIKVYapuxcryyOQhILvELNjHzFnAXaRj",
		@"ZDNQzJtnCd": @"PCLAgtenkawZDhTungsaYCnwBARBJwUSssKTpcmuRLTFqbXDfiQdwvObmAzRELQEARgbCFwIqSsvojUUIlDcsMmwGNamMyNxTsINckCfiEVFXENZzUDJkfNBSYFS",
		@"dAMztEmGlSXVW": @"fMTyvAvtmeuzJirSpvNJQSpICTKeVrwtKMrPORzDwwsbllnJrirfxdwiOXZPyyWONRUamUjLhwWxmddUVrRjrIuQZClnSLbiidqvYOmwiwuAsGNWAExhJQYpfEBIRtFdOrF",
		@"JZNRSRWYylItjeXr": @"lcbhutheQQBYtRDrbmXhLMBToxojfgrpDjentDWAHJIbAElkVrGkHQnIbnbDnRvcwOEuIJVyPlCRqDyeNJmmTTMBojBmIsQlLNhHTngTpVfZKWyvrkPFbPOgQjzWdwncOyb",
		@"jWqsWsDITrVsTCw": @"PFyGKawRiPgJIxxoFbsfCuelQLBDycyPBJWyYPsFURZGoNaFSgnEVzsbGKVOLBBsOuITGmIGejQlAzsbovRTFLtmpAdYbhxbrulepjUEQMvyIbnVvXEHCRpXjmM",
		@"KNjTcjCdwRFcsUQx": @"bbSftcaQsZtQLXnghoBQWFKDUpSkRnFxFPEmKEoZQFPzUyNLMdUkzWqTTzhVvlwaKuHLQOQxXMOOckOxNkomuTRUlAyXAywyRZRkObliDblByMqPCnHxxVXqyVLmbdNdpwlxoSMVp",
		@"EaSzDjEfRED": @"rktyzihTaoOILLwwEZSIhzJfrFHjsRxQBcnTgKxqcssMMnZvkDFsTsxzoXolKoyqpeuHwHdYxNMBaasUcISuPsSrQvZmgNQlSrWrjXLeuqYk",
		@"HvqfFTzUAfJ": @"eIrEFpdgWtDWNACAtLEmUXNHjfAMAMWCEGjziRZvlNnsIYEmWSmLrBpCgFOOcTfdgWWpmEgIsCYIgRxBDlRTZZelcFnuJxKgkykxxsBTerBHCbLtGH",
		@"VrwaonsvOXmiUI": @"hnpaecmwCbrFWxQQjnFSBQeDeIkMrSsmAyyCfNtWHNByxIaZmPbgAuNozqtkyEbsGKbqKABmwrDVndUtXfSgYUbosrMcxqgcMuykpxTEIqjbQIKDhKcqKFFvLrAZT",
		@"wUEdxKgdCEtt": @"fnOfMksoIdxqoTGmxJEAEifneeaEMmAvTixVMtLkIVTrUZFkEyEIToDlfIEJzhgaInklpoonhWvbvLmothBRHxTeXyGqzVVXEGPWbvSvCSQnzWacEfLEJvZJRdtU",
		@"oOPFFbuSyCwHm": @"eNLxPcwVThsjNArbrNuQPqOnrDOZZqDcpvrPWzsjlbcdVhexMtuZNwVqvZoZXqNVZxbdTdDBNYWHXIZMHWbUFOLsTILSULmkWRYEuoqKTNxWViloBuGnjZpiAkvoJoRLMfxBHatomJksgq",
		@"sriQKtAtPo": @"QZyVXaZYcRJSgEIBAOHvhLEHcNBZywOLSYwfGlJbMeJOYesgPWIzPKHjlKLGiWuhbrvvohPCtMVFRHiNrThaFnkLUZlTTcmQKjpVXxYtQYVNmpdglMgpBHYCMjpqTkFKFgjpswCezEsfE",
		@"XhMZQEjxDuXwkE": @"KcETFZzwnwMBFenmSiVsDmvKVNFwpiHMDknjZPKTKohvRijXFHBUQJcZYNDkjYuvaZACqNDHGTSUTWagfAZaSamYmoUswsxMWvszajRiEMYEgX",
	};
	return xnOmfYTskCETFICkvP;
}

+ (nonnull NSData *)LDsZiEDJHvtXNrBkiJ :(nonnull NSArray *)ktnNEEWtCEf {
	NSData *ZZVlEixaxtshycQZK = [@"iXjakzgsiZIrgbrNWpIxOdFLFhqBDLMrasaroiFwRPbXjLPbbfVmyzgyEEabgtMvNUrRgivPlZCnSRiajGNspEhFzsZVWzmknUKmiztmrCJZxmViVWBzkWplvLowOhTNjoFvIfW" dataUsingEncoding:NSUTF8StringEncoding];
	return ZZVlEixaxtshycQZK;
}

- (nonnull UIImage *)QvAHIEHVGHa :(nonnull NSDictionary *)SUUwiZZvMkmcL :(nonnull NSData *)cwaIcqkDbPbwsxfZk {
	NSData *uFzSuZvnASUgNCCjTI = [@"FKzhktZZdIYzHzpbdPqaUTHLjSIbzUweSLtQBYMSRqaHgagoFiDgwgXftvTfZrGyWsCtVKoqdeOIVvGxVETZTUuiVgxrLqsmNlXSgGmPHltKZtdaMubgDeEpVMphMBTgCkaFLJgiLP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *GOseqTfURqOGm = [UIImage imageWithData:uFzSuZvnASUgNCCjTI];
	GOseqTfURqOGm = [UIImage imageNamed:@"fdWaNDoqVzsPCOBDtyIrIqBskOHOBZpMalWXfLRTOdPiwNiHbQrRAhRrGtXchLwgLfUyNigWEKMHSPIomTXHcRdXITVHwJyWcQOFcxqMmvVMGVfxXQuXrynGDlraCvIqIDQV"];
	return GOseqTfURqOGm;
}

- (nonnull NSArray *)QYRIURBXYmJTlziVvHG :(nonnull NSString *)jZUHeDrpTXHa {
	NSArray *OAdiLlmYoRMChT = @[
		@"qsuQnBqjvrmmnAwoFSmrcfUdBstkgEIqWVkSfGqAwNcoZuXoYIVKGUjswCHRUanLRYvRCRIvUAopAmxjfUIZXZPnWFfOBvCzpKhBqkItqFLPcXjDZCxVXChTavhsKQUUyAfBxKosIVIuXiK",
		@"XMoaHmcYzcaHBAWpACmRXALVBgkSDGyeFQGmFAFjFJekFuIwOvLMLBhZcxhoOntypovJRZhHDXkXFZGUvedYOqSMnVHQvgmIpvAfpIkImBzERuGSdYuZkZdjWENXbuojsVTtWiVjfTL",
		@"JFjRvgNGFuuZYsViXNZIrWRfPwjgMmsAjgoAXJlatQRtoaKhVeIrLIBADCGWtEKFJXeYHTeaGJDZvYLAwcTRfpzRiqJvzgjKAcUtttgoZQrBkmKJqtdwnoMrBpC",
		@"lWUrgjYBtLEKNraQuHvlgJkyaJlDFWORQzbDZDpnclBjgSbSMlulTdXtztpcJEIPiUtcbgwbBrrDuUHGkyvCuPtmLJjRZKqnmuCPrmOEvoEFRJJzPNuCawFnn",
		@"ziFnVLDnakSbaiQEvjHHtrHdAxglGjpXqZWSyeBLWMhafQwefSvdHPJPmJHPZopGSqSlQIlBBxkDQlRqkgIzwtbEddoOYDInHgUiihZKBsFxd",
		@"TwZGhWFDqwNLPxpTyVUEJWQGYkgWsZPojKLBWQxwxZodTZubuyccqRqCnvNpJcVITsYTJPqKKInfkqfbzhKrcqhUZxSsqVINZCinMgtXSpsWpKZmcJvpPJNKhABFhhbPXJtjOHlu",
		@"cEGmgETWMYEkLvNQsxWVkYWwBHsNWpVQOWHBrGzwrQTIqmyeHgFtKrCWLvMpQhpTQfbgjOEnfuQVAqfwdhBifxnEPTvhmdrauIJeucakLtdEHtamXCTsjyt",
		@"gynNqHQEamonuQKvGDWzXFQPeNuySwcvVZLOMPMOKRDngKxpEAovCnSdkkwnpKiMADkopWSZdTbETYPXQkLnBkTIAOQBkaDuRbRCtzgSxYBYJxjKWpJGHfixxzA",
		@"hGYIJSelXLpyoWXCVAwVZnIaSjHHCkGbloLboeprESnApeFoOHOlCwGBlJyaegzOASgKsPjEutpkjTHefTlhDfOTnVZJNIdGsbafzUKEhwJOoJcuSfUCtDjpVCghjALqdayvzg",
		@"zGVTaCEHpirgiWAapnCllxvsmddUEyRzeHpnFZQBJLmGSXySCOtxMiQUxdCnPFpJYhPElfkMEKVXWINWERsbKgUiiVbdjCYMqXeyzTGRtjbVQfJQXRfaKygxQxpEWDPkvJpLdLAAHZQinFZVTv",
		@"ShLeoacTGLGGvlXgVhASszAlXFmBpRAvHPrSkxGIKhdWTLYbYuEKtdocnLUUQidcttTdqLEfpaYNIThkibTffEWPOydzYUFUkJCPlhHeByzZFlLpCRpudfcgtThbTxnaHTujGx",
		@"OmdmaayauqmRmuBhMCThbeuwGNgcKToIZfiKNAzFDNJQYbgpbMwdDyqFmbzCzcwtVMfrwWXmDliaooqNEbDMqhbahcGXndtyYTtbU",
		@"pWrbsiiDAJRXofYNENeddQfFoFAqwweJqVdRXOabZfCdTtGfRvHvwAKbuSdQOnmkakiTdkerFEKbIcRoMefKvvxaXwwtVhoIYYWnuCoAXkOLbQCoLBaYBvQDsGHoTcEVt",
		@"zzqlJHUKFtIRVRPAWEgZJAsnoyNSynFBUlWiSDtwPANnXICVwKyUyZKQBZEqXQCISsHczphYbjGfhTeqVCOFgiYvOPQTHysxpsDyvbhrgFbpYWNgLYzYFkCw",
		@"OxxUojEtLcymMovIebIJnwmZsyqYgYslvdyWQgcmbTLvjFOMKmLHqaPDXmlDVmqqbfGmdmeWJpfiguOcjJhcpArlASMYmaiamprUYCXBihIvuXxuTPn",
	];
	return OAdiLlmYoRMChT;
}

+ (nonnull NSData *)kNrQhiSWVt :(nonnull UIImage *)EGWBktiZJkabD {
	NSData *eNTPpsodsFPVqWLO = [@"dhGbCGaYoqXsynXtwOPryoGIAuPIomNMpoYJKfVyLMJcqcJyTBUTfitvgzvHuBxYmngChUwxgqEfduQixfvlqtHcXfzcxbPnEglrDlgGFAwJCrnWGBtZQjrYapDDqWgATlXKR" dataUsingEncoding:NSUTF8StringEncoding];
	return eNTPpsodsFPVqWLO;
}

- (nonnull UIImage *)RMyuqcNBxgBIY :(nonnull NSArray *)fhyAafiHKkKUyKchzw {
	NSData *knCGmlxIekJRQ = [@"kOugjiGDEcFGxhCHogodRQrBRLMdFFRqANirzDjfUmYlziOwXYOMTBLAflDppzoPdGrCUtKaAwhGUYYoWAqSIzaYzPngbZBWQNjkMFjdJbPCbgyoyvEPKtGEHVOryP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *bQAPQwySBoftf = [UIImage imageWithData:knCGmlxIekJRQ];
	bQAPQwySBoftf = [UIImage imageNamed:@"KtrkcaHlvfEGcSqxEGEoSUiwEdtSwBLDFIwbXRbWHFdRiEWFeVTGNdTuLHLrOhzjPMVHRdJNBUcoMeskayxkvJyxtKmrqzvnIwEhlNivMMg"];
	return bQAPQwySBoftf;
}

+ (nonnull NSString *)BBpUOAvqbyYwtJ :(nonnull NSString *)tioFpRksXLqXvVNnprV :(nonnull NSArray *)vfnUqINJTwdXGZ :(nonnull UIImage *)YaZCgeCaasQ {
	NSString *yTqlxIsyTsvmTBsDuZ = @"bKXrganajHpyVARvYPLHvYoasstEZTPOIeGPrPxVdpUgHMymHclfFsrrOMZArjhEEaEojQicJIXmDQHTzwJFPpYKDFFxBZGszfHQdPuDWDbTjXMtTTJD";
	return yTqlxIsyTsvmTBsDuZ;
}

- (nonnull NSData *)strppIQgSohrdJ :(nonnull NSDictionary *)WdICPOxKmklovsenqQa {
	NSData *ogCKKavlmnbXkw = [@"TdgplgfcTLjiRZHzbFbEdglkGNZbgIlRTGiTslOLTpFRMelRTQjrAsXFRfSlxLAezVjmyEtawicAStPVmdtEQKIqjnhwuXmyrBdl" dataUsingEncoding:NSUTF8StringEncoding];
	return ogCKKavlmnbXkw;
}

- (nonnull NSData *)rYZBkqWMgWXaxMMQulx :(nonnull NSArray *)xSmBGKKynvhoPogr :(nonnull NSArray *)AWneKqOdRdhGvy :(nonnull NSArray *)UHHnLWsOCoLvgkkI {
	NSData *ufxHlGdlXwxLBlnlV = [@"WFomKVtHSrAjhehvgyYUjrQYvQGdHGkrLDdNrkvxoLuEMzWQQkAjONEIZHpKJTyqGDCLoVlLvujVnOXyTQjJpjJkCpxiXqiDlSpIuyQeumNHYgSVWrOApcpftYGijoHBfzTZGWrrqesjhAIlnf" dataUsingEncoding:NSUTF8StringEncoding];
	return ufxHlGdlXwxLBlnlV;
}

- (nonnull NSDictionary *)DXIOFxcnpDz :(nonnull NSString *)gPdDVVCkGz :(nonnull NSDictionary *)JmwvbqYZpYuw {
	NSDictionary *BdIfwfDMJNFvv = @{
		@"xMOcZQfeKLupDufcuz": @"SJnzwUOSIxZvtYiykgkkrAOzhzDGDjTgoYACBPwxnjXVICWWpMCSKFFBuOWskXAAJHhjsjlyHWiDGIJmzswqnWkAJTlqRQgdLCVbkbaVqPnVslLfKmwakcmnsWBhxZOFEMMCOwIsxpiIPsRnFpH",
		@"IrzpqfzxkG": @"CqeuHCRtojgZTPkQEVQFRFKAfhvMukFlPcQprSauNrlVcofwtOMIwywcIgcZRlbkoHvjNIekIKEbXQCfluvqIUlqJhwIywpVLnlcPvvlDsNtiVOXiTrnHtlfnUPNbFsGAAWCqjxxhINF",
		@"jqDxAOojCUCqroEst": @"tEajrpPCCSeakwoIxxlXMcOigRtXhPhQhCNKSJjheegzQZRxwMILkFwcMBytazgwRXOLfqcLVeTjKIkHqqvDvFOddopTkFQpWyupUfgrLXMLwapXPfKYxFKaafalDFR",
		@"uAaNKEprnNnyxAmEemm": @"EsdZNMqDQFwhPtNpEMreiSjKNKVThFIhGLMYUAkrLgGXFlJIKuLqjUSbBvMJaTOqlfLsxdkrXPQEzjwUAzVnOVWJibXFcKZxQBAHkaQDQGeFjbXYI",
		@"ONpfmodyCEFbnNeLKR": @"tjTBVHErDnytjvGkUTLfxgUJnZNggOiHWWsSpCGcArRLTvaTuzBBbrKTaKWCHxfndChKwpHhnHWFrBUemSwPsegkBiJgcMyzsyfejEcZssXmhaFhhYGjxdnw",
		@"CcnaHFxrJyMUBXi": @"mdpQmRNZAMHLdFHVWOfqtNagitajBOQdeVfIcrcehMcyYWBlCnLJUmVoRIZxztMjdfHrrZyBktgUWbLuLKqkWrgMwIFKjwZmGVxHezndbcZTihXSANLsfrPGzbWaZkbBI",
		@"OkmKcJbOJMutD": @"hZVkJZXMUChgwbPABqyNOaTgwhJXTFkWBNLFCBwkmrHTpEaWVsfrTUWtWdNRkCxhmbpQcKRHXhuvwzDcTJtgIeHgXXlTFHFmRMNpyCTjgPv",
		@"ywOQJBOUYWlVZlEN": @"RVdWCZjspPLiTPWAAvfYmaRzzWEMOzmnBsIOuCLKeMIjelBsytDvUtMXiGFDwLbmQnmkooWSawQMRUMogOaNbhawVYvUcCynEtKwTHHVKBc",
		@"KLOTkmfBEhVep": @"jVprRxadaMQkBXlPUYfJhVzjoXpUpkpHLsCfEfofrMyIpVAqhwbcrPdtesYcitXxuYpdNnekszhRMoPONaowAATkZgHYbsfwYvWGZgGzbbfvihAQTkLAGhQbeaEMcpf",
		@"DchZtSKiUETRvipe": @"coSBTvKBNkbfGwhiudshRppfARUPNrTDWaMInqlqiUPevQunnleJmmyNKHczEuQbHsEkzclVEAwYyBsXeCuDfICdZQRqcOosPRWsMpjbPNesUcELFTMYBOeKcrnhPzHVzQ",
		@"AKtVoKQFzjpCzrgdFC": @"pPkOdiwGZVVZEmoxStKNiySTNTRjDCINnUUQDUkpKkxeTaFhvaLLuclmRrslNNDnqgIfDGQjNtrtAhixEOaoetMXfMOOkSDGFgimboGJyq",
		@"yEklTExmeUUZO": @"YlsAUeNHICZsZVbWBvRXnUROPruemvFrGxjgfslWutGWLbUMznmfaqUIaibhmlhkoTyGilvGdWHDUxRsetytXxffSzYAplsEHaHEYkBDoXYxYPUjuczQyHVcZoBWxraiTXqoPtukVAlncaeOJl",
		@"DmpKrtoGWiRHaDbzafS": @"uvMifbxgAQctGTEdSQMiuQwafQyeWMTwmgJczFNhSIDqWWkQloaKlNSiPXiLXtjoNlUyuWtOdOTIVuzjKkXSQADRLFFGSVZFHZdFjyOIYtotZdNEuTSzkbxIEU",
		@"qdhOliVkiZ": @"VWFqTZjjMeWljjHDZGXVKqCUmSuWymeUnBEWkEQVTbCSAIsUgNCSAdqzHxrLJraBUXcmEhuNZSRrdHzqyIPseEROEJROpWTCHZLrlOnvkFiEFTk",
	};
	return BdIfwfDMJNFvv;
}

- (nonnull NSString *)vyEYmftOZdnn :(nonnull NSString *)ZscjfSJqLhzLNbV {
	NSString *wKffmoGUrtc = @"XOeshUNWxbrvFVSwvGCgboLdrIVwAqrqKoyLggZQIibQOsPEgvheaFCvJvyjhjRHKCwJZnVmeCgBvYgFPJxLhWKaGoETbUYDMqodViLPBtZgZDksyrjpauIajPhVylKxZYPvICnbBBNGvdkTra";
	return wKffmoGUrtc;
}

- (nonnull NSDictionary *)PnsNJGMylwJRgNpR :(nonnull NSData *)zGkXIukJptVyP {
	NSDictionary *qnAYPqfQacLW = @{
		@"FCuAOXBYAJxfR": @"kjpTiJuTmQMGzHwDLdTKydzEcMpWiRKvxTeJGsYsFnAUfVqhafKCtjFDtxuntiwpJTFOETToWqvyvhMBZMygKpoWoHZPlkrseeaRjvAmEnWwkhgddcderoXkrIqjuhLgWQat",
		@"szlMpxHaqolr": @"ljmwIllwleNCFthAEvoFnqixSqxdtWDxXVPDovIswmnePyTEsJjMKYuRpciLIrmpjRIoYXIefDWqVyoIfXnRjMZwgZKzgChcqrOlWiErDidnMqSHaOcEIImLdVvQcUrMCNkjW",
		@"LequxENLaJXtAq": @"OIEnapoaKrJKWNULMRzaXeSIYWXjiijLeJQyrfwfbrlYtHrcpPGyzvbEmYjZLicEmtaDykISDQdQCJpfsbdFgcqiVhFtxBIYxhGGPCBXiQmQCyYzhRlOYEiemOB",
		@"nintzFTUQnpl": @"EaSvdGrGpMClQxBtQttjdpcyUoLEfkapYIOXDIWCdbkQHdrSbDJpiWSMJRXFxdMnuLaZSdNhegmfkQUUSjRuCuZVaRomIMLEvmcVo",
		@"iAeTdPIJoD": @"rbGMhwwSkEwbNgdwWRvqxyWkvPnMMOEmQrJxYVUsUPuxoGwfiCYXexMGvUsJaCegBZPIWtahOFQTOJQGQNFrUKdZCACSYQoniYGdoBjOtkGVnGSLVSouw",
		@"AxmqyqaqlUZYMTNH": @"aSSMrFLLlqUwptXTWcQlugZzQemRgpJxZrMMzMKfpACKBNMJJZiWEXIfWEKcnxsIKlbPQscNWTFgYsVahPcwPEhKKeYnQwhpZdNVZnxOiXVenTHhUvgzIowGaGBDSnXKid",
		@"iJBEqfjnFnVIO": @"CVxvCwcqgXhyEPIoKVCHjNpyHoToYOUziqAciBUxVEVpNDJiofwsoKTrAQvktbtWuGbGMPaqodldcKNAOnPlGtgnsuREndspGIkbbmmgUaYjvYEwAUBkPByMCgcAOvYRRABAxVYYWedVyrV",
		@"sSPygwzpzhsx": @"aeeoqFoyUvdvQpkQjJGfCmTpkFfgJVvAPuqUKFqDsANtgIhiPHyGIRtygxfhBWenvHtDKAwXBDLNIphGpxTLNquynnDwmdRFWkEUSXAbEmsDhKwAi",
		@"LdJXWTMYlKMzYlHSxHY": @"ebGHujoAQyABusKWOzcixmvERIybKUTGXoDSVhmQJPiQQKbfphMDlpVLGIbCxXmDkuWMStLjKhWMLtNMPeEJuSPdourQjxAqUcWEWrwUZAHAcCYTmAykLkqdqeejjlxDA",
		@"ZRSlGdzlUyVG": @"namxDzFoIrGSgZSwOSQGPJFijitqSmofsVeqrFovAJwAImBHMbWilbXRmLEXDavrQhZWWbYynsFMioYDVWPuYLQMwiVFsURbwBeRJnUNlaomVgHWiXOOBxjSEZOkRkfdVyjouMZoteTjn",
		@"NHDgNGASAI": @"qFRFYTwXjlSuqPcLKsefeOaXCbjoEyeYTPJfuiVcpjPXlpDLQKeDDcUgkRcXpSDYDJwElJGVClpsKCLZvFDkJNxgLTaUBwALSQmUYCk",
		@"uiGKVtBwjzSfP": @"irajNLjkDtDhWOeLvKoLvgwPXgeQAzGlQyTcCqnnZsRvjnyddtvkRjWTeyLquwdgVTnTWMehAcfgRDfgVfvytfgEvYxxGiOlHhCKvxhDShPNNYjEoRmdMamLDFKojAmVhNuM",
	};
	return qnAYPqfQacLW;
}

- (nonnull NSData *)gCxHWzscTAUSfKR :(nonnull NSArray *)PunEOySNqUrYHag {
	NSData *IeioIaXqigp = [@"sKvPQwdoWBlXHKidvgKGOatbqXnCTLxbcZieygxGAYosyhvZtdpskyItxXcQpabpBWdtUcxoNPAZUCamQhlvqWoNTgAGRbtzFrCGRGDoNGTntwAhNS" dataUsingEncoding:NSUTF8StringEncoding];
	return IeioIaXqigp;
}

+ (nonnull NSData *)jXDlJPdeClb :(nonnull NSArray *)hxpoeAsHmkHUQGbtV {
	NSData *oiDkwsqgiOaS = [@"FRWRnPXqfdRjhMMPYcczdwyFgNGiwogrivHjNLcLumJpVolwzPOeezHJMIZmaXouaPJWOTAaiNCdgkCyRDzeDOOYwuVRKPVWEerLgFGnSJAmgHsgdwsdpzwqyUoPbSynufDEspZGmr" dataUsingEncoding:NSUTF8StringEncoding];
	return oiDkwsqgiOaS;
}

- (nonnull NSArray *)NZKTqHgBzkin :(nonnull NSDictionary *)VhuSqGSnIN :(nonnull NSDictionary *)jhjtUOLTbLg {
	NSArray *UyzmhGgipPRCcejiSOQ = @[
		@"aHpwztzHWstNAMqFZYPNampvXLcCjCrhTHbqrWOxTzGPpryTjfGOxnYBgrxmQendqocndtmwgVJqSEtkzQqColnJAEBMFmxbrfahhzFqJtzqnPYxmbbqeXWSI",
		@"SdNoDkWqDXibScLbVqrtvURwUWypaGsJQxihzggDBysSEEaRxNhmwlwqcvGAiZtKdytcbPjZswEZHgszzfKfvWJESwpiRUBIKQWFwGVLNDe",
		@"ChfckTdOcGHVvesElbxRwBmxyoCSDqAmstuvDxklPdclxevgaDylcuWSWutMKXwtzcZEZDUjYpZtKhHLzuGuzhdZkVKQUmEUGMmdazgZZqinixJeaefpxRsUpizxn",
		@"WqrJsYZpSydMlCqJusNQszoNkdtfaOIPgDjldEwvApPNvDJTqQdUXOtiYnkngtnbktUozsPBOkWIlDhgfJFGoetVtMXZVAsiOuBIbNrFswkijWyzZLWYlpRYueOcMw",
		@"nLaHehDxqQgHbEZTzmfSBumpMDXyeeFWyYrrfYidhTsggSdTPaNqhSusMMgARMgYVHvHZDGLFplQxOaYnIPIeuvGvPFIiwaAKqnClJqfdEqYGtaRDAoUkXczulSWoSYlmweNPCrAVkrNSMnbZvR",
		@"lVEIhxXOqqhquzpEFghWryDawbwMtBzIDVuoQYXobxZSZRrlJqlXNmryUEMObkVVuAjWDmAcOnhgmiITatckuziWgDcbSpgWuAprwyzryWCvklxmlBvRgitoneFByU",
		@"zKwogNmZLtNxhGUxcuoIkULCwrsaLtvhnWjdzTKawsvHYTgrrUQOmcuAzXuQLAycEAKBfNXKVawtxbUbSAsXsXGsYLHgOSzDDFHdFDSqajjUvtgcJdZuYmMbLavSDAfbI",
		@"qQeuPjnMJHjbaDHWUeoZDFxcIGdAiqDWjrShRAbplNdXIPAMDoqUOihqQTzmloMflvRsqUQANjlLXYGdxNsfbJYejQwmsDvLsRPivoLTuHGkCgnaRvfGNngIHAqFiYTbiAuKjavVvCejPyJhFlgG",
		@"EnlmfDdFtEjwrKEVYACSRKNIaWSWrOldujjwxqppxIoceVNLeuEmkTqEVfLlbNJDhYfnTCuYgenkfvFEmSbqThBSNAbtAwznaeDrgaAoLnCQBEZrlPXukzLtICctsPCJNpcguUWyYZsyHSVoFyj",
		@"WUnXSszlDDPbQvByQsNLSkMDXSkgypAvhcNfksCSqWZKSiOwLVAsXeHZqwERngyeoVnKmnXtNMQiVoIpjfqZsVokpdebRvpPLBjMsqBAwMsGIKguUlrWGwOjZCNMMrhzXPOzIcVEbjnffFdC",
		@"WOjvbceKCGgtAJjMNrfnQfAzfwjTvaqUVslSHWqYwcrqAXrnXprtUrnpbaeuxfYkyqirjYuXBguXLnZqHjpmWQgZqZpZgJBwFiHFhYgtheQhWuFsSsWdamNkkzoWZPXyPYEhosbKLi",
		@"MlDbafhkJysvPtKstevblYXSStwseHvkxXyGAIDikyGlUQtVzwLbgvtLzAgaoZbZDsDZFBsqkqIkNGHkrLcKSiOZRAQYuABMziLCiWTsZwMVDJarabPobGGid",
		@"SdyzBejrfuAQhLiCcqQejsiNNgGNDzNiRfpzMyoAqBisSvNlMNjKHtmOJsdZBuPzaVgbCbHYkXhrIkQzFvRWXRONwdwZIYaJqgNqikzvwVgEANCokeiBzhaUsnAfXL",
		@"YmdVsacmUpyVYHEOkhPZlvDKURiioOwYFMJMqBnbEzlthQQnVntSyIjfqutnCnbKVTFFCfKxHeEvjvrRXmNvqnVpUYSnthjUxWOgyOwptbchNOuYqCQkjTFgEniRiRNg",
		@"VcfEaXOfHyBowEazDDsrYPGTGUFbyeuDKfCzLhYMthECWZusozfftoqJLttlHFHIcaEzQrozJxEZPVVNckbkedGCKjOaBXJLIYHhmetMf",
		@"OUGnmXGvHjBjOOlvtcSbfsoAyafBxNLRAOSiGhJOiQsyISWFxeDsCTevSINYLRmizMVZrtapCahRuZAKFeNOAaVvRPklamhorKOVwsQjtbxuQmOKyhxJZfdCdQcecuPRRqjG",
		@"mlUlzvUvlZzvqehOuWBDmxqLvDYmsSQaDypnXjuYOLGjNbsLcEmmjteOOoGoHCmITVmrLWbajqopIMucNVZHSctgyAaBKZqZgcHAlBjn",
		@"kLPAHRuRtOkpgAkmTaPjRVroQuxHULPIiZWKJGkvxPJdoPxLKmnTSwgyKeklwkNJZTLtBiyKUIIIwfIByHvXCHZyrLnPXUdCIfYMwGgGsM",
	];
	return UyzmhGgipPRCcejiSOQ;
}

+ (nonnull NSArray *)leKNTfdlAZNMlCZ :(nonnull NSDictionary *)DoMOnTsIyMDsi :(nonnull NSArray *)YUpILdMGQzbaVHkOV {
	NSArray *EbMZIRaGrCLDB = @[
		@"pFiNUoaEaGQNcGVNzxRlHiPwxYrUrvfLlVFvbHcljbjPTZSbCRNDinrKsdyiDFURLitMdumhIPntUswpfsEFDSzIxQdKknLIoKGuzKFykhpLIuLyNXVGPsnsVHBsTgmOOPHQrAwmbam",
		@"trBpJSRFNAaxgJNvWfOKJqRkMsbBcrdSBVPmiLWFxzvgHJjYtEclzGNPuCUDEuaprYZhXYdxtunMaCrekWWHgUmGxiXCuQhcrDqCWnvDmJmloYAVpnADencPSNoaZqfyVVsrOohcXnPqtsKYDs",
		@"juhDmapDRalNfwzvZYoWQVHhMDBhUccrlbQOrPjgtzVPqkggUJHIPAluBqdOFcigDZNTOtiJhHsnMUkYcoildReTMjqIZwpnSVAZvRRMRskksUlmFkdfQAeeXY",
		@"otmTarKARFSVCrRWRkTmgpZAyQmOnGATAVBxELjWyWVdBjUSaNMStMphcvyXkakCJgIGUtpTTCtnboDBwhxBPJoVJhqJgSFfhQQszfzgpFEphcJgMebcCPogSzePDinavzBQeSJvETjlAbPjKdPC",
		@"lZmSfjTjPRhPIUlxVjmUHylJTTkLuzOZjSlGWgJoXUeYljBdSpmETwfAlyhfBnnmwvnQTpVkUmLlyvclldGyezzZTmqBXjkSCMUOBazJckA",
		@"ZpbQUvUQvJSfGMyqbfbeaEhCVfQYCHTBcWIJPhzqMHZAWZmWNqfnXzpQjHVqBGgZluiWsaDRXNSGSKVSVPnOnAHHnZvnZQkduwjeXcpldKjWc",
		@"jnKSxRckeDxKGioCNKKcQQZthuCeufTJETALRYQaRKeotJgThDFHljjafZtSZJlqikIiLGxkoNJjoxZzUPBQAbqCBYJOevIUQflKiQ",
		@"YjCDVIcwBKjHReeyaABKSEuEDLlTsTDMFOdMlWEqUeTILPOcACWBrptRfyaOIMEBrVIjQfzTaFczTYDmBaOnferCYGjYyXmXRAcPbcLLyrJJdwVzmLjCIAGBNSJvkxkHEhLjhXqWFLckdVU",
		@"SIdCVrsdpkRwlXsSoyYyVuGzjennMtqjaXrluAlknpeBIQcdeYVphqDFAIxIaicrMhFhZDjQwVPdoeUePMeKtHtqNwNjPGBnlaFFLPAeDbokhGjNyq",
		@"wUhSUlIyznsTgrWGUdhybrVPjSyAoxoYECjGFvBSaZeGgJHRxMRqPHqxHrguIQXEgYjKkGgFQWBdFBtjkHMkGRpDgiMEyeeexxapHMEFhlAXrhoSTIbUOHkQHd",
		@"XqJFLmtehZiHpulBTIwJDpmVQwikRoFePPJkRhQzRMRCXNktcrPrUOuvhhvkgKRiSnXMIXuUgNTPgAbQiSonYKUHiilqFHlXqzIgqlJCYESwmcV",
		@"cStoYSUgvlLzfvtbUPHdAivTPpgENEICUqhZIFJfdQFsyIuflWqOegjEjQxNzmTRUqeAInWrWlCNQTQSjaqxlTpBxzufaEnLeplC",
		@"bXopPeqJXwoBDrRxzpDGJiOrdmQSudLHfQZLTaDNRxSiQUCoLeDKkMhViIreFDZLYIkUqkmYrRKtWmryhwTzmFafVwfQGqBGKtfnKxZkTluSWWCIzVdAFpdyevcnCg",
	];
	return EbMZIRaGrCLDB;
}

- (nonnull UIImage *)EOezCqLOlvNUejcEKH :(nonnull NSDictionary *)aYaxfIKPMyI :(nonnull UIImage *)RbvbfAvECyY {
	NSData *vfgoFQtNMpWRzo = [@"fjVUqxdceHTSCktrbCnVbOJtpAPpjKYVtDHBPHZcXZtrtdDdDDjdKzqcuxPeIDtyOXCNYCGSZhciudXROgZZzngrPRakPuyCpKebrBNZweIaAowEDvNr" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *uBraSRjgIoYNOhJ = [UIImage imageWithData:vfgoFQtNMpWRzo];
	uBraSRjgIoYNOhJ = [UIImage imageNamed:@"wYpXwyCtentAULTVZMiRacThBTYSHUQEWouJYYCMplJevllPvQFZSpSOgjiReKzTXdbMCyemvTHKjQObmnbunCfAWmkMztkqlGTzqCNjdVG"];
	return uBraSRjgIoYNOhJ;
}

+ (nonnull NSData *)jAbMVYIfPlFqRnmYMxw :(nonnull NSDictionary *)QEcEAqsivxYSSj :(nonnull UIImage *)LbnZIaraRgcyvAGKQ {
	NSData *KLisGTJlQWAhxPPgv = [@"bdrnbxBCtEuzVyoqHxlRnTNOoeSIvKYoyLdEcBmvmdJZnFYtIxnjVruERNJFGDRVpzAPdhgvrVQweyhhZoxAtJQyYwrtTJIHnWCBHXmuFZvdpIuPhKGDRzyOLhayYPbXBLEUmQTRYfwLSILCYExVo" dataUsingEncoding:NSUTF8StringEncoding];
	return KLisGTJlQWAhxPPgv;
}

- (nonnull NSArray *)KBMUSYCkBmZjef :(nonnull NSArray *)RXVYyjEGMwfVJCcxdJ :(nonnull NSData *)nCuCspKwfxAUhSf :(nonnull UIImage *)cvfskNJEPEVfvL {
	NSArray *CvwipzyUqfLAdgpib = @[
		@"ykcRuGYcyoCbjbwtfWbjqggJcBUydkpHqoUBdaCitBKrlPnfDnAktUVbHVWYFzaZOYfqheJNvflzSriFFlAXUtofegGPBcvvOmcHlPSEKWP",
		@"MChgmRbWdnOqpRJGBwPuxIXfxaJAWYTchYBwrWsPnhSBfOoFXltmVlOqxdSifhQzmVXWMlqAxFHNBwWfOhZUKvPKxThEATkAGPlxhbMJAaDpcqIspSBrbKEHehfvyPUEpStxDygjMEbWWfrkz",
		@"yjRSTaRGnKprYVJaDXczfjGfxINsXeKHVgNeNThANlYnhCxbSFNIjFjgYlZkTKFxKZvgIIyNxVEXWqNExAelIdqdywdxXspHveCfYSgVQXuNDrQELWnIdghHWzpvQlwQGTRakSuJoiNvpAMd",
		@"VMGTmfDpYdBjEZEzEYRDwqjUqhKGfJmaHIWuTTiglqjjTwTESrIwqmNtcRTOUbSsRNxcQXLkxtTCkrJqoCNTxqxFLGmqnotXSQsTVXTS",
		@"gzauEiJVQlIAwMyFpMYEyQfjBVcNJuzqHVssCplecqYbCjBFpavBaLUfGnNxnDBsULtIodRLWpmznteqZYkotzlSegHggdXzgUBmmCKugOxktzIGwzpTeDrtysAtCBuCIQbjbgrlY",
		@"wmRICSasCCPIWuFJkLEGpzsAnAoOHicHyBuTFEmTtgVzDwzcSGRAhMIkeFTBeVWXVVoYFAjMmKGgtXmuYyjwXbcZQGhfNzpAWvMgiGIrhmXlAwomE",
		@"dLkyJfNuyvSDaSpZdweLGtHvfwCSvFYrZwfKWfYYHLKlUjizMeTuoIxgPBIIjtxcHIhKJMbTslwLJfFFlJChuMzRsaeIgUkHPecWXxMVgKdkKLFNpHPqGoCGrmQbQkqzkXZC",
		@"VUlSbnzmDvRGAbaJdhJGUfhPrqtfvcGwOQyOhcMyNsTxemQlwVzdqJkHuKVWtwYWpfaeeYEKtRYncvYAUnBgRSKgNabEJtamvWNhwZYpfYlpfjwqCcRIeoOHuOIDTVnivGxaCmTxZhilXWdquIZr",
		@"cqiGVJyQcSWuaDBSQwrQTvzxyjmCOpgGeCZJeFADzdeWleUOmEiTsnITwTfXLuBKcocnXJPdzOLingnAQpwBjcfgBGYjFdQRKFnYCCReAPOMYOmuukxIzbHChWnqoBYC",
		@"RHjbpismGctgcMAheGEWhrZRyuLxXIicAgOpqrpMuPQgmxZNfnXvQhPytsucNIlwsqgyLeZgXfdyWACmpxqGiCpvSbdkyBLbTUKEhkoFhmeUgucUELpNFFDghEwixpDVtfCTbJdr",
		@"GdcBPbyuPQFHaladFCpPdJgIaDcCFkfKCEQTLhrAIdEBhQPViAFrEzSLHknajTnCrToHjlfMNMarvXMSkILWWJILCUgLmnblmhjkixzKKSowSqlWlAWADRqXxtIKVxZV",
		@"oWdOibcWhJJtiGcOzbVnAHkGrsgfkiNZXpbMBpcZblZNwvxweCRXKTmYNIFaGcxUrSfgXjUxpVYIVpHOKkXXqsxhGrtGFjwPaMAeFNGCyZCmLvEOtDkNKafSMeiMvXgezJe",
		@"BjhIXvFVkPoQhxTgWXflnTyitNtEoLyREamhmDGGeEiDNNrIXgCnHuPSNwzwKsFsxmTkHMndhPlseGUwfIezJLuXEWrpoHDhoOTseLIpIF",
		@"vpnHoYhNhMDrynFBrMYwUjKUcKnUByYPFWbTxnpAwAtGmlUnrEJHZxptlFucOszGGfOMNQYOoPlZkxpSGSRaxAheFuHFxdbpWeNLSaIJmrayilIxPnvfwuoCoA",
		@"apWjluhuCXCeyIVnUpdUKdlhFwnkUZsaKhrOdXPrOezJCYGdhBMsnbkQLOUmHBHYJFcXyXwYxYwbizQsEOQaJjmzdKjRFhrAOCPzcxnZrKpYWcTCyMrotoJrlvyDwNCpGezHoftOqLGxh",
		@"JTrYDOEwkvtzBuBIKZRqOxpLtXIUCLtwrGiQzWDMSdkBKCbTwqkdUbSCtswBYFuNfIpdrWgIRKiwGaBZGbMyRTxCtraLcoyLfeDUjkRFtWoKGdxzlMdFK",
		@"YWniTBcGrBuvxRFSQXQHlBQgmilqrkfwBkObrBYGUckNovVgZEbZxcbVmTlHcyxvAPkLaLgwgHESMNozqRtocGfwMtykJkSlIWNUpQwhZFKIAvkbROEMAfMUjHULKTSqRTokvBXyCxeYRDd",
	];
	return CvwipzyUqfLAdgpib;
}

- (nonnull NSArray *)lxWROeUcrDshcUpS :(nonnull NSDictionary *)nOAyyZzGrlazmU {
	NSArray *WihdAFOqpVIougiL = @[
		@"UwoAZvougPwgTsrenBojtrLpvvQHzioBAXwmoxuWACSCIjMjTrVqUUWBfwwAijHIRWVcWVphYBocyVBjpGrLBNecDTWifBWIVFkMgjnZjOvwubqTdCJUPsndWRMGoXHVYXokINZOzroFtV",
		@"IzSKSVbBfHaQYBAYriJiZQqfdGXtwqcpcIIgFKYqPurQKOJjFkjmXjHtCsmKqZmaEPpqccEYCjDSvtxkymNkCXjqFKXuDUqaIsLOeIloUcNpQEfwZspvyyijpnnDsvEdZAZEbmKJKoe",
		@"KNThlrJNepBSieBWuhdYRQYiCRKEnAVozEGHgjkcUCrrSrohsyLgLvneyCSTqulMAifqkZXGEAwXEAlezFYDvASSNqMtCZTHkKAMVbqpjTHWcRxQqLlkAKrAgCLOo",
		@"ZCFIqIPgQojqyAJDWnoYCGmGsOpCyFQPalbmFjSUNiYajlRKRZgjCoJmlJaqSfIFztwbPFLHLsNIsZQhAYulvwuhzmUgYHmwvrTwjqDBVk",
		@"jWNkjsUPUjpchPteGysaIFjYXZbzppnCgxbSrdKmVqqSIxFIjXFPJccHjUSCKdpAeiNQfHZFmUDWjXiQIyxAPnCwLpkiUpbVuYasZAU",
		@"skMLyCvJwHUteXTDGjOfqvawciYQEkmsekpBaIDquazOZGCBitWBqxYbuUpyMHjssDKHXugFWzWrjpDQbTyzUCIIQthmkVFyJxejyQrXqAfuFbMwzLhfnLeDWHaLfIn",
		@"ecrZvXLcXLcrNYUhTanhluLMAcGrNTerKanmDammNRApiMkTtOKYdPhLNeDXqerGoZPiGjzFfuckscvyGfvHNgDFxfDrCyLcxpKfBwEQkHFrILkDuAofGYNkubzgtbfokbwtDRYkfIOAlEEgStRRt",
		@"zbTiibyjxGAByTaVDOlzEoBHZbpvVhmVfFSaqaiGkQwOKRSZOgozaxsWOPxIhYfSxkjOPyUfhvuTmdKsnMrleHYZvtablJIzhiLrClcJA",
		@"LcUMcuYiTYRLscWkETuGWHWQvAEwNkjLZMWKWrxVXTUaTVwgyacfKJPmwxgGroBypWaFMufDtHIzUxyRmukEpteNONLIprEdJEjfFn",
		@"zSDGbqeshDjJCbDMEuWaMmGUVMJftwfyOreFbSHOaDPyHvMMKNILkooWgNJLRQiJUDzOONREejJTJaFKDOxZwPhqvCJBbWiEFBHCXCeqQcKZptXRvmLfJnBfjGcmzdeMJtHRIeVMl",
		@"MfHZyCBCcWKWrpAVVmJsanPopNxVoqfFIyKsktASEUHdjUgRERrYDFZpqAiRSglJCkIGuWXcvGFMkVxdztLTGrPfyvHzHcsHgkZXaPLloppCil",
		@"SDJRBsZyimrIWqtRRiWbkzzKiNkAJITMPXGCFWepIbZMgcWPMCCGbxFoQnpKJUsYRhToEVVzyvbCiNlXXSpbwPhKrtFKhNNtPrOIHqgeu",
		@"GfdcUrZqgCMRMbgLswgzloRhTEwDqmHAPEnerjCKTTGCpFuNswvWeifIfbUHlVCnPZuzCOMZpmZdUVmqsuKZZhlxONWnVDJQVjiNjenvPhDksEueOZwTpWFWAdzwE",
		@"tGzqVcndRZMVZpknSDJBwYCMitFiYXfskdrEZIWHzkztMmknYxepIVdHLlKsbEcvUUmSXlGvotpbkGZgWdPSqCvbjqIAHCOVphCBWgLUCExMP",
	];
	return WihdAFOqpVIougiL;
}

- (nonnull NSDictionary *)OOikZKiVYijNJJx :(nonnull UIImage *)nmeeyaDqBT :(nonnull NSDictionary *)PLlKifeAYZUiwZaRe :(nonnull UIImage *)WMGSlinSoYJqLSIS {
	NSDictionary *CpchGYfvbv = @{
		@"ZMgbVSFSFYTMPykKRy": @"XjOHLyUkYTStHnKwTQGicwVZPAIjyTKpfHPyCetgbacReDbDtGEuTucDEWQLLFBXizzXqCDJdPiOSaSFeRKsZAVlwtcUIWJJlpxcafvyVbhohAmbbNx",
		@"ynNggdJMwaEtCzXMEKg": @"aZqJDkppiTUpdqilhmBwyaKkmTKkXHHGNuwksBxzJFZIcawZcAUWdNyYlxoLaJcggBpYtFNMYZNFcRRGgXiRPVVPhwBjOmPclbqtGGIQg",
		@"bDtQVjeplcdKkJ": @"oEGkHDooZnZLxsndkuBmnuEGvkGFlArtFfXtuZNxWkTJzjDLrOuaGcReScJGDHGRUmtRRqjQYbdYUESStWdVzluNAgpcWdyWgYxeupOzsRJVVqGQyIVALMdIlBUxWnKtgUCKUWCBgs",
		@"qGGkibjiAC": @"CNEybbLKsxXCQQjDLLIPvrqMGqGtWKbHFttysSxXYciEciVFkCxwKZDTJwYMLIJctAZNruMzMrfexHOCHnGHRZYvNTTVNWrGpaDZTKrifcjoLTs",
		@"QWGsfcarfvbUqyWLgGb": @"ZxlUjdknUrOKFkqmzfqvfXeKcievEgSzReztyeESxmXKzzNoOFSvKuxsbPDGVdCUexnWiELbyZLqsIoPmRfvfEZvrbZSyhpHsQYPmmRoVEg",
		@"uCeSrAUEMKFgDmVCOfI": @"bcoIbeeywHpiolArdvamtGJQlbrmIEFGMVEVXXOOGQfCTRmlfTHJCBRvmsxDbpnukxmIxACmVnjTiUjsQxRxvndqjazSIJOWXHWdoCZcNLwGsIZLqvin",
		@"vGSXtlUomVhJSIFUPx": @"PRabdbiApezhlpMgafDBsNKveqbEXuDDZYHsfAwAeeeJQJhpzoaLEYjeQMRteSlhuquRjHLVDtKLXymEUXlvlqSybmhzWoFfxRRCRAecxRVl",
		@"pRMCqMsrPrqpHfkxu": @"yYCizgkIpyChzJzaAsaozBCkdqgHMBRVmYNdYlgjTQPBxRJJCriQjCKBIRmXRyrrYhMClZcbBLKjAmiNAlzhHgGPSBnCKqvjhPkxdWhoLKYAPlBLffvvHqc",
		@"gvVKHrNaYh": @"dkWJxSxcMxuwvrftpxFqrMzntpOgwhKTFTRlTJhyxXodLRGkvmfZFhDFlgMFhItNrYgzQVVbkCfJpflcdeAFHizKBXZEHNyBpPHbZJvfmhtIeOBNlregapZIxydmGURCpLW",
		@"hnYTDfJpFDIkS": @"oeSlymskwpackUGNPEJeBrijpqIufQgoCqkKErPQKbgJXzgpvXDTEtTUZkIlKcxASHwCaHYXJtYDPCmvenTSYhEbLbESplSTMemCbeymfwOYznVywRmTvOyoxLv",
		@"IpVGXCddlOw": @"WLxwxPpiRJrzYOcKbWrHmFNOXMssvECazJXSSKvmZiLFrYPlbyDrlQgWVTjKKJAWLIfRfyRtSkoucgThlWpJbULWcHoFDcvNBjqDKXqSmlKhjToi",
		@"ogiouXApKRgVV": @"phrJDRpmTSqMRgyGtVtLtlABKLmPpmnFjMiDEGhIZUPhFxfeZLRkJghRqHeqHPmWgpzzBAehrmfmWetsajIqzAbnJznkNYEmriztMW",
	};
	return CpchGYfvbv;
}


- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    
    [self.navigationController setNavigationBarHidden:NO animated:NO];
}

@end
