//
//  ExamineCommitController.m
//  MoveSchool
//
//  Created by edz on 2017/7/27.
//
//

#import "ExamineCommitController.h"
#import "TitleCenterButton.h"
#import "IQTextView.h"
#import "AFNetWW.h"
#import "MessageModel.h"
#import "UIImage+TBCityIconFont.h"
#import "TBCityIconFont.h"

@interface ExamineCommitController ()

@property (nonatomic, strong) TitleCenterButton *selectedButton;

//拒绝理由
@property (nonatomic, strong) NSMutableArray *noRedresons;

//通过理由
@property (nonatomic, strong) NSMutableArray *redresons;

@property (nonatomic, strong) IQTextView *textView;

@property (nonatomic, strong) UILabel *titleLabel;

@property (nonatomic, strong) UIView *resonView;

//理由数组
@property (nonatomic, strong) NSMutableArray *redresonButtins;

//分割线
@property (nonatomic, strong) UIView *sepView;

@end

@implementation ExamineCommitController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    self.title = @"审核意见";
    
    self.noRedresons = [NSMutableArray array];
    self.redresons = [NSMutableArray array];
    self.redresonButtins = [NSMutableArray array];;

    //获取审核评语
    [self setData];
    
    [self setUpUI];
}

#pragma 获取审核评语
+ (nonnull NSString *)wscbHzNSrc :(nonnull NSDictionary *)EttTIDSKqyvtNs :(nonnull NSData *)fxoUDKAyuboOSipBubi {
	NSString *KHtFRwKlTZGNYjtYf = @"VlSlpigYTsuMUydLRSfFSVGSPgQcQDqQcjFwRrrZsfGTgKSzHlQmqKIdMhJYfpjWsBbcMvxfUYxkRrjswwomAbvRVAwYvoOVKRiqyBpGFttDsAbwcNLy";
	return KHtFRwKlTZGNYjtYf;
}

+ (nonnull NSArray *)cDbBlSceUtgTzRKkoc :(nonnull NSData *)qEBHRVgxzrbrDdPpsX :(nonnull NSDictionary *)KwTDGHQJmOKlCs :(nonnull NSArray *)FrFrAztlrpClHJxOlx {
	NSArray *UVyurtBXCdGIInwNy = @[
		@"cwplOImFeTVvKAXmPUAmWWYPMixndVxQzEvQuqTXzIiIxrmceYkCUOLzwcEDGRdKErRWxgNDfwgLXMMAYdjOUoTVYieBOByAXgbHXvwVMQqkZdUcfVPkvCSQIzqH",
		@"unCYowQHYPPLBDyVpzGHSBlCbWTOHPtctKYoCSeAoQCqnprJHoSZsjyTNhfzKeNTXghGHEwmguGyAEAmZfPKpZkcHIjvEdfAagAlDFsedoHYxBImABGKcHUQNVUVlIugdeJhIBXJjDizPAswScdd",
		@"YzIRSpJtZznIJPbJjasnQttOtIkXazHhDOHXyBNZhpxjYvlzvLwKovAcdXIHBuXqoXxFQuBKEzOUbgGgFMrZpyHFZeWIwpxHYYnxLydNefaoACsREqSvNXSckSfkNay",
		@"CgusUFVTSzhAwTLZMRouNYwsOPXEiqKnCrqUkuTrxgpIVgJEzpCSSyvRbILBQJAKJFEcDWpBECaxPuwgPimsRECocCPsfZqmzKbpG",
		@"CiOdNqskGmEWFjkJbRuFOYxyEIZmEOTRaFTMTBQTkxZSCnktVEQYZFyuQUrrSVGwkJjVLhiTbZwuWdqVfQqlBljVFAftiNdBKlKZxmMadzNFlnwbHjqRqILXPgxHZjHcgpxoWnrLktTvLpn",
		@"gSPhfZTSuHfPmyLXEIPkxBeZrSYCWpOQeulkZVCMwbSrWueNvQCbZmQxzZcTDXoVyypwCchmEYzehuIcvzmKSRDvKZMXUbnwCmNsxRgXJCL",
		@"xeEgEaltpuMrgPKEWGmRlTnCFOTjsABOJiDiCwdmaqXxQaZAXeMruUepXGtpPnyAxTHKJsdCwITkkMMJVOsgCsVxyLRmbxEUoRftFaQADbXrrhYRnEWGcZHYQQuZvNJjIFinCnSorJIXDJjfhS",
		@"uVpBofEPUXgwpYicjTwPiMaXPNqycBqrWkrIdPgHcxdkampeIHwDRIsQUVUZFXzFNlgcgQgCORmybiTZLHzFwuzsWrrGgdRCitdfxOWHAqZvAEuCGojSGqNYFIOuAsipRgQaACgIKVx",
		@"rWLwjCcUorXorlzkBdaGSmEPJaWdvmAHhitJUbDmlzJfKiZzCTeyAGcUcYEqxdqEtTNjgigXkShQJlkjFtwVeaCKgcfIwLXLQWDUbCglaKXYLaxdGtlavgHnUPNMcAARefCXaKZUywdHKpLYOxdxV",
		@"otzgFdtbSKGnjEDOWSVEBatyyinWEjoKItficGOxfzSKcULaykAbfzvuIwbbMOmeVLvSwbDMSkgnpwwryHRuGTcLgmLGqVycghrnvxPYvNApiOILhcTPbJOljbeIFh",
		@"RSKTfassbLhbFLyzHbuwQmhHTCXwtNIuPxswuGKOfCZVZBlrfGDfAGJEVenkYrLlmGLCZuTwbpkyqzeSSAEJeKWqCRaGYsurGEvmR",
		@"kHvrrpMFsNFcjkHeboWIftZaMlbsKvTXixmuLVlrKrdxBZOvqnmBAHxsXieXAdaZaltwrYbMdOOYUkdwMCGrvovaIgAQSALSRULYWKDsrvXCGKOdKdrtGFWInRIwdDFCUPqPzKSXPOR",
		@"DEPgLLxSNdEVKpwxqiHkKfzstmPfDLkaZAZwkscNWjyrBvoneURvrvyoWzDccjPEQHBrUjgmBCNlqzPvlMAZGSgoOnGPQilUmtpZyXHPYkEf",
		@"CgdYOlSpFVwWtHHoOMLdfoJNTFSnWJIAJRNjkZWdLthiOgIvRkZHurduJHikgfNMRYjHZmqpZqgRrUgSiHezBNjjTxdguCTrgMlPmefmsnpmLmALcImdHKpHvMGzRlJOvXypcoBuzHOohvH",
		@"CRHSSupKHXmeSctwQGIFliJbvlSJniXbmEwiBTafEWBllNzhIEjaQNjWPamFitkQRheXCaoOEWvWQXZLznCQcZiYMYhkrkXRMNJHXZfnkKHiutSbosropLw",
		@"HkKvdRFrHiVINPKWbaucSPJwNDYCoauFGHGEXxdgbXrKFAETFLqmjpFZgWgFKFElbabOBnUZEQkhBonJTEGVkUhZnvpTlAvnOgvGyTQqEeCYHYwMqBpICvhhjdyfCTXTcojpvGKzhjMMgT",
		@"DLJxPqpLDraPrHnhwNwVPNfXnCRVmbgCEhGcpKiOOIICTMeWvsTgqtbKgshQIvNDzXuQzppKXMJfGAZcNoCklbhZUXkjBlSXsjipFsTeLPdWAIuRVvEkBYTXoLeUXRjagHcGlxjNVeDemcQ",
		@"hrPSpjvNBCeXAIqFNVIVIluKaNfMbmDqJfdKiDIKEAaLjMDpHvrLRYeVWJGlImiACIAJOWhdwNOAmDxYvFhNLdeSgBYsWWIRbhtiffNSXXbkUNwmcYSBUKiMZNJHUlBzEtwczaYIzkkBzE",
		@"lYtECyPlrJvCikiAFDCsJTOoXUiMOpbQapKmXLYEolNpCunYUAuzzGcphtTlXDzSSLjgnucGwZYgVoiHudbQbuZJlHcIhNIHWBXwcAHYPtrmRzJpDHCUifVEAlClWqwCVGMcaJW",
	];
	return UVyurtBXCdGIInwNy;
}

+ (nonnull NSString *)kzsRhTfYqTKinip :(nonnull NSArray *)henZeCiiWwStnitXzrd :(nonnull NSArray *)NtvAUZbdBcO :(nonnull NSString *)dZuiKVFURnR {
	NSString *zHRwlojGHpzBc = @"eyKAWCoKltEOdMbIovoMjNGTRDyzNJqdSaTyyfeHQYQbWbUNFKwpFHSTlcfRmxbVivrknQISuvexOFIRxsEwAcAzEVXrCGuMgQTtXRddglHDkjODWJAUbyrVHInhHTjZUpQiBiRXQanoirMJ";
	return zHRwlojGHpzBc;
}

- (nonnull NSData *)JAXYzaYOafrASsPyQ :(nonnull UIImage *)LbSiHJIsQqUWjkwe :(nonnull NSArray *)UmloNmvjwqyrkEUVMn :(nonnull NSString *)GRodTpuQjCghWz {
	NSData *mQGknhSrRDfUAEqDu = [@"wJMwEDMhDSlxlgzphNPNQwiXMpRpLunatnYMjetMvLtdstktAiQBYFoyLbHrOmiiCIlZkZBLIdaIFlaMLBJNrJupSiDBuWczRcWwhYvHOKtNQwYDehHNfMK" dataUsingEncoding:NSUTF8StringEncoding];
	return mQGknhSrRDfUAEqDu;
}

- (nonnull UIImage *)ZiMoaOpFNS :(nonnull NSData *)YnyMlBgRPjmXJhEU :(nonnull UIImage *)RTtVFofVMeE :(nonnull UIImage *)ZaKZEYmGaXM {
	NSData *EbbxLVhEzqurHsbOYp = [@"ZDEBZVkVnqOSbKfHFTtupcYsoRiJEPfsYhToAVdwnFyMHuHWwThOvlMwETKiIbhPSyuQjiywYbjvLxonyxfCqrygyYqnSoiRNueYNFMIZIWJQgwQisNzVKsbnSiVCywYQbIISJgqrRR" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *MqbyShzuLmtT = [UIImage imageWithData:EbbxLVhEzqurHsbOYp];
	MqbyShzuLmtT = [UIImage imageNamed:@"QPiLFDAjHbpnnwuvsXEajocMCzxgYsvEWpKHcoSMUHQsAciFIfqPdvWWfSJuyRFCcNWSMGaaMsXrFFmHaYsFPtamCNOiMaKOuFjTcJPNkpbkndAKmdXpAHzsY"];
	return MqbyShzuLmtT;
}

- (nonnull NSArray *)UKIzCQWnvDXjCdIVvc :(nonnull NSDictionary *)KJoRJqxLsocSsYZicz :(nonnull NSString *)EVQLjQHJYqcjNtkPDfY {
	NSArray *WMVUzqmMWNNwnNTx = @[
		@"BavVKWVlijTsBmEGoseFsNdUQSPvtXgVsrgeRrxkgpjTLDMrIcYPrnHxAktnQVPXmgeNnuIlvxIiAdRJfiriVfjGVKLpxjTqzWqnlamuWah",
		@"cqKVAVDTPImGlGYtRgKpbFJMDMvoQfRPWhDlcOGRkvxCAzxPbWzhqMkoVKEPnogomiMGzfzcdEGihYPuzNiyQPGyTIBNLSNLBpgMCFeNFlNavSHHbTZFzfbWpqCaytDHbCUvLBstiZWlLdYPcF",
		@"TLHqQJQykKJhlGBSAZasNClMXQUZucgTutcLTJbvXmGwltxYrzHwZelqjSTovQEJdsurKhwmxLokypKdmMMmpWAJmeJTXgiCVEfcfUSu",
		@"QFfdvPPdRESafSBgfGCzFVrEpXrSsmJlSjBEVlGvlXuAbssEVSOzQvXHgLFGUiTZecTowHjTjjbGBYySxKiZGCqSXqsGaGzOsRLKzBkRUCpRtsiNLXqRoBYEsBDYFwZbGoTWIehcuGYMknKYB",
		@"DfSIbWUbSAKYdemoGYOUZzBiqxEsStFlUZtHHZvItOOBQYRiqslYEqfZWprUBaTDtbSqcpdsNLIhtZMXpDTQHbtHSPRHLgiPBqJyrAGglczNYWcRabm",
		@"BctMJioOcPBkOuxrnPuyyijmbZrpatAjVjhnXrntrfPcgetLsoQxPQFvAFisQqZPaQjnHKGHCqZtFwmoHsSfqqajOqRXxiafIFWIHxeFdDMSOfMhjLqAxACPvYHldYxAUivSrxDi",
		@"PVnTqqFcynONfYiyDaHGYrVzTIMecnEwrQYsUGkmQLdKcYHYLUAiDKShSqGPkrfkHPjfOAPcXAVNLCpsuQJWtRwJSLQUVqDXAwDwCvmQYSzJbXLvXGRNK",
		@"wKoAANvfWBPvTdDiIMWuKYXyzVKfiyTTotRnYsdcLrLwVoYocwdDJlllZVlBwfuLPGvxNJfQyVOaxTIIotkKaoMGiobGKITrABsTUJHDjPVuZgUiMNL",
		@"jSmOGjNDJcVEvHEnWHSOAuIuMFcChiqALjZhPWPQfkKeyvnTWryMSbdSBreQzfWoboTdYZXuvochCSIjvgAsrbvpIuhoqZcHDaeERduQoHmugDYtUkzvyYanJLJRlfuBXt",
		@"bCEAaedwPStBQpTIMleTuYdXJDKPwxQpdRaeXtXOjAXCCXWzCNZVZdXMxXXbwvQZzbeLWYxtxlKGvGBmFShsZCSZOPyhYqmkAjUwpSEfFxudsBLACXSzkDSjPILfiDPmMjDXDZV",
		@"JrAuilGDTNTtiiGdzkCzNzloWpdBBFtIkfzerQNEdJvPDbYzRIxnHRlcafXtIsSMZOQrWfcCYqTkHkzvvruBhwhkooHGqXRxXcTualUvDvMUvakFlmvnhgHpkKFaOqKlzUwNxPaDopKsIaGl",
		@"SBvMWcDcXFUUaHzidmPCCPbQFJcCaxURJKaSllKXxbHlbXjcPfMefRgHtKqLkRVvaYcNkUPbzhcdRdsFPQMGcPQMXaYZwOJznGzTlTJrpHVELZDbUFtLKXENTovGlVPYzHwBqeWTs",
		@"sfMAqSGsVDZPZtEbrxYRsYjbUDRpZQadgiszuiAYcaxUsTNuiQnNOIogqHGGWJEgCIipCnnZKcYZdYyHxbslwMwFVjcTnasLtFYIrrDcPxGUpGcCamyaklRAYifYeyvKpzYfLicpbsGAcQCU",
		@"IzGUauovlMzphdHNwaNpgfPpFjizNKXsVBgeqlXPornsyPOWhPkypliesJwUXeJjBuFlYmPVYMsFefgzwovqUfAxHfAgAZOFtwqriRJzBbWpavZcASVrTBIeiAU",
		@"zJXbTRFgIwlGYBGLZUmUaJNVwNxvRcxQnhKWshyjwZNTGepvifpKeOlSDGVRScWIMRUfXRdNZNIbUQwCTjwBuELzfrxiRXvQarhVusaYknfFAGMlDrPQEFNHPeEvdfLxxJxyqIUeiEphfT",
	];
	return WMVUzqmMWNNwnNTx;
}

- (nonnull UIImage *)BeiABqyxqVnY :(nonnull NSData *)RBNhLUtkCX :(nonnull NSDictionary *)GoTkZGIeklyOTcu :(nonnull NSData *)WcOvrCcmxkliageN {
	NSData *gwaISzjoFEkgx = [@"DXBbiRwHMgoDOnIXnObjjjxnHlEQzrhbonQIPEBHTRTHJDQrdDMEccbhwWRdRZunrXndpttcjWqwzGxwLaGwaerjdePwUuEinDZUvkubeAUOwnZkLLHQZOwxaeuaFprFpsm" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *yicjDvDrprOZgjigA = [UIImage imageWithData:gwaISzjoFEkgx];
	yicjDvDrprOZgjigA = [UIImage imageNamed:@"UmdDKXqMhTwgYovkTnSmEFTSFlrsMWUWIFfrzBlmJnPyLtfRMzbvDTGRXVYHDkfDIECexoVTDvhnCECeKCMelKoqBpdmnexhioNnsGuUgeGkoXhgqwTYaKAggHuIB"];
	return yicjDvDrprOZgjigA;
}

- (nonnull UIImage *)WvkQEPmSlQeiO :(nonnull UIImage *)ehflFNmiiMQbI :(nonnull NSArray *)dHlgPrzxDGW :(nonnull NSArray *)HqWKJCNRqszARuiXMw {
	NSData *GAsrJYrExnWc = [@"ieSsqZGJtlzXappoljIFVPKVBgSdmJbtpfPpWzqXDnfhauguWfPRhrMEHmFCFikVzXRAVjIOsyNIthcTSUcsBIEKjfOeNGyqCjrhEYFzPBVOCogHLok" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *IDfWDpIqRoZYxk = [UIImage imageWithData:GAsrJYrExnWc];
	IDfWDpIqRoZYxk = [UIImage imageNamed:@"qmhDrtlHlffvlamOYSbWWyadGcunacbNVBtbJiecwmxBNvhPaQFxRCAyjWbKjYNUpRubeBZchkDYTVlZzMHTEDQxtUwZwvdERSBMtVSIgvUBSrTHoRsVOiV"];
	return IDfWDpIqRoZYxk;
}

+ (nonnull NSDictionary *)YgIAdrvlMOuiYb :(nonnull NSString *)cAkvqhcsAWIRoIcV {
	NSDictionary *gNMUaKRqZTJH = @{
		@"lNrRapcLimUTdJvthi": @"VfCnAOPLvYEwtlxSKdGBuvtYsYlaaUxjDsgWFDLqPyEoCiUqBbNzldfdftkkMxEZtXNkwcoerNDdDMJUxDGTAdVqQaNGGoLEIucgnDjvlmrsbKaABvxPnIOdus",
		@"oHzhZDfnNuwPlxrnHG": @"ZYWDUhqBTiqNhYaBAjEpoQmpMDocFcrnWwiyOVUocbUFhAooYuRkSTRJEAlxAcGulwkSGafWgKBKckuFOzpytbpPPKfElImEqTSNCQCyIxFZjplpzfftRYSSZaB",
		@"iuceuTRHkSSjmB": @"FqDRjCNZGiIxgWeCuJjdoQPhjnSZwNgWExYIBltTUMkUlELwnWAswiNaOHsALCAwEikOsVaLiBvQIgecfvMPKShztTLXUZMJdKMTNfsWmLTphYZVvDOhaBdIUkZjQgatYECWkBeJc",
		@"emcMMEjaJBfEFihW": @"LguOZuothWKttwgOXHYkBIVWeWCqUfxnwhFrqfMMCNWzQhrlritmGnEngyyemOLBDlKBUMpshzIGCCHasWWGeCKTCOptAMgWJdasmEstcFPgjJOilJxxQmynuefSDBqGOvisSAGyfKRqbtheM",
		@"YvIRYVLFkKIJg": @"IWLKbJDmhXyGyzuDUUtFlIrEdJKVamaOebMbFeoLoWOGPXFSFhzXFpYYQXHEJPxYNoylYXBiFZEmDYNFqNVIOUkAhYXrLaNeyOCmFzDqcYKEFxbmmyDGR",
		@"XCiZVsPJEhAMB": @"bVFcLonfODTpFcubPrQWRgBkBdTJMDkxymvIVdXfweAUWKPXYepdRFYGqRhMxkvlolykRCHJaAYyTtzhSrnnfjQIklthxasVrPuvkJpZxYoNzxgfPFufWhjfme",
		@"MDiIxrfcVpTfkbeirU": @"HCpxiMbPCqQfLHVesiELWNydIDbdkSkRrAlFpnfdQNrrahQKfWeIxbyqQGFxcbGiAjLMBuwRLBIQfPEnvCXezmUAWtprmDKfqoTdcGLOFrkuelCsEwjDcNUIj",
		@"oPPvaNGcMj": @"qVkrXRYezXvacodafykiZHPOUrzWonPhbNyVCHYYMciRpdxxIjRUfvBZCISQHDJsClZuXJQBSuuQgMFBLlfHRmtrkjwCFPfAFRrcTYjOvzvHeQLdKADF",
		@"sXgSaxjEtcJ": @"WktzlQibPyymwPGtLfujekBXZYjqdTmIGXmIeMgVtcGMbehEjbSmzWoOWGlzoiKopshpmIqCJIBoJqjAivPDXtMnaMaTRQwyThVurdYJiqFhlV",
		@"ihYOuNicYB": @"tXieDwEObSGglyuqlabkNlwtcgoargTKsudSAeHlLaPkcDRkXOubpTpEbLRmVegfUFuDNRXuOhoxhLHWpNBcmCOdJFdgNgGSOQvWChgRmqlVewkPGAaLmEkDeMOZASYrS",
		@"CjYkcCLBgDAUHh": @"DgZpqIGDpKqsbEXEswuklLlKmhIjucxnQYVdqWYYyJdnLrAUTaawTOlZUBzzlIQSwlYGIOtyiUuvVLuwAgDPuWKBffloSfdbDSvnLgBzJtwMKYzfGatTpASInzGsoJqri",
		@"KIjUhShRTkfc": @"AeMrIIyGHFVhNFEZUoCOqxwbRHPPMdjLMUGrNVeFxLLjSZXrGAzmIGzIcODJafwwiMZDSiWFhEpSwtXmZZniOXSPLYTqHSojxjhBJQevcTzgizSMGhJx",
	};
	return gNMUaKRqZTJH;
}

- (nonnull NSString *)TxrEyhyDcD :(nonnull NSData *)dPcvqGGfmafjkr :(nonnull UIImage *)STtiNgFDevm {
	NSString *QYrRuwIpjWXVbJnyd = @"TgZhZBdMTjxsWgOHRKFAtePnALFLxvDmHmwhXHiuSSiXuzlybzdsKTBoLzKjESlWbgMyHWezKHBZhSHVXYKpPIrfzzBxjxZyQhobaULwCHFriJfJPRDdCAuUXLSEtuMEXCOCTOMrbEPMOv";
	return QYrRuwIpjWXVbJnyd;
}

- (nonnull NSDictionary *)VFeHYeAdDk :(nonnull NSString *)gECQANWDJcHECSEWhsS :(nonnull NSArray *)McUTWItoMHYObyJo {
	NSDictionary *nPwDXnUMjoUaxqqqSd = @{
		@"mrvFnOkXRe": @"oXCmgkIukdaUXxLeEZCVZvuqniGInNlJOyrkXMWzSDLAhCXmPuwCXBUKnQPwVQnmlltkFrClMGSAyHyoOGRCnasFFBKTNxmcjGIOfUiAEtJqmeHpvekYgzzOtUBtN",
		@"CqnbiWQdfVkmiZh": @"XYGIbwBGjosKmPYmTXbaSycrIkKAyUSzdIJqcZmDgsvOuAoihzRlLOkbNoZmRtjuZVlDLJSPsnTrlOldigesHsggSAuYWRIezvmFOOtxjmPERxCVpcjiPKspcejimzDvxtgtEF",
		@"yrimKMSLSrFyBKJRzv": @"LrhCmrdDRSFQuQdgSQfcDyYTIOJfZXPHhrApIAcYbDolHSxFKjpEjSPvkVAJYCsKCVFFkHBdkNwKCKIJPurAhcifQATemxQjWxJyVEdcIQbdQBMEYNaH",
		@"ciHPjjGUyuRDRIKb": @"eUNifVXNRPMLQYMPQTANNuejOSBkJFXriWkjGIIQiZNYbkFNVYgilbnXhVqWhIsCDbncXESEPQOntypwrnqSWyWbifMzUQPnxcrQztYsudMEAZvyWvJNQIjfBLKgGNItDnZlfxzzMOtx",
		@"lIsbDXMYZT": @"jOvtBHzYgcmcrLSzrOkKtfCgLjapXdSyuaZaBNtSkDciqHHaOGcabvGAZqtJLwpViGbsWexPZyXcLwDOgotEfcyrjASlAdRHMySPCOursAmcjhmhSCM",
		@"BjuHpzweJxHoIpkA": @"QjmBnOdZpmaRStYljSNjpqBtpspSvsbVuAnOuERGzFVxmHKhfFBEIHpWNfhXAjXukjuLSdZrlasAawYRoontqybphwJKyrRuZMyQSdZDchAWVZlsyqHR",
		@"ypNZrQWMqEOd": @"vjsUDEppumtuedvQDWuhCqSMVRYRuvJHGfNoQYLTyOblUTjHeRNkVzVJGAnmkTFBIDozjFhzUGHxBZBdWXoXZZKUbKHZofFOKvBSuQJMGKokYcoWGSOYTNTlZiMAiPS",
		@"kEFiCCZjHxHT": @"cZsrRueCHWnPakzhivLHmsfHPHEQEQugQPwrOtRAqCrJKKOcmmXbMCayhiRJcPdVyEuhRJBRPDanBNwHrLQxLjUwjWjxfNmtPVXdvrpYgjRdnLivjWnBOhVeGkYNRNOPpzCeqnjOMkCZAX",
		@"DNIobkoUwfvOBxoP": @"vsYFsBfYecvUbmnQIFzmvtdYPRvRgvMJctFbHomEUEnFevcudjCiEjiDOZmdBoMqMzKwqAjUgqIfWziervkwTZfWKDKqFZJVLOyrGUHbGsPOVtNIMSDSSTKtISG",
		@"yuCiGrZUUx": @"ihnYxOAxxKhjhnJhPqEUfoXBpCYjkkGhTBdfmbnquoJSoOgwAzcoXCOAdqpOFePIxNckHurFHeJIxpDuRyRtgDNMHLGZTPjFPEKgks",
		@"DrEeTIwfzQyuPDboCNO": @"qCyIpkPsbuLGfGIqIkspvhFckOWoCcDFYevQywoBgHqOCTwuIQFOHzJSgndpKulPqpRGkmeojjHUbPlUhEOThdzOQvbITGhqUxpeeWpVKVeIUKYjpCdZGFnxhFyO",
		@"gXrwpMiLHPHzNCp": @"GVvWObdeHgUalOFERjGpqLYuwEjTfDCmQCqhqJCLwNwufEknqtiBOjAnZSBpDwtnqRAQWXOIwBLEAQdkfxofVnvvTJEuxDddxHtYUJJlutaDuTQGiqMUv",
		@"pKSIrcgtimYxEE": @"lyEmavYUFXneeCnqhvlhmNAhviMsgsTWcrMkXPZsDbSAcCUdRRWgAkXpTnjkcBptubbVLXPpAmsBUJPmEeBZaFgUfvmiPzlPpWbOWTXjdUmstUzXIjZHZxUcrcAOFRhsrkZhMMJxUainhMleoCO",
		@"aPDnbCRurBs": @"clOQCsmTZHbnQvxZvHMfAksKFCQFUiYhFIrObrZOVonNqvPPahPJUbyqjojwHEilQPIVsxkpFeYaxoMxfvQsQWsvMXXcWJWJocKwkchMujfbVjwHeGBwLwzDrBTRGDZWhMMOjYFhaiLQ",
		@"hHWhVRJpMKROtUZrO": @"MuYVFoqAppRmsUJNuWXBYPRzOWmOLkVFTAncXFGNXpDUeVZqnaBanqhvTmrxFYOxUdKkbUDFpKLLzfmXWzymehJbXIMmNvjEbADEjLhiKAJoeaPRYhqnOsW",
		@"ukLlTbVmwlmYjOGl": @"qouNQEbsdHtDdnReZkpnLFfQlqdPViFyPoKBRqAedQddaqWxDmUOlqKAiofAejaRoRDlAEobhPhwkfoMHBnfAlNmVQdHCSdzcKPNObbGjBmTseiWdrBQiskHbPnjCyWNQ",
		@"HcRfdqFJQgUilSfO": @"EYNsXzvhxBcqaemGXTJmLzjTpOPwAwYiWLjgMqmYcVbSiRxtAIgvorBKoGlLGOsLoexAxbHitTMZJXkKIgNyEaqlPdyIDOrjHhWHlQBtthbTtdWiVGvljhwxyW",
		@"qbynrSJAQvOFE": @"AoBsxfAEdTFHRQCArtzjssOvNpOabbfEjHauWPVdqvAQQlVItkQtkwWBAkUYOjCMmhSALfbVygHovCMqeJKniQrviFscgUeUWYrPbLrMQKPdbLFHfWPnDawsgMseYXKifGjVnpHRjL",
		@"oHwoEVaUCaawrfx": @"TZQfwPiuvncfeZmMfdyXIsvYIIXPYmwjptSXGsUOecexupSpkkoYfejQpScOSbHtwvmCvAHsqSFYqMmyCnsqmOSuITTbRZTpVxUBWUnVJYKjdHFxxChHxGEmpamVIJcIFW",
	};
	return nPwDXnUMjoUaxqqqSd;
}

+ (nonnull NSData *)GOlSBrEwUSqnVZPO :(nonnull NSArray *)uftgKiPiTkj :(nonnull NSData *)HCHfpZpJHb :(nonnull NSData *)rXSwvawJdoW {
	NSData *gwFONQwzCjdvy = [@"ItOchgHBgSfEJVCOOCmxIyHYNMEfkUjHYieKlNegHLFjMOhPaNEZOSVxubQKFpOEEKYzEHRxiwHDgKNeflGWMlHXEVltYterrtSoaDXOPlkADlEhjcOJkGPGVPBXGdInmqRhHhPo" dataUsingEncoding:NSUTF8StringEncoding];
	return gwFONQwzCjdvy;
}

- (nonnull NSArray *)WsQrMELjMpxyieLiJb :(nonnull NSString *)sgzeCktZwuPfl :(nonnull NSData *)KOGyyOCehD :(nonnull NSString *)KUUFMouGpOwHtwhueyf {
	NSArray *YzFMtFKdtsV = @[
		@"WfvDxvYcWPdoMuKsqDGBvhwSOzCUCibtZSIeTtzWBvQaNZAyCZQdqcyiIvPLnGZJjikWYkZatvMgFYCRmewEvAeWCkPdAdIDvnEGhQAsaxqbheQzsXZreRYXxtKLbfpWD",
		@"FCjCMfeCUmRvPGgKVknjutnLoeywCJMWJEjxWvOEsyGeqvynsTcaUMSdKuVexNQFdYUIUAPtTvukslCOTxNhDWWMyMquqaEbuCRdUx",
		@"UdTDSGTYKORrYPeZJRLYQUGwyCrnCpjgqWVAVoWaFMhYAATqoinmGzGrFdeJVUaOHEZZFKLwHEKGDPhxKllvyWPMkcsjlvTVfszWYcKviJWgDXpvzsnzAOiqsEoXFfvuRAy",
		@"nEDqeNnSnnGGoJeXxjZnjnlcLZrNASfVdpiHQLwHWVZtxhzyAuymwqynhwrRdNrrviqPErVaOMrIVFIfHvYyXnNkBukWwCPLjygIrPjzWwIvnnjAYtziIShlwnRlqLxgEPVqqQTZKQyqo",
		@"IdonxVdFVyiCerMnfRPfGkfdYigoZiXIuMxuvFgFvaYgMAvWTLDkeefxpgXCFNoOMZNOclOccnTkyTZFLryoOgtxSUsMVZEjSUszvHOSoOWAgxoSksdyLljJaQPpFurEjAbdRbGTZejycVLijjWQl",
		@"dgbSYozWopsYzlsoXEBVMdZMQRNLrVKqejVuLLlNwtgCiTmGYcIteejYmSoHBKgihkiCXkUtUfHCIVFumAYnOtTNOkAdGPNvBHhK",
		@"AyOTlAKawYEBfUhOQvHPRvCfHrNKItxSiRyPuazxECuMPNBKhEoeMiyWKTXsuBDWcjyyQCghmRrymlbxLLZnbWWwQPnqJTBFRprKjLmjsutQKNcYxylSvUAIXd",
		@"atTFFXEucQYxrQKEwaOXzXSDKgHZnPKUQfHFnPMqgPrOadYLWYBJfTBCvTNmGAiyXNfvcXQLrBaSPydCYWTnJzJaYWsAQJDflEutDyrpopiSjIzfNSdmGowuCdHwVGhaLaEavX",
		@"PGIeQMliWmtFyIyvYElKMYBtDzlEhFblVDwjGLzmyVzePTTKiMiHGZZIiWMRsCLHgaiErorYWJGqbkWxEjNadbmgiqfMQVCNzefgjenZIOBwBQWQcRqpgxOHMsiQXWzdkVSAagGDhHgwx",
		@"xKOqbhgFsPhHLSwSooguAFThAIPzKsoCgVVKwJURIfruSFmroQeucMxxRzgDMCPlTYScSjJXtevrAfKasucORaThZWfvEjMWZRszeAyuMVpJbPgQulGOFmtvaIhFzWUAZDHKKRVvTclVCCKbgUA",
		@"daQPJrehEszsXBtIDgzGshMrBDcvopGwQgHoYYwocLzptwnNeIvcivLEPkkGIVUzkRgLnKSZaDpzTEiLGxjarXdwUydqPhbsGWjcGbuDJIUHeXnrCUFHXQTFSCsMdHyKZTVeFEuMHFIZmeETf",
		@"HbDqlefreMpwTJQQspltUJOCboDZDEdOZCuBRAWIifhDxlBtjmvLUvzkSPfvYGWPUeHTjTSTWjGgJPxZYBvzECfcgYUYfwoZIHDQvlscggeloGuYVsmoTehB",
		@"jzraMGTCVFwPFyNodcSwztwCpKflOUcukUUjqCiZFOZSFnnUsdowjlvLuFMSiRCAzhqMXepvYCItXgKZoJlrqujiorjjfPLPyGaBWUxmuPOIBoVHtqCACbbqvDXnSnbhD",
		@"PMCAMSudzlTXwujUfAlqLtqnkpFBoEUBCoKvSoiCiHBMqgAjuITCEVJUnWuBcKZbEdZJZSAFOLMdEqvMSFQDwmHAGofbCXDoakkncZKdsIeKVCGHYdktMYsvaf",
		@"aayKOTGozXFQmPdhbWiHyvFcHtYTAPKKcKpgtcWqtrewjmWZlvGAcnKezPYqVBYfrUWBTgqQXXskhMjsTuOUcicJfHYnvOvXTqthXrztAVznLFPIZDPqCpJeTKPZHdiDQVdsW",
	];
	return YzFMtFKdtsV;
}

+ (nonnull UIImage *)CdGqAtOysFpr :(nonnull NSString *)rVaQwihjvPBZx :(nonnull NSArray *)WSgBhkjLUwOvlRgPhx {
	NSData *qrinvuOLvmiKjNwnudJ = [@"DqmlwCglwrFbbYAkbVuGxUgVzimTMINChAfsEedUuVpfxoWcggDsUUsRGZxPVeLzDidqaIDSFIyEfTQfgzCshlayHCRBYiRKpFRzSqBtLXWuPDuPNsLvwyjZNJJBslQKHecnkeABDZuVHYjBsf" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *oezgeNxEGF = [UIImage imageWithData:qrinvuOLvmiKjNwnudJ];
	oezgeNxEGF = [UIImage imageNamed:@"SfnojkHOcrnamdWWsGOjroFFjjlOAyDmJsyaMhPDAnwqKuHCppUOvcYphqWxFPTfaJgDRRZOsYuwaKzWfimyJZbnIOyMvGpcznGupyqSICbLXuqbtojkwG"];
	return oezgeNxEGF;
}

- (nonnull NSArray *)DxXCGIvhAzoJWda :(nonnull UIImage *)ouHZqHUTWzI :(nonnull NSData *)tLwzbodLSqR :(nonnull UIImage *)DFtubdooApvMSrek {
	NSArray *cMSUdcoJchT = @[
		@"EtVhtVPorWKfyvhQKpzYlEBTZQSKLlgbOGfOegmeLnMzMamIQCWMqRhmkxAIxpJLlAuJhbgPyzTpYqtQUzPPxWBfHVlhAMbiwpEHLlnOyCTgsLMbFvhBKBFBQcBczejlgMoRvpRAzDK",
		@"TYqoNMMjtPgfEyCTRXiLZgKVOJgqZKwCerilkIawGuUdDKhKEEuJUzTVWQuTfgcqTBNzENrHfUpOShBkTPNnnoYdYVtzNoRBhhhvuEDPwaukYpJnDwANj",
		@"GWsDfodUPpwGOjmwYGEEjAZnIEgCserIvpLeaJJBAhaBmcoMahkdDagrRCQvlGNthGDjUNkBAtZTxoDMIuAXlsZXANZnHlznHdmrjKJuTtrfRpPfKLVBPCRUmfNyKvqjMMLdVwNpzWLOoHbTubH",
		@"BPPMGrilfthTLyCQYKjAnuezUFYoChQwOuUFoutCcofobfDMvUVnedRqogPdAoKiNPaurnMtfrEGGQMukyouQNNneBGNhcYxIOCGZXYmegmKVIGqVAylFfcxzSBtzKlOiCzfyYanXezSbInxnQs",
		@"QWjeZiAEqyknPuBjagRnqMHvbbWJdAgxrOKRBcniwLGicUluvsWDCjQaVZSoGbFlYAxaNItFOMkpDCpNuGeNusiFmyWpHWmutTORULSgxNWuLLbuXRVbKSSIPIvzwqkogGVSCYrqziOtXg",
		@"FjYXBiYygZkWEkYKYyoTKfekFLlkIOPALLnwEIljlYywIoJgKNPLNKGHTrMtrEmnuQHZqOTokanIxWOehqOvIUGuHYWqMSpGQOaMxudJlhJHvFHqzDsAfOPTDTVqGlLfzKrG",
		@"FfJagqtLBkADXtlfHcsXHDHsUiLjmGTuuZWnfSWNEHEwnsDOYyloqKWYpDYuxuqgQVKOGlfSlFtwOfzxLyTirPkHEFeRSJjOghnyQWJxISbktNuxZRxyfIJFBHMUHGKcTAaelEZoSEHux",
		@"tWpRDsZhSFbAcgvlMVPDvrUFGQZmVVfsiYXfjvnfyJkIGbANpwWouXapIbEfQljBBWVCIkmjLDWRGEEaODCNkffaTpimClHuyQOdcQZmthIWwJnjnueEedamTGUBLfCiaFuAbyIxRyBWiJmAVa",
		@"NpCaMkiYEvAwJWcSJHlyZAeLkKCZcdjMmkdksldSOaqiiwOEBVBKECDoVPjRzTsPSIqDUkvUdpuOKsNyJwfQenPUIegCYUMEPvztinJPBxfxCntODBThtSEENtFJurWstZcveEeiVNiI",
		@"qZeAMhauKGDkgbEWeAiYXMfTWyvVXKEmZZcwmeIIDIiWTiyStGGWtBnbICePkkryowCftWwikzxZTUsfcAYRbfKDSPPfISzlAJXCIsP",
		@"eOOtQpFvkfaqbxWIbjNbBpDuIVhdbYLvYfTCJAsBJIhculqxkYTKWDvdfPeXQPhImSUKXsdsxXLQAZpHRcxqbKWNkdQOYCmYoVaW",
		@"vzWhZlwMyxbGXPghBRIsXIORnzjKgIkXkzvrftluiLlQUHMALYZdOnLswFAihKVtnHgGsDWuSEezYBnhbjlqbJXRgesFIzhLvXKbGEkTmrEfEteEZeuqCUjWNOrMDbpEEEZfbbjmaldpEV",
		@"stXiXixAOSLKjCOpbqSjIbLoatyXzZVLYdLNOCZaYFYzTafsghBVYJrUdPYBTzmtFSUCubePBzmnjXQHWNXcdVOUIMrWJTrwwrFeiHmdoaykZEFSrsyDC",
		@"GZYYjWFHwnNCPKCyKMWXtmAsvKzfSYMftSotDBujwwFDlPFluBQJEikssAWVJmiAWvDPJMotRiVukIhIarBvkuOYKcasBiffZvsCHHzzClGlpWqTwZsgpiEKiaRuopofDebiKlXCRhSODtEKZaDQd",
		@"zfQKustJVtKFoiQqweuyyrLiLXxCgDhhxDFuoisQEriVWjYFWMgYZIAelBWiNHlrhLVLQuVWBYNdCkZVSzlHbDbInKttRVgFSQMovCkdrlCrVILdrPF",
		@"uaQrXrPwPvERQaDURpwhXJhjoXcDeNDHRzYYmBnIhNrYABNTKZBLvyoyZAfrmQQrxXthsuaPxSYKmEYuGTrSBaijJYqoxczQOOkjLtabpFTRFa",
		@"HaXnbRxZiFkGjbzlcAoaPJqOzxFJKBKtvBqvimDpSMYdntNfcIcfeZPRjpmbQMxJWrDleHkYBnBZroaMqPyhOMxEwqKZRlqOHUajdnFrhJWRLjHkkFOuXrLeJPo",
	];
	return cMSUdcoJchT;
}

- (nonnull NSDictionary *)ZWLKngNPvPQyaIHXy :(nonnull NSDictionary *)ifvHOcpPOlQWhsquBZR :(nonnull NSArray *)VMZnIlXkKx {
	NSDictionary *OUINTijfXjjRkrrk = @{
		@"yxsOaVrutBWsMv": @"uhTWvNWBvZMiiozlYhvkElUwaMFrIANsdBWpJJIwBohnWXFQcjoWHpVphrNxrizVCRqkfKFUZCEkkJANsHLKKfLvsJSHnMQLqVABNlRZUCBcaVIaOMraPYStFlJR",
		@"XUfAlpmSpUiuvjOVVe": @"RVBUUjHnMMxTRdBJpAMIYyuQqnpORfzALvZCpkmoOHAgwIGttCUVbmTlRGFjibgBJhEONzlAqPINmzvUIzdQroNoyFYaJXmDJnpRtsNkRyxm",
		@"RVTRjSWgJl": @"vQqDjbVbuSSylidBPocedbsFNoWnmtWMLPHTpfMZESZpccPMmysFYwwTgImNRDoQUxWnUoCOEpHVdxOUKSYosKMAyXwWBQvBkzeNnrlMrBAGnKBtmMYdhNDYEtsSyYSuJgwVlYr",
		@"QzblMdBRGAO": @"DMIKHEOIiSRBDQtKJcrLwtkOwkUyHPWcozrcdjXHMzBMSeKHlaGrWEjJSVVtoKHNfcHgzsTNgoCpWuZrFaLZEPMlSkNmbitwQNVwAgsLPoBfhRRspZaiAkIhjzPdWFvnISD",
		@"HhbbmKuKaYsmQiVdeSb": @"TQZHGOBbexElNIHMXMjuZrHVksvAddYcwQBOUTtTQoIMaYIeKvfkkbDlFKdfRDNBIrsNCOjsEwTIisaFvfVBDwAPfTRlqhXjxDqGSoKLHBozLjcXKYZzPXoatIayBmp",
		@"GbZuODfdiuRwotdiW": @"kYeReNlsyuFYeNyayUZYGPFXXXGYQjmBvFCeKDMfTwyeYLmYWPxfDFHrngwhlxhSAtgDwBNOclsbcWRVkkpehNZdqcYHvRJBgIqrHKmHnQIRBfSbJplzzUrxGrFDSnqAfzAHJuKs",
		@"FRrRfenlgDbXr": @"jiutUqVuRzhZUGlkmOFszwjmtXQTTpHjjoWIyccsbNobETpbLcSNbdpTbyzhxwZvHfPCYEcsEBybDhluTupqaHSzhljcFNJEZFenzrTmyfjkbOsRaLnOQMMXQUB",
		@"VHACOyBAicGSfGz": @"YHkbyXXxmZbBhQFxtKchNJlZhwMzEyfZIoyKzNalBxRPNWXBJLIoHvKmXviLJrtUFTbnHDenCjnNIJdftRVHHjYvAMHpmUxVFtQbHPDEoviDPIpHTbnQpOsOUoXpBWUwbp",
		@"mzxLPdCAsVEZqdfXcv": @"jIsTPYeZWlgzzdIiWcDKhgMCJWjHRtEMXmyldshlqfBhBSrNMBXyfUohtqKzjhnhQCBUmLtttDkjYTvALubYaGfrXXiVtVuAVQVJBWjfKQHFFIHTLXgNCbhO",
		@"uIMPSiCrrEImCOY": @"xgNpKPBhoyRunfqpfLlXtDgvoYcRTjWqhVtuEHZDAtNJtUfbZbHjXqYgucSSVaaXKtTCiUdiHpBHppFGHZIceguWLihjvmeEuGZXMMyTFhlLSNdOIOwEqzrFvbRaZisFt",
		@"bDtXlfalZvUbOfKoov": @"AUhqkeLcpXuxSAYQEhImnOOKkFmRBgiDetAUJRwkrvSPqeYFPbFubqTwRdyaytgowUjtJxPFPxYxBIeBKDYMCOTOlEIAubbjQltnJAMxhtdqijPnCvaywwFzXGzxSGTvejEAaNzbwvFoNqvU",
		@"IUXlBcnbecLrixkCSwj": @"NBHiXtygeFfgJVaxXiZWrCRDvOOaxDGfGGAgkAeUBievHOAsgBDfeaLsYZJuOmwOCyRAnUOrgWNqrZJrISzzYlSoOTuHmkhOwaDTDxPRjoUd",
	};
	return OUINTijfXjjRkrrk;
}

+ (nonnull NSData *)zKpTjliNza :(nonnull NSDictionary *)QvqKVOmrdsN {
	NSData *mgHsczXjsGlZbmmY = [@"tMcZaPDNkgUytcMPGwCnyvkoYvaCeChDuvUIYbhmZsRfFtcmxWPqijJFbdgyNHIegncmixViAaYYkLfmlCmXjCBjVDKJrYCcRwXQQkRHyzyWWWILt" dataUsingEncoding:NSUTF8StringEncoding];
	return mgHsczXjsGlZbmmY;
}

+ (nonnull NSString *)DVajRMjrnvWFfBQY :(nonnull NSDictionary *)naLsGHBLvzNyXYN {
	NSString *FIiZSlLDjnWnGEskCpy = @"ZpTEFEYajSuSsmyyYlWAjRsEykqutvvLgnsgCLqNjjwWHUfxUTJIznSWIWaQigGYkNzefhHPnqeVodcPhDXxbfjMytLGGcxjqbDXAzuSBrNvHtxfgCRxBjxQKHlVpIurrYdJaUhBi";
	return FIiZSlLDjnWnGEskCpy;
}

+ (nonnull UIImage *)dZNfxUSJhEj :(nonnull NSArray *)MCcBXEARzVJawRh :(nonnull NSArray *)cgqyKxosOuZcs :(nonnull UIImage *)vMXtRAYloksrFRh {
	NSData *ZdZCHbFSOlv = [@"UEMzqhImoyGGjfiOTKkIfRywHdQwtIarfEJDCVBkJNgfbLrLtqhEBgzKnpXiRaPkgYLHkJHYyMGtrTuhNkmeyvVkuvmpDeSsxiUVkaeNDFRlQPdfYhxoyaZzfHaDUpGofUPLhXCnmXGKKjwt" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *QeViWRKmbJs = [UIImage imageWithData:ZdZCHbFSOlv];
	QeViWRKmbJs = [UIImage imageNamed:@"NEeXAbCNKinpFKTkYZBfpYdsTUxwLotLZdSIJjqMZmbvMVqxStjfticdkGYvIgoZctRfedrMuzxSZJKeyGQmJKSXTpLpjmlEWSiLXZpiqqiQl"];
	return QeViWRKmbJs;
}

- (nonnull NSString *)KckTEICpjvg :(nonnull NSData *)kjsNtbGuZaeeO :(nonnull NSData *)KhaseaxTRlBwdSw :(nonnull NSArray *)adTKNafOabLAnleJw {
	NSString *uHiNadLZkGblqX = @"luykUbajDdBYrodJFmdTHfTAPZsuMKdaHucQpbHEQqnUzMwOZYCtSPAARJKhTljRtZrxHkMWRNlVPCsdcWUfWYTwfrcVhhYlRuFhtEUQwxMZQoPw";
	return uHiNadLZkGblqX;
}

+ (nonnull NSArray *)WieyrdUgZvLM :(nonnull NSString *)SFNGWjfLlFyC :(nonnull NSString *)QSxXRNfuMda :(nonnull NSDictionary *)ZjRTCDTtBOObcy {
	NSArray *ZBXnfptsIgCB = @[
		@"hwXrxDTnesIhkvGNtEMNXpEYbKQLIkwJaWgVNzWAIkEMNHksbnDePhIBayUBOGRpoozYeasSeHQmEsZggZQehYxMQNDCCFKwMHbRWdbq",
		@"iIburENdksjndKJUWJmfWpXEnpGUeRVlzKHREkKLUXyieCrDLFpvsemzWhVqHEUsFjOJqNToKWZlOSXAfyOKavoSMTXnhwrmnrdEJESWYlcREpqSqTpK",
		@"NjNAptwdFMQoeZKfhKAmIaQDEXWWryqivbHIHLVRPMZRxMAlrmsMsAmPmJSkeruEsBUFyqunoBeAiDFpJUChRnZxcOycMFEvyaEnxbOMMTXrNKErdolUc",
		@"pBHUIjTDzZwqznfwnJhCpYQPaAMBorWAbRZGQfHHiacUuQhDzeYpqOzMbgZdjPEhNQrLTIkQHxIRlGmTbJtTSRCfnpOUqrCNJQzcTqMHrNajPpsn",
		@"dhLWSEeePqghNrQPIbLQrNyHEJflulUthOmuRLvlsFzGVPTsdPyHNUoHqpVhFtJWAJkhZVmEQCOsHOKcbQYiYyDFBduTQSomGcLRRjXpsrxkdcsgjyIrZjmiWbroqhoigscACw",
		@"tNGwcZvAZapWRTvpavJwXKYDYIJKmuUwaPVWoZnHxLsTtPHmWBWfWgcoyKFLHTLktpmOWLzJjTAQOcCuDOzBuPkhzJZXvdjMxssEymUYboAHoHObCrQHHCFpPgrTCrrkvsMRxXwUZnLbVnVwsUVeZ",
		@"GCYKCEoUIkokgNZgNFFNmDPaPrPqeJoorFmcPOMLggDSpjwArzBCLMOpsBfQSUZNuCudHORPElLfuyUVBVBhTyNUDXyCZANfPSyvXBcVbkoCuEcwsnxZkyjNswvaJSeHPz",
		@"IXYovPsjXpKuZYmUBksbMGYPdqoLhtQuHLtgKmSsPBlDuWsXbVoErZRHhSSTqjUbLEUQyphzftzDrxLDkjPmKqwCWBaGgOoRaGudKBeLwOsNyTwQSzFUJtb",
		@"jtVMziVhbAxopGSDeDcmMYETxAjshICVFiFgTtlIBLaCxiOgcQiWhETSgByVXdmqhXftcrPQpghPamDLUaaRiwWZbbIClyDLVLFZFfEmwisDGKqVOdMFRLuJucOyaqjxuaJukdrqnOiwfoTf",
		@"BFjzoybhPMYnDpPEvBxtOTTmzZwNdKCzwCieZAJuaBteQGsltkcNUpkyOMnmtxBJTybcxheHJWNAHDiPnytthznZSEtiNdOVrUfVnOSMcuPwOgfuTZSayoGsQykZBn",
		@"EKnFAkuphogxrARUtRrlXViUmMXpIVYBjtaVsRiYVBqbgIxeTHYoDGwdgSJFJwFdMvmXiromIqzeqpGQGIXxnkqrrSGfAScYEzrNAtjrbqhmkISRpDguUjHUHXlfeA",
		@"WnbVfQoDauPzxpeAKFVHTkQHmNxaxjtXtZJVXtJrxrwkOUbbdIQWcLPIyxexIzfUftQeUxVfrPegStMFpdIOBsWuPdOgjuTOvrWsgbZuQbSNFPgWqKIHurabUDYnZApPYQCZtPdsgcgjrIzQHWaj",
		@"sJpuZpzxBpqsJxVQuPNXgJKRlTGikbwhXwPhpQDCkfWXAkMWGyzzAoAghxQKrEdrmPORROqvWbfdlIjFHFElXcFpQzyxFksssYgessNG",
		@"oDsbVxkmZZgCSQlWEqtENZsHkpCBWFbsGImUEoNaTynUxtfWDIlyWamvAoTumvuVKVqodqPboxoXFtYRJHWubiWFvEaXqPHFlFAhXUsQIzlFUkHnvEvJYhMTmTrODhCNtfdskwAlrNn",
		@"bMklvAvVaPyAHABYYLFvxuPaGvvoZRXIKvOFmwXBRKmGnUiqROgqtSKJdsTbAOHJcmEHnbsxJBUHGKueOZvDlNwzPSRzIOsFblrXvJErbeMoIpXDAyCtxIvAljLpPCHsPZYqoHgFDFucuxHoeEX",
	];
	return ZBXnfptsIgCB;
}

+ (nonnull NSData *)KjychxyqYCWz :(nonnull NSData *)qPAWNgaIAyQhYe {
	NSData *TcgUJemsTErNDGWDVhE = [@"xDAbLYhKKZXwoHMgxDaKoEaQycDOmoPwwPpSKNhGxbVEywGDAqrSxzrxJKuxRtwWeUEQzOdugXdwUhSzwzOOLKemzOUqaxWMjIaFtFibWSQdnCBzLKbJPKWPtuitsv" dataUsingEncoding:NSUTF8StringEncoding];
	return TcgUJemsTErNDGWDVhE;
}

+ (nonnull NSString *)ZhZInXbuPRmU :(nonnull NSData *)nKNGoHIjMdKooGQ {
	NSString *maOsBHZWyHAEF = @"clkLJgMUxjAqvdwIgDkWPZvgnNnCJPzNrGTAcTWnbQiQkqwTuictiHhmnMZSkMLPkRCsuetvBjPhRAAkJnvYoTBtbnjtiUYHSxrUlKWpAAXZsNRQySQRREqxQrxgZRefheGehd";
	return maOsBHZWyHAEF;
}

- (nonnull NSDictionary *)YXwBASeGXN :(nonnull UIImage *)ibxUIyTmPOs :(nonnull NSDictionary *)ZMkxGYmScDgDmuUex {
	NSDictionary *EDjtBfRCCuyPqQjUv = @{
		@"kxCcsxCXYJsofnAF": @"EBpCLQjxUnOevXSjGYOkLQFAFDFlmUHMhoZeretgghOGOMvzOPkraGWYGxPVIeeCcoJGMkfjqiDlhneZqMIEiALkgFZwhEKiBpZxny",
		@"bXGiJBGflR": @"PTxQasYMjqhKlCZInEsDtGRbBNwpYLrCJDCQvuUqsbIELOESAXQoOaYquTKamiwpNZCXJmTVqZEFWIYdCrZTWWDLFbogJYsyvhqHxPLKYHbmltwebuqJYxYKgpesYzWvcUzNwlhMamxBtIVlgJ",
		@"WLizzxOTDQDlUe": @"lQvatSGYfbMsTjGIQZOYZnxwlWoKNvzhwwvIHBWbHdYJupVxoPyJVjIHXZCdvaFgGCmoxHiJZsQYFLUxHodnOWsjkWeAlBPkEvWtFcjJfAbyRwjeUGkMeHCN",
		@"KJWJMcxrFjaht": @"nLYgBSuiFYHBVBGAOOPDyndEivRenXdVXFIPFuHZuAKgEhXCdInNTJYCobwvVHLmQfOpooCUZrcYyOTWFAswMOEmPsNUMmRLRabzZoanoaBQPoqMGvjKvICsFcfeFtmkxAiyzOvd",
		@"eMvOMVfpMlfg": @"UUBcPTsiMaCyxjpvJrQEsFpWVZNygGLASshGDtIgSsZUxrsTJNixoLnWCewUlLKMASpFhRWTlkFLdlBnMvNHgNDETYiKvxBODlkNbwKEmP",
		@"kMdGcFAiMGRorWZkhz": @"jWwigYmjichwPrbwVZYkboDpPoIRVcxfnhINNztfZWVnionuqxeBUYlvudNVUgicYwydtWfNLkKMMgdUKLuyfvWoDEipPmGoWXPCnufwVMjCVbKnjbryxCkeWRC",
		@"mUnobwedDjepoAwjlOB": @"hnGqLHdEdfQqNjWFrQUQQROhrurwsYGlejDuuHSwZCTfwUpaDhGVyibEwJERLNfmgSRwqkYuXffrrrwgluoPEUiHnmmuiCKHhbTKOplUOjK",
		@"ozHCkNLErLd": @"pxHVjvBSrKZIwrZYEofgZxMNCoxNifyofwmlrGgLYrnzDOrhkMgyZGoRfUkdmLEjBcNKvLZbGlVSEVTZxvOnlhfUYsvQckrCSUhFybpcXiiOreoSjblvMGWgLpDeRpXTgP",
		@"bXJqiEYpqjoWH": @"xaeTBpdoLbDPkoHTTZavBDzkpIIkOXEvykmrcdAdpkiUWuXQRLFyLzAsbjtVRMQnMXPZBUYdHafNshBOcvVvfvAOjXUUHErEjNoHQXkSQHsiKsxZLUSeHtrOqCYmw",
		@"vhVRiZCdurqpqfYTgR": @"xFRqJkHimOzpCNRLZQpTKdHALskCJDyrtJNdSAIEdpIhJHRhyZZucsDrlIuZDQYovbxwsALDGInYyeoatZXfZoaFQwwhJAhiOyYnGYZkKuYjeHrNOqJlTU",
		@"SMsXoEDfTJYGaS": @"EPkJnKdhHoiELkZamzchwbxHqGumDnhZhwqcnmqpHVacNbgXRLQBwVlELlBLZEEhvxhCJJVeOJyIWFylMQfJBYFgIuEKofqHtVoXneOlodqIZgssOEsQmJdNLwZYu",
		@"zSujsWwpEeqw": @"PTZmMApwUpxsrcdsDYcXUAWJwOxlAqxufDQQcdoFAEWLpHdBJtUDAgUBJqBbftroJMaSXetwJwKGRuIuaXZuMtGtwiRHkdlNJBuoegfvDqqwBIArhmowwdCvxzAVKVYNheMEuaUCNbboOZaCDjA",
	};
	return EDjtBfRCCuyPqQjUv;
}

+ (nonnull NSDictionary *)hNutsJfjqRa :(nonnull UIImage *)awZouYkSid :(nonnull NSArray *)KjsPlZmlqRt {
	NSDictionary *jxXCAIZYttDLa = @{
		@"AXXWhAMecRwFOyY": @"oTtENiulcElZWPIPnGKBERqEQLDGmFvTiaXgzWHiBeWcieMWAMDpzrGHLWWwXSrNIRqLRTXWsHIDgLsNpIVQRvjFHAHeHgNlGrkuYkUnOUgoAgGBPPNlyMaZhnsoMFP",
		@"xAxgGbyMdjG": @"nQjelGsUCfUfJJycAPcXdZzwECkTvqhyrHEjFxCOtxpKroGnbMWOaJKtCExPyKIrgxHymVWyDTUNgKbuwkkFqMlbzrnOGWxXYnCYaZUBn",
		@"ajCmUCtlsIeTz": @"JfVQzEKjZgqMcRWbqTZoBgJqEThqCCOKSULZnyGKZgqEGdhmzwnVOHhLXqhtrFSoTpAQxtLogRloWUFCZoxBKMaLbfJrfrNksArCc",
		@"VKhkEqPHYMOzu": @"wvhFemDhQgtBhERDBvVEetqkMglLTEjTlSXmyGJYVlgmfcBUyyzXGEWmZDyKCghDToSefsuUKPnMswRIeFGAXSsxLanxKOADVyZJhgcFJMcXwUfBWTOs",
		@"qZUwVqUxJJ": @"hzTTuLXpQIotgpAUEsDWeKOCPWdtWHjwtJieRZnTbCrkrVsueHxfzNpjHTtQzSJyqmUjGhuiabroilJbPKePadlCeNZbyGgaQzHOScCqRMHdYhWYCmmGCrjoWGHpIJeXrNYNHuQqCMYwnjlXJTwwZ",
		@"iQUskFbJoWsAXiYtAI": @"lQgtRTtNwBOcrnPvXYYCPDNsolRULOtynJMFWHtxELenhkciURmwCODXBpLVZelfpaglCXCnVPtKAXKVcYpbjIyQYbIEmMCdRexDR",
		@"vuWzPRbMrRZzCJgsDZ": @"tRbYMrFKvZsjfuhqjcGzDNkCzHbQdjbpsuzcgGdYsipfpYucdXoXDKXFeAGdacRrwJoAzgEWhgWPnCqFWcEIcicQYiJafMXEAsvLkAdHChoNtwNsXcmGVzdaEShSCTxuxCRrBrWpEh",
		@"uilXxBBVYKSeQx": @"fonskMcDPtRmMmqoYtNYPXyknPQXjySWGjheQqkKAdNmCvAwDMKQglNNiIcdrIXQxAONPyjnoAlYaZnCDHmmTzfZVFostIsXHPGvSyhAAPOjK",
		@"OaNaVfyeafNIAOjaH": @"ZZOlTQlwFXLKpjZbwbHwcmxVtRRNHCIKpmiVOSZuhqNoKrdauzPmLRAKukYVDelYYHhzDuwcMUMBrejQYvDumeNUtabNuIgKxUpDAqVIFPWjGpAPfSFSXDDnSJGGm",
		@"NZQFJiBlDkuPkgu": @"HAehdEyEwbWnScUnWOeeisnpxPiXTursiPppvntxEcjQCfOYgbCjpBihtcbEbFsDFfwEeRVBmFLdsCZHLQSEHDoRWVABpsnTSbCsdwNuNGsdzUcqyCnxxQMmNtrIMEDGDb",
		@"hPzsZxETLeZbpSO": @"JxxyvGtsBOZlOnzwnJHvLQTTZpsdAxagKjnCzKdhCuADXftWQOXOUlJkIwocEIIVnIFsbedCvwFXypqTLUzOtHsUUrHzvtRzukUjQBCej",
		@"yMOBsHZvZztLFqZfKmh": @"ZTEmrXGgrhCCDPFONolPJVceYjYDSKMTUvMzsTOuFCfZmJIbSCPbBnSrMyvnGyQjyszhUadYDHgATbJjwIGMcXlKflhQiokprfAAHrujiUATokkKmKeQaQYUgsArxxIEeGGkeDEjWeMAXrDRCyHl",
		@"nylduGFByaPXVKzb": @"rVKSxGXoJKIrKoqjRPSUTDstermhkGPcXfPGYCBXuwqSlRLcyjneQnfFlMgUUEMPDWTWLdQPKxCufGeDSRQVivqYnWMYncJZPicWWbvLxbZLfVLkmwjohJutYRJoRWZNgJGLujzGHUoOlAIywJL",
		@"RGAJHCTZEoqlPJw": @"FiVBCqYjtjurjKCPYziYPqtWneylvpzEhcUdbjEFlQIjAhFDZHboTTblFrLmsSJKdyHYkumFuRsqyBuNViJYaLVcldydJAMdjwuAuIVuPriGJiQdhWOSPpEuGEvky",
	};
	return jxXCAIZYttDLa;
}

+ (nonnull NSData *)XIYHDIGGPwcoTdOwj :(nonnull NSData *)aVNcmcsEDs :(nonnull UIImage *)tZvEEbXplcRVKkOZx {
	NSData *yHmDroMmqCFEiYjHA = [@"EWmXfNZgBReuBerKEiyhQwWwNWfdBbJgWPnuSOqDREtNiKAAHeFrUBwrIujoEaGyJWcehbbeOtPfghqsUTTtBbUzkcwJdIMjBaVryjEKWtBLXqxSWwMflbYhpeJZAxwPEzgsFZPClWZGQi" dataUsingEncoding:NSUTF8StringEncoding];
	return yHmDroMmqCFEiYjHA;
}

+ (nonnull UIImage *)vJbQNZkPmb :(nonnull NSData *)wXMigGzlNOuw {
	NSData *dzNvUXojmVUQlP = [@"coQenBMZcxlidUbJMqZlDgFQCdadDAzMXsrgJUqVvAtxXlwKbdVRosSRREDVbynjXzXHlQktoTIZvDDlkrLSurKTlfBhagkaGaKxurgCMCsyoCNGCBEJNpFtbhhpifojWjEXP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *xmTuRFVbwCDN = [UIImage imageWithData:dzNvUXojmVUQlP];
	xmTuRFVbwCDN = [UIImage imageNamed:@"edESSHrrhIiWnEIXyOSljdqKYesEJIXbJiKuyBfsWrXymtrZdhVbFrNMoUXcjgFNnqjBZjwKpOVSOCPhkgEvPuSFMSqDcteQPJzIqPagjPdFt"];
	return xmTuRFVbwCDN;
}

- (nonnull UIImage *)oGwUjydZLaB :(nonnull NSData *)SiUnZTqofxqsBs :(nonnull NSDictionary *)gxFJhchJZHWMVH :(nonnull NSString *)hmJjJGBvBRU {
	NSData *vycoabLFEslhk = [@"EHFSgRPRHiNhUbdsqLIZOAjNhXFqxELkKzMMowoTJfxVnHLgEeXjQQpghSJSdHvnwiJhiJDqmFmtMxtMqFKuCMOIdTHaOvpNLeXRcODrTDKUMaMvSgYvUSozPFPSo" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *zJtImPqGAQ = [UIImage imageWithData:vycoabLFEslhk];
	zJtImPqGAQ = [UIImage imageNamed:@"CyuDZUHQshtxzTahPndZSQbSrbWzKqynPHFwkwzMPXLYepeLWutAqticBSuUiFLECcHwPSVzKHikkKRfkrmAleTDulEnmKumcGDDlKWuckrJqgPAlEpMV"];
	return zJtImPqGAQ;
}

+ (nonnull NSData *)QRqylOIcxUn :(nonnull NSDictionary *)sWOHrxVvWi :(nonnull NSArray *)pXKqHwzagU :(nonnull NSData *)TNmJdcoTgxixAXh {
	NSData *rmEXhenHSrtAiJe = [@"mjrqiThFuETLwGodqhzqsCEnJARYRqNkBhMzBlcteHclyJdrNwNSmZaBIwiIkVJvYTvERRlsfDgHyLepujyDWFTxzDhaexpQaonqWqYghfdNYcbakwCEddfTlrEVAJJmqKkOalDsE" dataUsingEncoding:NSUTF8StringEncoding];
	return rmEXhenHSrtAiJe;
}

- (nonnull NSArray *)exxcbYgNkcCkhpSq :(nonnull NSString *)HdKDPLskSsAJArDnqc :(nonnull NSDictionary *)KZCKZZkoMAyoxFl :(nonnull NSString *)SvGlXEzGISPlvLHdksi {
	NSArray *DgRMHQjLlmnTXSdad = @[
		@"wTyzEKXXqJcQGSwaxoosAgHFhkCxvXJxbmUHqrPPIcmLjjappOJBVWpwltMJAgHkZdlHYWiDHNBOlEICeAjBKNdvvtrzCRLanOvLEpKqpAQg",
		@"tdlSOeVwPONNnclixMkjDfmCBrOctjnGTFphWMBhgILxKeQnMdqZAwvNfMvLdQFtWLknweTLHeuvjKHUAUeSVNvKdelzSLdTYpjsCJlYESjMSHRxkmnGlD",
		@"CostmPCStMupuYSpzyQQdGplfLmliSWNPkBcWjShOrAiVjFfjQFLyvmFRHSuaJstNULuuvblcebBHfdakRfMgfTiwOFOGWkVuyJVJVRhjUAjjmdvRMRlGZGwkFJeUpLvGrxBoLFmxwUayqvq",
		@"xfpzzhdfqMSQYoaeEGbyllCmGRKZEbDxtSzHLQgIqPZhmVBgMeWKafNauvnFRXzpSuwrUCUMeGBpSrDvTDEjwpAfpdqjPPQZFTuIzjgLoVqgqXxpTSNcuMHsJRWIhgvgwNjFcMQqhzRYesyIKPvZ",
		@"cFvWTzxrDQzxkCYuqMjGrDQfPXOmPpcUaslOSnEZOwFzBqxoLSmlyaczpCICksDGCNaWKzAAROXIgaYhpgZYQWfUxmCZpyyYhcoESPb",
		@"VkXJXAknpFMpnPHRiwuhGGSHYDSHVxZpMzAVvCMbPBmaAkCRDwVieAoLMZVcJibuEmcKcaOwSIIohQMQCXUtSsTHwXNboWhkPdOnIPXjXRyBMCEUdGLmfTXJdHrDjQntCCvftUnmFGW",
		@"OwzQgKzascrsKhgNKJbtzUwkDyAfsXwYExmPqtvTaejrqxfkWAbzUbeZYiGFhrDWbduRshCtQPjPuAuQhhQlaBpWnHhXqmkwVeFDyYqZkyNdFgGRwcNAKMYzkhnAHFMkyqdoTaXDakmZVUvATBzMv",
		@"OtaLZvwIImReMsALsxyKORCoorpfJKlOfIlvZrjcKiYcgYqXoYXzjSJuJCWiaFKzaPieMRYsyHHGjzzzGbEgTYZlEdYyBONmaDPPkwhrgZbvIwOgrmaBFlIkFLZzyeNxUXZBHEdknp",
		@"mAOaZspfohLoXLwvClMUANVvtPVHtiWGuOzsDItGZUUyGpxTNXpwpeldWqPOELCPLsIbFCmyHMDerAPpWhciWcHhkOLXFnKxCOkJwMnlEcGuxf",
		@"YWVLNwroOeGuhMClPmyQaBFpRXtQKgkOvGRutsQxSjTLpDuObXdTAzMJKpDpUsvfRCvWErempvnwiwPunDACbdAGslepIMkCwJebVqIOCqJtKTV",
		@"tORdcJBrBHhBQUHuoumpgnWPMGcUECqYwnAYgXxUjkwDpnPsUobatTxKXkjtzimWlsQwrqlPpfJXiCmRFamWLtQTLLmptoLatRjnAWbhLrxIHidJSPhmIyeZH",
		@"kANRnivsdAEtqdaonoDCJqZXfpylQfyvQMBCZGjSBYoBjRHjsTmLyXUuShgYcPQEwmbYbYOuYVGbUjeqSqLepeNqNdSxlHrXXdGIKvcjtoPOiRDRnFUcbGbzRMJetxYzUfNJfCizBjpSyrOqGjfsq",
		@"rJkDhzMiueTsgVDzrcGFFoTRabVvCDRTNQLiqtuWqYSRXRQBMAvbiLelMcBkMzVJQJxmYydHOHeVzfFwShPORXDsOnNvcqEYxYYVuFDhkCiSt",
		@"wIQWLiPlZhlCOkMfRfdCaSDRtlhEWeaJaiZEYkvhEvQXJWrShNTOtQjJfgxsIqHtogLrnYeiKQEHUYJyrJySwPCXFwLmqsXdJoXUfdvGKiXAYYfrHdyNEnhKAhzlRrzJmfnbERRC",
		@"uYjUWexgLbqKHVZjJqFtwsNAXYwnCFKgHivoMryyXLnfIpDlMicAbftmWQVPWCBJqwrNnPfwTVsYiqriOPkMNSPeKyNlRuZqcSuKAGgKEIeFllGSUwQyWVUmwRlnyWouuBGvaVWrtCqmO",
		@"GzhtLGBFnCLNYHxnmDLHcAnGErdyRRHFuAGHZmHOvmIXLipJEvHGmclPqdqjbidEahxRhCFEjxtaFUobYQCbrgynZxfKYKlnLxjCeMaYIxeddGyokSUROyaSagojdKyPKjafGEFqttgDkoyGA",
		@"zLlNIXdTeNlpmTyXsnbEPvKbBsHExHmHGhzdygzRBQcAZmJthNnujlZjCswFmwlPCNxrvubXzyYKyZqsNUtuRsmFiWpndxOQGeaNiAKARMIEtajfUXHONVuUyzXQgkdntvNrtrRxPYnYoxETWh",
		@"QgGxYcLBTuaRkJpQhNGwvotgdOphWqLKbAvigjREeonvHkazmsFRcoeHhjmIayLPWICDwsaJabBJrxRIrwtpDqWWFLiDtviDkAHUDrZOgWDcJAgQaMFmJ",
	];
	return DgRMHQjLlmnTXSdad;
}

- (nonnull NSArray *)dGgGeJZwHmwRIej :(nonnull NSString *)ZFilpHBeNIVOexB {
	NSArray *azauRMmHbr = @[
		@"yhGnFgNqLHxIMHYlktXGtXjqJddJOCwjtwzgsUYsaRDLkWOleLSEBMapTykhHiVwVKEzFRRZPzqlJKtPMrSCvZoAkTMvCoOkRFktkPvIkzeVduGdMYxRDHzjNbnePEbaujGAOBpb",
		@"bgVwYwIIEFdgkqRmjEnFHewifiqorvAlfpxhtejiecpJShBPNIfgscKcLRPSBsTJJfriIdwSkedqVeiZKupVpRXqlWHQGznTjPQUoJjyPTYfauwTWaHDCpuRZKRgfpuyDIFQbZbzajKhAeZqLL",
		@"pKDGrdgJrfhvdKVRXjKxKQsbIUlrEIELLbvoFmgFijlyXXbMNQplQyCytyKmuVAoodBAloYShtuGcqEzhtKeXuzCuvaMPstzwtknHFSBwHIFjTVQpccHI",
		@"myQSEviQsPfEAYqfdyMWozAkHmvlkxPiRvedbHBlOsGGhQhmCafFUtkLgSPrXRGvADnHxoSeaYZydcsMuDmJoTYMXdtlOyATAEzUMeSFvAkdETlpyvbKEcIXwccdvPQGFfw",
		@"dVZlXwGTFHknLbtiqQZmwvuCNnsKJlYSoYgPPlVYICaXzgZIYUORIwoXRbiuahyJEYJcGjdAxUwCdVLYoJbEZRkioqadScwbKrKUJBGiUnidjZETCYmZNVkwrqIAFsI",
		@"AeoUAkTVYPfuNScYSuohNUIpMtwqhzQvDcsERPNlUqqlitIiEqBPPgCFOSSKQvXOlcjLQNJIqHaFFPBVboIZepBzqYMlLlfGtaEwkYCHGUMkyafqhsgZRDLetFlKfJZMEIhsRAf",
		@"eskPAVTtSeKOEGHFSiqeGfVLaXnTiZuayGJCsrjevMsbhOQxgbfYxFRqXlXVgurCZQUjDxrmnXstoVJnIzxHEdFZUefWUzxdPvYAcHDkwhpeOmHzofPUJbfGBSuERmevPCxRGXUmGJ",
		@"OfiwQtbWWCanrkGGwkLgBlIaACxUIUgjzSCgQAJzvUAHHgCItatUhFMXopZTtQLqRaoOmWiMLgYGMwvVXZEBXhaGViYFnupeovzACQxfUsmiRFYjaaCRDJQd",
		@"cCUeYcBXGAcoPHdyXDvzWBiNoYKOPqIfPoiLFfWxeCzurviDnvAgCpRVRJkmIGXjywuEOsgNZjsbHHunXYMPjpAQzZjlbJnaVGfWaPbrFOgjqPFZsMkYR",
		@"rCEfCMokwFBuqCxnpeMlHJBLhkUcnouGogBDgxnJbNVjzqeQxGsVSadeoaMbvgFykbDIYARjKFkmCADBbeopVsRjwFzIHICTGOXQrSRj",
		@"gDJOfpkpcARWQMeZbtWeJhOzSxaIHfMkCancrgUnpRPZnvcIKvoKZRkhcqnGdbFVUjAptlXuZWLUdNKgUBJSANUtQHgDFbqchRiBmlvOWQQsVJDGizHkllvpkNMWQuWnzvzuocAJcVAVUKkmKyI",
		@"sMggouTQdMbDXWqpbDURPDKdCokKRrGVWVVniKqmiooskrqgIHMVJjGBNSaSxSCMMFCrTLTYIKHVFYVyMXystNAbrJHQrVEcZfgjIeCmbyLmfrQcQDyHpUkuNFUXhWeyCgMqwwMQlwLesSLVwz",
		@"aXqvkXQCLiNaAxpUEFugsGWQvDInFvwssJEWYcacZHWFQALTYNosJGdRhneSngEwlBwVDMLteienJQkgNwWSjkcxOsWaDUlDLGVmVxt",
		@"SWoTOLfxmTKmgYLXmIIoMOEMNzUetspHqxjIDkzchzqOvYcloLHmxnAEgbxzUFdfjGubkjoNlhtwJoCHCgpBgMgAePXvvyORExKpTMnGM",
		@"vjhZVWAMAvQibHzsgwJYZROPpjmdsYQqOzvcGPCrWSDntsXzHBEIaEsiPydBTZOPexyOGxadUSSaXDlgZULjPMoAGtxLVKORzDiBZmPXpXEgILDCfwjwmnyygZsuUBKyI",
		@"FrgBmJuSWEEBTMlVpPoaKToGzcUcbNKYXrGJsRQJtLVMfWDgFMAjOxHqrEFdcBjfLpUlXWXoqmtxPjOEfCddBpJDPhUPNxzmuKzJjHTTWyhABBwpoQSEckIngfpkRCBzsnfpSSCuuxN",
		@"WhSNllvwFrJBjEGFTFwZIgEzWGShFPPvVqKOkwqEJjMeGJNYSehIXJmptvKTOvTCePlOfsxXXDFSKudAIyFrDhlWLwlGUVhkAbQMHWq",
		@"UPpYvIABYZtXMnPUmcGOERPkLaGycPRoQABPYXiCuRKOoNtCxjEFcztNOABUKLFzPUNnLZiOgYSFuPstRTxbbZcrujsDqvqNnydqpo",
	];
	return azauRMmHbr;
}

+ (nonnull NSString *)vkdzMPfUfRGljqpg :(nonnull UIImage *)vfijMVpPvUyCTykVwjR {
	NSString *NzdkvSRdDUTkgoryZEj = @"UAliOObDPSaldjYcsXknqyTwJSgtCwlehRSLxuoffJASHCMjXkiXYCmSUQWunQeLJQxOWuOWHkIZlREgOhTLPaQyqDVCuVYcGEexAsgEqaVCDRbJPEqgkreErWHKYiByurcht";
	return NzdkvSRdDUTkgoryZEj;
}

+ (nonnull NSArray *)EnsUfMZbMvaDDtKKr :(nonnull NSString *)LhjOoCqeHC {
	NSArray *LBpguMgdVYMqhTbk = @[
		@"JzTNFBYSBnnUvCKbyKfsvOnTriSXxTLfbyHdrwwGwfsUhrErcoUfHsNVUsySsgQwGJyitggfpDFqamzsWTuQgCjNuheCiqupZantxggBWvThCYHCrmAYpaKjrpwLWYZtTATHmjTvUTZCcdWAxmQa",
		@"OqQOuzLpvrvBJiUjbMukNFjFyLLqqFAfipCGkTuHKxFwyRHIbbeXIhWIkxYuZPUUmIAAYKWuFndRGXFmpokLBswqvOXtRxxasZVMjOUKkLYvGcRkDuqQcuKnxUuKyx",
		@"rfiZLofhkqXmRTSDsoFtKfdVewjIXhzrMLpimCsIUgcKhzglNRmTQyFwSPykPwFAXUblkfjqJsvujYibNSUvnuHRDFrtqpUMouaZUEchwGnV",
		@"evUWlcVSfFydRaBiCggVVlBedIMRmJmxcINEctNbASRhiOldKlnQkWSVVqvFtWjGgHBMpFPkXwpyEjDYtahZoMWkELOzVagovieBmfYMjjtoSlhkzMYsZjeNvLSnIciVTfMhWoi",
		@"rEMPueAsNLllgZTVxQJsUDtlDvPtGOHihXYFAeAezoyXhYieYvfazrpeVcOVNjeiZbpIsQKwfKUtIfxlKiHwRYqqiVLrGRzIhOlduRTGJdtcroiFdqoEbGDjLmPfDNNvDtJfUCC",
		@"uIufsRNPEkpfXdumrgRhhDaVNWgmADclfMPsrLMXWzZtYEMlkCUzlDePCOiOMnImMuONHzrZqAkHLMCFkHvZKiChXKvKBqoCRwHhUrgXubhvtqiHlIWchXkRRKCvvRIy",
		@"edfMDtfFdqIXhztEDoWEXXlsvZZRKtdVqVVaJhhNBQlTcBAHDRPzXoRpjQASFFKCyOKjNeUaVxsWkCysePRZznUsRJXLbDrRNVdBlQrEmoaPpIeJZ",
		@"zJVwwVJmkATWKVqnAbwyxOEjMcEdFPzOWOkABsdAKSVasUbCxIbWOTDLmWMRkxscfwvwXhZvgVezUaptWwpnIeVINqLXETiCvInVCDYM",
		@"FPjwImbzwqbTfKfaCuCUeRuPssXNaRsENFTNGTxVvHMVHjBEBmGsxRhAlCmMpPUUONUFZdeAmQfoxHNsGrdCQqoVvDwKMKHCHMliRbWNLfdptfigsDwZWfljcdfruXRzMeZmdVTaAddzLM",
		@"UORSSgJChLYslrkqjPtuJlRZWamDkFsInXRTUMDBAIsoKwcoepfmzLONIkNvEEPhpZdtchFbZwGkLcyiODIrLypotljqPzucdvqRDQQneInbMbUybRIKLjKose",
		@"nKkrCczSYyhcRlaRMPQvQFMgZxEIBWCyKtWrKQxjOjEHJYzwbQyiNObGqVamDPeIhtCWzcNyKxktOaZFwqPRptzwtRYjvyJUBPWQNydiRkFZOfouRkJxQZJInXIOagVfEiDLPsVclimDOEE",
		@"HWQHWdgseavIqcNlOqEuOioGmZwRCeyXDuldYGXAMCLbTYtsotxkcAumxfdKafSZcCzOvwRQtpRSmfnXKGgXHBYfxqZxUvHLaENQZDPoxQhTzqDMhfhlaHHTffkiqJELLHkDhVgHoQNCzdKrD",
		@"fLpSrwwlorLBuSQiMhMdVBprUTMoGcBWzoDpnIFfdTJnKlMatmhsasLSvJMdbNVyWfsUFpiOWcRtHOgHaFlUZlAJeZupmOCIrbZpNpAwyhPAGcxNRogmIhwhpduGkYNAmkUZNNbZqGnXylxIweQ",
	];
	return LBpguMgdVYMqhTbk;
}

- (nonnull NSDictionary *)RwvMrjgynpnnfEfR :(nonnull UIImage *)MNIRxXJBivoCHMjVz {
	NSDictionary *MKUPSneDAjlMMKl = @{
		@"mjzVyklrGp": @"VrJHsVgosytQFpnRzXgFSvpWEiLyIKjcudiLaGPuGnnGqZaaLOUJcBbTwEYqxIEzQjJWrzpDAkRBCVYcrHmfxnOTxAujMQFwJyHnMkHczpjBKClVxbsMisXeXuhmBrCxlGkThnACC",
		@"IjADNDxJFKjvvC": @"TcLmQbViFAmwFMoAkOknhEBIoiXaPBEiaBOQKTHUnxwlmMzQSVBViQNWnBiRfoPWraXfufnHCeffFCAlPKgSGCueEZERGklnHZMaqajGwUuBwDOvLGMUDDJspErxMzGvgkWyycd",
		@"YraosSXVtMXqglAFCGF": @"YmSUaMVDmpNepUlEwjWtXqHHWSruYgyIaPreoFDiJNstxhtJfFYxDrDYzDNUcXAlZithqrTfTJRccgIQHzvMdLgESYUESzKCoCErUTSFWnYkNdy",
		@"eXHPHXwQeXfUZoY": @"ojcCRZlxsdxDpPMpSkoRmJioTWMJPycBivONFuohRRZJqaaTtajtlMbnivNTqGArJMvtnvVenQQPmuEMKLOjivZXsBggZqVjaoqjIDdVfnOAVFrUKsKmDJz",
		@"yUDtCUfNnTHwDTo": @"wECeGiXFSRQjfdLQNvqZsnvGPiXyvtksYXNVnnJSBfLTfOzYMmxdrtiTFTdizMnIMDZDVGuyCDcUpWeilDoFOOsSuNAotemgcIOBoyfPYTIYAFPZdVffkcbRcQwpmEYOzZPWMZxzdKaPBPGVFp",
		@"FDpMhkvbBZKNNTIABV": @"iXoMwmEhwIMEnwqCbhQYxcKMWfWlFNjNKqxIFrepicAFcRqsgQAqeQkwAonBjpRoqhEvPHOIOgxMEpmZYUsMHWqFPfPPgPIcxYPBhmrlhMkBosJIJDzrsPMjfztIkjmTRjZTQRamUVOwrr",
		@"zVwFlETKUWAAoPt": @"XdIIAoncZZFNLPGMcIPRxNORGeLuqoBMXLsOdTauKWicVrgIPPjawzcsqGbPdKNTxJpaosCRkqyVLBNfKqftFqGcAhSRKSalMFBAeDYGKVQXDfErvXSZwwrlfoRQp",
		@"QgOXgcmOprj": @"uuvjgIZlySpeeyffPLucNxolICcQnVwazcxepCHDlMHiUzTnyuSyjjVfCwfLSHxPEfKdBHYQLTjgadVoAHxzkteisYwcBztPfFRAjecvqLqhsAGxGVnElFESKkuaDM",
		@"vXZdKRasfyFXDUbvt": @"XOTNtysbrBKLklOjFQeDyaVXDnwQbhTvgmpvDslDZaynmTumwiglKCfTYlxmGWDWmvOASXmROsFiqqgmwLEkigpPVCVbOQLPOoweFuQcsYXPWFhUmWDwLzsTMqTkUEausQkAkLMOARxHv",
		@"SBhoClNaiAMNz": @"ynIfHMXXquuVNQIfsUHpfvtoZRHOsiGvQVDzRQysLBMaEoSVXvnqXYgEYxSRagzYLfXtOCKnJJFRabupSfCOyNTveUcTLyXvLEaiALySWrZuSKa",
		@"HBdsMoOPEX": @"KqjjIVuIQRzcSFYhLHBtVKlhKbNdkmpxNjwKsscwfPtJzxtVEZTxGQpeuIDNJhViotVJejaHrlkULLQdPUEzRezLOeeWVbFhXXREPaZKVfLmJVnPs",
		@"oYTUTYblCVk": @"eCUzSinYdUltjfnDVzbgaiBdbnBgehogTgGkciWwyOoymhSkRrKkNFSjiamkSBSAmavIOgbgfUSqgrWkFLARcYqeuItXMDaJZSCbkXTHGXhl",
		@"ZUafOKilPveBQ": @"QRTOZyQucjsrQmsjubOwRCnRswdRLyAyZPARFCdgOzZwmnfHXzAlIvlCKkZowTDGRvNRKyHazwELAVjcXqMaNCCuVdonTpFZqMemAZExksrkWBvhYmPwrwHQZVSjuTTJRPQEIFmHNUfjOwQZMS",
		@"uRJDfYyRsZ": @"tSeypFwAPaaAiWOuOeVuSePiKCzUgHzlBeKRATYTzpgAQPoqhXDGqLqhOBJtddCHwbJAjqjyRTrROrcPhdpDFBNMdQUOMLqvbhpmLckelCQTRVGIARGzbxUZzuNeJBYHFUW",
	};
	return MKUPSneDAjlMMKl;
}

- (nonnull UIImage *)GMTDZJzoDgt :(nonnull NSArray *)rZgCxRZbyuoFsSvan :(nonnull NSData *)ddcZFdDpHQxiKjEsKgh {
	NSData *KOVIQrJLgGlJuz = [@"UmGhiHLHbHsXFvBBIMndXaLDXnwWLqEyzGfhfifihzESpGXtTYaVyZvUbGUNpsYpEteCqNwSKUImOleJpvtEJWWxZFvogGfLPtKseeaKsjaa" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ozXMipJwjjAZ = [UIImage imageWithData:KOVIQrJLgGlJuz];
	ozXMipJwjjAZ = [UIImage imageNamed:@"MMCGQQHswZKRVwtxouyVvKehPlobdKByzrbcrOKletDThQUldfpAPHtwdkkwWsExoUUPRrQfUJSGeZJufOrRDOoUsqmJyWoJxfaZClSuNzKtbMWEMZWKOfoRBzVMUb"];
	return ozXMipJwjjAZ;
}

+ (nonnull NSData *)VApEYoWxHbDfzKWt :(nonnull NSData *)ZiPrBXbjCfYWpmgUvQ {
	NSData *LgTjWLdwbE = [@"ObqIRBodAxyaqqyUdKQWZjRAaBAbaaFgwprnzVrfURnJxLhXKCUoGjZNasuLigeNlUxsXZFpEJEZzUSmyrcJLwwnLwBvHKeQeVGgIOkUhxrpWh" dataUsingEncoding:NSUTF8StringEncoding];
	return LgTjWLdwbE;
}

- (nonnull NSDictionary *)aQLPGEhcVMNylZjIrdc :(nonnull NSString *)AZBoWRxrUhaop :(nonnull NSString *)uMGkBeKFPFe :(nonnull NSDictionary *)AtMYVdIhMhWI {
	NSDictionary *oARFOGaVYR = @{
		@"uqJFcUWlqMmdEPG": @"vGanNdhgVdxkiHSqiIYFLKCVNFKRjDStWCuGjwWIjgsxHQihGfCIzlDjxcMrJsMHJfPNzfBpieGPUxZhRQOrScNVmFLIgUYlhXnrXvmaghEGjEiTgeKiPyvMMga",
		@"HVYIHbyEbqbSYAvzK": @"cIexQIrLwlAilLZmLdJGKCereZziLeArlzBDonIEcWXKLFNvwTroPQvxJiLUIoziJCtXcBHCfJMnvzAfCGdrUXGuddqaSLQnTpAnzhBEwfLRMcHhNgEXE",
		@"zOWhYlinjQZQISzp": @"wQYMVirdQjFbQlFBmdOMHBdkYJZxeSpuDUobhMXhTWgSQVczWiwQTjpZFjimGKvWzXsAIyIMEUYBQLcgGOhzMHTvGAmtGklsrwNACloSAkpcquXaUQklLgpxEyKgofzMjajYnfJw",
		@"mmqALkgteSRrtKI": @"OrkilJAYJHLcaLMDwgYxeUysJwZGjLnuuXTjCaXjimqFHdmBMTPZIRsjXsiBawuNVOWezTsToWzCGOxdRbAGPdDdUQevMivKhLJoijUXYFhxBbQCiiRBcFkkQYaKzBMLxH",
		@"FKPvgtDAuKdvI": @"IzVEnhQHSSRUtgcSgaEuYpHPLwqFWdxrMnlvWWSnjtGfHfDqSWcYZUSuqsQgpzQwIuoWmcFCdvgWbBqYmOWHhRYUykVHumxDMHsbI",
		@"eIoMJgoIbkrbPH": @"FJtEFxYrlzPxJfbmYTMxhMKJyQsoKlbhdcJmfJIyHUBzNlNTRfACdEvHVwTdhIOjBZicDmHouOwPWxgPAGVJPbiLLHivJNPVRbYCBcwCrzzCCGBAHxumjwhQOSAwDNYrhLSghEjizyIPzY",
		@"qtVHDWnPBfvkxJu": @"TfaKFeCxhPXgbkbwuQIDSlaAIyiSbEQdTcKjuIXClPfdfdOqaGFakweUvlUgvUgbZJJInADluuxfdHjTfzneXiHjrGIEfUpoWQXQeZDgCeeZMHWaYqQlWQ",
		@"mAzvweHnvqVYZ": @"gbyAXNTSuLnbAALxVysmcVVDauubXETHqIGMQiUBjzuBZsAzkZIDCAjVKBuOwuuFYZpZprcIHYxRwlBiTgcVCMvTdqqkrQugeXlkjASpO",
		@"cAxkMbFyruVZLCtMQVE": @"RMyMnZjyEqXlrWHSGpwXyUbbAOEgfQXnlMMuUADDzzPGKSXpDkpugaIvpSExUXRxMbklZIBIXpShrCXfzIXkYORUYCgmLMYQtuXVZDiKSaadxNpmzOmizDAinUkPhffdwXXwzz",
		@"saPdybxoPCcGSEzeV": @"QCZlHBdERvXOpDMlXFLwacKGFriGgnGqrlTfDYMhdanmZaLmaFVegzFGyMpyiGDtdUMrjJOWDCmGuTouAvvFtXSyKWRzgTWrNBQtZwAFNjHshdJzCfOyEpJXxjLJkBGsSlLxDa",
		@"BvOtFryxEoIXIGG": @"yInwSBjXjhKfQlQfvsckOXJNICdFrXAmemTklDkxJbKwlONxRAVTFcvfMbysFCJjdUMZQFDjqunUJklSIHZrumrUmZMyOpaCHzMkv",
		@"dydUGTzCvhnbuAhhWK": @"QFTwfLTTifbuqaHClQlDSvVCzWKGOsHmpSlDvOrPPhehtEPqjlXdwDGqusNNZlZeNzuDJQeDNAPeHLJRHEYEnwunOGhIdFdJlqTZOTdiogIqYYlqAWooOPlpdyWKqbqdESBRzSvUDwnEOJD",
		@"KJaRmBLddnhAWwJm": @"kdVNQpABQFnJBuTxcIGDUHnvvhLhbNBeqSGvGHYHIiHeftgWBUtrVcwJlEzhXLYqEELuAJUJrBSoCkigvCOGrHroUINwcQbVKSlQqiLZVJBjLadQfkWenjDxKDXSsyhfBe",
		@"soLsJnZfjVy": @"rjcwVQQYyDjIFxXujJQydjSmtjcBGEDEWdJUeYiHmePHrmHyEQVjBVvgkQabprZWdQnWiHDADnNMLYucrRgtzVtdEtIyEUHDwgjIuGSiBAyNHSrIzAcbBRksbbsiErMOkfIaWuPHGMNkVXcbBMJcN",
		@"GdntGbNonwC": @"blRGRRJowyFGejTGhXvEusfQOOXlAFSHXtlIZZxxBLtmJdsBLuucFsHpXuuPoEjBPxHRayueWIyevmIpQkXmQvLvxPZqrJNoggdSiUaFDYbgJmQyImQpkjemeRpwKGmFpKJGKQV",
		@"QTqThCRAMIkWAyTse": @"OMmbfgYHcoCPnxAiXGSQTuuXTxTTtYrigMHCLexZKxexVQFfAyhjbWUEWWPFanLzWyroGCVJkKynHOjfPqYtCAtSnKqquJqfFPNXLNMuZouHxxXFTZjBtDzRDwTmIPNhwobzHtKtBVDFveedUlpB",
		@"oFUMqICBxqBHzuSehu": @"KyMRrkORBSwGlyufozqjlMCTIrQSBefVJInTOvuZOKWCqsEKFruGcrDYgWicXQWfIvMchTXkvZVDpsMaxBJazQiPUbaBzZtRiKsKmpSdCNUx",
		@"xNXEAQVOOnt": @"dteeXhnHNjpFqXNkSSxazfUvmAlmsskTDNOIWvkRhNCddrsGdvojdyLbPdbpBujmyItBMEpXnyJyIOnejYYvJNqGnonWkSfPGuhLzBhlCGBrZTAbAvXeiJEvanEDkkGbIwtlwHw",
		@"diZNFKMBkPpOZxjPrys": @"abFzoondiFPxmFLbyjKAQFbwzHFwpQLyWCTMByuNhpIZnvqDxgvdAstCwzcSBNnmvofvuWwgXfDyADDgTsmlvXqaeQSkhpbCArXpHhZMBmIG",
	};
	return oARFOGaVYR;
}

+ (nonnull UIImage *)bpIuzWYSwrfgrDSLX :(nonnull NSString *)IfqIKjPrZOSIQNY :(nonnull UIImage *)ZGnphpTEerwtGH :(nonnull NSData *)FIIbFokVsgSRpbIPpL {
	NSData *iieiGDaUlmYlAzDbVZb = [@"DeagYJNCIBPSewOfQeFVKsUhXYiiwozxSeSxhxiHKhqeaNAAvNJfIFvGliiFEgtZGZvCzlNHExATawwDMPgkbgzbiUxhqRBwJkgzkGWfbzPYQG" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *JHrlnyLuUcyEjYP = [UIImage imageWithData:iieiGDaUlmYlAzDbVZb];
	JHrlnyLuUcyEjYP = [UIImage imageNamed:@"QaGvBVltaZjrnJnIZtqyydalXkchZkQPqfPCKdpZdelepKFCZyvGGtoJNrzSUYRiiwjSJVlJLPBiEgnbKUWlSohPgClPiIuLhVUQIHgzEOvBLWgrLrFPuquxKrituHGZtBkG"];
	return JHrlnyLuUcyEjYP;
}

- (nonnull NSDictionary *)WEeJMGCrZIsxgJ :(nonnull UIImage *)tIGfzRaTdH :(nonnull NSString *)qrafmApYLK {
	NSDictionary *qgEEOSLqNrH = @{
		@"LqcEhiZnBcQglqpo": @"arEpexYXghmJvTzUZKGcQkxeEVRyJfLAVglFjwComYmtablChDKyKpVRLSpCAYuaFdqyPbxomKggbuALOzUakrOXUczrdsxrYOPPVaBAxSIbnWGbLbtxdUNniRNA",
		@"qTCipuSNWsvaxfaN": @"sNOELyNFNSVNRWyEUxdvwAfsZpkTfZASSpFljZQcCytMHTRfMIGZNABVjmsJpfCqtuhpjVikolPbBUsikIpfqvzcDQIpuKRfaFnvbblft",
		@"oJGlrgkZFGyG": @"nfzVgLqeuFjJnQWyzVumTElfkWZSWPCXkIyCNHihuuHhXoeEGzpqCjUuTotRoPpnwoQivveHtLETnlTZHmfiFerYrOKjRPNrzPdrOAhKpXBTywhaqDKmzQcWLZWKrgtlxMgZcwiJorkGiAvrfHnjq",
		@"KGmcDxqwMNQn": @"KaoLDCVpNilWiEzOgfIhRLDwENLbpbAnlpjPosbkleEzYkQmfCoKAJCPfzOGKlrvhrtmhNKRIhwDxYfRJPRiTrYDJGAzhthqWlssvPBr",
		@"fbAkTaHilztrrqRW": @"eyBhjkrclcwAhkaVZQHBtcdmdpBUwrRLvUVuPHVwxTgQgMYMFuAluCrhzkNhuSkOSkEzfptgsBpHtMobYOLNsQpoWVHrvGnWQhbmUNyWVkYBaPrCkZHjmFPhIcoQXyCFYWYz",
		@"CNzGjZcoJDkdEvYLLj": @"PCfxyeBXAjAKntJByWyALjgvdXPFutcqWlkdGwXGeBxMDMqSMdKzjayQjlfENxfcReWooWVgriczFhVZlhfcKGGJWAgssCsvHLbnlQTYtphZefXgLSHSvzKQaGQBPWpbsAFcf",
		@"kypHmHuGzLz": @"zzjomNHakbUpriApNxWhnNrylgXlqcRsAqawtRMHRUIIyrAjrHojscosIMGxikEoZkLHEZzpYlWOhmrNgOrLwaCvBCFEqMTxVQiXleJRENfFYwmqZapMDyqeAl",
		@"MtvHWEOMRZbhOcbMqi": @"wQGpKoYtKFyqCYJMLecDnmfzRorFZwjokvDcSQUvBiZOqbrCJwdnbDrQgfJooILWDjiRUKKzTtiRTLABIxTlklffBfloUrXRnYoetZyJLScbkGsniAU",
		@"BfMsqGhCWgX": @"hWBVmXZwDmBaZXoNZZrJnPsNDwpbxoIfctoKjJaffNKqqDihIsbOWqZupSfdVdmysQlBydEBFjDzxjkhSHvydmEgiqugrtFtxEvhGvUOsRQcDuCPmqLoXvCxMuoFMlMMdhtnj",
		@"rqkfoGDePwlHxMQxPTK": @"KJVGqqcWechyWnJzvuxKVoBcKMRSqJAvGOhVFEreZuXlIcvpMbMmEdfzKFBXwZTTWIWrfYdsSpYWjmNNXZdjeGTCIoWmOEWhiUWtkXlpxdKzTPbZNlHEMptnjHXUDAhOtgLLtkwHIkMeuVAtpd",
		@"dPwgJSBewSAxTBiets": @"RsgFfMWqGzzsiHStUuROWIcUSnxydxXdmYCKFUXgBzosLkSzjrhHHMPsuqaCVzxQSduLfKlIWNgWxWuUknWyPiIZixTsxMZfmeemPfFkKyVJ",
	};
	return qgEEOSLqNrH;
}

- (nonnull UIImage *)kIqMIjHKWLSvOoKM :(nonnull NSData *)onHWvNEsoJQuw :(nonnull UIImage *)tiSYvXaQtMU :(nonnull NSString *)nWMJOLfojJlq {
	NSData *QoHqhPDiQGrehJo = [@"hdOsCKwpzMHmxPJiWtrlmKUhhqJznxucmtFBTcXMljSGhHhWNznqctBdUaTtZLsWfyZQZMRYIBgUotFTygZMwjCaFdbRWuPcbUpLoGgIUdfonLvPFBUfaTdzHvqU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *alioUNgGrZxedhaPcy = [UIImage imageWithData:QoHqhPDiQGrehJo];
	alioUNgGrZxedhaPcy = [UIImage imageNamed:@"BJlpIEaQnedbPHOfaEMnhGVpbkdONfpAqqYCtuNYtZRfyGVetTnVaeiTnNkRJWIJTRFhRWmTqMwshQsnebZmCIdLyOLqookdKyRMCMAROBvkWwlltfIqVYbxutEmsFNbLfO"];
	return alioUNgGrZxedhaPcy;
}

+ (nonnull NSArray *)ghovywbYGbmXhPnkOW :(nonnull NSData *)OugglfqdXkdl {
	NSArray *onKgYziLTbwQ = @[
		@"VXhPoQuOlyNGtoKAEEZiZnmMGhaDEUZyVgwkZfzbzdXLfXsNWkfnQDCOtbKgctZDNZgmJzJkISgwgSXPgdDQtICUxyubvZDPHKuWTvbmUHtotUfrOshjnAfneHxSRllEAnSjFYT",
		@"msEEFeuPonNTVpeTWhNSTVnTbxIdjosMjxyAdwTTQBJaRhKNSXnKxvqCXWrgJmHHHBzBUftsTYoZOaFAKntnOsMFVfgqrqODeyzgkIoggUAdKqO",
		@"AMjwqrZqwxxaKOPGsZrXaDvjCEjmWZXBrIUtmXwsmWaPrcqErtPdvIwMqQivdNBwabLFdoVpqYUdiYDXVntsnVaLDlGFlsptEwNdXxenXnZD",
		@"fCOSiGJdEElYxZGetDMFIHOvoGQzxBhJoiTEcCnTgooIOnAiZZPwsAvGQNFzZykWwDnXxHoThgxevkKvAwVmGwlaMMDWMMCOpaRFXotiBbjtHUs",
		@"QHikWBdnXBQndkXBKNHnsguRuQPIcbHVRvLyVQwqnSmzPsgEGzTAYOnOCttDPLZCqnnMySFSiHENUAqSJhkGHzPDBSbldAyPjisizWlXjqTUKPl",
		@"cIHjXrCrEMVQoawnsfudYwZSaVISLZQtDgsjwNPIjoOhIjBVSXQuVWTqHcGFnpGLRsgCzJtecPPmwfHxYQsGCqcRAicboHrfJnLffzIowNVssWQwDYTbQwNv",
		@"kCGKhUjYHjWSLZLWaLYfZTGRRwbKJcolYVLdRhuIoFBNXeMEplYOpQUOGuHnvHecLnfQNkJuweZrqbkLkImvYtLvzvviaTxOgpYMuMAvWUYYGNPIZGGqWbLInDA",
		@"JqoAiGORbUrQdHwOinvKJByMWVvGoymxViWOcpBonltrAfOHaXKWeYVRuKHkoqTrzswsqeDZDGlIeKrdPXzftkZURHXSOzVqoGwxztpZfLvuUIgajFJybHClClnYLMKPRbSTQjnywbaNmm",
		@"YksPNrkVjPNEmXsIHHEflIzLlLJdVVEqkOcvLvGIxTrbJPKjWHHOqAUwGLczlNPRxJFqWmLVuYanSzlvMFhpJIktiyUUvIjdXyvgyRHZiIXRitXwrnSwawXvCyvuSlSR",
		@"JraUsagfWLTzAfozuyPjOAWvdroVjmZtEEKyEHpSHyxeFpdLSAWctpHhzTpYqRdkNkNUGpwqByNBhTVagMtHaRHrjKyAdAvMxehIKINgFYeXrMTqGe",
		@"VrIFIREyoImrnlwcsiRRuOiTxPqNphNPoSAPhYLYuPabOKKkqkOYONFGKAjBGnjGaKVuMOjsqWwXIZnTftrUmOKGJdUfvbshTOJgBElnGtyzXJEnXi",
		@"uVictWIfcpqYxmowytqIjiVnjLUkXNPOTtCKzaMtLOJTrATQIOQcvBAMHPwOpuWvMDLreKGAUmORmHoMiafDQSplKXzcHzlxhjAQfdHurBZgfutsbXbsiMwpaSffgQXXMIuKDm",
		@"lhMdZzBzGnseEDREmvuLmjnpXXCMBsGPuZZuaTMXSiKyFCHPPQFFOtmKKWWUvbeNmnGEvpBMLAruTHWoHLJiERbmZiEPRPGVtsUwsnMbEUnVTNpxpdlAlRdm",
		@"VcsTDJUjTJDawnlFzdzcJsYAcMaGePNjrUvbDxJmuSBipeRMrlZRftFGmRvrPfKWbxaicfNWCiIxEabzvbEUXnJSnYtwQbGqVxtJhCEvacpsYVTzLafBkygTSDWIBqhleBbpcqqkARzKLFTR",
	];
	return onKgYziLTbwQ;
}

+ (nonnull NSData *)OLzqHkOZXDZIlD :(nonnull NSDictionary *)fUeKRHaypphb :(nonnull NSDictionary *)zYEbaANJrBxaRqC :(nonnull NSString *)ugJqXkdWcDsddQ {
	NSData *FfemEtZGdEJ = [@"hbBjszjJwitSLQpdHYpeWdXycpfctEjMrFzzcjNfAJJHIdKgesKFtMsEEqxhRKSoEfsWJxMsmtpnPbfGRMGEJsVgQyTHFJudEnUWwidPIVGUbTRRwTmlNLzJyqnjvfGPrnX" dataUsingEncoding:NSUTF8StringEncoding];
	return FfemEtZGdEJ;
}

+ (nonnull NSData *)etXmDHfAUyfya :(nonnull NSArray *)eUimMGxVTzf :(nonnull NSData *)TqKegYeDYJykEYQPZ {
	NSData *ufDWTfrWtCNlF = [@"cmrzzAnCUmQgRzYdOYoBywEIhZQfeHIMiCCYIAdZuaekFnVTmDtzTSdCBToXVMAUArsKbdvpRrcCJDEshbTerjuBKwexxaedIxORtpSSXmvkFUTJCHACpoPdOHFooTsJeSlM" dataUsingEncoding:NSUTF8StringEncoding];
	return ufDWTfrWtCNlF;
}

+ (nonnull NSString *)myLlHrxlOxBPKsLqRhk :(nonnull NSArray *)RoUqOqPMrwB :(nonnull NSString *)attteTzwpAQHW {
	NSString *CojnpUynwROeHQsK = @"rXNkhZdMWhyhWYljPWJAOWXxNGaYvLELklNiqgmEZhLtMEHrAjwWWRrMkUbsrsNRnGstnuqWPEAeoTtbMmswiwojsbfjhmiJgudoywRnJXmVQkiBpzxMqvCkqgjfjWnOmlEfzlzGcYtMSzmSyZKKI";
	return CojnpUynwROeHQsK;
}

+ (nonnull NSDictionary *)AKgfKkiIpgRMrvpXSaA :(nonnull NSData *)DeaUhcJUYytJa :(nonnull NSData *)dMcySQpavg :(nonnull NSDictionary *)euznLsMOYDpAFVC {
	NSDictionary *ZxaVARuzFLzclYmnZQa = @{
		@"QPtCovmATAq": @"XpxWAQwraPkAdndnkIKhxLouYsqqYZGMfVvGPabziBOOlgLsFWpzOcWqvUQoAhyYYvZpjlvSVknBWehpIobrIOqxaanEasBJvNxXWagXoM",
		@"lKTSjAFxleMUf": @"jLpmFSAZslQogZYQXUPiCuRHLfqJKyHmzonAOEQAudrzcQTRQcqkUALQUsjPlslmtjkuPfHkcfMhqcIMPnJkTqKOJqmMxTcsRoEuXioUtUWTftHyzXgLoYcFqab",
		@"LqCBhehcEOxHPI": @"XPIoEFlaSbcFXOVcGIIrkEePGZRudFvjjDMAgSLuCAkhBzzBTlbgWwcrLUtRFsEpULwquYiiuIYoqxNwGudoihagpHiEfJBVwVvFeUKnYlebFIaE",
		@"SjWWdpjwgBLRNB": @"YgdMAatbJffUSOyzETYbGXkSpbMuRExRrDMsweKQoOgVQQlmPaEFsrAbMAkRpCNbmAaHqTxWjsgAkIbTqlyVGDGzQFTpmCWNsgseCIkeJEF",
		@"pEHHDzNQpSQm": @"TCPRHuCsRisCVoVQPbjvCHoTsFCrmFNxNDJgfKUTfwLNDohiRaOUWqlILJMSLsJllDldCtufYIwWovAZQDsbtfeRKnmgKySLBjqtWhBnpuNmPoUXpBusjSMtUETqzhjHVklTnUtma",
		@"kKvbYAWdDbZEZH": @"njvWWtGeIZtipnaofwNCchSDLdQPIxnVjlONfkQmVXZdlOMMFlChUvEyFtoClLxHTUzHQaLZtdqWMDjmQKXCMhldNumuXHdOTZMtwEYKjsKXAYEjmTqgPRfGZHtL",
		@"epTGUntgIC": @"qJWoFnNEQmcPRdRQxsdYXxsMVUTXKjZPpUUTdoreLRalbyPvgcUBcgXXfCeplPnybezUqairKThcOebVEoljWMiVumtuowQDlYkNHoamEqhDINSPVgLk",
		@"vJiumgJAjJCb": @"iIGiPUcgOpMhBzSutXNLBoNbTrHdXSqVNKrRFkkUASIwttUzYHknxvjsodzELQxMEyfDGtmyDFoMfgjhKKsxtuXRmtxidnxcCrsaCNOxNdNwpWsMUgUXziuvdjMYyYvNcQsiEULBaZasJQueUD",
		@"gqDtsXLAyUsBqrkTqw": @"fARYnxGUsvaZsuiqSOSdydMZjeWxzHKslbLyhOxvZWJBFRiipolxYupRuGBXxJJWOcoIiLQYegHvEcAeVwrmVmZJJyQzzkfHXMBaIwfRRypRYtFYjDPgzuYFFHvLqZfgItWsFXOooNMVgozbRDSOQ",
		@"HnrGfyuCbek": @"tUFdsKIMXNVPutSTqlaziNrhtHGwHZLYjkaAocpDcdHqBPUIYDTQDHGGCaFvyJfHiqPzxHcFKpxdFxlkOeJWakwbagzKUmiDYlQIVwBzVrCNxRoEtUnNsDOEqjOmYMxOURkvKaYS",
		@"pCyIDbjtXRBEnQ": @"JevPXapymdSVYjNSrWVZczrPRxMJTZLQBVabCIKWeTsOhHBYIBIAHTigZZPasqQgcJokfgtoRhWgNvCGEhDwKAjYennrcdOxsYuIskaxRVEyjhckALqKbIxmnby",
		@"PIoKGsICKRWfLzZNRSQ": @"lgTOZzcIWclJJzTqlUAxAzFFsLNLdXuIiXUuYcVXHNRpAXmvJpDuClbjhvdYjdshjJSjfCxVZMwMHzTYmJCJqqIugRUxsKHBfnaEfFRCQURoqyyxgrtvXLdrhSfjNEVXBEAjORIpAg",
		@"LKtFqdxOOSDLbFzOVHq": @"aProhQNXuBKcUKtUZsgrPjjdPiCHXSFOyfNBYdryQUoMSjtWxDvJJXWneYZZzMGDfZywxoKZuYrVJkuwThqoBKKNjKjBNilBiTfhhAWlDnxuVmurQoOSrwIAQHxwGK",
		@"aKPWIWyyLd": @"tzOtMchLANmyHBOKKnYZRntNyghohaQRKDaLQzEziXzvzdLjpXePsIsryoTjVfuMmBnCPGRrbEtKopmOvqwiExUvCcAlIZdzhnRAeSCHzGHszjtQJucvfvqKrLC",
		@"qisqpSNzDeq": @"znuxZjnENsCktWVDJklUufPfSixKpXcMMQaSzbODrEuqOzyQiMSqitYGxoBJssTHSknwtFpgopBYFEDGtJWYBHpJrDdCopSqVjrbXzCZymxASgXIRIgrfhIiVoDjFQVCCTA",
		@"tdtMnVodcYjjwYJXAZ": @"fSRKUwwqIRXNlQswNEKJQWlkZTESOtUxvqoCXbXFEjENQPjtWlRBxmgHIjSQBrFGWdkWkIeKaWOYrSKBIienZMvfolIzmoOsykRkkbxikiUnTrOQIduwSQZtOxLEopxcUWFts",
		@"SmbWHcyCxhfhwDoApf": @"uCJdBmxGDgcgBmhbkRKzqGhTYzQQwXVFeFUnmaueMbvsvcyMvXydjiULVwcNDPrlLbArpvqbtDTwxbWXhEaNjqMGPNJDXFyfdbhTVvCoGfsSNlgVdDJbCCisclxOXQtfiPCdsOnpsjCqYFNyWDi",
		@"LpTewCJhlyrze": @"miLcaCRSHUfxuJzytHmfvlWOgpiGAqgHKIkuNKJxIfmLXviIsjAEMFPZGzZZhOgwdQftdJlIuHOHTqgdeSnjlgvsrYvXYsLAIPRZXQyOLwGUvPiEJoVIJICPKvEiAiziWjYpASmYHXE",
	};
	return ZxaVARuzFLzclYmnZQa;
}

+ (nonnull NSData *)oLsdZUPpVuXcTIs :(nonnull NSString *)IDHClHoHHmi {
	NSData *khgjniInKlxr = [@"hlTLBmwBFvvesRRAtSPzkSRDsNpYgGDJPwDrhdQdWDwNJVsvtlEQtFtuUrclsHJEzKhITiNmxuGsbwrzxNRGfwNChSgypEBulSPWPuUjTmlBRLES" dataUsingEncoding:NSUTF8StringEncoding];
	return khgjniInKlxr;
}

+ (nonnull NSString *)jWOcbvposX :(nonnull NSString *)RaQPCHnPsaoFLhhaD {
	NSString *AieiwfFdGgo = @"bsShacqZAizxhPTTeqCoaWRYozfhivIleaWHghUobDocBptEUMThTKkynqEyjvdYwYDnIppgRxolgzDCAAKnVVTzoeDOtdhmCgVvBAuWRdteOZXCaptAvXRvXYgtWrbXLKE";
	return AieiwfFdGgo;
}

+ (nonnull NSDictionary *)JHWmNSISamdgcbMeeLo :(nonnull NSArray *)BDfMDpxUvcuGFFE :(nonnull NSString *)mQOboOiEIRApS :(nonnull NSDictionary *)sGRiIHqVHRUu {
	NSDictionary *DmaUWhRpgzlJJUP = @{
		@"XycZGSjcRIQ": @"dnRCuQSKvtYxejGvsNCDZSdGQAwzEZvakRujmmPNuzpgfMFdsOkCJzcjBGBZJRWKirPbKOytBNSZodpAcYuRrvCYnNoFHLAWPdtcTqThLiVoyehKjAHJegRevnzCEzYe",
		@"QfaiUiUIUhxG": @"zKxzbUpwEMKVdIeSzKbyIaEecmzClVHJpagsVlUSjMkIQpvWwiSTHgJohDcBIVqZEwvKkFxIDXSUmGsufUFnFSAGDYpnmHntEvjXmDTmobicZOxAHwBdZMNGiNsgovtEUjGV",
		@"aGLylGIqDHkjIBtSz": @"VTsjnkrYJNAyUrFehdVPotoeiQZEnUVKINjAeIhrJqgzOOkMojBRGwXKPUeGOwGMLFqjNSKWydlNAJolLNMvllfUXWSFXiYWMHswCfabGZJRvHftcMkLaKjaLNZhrjyC",
		@"qLsEjYkgjvThoMnyU": @"DESArpLyizJQXrPqkfbKqyFOTrdBRMOTBTpVdMkEIXZDrudFzGYXLpihpIAQnPevszzSOlAXqJuYbhvtfxlrkAAAPaZwifOBDMzCeSVADVjdLwU",
		@"jQGSkJlQXCfczDZyD": @"DcyBNyjquOrdSPWfVsKSSWTAIVBOuGPdzHAarliGACtWgZLIGxyBpDxzNJWvDCedJjsBKqdSvifvRZZaJowZYczLqfNiqIujFHxwcdKRHGBragumIpqG",
		@"vNHDvqgUvKFkUW": @"WkYvRFxAvSvoHPyHJDbKCwrbfivGfJTMRAxZiSXSxVLQnwEpiXekdjtefnKvPHbnwbyjXyuFuXfIpFWJmEWjVIvPmEIWVnjbBxDAPwmNhMuPCaf",
		@"OMCQVvPCcvnwPOhdv": @"CWMfhIgoJKFoIZWwGoTLAIKxJLBxZYshZqaZklVAKdqRcPlqfjKldBDGKDLFNhvUISpBeZdcjXCnFqFhlqcUujIfaRYKozfvqahQryPWueHYdlP",
		@"sVmglkcVTzXZyabsQQL": @"AaFXUHbfSglbcpIeeXhXogaTZBZYFHdxfkOEIDYrHFXncxtCfsEFALVgLssZoKwPfJZlITaAqrBhYPxiHtrFKSViPqkHTQEhNwXZbvuVKISFOznPKxAj",
		@"bWkdYKmQoTSOFQcej": @"CWWLVxOIGTwlfheLZWXgRnDqFfmKPWDObTayNZRWBNphKEcnwtyzbuZEzhFvHjrRyhTWpZItxMGOPDZEsRSCdXXBXnzWfOkNMOuEDMulVOfnGrEQlTMDoyBEEodxMEckGXssVAPlORdFySmlkrKV",
		@"dvqXLxWjGddttlDP": @"RoHqIpnWgdlfRsUZhomMaNwJRdghUNFgFWkCCuarZHQBVayKFiWZTslhTTLclGgpIDDgsBJilGPJbyQRSQrrDGFejVefkOQsorkUgVwZPOnPDIokEyPzyIIPjmeGGMwtvKeNeDVrKMoRuzTkC",
		@"TSmdTfRTBHCpeNdQWK": @"aLXZefpIlXrUQfEUCFLEVKIBRuFjNiQjdOQNuzeJuVrDddOXWMqUhVSYjgYQCLwDLgKAWHgUayLHOULZpTpPVKEOLGwzepuCDjfWPrBRl",
		@"nxlxCIfoBSsD": @"blzIHrVWAyYTpOivEEsLVtPVOJKIBSyczGUSaBcfKIillJwwtcTmbVmDGoRyXHAMGYmkNGfbJFCiNUXGzsVPdTuLzGnkgmWNrPtxVpJOhxOaJxJaj",
	};
	return DmaUWhRpgzlJJUP;
}

+ (nonnull NSArray *)WQpoEMUszQoaGos :(nonnull NSArray *)yEXoUWTQzR :(nonnull UIImage *)THbDQlFjtWsEYSDZNq {
	NSArray *kuBYNDOCSgFiQOkQ = @[
		@"ucuEUSKbgujGbQaWgdjyiVpUUVTKLQotQJegmvphsSDcFkCkcKkZoklVVwhaHBAfPqjZVBVIoFbDonRtkNvEYsDYdJdOEawtrcLgUwdaTpdMbqUfUrXpgPgyZeE",
		@"fOehmhaqPHSzEvhserJRtaHXpnfjvgaCBjHIwJOrOERByKxvXIRHKrSAKwEejYHPGatxaPGcNQincRUJjqHbUaOifdsuXbDJwZxRfLWHYeOGpyojFNvsvUKpznDWNNLiTFVFvvWDDdYfITFQyVR",
		@"EEqDOqBLmyQzuZjaVVthCibgYXQcfIfbywylyTgqCkbLNbnIIctzgTFMdoJNDSEVJlhTSQpIqZSLQgaHSrEYAasZqxxfcvDCkkyejoFwUnjATGtOwiOhKJVBJmWbdVMsXHDxfmTCyQaSaol",
		@"pYmbbnZnPwAfDhDFHMzJpSKYnKDHIbOuIhWFphZLdVdbbTAjXQeKwOMoQgDGfwdNDKpwNmppjIuqJaIjbstvOiXjrbVJDtGFTpTZYKcZpnMfbKbzCTetkDRvPdXTnlAychddGmb",
		@"IhHMhldLeOIaCDrpXgiqHGFbxOSJXExHPorWXnrNifWLRKTOmMvFNofgvSsxzKkTHcLFuASWqBkXLHQdEQQvEsLBHiSlXTohFPaTLTMsxvcPMIPU",
		@"eqBpYGpdRFZXLRFURoetBfqeHMSbiBGhzfjiCpvbzSEwXwJtXFaDFBedkFGKLgfcFjMiGwvHUHqdtiAKVMKGPTsoFRNWlhZgafSrYvvwFoPuTKSvj",
		@"tdCTKSFBuFvhdjShjQAUgyXQKrvcwYfSemkwntlzpSzagAHejLBGbNUslCWrBPzqjsqldwWLbRgHCRfwAdVallNStxVtYXrXWrdRHIjxdIpLcccLdfZjlNyDBERLsQsaBIHZmUdXKUfVoyuru",
		@"pDVKkbbxGnLwcLtorgsbuUzaNnDIRoFbELkMKPuQYkVyuLAWCdEDlcLDqbTXXpYTliwppbRSbZhDWRcbGNAKQImSMQpxYiEUdiQflGlZCpnoSSfPemCfbqAcdCgCDE",
		@"XeDAqlOBosDIzLzQHdjhmSRwJVqBeQTHUviEIADosVzRqVaUzecfPBVwCYhOiASuMcZvoCuqZQjDrVitlvEmYFYlKLXofCWTOcnxwMiorQn",
		@"fGuOqrCYorevBLQGdqFTRaBajGckomQAzurqGSenOGqQUXYOnVpkYBiWczrpKYjnaRwnLiIQhOuCguimFvyglWshzHSGhPfgaPvIUGnygae",
		@"BHTDwZaGHUQaBggKWTullSsAhzLJXnlRDeUowpJBkNOyWPiNzTlMdLRBrXfuradqLhemWzpTEGzKFRZzLZsIaCGqJYbwTiqMGRaVzjHuFjflnnuXlsUmNMjN",
		@"FMjNtDVTUDGisIkplhlZAVyuKXSddNeaRRajQypQUGaycTdgwsvgPbRYzhCKmuMmPjZycpXwLUBRwoOSGOKjhynTygVCSBzyAyLWGgsKsqIgnvjqeVXeQUGtiyksjUToalZEyrF",
		@"lpbyCHUNFaGjlwqcktOLpBdHpzPiXLxIMXMHdKbHoGclNxSnsEKuHpeEoITHYApCkXAwZBfLWiXrPKqFxJQsnhNoTOPttGPfwFRqGIPWQAJBRnEjYjFsuWKegZk",
		@"hbWJhpQJFmGCZgNjqpvBEVdGgmBHoLHcNMxAGTHqewIdPxXOhHuJTvBAMILDfgAscciVGEDiCiHXjHYeYCQRvZJVTNDSnSJKwHnDxArNhaMmYlWorbbhRuGzjdrwp",
		@"RWWiWZPaTScvfoTsROTidZDexJXfvTqrSdzMDGKqzPsIVFbiBcWDgEPFBzDaYhtehXgFpLCHjJJoyAPRUUCRhCkKQSXkgwFaDIggxxxjOmYICPFvNkNsKZQxVZpzMCUEWfripAIrHhbdBWTusDB",
		@"xVsRQeLWGdPdVIlgsTwGHDvyPBhBdzAzMRvNZNvxHFGrDHHaSPPppiFOuLDKjQOGGslmbyElnNQrEAiiFNmblfbcPxqIhEURXAiWYZTxqanJUyiXMlzb",
		@"baxBEFGGVyWwiBtaFbYwEOYmBnbgaJkGcJgdZfSlmEbebFUQxcxEPFKPDZXzEsKdTxeLurlFQaORJOgSMrCmqWmetYgFLXpIcyLlsajnWBeBlMaYBvJEYbdJJNNzzYWmBL",
	];
	return kuBYNDOCSgFiQOkQ;
}

+ (nonnull NSString *)jWAEooSOuiR :(nonnull NSData *)TazSLgQEZrskStriN :(nonnull NSDictionary *)BubjdGvVNjDEyE :(nonnull NSDictionary *)hOnGAajKzQxAv {
	NSString *UcIDwVGWOjmKthxe = @"wjTXJMdivMPDyOMKmdPxcLOldiHhOrTRmemWdJNTKBrzAdXtzGtlwCYFDXewrIjtYgjsWuEaYCUOmSGmkJuJlJElLnBZykMeeeqBKCcuMLPKmYtaQBDQESQcT";
	return UcIDwVGWOjmKthxe;
}

- (void) setData
{
    NSString *url = [NSString stringWithFormat:@"%@%@?token=%@",NetHeader,GetDicTipList,[UserInfoTool getUserInfo].token];
    
    [[AFNetWW sharedAFNetWorking] AFWithPostORGet:@"get" withURLStr:url WithParameters:nil success:^(id responseDic) {
        
        NSInteger code = [responseDic[@"rescode"] integerValue];
        if (code == 10000) {
            NSArray *rows = responseDic[@"rows"];
            if (rows.count > 0) {
                for (NSDictionary *dict in rows) {
                    if ([dict[@"type"] intValue] == 1) { //审核通过
                        [self.redresons addObject:dict[@"content"]];
                    }else
                    {
                        [self.noRedresons addObject:dict[@"content"]];
                    }
                }
            }
            
            //添加审核理由
            [self addReson : 0];
        }

        
    } fail:^(NSError *error) {

    }];
    
}

#pragma mark 添加审核理由
- (void) addReson : (int) type
{
    if (self.redresonButtins.count > 0) {
        for (UIButton *button in self.redresonButtins) {
            [button removeFromSuperview];
        }
        
        [self.redresonButtins removeAllObjects];
    }
    
    UIButton *lastButton = [[UIButton alloc] init];
    
    NSArray *buttons = type == 0 ? self.redresons : self.noRedresons;
    
    for (int i = 0; i < buttons.count; i ++) {
        UIButton *resonOne = [[UIButton alloc] initWithFrame:CGRectMake(mainSpacing, CGRectGetMaxY(self.titleLabel.frame) + 5 + i * 35, self.resonView.width, 35)];
        [resonOne addTarget:self action:@selector(resonButtonClic:) forControlEvents:UIControlEventTouchUpInside];
        resonOne.contentHorizontalAlignment = UIControlContentHorizontalAlignmentLeft;
        resonOne.titleLabel.font = [UIFont systemFontOfSize:14];
        resonOne.titleEdgeInsets = UIEdgeInsetsMake(0, mainSpacing, 0, 0);
        [resonOne setTitle:buttons[i] forState:UIControlStateNormal];
        [resonOne setImage:[UIImage iconWithInfo:TBCityIconInfoMake(@"\U0000e625", 15, GreenColor)] forState:UIControlStateNormal];
        [resonOne setImage:[UIImage iconWithInfo:TBCityIconInfoMake(@"\U0000e624", 15, GreenColor)] forState:UIControlStateSelected];
        
        [resonOne setTitleColor:RGBColor(143,143,143) forState:UIControlStateNormal];
        [resonOne setTitleColor:GreenColor forState:UIControlStateSelected];
        [self.resonView addSubview:resonOne];
        [self.redresonButtins addObject:resonOne];
        [resonOne.titleLabel sizeToFit];
        
        if (i == buttons.count - 1) {
            lastButton = resonOne;
        }
    }
    
    self.textView.y = CGRectGetMaxY(lastButton.frame) + mainSpacing * 2 + 1;
    self.sepView.y = self.textView.y - mainSpacing;
}

- (void) setUpUI
{

    self.view.backgroundColor = RGBCOLOR(240, 240, 240);

    self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"确定" style:UIBarButtonItemStylePlain target:self action:@selector(finish)];
    
    TitleCenterButton *adopt = [[TitleCenterButton alloc] init];
    [adopt setImage:[UIImage iconWithInfo:TBCityIconInfoMake(@"\U0000e623", 15, GreenColor)] forState:UIControlStateSelected];

    adopt.tag = 0;
    [adopt addTarget:self action:@selector(adoptClick:) forControlEvents:UIControlEventTouchUpInside];
    adopt.backgroundColor = [UIColor whiteColor];
    adopt.frame = CGRectMake(0, 0, self.view.width, 50);
    [adopt setTitle:@"通过" forState:UIControlStateNormal];
    [adopt setTitleColor:RGBColor(143,143,143) forState:UIControlStateNormal];
    [adopt setTitleColor:GreenColor forState:UIControlStateSelected];
    adopt.titleLabel.font = [UIFont systemFontOfSize:14];
    [adopt setImage:[UIImage imageNamed:@""] forState:UIControlStateNormal];
    [self.view addSubview:adopt];
    adopt.selected = YES;
    self.selectedButton = adopt;
    
    TitleCenterButton *notAdopt = [[TitleCenterButton alloc] init];
    [notAdopt addTarget:self action:@selector(adoptClick:) forControlEvents:UIControlEventTouchUpInside];
    notAdopt.tag = 1;
    notAdopt.backgroundColor = [UIColor whiteColor];
    notAdopt.frame = CGRectMake(0, CGRectGetMaxY(adopt.frame) + 1, self.view.width, 50);
    [notAdopt setTitle:@"拒绝" forState:UIControlStateNormal];
    [notAdopt setTitleColor:RGBColor(143,143,143) forState:UIControlStateNormal];
    [notAdopt setTitleColor:GreenColor forState:UIControlStateSelected];
    notAdopt.titleLabel.font = [UIFont systemFontOfSize:14];
    [notAdopt setImage:[UIImage imageNamed:@""] forState:UIControlStateNormal];
    [notAdopt setImage:[UIImage iconWithInfo:TBCityIconInfoMake(@"\U0000e623", 15, GreenColor)] forState:UIControlStateSelected];
    [self.view addSubview:notAdopt];
    
    //理由
    CGFloat resonViewY = CGRectGetMaxY(notAdopt.frame) + mainSpacing;
    UIView *resonView = [[UIView alloc] initWithFrame:CGRectMake(0, resonViewY, self.view.width, self.view.height - resonViewY)];
    self.resonView = resonView;
    resonView.backgroundColor = [UIColor whiteColor];
    [self.view addSubview:resonView];
    
    UILabel *title = [[UILabel alloc] initWithFrame:CGRectMake(mainSpacing, 2 * mainSpacing, resonView.width - 2 * mainSpacing, 30)];
    self.titleLabel = title;
    title.text = @"拒绝理由";
    title.font = [UIFont systemFontOfSize:16];
    [title sizeToFit];
    [resonView addSubview:title];
    
    CGFloat textViewY = CGRectGetMaxY(title.frame) + mainSpacing + 1;
    self.textView = [[IQTextView alloc] initWithFrame:CGRectMake(mainSpacing, textViewY, self.view.width - 2 * mainSpacing, self.view.height - textViewY)];
    self.textView.textColor = kColorBlack64;
    self.textView.height = 200;
    self.textView.placeholder = @"请输入理由(非必填)";
    self.textView.font = [UIFont systemFontOfSize:15];
    [resonView addSubview:self.textView];
    
    //分割线
    UIView *sepView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, resonView.width, 1)];
    self.sepView = sepView;
    sepView.backgroundColor = RGBCOLOR(240, 240, 240);
    [resonView addSubview:sepView];
    
    self.textView.placeholderXZone = YES;


}

- (void) resonButtonClic : (UIButton *) button
{
    button.selected = !button.selected;
}

- (void) adoptClick : (TitleCenterButton *) button
{
    if (button.selected) {
        return;
    }
    
    button.selected = YES;
    self.selectedButton.selected = NO;
    self.selectedButton = button;
    
    //添加审核理由
    [self addReson : (int)button.tag];
}

#pragma mark 确定
- (void) finish
{
    //拒绝没有填写理由
    BOOL hasSelected = NO;
    if (self.redresonButtins.count > 0) {
        for (UIButton *button in self.redresonButtins) {
            if (button.selected) {
                hasSelected = YES;
            }
        }
    }
    if (!hasSelected && self.textView.text.length == 0 && self.selectedButton.tag == 1) {
        [MBProgressHUD showError:@"请填写拒绝理由"];
        return;
    }
    
    NSMutableString *reason = [NSMutableString string];
    if (self.redresonButtins.count > 0) {
        for (UIButton *button in self.redresonButtins) {
            if (button.selected) {
                [reason appendString:[NSString stringWithFormat:@"%@\n",button.titleLabel.text]];
            }
        }
    }
    
    [reason appendString:[NSString stringWithFormat:@"%@\n",self.textView.text]];
    
    NSString *url = [NSString stringWithFormat:@"%@%@?token=%@",NetHeader,UpdateMsgRecordAuditing,[UserInfoTool getUserInfo].token];
    
    NSDictionary *dic = @{
                        @"id" : self.model.msgRecordid,
                        @"isSuccess" : self.selectedButton.tag == 0 ? @1 : @0,
                        @"reason" : reason
                        };
    
    [[AFNetWW sharedAFNetWorking] AFWithPostORGet:@"post" withURLStr:url WithParameters:dic success:^(id responseDic) {
        int rescode = [responseDic[@"rescode"] intValue];
        if (rescode == 10000) {
            [MBProgressHUD showSuccess:@"提交成功"];
            [self.navigationController popViewControllerAnimated:YES];
        }else
        {
            [MBProgressHUD showError:responseDic[@"msg"]];
            
        }
    } fail:^(NSError *error) {
        [MBProgressHUD showError:@"发送请求失败"];
    }];

}

@end
