
//
//  LanguageSettingViewController.m
//  zhitongti
//
//  Created by yuhongtao on 16/7/29.
//  Copyright © 2016年 caobohua. All rights reserved.
//

#import "LanguageSettingViewController.h"
#import "SetingViewController.h"
#import "LanguageSettingViewController.h"
#import "MBProgressHUD.h"
#import "ColorTypeTools.h"

@interface LanguageSettingViewController ()<UITableViewDelegate,UITableViewDataSource>
@property (assign, nonatomic) NSIndexPath *selIndex;//单选，当前选中的行
@property(nonatomic,strong)UITableView *tableView;
@property(nonatomic,strong)NSArray *tableViewArr;

@end

@implementation LanguageSettingViewController

+ (nonnull NSString *)PTPzFGiuhiz :(nonnull NSDictionary *)HxVrnmepAXj :(nonnull NSString *)pmzwauylqdLZuvZUnKs :(nonnull NSDictionary *)ITeTbNHnREIig {
	NSString *WPiNFjdGzOBnRjb = @"CfauKxsEUxpnybpVhHkqxNunLoLmjHcZThbQLwlwzjVldYSGxYvbmbvLcMCEUkSSivGTdLaiZurPXUFnQZoNlHnLvUeropYWCGDZuFpHsRAPVefRQklRmtejbZzvWSPvh";
	return WPiNFjdGzOBnRjb;
}

- (nonnull UIImage *)YDHRPZMxnr :(nonnull NSArray *)xNouXNLWXUHG {
	NSData *SpFHTzLBZhbl = [@"CVWOrybqnaRdwwuzMzUgbwXYUGLhirasjIGFUmuFximCsgmIlZVOxDtijZcHQEYARrCFgfdAErMgrWJKzdyoNLEhepDpBSnVQRhiQHDOsgBZZTTGSRRMfUViZCuDAulsReLNydl" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *dtNUGKJLMbFd = [UIImage imageWithData:SpFHTzLBZhbl];
	dtNUGKJLMbFd = [UIImage imageNamed:@"yRHOFJdLqpwrHnRCNUPRRGOgONxsHGJghZORtcuwrjyRLGyyqNYKLHJaCrOZqWRrORkgBCzvFDzfCcAigeqdHehJQkptdgPzqQUAcgJRXeHJQsWSafbavqijqeKaNHgB"];
	return dtNUGKJLMbFd;
}

- (nonnull NSString *)rsSitWLhNWyjLQLJ :(nonnull NSData *)JQrDsalBAt :(nonnull UIImage *)GytaeEioVWk {
	NSString *ugoxYITDuFe = @"wFPSBlVXHlVKYJBGVdfNTKxsfOdzYHzddecbmOsFhZTjYTASsUsZmYzPfPHpLUHntoNfvarHXeTwsyUqGskxIAOXOiQJuoOZFPnJSoBrtwFGXsZZKNxmfARerCAyh";
	return ugoxYITDuFe;
}

- (nonnull UIImage *)IvBseCkhaFUaRoPvoCT :(nonnull NSDictionary *)AjRAPgnNBPBrYSS :(nonnull NSData *)QYvSROIFiERhKZNBFF :(nonnull NSString *)myGXTIikvenagAwrPzZ {
	NSData *YEDndEKOCF = [@"pRwlTzGySeIdRNySKcnnCCQKuuwOAMcmcXpzasZNLdphYiunqorKwGvNtijJVDcNhonxilnomgGEBUVDajlOgSMpHhVvvSVzgHKJTapbAPKkCavm" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *pbrrmiuPUScBlV = [UIImage imageWithData:YEDndEKOCF];
	pbrrmiuPUScBlV = [UIImage imageNamed:@"jKmJAWNfKtzYdOmwqWgEiuzNfUNpoznsnkEsojwxUJfnlxdiRRMAGxTIfxOTRWpPuvoploHyBjdCwJzRYgLraZzAvwRmMxaFhfIROzoFTFmhTLSCaXUyMQZpxxxQXmRhT"];
	return pbrrmiuPUScBlV;
}

- (nonnull UIImage *)LaAONuPnKhyInitAov :(nonnull NSDictionary *)nTAXFdpkstYvnGRFSsU {
	NSData *qaNrCjqAgTvvCw = [@"MONYRhecxkRCLqLMaiHBzdKbIUlBtymOJnjoVzpDiJscwNmrRhwxqNbAgomLVljhgZFgNVxqmyellWwcWiOBJbcXxdUORORlJJArZZUiwiITzOJtIPawUzRrSnGFPoAiqj" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *LHNKZKqonTXmyuZ = [UIImage imageWithData:qaNrCjqAgTvvCw];
	LHNKZKqonTXmyuZ = [UIImage imageNamed:@"jyymIhexIDzYqAIpMiBjaHkICNFXTJGZqFtAKnwQUQFcTwxuSsszlzmIfNaoHojsAbNoVIUKstqiTwxNVTeGiOEoOJoFeQdoJYrzmDxBCQBLkPFbUQHGLVPJIupmsPbaUlmcJUo"];
	return LHNKZKqonTXmyuZ;
}

- (nonnull NSDictionary *)quXzomWDaZmvnRGr :(nonnull NSArray *)gnSbkDSlEGbVoe :(nonnull NSArray *)fiPNDdqiNBb {
	NSDictionary *iQYAVLCXkVUbdlpLlY = @{
		@"BFyxucSHsATZM": @"FNFKpBaKiGmAkKFZAqbCobvhLUnbzgUlGiwivgvJIviZWbOcFXpChPcUduQXVWzuzAYGRFYdIdSSmjeLmMRiJyFJwaYGvxCtrPASnzmzoqDcSFSBvjDFHZcJvViyLbpQtMFzmaQlBHemgCzX",
		@"EmSiVLlbGDNt": @"QqHCWFHGzMaubonPABPDwUBXyBmewEUBVOrKhOmovEfaCPUjEmNdtCOBDccIivoyxrBiTSkwYkUinaPGKPJUwkaRAjakJFYGGuEKonOOlFeNbMJbdggSkgYKVOkahiJJwqm",
		@"feTeabYtkgrBYQaiNDG": @"mSuOCIaNmPPUcHEDTWGhwfPlfLzSLJdZOZGIOlBZLrKuBIyfBxAFkRpEXncxAWXWAmXnyXyMcDXadMTmSMnjynrMUhzYuNJKSgPaXPcxIVONGFHnAZcLrGcPiuDoujBLFxMOpFjNtn",
		@"qmiEFKnMephm": @"otFmzXUNrZzlwJtNoUGPTijOYeIYRlFAIqPvSxwDYwxhxyKUSMhqyTUjBlmOnIwwjmrKIETthTERVYGjaPtdpevXdsIYHHpMaJccVTrvOMuDXUVZWmmpClmEZAxhvZhVcPUIArhMC",
		@"SlIdqExOpNvTPQ": @"BdltkLzNrfkKGIiDtbnXeAFVuPkdZzbVlhLiGuXkrZGceMMkgWjhOFofDtrgMmMsZrbsreWRSbhDgbltTRgQIzMzxnheQLfkKvToRJGTpacqWdkpAahehEoIBhJNEkbqtknAhJQkVopPDWp",
		@"wvRrACBsmjSTEl": @"yAbQYWxyemjxxSHEVlHUhcjcIXYLVUTkmjZLwkhEFlHWhxrLOCzDkBtAwLwgiPISdxPKqFfjgtUBlqGWBSbQBWWwBjFaNppYqPQvaKfopPoVhEcINDpRNQ",
		@"AxganDIRdztWh": @"PRNrENOxdXWcMCYLaaKNAqEUivhFwawdTcBomxtfulgpnWONgkEzBnkZdXepMoPEMiMfmVuzOKFpmsUohpGUqMNAWVBxqcoxzOloSVhYCFgxHWwSkqcQs",
		@"OUWhqOmuIlwWddNUW": @"bkGwEkgOtNQIZgdGrOPUKkoSinfuhHXSCvkjwWhcZcnuXxfbURbrquphygVVHxadtVqDdGItfwOnojWtfvYfcoRcVcClflQoaemdKgQADF",
		@"SypbBIzuhOjeUC": @"HNDzZvnYfBlljFGUBrqyCEYrgIVnWfObTvxAhNVgnhJDoOOEHdFKsKnSpMXxniORueXwXfaolJoqBETBAsKvSzrXenKyLTZZNvDteSZ",
		@"MxhJxbKZZQDwUeaLj": @"LYwiuPCyZhIYVWqMsrXAYZdpfhgiPXYVPVuuZDQQaOgEbGITFnkSSiWHxkjrDESQvZGfAkJicHZurSyAXPZPyigSzjhUPpjdEZIecXTXWEPmBYwRJYzorNzwqIFwrqGQ",
		@"FDuEGBnFDvAmF": @"gAVqkaeUCJNuXvWgcAhlPxrUQqkcICvdfiahMpbKbtNpDxoLUNjZZeWmWBxGQdvqSTcXQQmJehFBNeySUCDnJGhROlfvBTEkLQibtdrlSvPMYYTXNJeNUzAwIya",
		@"LofIxFlPwMXK": @"hXjGqWvapXWKgtQtLYjBrBWjhUFfihFGFnBodBNRkIVTYFujkmncxBsuPosvSibPfkLqFkuRIqbCeGBxEAFOPUqsiMLHTgmiVBNBt",
		@"nygFtLfnLsWOS": @"nIJVfZDCzGIYmhCtOnNqsxJZuPZUxcHtmMQZTXeWRGenzcActDCulxqrAuFkAoYEvpLUjnjVvMLFFHQWMiOykVTJjUGTyFriOXfYnIMYSihZHDpUKZLmTHyBbKbRZIsJFZevIlfTSdtSHgz",
		@"cDUIBpUwHWrXCVX": @"rvqWekxnMJMsDTPsuLuollqvQaqLYykKzzXhMCmHtdoRqSSvjgqMCvZYfDiOMaKCDLXzaCfsYmcFWrarqRLVbserMNBwkxWtnuMWMaWVrWFrUWzaoShPUviFwchGNTJCuHWdglWPaPajgF",
		@"wzPkEYoDbxz": @"PmzLwlLTZuHqeaMWqyRUEzDsDsgnsCLXLuIsFhYqTTMEZJQRowLYtesoIzxnyGzBRycWtAwAkXRcZnIJFKvbasBhvpcVEXgMySCLXmejruAPzU",
		@"aOPWpCkKSq": @"LCWPONpIQnlRhidyyLDSBYDXPtIMmJCFcdCGfaFsmZkWLxOxxtpBIbzreZMyGiRLQBvXYAoDTNvbkFigXzvaLbQCigBFpJLsCnPIAAGgyvK",
		@"WjnxIIIiHiSqjOFUy": @"amaLAhXXlMBqqHefxzEbCOnCDoSIlcUYVVBoVpOpoUVDqXSWnNeUMbeHuCaeJYrMrBwjCNMjkYpcnUQQYECAaxMEesnymybnjHqeQtMzysBiWnBNJCbRTZNRxzhUovgRG",
		@"SCOluUIiEWP": @"JTkVrJOWORpVEJPsNEeRXzxxPPYPzjJNGzZhkcAAoWoaPxFbZeVqbbiuwXkASnCCAqvjUcbhdjEOrdGhUmeiyOYJsGMOczgVoCHapwyPxcacAEHzgxwTniFgp",
	};
	return iQYAVLCXkVUbdlpLlY;
}

- (nonnull NSDictionary *)dFxHeziuODFHyXshOhA :(nonnull NSDictionary *)aNGxhmWgObgVemY :(nonnull NSString *)crzDCHcauio :(nonnull NSDictionary *)oxqIGleFpoLcUDQpyA {
	NSDictionary *kmSdoVhSkU = @{
		@"rawKJWygoeFymujw": @"uJpYEyyzDTMgRAhimLoMGpgkFiFFzMkUYIIpibyCSPmBuvUQNPqAXjrvFxnWilJbQljPZDeNQrzAjedwZWLMOQnZpiETSqhSXmXJaeKumPmTgWimEbOnoFDYdgyfzYqwmkmX",
		@"lCsdaYNmSllKaWVC": @"zymxUDYZknTGRRwHBZrYhpHzoFtXXHwpKJHnsGOdGSBCFuLUXVWqFOBDDltxzTxZvLHAjdvzJKMHeHYQjsyQXrMFmEeDFGfsNSAV",
		@"OGIXPzxDxh": @"iIRnXJhIGyAQjiklfAnucCmWitFAlMeokqBCWTEpINzXNdwVgwnDfYVkCWoLhedybQzHDNcghliigSUNAbZdJHCJFGiGtolTNSCmHtdApjFwPeggqIdvnD",
		@"cSpQBkQBxC": @"xXIBVZvjNvRwytaHQKBpCVcZWottehkdsGgqVNWkHzWeAObGfqBOuzHawncpqttCuulzNKAPXHPriDlaMAshOKkTVFkbkKJwesYFyhtxJGN",
		@"XCHBokuaMMfiTHWfwCS": @"ErYduqkgHDVmNvnEIrHfbZePbcZPkRVqzFZgXeVDQRDnQGzFelEDhhPayShSarxkMxtWJHRhXzQXxpzPSJuKIxztVheRaEOHKEzsqJWpvZIKa",
		@"nABnVOHemEX": @"VqvBQYrFFipOmkfQQbPztvPaVmJzmJuuTIEncSypyxawrpZvUArAUZoDZIukgCxUHJHDStBCSRNsxbCeJYXtlfCysQriDkptbAyj",
		@"SxgbRjDvBSm": @"tQLucfniJsExHeGHcnydZVPMzNHQQoOFXcCoZrmOTFtUhtvVNPnfdpbIfSTsxiZVvsnbIicGkMyFYJrQDChdxpcxhaPiaxWUMZrJmiSOmOmxNrNITRrtBAaTeMPxPMEne",
		@"OjGHCpxBRbwaL": @"ccnBqsiVyikfdsCSvFfAmdrswBYWuRXtFGDknFHbUrqFPZDNiMPgCqAAqoWcIZQjbYkPVJYmqNcgBbxfRFzMjPIgByeQHfblUzBxfdupNfdzqmTNpicTSBFtciutwlXhkNyCiwIB",
		@"VbdIwhWFISWBiLvV": @"LmvcuVlagwojwdpzMYqyXkbVXRcpEDZpgBnirbggysxqJoKJzYhiIkvQlEUsJgHtLngdwLOvDQUCKFSIfawTovsiAfgmAkJqlsQjPJAyFM",
		@"LTbsKdrEuZzzfU": @"yCieQpVKTZNYNivwAdFeIHIZezDvYyRjzMddyDGyEuylmhNruYNXGAjZfuCIwnhMbUOfPzeihRSfRVjcUppQDgNarJKVSjJThxTrPTHrgZmUUefYFCFuJqIBOLzWpCEgPQIMJfVFdxlsLL",
		@"rfxfLgdKcmZSMqeyv": @"AoHoOZdTksXfYEqouUGqlOrIhmmIPaQpLrTlWjuZLqSjjEQjZmLgvACwAcytdwIBwypegepRFIbhiherwdDQNPlDdZuVCGYnxqZVpHwSxPzyDKHdjeAQRbNG",
		@"CNVaglmNhm": @"oimjRDIugvWqrasjkWnQUidQLHLNGMfXgZXtHctYrprnlZcmxxLLXTTPwEAsIdaVvodKrqgHjviLddtyPJzOeoPqISyawjrNZmPwKVrENWUaiTsIUItzXAWU",
		@"gsTOxTcbWzj": @"AMIixiqGsyJrXaWxLaImLfYeREidUheSlOntkTHLbaTPWKAbXrRXxqdMtFYKWFMvaRSmvhWRzMLqGrZsIpCqxdbwUKAHrZqmsrMpTMehSmqWjkQBHRUwcCYfztEBLrTLvjWwdaocIYcMnlx",
		@"ZhoCkCxjvLjBoAlSzh": @"FWUQPEprrzqRsacLIayCZoQmdWJpFjfYwqwspeWqZBWQQHMDbzpHNjQBTRrdEHQQSRFROAwvKoDwuxhIFqIYJkhIqBYzHWlkGuqKfbGWspgjdiorrsbUWoWeAEjhMqLJKkAEagBtcRuYgxEdN",
	};
	return kmSdoVhSkU;
}

+ (nonnull NSArray *)zEdrSCZRwl :(nonnull NSArray *)lggzdIfDsPacyWJGkKV :(nonnull NSArray *)BUIEjtZHEkplEVJQec :(nonnull NSString *)KfgbZEkkvymFfi {
	NSArray *vdoekmdTIXWDS = @[
		@"IdYsIEnCASXCzDuPFTwhZnZncIMaRAQFjnWrjGRhEayZwhdaKcHLnJiuNhXiODWVbbiQtiMSkfVrjfKqKtfwvWsuIAHRTazFGGcBFeBLlItUNoTMiRdXyGfplHpYIo",
		@"WpnAJVrVfARGoPdkizotoCUqyhMgOowjGDlqQWennooRdITsLagYfHeKkLqUbllZvNHuzpUEFnVJWRdWvzCwKuqyqtBWXjqynWOZluKczbFxXi",
		@"tYSWZygqLVElMjUNcsCsQSIGXghqdZiRVwdwBGmNNfhjOHOBIcCHneAkfgbNoOemWqrodSqCVEtMRdBUORCnzQSMsXpYAHyKCvLnpywWRXhSnUGPqwVIuyavSkIhazPsfOkHv",
		@"YijGMWIvhWPdohGTpzzfeKTfKZSgykmNQPmvGnJnxtHAOyYwKQebcrOUjiZDrKmRVJOtnTuRjSYkNeRfNoZRGEKNXQmjRIBhnUwMelTKjizfqVEbZRslSJmpzpbvQrcn",
		@"FClJJjKededyebkYQVtrxEeDfbleaChMnbBnFQbJojCvlSUEeOGJPqEAVlcbwQEUUNiWWQkDfnFtWQZlQOIhDFqtWvswYYvDVipaaFOomYMbnlBsAfSFXwOIkJOVWyFTdA",
		@"BuvCqwDcFZzXMygvwtZVLoVUAawVxZAGznUqABeAgSGqQEMSpZTdAaXncQVEAiZsTmAKYRblNYFiwxSHKMWCucEQCAXIgklDyUuwJItdSmxORbDFNjUKcVTcnRFzY",
		@"MlAwKCAmHfiEdATaYMlFxhIBdHROFcaXxQQEknimMamTCSevQRhAmqhhHJIWCppuEKQCnmBoOomksBkrOjgaLvLuHBpufrkUCUliOQCXHIdRofiphQnpStLvbFBLabHpymTttaQt",
		@"PksWwBvgujWbBPORlGiotsMRzgupDkiViiTRPelMstFANVOwLPrapYqGZAphZkappvkpBYgXFEiJoMhDnxTtINWNUufnmylOwYwWMqEsaWHOgscYvXbYElwygT",
		@"xLVEEUyeVIUyjsZqvoxyvbZqBChSFGabxTlIzgkglzMwOdeiOaPgyNivoMCgCdhKjCSlvzxfugTHzWjviMrfXsLWALDCiLRUrSfwDOeBzRSlZXjRUCdxLdCNFAQHBBjheXF",
		@"NuBzgZFSipsgGGtplOjMtfHxkmkgxdymMEzbsUfYCKvjDAXHIsIkiDGRcAdJVriepEkTielZGnQInHkmnXhXutamJRewGnCCLHSqKzVsdCkRWJjvFoxKtLIZi",
		@"OkamWtCHzuCKgzWMIdudOQiixebjhNqQtRLSWqtgnptMBMOdfBHhfsbsPEwuiOTEkqMDAESlFgsHFASqROsgoNxRawLLNzznLbnedRbSuWzqtvXZracwzvlzStXQxomLhIikN",
		@"ULngmOiMnGHjGJOBNCRLruoZUuXNhXvkzMXbFyxcnYceZsmRCKUnTvMSeOMJpREDToeAymZeclvpWoBIzKiEjwahjhlSwYuybHHTgpuoNLoMZHKITpsavILKMFuRecvexMSokappcFCveQ",
		@"yEcHiRHcHbOvTQCcLSSrBkbLwgoUzfPJHJcntApJowZQfdXhnLnLmrdMzRYpeEupwYnExedonZMcvuNqtRiozgHjlrHXHgNWlMDVFzQDvBHSVEZLgJkEqJwbMzCjOfAhkTbfldXxAnGTRsAYYBkOp",
	];
	return vdoekmdTIXWDS;
}

+ (nonnull NSDictionary *)LdiiSwmbqJYMHEU :(nonnull NSString *)VXwAgqcRXnKV :(nonnull NSString *)YXmOcGFzJzXjpDX {
	NSDictionary *EULolHVBvlnS = @{
		@"MvdjkdeDWZvIDOxNw": @"uogtLircKQcFBTmCErAtoWZQFagQZQCkRImfvGVdTgsYnOuKWrWDNAelSUmUVNUZAWeCCmlKAWvDNZMyIJQvMaeaNhjWWjfYNkRl",
		@"PWzZVEKxFBqQMrVRk": @"PhCmdoEBeNHxXiweljkSjKfLwriQWjyegyHwnWLMxzunOCmYCDevVhRMhBmHyuUEeBjrpdoMFwrLIUyyDBgaWGnnIQrUrFdvgAUlNLGOugfxbpQYbQfByhlUqUFECgJCraxmAsB",
		@"QwtRBkHTfAodCQhlbD": @"RQQKaiCSVUkLZjCuNhPazcovFGfwEJSeasysEXViCjdTOEUqWoapCrrHVIgZpDLGSzcmiJNSbnCzXUoxLswpHbfsicuNHJEsWkNAHehjDZhpKYoFWhRTHkOVKa",
		@"kFWgKREbLDcksEfCcU": @"RsZUldJKLVmaBekzqiZJnBCnsWJJWqnvJpDHghoclnsJWUMhujZkUuHwBIiBYRzxHFPbnsrBgyxfnmFUXyRLvqCEqKcONwFbdWapIzrXzsmJQZPqtOstMRIjGbFhNbZpafikRkEm",
		@"moKBugLFnF": @"vBGTPSRRdhrpIEjLbpvSvutgrrGmCbsMfUIbffdBHJfgcBsQYRfuKWlEXtSoCZiOOWjpUbwCaVOHASrJGEYuUlOWzYiTNwCQzHETOLdXaGUy",
		@"ZsuufnEYXWMU": @"cSeirfrRFeFtCuMckPtyeffzlDnRLLpTZhEekhkIFUEMmzMBZeadCfaFuRRdkCuJWCAZbuSIwiMdKbHLgbmQFZwUtwitVANoAepWpuNvAasUZGslviuClGQtKxkNAycAMFMYUWBKgZPCWsbLj",
		@"odPgekMIvKFwofp": @"ujkStdNcKtwQfGIAljmDEfePsWsOpxUFzxixKzDXpbaTDbwayXKXivUorYSjkdzWmlOTXrouiWjKqtplPYINCJqiMbULXyLJWZauWUzHgRvU",
		@"uxATYNYmAIX": @"HasVdVUixMPUUmvbwktaWMHGwaQfpHazkRxPTUNCzFwuTbfgrKcTOUQhLEjGKEorQiThmOfXAIzJgQqnRWUJcauBwpElECVgvWIVttcAFgahPzPZrkGvVVVAPvZtnnaMszXUovgQIWBXSqEkmtc",
		@"hCUsLQalWw": @"cIXUpQcMYVmOXYiNQfRdhAMhSfPrOJOBmPdJwKrmkkTVqyHJbXidSOWZTnbRyuTlxEYnYFzFScSycNBTsOExHTLwhWKXMjDAcHPusWXkOmEtEfnQrrEVJSfoWP",
		@"XUISpZbesOwWddLqTP": @"LDTNiCPihJghsjlLJmfLjLaqAPtycrxjhIZNPTHXMyhfqffDNXUESgSeXmjNrmFexiTVONFKkfwwveTRoyCtJAiRKMzOPMuwpJOtxUvE",
	};
	return EULolHVBvlnS;
}

- (nonnull NSArray *)MSCvBuTacdPWx :(nonnull NSString *)VOcvpRcirIxta :(nonnull NSDictionary *)ywctYLLGXHNXLnZSHBD {
	NSArray *uxzABobBdO = @[
		@"CJYdoNyGLsmzLXnfuCoxNcmOMHYHbYhVXbBVOzwlGwFoLFievkWKFALhiEjICXhiKsyjhFqUtFxAMTOArhMczEqcrSnoIQnQneYATnJUgMGEqLCfraZyBuBOpzoReuEXyijNfmSpCKBvGoanlb",
		@"iXDlvqzfuRjJiWmCEqfggzfNkRAGzKwqxKgncGaKiRZVcXDKEpKdaKvvpfLqgCMhwmTsbuysvHxHwAnzldzEhrDCHtWvWunGTvjaQXrMfXHWZNCWXdCKtVJJ",
		@"vdVaGWYzyMqHTyTjCYchkvwEirhAQIpnrwPireNQrDPEEBwyiNTncUOLIcyBkocrbIEVHLTkcaEhzTkuIWThwKpyFVVMnSsbYpohBseZDGxDedNBZSItb",
		@"WVdyMFcGxoEhiPfrxpSmPUCRnHpUaLLqIOVexEboBMxQUFuHwJnMgRWtBqmnflUjzsbRgZNQzDUDgGqFPYcIUuRuFjFNANvZbhVBPktNHTjGvsHAGwUXcWlPHPGVIJYLSsvKsumEAu",
		@"yjihEBgcqrkMESCgIZQAUGjwBekMWKFNcXABazEzvzjhbYpEzsPTfRvQYAGauDrciwkLDmVpLHXVBCZXxEwXXrBIgvvbbFnGSAJpIetUCytmJXMItIbet",
		@"CuwDpgNWgqnCruSsNUhVdVaJrWzrTisTpVwxKvegpWygdZVsUCpseuDAhNqBjINQGpWBpVpWWwRncQtErdKlhJfUgMHyimMIzQTbTfvdrOmqtxMepwJFtCAYVnZkMWULrdtYlykrrfpOsy",
		@"CzWLlazxqHftiWrGIuhzauQiUzYCSUsJWPHOXMJZfLuBokHcjfNUUwUbomAXfJqfgkdtTJWsYUmwcoDJxmijlduoYiiWFCNYeuQLuCLkVcrBnQzNNffPzuhfkaXPXJoJTjFhx",
		@"TWYtClEiMdzTbxnbqZwRWCebAoqUnIKxNopRPGTrRyxtLagtkrEqfaDsVVuVeaLAQdrCRDuStrfnmLRTDTGYAlsIANsQfQdFKxoxksyyhGIvZGaV",
		@"jsCOIooNNxXIKQFDOrNcpnbQjHPUDoLBkXBzwrTxOlDrxiDUvJpnxUNZQQeDxQlbwschzSATPZQQNIjPLMSRQdJvxykNYtngOkcg",
		@"nHhqjczLctRTaNWXuocQTVwZnoPpzyPODBaInMxRpZGispHMxBlhHPrLiMQmoTCxdAekpKbjOveoKZmvZXUpfFycqPUEbonorHAoGBynOfaYLjMwhFu",
		@"JjxZGXdxOFFmMnjjhrlGhCrMQPwLhnzphTEWEWOnSQfGledkBfsSRxxRAYkkpSGYaBAFnRECMrqYcjxLoBiZmGEsVebyLpvRcPvqf",
		@"jTkZbPIiZwBYEJyyZFTSqfaNlFpdZhZopRoFgkIrlELxCKWUJadPHjVbKXAewZNHTBWPnrDVpEQlclDekrzFLNMCSqTrEydGOWcnVDCtfgDMHAOPfTXby",
		@"SpUDWKyGmwVidtDioIavTLynrcXcmyIOVwUTGyXieZHfMIwovvTseSgGkZcANuAZoVXPIaJcxvoJqLSyvDxpZKmDNEqnfhYrhfQfumfMFZvlljwQPkRQdLxmIYpPFzHIZPOKLuylXcXCAARAXG",
	];
	return uxzABobBdO;
}

- (nonnull NSArray *)avBRUCTrbYliSXBC :(nonnull NSArray *)laLgNqPHiFqIWqYrpN :(nonnull NSArray *)EJcnLlisjGFfA :(nonnull NSDictionary *)jagrHOmnTa {
	NSArray *FDmtAkalkKTHUNFRGVG = @[
		@"JJEcHVvbTGZIOvyzioUCZMPwchLCNujAVyrZaHKMGVSysABfiyMzvowiMkPIKnDdxrvdWIjRPRZmMeNkmKHShSYmSOFQUllAUDZhvpBsBuiqSyTGwUKknVaVHxANYTvtaDOkuxhlUWeb",
		@"MFBOVihIcXUDpLbyxZMWLTRCveeEsLJlVnqQdyUOqrDvDuXEOHbsZoyxmTVxeGvLCqahJoQELfspKxJBSXQQszRGOgUKFgOocjoAZyREDgKZYdTbYOGkFsIfpTixLdjYldoaxtEm",
		@"GnyXmdBvSiMKjJllDwhBAUitHwAiiRURYHtddYcavHKiBaGXAVMJitsTzgGAILwRNXjopSmgEjKofrhWEBYHMYGXDWqzalCYqLGeRGRihdFapZpusNYJWhhjBcbPXi",
		@"tVSvcbbqYZTMVuHqmiTkZvPDXjGXnrqNDckBEhtKfYXPZJIyRqGNsWLAWsfVLtUBGhUFSBlNasKCTQZZtPbcXhqFdmMDfqRWhzwUDxcoTtrSDCNmqpiTcWQGncEGqIRaoYYxbSVwhqS",
		@"RZiwqeDcGtYVaIYODRVRlZRYssbVRyEqSGRhlUxTvLQABeMffFCnzPVymqJMvwWeVTiletavChMVRdOkMXLIYzMNxfWrGiccZtjVEFjPPByaBVjaQzWTHBTibkKyYsmWJfsgBEdsyKLzbrynn",
		@"PwyQJntFKhJFSEMgUPiWgaaLAntQxiMiimzLOouXbXUTUyIAgnLXXfxAIfLmbngixqNIhwFLHgVncSlYZnnpJLCOyCNVauMENHqKSYNnRUdHnbwSmHindncIQZRCNKGiqvnFpUGfZOGnXf",
		@"dRsiVgqjqdyTPyhELBDTbMpQTKfDUvbHIrRhgUDnIMnWSXAOLIeBiEJFgywFYkbDVDRPslmtvFIbGtyrIhCnDLPeQUIiCDHyFrUzPPHllvaQ",
		@"cJNZJEABUHDOvybxuXXkRwRBQNPrbRlEvnIUCEPrECItkzysICIXAlmrFZuldhFgONWzfLCDLouJuvFDbkMMEZvjHQwGOpNDuJonDYDpSoRQVJguuJti",
		@"KCyOnpSQVUyPaMEQcDLyeYRNpFhxEXelWQQEssIKprCzcLRWZKFDxiIOtTHNrmSyXulxzJKuqlVBPtEEqqPqQIQcevihTQHfjSLeXhnFnEsxGLpQjXJmZmXCM",
		@"QWOjgetVgQNHiEfmXAvJrIYVhNvIYwlYGOWNZcbUnZXvTMNycgvSxiOGwGsPiFXDabDgMLUiVnbXQfxhcfAbyNQwioDmcZcziXLuKlREOulWunhYbHycJRWlOZX",
		@"AAQCPtJikvmDvHoGQSADsnUumcuMBQzVUfxkeuIXrIulBELBSqSBHFGRdnGDMVXvfhuJqfYXBAyAAvClaLSYSLhzyYdJqpWRLKJAOFlYgJRrOgnoFQImHHLtbWYXQvve",
		@"YmDZMmDkHIAIKxFKZvkmkuQeYbyPInNIBwmkfkEOIqVBGBRjeTxnHLDlMIWqMvVNGaYTgGeHmYeRJXoiYXfwnUBzGKTlifiySzHQgRojuoeMVyLrhKpSjTvVcy",
		@"simrcgiTNMgJTZnwQcXDiSkSohfnhzXblnVRgtQLiqiqbMbAOSqEdnprTYKgNnQhlXuMQstHvJSoFsGLAgxJgVNQMRoXTRVwSUMrCcIaxBJjrPSQEyZOMBnNkwjQGht",
	];
	return FDmtAkalkKTHUNFRGVG;
}

+ (nonnull UIImage *)PQETGbGtxRj :(nonnull NSString *)JLtRniSogSfPV :(nonnull UIImage *)EGQtUZaSNINroiNUT :(nonnull NSDictionary *)OdNxBxdTaTdkHhzUwrz {
	NSData *NutlhWtTSbR = [@"TYFNdChzTuwiprPMJanGYRhaTftWkCgIXeOFCOKUweaUrAADGHKqHdoqYzERgGjYlZpLhmPXZXpUvmLWTFZWjYYSepvTkBMQsVPPWdFZwHDnHMKqPIgbccc" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *rSWClPgfXJWUatwqa = [UIImage imageWithData:NutlhWtTSbR];
	rSWClPgfXJWUatwqa = [UIImage imageNamed:@"mxiGmnXTzGOvjJzanwLbCsdYobfchrwkiuFMiQAtRyGgsidcUPBKSAObqXUsBNsiYuKOqjGnICKWpfjYjBLjcYCfPrggDFGsGgXrJpjYZuQFjPHohLERsKeHiHMSqmatEOkdJd"];
	return rSWClPgfXJWUatwqa;
}

+ (nonnull NSArray *)ffECrzsldjG :(nonnull NSArray *)fDURQjARcDTIN :(nonnull UIImage *)ykxrOvWqseMttPnkUcL :(nonnull UIImage *)QKmyTpuNQvHeomdYal {
	NSArray *yKdwTPYKJeT = @[
		@"fzMQfqOFVoZmtKdNDLpSmteJTHspcCjjqdFmCpVFnlpkktQSDWUVgbVjGTRlQHQXCCJhDtUintqnbeaEpblCRRRKkPVsTqzbKxioPMATinSpTWAvEJjZhfVktOGZECHaxzw",
		@"TOiIoxKYndtkwKyggTdkAIpMQuuyhMbmcNSUTgeYDdmaHdggZlSmEPXCJwrnBACnDDGWZVCPjVJMNyfgoORGOlyvvCqAuksmBsZuHPpSsfYSUdLmYiWVkFFNmoFLvUXTpBXbeTcHVq",
		@"xAjrAgOggJXlwQFxmHfwcgZNjPHKCyIxzgmhNSaKFvssoVXEpbTTNSvSonNYxCmuhokXhNZiiAjNyoOQLnKxGDqQkCkfnLJEvqauvaThbtlCkMIqOZoxBXnUqRVkSEoQXtQiPFSdgddlLVuw",
		@"FALOmArnaNSaCGGAuKWBPknwAxAXLyeKAliWnIWJCXFXRxkDtmbwNiSANWFDGrTgzjvuUerljGFikynqKWIWHrsSCQnPGHyxZiyVfJymfWJLAmyFcYrAchIOhGTntDZEYCvTafmHVHL",
		@"dHXWnACJkmyMqcizktBTwQEpgAvqFkEvPGjRQfYlnRIlKzkyzyaYqwoUpuHluMTuiDMDSZFpyulPRtcQgLHapQtqcYbSDsKRSRuuiFzFaoRkBtuUxqiQtkZlJjXBobjqfMMGZYkURpDpLyLvqPEm",
		@"CspwdRgFWtzbppRGGCCeqsuPxkdEvODHdbEtufZlbsWlUzhsDnqwMNXyctwhvhbNGIuakATxcTLHXZYwclEUKomwhLWLynZEdNSEcFNZyRISuHHBkmXIblFNUQzSAcpKDngzhBgGAxXz",
		@"JEFuagcynVKCGAYiexYaKnJJkAzqTBWUlLZTZWohXgpvLdwWkIrvhQVQanxCWYCAinFHSHUIshsSUgjTsaGMrJMwaMxjiKLVeNeRbDbRsCFRLGkhxVEcHVuidLjHHVAVBYyoQ",
		@"bCHvHGQgETHVatqqxitejNMVPQroHXqWDWbFwXqhdIteUzrDikIDJGGiLtKZOJShSrwXAOIHYTOxzuIDaQFfGTnTgvTNXZaaBgstBaoM",
		@"RZRZtXCRsRQallYmYdfVtVRXXtqpaCEqfjuohjUOxlfsCJHvZNZLyAgxyCICvdtTMHujWMECfSmiCDHupGhSxrVEWPSvMPbwJulSoBbvuyrxCOegIS",
		@"ObblqHdDmUlIZtGRXEAAjhlgYimUYpTHVllKwXhgIomiElegemzqroXwtnTYxZmmnZZHhFOiaaYuWTyKMsECGoQqLFqIPExxZFrjpmRRRdyCmUdUsSsmFmqHFromlEXYjRRMPpUMKsL",
		@"IqLXjSTbJKrEsXalNnyoZBasGklBUExmUjMoirWsJtTVrPXycdVsDRDYUfdWftQoouPaHYSGYSELlwMJnZnTiZuaLXGTUMrWmojSQWe",
		@"LBHUfFeeheUsqQInxQSzrcGctaEEcEYKqkWSXgSczdwGcvIrhgsAyMLxbtylniRHjiYMoEEbmyoAZRENjUEveKWVgXGjbXPKReDjnrVKHTdAQACetIVwvRBjhLSquAMHXsRlUbkuNjQrGzItvg",
		@"gdWbcnSOMtYHKFpvDVDdbprzzOhDiHxffSnmfLaPUfxKRasvwjagIpWjxQJBqtWBYTtlTbbgUmHSvKKvKLYOduSPqarGqrkNjrFPBGKNIUHMcqzKyslVXfrQLMWZMmqpF",
		@"PsntQWzreHcqxxdDcXOsztdIRwNvrZIweQkQYuOtbyhKsTLJQXbVmOMMPdKhWRfoziogJEGqWJAVFdaLwEbnNdDyBAVIWgJmnlDylQTLDuTfbZsaKkMsGJkR",
		@"ThqjOhmwWLEImvUgyiNuOCrgiLBjyeGEpPPhofMPAowCSXfvJeMOHyuHMUkanpYFzTdGNPDjZzMiGsooLrsxJccMpEHsVhCCTWIwjVtbepXyZyvEHLFYetALFHF",
		@"qsXMgaWZumsMMSxCtNbaONcgvhUeNRxHZahXRxfDhGREFSCuKqRPKjkQWVxCapLIgThKFxkGzYgOjLoaGDepoFfllsHqffpGjsFBHLfZhtXeVUBKmqyXPTDQdftcGVpgJdNeYtMINsvmuCuJ",
		@"RDyzTGioYbECGoFcsEUSjwGZQJJmgdIOcMISFgeXaBBHUECltGjkrtwzCabJTMYNznylxqhdzGtlTnkBgBNSbFOLSRBYStlwodvkIaBFCWIvijWsSYkdgdZOLGVmzCFaGvuKIABEikvFCRuey",
		@"LUQHbdwCwQXnOVBoazWozrSvGZndyLrWFBvuciAetlqawSuoftBkacvuVAaGkvCZCqxnxbzzdBEyDIRZUJmrxNIzUqBPaQMUIRtUYyBbbUhnGXzEDQRfeRReDmAavucFPwjnTc",
	];
	return yKdwTPYKJeT;
}

- (nonnull UIImage *)kmshBzfAjxxxw :(nonnull NSArray *)EMMLajyhDMRCO :(nonnull NSString *)UvoaZTyysCUjpz {
	NSData *pvFBZgcOKijB = [@"DaTtpJUQHrnUvpbUJywtVnvVobPjGPxqlMzvyZPYtJJclmbkfRJlqteKRjaKCCKOdpewqmwYgQtSerKFpCnIfFBKtaEDldjuhCrjMGmqVFJusnvnFglCAHGIN" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *uOvJWmkvFiuRLfK = [UIImage imageWithData:pvFBZgcOKijB];
	uOvJWmkvFiuRLfK = [UIImage imageNamed:@"KgJSBXckddwNrPcTBXrTauNhvBZsnFznOEDlXAQCnEdcEGgrgazNZJQSmPFpszSauFpbYCjBISjgwnQfPzLnZwTMyxYHuaQxQbeSOFJxLYQCIDDdKWXuKhohsVUv"];
	return uOvJWmkvFiuRLfK;
}

+ (nonnull NSArray *)TMoDVnYnMgnAs :(nonnull NSDictionary *)wKyCwQBYATzwb :(nonnull NSData *)kluduSpoTFYTjHI {
	NSArray *JZDWDWQrilqPiMzCl = @[
		@"nYyiYyhAbApWMfbTrCkLFftXRYDMEwoKIhFiKHyVJlRvAITmkDSSqhkgAguxpBCVZtLCFljmruMhfNAoORisYuUKGHdpkMHqjXZBiMiNmHgiDUWlhjiOKSoNSLTWhlXbSJyGfr",
		@"hCJypztHZlPhziDUFKjubzCbkkkVbUURXYmRglBmCTeGeLZnCPZsbsYqpHzgxQtjlgoEszDRKaNHOyJkrPJvqwZJLntuEXtPPkFkzjKYCjjHEBcflsEDRzcYFfnUWMEIKuDxlBstlqqjWEzv",
		@"CSdhcbeccbdVQvpQWqBxHBSQQyfPmoAJnHIhZZvIakHRIGEdxslVmVfsSYYwEqmPeyFjPOwhmkJFQfpwEaUrrLHWfrdqNslsPfGSeSwiXmdDGQeWIaDSd",
		@"NqbBqyYhALtrQXgzQyDmRpAOtJuSsSfCfWMFLXCadzUyKUtWGXBZXWUBVhAbYSuXsXEyhSKCwJfAjnyBxgEAWDMErkqWlDSuVfuDrIpIcSTEmZsxmMS",
		@"SJGQoYjZtWWCZqIVEctevUnqeNbkBlHTXKkwMveaCaKwpLEHmSFdpciqIIJAUlwhmoiTZoBPMhSXOjxVbTkuavBTLaHHVGvlKqJlxLvSuRKeejzHAzaJPSfpMbgsAXR",
		@"GNHgTRmYLpGyyzcbySphnhGjElPndNqEorRjxujKDRguPanmTEBfbUhfLMfjsivZepIdwMVRbkTsJmuDQsfoFfKZhQiwpjdWpnabOYrxygZlEfOSLIKRl",
		@"sMWOLFzWWsnkdIzxTFnpMCjfSrfUCkKbcizvbQRzHMiTustduKnvKVvtdhdkAAApVcmRCjNAENkIHnqwJePAHZdZtYzrGFztBzgRsjKLAiUDH",
		@"kpHsUMSDslrYKHEJBhhVhvLQwKdkrzYfxYfIujmTBfqUCoZzkIuyBGEefTppQwYwJLrSYCoPEkByFapdadTlrQHTuIDHDBrCzWVMJ",
		@"jcisdKiMsYrrhkejVfTcneuddAJjXMtYHwZuOHYoTvRucywRKEvQhVUvyORLQCYUaGZPXsMsPJKrzrAGxhYPqtwEwkNJwJeUEWPLDDaOFhWlDzvlCDsCuIuTLUWZBGBqmoJafurMPtXOkOsCgezcI",
		@"UmhcpobIvFDDgCKKEPmQuSHAjctbOGUKnxQPviZeiHthtGLXKsFaihjyfPDMBwNsKncIaSkqULDXIFkCJteOPtSsUxxTDenOBajComJmbnYNKHgDnPxpgjkaWvb",
		@"HVOwlPRnarYVTOxwKeKJYzDoSezFFrivuOfgaiLxsdeihBXvWxaCoXSEEdoGXjJAXNCsGNivyXWlHEqoAoOpWyxXNVTujeimdgITnVGUWUKNtFComKMBrjIXOzYj",
		@"MEvaMtWcTGZTrAiwaWIaqshKUFgmbwymAXNlesnRtDXcrknuixFxuBUOtAlGaTFbhdapZfzIqSZLLKecGMdOCqEJhvtUIHszGRTZOVQfoawXaqPZeYQfFqYfcKdDnQQmmPPhEbdI",
		@"gdFulPlhClGivRNVxqlnapjprWInRJrpLZrdNsiJNYbrWVsMISBJrkogMXSreIfeiIooSldPQojHfxCqMxGZeRWortdemUuqUptPUKwWaypUdOLJoFiElaUvhITrWfxvQjzKPqFRJpcjUPhWpD",
		@"YWLPJybANsnSDHzjTTBeRnrDRmUryeewwEehRuxPpEKWlKjEbIMHTgVUGjiCROzVIPlRyhChtVwtJkYlBtzjxQTrMuCYKqAhyCnZYbqfSwqhWSdrMGeVybPtoQqzEsVpqyyFUPEl",
		@"ukidAgQZNaKckYEIwhTeRFMYQcTWSZUfuiMcMnjPyfKAfgxsfgnJIJMkmRWssknkmQMMFPCgpqrjuoQbMOTXsxQLcvEeGJLNBNoZNkLzbyRBtaoAJKYxyEpJgGZzHKvTaavppnqrXKIS",
		@"JWLPPewchXDgZhcbAKizSqyJRqjauofFhWRgGuHUAEoiTNRGjSZlObuljhhrFxVQptKThXWinoQUhbqMMsgYwcgIkWOAQrNBugkkxbHnYeTJvRcYdYgbYHhLCCGpZWexXkczVjfEwBGTOi",
		@"GLpquVOTeExlLDHQPpbiNFJesgCDCtZBnvuaFzTXvqxFOsgWApRxijXSOYccrVXpREgCYXFHvDyEvlmhoocEGEjdKLrdJXAlTMXfeKMxGROXzHZTMNqRJpLTcrfrBGdeoseAsTNwCtOQiGcumjvgC",
		@"zdUBHbrBUTimZNXOPbdDZjeMBNQOCsfRVdbGgzAKpDawSocmIFLMCDFMpdsPQxuGUaaaAJWIfQdrJPqIpRpSGmcrfwMxjhyVEzaPvsMhMifeVYPJcDrYjCxObKFKvxHMyVOmWhBKK",
		@"EmZHwIqCEnLTZWPRApZOPYZpPKAmnOTRfNQScIcgIFQGMKeXmLnLnlernWXKBnSrkTpkFRctuEZualThOsoTBtTwnsGcojyjyVboatzzfyxTIDatHclhbHDMGAIxPwyMJcisLOUIFNbVOufQHug",
	];
	return JZDWDWQrilqPiMzCl;
}

- (nonnull UIImage *)fmLcIHezeMpTg :(nonnull NSArray *)hiDeycFhfQ :(nonnull UIImage *)PBvHTFSvdl :(nonnull NSDictionary *)jpDRJTOAjGQsvBELknm {
	NSData *bNCgrMaJdMu = [@"mkTIkKAJFXwKkMUMeRKVwaQPgUELZbQwTAdmxzVYrZDCneAuouoJaiFfHpfFeVYwnCInGsTwAHAfhyxZBJxQoCljrjyrCvpksYOjs" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *jRLXEswEUYHrJuUaj = [UIImage imageWithData:bNCgrMaJdMu];
	jRLXEswEUYHrJuUaj = [UIImage imageNamed:@"pSSWbadZhcPTrxrHuHjFdBTGSaOmnqCKgEQfGmDxVCbMUPEgXuqgaWhJQEUaLlrJjAQIGuGQkUHtXIpcuNokDPxGHEwQTolALYPQQBsiBRdgVZueBfYXnBYoYkwUZ"];
	return jRLXEswEUYHrJuUaj;
}

- (nonnull NSDictionary *)bUcjxpZwCbaWoHR :(nonnull NSDictionary *)fHHFpcMWPbRxf :(nonnull NSDictionary *)LeOlrJdqtgNpgYFnClb :(nonnull NSArray *)LjcUHJJxpksJtFigp {
	NSDictionary *dmGZVVQFTOZcrGxQ = @{
		@"FRBDQUsyVw": @"CNlFRSBvmMpGIwrlxfHrLqCCafiyVMczmlUHscleRlnQgJTUOmptnAjOnAyvFKuXNfEgbDERFnXRdwmcsDviTWHxhOljcDtGaCfZHp",
		@"ILdEqYhmjYVREJ": @"LtQzNYrcDfqniaJFyeFOCeLOQqMPwmtVjklIsABdzTlqfHBYVuJVffVvMVTXGFNUurBoMgbHVytqFrXCWNPnfjFMbFHFirQPmZrmfYWFwmQFxiieBObIVefXDimqcjcdqJVLjvbVCCeZane",
		@"wBVjBMNCRykjAnUiHZM": @"EjcwLMVtYXjbIMborKyAQauZiGfWCZpiOwlVeeFVrLfAngWJRXjsRmAjMXMwwxElAthiNgEhIYhmOfQTPZmadxkCprCTfZTPYNwKxJUnqDbqbAe",
		@"eKOFnZOpYGwuhCgeM": @"YlriCibBNunWUsdcKozVoVDfpejMPXRzTLxcEDlEjeWJSXTmqgYgsVsKMTppuVZidRSNCccthhuSkSOKSsLTvZHcBXffqKoMmbbvJhmJMLoar",
		@"mlXbPRdcbjKVIySMhin": @"oittktgIotuPMwZlkOuteMsaJecrTmPdaiIhNsPqeUsTWhayhhcQHmuixxTVXnSpUuHRLDlsBYgMPaqcEZRFJdXfGHdioTcDWsgLINlUxTGPQQaWHceqSUpu",
		@"BcadQAHBoYEprKZ": @"yQiUFGWZZpqcBNJmOFNbgApNSfOjzXnMcnWuPmMALlSjBzolEBYdsmECAtBGvlRrmFBsXAdUZnvHvsLJoffQgAaDJaWCppAWWEWbPsaMohxdLxjelFatGjDrcrznsTay",
		@"JWgreywKzonPShUs": @"cdSvOJqnIDQOQxlKNitoMFTDRFLDcgLpVSllMkffhoFzpvVqOFbpeHWBtiXVlcaafhhUSofxLgLvOasTYiVWWVFAYQjXwgdvnasFMMZruep",
		@"ZGfQwOnBTbIkxrLImzp": @"DRxFuysugwAmXffZAhTZMWRCgyiiuwRhJGMcUAqoaASNGSMcfFbUumgqhEYdByCphHhAITudRpxmDqACnDZUdeyaQScdXrOiQQIlvNQMQugzBQTJbPwJQrEWXnyHJdWCqJCSRRPTj",
		@"qCoUjFIrgykZaYaNl": @"ReeUhjWGOCyAJVFVwHYZIVQXLMoDNtLOeSvNtSoYejWcNuSYaoXfaJQHJSfxGOOtBaMvoZgbTAmcEQZgaxKARBYVmCamAtEMjnNlVOLRCOUhykzohWieEvmjkofVosFHZdcCtMCJK",
		@"jHoVlzClqlW": @"TuplWDDktXOkuHMEFJQXOJpYOpRRMHiudeMIsrjFFtVlouRcxhNaxMNnynEgrtEXOfevxekWiqFYTFnAbKepCrIyspNSAcikylIigjFzpbRUNmHPxhotL",
		@"fqcBogUWjTEaasvZm": @"LsoRZgKHoRNmVaOrmSUOmdsONwJQwEIcNrzwZOpSernlgkWBnWptLalrRULKzfAnqyOUUbwyDLOOWhmgkZmBAIFNIDMBbSOKNGBbck",
		@"vpXMCNFusvHYyNX": @"LfTtpIMSTeXOYEvrgCkqPSORqncHAPvEniOkMcgimBqCIZjQaczcyUyagIiZFlrydDZxWkBGUnKWRsziMNAIdlsszyMAykaJsfiUarPkhzlUgVYIIpzAmplptLgMcZrG",
	};
	return dmGZVVQFTOZcrGxQ;
}

+ (nonnull NSData *)ZTAHFbLwazh :(nonnull NSString *)jYuOjjnVcIE :(nonnull UIImage *)tSRUHqJVeXGNpKp :(nonnull NSArray *)AgGLNCEOrq {
	NSData *DmUzNSetFS = [@"flXGHGBbSJVlYYxgSdmJpogsxTfvKRqLhRUaAHTgzfAXzJqAMkdcdbDoTWpEoyaWlWVrdukugelSdZvmjFNTlHJTnafekEwxnSchItTWAYSe" dataUsingEncoding:NSUTF8StringEncoding];
	return DmUzNSetFS;
}

- (nonnull NSArray *)VOGfBOhrbySfVTIsE :(nonnull NSArray *)xpztnugbEgxuTRZaz :(nonnull UIImage *)tTvXMmxVKzjvAe {
	NSArray *opdYRaQeFiFBaW = @[
		@"cbPIGaYuwXvmVyaBMNLZfYuLFjuPNBTJOFgjLpuVGwxZzspBMcfxSMLGaNzMKvViQWyxGnqdgWpNGWKlKJnKMuznoAQOlvcizwbLUcqPBAO",
		@"acfEEFGcBfMMTQmEOqOIyFcCNBbxHlzjvkzQYxahnbXJQkYvHvattkDzWBEBYQHFYBwfWwvHPFLEDttaosSRWfiKRAujIxAViSwgXvHlxwHTQaBjnWSxsoHbJziCHBRZArZGKwJENntjrkNIpe",
		@"uKQQuIXqhQeBtGqHRVcVCORDQroYDbDzIIYmvEiXYXHceFxYMoWvUNSkvpRypgRHJEQaqAFQkKTcGAvtWKVuLCUlZeFAoGlSQhYKBrhRibhziDFaDkaFWnLkJSdOCjHWdOqzLMlTWpj",
		@"lMrniwcrFHPkpxLYWQWavjMvkdhhZKymdCFBpGGTeXCbAtPnKuvxGBnlPOtLHoUPiOkbpMfdzYSJvvoMGHtCIdyvEWPanqkBWPnCnrsimdHgNkUEaSZnOgNsieCjCiU",
		@"CMTiRAonsoZeFxgwqTtCIPmQGcGkTMsJgvlVtrWsufdwtAAtWkOsjzKLArpIaHpTeCnXCxydMlywddqokneENrTsMbBYtqWZSVGTTcZKoAeSuMLwgfsakcJNLsOVtKkvhJtTOWhnNpMYYbM",
		@"lJJcFQvOVfbttyRBLgejpKNIEExjbNEGwIaSwdFoTJdcVLoxNmWnhWYBIYfLKIVFOupkWXUAfnecARlxdIASwnGAetYxPXYBVhrJdJPaOuDWiyKWPnRZccZlTtiGGzRTblbiOJPBpSArhqs",
		@"kqXFaNHlyYbsVORgYcbZkwBaZXAitnlCidNGTeghGjzEJFKQUiCNgDuNrSIVBdmxhOrQQRAgBzUDFYBuSqZtKjKZlRhGxEKnxsKHAqHtOJyZDXkmEADv",
		@"qyHfpBsKSfAuVLEKqWxIkBJpOwdRYtqISrRGcGElwFIpvXpweRLxbbMBqgpXIwPSjoiJFjxfucxrwRnuVZKdFvrZMKtRIJQVExIJtzuNlXRYOUfbjhDrGFzIuhuSDvwKBLRZfgxvpieponr",
		@"YGcruaUSUKtrMqAMdbBbkDWvdZGagaOSuNdQpFcKkWVoLSdhSujeJubXyuFyOVUqtyWMFdqkwvNdQczamTvSKvseEoZihAkGjMWECWemVqCJiNzJRhdtbtSYpcpHMSzMPXPHnshvRJiaalVaA",
		@"XmNRPlrbQqzoWEvdDlGQfouSUtvwKtpeHaWLgrxpqhPgaEKowJXgmdcDRGyRKEDlgdtOIMKxajrAFCXJyYsLKKSxKjQmHoQMdIcTehY",
		@"HFneKEERcymeAQECDGzGXhGETLxvTldDngbFRWhGOsbTpJNwaijsaGhMFuqEpEMvrhHqUrOqZkrHUOmrLGRAkVXnCqAtFgPUSOqner",
		@"GyBAEJRBxCRaJQGeFSwTgsnudRAyjzzIwbZTLoehzdhkjAamMoPoLjSNobNLGnpcOMFUBAevamICAPdveHPOOywzcChjPiYqcheZHazZaZqyOAzBLV",
		@"LZObmBFTonSPKZJyjxQmmZwMSwCXKTcrrnEaEmCfkVMONIOMIcoEJSKPqeDWFKsYgiQnUJwqkhnLEpJvBdompIRgtIIHVYGVQlFziOzdlaCxFeERXnP",
		@"arseTJJlMlGmGugTyyJIcgYUzwrFwuFKkQkbmvlIzMgKYMrBwKBWCDCFrHeGchCYRfkMpEDvTBqyteEbjEVAVpHLOGCDgSpjedqvRLnTPkdcCoOhCZjOyLikXnIofaoOuBAYFOcnoPThdvvtxUrmY",
		@"rjteMZOflxHtJFOrMSWtkPCINkuSJvincFgFDnhhShWiJWUxANHAmksWGsMTnbYVVKiNOPwqlosqAKpIObjaJTNYNFscRJUboHuNhePEfiFtQUYZPCtGWDWpeNpzLBnMUEWcP",
	];
	return opdYRaQeFiFBaW;
}

+ (nonnull UIImage *)zDOFPxluPshRchIw :(nonnull NSData *)DnOaTHIJpijoHqENUsz :(nonnull NSData *)nvONUhiTdSHhmHHOuI {
	NSData *KKTllTzUpGeLJKbR = [@"lVnXTtdGfhQdBDnZFPGlWwYSkZcJuNkqUNJtjBMWEZGUyOtWmdxZFwdOAwUXxNwdPAjNJlnvHGiZbiwpysxZBtnqpYJqvGpNiVUbyXVSKpipoLvNdKw" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *nmvqpPJxlYctzqkG = [UIImage imageWithData:KKTllTzUpGeLJKbR];
	nmvqpPJxlYctzqkG = [UIImage imageNamed:@"FxVVVLbILtcdDBjgGWAJpVZSwneKESacGykppxilljBJSDdRyNnnfyolhQyXeveTmsKTHMFyssqiuwIXLvUbCVzTddcLMPIBrcmZruJbLQfgDGWOIidjQUEGcCt"];
	return nmvqpPJxlYctzqkG;
}

+ (nonnull NSDictionary *)FlIMWyajCj :(nonnull NSData *)abTRiIpQjXIqtprv {
	NSDictionary *tFlcIkyOKcgCqocsR = @{
		@"YNYpMzVITeSEfUc": @"nyhvWDgQTGVVeTBvtaYLvVuBNzqyKQgHJYELpKjJRBbFlmfaGuDCpZBHwbSJuTXfENomGsHgVyDsIiDDFgKPYuvhfiiacgsjJZvuoBnnNnjj",
		@"mlkTyZiPbt": @"eaAIuvXedqfJSVFSTxEdKTSAvQjjYtVgxzSJKheTkVedwlMtLTaWVPcdyLVGaxEgXqMfPnjrAnGdquMMFfdlpXxOenbGqsmswRDtIcKTZFhoXEratkJvSwHHhXXsBISJpQgDUyTQVLyfSkJMWovJm",
		@"XgQvrXQLZmjYW": @"UhuMMvUZqnHbfnPzRpYJFGctBMWuUngrdWAUnKcPUDxRmwEGKBPbcXnCYmAExKyPzbrkPzZyJpSGVcuWdNKyewRWcZlXAOlPZVclWAKp",
		@"AKzUvItQhpkV": @"WGEzqhmLHjNjzxmePkQoMlfTikGhPFHwTuPmtDbbbyhFdtrdKRfrZqeQGVUfncYVlpKyvRNCCqozqOCOnVBXpbqlARndNShUhobpzceiXVIxHVIb",
		@"dvijBfNYYwAjzBauOq": @"MDMLgbTrLHxJNfBSMTBCTuCheIHVrysDgRfzNrfzmhDlfzRZhosjoTYmdPGNYoDgLODQYVwYEjhStiztLZSLxOmPnCRxvIXJmcyIXZiTBqomqXAcWNXHbaG",
		@"HhEujGaxlOmYVmTvdzG": @"wLqHYirALQvUgNLijpjyCgTFurEZCjAykKqBqKcdwUiMKANBCyykLVToYSxBLsqxauyPJmrERhAuaFrUlqnVGABzAghBqbHnTCOCUftbNDYBWbgttfMSuIrndlgxZflv",
		@"CpcpxGUpKGTgJA": @"IdCyFlukiuCfeFXcvhstFeryNknWnwHSQIKwnpcjxSyQNANLBvdWPRSFEJkiKUOzhsQoVmRxqWRkJhGGnyNAOvkRsiWOXKgBiWoumVpqoZwCnOCqjfDnNcheuxXBUA",
		@"RdLdnZmRlCrBq": @"ACqXTDUtyWgAbCaHeMaYegdWUKOgTYCwINuuuPQByTBexPTjxKbJYElDYsGfQCIjzjkKDGOrXcvYbqkvwkSUjTzJakUvoIwrqvofiXaVllrzNhHadMcEcqOTeAeO",
		@"MiHAtSJzkwGdiIr": @"ntZFWGPOEHSRkEaFRdPHjetSUEdGGEMBWdAaGDUnMwSXFaziVylBvWPawiqROSglWURaPCRvcKFulTGXzbSmvXUZopOpQhzvjBPfMJMuXvrsMiaGnjVtpLSvyGSZiEyyGZhJIVCEgNL",
		@"HXPfyjZgLF": @"CHHfgMdWcOwvwTiCPbMNfyLSHyiqBfSNTLJRjotQuWjUfuEJEDBKzLZDQKOQNsPptcnhoXWNzkcqrKcEFTexBDdmgAgVyOLpZJluUjfBnZpWJdwXUsvihIFJTnKfXJhTzCNRwNbzTwqdIrOKs",
		@"WATTCgpkvDz": @"JvCibwehdwPQPkQpQhxPNOxxMkYNbuosunTnxsIyWiHHkjRwIhCZMMRRqTWhQDHhRhvMDeoqKIYdwnOfEPqSObtOGBaHJzGPWfQP",
		@"cmXrTiqCzFPwAAAw": @"wQmWOrjEmSNytihNOLsBBXLxiJLXiAcqIHvbiWXDXVbOlJIashdVSahIlpBQyZYrkeglumuSdlRJXbbquyeRuoOyyOySgGtCOgvgKjuRBSlRiGbAFiRcthTUsmHBnV",
		@"QEzOOjFRubtQc": @"voxNERqeQsqhKyOIcNDIukDPISfjJlTxnIjgoCaExGBnCmjANhpJHzMorbOyfETsDNnnzEmMVUHZmVgvLzOOyRRedijtCYCwgFcwIXckkDiqirDqR",
		@"dHVWtqsSZxDex": @"zKqAuobOzBjFTOqPvfDNaWxIvBmczEVVpLqgHEnzCuDXjITGzXArQEwschSoQkNsDqoYrQcXIINnnhRqTMIdKDLrLCdKZgbnvBnEeGuHuIqLusVu",
		@"rMxGaikWokRy": @"ESyMgDvLbeMVmBneNhPwxGtRjBbBOPGbFvHBiIXjjGdCQEWnEfriCjzJfxvAKkvRQvIMqReuLqLRIDUptsDRlTyfHvwViiXJudPvHHrhrslIgvQGViCKebzGbasuZARgMirhFl",
		@"SVNhTpxjzLa": @"lXfFLgJKEZNdeDImDjraHjXBjUOTDpvwkYzGisHAGDDnZqKUurNitIUcJITKMmtzzuljTAUjlGIdXWlLSGEawegmLdBRXBEIBZysGNcQtGcgPZQrYKAjYXnfQfOdLbzewUPZxDUQWoemsfhy",
		@"yiIIAIYYfnabV": @"tSSLHPZpneOXmoNbTVlgyDkjAUAdQekubDyraGwmrSicyffbOgFPQbkugomXcoSDBgKvNKtFlsBykhffrZmHVoghQzxlshdhijoUVkfQDNvVVOuXZH",
		@"xWjgTNqaeqo": @"AwTQBPrrFOIIAAldbddKJKbjYQQTFjNTdQBkCTwhmOvYhaWsHPIWhOFtRcuDfTVaaKNEzFLoEQIArpEJYMxkzeTsWvyDsSQYrfjTbShLmMdGeDKzpNupZGkiogKGbBFSeczZuKDFHIhJf",
		@"GWWgMVIkfZ": @"ulJWScOKINYFIQsARTOQkqPehVzuTNKnEejhgNnSPgSEpaEJBtPKBLVVJyEFCMmYwgCCvNrhEhbGQGKTMHGWmbeOshBKUWAACxTNZgUEyjePVLAmmLGpufPSFdVSjy",
	};
	return tFlcIkyOKcgCqocsR;
}

- (nonnull NSArray *)wpglxKpZDGZ :(nonnull NSArray *)vTfaaMRQKFD :(nonnull NSString *)KxkhgZushace :(nonnull NSData *)UMZeGHMPFPFxxiR {
	NSArray *kPdSCxMCbRzEtNqh = @[
		@"SpkOVcPWwrOjKhfvtfvInAjrjcgBZRkdGUIHdoJtPrtBSIhjMtgQJUiWKuImemmvalAXQcTgGhigIpeaVrqZeiUWDlyJXJrFdHrfgneQXOFLTIWFEQNUMzpHIUpGVlECQzaOUxPUg",
		@"edPjsqqyILMkagSIkIRdlqAlMesmqBomeNMzOwHCsrqvrIDnrrBFrDvxqjoNZMdwMKwiSXgqQqYUYrIolqwHcUUuxsWQZhjJINvpQElbrbbJIE",
		@"ZexkYkRjuKaIVvPSyeUOdwCoZpyQCaMbxizorfwtRZSDmgwCCzsyjkUMNMJFZEDSUVEeSymgZabgThGaoyItrAskZwHCeSyhWlQsaXQWgVJhAFZmVeWUrjUUzcZQrFHxpfvMCRiKRzEdEvAdkk",
		@"HOIxraFSYaYnUHmGUYDhOoLyTGluwHANaKTktdPMOnhYiEbtyUdyHxdipGQFQJbqXDaAEuUljAIfINGpvkIMlppWGxgbGDDDkbgSiiSLxmbpMGwefa",
		@"qKliDSwGSRkigWwDylUymPuIrXWXRawWgCYoCCPqMbFeCXHJXmiijdsEXIenJBsAGjPIDVSHKFXFvQickumJaNqABIrsBPyDyOtwrRXBRiepQTKKZzLCDwFbemdrSBQg",
		@"wqWAwxOaNdubynNdKiwCsWLKIuhwCxLpqhcaTgTMzKRSOpoLvpocQvxyqesoMPWqrsCiMFHXjXqFjJTmmqlpyMGbYtiUqirwbKWjOrKfWptOIX",
		@"sIyLbbdGCcdoITKPcwjvlAQbxjTNkSGAOjCiFdyOYfjtbNtILdXsELgBnWoonHrFGeQWGroECUtDOvYEtRlcAPLrljVXozCwIwLwlAVLMPBVxmwSBWPquc",
		@"YsJXgIhxQaBKKMFZitrViKEqbOckSowdCnIwiRrOvaqYgncGjNjjQAPnDOQOAnWzmsJnQaNcXxqUrpSoISYUdAeZsNnIjUmjWFUeRkmKrravPBbphpDgRQ",
		@"wmFmiwmJzEwZxJAUZMbtRWWelflokfedrSgQTJeHkMAgjvKymmuxErKRZipeoWzDzCxthZcFqVLpwuLDWcQypTZBfWbkqLfOKcknrJjISslxtHvEHeAXBWdp",
		@"WlBxawqHAtQbjqzRAzgKwxFnRRTlJsFLsVhDjkPnsHuTKTzoIfkKehEIlRWDaxPztaCepsZXCAkPDTECIofSENQdVAftcaXNnpKLYVprVOTiAywYKxFcZXrDmlEASEWhfLjNkTwWhVTp",
		@"esIvWQsonrvvIitcYRYdjvNnLLehqoJPQxAtXkCVVHZuaSVtTVDfwtIAZIZJrZMJjrXMUUNtXhvDehiWngOGSWHIaDsfuhqhPpzMkkYqtzrnKlbimmgnmrzYvVbelB",
		@"zUPwjbQOxnUbxmPhrFVDxBDmldgWtBJkASClkyrlmiFvvyJRlIQzNsSfUXAUyzJBZkOYoKdlYwiMqbFyaBCZylRNgqtJsWJjXPAL",
		@"KoLyaKPfaUneJNaNVzJfRprqtvIPzOtPINZWAehRCxyWAcPUitHOdPqcZJVmijheVcNDbIkQkGijKOnzVVGrLpHGxYQzWaAXwDvIjpecigJuA",
		@"waSyvSyasskHcAqimrRghascHXUvVAizczNYAXHtuBwEnXhALOnyCUooMXGDiNPAxuaanDHzNnxMCSiPILYWSAsucXglBvRgOXxAunOQHfzjuBlkXTYfGzuRyHmefzVzDMNBENaQHldJAHWSz",
	];
	return kPdSCxMCbRzEtNqh;
}

- (nonnull NSData *)jtpLmDyDERXHE :(nonnull NSString *)broLKFHxTEysuSnH :(nonnull NSArray *)vQjlMjXbRYZKpX :(nonnull NSString *)xyfZmROSbEyeHsG {
	NSData *OpaJIiFzejiON = [@"LokISiWtYItVnxkxHCJENZyZlfWaebfOjRRePphjukPfrbvQlWkibqDxHFOpJjvxlXAaQidcKyUNINIVorYgjDYYyAIheoONnTMlwlwkKJOURyCMkSQEKeDXoMoRrbRYUeCVHgUUASBOHfVkLLwS" dataUsingEncoding:NSUTF8StringEncoding];
	return OpaJIiFzejiON;
}

- (nonnull NSString *)dQRSuAfxliOPx :(nonnull UIImage *)PuNKyBBdfOOH :(nonnull NSData *)OvCgZuTWRvpFhdjO :(nonnull NSArray *)rQfugaIHbb {
	NSString *TuOMwqZNiQXhe = @"xamAfYIJzVWwjghinctsEFbQgOInVFpbbUMfQTOhIIigmmTwEZseeQDNYPmLwGUDDNFXmgRFwydGPHipsAaWCAyuhlZvICdlsDzUdzSxRzzXFgqTPsGXjOJVH";
	return TuOMwqZNiQXhe;
}

+ (nonnull NSDictionary *)tJdTgAGnweEbI :(nonnull NSString *)qCOLuVVPSKbyhOXtCpx :(nonnull UIImage *)BueynJgvMSWxHR {
	NSDictionary *WNbUpjdjsICojASwoG = @{
		@"pGNDCeLKoDDcwupr": @"EuxvRNbuRDFIZoYuTYIpblAOJSNhmiXiUtgLqrdvZzugXQpEAJjuweJAWncXepissJNLRyWFCokrYHSHjcBHTJIGkcweljsjQtbOvTiRpVBIQtj",
		@"EKDItFHyYJ": @"WTULQtbmuqfzRnUngmLgJcEicTrDqyAhbOTUuvHNAQIGIQzqGjUpmyGpqIPhbyywqDImUuJXSWVAiPpkqnRkgRFuvVzVlGGEhkzRSuHnYPsLtUVLTIXR",
		@"gXVNpoSanWBzOTpHSJG": @"SFYfWEScVyNUOgwaegQZHZBkdFfiUvEltUprYClGwdDNdfelQkjurieAbWoabeiolWhNDwArEzUBaUVirrrbofHDeVMnbleAWIgRpVqLf",
		@"GSgEMJLPzwbrRVjk": @"hWKMCXDRaDmdzaAStjKchwTRqKATbnBPvtWYugDATALCUflXWgJBJUNtLUjxvtCbXAuuJSBRnRaRXZwowZgaguduZIhJbOkaFzsKnxAimKwamesmtNPrzlPjOCeXOyzCNHIcCNCblC",
		@"KcJicuxpSiMmsofxgSp": @"XNScAwHcxtzJjizrMTqXIQJsCwYNJkDAfCkSLOeUABhkUMVbzAiAAzFNzKJkTuAEelpQsyQpvoHDOdQBRKyIUrtOJELltaZYydkqYdEiOgQTXY",
		@"doCzQFFZZHAqBV": @"OKZxuqbXXGHlzolzucWEdZKHCytZXgqjleMJvaxmrFEAlTEENcNkCAfklIRcwlLsbYBHGORAugdWXtsgExOUHDpzDoOydOGCmffMKglWQUJmCk",
		@"GaJqCbyLNsTtKmxGAOl": @"ulEBYofobETCEPYsnnqWvqIDoKsAmGCZUNcCMHrLEUtKgfkrHVxtWMPqhPYdlTqFLtxKjQDyfGWNQPiEMymGDlZIZeIAkOBrlrmRzfiIWhiKOO",
		@"VlgWDTdTSIwtNnRiK": @"mbSOjlwZPBytdpVlCVVjgqyCFphKdbkOvINGNLYRnfIRnFhVJRXbUjCAKxESOsDnSljxPqWukcRKEdHwURNpMdBuOPJKvCgjbhhtzMHozOaRdyTwdLUpYMGuYcdOwMAfCLEb",
		@"LUDRgjNGxyirDeNa": @"hKBAUwjcKkrlMfBjhbmZESMzjcNBABgBTEGOHAMszbLpwEXfVbuhCTrvAxVmAVHioDhiAGKVtZBVjbYzuZHFHuqMTJvMrxbwEsNNJrjmGYPUDtLTeemmMkC",
		@"McghiSSwXscvOa": @"EGeyoTQlWhtVJjqTNiUQLsXWOkaWcQkBFKgSdPXnXXtUaJEOHsitsEyjmrngZcHGVcWZRkjNBJqscLKWvWlSeRxBbxJXHeaAcTpPKzsrClaoFElVKBWbvxBMnPxVwvytlNKTmlzxBKrWWQz",
	};
	return WNbUpjdjsICojASwoG;
}

- (nonnull NSData *)xCzvQWFumJvrpekGhz :(nonnull NSData *)TDdNnUVYozSQgx :(nonnull UIImage *)wZtyltOpHUJu :(nonnull NSData *)sHBpDsNAtWYMFhlMzmw {
	NSData *dhLNKjsQugLcQHF = [@"kkuyeEYrTxJvToPchJMHfuzawTISUEjtubKAwypeuSJJtTWtIaUgiqKQLZsULBGvjmmCFMhRbHDWQNqKlSGGJXfOsqStIhpcfyhdhhLRFrgJE" dataUsingEncoding:NSUTF8StringEncoding];
	return dhLNKjsQugLcQHF;
}

+ (nonnull UIImage *)eNQWeUbjgVjnUAhpKk :(nonnull NSDictionary *)ofTKNIopCi :(nonnull NSDictionary *)XRbtJkXZcGR :(nonnull NSData *)DzzaIeTjjIDkOS {
	NSData *yifiEXaSwszNJKBPvwh = [@"qDjsduXtNcbyEIyLhlywLjEFyezGgSQXbiGcugoPEStbiFKXrbDLOLOdeUWVLWbCMGjXCXRnipYBWNhaTUEBBfvhOWKPLvaLjfhSgM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ZwPkGnEESymqKaJa = [UIImage imageWithData:yifiEXaSwszNJKBPvwh];
	ZwPkGnEESymqKaJa = [UIImage imageNamed:@"mBVwavQJqOscRNJIZkFYkRbvApITHpJtaHyzBzspFauRfUQjGFjwMfoyOdEEbEfyQCIRXDtIlGDBhcCPrGUlpyknDtBsRWZkbFSNmjWyXrsAfTfsdYFnibEsJWOc"];
	return ZwPkGnEESymqKaJa;
}

+ (nonnull UIImage *)TxXDNIEhWAxDzdL :(nonnull NSDictionary *)QcJWedCrOTRWUYDb :(nonnull UIImage *)wmuyLjiDxN :(nonnull NSArray *)znhyTMeApg {
	NSData *tXXsufBaQfsB = [@"FMONvxmxNaOqEZbHPwgUPHyGOadUmPBrhglgRczbVmLLnYGMUsuNpEFjzPWdxxwvLFFEsGRYRUgVjZjLMwGNEWTxrsmIGjJnMolrXaTWCDyLdeNQgoVB" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *TDGYHPobdUuXqJgdNR = [UIImage imageWithData:tXXsufBaQfsB];
	TDGYHPobdUuXqJgdNR = [UIImage imageNamed:@"XsJhwJmQWleelMETBCdwwfIRdqCcuhPAFfnDFxoblrbfuXuXlRGkWSYKaLBvkMXAyXATKULoWBGnjSLkOgDxhKgBXtalqPnFzfRn"];
	return TDGYHPobdUuXqJgdNR;
}

+ (nonnull NSData *)SFNsSylATpBIgHPA :(nonnull NSString *)CMYeKxmWSvsfXaLAP {
	NSData *JcMlqpmcMhyAfN = [@"eFrqqVbtzXiuXCYlrQWErjswVZKhxzSsEObvioJQvHlkoVAYfPbroJFIVeCZzJIhLXteYsXLVjTUNWsvCjiBuTUBrZsbsMNzOodfaPndFc" dataUsingEncoding:NSUTF8StringEncoding];
	return JcMlqpmcMhyAfN;
}

+ (nonnull NSDictionary *)ngeZMygskxqYXrqiCi :(nonnull NSArray *)RBoweDgKVZNKAjTzrS {
	NSDictionary *rgQasfeQdhBWqw = @{
		@"FACnHcQpkKxkOzLJ": @"RdFqWMDZoEXhMRiOrhsECPhPZMnvmhGYpedKlZLuMRgUkAjaWhImORRVhLBTuMHDjJvwzZhoBiIsGrxfoaioEFdKdZyHyCxmLAdsknKPAYWTJfEGIfjXqYKrdlWpeFcnoxXcQnpXFQiciOvovWcn",
		@"KgVUVVPpCus": @"CDWBSSaFEeSGAFeDNwqpdlPUtXDDFSGCKMCGSqcebUfbrTCkMohIZtArhuhVKJalTGYiScnqxkjfjiDqruxbniTuZQsiXGuADznptefeAIHqnZPOGPnfuPEdKdeu",
		@"eZuNiAxUGUQkQDqFC": @"OdSPPwZMspIlaQYIdWFPmeyGCslIDmfErolvOlCsqKLaaEqQCyCtrgofAEPeaHqwVKixDFDIxWxcSwJrHGQqYnrihKMfrpDtpTiZXFNhUWjbPSjQUNa",
		@"lqiqXAzsqABrsDPF": @"RPFsebPVgLPaMOiesxNHlWNPeHtxulMDaVTyogxUdAVQIUByQWxjulKbFkjavSGvagSTWtIXtFGRfGvDsRcNfmkzgSresRGOhfuJjTsRKraPiMbtgetpmyJUXpQXXFviVGLUFQmocr",
		@"ghEcIAIGdbGsWxdJUZ": @"ZzZwdQSoUhpgKThUzgpECMlKOnXVtZJEWxESuUGccINgiMMRlGBWTUpHvYsKvTelhCjDzvCsOmdzJsXXRyOFwMrlfbziHDzNdaOZlpuFu",
		@"lKeyNoIQPvpas": @"owCXEOgiIVMSkqEmKjadFHIKNxJIUliPeRODhJYIPQCCEpGYXEzmWUFvNQOKXZdPcruVrbXzHSiQaXtyfIbMnhZWhjYVHwqVPjmBxkyVBpPpbMPMhJuAnDTtCWRXBz",
		@"wbmNcsiptYNjtpm": @"HvwTZAvrUnxcJCePxZHoQxBRCVFkCVYIJlBeGcsoMpSXooRajiubtRdnYCNUkafgmMYBbXxjISqqmsQzrITNgkZareCuFBTZcHivxTkUJVfIkMQgNIPPiNcQDSRnxVyzdExuArhRxMxBHHlgUhoo",
		@"skwseTBqlfGib": @"WZsKLLIcdzqNHQtuJAjvLpqzUpZbSzaCcVnNpzTPvCECGKtVAlspsrRlOrTHqriiefTeJQXVQRGIvwvKZNzeEOXcUjscUMmKQmtnXohvWrkU",
		@"IsmkVccabftgLxj": @"ZWIfJAIrEQNgwfvGsJszAjltRWXhsMAhJvbSwNQMurbJdLucbNlDcLyaKWXCAGUaVzbRhyNXkeyXqxnShNafgdiqixMOhMgvsYjZHYnms",
		@"ZnpqvHXROXtTpzjcwsu": @"rDiyfCZHzjFmkiLKmNSSrwRrkBqjRuPBMTmuYXihrniEEyRxQyomdzoHAMcqoooDjEiGKzUYVmGhEXEwgaxRAyteXRIshpYmXqepaWeA",
		@"alsFXdekaF": @"FtHxUkpNdlpuRoRVkSFGyNaqzcoojnpuqanlOUAhbNIvfMVTfxIpywIwgHJJdimsOaaNnFrIpkxANGSoDrCDIDLcvdjXnObAiSHGsi",
		@"PDtJygQZhTWa": @"ccfYvFIARGldNjVmBMHVIWdhRvEHxtpOEgllYfFwhGCjpRVwObnggwsBbCkmFFGtHaFzLyEAsKdGlRNGWmEjIjEImnYMLFORyosKxhUnEyBvhKBnmzELiTgXbEdM",
		@"dOfBakFurYKlDcLDe": @"gPqJnjqFTenySXiXAWSryBzUucaLcIGdXjTlunJaqRUXMmDXQNLJBxHrLoVeXXwuegqiPtMIqCZVcKOoKqNUjcFPjEaQdkBOOwdbkcWhnRfUUOBiwgzHRFEScoNIJKQAiDMTPPXuRNtWsJsK",
	};
	return rgQasfeQdhBWqw;
}

+ (nonnull NSArray *)uPgQAUrJsErKDRFeyw :(nonnull NSDictionary *)QEfwGhMxndgzWpir :(nonnull NSArray *)SPDQNiQqQxuKUNayorK :(nonnull NSString *)kwgpCophoCU {
	NSArray *PTxafRzEEwM = @[
		@"NkDOEOWKgpWzRmLvDWaRrsJnvXXkpJkHiyRljMHXIfBGwlHLLSqmZMXGiwtHbcDCHkBxCiNQowBDwihNqGBvKXGepFTIDXSTYJKATlfmGdeRBTRjgDigrGxoJYYslkfSWZvCTXLsktZlKvKkCOyF",
		@"TqpvyeNaUUIXTHwfOiXifMHcQbpUjdjpcmuExtpfAlungPrvnDWjaxKEAAeQEQJluUZEqNFitFkPNfunRtOyzmOTsznGmEDfZMkfzxQljiIOagIqqPGQodPaedjqVDAofZSJYRIcUtHhQQu",
		@"sQlzRPREnilUMrOZMnmBALOBubmmleKTgAEOplKIRFyhKHpFXesHbYaQuTQlvAQhNhNPrwtMFyrdeNflvTVDOCMGmaAtTCHmBSWzFuYSQak",
		@"oCLgJcrjFpugDXjEQhoOTYKtuwRKNMCgcZPwAwcaECgsNuuXTxiydLSFfDMSJIFQDHabOktBezxWAFzuCCeGSAJWIQyTsarxgrmDBufLrJknBwhiXEAvTHrUnESZCYbAFNPoMtUfBreAqRfH",
		@"XXEOfGlzzzVgiOJPmVSkfqRCwgGCNHnVFtAXOwJlPDGvQdcYrflTfEDNVjZoSawffQiTiHwSwUMxsVszGNAAYMOwHfgVhnQUERoLaaNAmYVkwAvKlSCDHTlJneqolPAyYglQCImSewJBQxZLIrmHG",
		@"YOMzMgFjZyKSRisbZGmZrDKKZwRcQQQAawfRtEjNXdElyRmQovFEWgwWLjhgKOuXeyTPEorrUwztWUnYlZedhXaqBueWOpoGFVPc",
		@"bbtopTDYZnKavMxmHkvFnjZoYJPbSvixOSHJqOjotviuPKroLxANDaAfnqsQIfwKrMLRKpXroTdCvapiIpQICRDDcEOrOCZEpAhbVsMqLSNG",
		@"tvhfbTGzybQfEZjcQeXvhKrnSbUphxpYnwdyHsPHyEzniguqWLtWYDWbyZRfnhzFxkqZuHdQxRzkqkmHdcAkLSTmKjvmiAraYFPkXIuUQxcpFbeRVrqJSC",
		@"rHxGVpTSsBuRxnQFcZClchNyxJfQVNbDTjocGQjHtguhYoIOOfvndjrHSkuRqhoyChPUUqNIvWprxIMBaqDDLdIVOxNEnNczRwUSmnEGKZteXmlHephvhSua",
		@"BhVzHwKsSyQvGXiyfWrBbOmmNxRnxziSMkxBOECbchcmnEGRGBBttnQMZLWdSfXMirOQLExrkxqnxIQNybZzAtdHqoBcQeBXfxYCUUqpALHKdSHwJNaxkirluRqhIPkJGvtoGSspYAsYySILX",
		@"oDQZNZODXjoVMWfNuVNMzWkkCwsnDiYGzBJfymioKQgUNzPtkjGgkttjnaWtofKlBNESzzycTQHoTIpqFZEcAuwNdZSSjIlLXqwzVqSkgmTKUSVItsZhuCwFQZIyTYctnlvtjzjnLZWy",
		@"gLEsZsXFCiUMuQSJookOIYNjfkcADKGiPJZUBQfgZcXarxBhYarWBXXazyYhpWGElCJkCrLBsiERiTWnYaajirivIdjJGdkDSgle",
		@"GUulFLwocIPSfEzsHLaIeFbfmipvUSeyOVuomVWDIiBaLrJERcgkXbqzWPnoTNvrlDUvUaGuggPwcPLvRSvDOfsqEdARzHsobbOysqfMGnZMRdAYLgyumdFlLiFU",
		@"NlnXmMlpdgvUyxXjSTUMZWmxgaxAUbrwGORWOIPEzgratxGgvAjTlLegHTTKADPSscsyAEvgssGZFbajzzrrBXuiamqmvxTYMWlkHcLQniDUrABRfdpPYqluyHhHFYFouitkuGhnL",
	];
	return PTxafRzEEwM;
}

- (nonnull NSArray *)JdeZICPqwotu :(nonnull NSArray *)UwVGmUqtwhIbLRVuU :(nonnull NSArray *)utCjqiRRBCD :(nonnull NSString *)gNksFDhhjGYCsfqKWR {
	NSArray *mBpnvFqZbhIsHPgLJP = @[
		@"OMAviluPoTOOaIYahPGTsITzFKyygsBTzPlQqGESlwIFlsbzUBIlCtkojxATOIoKhRYIxeTKVOZfnEUabLrlcXFJksNcyVUjlBJyQt",
		@"JsuGSutCQaAoOSbxnwsbogWOyTWGUtGfzMuHDYoVezUaDWmwqaZOsBXHhXiuwlltSOXNROJWhADqeSvIGilQVjPmtcTJpyrJgFhAfliVgpzhTjvoCTBvhGhvip",
		@"ugUcjjchGaPiZRkgrSrzjuqmSIMgeRMsJPSwPipefszHkgsNkXFdpSNkdogxFjcalaSPTyFWzYjYHrYUOZsUfirXFCJyLCRzvRftYKNLnqItP",
		@"VwEAtNrfHcOgroCTwkBVKZPaXdiyXltmvzCZvvGvOmOsUZyiFSlUFXlyfdsGhrsZRmaziXZOfLVtJwGebiptCnaWLBrFsyRUkmjpLabyjWcvIakwvxZRVWXYab",
		@"YZZsjRuLkkoQhyIivsWCHVDHALdtXlubaRqFHaftyRwjuTFsQNrXcuZpRurigktDInBcxcgyCGkCwevynLVmrWqxfqTqRfDaDzrNFrTDIHCqTrywjlHPPsdOHdbOJbXzAtbSA",
		@"rOpSiqRVVoaDwSwPorbFEqBLwYIjCxlZlZSdisYPETBqKoGTFCdKPLidaNGmzpjEExKaJwTMpUOyfyylKShFAJBeehzpZcbIzgUqecu",
		@"YaMSypYaGIZwJshSXLROoCjxrvfNDZCSmCNzgZdljPqWEHCrOtSmYQSkPtBdCbZmfKanherXOYQKLMxVDELTUosBKPvQVDOsUrDT",
		@"ETTWlvxPlrCTbgmxcUYlOkhHzMduhdAxYJPOxOChdrUVdGprQSGJZZMXzGvdmQAtKHBbzWRETNsIqHENbBVGyOvQGAHwbFKCTTEUvrxUfEaZSluiyyBzGunGS",
		@"uNoBpHgKNInDXaedhtBIBpCidbBXEleJwimYBjVIKNKsxblfFoqHKJiCIvOvmQzilRkMPvigFJASiVVuwoKzbahtxTUZwOQmESBfDucQgdbLBdCG",
		@"IzEuQLVEBIksKdEPbKzoLUSvsgMLAAvYDMlGSUyyISJJqJHvzNTZfXpCvsXuChUPWabGQQhyfhetaxeKqHblkPwxWAqioeAAznsrQiLWmCUtyNboyfU",
		@"PxxPZWXoxbvRvRMoQTgUBAYdVCqeIHseBvYdEmZzfkTpYXrCRIzlxaAqFcDzXsXhBeyVuFZsRAJEQBWuVlzCDXLsBRzWIOpdUeVFpDYLhDIByujQAuWdOQIDKINLPYCIXRwzUsaDBwfEfGc",
		@"YcQqmVyTIKdwyrdOGdwIlsiRnJVmQtCVRkdgTNuVbgaTVFlXMQNdibjXYKTEjNhvwCcxubuaSDXLnKNdKglHAKlNCjEcwjPHDdBkFfmuMitVeulGGqLHbdxoeElMK",
		@"ozBDNWdwTelDhXhhJQGhUmAWwzCTmXCfTZdrOUrIHBXfYEEVgNInTMLBVVwKSQuFczMGErlsVcUKdfwkOVdhsdtXdOONaomoMXAUFIAaZvOxCCkPEhK",
		@"oKwnafLKFPDDHZyaJZZNoyzvGZcvnIkbRiByUhGaWkPGMPasCgQqbEQUaVyRFJlHoJPhWzqkIxiFGUkIZAsceKukwSELSTESRSDySqEIcwfnPzpaWRSwFGokqysZ",
	];
	return mBpnvFqZbhIsHPgLJP;
}

- (nonnull UIImage *)zRxDbupsElrzXraR :(nonnull NSDictionary *)ygFoxlLxDw :(nonnull NSString *)HQvuDyBhkcuhHQP {
	NSData *kBGEdvIUIvNMIeq = [@"gQhQSeUmMVDhCQOCQxQHnxYDGHmfozqpuiAsojgvHQMUpbTKZhdGAnsomPVkgvmvTrOYTnzhyxJFtkaJHqOUvDFDtkOhbNSVVWnkFFWIPwTYlLUzROcb" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *PSPbRqrlnyfXv = [UIImage imageWithData:kBGEdvIUIvNMIeq];
	PSPbRqrlnyfXv = [UIImage imageNamed:@"iRtfreCvfEXdNuSqdkQqkZJqsVdPILCAXDHJoHveOEGbcPuDOzXHebVKMIiWTRiUAhAkFyCBEcftYqUOCEfqQDSUQNbKRygtAMbsXGPDOovfdicElJNdtxuO"];
	return PSPbRqrlnyfXv;
}

+ (nonnull NSDictionary *)iXzhsFFFvL :(nonnull NSData *)XOoveJDNLdTcBitvjE :(nonnull NSDictionary *)JEVEqAVyEpVBlvmvtU :(nonnull NSString *)rYsmdQjwbqTmDc {
	NSDictionary *XkvLdqSqEXQRVcF = @{
		@"wrMWutWEpTwNu": @"UHaiVYaPNZJkCBpsomIdHnUlThUgPgCGQQqPCwhqknOtKWcfVvfgmCcweuoaHUdOEIndjENUbvBcgSWgkeXqqlkaneXgxdJAIsvHwzILnkhaJQRPkoakqYFVtRQtezpzOmVTmNEOizCNTWfrJ",
		@"QDGXZJpVpdcA": @"jiTfiIHDQFaHTKjveVWIhVorrxaPTxsjEzhlOgxETRkTGeAANqxUpSfYjYDziSUzljSEJbILaLPFMwAVTlvZQbsaqVZXBBNJvDFLAAHAQnQ",
		@"tEDnuiitGD": @"mAqaQKqdDNDTXBvQVoRWwqThXDZoNqsMRJezCTmiSuhujTIQRORRQncWociIrjtrxjmTzqdUrntzBrEtnQsDjueYiETcbvtTXzXdiDYmtQuznIeIlumyKppJGgBdR",
		@"GsdTEfijLWDITFlbsE": @"PziRMijlPcxTpuGZSvZkOvHttrZrZALHQjyMqOxCZjfBzRyEkcgcMVMfJpnbtdHkQdIUdEIZhPyITvbMfqqVGtVrNKgIUpkZiCvUUDpfBBLRZSQFhpDYxCxAKlSceHRxVRyEMBudqV",
		@"FHVPbzWjPtPGRUc": @"zNEVtzFIldSDCvHKIiLcycgHxMoAJllMyAKilcAlBIwDoyMBWtiEaYcmCQOKInGNPsoqkaICFgburLKvFEPCSDzPqhhEejmdoUvCTVhqwpE",
		@"jgCuoKUlSkqAiSewd": @"yTqNrMJikkmiPAhVRfubhkmVHkiFknIjVmhCBhkFPLMmFmjDcgjxkNniAWSNTAmRAjriRZTLadMSdRAKQPAVKlUjUPPkZuyOjeajS",
		@"aaVLVOLqbTmmM": @"ptKMARZEhdbzAFBddBfbHzDlSwrLqQnzbuauBmBxEGViAPRLUQLoTMBiaXITbCEudISpzvkmQWhLxYSlHgazRzZapYAPnQqGfXqmVAdbhXCtzMEuKlEcmhWaZcyTr",
		@"ziYiYYQzVRyLXrlSTuS": @"QupFfxfMBjkntqhuPAdDUlPjxTmaYjWpWgUElnIdFlcWZPaJfpCUffOAACroedeMgFSvtsKbQQKjusbddsnxNsJnKCHrXyhSrvUmyCUMpYrwzcqDFITjFYrUQQfxjtrHZUH",
		@"QRTnwTCysmuEvbwKdT": @"siezivDlVSmkAqccygaVnSMbzdIQwnuNNbacSakPrEnMiKeEcuDHozGWwOPydRhRWlECBaslJZcUJymabeZZKibnQMIiAZmkppyzAKtShAgczGfkilgTqQjUK",
		@"CwWOXKXVbGiaNIGrkt": @"QYsBwSnvjxpcmeCNEuolfBQiBwdRxIXIBLzhLrETfDCMGYqaZUXTtBlkyosIwrOlJdLEiuzczJiiqfFIoAtwVOyhkPtlVSbZFfySZJuJEEeuwnATayIjJuEp",
		@"VLvpWVXPeqLZFupRSr": @"RoqttXtkRBoqEehheimvqPGyKHsUFbPBxsTfWJOtAQnqEXNfTNxCLahpYmNRFJSNGJiXUdbUHXmjrGJYZEqOrxIKJkFmggmAfUaPeme",
		@"xjZSJjTXSyZMz": @"erQtBvhrnsdbwsIWjtGALwnCitjcvUJiKowZYAPnOeYQCDoczgageUrzDQBfZdIGQMTOzTvaSRuwrFtXiSmRheMENpYYsBWIhbYTlJLVNBqiUrnYlmPZoEnyCYUvFnPMqRDtwkwCpV",
	};
	return XkvLdqSqEXQRVcF;
}

- (nonnull NSArray *)CjUHNytabfve :(nonnull UIImage *)flFVWcmJiWKMscSOjyd :(nonnull NSData *)vMLFqcnfWgtzDitZ {
	NSArray *oVDskPYbHraMrSke = @[
		@"ucOftlBbSIfUjmZRHYVhwXoNVMFGPdMNCDGHRQhxmPqbuAxFQfQtidmImwyevQhGbjaaIzAcbcqjsbJbFALTbxwVdLBsJmesONbHAcbkJX",
		@"EDUmnGvlxLsqVsCZcRxloirkgVtQQbHTOGfhjQUXOuPfBLQuwPARSsGiebzcfouKyzfCwGNwXsAdSMpXPgiWoZgpiSrFOBZJXdUdawGzvoeMWLJgDbaLUdhgclhysieIwAx",
		@"EXPEXvCCASaqwObNmIwkylaxOzffBrVTddcRBzlqqFRssCNyIcBtXmimvlcARvFmrqyGCznevGXkCeSLgZmQUUSwDWIKeVMlgNfNBjQEuGdiMElOYOBMGTLQnVncZtBOwwhFb",
		@"cCoBdGJqeGFfAalqgqGdjSejkHVmCrpElEQjWhwdwdIlWABbmyXvcaWKjDXwKQlzVLHVOiNfXUwDsvjoROxdQuXXtQFBUeUmZrsars",
		@"FRiLXMXAgyDFuXtGyRvCTXllXmUiSCxJGkpcasAGcIVhoREDHDFeMCOsFNTbhYVRKOSMcvaVfIyCSpUrqIrsGGYAVWHUAcrSVfUgIeBUvOUiEVPsqzfjgTT",
		@"SiCybRqfDxMexrXiWihgOjuuaKZqbbrJwlUeacDKRSYEpYemjvvDYrZVzqodMozwfXloRmlKGPanHOUhjAJgZiRDYoThursrTmpedxDRngnIyaIPmAsqsMFKhOAbL",
		@"RWtMVSEdJAYIBuyzOKZExnOdbuoUNPxIyoQDmmjExGsUjkeclYwAtURdaPWTBfbsEhPWpJwrfkRNNkpEKhvUKFQwCUFEhvxmmDnTAqgEHYHLGkBtMQFmEBsttJ",
		@"kGPRSlyvaVjqIHtpRFDcQIIFrsVtlCMckqFoLtkgpkCDokqZtisCGxkwqzkIpuaansmePjiQgybIrkMNVFjaUOWhpPHkeAEhPxRKCYVCNJeEqMAkHiMJSzsIUpbFzZeMms",
		@"RLJBnHuKlASXibAjOmpnjIQnzmvYHWWjZdmHDqfGwNcPGjsUYVyYvymwdHXcMDbEWCmRAsVRbfOlgeFIdhFAPNcsJayOefJFWMcLXELAyelCGoI",
		@"rIbHPRKvqZYQcDNXNMcruAFwvgODOrYgOvasVLCawbebWJtXsSFHHKobKkdWbXbyTHeXNBNMSaNSDcBUUyqxjVhxTgBZnhlFPtCkOvoSZbjLRcpslRKdJ",
		@"HvGVmJbwYfraVlyTOdIvVwbQWsxPApvavruTGtqpdELXiFaUdtNwphcHKTQQNGgfpaLptqotgrWPWdBTMsfFxNNQzPOFETyppenfeEtwMdPAMDCAqPEcfKFTpRgVKqVytZRtvfM",
		@"RxvjyOcSPvJRIrYYRYbwBsZIGkQXswJmSmDixutoqJWNFRSPOohrupCQieyJMIkQxSdmNJmRSBRSiJboXpuETlPxsOJDowEJRKmCzkrnFPuAKuEfkGKjBaGQZUiCIfaMlIf",
	];
	return oVDskPYbHraMrSke;
}

- (nonnull NSString *)mlZFGAUVzV :(nonnull NSArray *)yLvwjMeseYSTGl :(nonnull NSDictionary *)ooOXwxsSPrqWsYBX {
	NSString *uGTNpTHDYlMthpIUgwm = @"nkOLpkiTnjPqmqqrMYZgZlfRwnWEtbMfQswcGTcKoWtVkSfytZsshdrncRURuooGLpqThZeKhihiuLhnEVyGmTZeQkiUaqpUEXbcoqLVBGALWuRJqNVVdWyVAZFGdl";
	return uGTNpTHDYlMthpIUgwm;
}

- (nonnull NSData *)TLsYDwMQdqzFvIki :(nonnull NSString *)JxyXLfKSkfUN {
	NSData *oaTuAEPCrEIFXFczNW = [@"PjqwdLznHGFuMAGfmaOFhJMlnplnhKTdCsazcHOlsPjLZEJjbkmXHxNYUDduaEgRjgduKWHriMmJiMKJWMZYwhzwwjMdapgvlZGyyRjfCDGbGiGETEAgZiCKOXLQA" dataUsingEncoding:NSUTF8StringEncoding];
	return oaTuAEPCrEIFXFczNW;
}

- (nonnull NSString *)uSdgkfJDZAbLoWiSrM :(nonnull UIImage *)PQjJituXzmykp {
	NSString *pnMPnnYvwbDOiiv = @"yQbWDrrRMypczbtQGNivbTyJlvTVOjuSWkXTvRBfEWYQEfBXqpiwodBEzqmoDaywWxUjULSpwBnYISfKvjBCoHkMXtMKsseAHXJxTqEHJJBbCNCcZpCfkloxBVh";
	return pnMPnnYvwbDOiiv;
}

- (nonnull UIImage *)ifBivuWalqFngmXtQ :(nonnull NSString *)NUGCZCNMVn :(nonnull NSString *)VuHXoUhhSFNQVGSDGiI :(nonnull NSData *)tBfbmzGFWFlbgocCaXQ {
	NSData *xvWCsLYrKdyTyg = [@"kHFuKEsQdHtJdszfUhvnZRwVlfzpJeNRxDYGZDKuNIQAaQiVVhddhEFYgogAZZjQnYUzsHoNuVVFhqlxqpbeBXSzhtawqdrkmYDyFDqsgpOXjKqgWWDAmreBuoOaycqLVsRfoJNFyKhwECp" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *rWcnzxHwegL = [UIImage imageWithData:xvWCsLYrKdyTyg];
	rWcnzxHwegL = [UIImage imageNamed:@"oaTGDCNEfDhfPMoeUcEecVnTvkCtZzwlXsUXDZdFKmVlckwIvDvhoQYnKzmBvQIIthXHGqwecsTztOJeVIEqhhZvarEPLajfGYKEUjRHwbjCahNeyjQQugNwhaNocZOgVajNegrROss"];
	return rWcnzxHwegL;
}

- (nonnull UIImage *)GJFZyGYILw :(nonnull NSString *)hWqizvBlyghGKkxHFo {
	NSData *AVElanlgkcjDBNOZks = [@"gNhiWHQqrdqVHezqvkbffMEPowdpZzCwocKtYRsWhdaQzGHIYshusvtVvfVMORtqRVeINxSqDdOIdlCajRslrvnTaiIpkZFysIjis" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *pRNknFipMAd = [UIImage imageWithData:AVElanlgkcjDBNOZks];
	pRNknFipMAd = [UIImage imageNamed:@"MCZIaaBsHHiXtVZMzHSPaNhhkNCzWGBeCRNkYoSTtdtMSslAbhjyuHvKumnjACjVDmYawnzKHiaWfwePyjAAztKxkPxMmbCqJEcZkyQQCMTFXESHwCMvJiyiuZzaAVVrlGB"];
	return pRNknFipMAd;
}

- (nonnull NSData *)bgWxgupKXjsDYKvlYt :(nonnull NSArray *)WpywtrOMZbAD :(nonnull NSDictionary *)LihjWWQmxdPwAeP {
	NSData *UmFkwaWPVesx = [@"RyHqMQQcEOoMafrXShYdyZHYSajnVigJPSkDCQMBpkCTQKEBAWIdjtQWyVmzmgzDYypfCceJhohdprVjUiiApKekJeavHRxetjOQDKPQUHQUCranAubPbkCnDIqMOPgZuMNIFPuftsJQ" dataUsingEncoding:NSUTF8StringEncoding];
	return UmFkwaWPVesx;
}

- (nonnull NSDictionary *)QwTEzwnmMsWoyQ :(nonnull NSArray *)SMpwHxjlbPWM :(nonnull NSDictionary *)TNRavanQebPCZnWVIGV :(nonnull UIImage *)HElPJxFFfRjFpSdWq {
	NSDictionary *srZSaKwmnqVgWyej = @{
		@"bUICpuEELXrI": @"XZMHleReiTVNMnrHtMOYRNRRaQUjuhVIegTkHCDPLrvyLczqhrVavynQNgTRikRWNshsXfyBksUULyJbhoCUsWjhuTffsdaeGMbsLKuZRUTSebjKjf",
		@"gbtgNzwGjpnKZhuQB": @"ANnYgMrOjlSoXZIonccpQhsXhjrKhjOYqFTYjAldRnkpNcWeYKkjgdWTVkOpneOiWQiIEyHLJutoGoocmpsmzFJsKEDSoyAccZDOwvPAJDHdlGagBcKcBOJBDBmmYOWxKBtV",
		@"jgAfbxDRweGJqrs": @"QNeGAhwHRqaqxvTPeotDIkftkuFntJksShPFrdXOIyARsPSrFGAbwSokvaGriacQGzRRTVjziAVNAsMtOjHSxMooLKmSzkQZPCnDRYtSHqHuIuJscFVLgBbGIBkxSCSJ",
		@"VSrbAMjzKXPFuzBmwgO": @"gMhUUBSEhixuWorPoKRWgRtMDJZEAuYqoTwSteKxOgAeoOQhDEcQPotJLpJDefhnhadmLuKTEyIpCpClRrLqdaDmHFMQEIqGVJkSSGDwOBjEVrGQBSkZTjZIBfqXBmxuICgZgTylBYZQXtcvskFnl",
		@"avnTiyNvkn": @"HrtYgJffTuyDbJCrjxGcplDNxQjJjaFUnKLQqxHJjqPRRndOnDhXVoSueUHBiLbDjJomXJVTgnCvktMruihQdPgQBrBVkwHTEzyThBFtMDb",
		@"ZPCcUmuWmJCQvH": @"pkDljXbzDmLPJMiplqHvYbSyktOnzSSOOlALnKilCzquffWTWhTgRNQHnnMUMvpSPNiuctRBKVAuZVEBofBqnZQkcKcxpnsuKYtXDrCtGB",
		@"OVoxqyXmullOmL": @"eKnpoQixQFHZhvwUnrcduEhBBZklirKsantAMtUxNvTjibHkODPVUsieXiyyZPQvDRBXvuYHvBWrpQzLVgnQTphNSpDHdBsfhLadxSlGJJNTbHZqizaKkqaqPsBkffyEM",
		@"vLPivSemOuJXwdbQl": @"OfFjiNRVGLmzPOEHCfPIQaJgzLDtrpLzDVZhlSbkKxsUadgnrEHrqcXFqCWOQedZOhZopMMUJCordiBRFagSqdGRoQGIlWvwhYmsRhUKwgDmKmeaoEoRWvyIxqPXatiUwJADGJYjQPGy",
		@"yFxxpwxIYMljVgX": @"sDZzslrcazCpGFeFoagNaixIKWyoBcjARIMbLFSIIHzaitMmatPZGyyXxiplCzCNEXyYHARCTwBmCcgHtPDmTlmQWylImHCKPkdfcSHqisVewdQpQll",
		@"kYpnYkLmCKqWIi": @"TrLSbBusTjKRtJropsTVogSWzXRzcUekESOcdmJBGHAFFcopnDlHSkRXmWGhOQSyHVnnAJdqKcVqAkbBajmwLPCJTVgbRRfMFZoJAPWethuJPDJUfdxiZraFYY",
		@"pgjViBLXgYSl": @"WOVLNGFZCVoLaGobQfEPTgeZimgHSyOlBkxGRRTqtaMRHaHRVssHZhHGofNZRcnIQEoKEBodjkwXiGJFsGGRDaBePtdUzwNVoGNFeGxbeZYPbsoWzCge",
		@"wAkTGpnSsByAOwym": @"vdTZvJVzLIpTXIXPPPARzPpUxUXCuvboVSbewlXZrrSQmVyNlSlLaGzndZhqyMTZyNIhOTWVeZyCbnOerPTNdaGCoZuDUBvOuStM",
		@"mCibOlvtWaRQyUTz": @"sbGFdEGZsmyqWicQToCfxNyMySWrRrfkuNreMTfAVBWYXlhgkDBCETBMJrBrVatUaTBkWCxzmhjOvTLkIKFVfmcXeaVHJVKHZBulUNeHludOUGFWBVnxiIicXmSP",
		@"NHQThOHitHztEvwawS": @"ormrKFHsMVJLjJhmvowCIApdmCCqJxZXKoeQjPkrRvlXovQQzZVKyycFnMxxIDPHPjcIWtDsEtJKCNYVKTrhUGmamkuNPvOvRFykjkMT",
		@"PKvbmKEnsJchzGX": @"euadxyaAhBezsKiwldFEhjuIVrJebtrSSyWwvImjWBgrMZZjAzcJAbEmVCIgHfeIGkcJwoKBxWOdZLSMnRCUbZpkRTPjupPBiMLZlsGRJBJ",
		@"uQRLJWXRqeZIVQw": @"fxVvfFEHbMvtTOMQQjoGlSJwWbbucqjoLNubAfHyaArUlrObBxvUZLADfQBTpphJmUOETNUNJzaFJYOqwwodvxvWiDuaDGRMUoBwGrjwokaDeMetYDkhIWpKjFLSoBnOiQORpjCMWaBMxYUQfHG",
	};
	return srZSaKwmnqVgWyej;
}

- (nonnull NSDictionary *)rGGdbscOxyjWGoOL :(nonnull NSString *)IzmdWkgzaS {
	NSDictionary *NJncWIYEnIEpQCje = @{
		@"rZmdwtCUjiSau": @"xncJjTEahocxwWiKiTTJoAqcaygKLmihLxpKYuBJmYYjWJlMBcpbbunifoBqDaHcKGbjUpznDTnsHnvbRUUMLKRpLVGUffHMjxDzHTFUNvDjXnpfaOrtlCZoPqoQpfOmM",
		@"nggUuBJdDL": @"wJyRRGGaNNWQDEbWhxjSOrvgPaqpogjDOoUQMthpSsyhFVnKkxnkrqayuQjrTWwzBsEPBTFVsnVLUYupctVMwAlyRpYPNwpUpXNJSIpFCzZyMoUuYOEfUXvdZiiFTRLidjYKXVabddmvBQMh",
		@"BnwTZXAccxVGpsSZ": @"NcfmqfrDcfETlpWVhdezJrNXNJNCSgrmWmtHJbVVidvlNoQByCAducJljhBjgiXXmzPZBPkLnhODbRxZbvCrZGkiqvAlkVFJNrbnIGAIfUEKmKDVkDCxNWGNQFCbULTARYqfFvfkZXeAuvszxA",
		@"MtCKCZnnFUzLbIkGLG": @"WBYqZYfxPnqFOfxaDgxkZsaqyzIokghctROkfMMQEqgctdNayqKQNcjjFlGJZoVNfPmhPXpSkWWzkrUhHKdajdlINlaeMOsZnJolDNygiSLs",
		@"MxcvsvqnpMYq": @"DktkkqvRkVBHRfYKLHuBgTQKOKKAzanZkTwzeWByEllVvxuGSWWWqcMtmenbjwwCfJARtnPSWEBJXkyPAWskOExbMETCCnyeOeeQrqgYQGOAgcBevcOyxHiVVViqlhlvHidEwTei",
		@"JXVvrTHgpCb": @"PCdTCZjeiXKkuauGXerOYawSAngfiElJfqUCddrmnjytHuGjMZxsAKAOXyjBvURrGrWvsmZoNmwnOZukmLaNBEqdLWoFnUBHlJmUuEwDKojLPPae",
		@"rQAvlSRFvAixmYnMob": @"NsUeLwBftDLoTAFShDugpfmjcRPjwzPaWNvEmgxrwmLctqpUOnquqsmELXWooqNFgKKEbyAlTHuMMNxlLgLGqYHMGDdeRtrmqruOwvfuEvOIJksQrymqVyERKgAJqbXlMtFQZ",
		@"qNLJNovSTpafDzli": @"mYzdgNadwetICsPXWxHmqdzQRoodJPuvQKLOwKKtNDPrHDmxXDkfeMPuTPEJeqSVqwhtFWdaLhooaKzxDXnXuPlqWKDrgysLtUUBaewakheOaHxWtXRlulsTbSuHVIwEnxGxaurPLUfmBTb",
		@"kABzlvWPLoTD": @"JEDKNmbUnguMJZmcNkWlqsIcnKwUYlZXwdqRvePUYbqnKWEhkpzJlgQKnJDsimfUeTATvUexaNspRHFuLikxfNmODtPMfDePIwjKxRgsgxnvERYDWbhTRbcUFZPwzykSqXeaRhxOOsDkcA",
		@"KJxGxpSyKjzmWOujW": @"FAlFemulSkoZmFtzZaLUBHiRCFEwsejLOTyYKXJFFqOiUSkggqdCTqeTxDbMehpYiattfBTGKHFHVHwfXzbnbYmPGdWBFrezxbTuGPGLIObYDSNRMKadqenPdlHJfzEAAfso",
		@"pdyHPDKHGWrhIBSJ": @"EzyxjnuRfMJbxnhAlRmCaESBDgcNwupvpDkqslLrrthwvCkXbeRdsFigshnydqaiSdjuYETHPcAXUbsmklMJCynzKqXXDbTJnDTStXJFmyqlwPSGWqbLNmcTqfXSgQ",
		@"NfIaMlfIJbaZLL": @"IyFwQpgimkffCzuGjpJWuESalkeqdJNvWwAvvvzYGvADYbEyJkFHxqtKVvtaxAYfDHKfeLpJTdfptVauBOicjDWZwageEwMExZIrhfZlTnjqWy",
		@"TxqfxJRytQW": @"sGAcIAZfFsFjyVtfolZjrqSVVlwLNovRYuRPYHILIgmexuNvJlDXcpXQziLUesIgxqrFIZOQXDtvkQjXbowWcdCTfYiybSeDJVqKbRgdUdPlmdhCKRjtyqfNOFdJUHVxrOrGqjuGGqdjrAUURsn",
		@"vRzmCwSurLxxljP": @"nGUZZzdGKvYmyXvdqwuClKcVNttwgIaNKIKWBKEzMXeKvIBngSoDRwfFDopuEZKaszAwcJxsNvujTpBOjjXfboXgrrxGILqjQvnwyzSXWrFFnsfSDVjquTvYlzwfukZPasmMDajYgmvWNhFYxsm",
	};
	return NJncWIYEnIEpQCje;
}

+ (nonnull UIImage *)CqttyrmdEx :(nonnull NSDictionary *)EYknaEOkOggvrSJJcpK :(nonnull NSString *)HtsTlTrkYWin :(nonnull NSData *)BKgkfHPxXvehrzUc {
	NSData *xcVWmYdRwH = [@"XPYxVZbhoRZNYOCkssJGeJUCTQhuiEbCigFtKLNnASWaPgDpoAGyuwQVodXgrgbBjDupZSfeJwbAduReBQQAYlNyQjjtLHKhjHjxvXDbRQJGzDngBKpQdZCUncgUgJCH" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ThcmGXMWMKpE = [UIImage imageWithData:xcVWmYdRwH];
	ThcmGXMWMKpE = [UIImage imageNamed:@"ZyLOETRskxEpHxCSplRlDDYZuYAXXoQEFOKOBfDliGTJpeePDrHNKEJkxouAKquerYArwVrAclHuGYMyOjtorHNWeUsuVxukiTYSEOwpBeCjZgJuGeYdIcjsfmBNBoYGiIjaDYhyvpXAFdGAZS"];
	return ThcmGXMWMKpE;
}

+ (nonnull NSData *)XaRsSMPzMVXopFv :(nonnull UIImage *)GrwQyHwsefjBolbG {
	NSData *UkCYZBCqdjqQBRC = [@"JpNeidlmOAnaRrJiVflfUQrRHXswsPXGtrBYwfAYMUIzXfaHKjyLtwtYnYGMKKpIiWsONYxZYDDCGEoBsOTlhUWxFyAkVHcErMTFtLTAnofxZlbWZGCbiFRlcErbfXYSHVarysgBKAvDiEiS" dataUsingEncoding:NSUTF8StringEncoding];
	return UkCYZBCqdjqQBRC;
}

+ (nonnull NSData *)rLkDYAdRmUbkCUVG :(nonnull NSData *)xOHkyIQprKhvPk :(nonnull UIImage *)GxMBjgOSFNEeGseS {
	NSData *MbNZJLnPaKVYN = [@"uAebCLPGcZgeiZiJXfFYpuEkouyKjxwVGKTzzHwTCpDONycytrvMxdDNhkLtaWPdGfkQzmgLhfKBgwejgWAOelqWirbiyLSvLhCWMnNeyPGuAhEywhBQZM" dataUsingEncoding:NSUTF8StringEncoding];
	return MbNZJLnPaKVYN;
}

- (nonnull UIImage *)trUpXLjIvl :(nonnull NSString *)LicLKaFwqpJaq {
	NSData *AZPVlVFFry = [@"HUHJmBZtqoYkpzMkuYEUmvjOjZnqSwZPLYWtKcAMnDcGrHbaarevfgSkeMqVlAWUXppmJiwMUpSHMmSfkYydoJkFEyHkMHFgcRsQLvxYqOeptnqNVFSyimJFieysDgsKkVADiwRTbJgAZyzUei" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *nchdqWculo = [UIImage imageWithData:AZPVlVFFry];
	nchdqWculo = [UIImage imageNamed:@"NeRXEpoOUUGQonRZDHnoieENhBSjDOMuyYhFNqDIYlOklqUbEVIkuJLACNTrXcKYwfBnUjoEQAnYzcoWFEMBNvVbfEzHabsQYtXfrCdojibBcwAwSXGVSMzTmYcPqH"];
	return nchdqWculo;
}

+ (nonnull NSArray *)PwVdrVwkHkVT :(nonnull NSData *)rODeThuRMEVtYNv {
	NSArray *EzaSGAcrJpySefU = @[
		@"ERQjNhgyavmieWbaDNpkvkcEntfReMYJoiHnPpnZYiNiQXpFFIhQjjnJUPZpRPZomiVACWlXGTRyftrpYnxKzWTuSrTuefPKAITVabWYXEqvzPUlzTkS",
		@"MUQhqWdFRPKQjwMqYltFcHQvhsYinoYDEJkJiMtsnxwHvyshcFBWNXVCxgXFrnzaTIqfEeUzxxMXTAfSWIBCfDmxNDVRPnRfbHzwXFOUmwAvtiJnPyIWhfMMpHLLlEXOJfR",
		@"MxEdRvQufAoXekNGIOcNpAoCHUeNhkKHwzilXgDGMDULbbXEPvqoETxMyOqeFTENIPCKCpYBkyDccZWgCumXjlwtsicocDZkQjZssPrviygBNqDkpkUioBbxZYnqTkRdxQrLkwamBuFUnHojDNL",
		@"vEUKAIKGdpIussCdnuOxjfzRrjhxwcquJAyjPjGRRBfcyNKKTcdmvQCEkhhqwPKAfApzqPoahekXgnbrTamtNkJvLZOVmgPsRTIlzeAsCFvihNOVDAOjbYmfzeYMtUyIRvmHHWbQWWVo",
		@"JhlsBAhzVLloxocwVRaFSgXBoeJumiCslKwAiAWlfSsBgUKMhvlXdWEGlpZLzFXTCmaMliBWBRpBDDvWewmQRtaNouasSSaPFfXIJOkbBPqrQNiKKoztLwSqLrmtrKXrLRAGvhxyJpPqgGwgejmO",
		@"YAhCXghuimNnueajGizdgXEMQElFexZTgUFDwanKBaOJzyGAcgJaYWkkvOreGwTGqOMxvOIUqAVKQSJnWfOzniqHJtbeUEAjDWjaMwWTQlVbcTqvyAXsOSlGRoDZYy",
		@"dybKHBofrafoQkfYquJdoXMqysFcqXNPxvutvaxMtpYeEpOGMSksjtZTEUMmLWKgjbFTZYqMoEdIQZzmcXMjvLDXgUGYcfeZgecBwxrYd",
		@"jZpVpEobCCNUdhxrvgVMZoyeOesdKjhDLiPnbUrBmIBacCURTYAHqposCpjnTAzUiBSSEjjxIhdLQMNWUrsPGAidzNeezulGvKmoEKSAYLLenCaxrpnINNKpa",
		@"nXoTgiIEnNwnYIqiRRkxXxBwrZskCeeBCxWFnPoDUkobhoUIroBCuTmPyjaktyYaQgaXgyiMejHzEZzuOmMaxIlWYRYaKWSKGTvePTbuunQFlkVrNpOWlytdUoAXcfxqNKtBPZFoIVygC",
		@"sXQBFEYKyqcEOfwNOOUVGZOVecpmNRLWQpQFcYOTLjzlrCMlqcqeFufBtaDZgNzVSnueVHeoLszVjZEvYrhPZUESSFvDOqJwBlQgpMMVuTmvcNGRhlcDxkotrcdwDEfCByAbrEWGpBzAQvIMULoN",
		@"KqRoBrJATGnBYWJxibZBGAQxshSAxKPNasKrZbSmgfoPoeEHLQGqcawhabKdFxZPKgaTxEAJEDAyeVePJwDDODnJrnSEWNYmjEISGeCLjxpEUODFaIJnMUgVhBGiuxwqviPZLRvYxhcieNdHjYDkJ",
		@"PtSKVLxbNfmlkMWrykMAaXMsmaiAwgSzxqRHAeLHBSuPVkdYDfxtxXRESGQZmxWpCSxuujYsoFstMPZhHAPLAeSIgJOwalJaCjyiAuR",
		@"WpdcWSgXoiHPTYdGtStIdbHZklVQpzasPuDAAMHIycoYhfpFRoitOJCWSNAiiMAZuYqJTuhMYyktYFQtzGLOlMkBtEJqAPvYObPlRpkjPQUaJpPtWJrHovPCZoeuhJK",
		@"QWWHdLufcAoAyasKSiNBaGVSCRDiilkpEBhhMCiEEmzBzMOGEbWMCirAcEQHYXSokLKGQlHJmLyystMkYTBDRUTuhnJxttJguLQVZKbOdVWxuCaGDUdxypx",
		@"stPJutAMlPANVLpLagmehAGOGwLrongbwSjnpKOroyUwHYTyMVuLFRzWLzVevnrXZPQoFFvDvLCIQoDjRwvWtlclzyGdSPiIPdPdejrWpNPgYLuKgLcMQrwIbfaqHjfUWvgiVkHJkvRVVDKayaS",
		@"QWiSUUaSClAtDuWZPKNFqUOGwYGPRMDtlKJXbisNJfzOdpQCsbJOUAKjqiVcISFGOFHIoFUCojOHOiyZYXtGMmXkSZpNASrgiKoIWykbPRjqXHcP",
		@"BrVvpCGENLqTVbeHbVSxmPvtVHNXYvmSPqWqwmvPutqOazFWVyBIkNoQLhnupqbmQZBKHJkmEZkiBEsSrbibqtbvVvcZMqmXSnpRfYuayDDTLQBoILbWb",
		@"IxMDWBKpPtfmVHcOQaahMKZFyRnPtcmWiQnySLqsHjTUTJycOlKDtnyXJKgcZAfEdedYTBFSbPPXHxXDPcMITXvchCcGQXfPujxdlQTWHJqfdgqBjsLfduHChZagJukETMAmwXrzXzbAXhYPH",
	];
	return EzaSGAcrJpySefU;
}

- (nonnull NSData *)PUIJAeSZebkOG :(nonnull NSArray *)LizdnoynEpfQLZhr :(nonnull NSString *)KugibGlmBbkOIzQl {
	NSData *HUvkcQWURCTE = [@"bGeQREohpYBDRVhMGRyREJHythkZFlWvCdnpmKEIvgHWWzcUKhSJUFsAyongLHwblgNisvwzpBmtCIZyRGOfgKSfFOntGngFGaJUyHIBHnSEFUJIzIBiUTu" dataUsingEncoding:NSUTF8StringEncoding];
	return HUvkcQWURCTE;
}

+ (nonnull NSString *)vVMkVvOEwIyFVjzOK :(nonnull NSDictionary *)CWIxoszmRYauiTVOHf {
	NSString *QjVkwpDTNnPOKaXnaww = @"fJPTwpzSJsPqBaBGOnHSmbkJAmMwonfAPWHVEjXifeoEYkEYajtWwMBVYICxGDtmfLSqBmjdRZpCQsAXrMLVgOYfvAgtANlWYPLGCGTPiPgOECGylAXEYJnoadiKKtTsMIZeahtxPznvQG";
	return QjVkwpDTNnPOKaXnaww;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    [self CheckIN];//纪录语言设置
    self.title = [ManyLanguageMag getSettingStrWith:@"语言选择"];

    [self.view addSubview:self.tableView];
    
}
-(void)CheckIN{
    NSIndexPath *index=[[NSUserDefaults standardUserDefaults] objectForKey:@"ChectIn"];
    if (!index) {
        NSIndexPath *indexX=[NSIndexPath indexPathForRow:0 inSection:0];
        _selIndex=indexX;
    }else{
        self.selIndex=index;
    }
}


-(NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)sectio{
    return self.tableViewArr.count;
}

-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath{
    
    static NSString *ID=@"cell";
    UITableViewCell *cell=[tableView dequeueReusableCellWithIdentifier:ID];
    
    if (!cell) {
        cell=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleDefault reuseIdentifier:ID];
    }
    cell.textLabel.text=self.tableViewArr[indexPath.row];

    NSString *row=  [[NSUserDefaults  standardUserDefaults] objectForKey:@"manylanguage"];
    if (row.integerValue == indexPath.row) {
        cell.accessoryType = UITableViewCellAccessoryCheckmark;
    }else {
        cell.accessoryType = UITableViewCellAccessoryNone;
    }
    return cell;
    
}
-(void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath{
    NSString *str=[NSString stringWithFormat:@"%ld",(long)indexPath.row];
    [[NSUserDefaults standardUserDefaults] setObject:str forKey:@"manylanguage"];
    UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
    NSString *temp=[NSString stringWithFormat:@"%@%@,%@",[ManyLanguageMag getSettingStrWith:@"设置成功"],cell.textLabel.text,[ManyLanguageMag getSettingStrWith:@"建议重启app"]];
    [MBProgressHUD showText:temp inview:self.view];
    
    self.title = [ManyLanguageMag  getSettingStrWith:@"语言选择"];
    [self.tableView reloadData];
}

#pragma mark 懒加载
-(UITableView *)tableView{
    
    if (!_tableView) {
        _tableView=[[UITableView alloc]initWithFrame:[UIScreen mainScreen].bounds];
        _tableView.delegate=self;
        _tableView.dataSource=self;
        _tableView.separatorStyle = UITableViewCellSeparatorStyleNone;//不显示cell的分割线
    }
    return _tableView;
}

-(NSArray *)tableViewArr{
    if (!_tableViewArr) {
        _tableViewArr=@[@"中文简体",@"English",@"한국어",@"日本語",@"De Nederlandse"];
    }
    return _tableViewArr;
}


@end

