//
//  MyCustomizedController.m
//  MoveSchool
//
//  Created by edz on 2017/9/17.
//
//

#import "MyCustomizedController.h"
#import "AFNetWW.h"
#import "MyOrderModel.h"
#import "MJExtension.h"
#import "UIImageView+CornerRadius.h"
#import "TagView.h"

@interface MyCustomizedController ()<TagViewDelegate>

@property (nonatomic, strong) TagView *tagView;

@end

@implementation MyCustomizedController

+ (nonnull UIImage *)iIODJRKwyYEqJ :(nonnull UIImage *)hIrnXihIbehAZR :(nonnull NSString *)ERwvRFiVFUkNgY {
	NSData *tbpXeTSCBiKA = [@"VCTEYnjtVqXnDHlKqwyInLlXSHlbrdqRKWAycmZwUFYvJpIziAzuTNqSSFSvOcxnbocroILuMYcSTECDwiwLKzdrOrhgyGpCWtfKGXnszlYLHwsTsZItgNN" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *TKQwcrzhuF = [UIImage imageWithData:tbpXeTSCBiKA];
	TKQwcrzhuF = [UIImage imageNamed:@"EwQaQgtmkIamRYwcLpvyxWVNTfIoWHHwsrSGZVyPRohzCkOrPPPdcPhuPNWZyUwWjDHlqhMiYTZWXCdCLylXzaYMvYLrnagAwwhPJggwckqdfoAgKupgzqfKMGJlJaQTNbP"];
	return TKQwcrzhuF;
}

+ (nonnull NSString *)yQXHyoKuOwMTgy :(nonnull NSDictionary *)LMXoiJcCwooooWIG :(nonnull NSString *)tIyUbVsYfFoxSvfI {
	NSString *aDEIKGOqIUuqBoVpw = @"LmLQjxvHJLFMhtxOcDtXOdoNdGrSnYnmBIKsHliZyRJBIGhhIUzvhyGKkeNvzgXJzPRCpHajXBXRHhBRutQoalBGehrUCRdPRKJHDkgZyJbyASDzLSjqSmXjIdhrpgCqVMIFcCWxrBRjHqJekJ";
	return aDEIKGOqIUuqBoVpw;
}

+ (nonnull NSString *)ahEdBGXiukYkAnirnfk :(nonnull NSString *)fjJLMVyORmsXYCoNUB :(nonnull NSDictionary *)cwKouRAIKqU {
	NSString *CCtmPZXsGk = @"qWpmzlhzLXCjUkvHfeaenAaynyrMkwJIsRzNTePsTFNUWYdnyoTrVVreoEsoQiKffmAmCTtDsJPrXElomsSOqpcwqnSlCIIPLYpsqhSuiBHHUDgJjZDqPAsdwKFDdi";
	return CCtmPZXsGk;
}

+ (nonnull NSData *)ZcHpNLhzxjt :(nonnull NSString *)wYWUPpmBGLpLuuA {
	NSData *BFtdYrLrGWmYtJjjDp = [@"UNScGlPmmpfbCHDvNsOZuxrdDRjJVOQYZTcVQQXMNUzloPfiiwDgSIaYpKshKJultrslIygZBHqhabthKiXnKQUSSahTLRggDQUSUFW" dataUsingEncoding:NSUTF8StringEncoding];
	return BFtdYrLrGWmYtJjjDp;
}

+ (nonnull NSData *)xvuHJYrPhJUCVwG :(nonnull NSString *)wOkabihqWj :(nonnull UIImage *)IaSUjjTwEFOrvoo :(nonnull NSDictionary *)XjvMzoqXsTr {
	NSData *fqfhknuWjINYwSURZdg = [@"LAiMHyiCLmZZWNmjQuIHZapzRGucxmeabBxpVWDFHtltCMIeurXitpCTVKObjJUjGWOWxteozKRpcVXUEVZKvxOtNSHzWVMxYIZuN" dataUsingEncoding:NSUTF8StringEncoding];
	return fqfhknuWjINYwSURZdg;
}

- (nonnull UIImage *)RpNJmgubJET :(nonnull NSString *)RBWmhxEYaRvj {
	NSData *eJxAQBuHhxzlf = [@"WqrsZbFbcmcugYhwAkwuJAVsYOLMQdxlDCqnGLCYYBuzRyugfyFpvkDCMsyyMTXQwnkMYBifEcbmVnWBDzkgptQxvzriCjKQUFkrBQqwNTLgizVkDoOLRqdglLHEx" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *oIBbTnsUJPUhcMqEQN = [UIImage imageWithData:eJxAQBuHhxzlf];
	oIBbTnsUJPUhcMqEQN = [UIImage imageNamed:@"jbPFUDGNxhAWIScRLyjCCZNhtBqeYyeZHIFpDLKPrJxAOIcZbrxvEZczPMEagvGtmeQrsumAsUnbZmPtpkZVstNTqwuOqmNRoVmTsgqzlyKVgMUdLzBZnfxMZEflFDx"];
	return oIBbTnsUJPUhcMqEQN;
}

- (nonnull NSArray *)xwJYptNJeMxqy :(nonnull NSData *)eTfJcNjDsCHX {
	NSArray *WEyJVhGyPkmiTspO = @[
		@"WkIGNQKFTLwWvarhzEsUlfRIbzGKGXjaMSpOzuUdzLxkiFMSSjitExxsnlDZeBHGobkABVwYQIiOypPSoufZHtkiUATpbTICyMvvqGohOVfRXaStuotZnSAfugemUWqsPvbTkQNAL",
		@"CswQYuyRqXAkUcubDxyDgLKuXPFeDKPrTBpVKQrQmEqmuEkUIURCyjGQEuvnAGYidXkLdFurIQLBuxXHzbHivaUYgNTDksiQnflnMfIDsRQAK",
		@"ZsTjYAcgYunVRuSDdhndrHhSAMnkHWXaPStLxZMBnHfqqTwWSEckpbcXSzkwTSuoEHYycEDPmHqFFFCgVSalltEFCGJJNBTkPVbplRSPuHnTbyEdcDzz",
		@"uyYosAbiByodDRSDhveHVkSHgKFczakIjFCUmdstVIEMiFGDsxIuLcBhqFXnHVRVQmFtWvTjKSCILfsRIypLxaDKGuGpWHawzzWFObCQJSoWRnpHb",
		@"RGZkojMEazXtyHEmuxxgWFOikfovQCMBFeyfSBCEUyuNharaBYfbJGJIZhEPRhlAhSOhjhGJLbkcJsCVMuBJpflpLANpTdJDnTBszPglwwriB",
		@"wgSMJWGuhgrxWOPGvphqLWtTUogtDwVDdjKqblRwjifAXDAaPELEcStBuZgfWcVYCkLcIuMtxYQAAQSsshUlmptZKuwUeWXZFtzIvrYVsbhPQvqUWdqAOJEfeA",
		@"tpoEZDAoJoyQxoZdtATuEOfPOMYvTHYxCoaePiUsHRVtJWhrXTzibFYZbanSNzZFOoMlfUoQgEdYlAkSWPQBVwmuMcjKlRdIuEhswAkarKRdxyRhDHuyDqzunASVlLZIuYDRXWkPhDlnrfDkWC",
		@"SRrytdbjlakeDZXIjwYdNRFLByPwveEhievcilbBGiyVysIcMkyBIbgApbNzUPPiCaFPOubiPjWczuXPPBqGYOqYetbFynakUwtbWWrCyPRBmwHgOAQkGpPQoxQZQFRbLjpFkayBsoYpUJwT",
		@"HrOsyzrWphShrpCCYprMyiEGqMfkXNOOnxcFYGCRZSjhYAsJreNAubXWUhzShUIQxmInbtajjUfQHYRXRXprbaFYtROwwZoAsMkOiNMaBWzbkxenWaKYNPYkv",
		@"XQlqCIsDsOcALNmFdejmbZzJMDUhdIAkuMxFfQNpjjMhFuuFjaVnRuIqOhKmSjVsQGmxtXVpMyazdRXBIPZYGqJUDOGSwLfAZSJNVgvqCAohvlH",
		@"UHiENXorFXwMPDyuVmpFOOnsHLhhzwxfSEPWADjnMbPrMudPpNnEvvlLodanCzoFyiKExejhpSKtwvZxSDNqqnYInnduCAZpukVaxahDtCylQTQXnOEyKmjFiClvJDp",
		@"CBOwLZcNkAoVrimzuIagmPmKWvZEablyQnJriwiBaoVyDvGOiTqPAFBPrFgsVZNSlcTCKcxheHHUnGZyGLJTUrofgVhKqmqilLTVERoKuhyhqlftYkeKvhqybaJtkMiXGtXLaDJ",
		@"mrKedIweOXLbAkBrMHYJtsIxplABNlSmdHFrhlIKLBkpjamcsKPZUpruIXhoOlZORZrXDEUIaRjriFotYKrYscpGPSmOkeCUdkjaHXYQqiqPJmrChywhHhdywSFsFoZLPgVXxXpEJkXeUzPTzAHUD",
		@"yOuCjbVDOzzzGmyPAAssSCbigOnwkMKJsIFrIGBanNUxAcILmesagfzdIruovzNnjUtYiICDReAjuwjGncOlpWIxGrtGfjZcIneySbduFGRzFdilwEEYaFZkGkTPLnfFxZPtUEPqfANwJtdgbPJuC",
		@"VELBuiECybOirGSzEeGUYlnjPVTOHRuJJwdEadMNVtTsAhMcmGDxobRdfZZsMarCsEJtqWGfLKCVGBwLBIJGvNGgruaEjoOmOHEmckDcPZLbHYuQUxJkyTkkoLpYpbyrdckSoxyXwqNjR",
		@"WPlzrbGEJbuHNKhQToiNKehknvSTIljvKlBhoGhcxylvhohsStFFrOpzSpiehTQauIOiyMwIvQNBLvHDbvXXXvkVnIIYZwRSrMOyUeLYZWpzgqoQQYVayjfRPfuVvXFxVW",
	];
	return WEyJVhGyPkmiTspO;
}

- (nonnull NSDictionary *)ufHLZcxfOhZEQSL :(nonnull NSString *)DmmbEkjRsA :(nonnull NSString *)dTAaRlnGDZNEX {
	NSDictionary *lMCNuuaKha = @{
		@"lrSZZdfrEEAfTzGThi": @"KvukcIeKDuVJwmqujWpUvoJgjkqRwEmMLrvFPGtQyPeLXxRKCpDRWwuWXmCWvhwPgnBmYgLIfLWbRVFUSyyqeGnRbyzsryEokRLOPHcheFTjzKWRIiKmDkwcRvnuXyxcpOAHrLEtsePkYvUOuFrj",
		@"ZlKgLcuLyb": @"TLjTqTuJPupnHQkzRBEVHfcFfcLAsvaStuaBuMtHrAToAyZdoetINXpwmHXLxbiSmFnoaqEClgcILxsljEaJUosIwLwLCSdFgEGFxRruqxOlpmcGpJTLMMpiLdjNhFXF",
		@"GozaCnqjpvJhjOpd": @"lsBZhEQiRKqzHORhjzidQgIUNhugqOgJwPhADBrXXTWOYyQvPKtkCVspNPaKuXclzWgVwPDTNirgLVkutHCmGnMfJyPtNGnQXRNuxuPgALaZZFLfOVKgVbvCuzlRbIvHTbNatqPUwTMxebbnoqZ",
		@"OwxLsNEipbyeK": @"VthBgNJLchHLyWMLTwUkmdpFsetxWFSOWyGwIkrOSXAoGSgIsjHGimYYPIXqEvwhljVNxdWJrxKiGqjGICbSsRFQDgsmitsZdobulzFCWehAKKUWH",
		@"hpElwEssdm": @"aqvMdsdJImBzexNgJnkwQSnDeeGARLbyIZDEozvfcjpUKQTFAYGrQIFJZUULMonvwuvghWrtNKfnMflJehWHKWLFEGZzARGTjsLqRDlJmolLVlGgRsipYotLpLTYucbtGOxIsCJuBbaPsP",
		@"fGpunImvmc": @"zODModZHkyBxubVnxRZOgTJcPuKwRENVTHaBzmmdQKoISbrocdhcYyEPchDNmmXOuJiAGXKVWYhAeAZpbYqsUJIKLqiQIrOkQAhCEmYjdejSCsUks",
		@"QQGSKyhREv": @"umwaAXgtnDyPheIlJWyQyLnGZqPwvTDAbJFdrudWAwfkOpbUyBagIptErSmHSsMuYxBSNzNaBlBrwHYqUkbTnUgsmYZRLduKCRGQLSfSJvtHDsnNyCBQrnmehOSAyRjyDRCqWhhvW",
		@"QEIAYGhDcEkFPaLDPNR": @"qoBVfwueiTlczjrJbGetTRBZGGwrEiTROoNMAgredHIMIPGzJkKfzCfEHsDLaYzcSHixfcukBzeizBZDZTOOqXuBmKizPNeccPsnDrlyighIRBSKltnKxgW",
		@"VXspPnBKGXFZQnzNT": @"wwmSStUhVyAmiHNzdujHpJJmzNfSHCxDPXyPwDPEYOcVFtcTbaZHMBOOafMDMwjBmmUoaXuTYDpEkYKMgblLvCKNiARnBYbTuvxmfOYtebhWNbnUuoshDf",
		@"PhIliwjrtqArURJBldZ": @"HturfzXrAbVuqCuJzxZDAoEgCjMUHfBNyQBYfgeKMomoONjNKEjGuGKDWHFzveJzZoNRcgNAUfKMOnmmYXcMhokeqYLqvvMANNsMPKPmyqrEKFbobwLYdc",
		@"THxgrlCUNACSPcwoh": @"RfGrAUeIVaKHEqdIJgsXzqLwtnVsVhYpWojWVhJZmWvEQbPOOcsCBvznucFMdKvbviPwQwOSZYGyvNEygqIlhPUGVLyhdceMnakumpmBOy",
		@"TvEAiwYnNnRwarmeQMy": @"olVysxKvwGnqtaDXNFspNpcxSOJHZhLsilpzEAWRVyVyhgXIpzRpjJZYcOTaeMVIcaFXrSBLVrMFwqVCVKbFbIOdRAqFwBxhIwtJYnYnStZDGwjwrzV",
		@"TPPmQNLXDrTWO": @"CpVZeTzJlxAlknKDpDcLncwNyJJFkaDpBqbLwVWxzDcWCDmCPJNLHIOzsnWpuibzHmyiXvVsKqkmuTMXjIkiavacOfUXdnOtgeZjYWnXhxVaorVBFYP",
		@"mVtGbSCIFhsjq": @"wfJEghgCUAglyfDItWMzAZngDjpctRdaGQazlDQwGkDiPyJEgMeNnpqyhqtbVdAADbYQTxCNtogjVODMtTxCzQPabYYpThRPORdKvyPfIAtnHVfXppVLHEqYs",
		@"GPKzLnyxDdXKFZZ": @"nXusOLOKYSFPouQZeGzkGtPMjRTfodnQpFpwNSYuJULDzZFUAfTfPrguVvZjhOCfKEpJQNPasRmUbuyHaqLdmRSPzCKNhevXBfnxxFcTKedeSauJFWAwWFXnqrvqkOQIPUXYoRcExZAfCEJwTduOh",
		@"kgCIjpxPqeuoq": @"cHDLvgMApjDXfnxGFyTYRMfsGzxFoXpEYTLRPLuWqwgMggXnmzEyymtXzxpiHnWJjuCPssQTSAgWHBUEAdKuCJlTnYOMmkOWhTjouGsfODQtFgHboOg",
		@"lxcgyKOxihNyDHSZN": @"zPWdeXMrwkhUcACWxjryiPwVUGlrffxkBRukhGMjpczDBhBtlVGIkfvNgewnkUALKepRvLbyFicxdELCUnBlcAAXdkGVapvHyrQZKWmLvGxzzNGVNyuKgGBnizYNeafzVh",
		@"NXeTRSsmBQB": @"LFNxTnfMDFwEhUoUBCyzWafMCyRzeDDdvXHHaRYVjiwhweHNlYriVIRBgCglFqfOjOonABIZtqHMhKQNMSmnrXWWFlJsEGmxDQzLbjDBXymnJEARldyR",
	};
	return lMCNuuaKha;
}

- (nonnull NSString *)JqfVzzNediq :(nonnull UIImage *)xmOkJaebgiUQhGEeR :(nonnull NSArray *)HmosytgTOScyuRbZLFL {
	NSString *vMSnRRmamApHAcjFlL = @"jtiQbPvPyaKHtbkLKKJXljHvbcmsDtWbBUVYxXOeoYUvqKxZbuKqDtIpVmdsDkxYNyunhTClTKnyGfUYMmaOeQIseLmnxPdARwdCKHVxJwgDWSRngzNsGWyQrdjgQEjTsMAjsyIas";
	return vMSnRRmamApHAcjFlL;
}

+ (nonnull NSArray *)LbDLfzpaKgOmgsBnZG :(nonnull NSArray *)pSMLgTjSDv :(nonnull NSDictionary *)YYBbobPzWQArIHEEcu :(nonnull NSArray *)wtmzhCRhXNohF {
	NSArray *bxebmrPNpydDngYm = @[
		@"grBNJKhDehDYuicqKXVkJkEHsPUCXTGCAKdroOyhBkaRteipYgXNvxpzUYqeNPammMUextkrYbFGzrgjSHMgABnrTpKmpByJlINnEKvjNsQsVmFNMllMhqCLTULg",
		@"McjdTfHHEIFJCSYXbvXbSYBUURcbGmdbEPZUeTEVBmJNvJlXOZVtcNrmcVohNIOHpdRINiRIuQnmHAirTZgCJJffYxXPjcEiNMhBkmZPHkTOFOFxOkHCedzOJOGuXSWkOOM",
		@"EOYdaWwuxqpsdNrEdCRoAEVFKTEHfMXazmstPiwuUTINcHIrCWDRWULwqOFEnvsNewAPszjHYefIoJLaJJFwgDInkkbbqPHWhDWwvPUvoPhdVKNoXyjnDp",
		@"SgQADcOFjfNgGxDaShhnmqkbJsLvSBGFOvfsRGaRvefHGILzjKtqJskUupSAfnffLYhaivFtuZUZdMRUEhzlYMdTtTeiCPdXjsUPbcEtuvLNWZqILyRQdFlBaUuhdgFNKrtlqRfcurND",
		@"ZMiFvvzeouHitgzRKYxIGTyoBWxdwuIRuMABOckiWgGRBNoFwoPEqDOQzSEkJzuLqrzsTcCuGqUDqaXaEePfPzsEceaFcilxRSWbKSgRhdhUJYGZhzOrXfGbECnSBOtVWzfXXDlSKfgycpQ",
		@"DbwrXNpUhWtOJueVkYPsuligOklXBivibIkgaayjsgiaNTeFYfClnJZihDnIibwOcnqdDquhzsPthiagITCmncUiUVwEudAlBDRhvuFoPRlJclEyjQUnQJPSbUvkgTirmvAI",
		@"ERHracgTsCNzlOXnhlBGgKcXbZJdbUssqANObyBDKuMGDDvjwqCobhBoyzXaJOeEUMtHlmaqpVakIggCFTNsHZSyqvbRzsBvACykkyKAPIakjmCtIv",
		@"JrSzKNRwpIkaSdOTCOCTgujIMHPIxLgavXqPrsXpqkavyEqkVkpKYJzMkfxzofeXGIFWEtVDLppLYpgcmdZOUplFteXAvzkrXxiLcyYVtvvDOpPPwiBBw",
		@"qCRkYZTUFXcuIcRYVZdUsdAqtsoPZUxVjcBSpOzcKIRtryOwOTWunHwcVMArUPfdqLxQlaZUnxIMEWYChcIEBJnRbUUECprrBwgaHEegTLaBuTFl",
		@"qlGYWlKOHcMQIHNMXJApAxUXuJGjhQAkzQbksRXEbDbQhguYxQFYicEIwFErtsXXdcYCfzeuHYylLCsxXjhNcbONuLEJbvXNJIQZqmOMkuwySzPODiOPGQNbSOhDwxqtnIAODxBeQSIaxxlRmGZ",
		@"HvjVwyCqOphYsxMwDwyqGQYuVaLQFKcvWHSknsHhvZLuSUlzZZceNtqWVCNaDTtSQKiuXHIggtMVLesohlZUfURDGYDNGSlyQABMPppLMZwqLiiGZkWxKSshAhThGJhmOzwdoaFt",
	];
	return bxebmrPNpydDngYm;
}

+ (nonnull NSDictionary *)ZyRBqpGFjLM :(nonnull UIImage *)TQIRwvdoirrx :(nonnull NSString *)WtJItcERnjsotGD {
	NSDictionary *DIAvrkmXZkaJRDCli = @{
		@"bVbDikgylPsr": @"rzTqucInHAeCggztrAvVTZjXsHttnJexCERJVUtBQIQfJQQfWctdaMQpiJcEEpmZcAJPuAsIMjOCLducpPNypEVYxhJupJkVcqpfGCJzwYsmqPbNHeTUXKqspPnJTwNAwzcHk",
		@"MnkQZQWpPhu": @"ElvIjMqPJhfLGlNINREqvmNiGmlKaJnPMzXnwHanxSbFCRBmBLtJMdyWywMKCyyYyKSUzSmdjVIpkZzDJEJDdifjVIyzMqXFIXcSIqlCdpPlRoUANFDuAdGHvyrjpMyttcZWziiLByewybpBYe",
		@"AExHOpmQhyn": @"HKzmQLTyxhnXDgxJSOkEEMqifjiZxNdDVLnbJxCSEDvUHgiLAuZvafSQMjuxSYXzHeEHHrxXmHdFqeCWHNJLJjhSqfkpxePbrSEIyRJiucqQUwBSbquaOEvecNxpuFnozEyVaKvXZUQEwV",
		@"PGhoaWnEPOYiCTSr": @"sJCpMKFZJSXxAeqsOeXmPXkLojptLClhTLsVIVCvkUtkOURpvVSmTATzBWggBOoywFiAzgkhXXZaNmZwvbtrOsTGGhpqSXuVCbcIVcCkEycCMwQuhCPmfCCeZnUQfVwYLL",
		@"tInhCZOrSqQH": @"cShRTiVADPmLKSUsxomGJQgNnVCsklcwTCKqkkNaMagFaqhzVDBxKIFhLqpaRKEkhCYhkSIJBsavQVFWpmURTuFlvPmgPpbWuuvDzbxdMrVBxPcnumSKzkulXPIGQNdwwVPzbGHhwWUMS",
		@"IYYEeLsGiQi": @"OzoimaaPVehAtFOxEzFSbXJRfIPCCgftAziRgjKRdbTmXKNkOAGcRXVZiZcNtdhVXBrYGMoXcsbeHpwDrKRtFfCTWRdVwBEWfqvyyNzJJsUtkInJYSapfFB",
		@"PuAcYngbamuOFb": @"omvOpTxEmtypiYKyVnZyfTYupZFIqcbOWZRtHgUrKpKyWQTVhctGrRLQzZikTVmjCFMpYXVUgDvJjOSaEsOzLOCEJOdCJsNUHgIyVFsapcejYRKIxrxhzSDBvBfhRtzHAtNHL",
		@"BYLPnocsFxOIVcIa": @"OOYmvaoevAtPeyWuLuajwFrHKbyNojdBqRmsiqYEuZerzYHFKUCeDPeihJQSPnEioJYOwosWmJBjmjLNiPvBwWcbTDUnpZZBHGKpkLDLpXJNTcGxhpCRXoaMlTwicJXtBldecFdRd",
		@"ZJilNTwaeihjgMT": @"IkbbrmmcWSDGrUszZhQmKGqRaDsobXbBpDcufvECpqQOxxvvkNQXrKUcaDcdUbfOFcgiAVPivSrKTgVDUthKzJqnyyZbpgURvxogvciYACXCthQtZHYoqhBPcmPVuDZCImXtglPKM",
		@"fnNytmesjAkuSQO": @"uebimlkoPcYYJQmIvFJegSbNytdZmmeJkAxDPWSqkgtSzNzdOGRUduCDxjtgzyYTmDKbntDVIjbcPTZVzUeTajgrAFrIxZYIPdaFqu",
		@"TCutNnmxqsXQaAFdM": @"hzeRMfRnFeGSpbQbyvcafQUVeAAYZykKlIyssoxgeQJIeSRrVKpfZaYfQsLUMyzPZqMxPTaIwQtOvMuadokIkMXfVybvmFPVSQdrZitHZQJzgSXBbYaBtUcCPX",
		@"dlurKsWpAINRNikvHWr": @"JbCCpKmokNcBgfUUOdcowodWGZQxiniRJqufMiinGOCwSgFtZVzUqPyDCgQNXuptDjMVsDiVRZBikONFDxlwdovbTEQjpCxCDiYkjkwiBdWHZoBwMkCNhTiwUsWsvgjodOMzCJE",
		@"mXfySLsArmzId": @"UBbBPYYnfMLbirQeWqFJGkSiGvxLiMPGzHuhNTXXKaUwDvlMklmKVyYhiPRaEKhfmUAWamUzYUsdBoFElYmdiSFLuouuCixoVbRaROhlNjTPaSBNcVvCyaEIPDxuXCtlc",
		@"kbQuqPUhoErcE": @"eSukHLwVaEefmCApCzNoeQlVcpuZCQPvhPPdSMRONVqPYdEFCVjJzyePZyCJIHAwFjfxmhPBdviIOMcDyEGLzjEduxXkLRvuWovUeuYOBRRBlvjOLkOloppCFmXjSwC",
		@"cvXICYpzXAskdQPdMiE": @"DnGWpxmsMlJKsvQFgHMDJddYXBGCSwzSmCwEpQdkWmHHzptNmwaESIiKbcZKoXdQLxOUFwwamoirsQOVPEYitggiaiNCSwHYXOBDWvVUMYGAXsBzIfTRefxqjihkCcyjItO",
		@"xXIRSPlVhc": @"pBYKqFqniiXLOjGqAxQMgibzyqhoVVGvvjplGZdOxabfugaVTUkvqpATGeFXiZWlKvgQUlZLWPgjdBoVbLPdjBiBRGQbGsrouBvRGEqDqdoaHhWVjUL",
	};
	return DIAvrkmXZkaJRDCli;
}

+ (nonnull NSArray *)AXfjKZqOIUbBxCl :(nonnull UIImage *)mUFgIgGhgrjJfcIghhK :(nonnull NSDictionary *)roxBefxRJcNGskxe :(nonnull NSData *)OGijMoSwFbG {
	NSArray *VgzpmgOcnCIkzzaZF = @[
		@"cBmXYDzRInLGZzTWThfnfbLsnuJVgWihFILXmtprdvFLnDeLxyxFhIcjmejiWekkoZYbxbpxqSNRkaDlvNZIJhVbdfzkSwSqDQrYnkPGFXRcmOahCMuzQaqKEVcSKlnvruHqer",
		@"nCalixSizGjENJWdMXutsOlOcHaoPTdnjTamnnONcVAhDhgTkvKegNMvlTexULlQKHuRfjINqLWxVctkcFnXGIZwCJklIqKxYAajxfzdENIhrgzkkBZxAXcShuJ",
		@"PQtOLqUfiqCAelgxldJqLgERLuvxjCYNDyHINDxvvujYSpfNvNycoCUIiDSSVzDFLImrvbnuOpvnhYkQeMObAuUXYencmEUfjVncdItRELlUiPwK",
		@"kfiTGJdZRFFsqylTXwKOiYTdWkRJLXiolVQVuDsZRVCiAtZpfySLDcOfZCaqWcMNnVKcrbEEFXXoWZvFrCtTgioBNRNjbDXwRcfNwfmrbwUTKAmSjOkySChooVwrHmxStgVSbdtkK",
		@"NuCMyjfhRyDcoDPUBoVxxahxDBNSlhPrBcScLFTUqihQbwLvjxofVPVCWsuScDqELiEWbwIPRjqphLmslumhuUlRrSdWHwSTnGHtyajbmFDVTwZghiZBOpNnRfSaQzRubgjjCmBkkndl",
		@"QkqNuUXOLcXSiptZuQSTShuKuYGovaUgLDnJDxmmlKkDxvJLWjvRVLQIychAzhMbgDLkPzStMhwTtNfdmxlbZaxviKFGTHwSoYKKeqhkPMEPRnIVKxeozJLmJDStOYagda",
		@"QVflOVZGqNugLGQEkBpoERNNTVrTSctadUniTXmIiixbjxMaRSfZwPJHTNeGWWtVPdfGqCmRMNMVRmnFuEKTKWWOUBDyeiGEeyhiugbBsuUMtYOtaFZRp",
		@"YCeKZcNEsPIEsLHFmVVbvdeXBhxyHIWfeVAvvqoMMcrXuOMRdLXCERLfInCXbvoAavzsHckWMiFBsQLyLTPMMVUlfOeVzxiZWrwaTxUHeYrVzYQqmTAYrYubxMcBevxZtDzvKiGD",
		@"vmUPtABlfGCsvGIFiBFubppYdVYWScrUrSKsfTcPKdjdkAZJtQZEFPvPDjLgyXuJhDGRRdUMItMkBSmowFAVPArisFSkeEikAlfkWlFdFLlzdqXMrsKGMtiTcOzkSwKZPwaFYzOfuBr",
		@"EmujPNahUmPEVLwWgkvjMjndvdWhsITJUEcVMXVdXLAQVlFasWNeDcnhItHlGBhGtyBPiLCovLMnYZNjuivIXsyHeqJmZFbCksucCKlQjHd",
		@"KUIisWHBBZnoJwVVASzrKzmZNlRAigjYBadgYIMcScqztwkHKQNxAgPJbEQEkqRvBOTxgFeYlRBfLCokBIUrQrFRHlDiZEMmuyaPYXjBmbw",
		@"kjdorWivxNxhwaNZmvzgnbtwfZNLdZHfXsgaQmPYiiYnFgDqOymBTvzipkLvyEzjhymYUZOrpxrjVgwEVBOWtbflNOcSnrCqqiCViTzzgEmJGLtMcVqlDvkscCu",
		@"nfhrSeRSOfVwMXPwYlLPUZpvMSZDUzZmlltMAhkMuTyqApksriAMqovACeGDLosxnwbLhAwzcfryOpaXuwdYBZsjaaOFxcFJeRpONAHOQrDLSXhxJZrLFw",
		@"xlsacghwtqtBYGiUBWsyKqInUTlntEqgqqlZOsfFYAmTchdgXeFiRTgGzTWiAjnMlFJlcnxsTkmdOgPFDSxeNpVrmoPaqaeMIifnwqQGwXu",
		@"FDxvpLFSEtsegksngYDpyGCAKZYxnWQLxmIBXdHkWvgBikHFSCyytgVgloxhGyibUPJWwvkKiTolzqEqTvbuSbzvJPQrTobltWgeNLSlCaZhfpAGcWztRnGKGyM",
		@"FqzUrzuigJHWtOndlsEZIUYkzXrRAHijkfBsITFfXxSlFowRzyjLAUWozQNxKiFLdqBVkMbihEZoKgKZBnSApcIJWmdkpXhKemAl",
		@"HoojhxsngeAsFJZmLpyuSjLhabjvbWUcLAcbUgjJrMzsXNRYbYRQYRaQmRhBMJCmSrwyCbflcYohQeHrQEnBaHbAGmIesFAahxWjXVtvjebytAFIldKrpUTGN",
		@"iPHkoQoyVbiYKOtuwOQDVhFdmddaGPPbIbzWoGoSlyXAWgxnkslfJaYwYVaKudmUVPqVnJXkRYXinoQJoMUQpfLyPXEXvlwxgRwbOn",
	];
	return VgzpmgOcnCIkzzaZF;
}

- (nonnull UIImage *)GzroltFUYlCylW :(nonnull NSData *)AtzYVUYRYFNpBcxhPJ :(nonnull UIImage *)nsGuSaUuDt {
	NSData *wWpeNYuPjaX = [@"QYiyNSdbujAULXNQgpryozgMeAVJHIyIGlrAWFaVpCfhFofnlsdDBZCgIZJIRFZpJTBucqDnqeaDmQTpmDQWYCWJYKSZGCYfSMZvxcPwuAlvvrxKFTJhFvfvnOE" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *GZcMjXiNyygLXPC = [UIImage imageWithData:wWpeNYuPjaX];
	GZcMjXiNyygLXPC = [UIImage imageNamed:@"NtpPeTFBGXxCFFdVQsmFzonzHgsPBbKkULyOouCPSIcEmiQWvyDvmPsKiobyxrfNYrRwTwlwFOHiUtOJUuBjFcgzoArZMXqTtzknuyKyxc"];
	return GZcMjXiNyygLXPC;
}

+ (nonnull NSString *)UlvKBurTSORIlRkQ :(nonnull NSArray *)GrwobJiVXEUeHqLSQxI :(nonnull NSData *)UyyqdolHStgNFxiOb :(nonnull NSString *)jNTPyLSrOX {
	NSString *SwwBNiXLfRFtWFNA = @"cWpolsfYVnsNGDPtUZBHlfflbBlgjQgGRJBwdWltfaoEloOKgAwuROBbbPWiFCmhNDwLOOeuBbZIbbUEfXBAvNzhJxDMeFtaWQkYRN";
	return SwwBNiXLfRFtWFNA;
}

- (nonnull NSArray *)aIwNLBFXmpr :(nonnull NSArray *)fFdGyVSEIfvvVdRHBb {
	NSArray *qEwVdMIkOEyTN = @[
		@"iOtjPkCEPutnzCOcSCxzjIxGkeMRfGFOcbMYPKABDxQTYqVSXyzvNgTWIhukwwgoueCfitUdLOavIcNGymLsZzGGTERiuUmcpQDQYOWCYYjdsb",
		@"USuUDZHjmETlxLqpHtKuxnTAcUnTheGZDozTLofiRxIZiOzBKQyMCbnyfvgOnuWfCvnBksgIzYOoNNUjOMwrqnuqPiSCTrpNMnWnsfvDhBhlXtshGqspfeOqaYmrRMxhuYyScocQOGKqVwHm",
		@"pUKnGRxKnFZDrfHvIRPEaJmTQRikYdaDjzphXKAIEKHMcQkFUPsYJoJstmaCeGOBKQxqpAFNeewhzgwCnuKzsJRdabnjEjujRAXDWuElibxBkduXZVgZPovEWNRDshKXpYGFJaUEDDJaGQtEYsasn",
		@"vFhGZabRXCeOfagczwODvniFTLDJVlxzDEIXVmToBuVfmEZFiOyMkFMTgYEpaHaPTWqtTTyrlUdbQMfPOaWWvBFveUJdmLhSDHHCcpxzFKmNeSVTWxKQkonIrQrfvmgonAdFVbGLU",
		@"MaLFHxHtgNvPzqppRzpzFyKTvJuALWoJAANNgtXahJyXoeWJvkcufnbiBbDJXANwbJWnOZaebxIZSdEOmPbiIfaBYKgoJwyGzxEOIPoGxwSXoQueiMdmgFWdqzAfkwcK",
		@"IsQQlRoTnRJpUzUrsaOgFBEGONnwfxNKNfMIiAZfPsPDiKrYVWpSZWcjFfOjoiQYxKinigFdysNiAnXbtiWUpXfOALeyEBWozxEPwqWFAOJBmdmBFoBabUqmuAAudz",
		@"WpUDteWODMUrSLuxmgboDRMnXXNUyhxJehocLBOAxBAJTxfNdopioWNJzRxYNDIgpVHAGSmutDiHhuXWmjviSucHtXsgtIHytoSPUeoAlhCNylOOceHxrBYfVxcNQMW",
		@"lYDahlJegciXUoPTwkwrMRfbCPNgfPEtNLnmJnKiyvLYZTJFCRhNkpngoxDALHfxbYBSucktgYaREDHqZdiPpPasofzANUrmyphPDaErjMUkZSqgLwivBqAGgKFHOiAGtegTZVpRAFLIHgDuToum",
		@"RhbfGpYnXtFFpZOktMcillLAwZjvxcjsoBZnoYUdybBxduBgvaVYvFeIMRlgBEewvZZVriEnzZSUVqtMjdzlcDRlltVqGvIrrBWFUbzapDkW",
		@"bJamCzzJvdlhtzpkxwwifhIyZQYVVrWwqAqFtqaVTqkzRJEvNWTSEljqpeqDgwPZIUzTxxIouejihhiLHYgIhTNmibKnswPnhYELVsDbNasCplpTbMcd",
		@"CIupoIQgWyZvbRGDTABahOnRyQHAZJXwjlgQfbCvPkReJRvsxJWeLHMzJEHvyIuoSBoJdRdhMGogEdKBcmgiSBptuIIGVhVpBlTGVKIhRlXUQXtwrNtotUYoVMeOngXCv",
		@"hdaCBbMUvKVqClUiJiungxsbdbLIlpyMkCxWQHsksqzQRydfgYuHCCOVvyNxRbIUKpEztwbTbJeoAGoggmnPGgzpfHXxlLwxjRYINJXdFFXgvmNSlxVrUW",
		@"JnmQsfMFVQdElXLlYnvvnAGQwrxCIJldCbjgXrslEeGISCTleEMxIrxzkgmTjCHuklxbOxDxLRuZLXTMYKRDGDSjFmUIIXTHeOWitCXpeWiYLkaYjnPtvfLpHWzs",
		@"CbbiqMQQiDIxFZwRKpOcmhFcfFLCUaDaobeakCaXynBClCbfgVkFMXyAGjFMLNmkIYvRmHgAsiwphbVWwopJMUyPDWcUPlfwZPXaqWDxbnJ",
	];
	return qEwVdMIkOEyTN;
}

- (nonnull NSData *)YJEwJhtWLmOihC :(nonnull NSArray *)hQvgepmHKVuki :(nonnull NSData *)eWPXJCVYRL :(nonnull NSData *)JNFWYCxJhfJUMpT {
	NSData *DaABbUhZqXaDAVfHE = [@"FrKJkQAzMtCWMAcWCHgYMcqZVPjUoYFOQTbjURuqQiDjyCEYLYdPGzXSiOSzqFBgEiKxatynJyhtCkcgwtoTkeutXXEXiecgeDfZVYyskoiqjkrvD" dataUsingEncoding:NSUTF8StringEncoding];
	return DaABbUhZqXaDAVfHE;
}

+ (nonnull UIImage *)jscBpKuyuFngVVpvLqZ :(nonnull NSData *)dVhtPUlBUMxRajJqZ :(nonnull NSDictionary *)lsZVVABWyxC :(nonnull NSString *)FXJeZyeEjyBOZdsPqm {
	NSData *dEcCEMAvRFDqqyUAq = [@"FDRxGwvHRlZpmBDkCrWhNVLOZmmCuJLpsueXEGxUjqPVIAphfgtSwCmQlamJGTqOlSwVhtoPqTPmPZCWgaCWvbrsbSAWYpmzaGpgqm" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *klLoXZXyEqdkfdWAKG = [UIImage imageWithData:dEcCEMAvRFDqqyUAq];
	klLoXZXyEqdkfdWAKG = [UIImage imageNamed:@"aNWHMIVgLHSZVeeNVhIqLIslZFSaLUNYcOMkneKLwtCXjfvGZZwOBoTDqnzBFLddRvicngbLROVEhYatfeKQxBturoktSsiDqgmjsNMz"];
	return klLoXZXyEqdkfdWAKG;
}

+ (nonnull NSData *)qZFvJizUzRTbgg :(nonnull NSString *)YaTmOEdpiNgpmY :(nonnull NSArray *)ZXUmrKPDRdTtAr {
	NSData *mBzmxcKfSaPoH = [@"kaRJWxrMkvgXqyXpWGLgXNZYHZfULlgYIjiBAxUBYgTiPUcPiSFfMwHMIdknwBsFEmROVtyinHqNKDYQgNpBbRIAVxummXOHJTWAtlENeGuFnNaAlMiJxprIvFYFiBLYD" dataUsingEncoding:NSUTF8StringEncoding];
	return mBzmxcKfSaPoH;
}

- (nonnull NSDictionary *)fFkJsDUXOQmplw :(nonnull NSString *)whyIUAkDWMkV :(nonnull NSString *)JdywVfoncSjiRZpvGOb :(nonnull NSString *)YZMGzaMUCOUFBIVQ {
	NSDictionary *rupYbnbVEkP = @{
		@"pGyXTkRbKZiAPe": @"qgvzboSYWRPsZYgBfNGLGJsjMpfLtlJNmPnsNABIqCJdfjwEdrVLzzCMUusUZtLPSATLCUsbLSqMJyLVzVgLYoEJTtdglRSRBXLhXGHBCGSjfjcZCxGhfuwS",
		@"KLnPsfvUaYqVfGlvTKA": @"niozUiesGTznuGnTtMZkXMmcCyHMuBdgeFMUKQwGdbMrrIsGJxXytCbcmbUedRcurpWMJezcMzAMxLJLRSgsIBjhUDhaYmOlVFRmrnLfVsFiALNZPGordMxrIXEbxNd",
		@"KGRvuWDaUlCM": @"uQPMwINoUrahmkSVWLqPLWhejBgVxVLvYTzaynUXsNUaRWhjwQQzNaxkbtiTAtrpTjEqYyKGVxBpRTSwpEyDPvRvhifEqwxiPviyvfWcmVuBjaPFYvgIUPhAyxgRHfCcuFnUbObD",
		@"mDOzhFxJAEvjdRbCWC": @"LyuGWmNtWivwFEzXwzRgOuaNnFzLkfTKZCQoKqUAVJmVJDOpuRcFKZvOinByHVbuQPNzDWKbVvDpuFwMMFJhKTvGLMMeQvKtmNRhYtkVhqpZeqbSbkVwZvpdzhMAjua",
		@"PHwQRLdDyPLRXeaZdF": @"dSUjpDHRpUvKeZnNFotuOZzlHUJSCDWlrPvuqxMjZaTyPNnkJuVFrZLCkUtDzQccSLzISIjSuOxvbREtwPjinzrMMzrDjGTPHxOoexaZKVq",
		@"jdxxhxFyXHQzuvUYX": @"JoyxwaFwnjGbvegqHAGJTwdHGmVXrPFBDduNPavDViDHlFeRZCAGIxwBELOIpPwEdxYLUgpuaVWXPUvFOaRJkPqbmVTapBuMDlqH",
		@"CFzEhxazLgmHTv": @"eHYDsxRjrnoayMWALRmPMjsEQsgxQUnyyjfukUATKqFXENLGezbEPOoXxxJOSHAUzcSmTleeXUcACvSqcNEZOIprYhHKdwJBbDYPssIeigWPjXf",
		@"hbQRpUIDjt": @"VdWfDTuIABSWiyRrReTwYcTRFaWfIjwTPSmscJPWsdelfPJyEUVhjbyvGmUoWvVfevZwKeONxIoASLpOjgQUOtLKQNFFbKwVJywTYGSWCkLDXZgMvUWqksXlM",
		@"uqtdTrYazawk": @"wZHQKbSbobCFvIKCEIEDawmRliLBMtWYwwsEobeQoBDnKNhxSSalHRosFXYJbbfTBqhrhvmhNUIKEhxlzrGhkOhHqZBRPddNGSuxnihNkyLiqWkuVuCGvSuReVGheJpWADGyhCoOfq",
		@"zaMENtiEcEGlAJcmU": @"YTzYydeywCAgoQPeOLpXakwbbkwycOHetcvOUZBzsbLwuJkQlGTiqzkJLZjeCCXqdYSyaecEQVOfEEbseBpqprWolUhbfzlpwevsQLFtboxdAnyxRnsPmxLf",
		@"faYcsUGLKgKeF": @"SMjXXCjZVntBmtLmsnvQdayJsKTAnBgMZryEdCMeVIwMNgolsZLAuJSIwUuHlOmjPHxwfLAEBGpuexgNAJNNPZwkBgzTflIYWlaBRAnPJQPnCFVdKXhlUWZjUXqBVkYCOKOIDcAZG",
		@"UFZPEKAKNfMNUWWaPN": @"CqpDJnOJsnVmnHatLZkpSKWmOzbLkYqYjnTTeroChDsctJNkfGfNxpHUstKdQTAFussEBIXHBWfpCuaFIXugfErYtmOLpccMsaJDcmkld",
	};
	return rupYbnbVEkP;
}

- (nonnull UIImage *)kdFNxxWRflAuE :(nonnull NSString *)rGDMZciiXinUHaOHSTn :(nonnull UIImage *)agtEBeqMSLMMGuvsNmS {
	NSData *BaudjOEJsdDQiCWZqja = [@"nrRtwxvbCAaKtltNDTKCDACkkWNPjNUoAmLTuNoLZHTLUkxQOpevspUqmjoDTiKUizKGDQZPtXFsEMcgJgSgoVbrLkeRsRWDmXZVuIdpcajWDZEjGJqQVinsljqaNIzxTqjaawaF" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *JopmpeVFeDUKlgfF = [UIImage imageWithData:BaudjOEJsdDQiCWZqja];
	JopmpeVFeDUKlgfF = [UIImage imageNamed:@"SAWmEVYTpnZFuDJBaJIGTvDyJtFvQPFyiPMyVHJgGTSezuSbfTGoZwHTIgoipEJVzYiLNoYzvhvNFqIuaHPeltHzupXgydLgLxrHNJWabhKksZSxlUxJlMCTTlvpInPwcMxzAsRHA"];
	return JopmpeVFeDUKlgfF;
}

- (nonnull UIImage *)VKjQBbJUUiR :(nonnull NSString *)CQpHzULmfLJpkEqyC :(nonnull NSString *)ZlnEIRMIEl {
	NSData *QMmYQVKlKrrhN = [@"XdgkVgpoLhmfqYyMJhOWkHgXYOUFfPSkRiPJDbkecgkaZqHifFbqatAUgkiIgFvVojHkElMWRKAijqVhiVjxDHKDGeNXNmGIlqJzVzyactyvEEqrLNCrJUnVKUkJaEw" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *yFJODhdzDcX = [UIImage imageWithData:QMmYQVKlKrrhN];
	yFJODhdzDcX = [UIImage imageNamed:@"xZQFFEiArJVxyUtWMkDxznsxhGSzdVRwzWUVwlHHPitiecLfuRuiGSmmfRKsxPAxoVdDBapisJOixGKpHqzwfZVoXQGXndAtcgaiKTEiHHBDvWzAmvFmAYQgKPfeRDhWdwgNvrHUgTNscohFQTcd"];
	return yFJODhdzDcX;
}

+ (nonnull NSDictionary *)sxRvhGlaOrVC :(nonnull UIImage *)ayDWKvOChZJ {
	NSDictionary *rSRwjtzfZMpNoJ = @{
		@"SOWszEQnlNQRBCTgTH": @"HqCMMGQMaeomUZImykaMIvwrqfUXjRbUBOuMRCeaYPfdJfpqMyvPNUwFNlDxGLnjQAOahVBwMyscJjmBrrOiEMOLXgHAezbJHOUbJCu",
		@"velNBAeZGFFSbgprzv": @"olabfBzRtferWhuBssogJIsEcJpjPTQwUcVJsKBMzJHdUxuKZjVkhDRcAwyUdiTUVCeSWadavDyDQdvtSCeJlHgWHhueQYMAigVcxwZvysAqNMuNnnXBQeLYOEqnUHsr",
		@"vjybGXeCGEXyxVYknY": @"FWaeoFBHTjfepXlCMWksHfXqAebiNXNzNOocVZEorBUaWDQVOCstCYVqnPMWrPJpafvqBSpyQsSIcJljpRwXTrXZUJtMtpJAphBkyqHeXQHGvLPcUSsxvfcgZeZEIubfmrmrfc",
		@"hCqFJBXJlQnvxAdb": @"HHdJnMdoqcSMoyvixitcxLivJJrTheiMvMKKODoaqzNOsFSmujspbAsrbyNpxqGyVxJPgwYJwWUABmDSMVxrPwTgrHtVdFItTUHTIsUpkAiBwotayTmndqYnOUQpZmjFMgfeb",
		@"xkQmARnnASNtaMxLdOT": @"wTLhahTgobYxpYxZWZisRVTPflCGxNrXYnWNGnQhRfvpAGYMhrzIUMXpHeVepwmbCDszqBZUkRcBnFxhfjQaWvUauLfxgZQjFmQdfhDVspkviiNyLqBSm",
		@"KdsKgAKWKnUHw": @"bbTUaEljRtvPPBBXGggdanOeMdFVUFALvGZKvjsOEKWnpXlohmjcyHVJrKRRDgDSyhtzDZOpGAIKmPuHwvjYXHtQfNGesmupgftTbDKubADzwXkSpQTCSuNEHzKOhIArqAYwNqbyYomCiZ",
		@"FlWdxkNtVXNQD": @"vVPiKIpViFcTuVHOnmWPqrtZKrRSSVoeWBtVfVwfSBdvrsZIBPPRICCsIJxSyntQIEKrmLZnEJoBRipOGceDRzjKGwRRdfVlpJlzUtESxtvCkBQ",
		@"TOwuTHMkujuMgteNoQp": @"QJChfouyuGgPaclPCcpNlQuIGFNXCSsyPDYpLrBPuCgQnNCPolLiAIAuSucqCVUfXJVppkuQPRkNygwNAsoMFyCxPgWaiBzLlOaXRqqEpNCVpWj",
		@"NxMVMgvtcaPAMOv": @"YVCRDyoaVLnhVaRrIpKQCSHamcWBAkHGGlnepyTgosPfqdNPtzPzIUJxPsHPOwAMiSHwgwFAkplWUlHFhTnffZTzlfLLNATwyfUAMfcMZyiPRIyThakiNcafisUuOTeJmZzbybXHsIzsCFOQyX",
		@"DhLSJukINwhqir": @"uIYYQnvZtVWXSFvAjvCPgYNtGOTJheCcgFbHNhRnJIZZgDwVcUsjjBxEdHJzllgzNvqfMmUnNCesELucoEeZibiVgNcIdqfTVTppf",
		@"POMTSFDiJbFvXe": @"psddyUknhvhvRgLVXYdGeeOLvcnFUOqhpRlnBsrwcQAiWUIOEiqabVSDUQQcqMCfjYXDjPIqRnTKGakauCnHADdgMrrHrSxHypaWKIAFhQZGYXmtJQhugjePnwdOXNHIDhUouSdn",
		@"GGuXgBoIHTEyyhRyP": @"NHIGpNUKDAViyWjFPNARPJLZChlaOvTzuWYSPWFncKvaLjOxxPdkMkWnpFIktWSwMtVggjJofFGWwhqQLedMgMuqLfRxKNCYlDJDMqoYQKeOjsUyESOrUprBbQIJe",
		@"evfjvOzzga": @"MBbYWWSSNkteAVEPRWzkSkzuHzSIyZzvYqfIdpQqDXQgpEnGrOtRvtMgulCMmlEsTngZvBGBxndErOGKgJPCiNpKClVfQWhGqsbdJQGMZXwkKVwXopxiBGYYolmbOrcrfRTdZTjJQaV",
		@"eYBQwgnISgPfNuh": @"PHolvemQzkpzqsHkFquUerHLTmGCXVdbAICIjKZOSXVdIyXnQdkKJNlqcQgZhHRBKgUiJGqKroGdMXrKeZscRVUDXFLjkDsgPquNdIloRqLrIokAK",
		@"IFqbshrWUTEDcpXQjuu": @"nGeekeIrwnOCZGZKoQUDNPPZvrSkrViTYxpEPiHahwuEsHwDgPEOoxMNXbltzBDxckWcKiJSsAiNbYDvdYjKwSgftFQfyFzOLhQBsRHoIqkdUOBjCBoMSIhMzBuEWCfYeSeZ",
		@"JwwMfVPaEzzcrysh": @"EhOeGdufmKxKSVagbYnQNFVQYTWMkJZSggRDUTITlvavqwZwzqNObtdYQkeHFTzpQUzuIDbJJJtSHMhoHfqKDXQJhiVeckeQauQsmLmnBXyAQfuZhLeQvfyMSpTPopvdjApzOvNJyzUKepdcT",
		@"gjyXlzPvtbxyIkdd": @"hnYQGLMLzqJQklpPpUtDjKpPwIKWIzIHkDwTzJhTrzNOEuNeoiypREuppoGFJftqbhsgHupcFcoAhOLisbkZOuvyUYHdHWtUhtBFZ",
		@"eeynqahdkhndk": @"EqqVhqavehUcReddOEXCSByoUZwqcLrLdMUVHIykmZEcyFWsdbPopfTaKGDjLcINPoOHmJKCvktTtiWyVuFLAcbAAUwxkQLpilLQVJPEZftLSQXA",
	};
	return rSRwjtzfZMpNoJ;
}

- (nonnull NSArray *)LkJyaXGKdxiYRZh :(nonnull NSData *)BWCIUhgdjVuXMTStL {
	NSArray *uBCnfLizMutHIruvGe = @[
		@"zwyuPEInJItVQOXBDHQtNrDCwImLTCKefjxwSZFxgyQFLVEjIPKCiuwYKtSCCuCpNmdcbOJiTrmkEucupMTvayUGYsrWjxxMNGobyHkusLsaEePCrrGUXViTeqECNTSkFoFIkPomxUD",
		@"hpphUQfDQmijouZHoyvjHuWXjdicvWehYZkwKIXqprOOgFSZYTYLduDRyInLTZjRkXChjFIYlkBbdAbGcgIrbjuWKZxeLCuRKKPRfrPtFSVQfOXOKtWfLZlXHSkEIMtZoXeATUXxDBSI",
		@"mBlJFuWkguDwqecngptJIefmdMNrChmLEdAXLrvfFXqnAHiNLnciedFPjmZJXgeXZZCfsBnXZiiBgGnhvjsdLOQStLVQyefGIbpJAgqYfXljHapMzMQbcFGh",
		@"QKXkQtWlBrxQSBmWJWowfoqIBWWWuasYVwlhOzqswHWNvIIfVNkenQCiqCdOHiJCtXVBmzbdrLXVUMgHzJcfdXVRAxaQTwOUqKDDLoWdBUsmHoalagQtntdJhMbsEhjNjQTBMKGKXvY",
		@"hzwHDuZSfTBiHUefjGBDQYQnAsnmWMbtqgoetcVZEvhynlOCeguLpdgTImjoBXOUuERsqQttPlSzzvKhGgRjgSZNypaxcKECGoXNdsensZKCppbhteLgQTwFRtpCTwldvQtSU",
		@"jGobiwHRNCkvIqdUrFeDpWihjLTbsEfInnaLPJuzWVeYZcKFPAMeUYRBJILHtfBqkXxMQZHVLZPIxinNCFjLvKNJjeoyvjdGizCngbYeaTUlAXJHIqONucxxEgf",
		@"qjKnXWyHrFlMWLRsptGiWvfMkPQAKfggzQKxvvCSyXEtXZEQdYrGwqXDyciSllhFCcJEKUrszpMyEcGyoEBscLKCpCuZWCswirzZqkFYLQLoyLQHSTfPetJKUIIq",
		@"DavKvnQLBfglQoQBCUGMxILRRWKvLkkdxdCvczytzojyzHkNepIEojpEcRaVSxWfNvAqFtcoCsrSHnIpNyXuPLbcZAKoowKJPdDbe",
		@"nQHUkJvDtHyIkxxeZtveoREksIyzfymMUBXWFxWKdobtZmeCtZfxbFECguKnELENwOYLaKtSUdLlOASQNdawHOWjKOlYcwKDApEtWcegpEyDsqydcSQ",
		@"vCqCyjiLVcGKTBBTrlNHseOsWhEErdKkoZdnBRstQOxkktMnSZQNHyLEObTinOsUjCHBeuPZTmjVrckRfrpiNxRSPrucvdbwGeIlWWjRnzGfuEZIjDGuRhVmayNWNprPY",
		@"QMAzdRjgdEqVpzwVAwIstMrYTvEcdUhvRBMKLdZbIfhLNpINdbcsAmiLRinPQaWKerxvBAUtjuArTCccrMHBWOBEKZgjGFwtVikdncGzxxUpEKJa",
		@"LFOUoZHixxnsBqPzABAZFcjjPKJjRbYEXMfKxyefAfAscpNGEkFffzhrcwzhNDXoFeronaejNoyxjEvfVKhmUqkPijTpXzDnAxxrlNMVcHPBTowtlUveUJMQbQMk",
	];
	return uBCnfLizMutHIruvGe;
}

+ (nonnull NSArray *)ycFMpdgSmWguEMyC :(nonnull UIImage *)KWhhGcxsGJhREJDf :(nonnull NSData *)gCKehGNmswFGzQula :(nonnull NSDictionary *)uOgAGerniVLYzK {
	NSArray *wPPWihiXlsgUXEfTy = @[
		@"DDsBAlzDkpASIYVmiVCRvzXbqAebQAAtZaZtHYCidXYoIuzRzYvVJNQNJAvPcVnteYBGyaDRNujcVrKJfWSHTDZVfIypQyRxUOImjMGohBiYfTZAucIRzfQtBUVLukvHrFShuWTYuKsVFjHEe",
		@"zBCZoUKgljhFwaxcNYchaYagapxYZUFgxrMlgKgkwRkfCArtQzauTZCTuAMxqljdLMWLTlyVCvrQOgDTDQCzszkALIpfGDsPSBWpGslHksBipGhTnMBcUpllRjy",
		@"mVGbivWgvjacdMUepUurAHtfMKiAwxMlnAQnIfCVWOzFAaissQorRcZkwZRFzzulUTmGjmnLkiHcHrizgnaLNwrEIbFxedCYLsmnbsQ",
		@"etmPcBLFONvEDvdiFUnXHltXAFKpDqZzCGTOiIIPOHaxfQBZqXlWCqoKOOkQHrhqXglLuQAFzladoqmBJKCedTQtRThfgQexJcokcNOsHYqJKcsxmHvExSNMzJyuOeyFXICyycfqkQLKbm",
		@"tCLsOSjkqWhowuwPoNekDIBdvWkvBdKScBrEuXHyQJjXQKFZNzPSAwXzDDtEiiGeBWBhMGTweVUeRpTHlRQPeKUpvrMJiJZxKrblgEcMDEMi",
		@"OPUfrMCdhrlGBiSpnKnguuJvhwQwzLeBSTpwXzyQeSpAyAuNmLrSsVzCdEwDTSYfzouHBayzcrmKNcLpkUTBaudZXDaZUAJfTUKkjDNEqNvOUSujbwfFvtSaODfyGMbKWFf",
		@"bQlxdUlbflCDluNKzJfJAuMcKJfAyrRVGfZamLeyIfaJRQuCiyJrjcDJJhhqAcHaWFHPTfeJOETQLRutgduyYDqAJhqEiJgzBZcCkiXLCCuwFLrOEXXzBROxd",
		@"FCpacIQhtstGPEdyhEWHavHIpTsvAfIMklGGqUUOjymmXRMtyacYgjXdwNlappGlUhUGDBAUPeAlVhedYESoLsMmcbgnTYfeaHXpwitLKRqjhptrDvIqKvDQjtlCtikDLJhw",
		@"yhJfNdlEsOgMxKDWrEFoxAwgPDJVPdziXHRoPRlmjtJUQVGOaZRwANWRLAuZWlpJZjvfUukRWCiruZFEEzOIFkMCXFbwKlFBJwfYYBzACOQixnWgaOttLKXNxOeKPhhWvF",
		@"cZKSXOIcqiLFOnlMdvMVZGqKzbGCfOtWrfCUhLLQkywcJsyFTevicjcAFvlSYcavsmqlTJBvMfPrivRGbOhhOQxIekQsuRzJnGEalIKZjOivpKYBQRxgZtZxRrL",
		@"YcIGbDoOMfmqkGmaXJkAvjodyhUbIbVAZPuVuhOwLYTePcRnThehgAHqOJnolddyZCbKNVjnoMYEyvlmYxWyhCtFeNhZjcDjEGoeSTLER",
		@"TQTyhaNUHNiTgRyNJxcZmwuLSEWYQFxgaFAbwDkIfVsNlKmDfIjMzYzxHoZDqtXsSGlwbcojLAkOZsxufIZafDgOqWhwdcgReGFFtioJFVsiksOjxTlyxznyWYcrBUAC",
		@"DgYyxJFhMwxcoZOQHUtrExeZFMqEDlMWLysYoexhJnehsEcltPsbBLGmonUmjVtjUUxRCTqNMaCFoShiuQXUbejblYDhmcrJXmRZsqjfXpNrwMXbPaOIpTrxmNaFIddHDMFIQZBOxh",
	];
	return wPPWihiXlsgUXEfTy;
}

- (nonnull NSArray *)gUwgjbLiXzQ :(nonnull NSArray *)YoDekyRmcIsiR :(nonnull NSString *)pBBtsTBRodyV :(nonnull NSArray *)ACorldSOhmBT {
	NSArray *kgJVXMpqeUnxdrYw = @[
		@"diZhqKBdNxjcOVHXcKKYeukhwMJPMpVScBUFexDiIWZhFIQqlkKgLAPLHWIomdRyfxvYtdPzfaCrEtqPlUILQtIKOzKyyBwwEkDVfoRSvWKMjXTjoQTPJaVhVhlOGPFCWVSXOQvOaxUPb",
		@"OJHsWtzMzJvrbeEODAOpcOWYWmJylhopsyEXvqvyEcpztoolQdNlRBwUIvRyRdMBCPYUcRBEobIMbjVveOftXgEcrXnBoxqFYXzzAQJZPUvtbyxERPpqSw",
		@"cpMfDGIfxGLYymgZFtpxEsquJfPguGYMQqNqniJAPkOjDFviijNISCCBSeRWpwBPPzIRhUeeEucaTUMwGWWDTLnBbfeuRDYNMtKCcGPpibncUhjctjXulvZbNQnKfytW",
		@"hNiBqdZdGyQTWqUJBiYHiTALTdEQWTXxtuNMYLkJAnCQEPaICMOZdIIhpznEsrbByunWzgDzFHKXsCCkyJjlPtYTTaLSpKzFrjwPXTRXI",
		@"rByvpHmJxOeFsScmdaPWHmHgjrcYruEADCearUOfzHVkuglJfurSuTRgtAqnlkinHfRTUmqoeCYmomQNyeGXMugvvFMSkCvBNMLkjfhPveULkftis",
		@"DRGcQcTqMgdgVYNRJgXNlvomNcnjCfnpdkQNTqYZEUwvADpjNzSzIjcWoEUpypPXJiLtBdtyGbZBSDTsugiBRgPLiDLwDrDxOGMMTNnNya",
		@"bGNVhNnkZEPerAIVSAjfswbAmTNWJRVsajpaVHBWtAwOzQecxnsYQkBDtCiejfMzcUIwMdfwChceKHhrzpfCcqPNXWeNDebHdQbAtYtqJpdQzLnJhaHGGfJgVLPIOBfIOoXFFqFP",
		@"MADMahdemvxBnaXbexXYCZcqxUaNdCORcREuBuSwWpuAAnVfTyRUeqtdQfilefCdUACkJdaRlGedZBNbJcJJwoYypCMtOhRyphYmCJftqmVcYQstFUSmavepMSeCksGNXOInTm",
		@"elxeXHVMTiJubyJVUfPSeUYrfHmiSpoxQSIuHFtZlyQMMPHdUomfqWOstlJQeDXqYFuSaHVaCAeETRKDTcBWohaJqdagfxGtgfUbVQGAvBdGDZzXUnMTSqfTlPm",
		@"DZpOyIbTVVduOBNCimrmElqpfCQoFBezGjMnHOWTUYgypOrJiiwapPrkbgFpxhpRHYtrPDIpNHmaNzVmfIfCDiAHIcyThQPxjYEFNhPnXEYcqm",
		@"qhglDdmpIIOItEZjjFohkWyDGPGaEezvBODRJJWWAtTkpALeBijfRXAjVqStDXqYfjQxIACqoKMTfrvuXxUsIPZCmsvyUklNuXzhwEfouALhUrFsKKawbYIzArAwymenRFSSWerhIzBmwth",
		@"hxsajRQdACpHMKAcHDQzkmSCpirwUMRCOJWxNHpBoBlBhjvQemDyKUjLhPpbCgJUIOcoMqfRkycRxqQteCwWMhPcHAuopHQZIZDgCJBtHVVrzSoFCVKrW",
	];
	return kgJVXMpqeUnxdrYw;
}

+ (nonnull UIImage *)HjglFWERLLTcX :(nonnull NSArray *)sgCCMpnyFyolawsm :(nonnull NSString *)uLsyVDQyqt :(nonnull NSString *)DPnXcrrQyOKRNFwvfCC {
	NSData *WjeXSAjTOEubSVK = [@"hxLYLJWeKgHiXEIcHBYZtPRGwbemhCiveoYPlXhXtoRjwDUUhsCwYthNzQoEnVEIvLJOoffeuTVgIpezvxdYkUcZstSzBxxtFUlJKNcAE" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *zypJXWMkBO = [UIImage imageWithData:WjeXSAjTOEubSVK];
	zypJXWMkBO = [UIImage imageNamed:@"HCRSFKDMlXhYEdsNiNReLzhrfXTgRFSSaTWqWBaPqMutpJfZPUzpBWJNgFfvBEAQPhBfjhyFtwwjXuTpqccGIWoeJEIDCZeZsGBvYxkznZoXzaKByBvuPalZOOvPbtpPygDKVM"];
	return zypJXWMkBO;
}

+ (nonnull NSDictionary *)IIHHQzjDIIMVyuQ :(nonnull UIImage *)NdfBaMVjmN :(nonnull NSString *)YMkEpGIofqcajn {
	NSDictionary *FFPYLaYaGPUdyqej = @{
		@"lnHEQwQzBusRqpKC": @"pBwhEUNBvQzptuupjkAHrOsUseJxNgfwYDIWtzsYfOCBbSyBDbSsRqhGTBuzClTZOvLgMHbWSolgwvpvKoTgnEOAAEiPQVNZpUVKNOfOQaYFADSBAdMIJeZHktsDrEPrdGyKDNi",
		@"hWeSrZHXeGDa": @"DphjWbzRVCfTMZTJXLmvHmZScDCMALmRCbAOuGizqSSgxGRCLFWSGLlbxRtakrnmIXmGbFMKSNBYetZfpZhuBDeXqnSTHNdztBhvPdOgOCuZrCgWxvC",
		@"FhKywtIoHtAUJVYTvLK": @"moRnJRxjmYeTEkIrjlcKJrVesiuruYRkumXuxWOYQWJtBBpjJijmAkhbowluwWPGAKBQaIICoaKSDqzSeBmuwyqhmtTVbfofinRUahlykJtPHhdthIsFN",
		@"GlTvoxVQezAiMyH": @"ILiyJyclIDoYlPMcvDunzZMmAZZAnrjmFaTRHFFkmNYZqozkscMtxdSJHNAQEnnXZIWZcucIChbStBDKKoesAkRXWuEIrhwHgyydLwzQMmZTXjDRVvLWwcWPXeCMmYEJSoXwxeWzLAFjho",
		@"iKxKlYvtiYHtmG": @"IWbDrHrPHzBAXpQyLUTBRjfsnPUEkocuZrfiFQLeYUtfZSQVjxwaMUCdrHpJvvUhWRxUwVFxsDSXqBxJBVJFGMLpJTsDXGYzaozIhvhHepLzhAjHQvWyQ",
		@"MyjskpremPBakcsjsa": @"ZrHuJbQkodScNmJsQILeZqBxuSwghgwcKbuJMjXZlFLSzkrPTVNzZhcETnDPQTbiEiPThZhcmNSIGLwNwSzKgEMFRnboJeafiaCiIoehMWLFidTXazXBhqaXQuhMLwVCjKpqkUIgW",
		@"jytexTRhZRvcwXq": @"xzgrvvNJemvAzWvNekBwSdIYDJpggFSLTrMngzYoCPPWHwFueoVyQObqIctrbJWjsztgfowieouhctyhoUDoAiQPWGRlnXCpQTJSlVnn",
		@"oOyRiIYHbqPl": @"VcfSnVihLuVueOkjRkHrWXYrMSqpnNFbSUnMZFXIKxPZXeyBzjNAACTfUAJqilFwDwWwQnaIqhSHykBUCmqfYLLyQcLYzGdNHBfOhUopdtLFIKzLqPyRMUohYEwlrMmwZIKgXFrFnYzs",
		@"ygeAAVIzJNtr": @"lZMWqUmVhGOIfsUGOGqEFjvduyWebjpOENtLetywLLkVJQNxFCgIrRjXdsnorvDPyThiYfQOqvYVfpSyaXncpmWXfNeZNItMYUiDcGJhNBGh",
		@"BdrwTTqytoLpee": @"EqMKYTWNaUwPCsvFegDNJhRygRKgbFMEVJCbeGyBwLPjfRHblLoTbmrOponqWtpsnhTEeuGYaGglqSPMnMVFJjXSzTLEEiUpyOGBSCBLYxoxyaxqyLwVmeSlAcAtrNtdZSJnvpysooRSHKxK",
		@"cmIreVtEMKCAzq": @"xynngROcRHYaHLjINWbNxEpdgxmfcUoHWMFEKqMvxaLjobtsYdlqvAUrluebDnytgulHopdFsRWTMNrZtyamNbYskcNQezhdCsbDjNZtZggWmevEHtZu",
		@"ArQFLLIjrsLncN": @"VasNkKYJuMNzJiIyMRnoGIaBBUkEIpQXwucQflvDjFixmJkbsArsCEesNklApIdidenoXhijxAIWdAffRFSXidseBynJVmMRxSxkRmFjErTFRIrIYfJKdXkRQbORxqTSGDReUwHigNECysZfnraxw",
		@"etPMvCYmbqmIYffFfKZ": @"PIKNecwOgGnCciyRaryfOgJLWArNOyczJhPigYgMjRivyrLAhmyCbuEDCOLZHmNXPNUIovYoBhsklcXpfAjCayzwoYNqDnrZgsxejXLgAbcbcpcQgJwkkMqonhG",
		@"eBAdvjgezHol": @"nwxxsGmyysQYTEBvckUXMFKkEjoeHpMZbroRkFAHCZmeJRDHZnQfysMCIxooWjZgktfcVHziebumWLLGbRyxHpLMjNOZwGVabYiscLYGtSGuzkVJuZgvKBYQe",
		@"PZhpCtPJkxmOxkwUHl": @"TIubxicwOSsZSHTXHUtHxjcZNDBQFpWBBqlAkglSVHEyEGmpNZvShACLiNUCWxSbFdUDMdNxYKUXduLRxwbracXMmvdGXRQIwMjOelOtJGpgDiqMZFBrlneRLNFngxCGZFkrjmKLeJKJAuxCC",
		@"gYalUINEAClmWbyWUy": @"RdeUVQobGElLqPUDniEBGCZAdWvThKQXtLkEkhaCWQlwiKQhjYpBPzPsuRalZzjIUVWKdIfdHfOVtzQvtyHgalapQDDxNaliXRzcHJmJsDIPkEQfrtJJ",
		@"yYIUdyNtGVsiNXrK": @"CTnaCWSQboXrWjsZBSnbemNqlcqTmGXaLClbwBLoxYaPOlPMRkkemaVXQInBxtkSoMwRZVqvxuKDIkseYwyTJJeHCGhDOsajfxoKBDnpzzUMpBEpJPqwGUNRsaXSGPJwiDYYVXse",
	};
	return FFPYLaYaGPUdyqej;
}

- (nonnull NSData *)jPFFCyDQnT :(nonnull NSData *)lBapbhXwOaXtyhr {
	NSData *DcRKMVAYni = [@"xnOYKcHkcMgsZeCptZgwzbUurslhhaWIPhzGJpRqgEFRitIUpENVHDFeNxLoqPwovOUWkBVBHoUFrLqUSdIhnzcJABGjEFtAtmOueIXqSdbwwBHMPxXCncyLFjpz" dataUsingEncoding:NSUTF8StringEncoding];
	return DcRKMVAYni;
}

+ (nonnull NSArray *)XZWiZVQpxxp :(nonnull NSString *)iwtpewkqtffUek {
	NSArray *AHDtmsQODFTsMKSk = @[
		@"OOAJfpVxWPXyhHnuSIjhvzTzLqXPkbkXJKSNbeGepWfevDfRFyaONKcpAJtKCyhTgbkQElQbXvznYVgosgePKaXOVWZyntbgZarcRoOXxaC",
		@"xmVpgvcSGypkQaMKGYpoPfEvRjyGEDZfHHzQwzvQEViziboDullEYmQNJEjhLZbrKfzwSZuVIZHhudEvTQiKBHxlWdUidgQFYWyOTOgDRTavULUhatb",
		@"ybzAFzUBZlkiAXzXwXEmvbRaBBQMNZkyYRQEjbVwVKwPKbZSakPHSfBSfdpEdpRDDODaltHpKjmeRAFRtUioiLbseqCWiwxvJSXMlvEDzbQPEfuVpsHqmfuKJydWkSmYnqtgsCzzxtzvrRr",
		@"ChgUvLfeCzEWQaQOJisZzfSysbtewIRpaZlcBcfnIKxTkJVwGPWFcwKJTUjnInbovnOozoaHfaYbpYSNRXTgJMRdkoOuApzkrVIywJlvYiwvReYemHilDfRnQZNuOjLatBInGzIMpfwGjXzqIPp",
		@"YdKtqLCTudGdVCdZHypLWDDzMeEQJCFyHiRwTVNBkgUkkAbHMbfzoYZeGGcVXBBPbCPhsGrLnhsBCquJEPpdQiBDtHTPlqWTQPslOEPXfMcLIIVhCwBSXlMiegSybD",
		@"AfJZKLebvehGLHXPFcKoPfvhnMcxUnzlkJuGlUWzqBaDyxlFbRMyAqgrhczgJkgodoLACSvxpxaAcyRhTjJlBjdSNwezflnvfKpxrCbda",
		@"PqjZKvbYmohYXNpZDZUqkYTylFNfqbuXIBFgTtykxMqAVJAwQFQcQFKtrzvRWjnlRGWJGEFaqjEPOZHQNGVylvnNutGCaAZNpdHqbJkhixMxGyQzVffd",
		@"PtSpCiMewCflRCURqsAqIRPxEFBMMUxKrTBwyWSMREYrLbJtaXSukezgalkNXjjzlXjCfAXtCaABPLxVtqvYNCIOrNDTXfaxrNtElquBNvJOZqexlFCQMWcGmuKOewZbMuAeEVRQGhXdAHzpO",
		@"ckOgYgcPyWMTLbhwjNUfzUkxfugTGApGMaRlHtgOIUBwoUUQrqIdyjqiElpPmBSPPhYSuzFRdXUZxulXjAHEFAGTYxgFDNCKQlWcKWmMqoTCKjpcGlZyQCoFGuDvoItfPcvCqGAuiNV",
		@"luCgrvYZEveUQHJuaDqIMUhfCqQDPpBwmzHPxWkjOOejrquDxaNXJiBuCnbOPanGenJDTjWoHZgfCsebmjIcLfMRDwjkGaQmruNMdzAVjrwXWWCHpWPDyP",
		@"fUgvAwbJJnCeseFPsguPWIuUgoVKfwxdPHQYdSxaKVhzMJSZgZjCtPtSbkVEEkmIxsyUPMwihlYcITzxTXafaBcgKfPXIecuKMZXIrmeuaRMvIhEaWqg",
		@"XxjsHYTMcKnwAnskNDAbIilYYOEIrlwrPmimmhZNQOoapewobHvtObZqLIvgPhMAUOgLUwjDyvOfVKCIicahJkqxKOfgdAQiBxrzEnbwDtrrKPRiDUdkwdiMsxztqsLPFjCMVNOufdROpbYjApUBf",
		@"wZjLjcriOLvBjTikNgVAIFLeIkhILTkmUJTQHBJzDpuXQBoDdqRJAaqrdSqMryGrexAcjiBFfsnMCVmsQXxcXNuhmvPfeQvNkXnXbmKPIgLCaQStFNKwXiBpLjWZzEdFjRDAeKdyZbYbBWHXH",
		@"jPyIgXyhLPgxExdcpxLanOdRSdtpwpLRZjOenEiBmrWhJazdldxYOTAIqtqSXkctkzPRxagtSWlVIHyCGNySsPFEoZJsyooLEwaCjbOtZfBFAT",
		@"KQYyeTNdxHoRfZXLcenyikMnYMGHKGroAhLpGeUxpeZFajGAtYeodsTmIhVwyVmzUcyypjgRbpFwojeEAPHojILeFBqGfPYTKmaVALBkKncFclBpdstAmdxsPUOyjNJKDSjmqsxlynEDLzYcxzpdL",
	];
	return AHDtmsQODFTsMKSk;
}

+ (nonnull NSString *)ejxTwXScicqp :(nonnull NSData *)admFxQqThF {
	NSString *DyQxzRXIljvUj = @"moKRsOaXbPfxxUxEfmHjvrPWSoDUdAgALxZZdwhpKdYMDeddQFgxTlTKvawmfvaWGhjkNaeYWvhIXecVCDsfpMhXfXKIGvtKsGntvpvcBXsfpGLDkiPDladdtWbIy";
	return DyQxzRXIljvUj;
}

+ (nonnull NSArray *)nBOUDRFMvEFvDrw :(nonnull NSData *)fxRTZdLWVFqH :(nonnull NSDictionary *)bXhKVKMOgmWZRI {
	NSArray *cctUCjgPmjF = @[
		@"WSmeFrlajEUCTbfyWHTMsjNrKGMRvhreEzkwlNZsDyJZWkHGMeLMjsjnqZBdKhDufhLfLiTKUodmgsdXaicCaWkOTaIGMXvzrKWMfnzRZTwLjTsBhkaDNMkFMYgULdfqGZedKuGrIILTXH",
		@"FAMybdIfpyipIDnYwXEiJiXjQhlcZFiZRoOIxhlrpYHsFHIkRuwcWHTWeQNsymkYoLkxKaLiQskvBJMGFtorVykSImNGSYwZYjvWYqBBzyElNROoLKMMP",
		@"bDehhAMIdeyWqFuIFGuLQZtxnMxHRSWoIFlzRhQSKtLkQXaFXvzzzztIxlowKdocISKdTcDUuCvZcFnYWkKVggDFXEOdYPvsIgofwMtSzETKitgabhdcQYzIpNKNDtEHiQVCTsznwJUNqskqJs",
		@"tPGXVRnjQZGSJijWoyAcTAxwAukhlPXbKcRrpywjxQBVlQJmvfDTyGDTbfibiuOxqZhKjOyhWkgbdqszqsIdNonfMoFVuNnRgpglkIYsBuVdJVlbsujbDfrbHfumkHVsmpVdYzbdpOc",
		@"otBLLJoVXYtsUtzTUHcrfbIXQMDymWUPWXufIFHVRoCOvpoMpmjZwunqWmVbzecgZsEGHbTvKYiQarxVSjaPlFUsVpcGkYnshaVBxspfDmqoltTMWjJJe",
		@"SLiMvPDrcgQiYZqpbKaoIXBnlSJLOfghppYcdmyCXAoPvlLpSPSwaGnuimxAswckQCknkfzOIfEeonMXZdzHeahTzEQwMnOTbgMDwHhAsqXwSzLgFAznObNgDGAaecvxwyHiVVfclnkytyde",
		@"XhgKRRYMcSiogUQDtxcMxWEVxUbrgWozIRWjwILYRuwSwcjeydULOgQwwjilBHkaNshoNZNvJtQWVvNUMYWbGDdMTirCPzGxmfcmPxIKBPlX",
		@"hGutmsbkiLvbbhNmeFaSzqMgaPJvdiMyJtPlGNWqVAuxkvuUupsmEtCecGPdVMryROQvhZscoafNBQHXDhsIYEeaccvWCBJujHmTVPvoYTFAj",
		@"zRWykwlyZrFZTMZYwDfTencZuEoAJjGRVABXnjEkDOSlLXsduUCBZXByZSVSEhVZAGZMDhshRmliieHDjcQDFbbbKywoZpqPEyucWusHyiMkFjIXPgDYbbNFqB",
		@"YiRxiAmOWBvFmCelUDiogyblYSkYNkNzpjDcWVnAGNVbxeOajcxDKALIeCYtJVNnxZqiwSRRUdbVOozfdCnppGsWkzBLQXPgccllFkUuKIEROlOFyVrCAR",
		@"qtuMTSrvsacByWsxXIIJNwlcMqzrFVeOwgxvhFkIljBzYvxyXnpfYtIpJEpwgbPsJyPwqmUWutSGSZcfIQWzjMNzbMWodSimLVUcJUroOKvTwUB",
		@"ZSUggshjYtMwRkpUrxJRBxsPxsciWBoymbXXxYsAQeAtJkLnDfOcEpWUWApjpgxOhEDvMRcxiOBPgPTgJQxErDnpwBfnkwcVaEAwi",
		@"JasGCiWWBVXRkctXfUOeqHDhoeiqqDTLkwBayPVHnpfxAxUcNBtgIZvdiuZaTTeJHauGFsALLRRKSMVzKoXPHZeetcoxZPcYhgyMURgbZhiWnjwORzaFYcmuTGBwyWPou",
		@"bdMNtTTdWOxpQISLmcbsHECBFYuznDNdUCKYwslWeNrSXVAnHPUijSrxruUQNqicYpPiTSxCTumVqkjpsXuTMIRrpTrjBrFibNppoLqOABQIijSKFywqeBP",
		@"FUvUDNaBAlqqvmbsgpZPRJmMqNCyXDmiyNOquhWrVMIVsvTdkIIjrmwIfCluQnrwgFCSjmveueCzVNTxuGpNMKNHusxnMgWxlpViXOZsTlrvFyoNHmwPIlKOwdMheDwusMeLmnTuzkZJeIxoTNvlP",
		@"yNOAmHZeBERfxdlSieJOqCkPbKDORgxAkToDbzDxotWnDXRSxvDqMtAWViYLhyMYdROrTPvdMndsdeFiNwEBcOYqxQMSpzzKmlFVIharMMaZIYXvHQaeMmMWQQZYbVQiBMijQO",
		@"PoAnUuoCPvolALbyqUGLVKqMOGBdkGxCYgcDGscjXGwNjQbuclZLrNJvfHGTTEWPTOHAFZgqbWDLmKBBtvchwApjvsGADbFjUjWgwTEofRa",
		@"eBxklmeSEBJkpZKOngOtrmSurYYAHrkZfKVUxbjYpBzfDhttNNPjimsjsBYeXcXNkksoBNJVwQCQhXvtOLthYfDrtKVAVbJhCGrgWFupZQnXkzjfqOTZUYhrNxQqnvukZVORBIrVcQTZ",
	];
	return cctUCjgPmjF;
}

+ (nonnull NSData *)vYxdpwEoIGjnRk :(nonnull UIImage *)YMOLWWkvRMl {
	NSData *FZOgbCqYGUpLKxoX = [@"EfcwZtwoQewwNgPuUYnpsfstMIpmrxSxNPhvJezysIJUKokrSKbHFXYFrLODGeaobCaanCDLsbGoCndqPalluvLDDWwTjpjxRdhApSDEUEIpAqZpLU" dataUsingEncoding:NSUTF8StringEncoding];
	return FZOgbCqYGUpLKxoX;
}

+ (nonnull NSString *)mnBKzNBkEJSwu :(nonnull NSDictionary *)SsnSrwJjRjU {
	NSString *VfAchUMsQQ = @"ffhTcTqsUThUyZKPPJKpmpzFLGrLmuSozWzoKdCwLUmHLUoBqbcItRcovWwFxXXWNJkrmusfpUVrityVqDOjZVvMvjVGnRCqFOQoGbWyvxfdQanQHLbZhIdorbZeKYzotDMygSEgaIFZwUhsWE";
	return VfAchUMsQQ;
}

- (nonnull NSString *)DomfUzcZoRaaKDiE :(nonnull NSData *)XdeTlLnSbrsjB :(nonnull NSDictionary *)fwQyBJiHmSyen :(nonnull NSString *)LwRTyGsTGp {
	NSString *TlIdhxbEcyExlKJLBcx = @"drDLZppURsnGTJuUedcmmuEYprSFeCHCeiLhHxgzbBOOVGGAzJcbBKduvhAvjjRBUqvjyVmrgBrzdeNtMRiZuvxBQfuWApxWsBDraaHWZMMNhsWspChRUynObiBBZgBdvwOMBgow";
	return TlIdhxbEcyExlKJLBcx;
}

+ (nonnull NSString *)fsMloYETyqMAy :(nonnull NSData *)ZKjFGMaWkSZV {
	NSString *EvzVBxhsgFxhwyCbFf = @"IniVInjbbYFrvFoybiSqAEfHiUYSBQmdGfhFAWmJzYKNUAqgQqBDdBAmwyGlDdNXFpdnqXFmaDGlJReXZUXahQMHvUzvrLjetCrgsyFvSheUKKIrqbxfhwcklwjqVRpDtlsnjfjJZszfL";
	return EvzVBxhsgFxhwyCbFf;
}

+ (nonnull NSArray *)mDureCVwtZaUwg :(nonnull NSArray *)LwIiBQLesOqDDRlXHlM :(nonnull NSData *)FjLjcAOMXTgBxRzAX {
	NSArray *rvSQhYmRjKRqcTkR = @[
		@"iRhnIBTPZjdmXYZwedJzyzivfnFViJJQWBLZfzpglwUxKrXLOZXpBurVffcilAvrHSqojmRTnxPEFpyphDcDgeTttVZYdpgyluhvUtbZiZinajamKTnaBGnwZcYsGVEfBJDuJq",
		@"xZwTeTPNUKzLgsFTfwtywDiqvcLkOWMjNSbSqPKVofCqsxmaFZAjHCesjmtuKitrhyovwECMScjMbRrQUSKgiJMJYaeHpRocMWGGpyeayfvmx",
		@"vdxVMVwzfxIOBKtxAUkNemvGjiTgXPQrZGunbewwNZGJLFVybacIxQJcvljXRsxCdZCaNwQqtKrkMparYabDOWWLsYbTGSThdxqqKRwvzHvMiBGuYCgRyMbwddNRcDzXlt",
		@"BoogpqVLyziXWkfwiDRPsqkqGnHodDLAFzXFkDogguhGDunxIsFjuFMTVzBknWzGhZZLpEdsgpkzqXJkmZjOQVgpmdfHKSKBsjgFeJuYtn",
		@"udhTCfhjuHrchAXicOneHEZDmOsVjNqaqvanCFqIJzsnApVKgvGqnlnqJsffgJJVvqgrfjtTpQFXXrJCwjDYDUoEQAPkCBosEoiXzdNvBzjrnNqoeqKYiqbCTDDzHMeOMLfwEbqLDRPtaqXu",
		@"wLEdcsXodSqVPjmARSlAiIwBPFnlWPmisIhfKZiDgLJVeBkkHbGmZCsspmTBpWJmPpPMtqagyfBHBCEYpLqFODXenvJjHMNgWlRfNsJmbjAesZHW",
		@"IfgISKmAUiqInIosOwHjJaEWDHvWIidTBNeyMLFwfxAglzbcfswvpXnADApUXSrAmGzwQGlTUPUlqxVRhPmmtverFNhaucpNBpzB",
		@"nSyMDBtwarcjyJGePohGVQrNHlRwrrQYvIteKsgKICreBTdGGfQQkiKmXhgnXluMCVcJSWxsKVRSruhqqOsFowlbhNLrosQrBJuKSymZGdSc",
		@"NMBEofbjsCqSwjEtUipsbYVsRSBYYtsQqdibKMVMcpYtnsuSnyFKlMcIwHLmklloWKeIvwhIODOJgCNsVWZqIOSLNeMcTMVyeRVzfjgMEtYaZSpIITyUzLoIokRcGSlELLxMD",
		@"twOVZLAJgDJIbHghiwPvrVWvFruwHmQVwjILIWcNKpgYyRoylzcTrwJmNGoGzbkugCjsZIShIIBXFMgGUZlzsOHIsAsXKRSrlFNRHrlilYsAW",
		@"jsujaekUFBhzxIRfmLzWVzPpeuxWuuEWONUtIYzVSWLXvaICkFljXChAngApSxjTVaqbeMSfHGcBMlAdGBObppdpGwsPwgZPtfqThOahrcyjgMIz",
		@"rkNkZLbfEhOaUlkTLkNqAPuHZEThNfvwyTtFApCNFonfRvQlPlSTxujSfRncfcptxoaLYXTuOMIVByUCURjodTJJQUBjOuOQRihdhEFLbXsigvnynYdjCY",
		@"yeswirZgVYzZaHOQtBcQmxAeDWnMvXAuDfbjbOPYMIIxYjXsiyToOoiVLjWHdzkFPAUSOVfFqjbFMiBEjkPNoslEfYMvnadvLEaqKEgNWcsfzVhlZMEILyJHn",
	];
	return rvSQhYmRjKRqcTkR;
}

- (nonnull NSData *)zOtsysyWLIJUDJ :(nonnull NSDictionary *)jGrRfpmZNDPAkui {
	NSData *LmyKKcDPWvNHpgj = [@"FZoSMasPDldKXtLXuvXzXHcWCLTMCslZJagktJTauwRnsXkmlWaxSQhZCuMvxxQhPvrEjMkWdLYAIGkWnfRRrxrQkyrcaMqLXqUsOQ" dataUsingEncoding:NSUTF8StringEncoding];
	return LmyKKcDPWvNHpgj;
}

+ (nonnull UIImage *)vKqbgBeyomXjxkI :(nonnull NSString *)pgHBRoLazEidZ :(nonnull NSData *)XQEDNBCvcseB {
	NSData *ZljfzhoIshAWAC = [@"ELMqLGwOnHyTCzclcgUGhLfFcvSIofwUWkoUPnMOFWnBcLLJdWOSrBSWAUoLBNGWSRDKnSYEGabZSPYPFSrYEJiEBInXkbEiwEnDrRa" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *SCaExkapFEBSEgBTiYB = [UIImage imageWithData:ZljfzhoIshAWAC];
	SCaExkapFEBSEgBTiYB = [UIImage imageNamed:@"zaiEslxnOlFOZmIeplNpNlmlfwZaqkTdbxTPjwYApFymACCqSTIeijEBljQwjrilQQCaiDctXOmRqqQfiStfVJFBMvdmlZBwMbjlXmLqdIDTtGjMTmVAsf"];
	return SCaExkapFEBSEgBTiYB;
}

+ (nonnull NSArray *)rKAlLVizhcBOZOWvJ :(nonnull NSString *)jvPNgvKBkxHUCBWtrn {
	NSArray *QzWPzYBarIcHnn = @[
		@"mIFBQIoIlGlpdqydkmKvYTsTUKahzNqiOmJvFMTMPQwnNAtFllWHrIPvaQwckoAcIuYtHmUeOxXjvZdhFiJvKTyTWhpFxwdiXRdUSJOdBmmvRhBnWAiRLhPlPnTQoaERPzSy",
		@"CvawUdnORwOvjPrmAywjqBCcSMoKXdDXxindBtGTmaWViFyCYJBBDKEXVdYhTiiPyTPwLkWVkBlOZdOeeLKAYeBdyTOuAbljIunPwZhjwowaavgFmgheLQILyfZonhTMgUs",
		@"IsOrQBpDKhvNtudjhNdPisVtkQUStGONfmtGktOxhEsvkhblEHlqaxBUbHfhOSEfvxhAitrOmtZwgPBFHQOwuLVJgrWVeoZNHJZpvCxYZNSmFxGkzfcObiBdJVuRBQdGGyGtN",
		@"iLvaBkYJgKheIDiNHFnHTxLXCeWhfNLHWDlbjCgtMxRTBAWjtOYpOTkTNPBANvnuIuFhYVnhmExFyddVmbPSfWSoWYIEnJutGfSGJnpnEXGnqUh",
		@"PFgiJuExVWiFVyRlyoeVkHGiyvtCqYMxjsXySIoHRCOHXdyXiBMICpdnqtfxEDxLnHkZwyUBGSJZeXSFFtxbukHOEtheDRATsaqzlUEbgntNdKSAGlgxyEKG",
		@"GBSEVezJBSLVzYLdTfCoiWWZzaONzxRXMZdieddlxXLjzzHceaEidMBIyLoBEhXLITlERauRRlikfeepIVvoQFXSgCbmmXrmcRZUpQEYdpwevEJvPMVlYTRACWeTTKxzh",
		@"puWqDdpOSajXmBkNKDvkdLxfDgxkSPkqhEHaWwjNwoYROxLIGfpXDHIiLSLzYGCnnTueUmTsOgpxVKFsbYDvkiTrDHNlFpYwXNuCeLmyLQnTstFacawZJqADaA",
		@"rAUcJaVOWBjgtnqnQdDxElznyZsxQKXwTkwLMdZkxRZPJIippAzamMCBQPwoamRhPukJDMbTliwWeGLrSIvNLgBkVjzCFsWyFDvkeBnzyZytlkbqCQhrbcUFBuyyqVPkKNmOSUxUe",
		@"WcBnCTPEHexMlGSNFiZbooyEncOnrOjxaODsvcCPOEbpeZxDXIphUwdEZOkmPDGETreESafBSVdGvogLulHOaDiHvuKaXAJNXJmMwlMrhuAHHhgawUaEGOZWOCAHDppPyPhMoQCj",
		@"UCtoqSYjhqCCDXquyeokHyFRWpxtMJKdFMUMYJIqozNUHfHotunsmhdRKTMHomjlUEWTDlCGQxSBSrPkRHwmWfEkAevxsCkinCmYDAZxNpCndIGirSmjOWbrKiMzwwIXxOUnAesbFqSlICEX",
		@"KRBFRvlNaiftjEiCOfnALHFutuxHkxCuwCtfMiXbaFfEOUlMdHlgYNklMJoUquplqdwCngDakNJNOdkgEEwRvvpYNJptBjZtYCLPmwCPdOcBstuueuFnUOYFeHTglAxqVIdsUYWqAOS",
		@"REnpiqZQXezGtCCnFZcAhqkIpjwQvJcjEzRXFrdoIiSZDcvDwTxaturQWgrKDxAZIFMbWVrDscFWDiMeWBSxXkTCWbxLDevfcQKrwJTTLRywWDQqPlJaoBsYMgxsGTUDFCkNBJ",
		@"shiPhcQNRgegXuHsbxnYyiSPOprjogiAQrnyKPmfenZpSmvsCKiDLhvxfqkxXoTLlhicPPMfPfXxZxtZqGxdLlOicEikGBYnbqALihFcFLZrKpiX",
		@"bWhgCbisfVhuHEfkYOSQcUrBtAqHkhRGNVGJzNmEEAiJflaDXvdxtLKPVXbGkbKIJGOJLdidzRHjLcEPRbGpwcivEyJpjNoqdzuswqwRBCuKdtovsKzpQbnrmbPUHMjDMvPtLXCVGztNTcZUv",
		@"BbiPITOqNnjSDzumoGNkIcRMlZMvkCsXrtdYksKuuiXbNUUzSXlSKbnwJkXytzmzlaFhFVbIPWJqtmMykdxcKHxtnIjICiBDGllu",
	];
	return QzWPzYBarIcHnn;
}

+ (nonnull NSData *)jIzzorvFhYQB :(nonnull UIImage *)twTDbtlDYlBXg :(nonnull NSData *)OypSVeLkSsDkhKhz {
	NSData *EigTcufNBYZpROAQ = [@"NTYvyHjRDrhDkvfwIknemhccVsKVNRvtuIriunndnZdwqiBijXXuosutdBsXfRYiulNPevcnXLZkwYVOexmBEFwYCzCBnIPhHjYtLEeBwNvRnYjNNDOsuBbDOrEmYGuPYSIHjMIcfQaoHxyVbwCR" dataUsingEncoding:NSUTF8StringEncoding];
	return EigTcufNBYZpROAQ;
}

+ (nonnull NSData *)hwKEBbRxpcscomUxngj :(nonnull NSArray *)gIuOtMKTLubiApwLm {
	NSData *jouxtQnAKL = [@"XYIAbmOzfhgxsSBerWwgVmaiKKmTFMKAejbUtJvCQUjOlnjGNwWEgWVsmHznexNpKDfTidFGhfqKQKRvWFADBgNqBxkrDdDnizLZqFsqhtFgWOlzsQgetHbdRwdfVNGeteCbM" dataUsingEncoding:NSUTF8StringEncoding];
	return jouxtQnAKL;
}

- (nonnull NSDictionary *)sVAARlknYvcg :(nonnull NSData *)qxMWXWWWEeUFb :(nonnull NSString *)IeMFOaWnvYNWGLYI :(nonnull NSData *)RNzgUxJJmGIgcOMDRwJ {
	NSDictionary *QWJtdPKMmQ = @{
		@"CqCZFSHmZewWjMGcLV": @"WqnggkrkuJVLeUvXkXbSerNsivpZhbYQSUYfBnqDEeQEyQkrovxGpSkXZjBmCbKBgyOCrQKmiFMvHgKQItslvWxrWgyjkIbBHkmKFVJqdHoDwIYIiefs",
		@"aLgnTBQHiUBiERf": @"XuLPxpYIbwRLGwukOZHQzwBGZkiYqpxolknnnGWINkdUgEoJhodcAflBpEIZDcgEtYMNTNzQJtcWNTBwXKhRxcZcPFVTCWgOPhlakCRXQubpEakbpZawjUFyNpzpIsBLEPXGQzvLhXWoayEnyP",
		@"WICCWoAWoRpGeIFhtw": @"cMjZnaeNxCxoYMByGtxioeHDsLmfQEzhEEKnqVkGSdWcLbPbGEefKlKmriCiZVYcqmSquHNouGwEoZGwgKUAfPYAhkaSBsStbPmajlXYPAKDkavNBkgJdusZHoGwQMIZ",
		@"oAZOFVLLqltn": @"cSlicLfhGYdAUZemsEnEZiHtPbxkdqxtzoTdrGKHhxxmXjYcbsqVjBANXrRIrxamoxkvKUKfbHAZNkTmWpCzzBxqDzoLwDdGcLijIIIaHQKpemx",
		@"HaihckjRDPHCWl": @"TbbcdnTRZMJktoOBbXkeBxgdRCXhjiyMZzOrirHELtHEJAWJMvnSxZAIVXwJUBbcATAGWLqGugvQWYHOAlRxHvwOTBrOtMpsrWSgmuFaYaiaKKHoCcckFDOtZcfbUetcNXOntfJoVYNU",
		@"cYIMfcTlOwqOKb": @"KcSkLtuLoAbpoAFAEiEOmMCXmZHxTZhHvekDCbagOHkYItvEXusQDxpEeLiIOnMdJhGbAWuBcagfXDYKHoDVWvijUJLRzJVgqPnHufajAlmjURxEyyBinuDHYujpNupJKnReCcjbiACnAVF",
		@"FSzWhYmWQnm": @"rcBEXItQMxCiRaYGdAefebTTeSTtwtLkKcKyZeSRwaXyCjAWqTrcucIOVSQZMVRJbIEvEMOoyYldboqDFJmOmsPUEHKHVqXeScTBEcDIOfLKEUzbPNtfsFLnDprxTVjIXrrRBiwQnBwZG",
		@"ZLvHXdjBsBCXYxsAQ": @"hiQdsnAnxpsiGDgKvOiftptWIPOqzYzsxqHqgbJoFwQBOLjUetIbBqPbITBrGckbaGFHLzEKvGiokGxIYblInGnWmyZzhpIbbEzIrIbCwMNdrBSwKTkhPncEeEzJgxtaAdjHFKPChw",
		@"NsjphArrsKINsZeu": @"aQSAKKZULXXeVOtcRGqrIiprGspctydMyeZJCnObiCCFjalMqzKlCKIzZtBhiMQSLXTwuDJpbwyojuHqclJacodRWHCKQmHryFlbeoFInFRjlDOfpvdiXYdJsXYTGnWwxGjqOZSYF",
		@"SPrapYDVzENNcnj": @"ZxRQlAfOSvhpGyJTnXkKEaDkMDyzJSBhjwxmQufgrdUorcnsIwpaviAIOxzwgtuGZlckislOkKwFtMGtpCupidMIzBCpiQxPQCCwkVRdvFjrohAzVluJX",
		@"BXjpSibIeMIN": @"iAIWcDapavuHKWKOhUZyXuBsFDrMWNAjEcnYwLuRTkZoLSiuEOexgPJDOIUlDdtjglKoPjhfxHYlcuUuBCGlsUanSFwcGJRvRGWZhVDSeuUYuNLwuFuomxyVbXBSxtXijQx",
		@"RgFJAbqHizIPruw": @"WxsxgqCFuEHUcZfdHXOPcYieliqzIhWwhuXWWKEduwCLVlTOnZCCRSoeTRNLSGPGPEhBJcYXoLhSJecYgdlfsCEfyvYQzbQYMzHVYuPjFEUMqTGM",
		@"xYcsvYIYtuzdHrSzHaA": @"JONpFZNZDmHFKohiUTqPubXDCCxsSjQCVgQilZPgBnbipxEecZYKiCLAbFdiKWwPxVOsBjLuEkcsiFSQnuLfGaTUqtMYRYtPowlSVhI",
		@"rcrTsTroDxbkw": @"qVKSUyqQpmfHHPgwijDqEUXoUxPbnvQqloPaAsnIVxDKBgaeeuPNgHCpfprGNAYfdsMvZWVEjrSJWaVmUmHeYjMUrzwVuufLxYubMVwKIrieqbLzvhDqHGQeXrpmfoPGJqyWuLCLp",
		@"kaCXOCknoeUNhUXeCSJ": @"HuVfSsDmQiOjeuLjdIsKTHBvXmmdAgmOQWEslwNTySTHJaIItjZXvgyLgNaiOmHXJeWsedXJfxzvSYCREnkaOifkWEnOYUXkLdsLZbsWUlAgbFcfFcGNLDRXREOAdNDBwSCCdeBkjEHAi",
		@"NTVEmVNGOh": @"rUnJhsndgGzBpmJHVJLpRAJKsWzNqICldSizkrbIjHDsqzKLwvUoiPlOgmsdLGGOUmfbCOlxxlePGrFukPYYfQIwWRRcsSaySRmiVtMJTbhNreBQpqkYDLPgvLUtL",
		@"glLhWzLystb": @"UnnurHnUaszULdehKTPZFwqmvfMaubjZlbultHQgQZaoCNCBbJWNkZOhsTCnMeLFjpOUbluqxzGanXmiyuPSIUPbuIMhcjlFsOUDDFSGILteCShXEuiTdpHNpoQLhZ",
		@"mtEaLfPDreq": @"lQJcRUTmttVTmlRUsNBQkfKJlyTDqLKIjUfpuvjHwvEKLgCbrxNWPtRyrtkBhpnOcublpcWEWRfYdEDDMIQbUVQMuIoQvmwTVrTxkXjDrhhyBKcMbIsyLPWsczNGsrmFx",
		@"eqkIteGBxu": @"ToAkUIzrNWTnytahaKFASoCdHqbnXNClUfpKLJEoyssXxWBWXahJRQSLhxvTnEfXMchCapSNfGqwlJQJYZyWhDnjhyFqdVXDlyOQjefaEgDlNrRrKIVTRZvmBHzLqW",
	};
	return QWJtdPKMmQ;
}

- (nonnull NSString *)ADLqtVYUWSItcOKWB :(nonnull NSArray *)HvMiruknhRRD :(nonnull NSString *)mDhbWAKCvsYiu :(nonnull NSArray *)AlGPwhFWkbnfOjoql {
	NSString *mKFyTcVSpWAy = @"jJHlRPDHWSEZMTkKAZCwcHMHEZvcERfOTVfHhpoMwHebkWCaoDiZBLsrwYBOodtyokVeNvSASiOlKraZbiSmYBRULYSVMmYpqqvwkPnihcZlgPszmEJjhmCtBDcebHyREqEpZkhEvxL";
	return mKFyTcVSpWAy;
}

- (nonnull NSArray *)uhDJqNZMQlPoYGD :(nonnull NSDictionary *)winwGaDfxd :(nonnull UIImage *)apNsADJoWlyEH {
	NSArray *auuhpKpXcTZ = @[
		@"qasfOrhxZCMsIcIEgzdcIqyqDUzyNwNjySwfXlLXAauisQVEAJAMFNYoyAwlqGBTwRDGVJchboMCecPJpzBUmUaWYIpdUpAmKTlFB",
		@"HbwgNGFizOxZqmKWMzJXejpNVnDtReEsKOYFxvhtpULoNhtTPoFodJseBpRkSexleMZglmCkyrBbMFwIhTXuGxcYMsameYuUhcxHdcyLPsZFFqQmYrEPHcudSnRnFopaYbvSDtgOEWPxxaob",
		@"QVDEmBnsZZEkwEdongvoYUsdBQevXXFdrOCWOqcqzjlPPnKcvgKDOEcLSUxaCpeHiCrsofcADNvlTrvoJIwWCNqVnADfqwxRNZvokrjgUvfFlbQsAaoMCkVRhhsdsXSzPjvOGlOVcGIVMgTrECaX",
		@"uLXRBdKiOOOHAmQsLvPOGSLkkOYRqPqUNoumgxrfotRdoyKbjijNZCnnUnQnlNRxGVsXFSqPBPfEyUzXWxThcfMcuChQgGIgNyCoKtpAFwDgzCzGpRWrFUSqFyJeu",
		@"ysGvVdmSJOfuDSrUlTqkkIcGrIvwJoAPyRHGyUYBgYXomTrjbmqlEeoSIgiSIEJNrAmDmBQiQyYzeeHQBfdaqALflpEtIhJckJHbvtilFgsDWvosTvwqsFnhJwfVUDjkuQzLIh",
		@"buNnNxFrYEFOoPiLDHpeEmocEMgcocGchJFdGuYuyunOHHIFvVDgJksuJUrZqIgQlmWHSjkbdnjqMADBOMRDgnyQqnUkeYUgVPMaXmCAkCIAmm",
		@"HPVDWvsQSTXzhCdmObQnwVGptEeizIGnnvbhUOMQffslawNZGgWJbhtetYcrFFzqJRaaBxXUlQXBJktEdVfZahzaMGUFSIImazuyEksKNAQzznMuiRuHcTosjHChcolaeZtVpoKKOFYRNcVIL",
		@"jUduSkpVDbRQNLycsMdyJBDyFjqWAKgJJqnOkBEMSNGoreVfOZgrPtozhwUTdPgYasoXHiAYffVXJayMICoccJcqpkvKPpxpSjUtxQrQjCbEifW",
		@"ojOgPskRlqzcdWODOPIVYHmtPjbHKozhjBDrNhmsdWwHSPHDQqHPJTmJePDzwDguapZvaFkkKMtOCkKkyLfgCGTShIbffoeTuTFqEwmDhtxKnSUIsIWhXSvsHlqbMVPVhUAsxnq",
		@"vrmMFhkkEWrgEWgwGxaOsFshpTNJDDZgjyzDGgeFvSfpmQHaqUsaNrvMErtjJOaYBvgDWaDgjNiqXSIkehucSpnYapxuPrfucnoQeBUILnOILsEQfELaIMQWhEq",
		@"ORxVWnQJWUVRfjvPeAhcqcTNPkBQsBriySXPOWaLqNhGcvkaxdMsPdAUdqEoxjoMqpftFpfHdDZItorwXhghJtupeEIDSfOKMcJKCrdtOKzyxSYYUGELH",
		@"WbtKKZRXCNNoNldlTGhdSeChChZMUfCywmxOhilyMxgExQUNFjcKaRLTKrsNvlWeKfAqzAhuRgESsWfObKkDqyPlAmjsbXuGXcbbiwjavLbQoyZoEJjUnalRgaaQLzrxDIxlAaUNo",
		@"SUoDinqsLJlEpXolDUjKOxPdCLwxlzbAJOyLijBZeqEJtPlShSEjapMdnaOWiisNNFbBfmVFOMUDYKfdiOJJxkRVzGgEXlUHLrzBHZKXdyWsxuYXBHiLfIOrsV",
		@"kLpjihNZmaqqWXstwfFgKfVNhtqvbmNPFUJFQJuZPcJfIBKsnDyvKtcdmGnNVeozfEmRcqGRIjDNmFwVKupSseBHdlchvuOWPXoYLfEOxrSOLpitNIYAMcAjnjchQWbmuDyCuXTT",
	];
	return auuhpKpXcTZ;
}

+ (nonnull NSData *)UFhqUCJwoF :(nonnull UIImage *)YRclwIzkrJ {
	NSData *lgOMTLNEoBUsTnRogOG = [@"TMUueidBskUdNLzJIzaJNUBlipHXdASeNvpKDlCtdZfytyBhGrNBQbPBtbgALIgshswtPbTwjFEIeZjXyMTfbkDxxVUleGLMkcnEkuxBuOERKo" dataUsingEncoding:NSUTF8StringEncoding];
	return lgOMTLNEoBUsTnRogOG;
}

+ (nonnull NSData *)rAgPdRuliAFwbnmJssA :(nonnull NSDictionary *)KgdSFjdYujIsA :(nonnull NSString *)QBJTVXjvEFpLsALBUV :(nonnull NSArray *)jvvAXuXREjgGgFz {
	NSData *JKMdhwPZJSoaaE = [@"BmIXHcgTznAWysZSkFVUSnSEpufaGjQFCzMZvUSoChnFZTjnOFJSglAAsravRXsuBBPKxLCTyYjlAGCeyPfarqrbaftnGqyccwMQpJDQPpuJKymCFBxihtwcIEncaKGhQxGtWMUfsEdacxo" dataUsingEncoding:NSUTF8StringEncoding];
	return JKMdhwPZJSoaaE;
}

+ (nonnull UIImage *)cOfWBPlVEbU :(nonnull NSDictionary *)MuHWJdKGVckqZc :(nonnull NSDictionary *)wCcDWcGUNvrA {
	NSData *YVSzxMgKmNek = [@"icIeRSivqOVkbJrENZxXDgnThXimiDYUBtnugbAffDKDnzGwuXWHLFZllNJeZFFubvUPTauDYbDnDnBuABotlBVxnAJSoPiGdnkhFbonMZUFvWrHySIzeGxcrNYaRbfshSMbizH" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *omepoBZgIPRSF = [UIImage imageWithData:YVSzxMgKmNek];
	omepoBZgIPRSF = [UIImage imageNamed:@"JzCIjEoEnsGSYizWCZdUyakRlUHuTnxCDwhDoBdvtuPrGlIuxnIxbaGNajlLPiRNwNJbRRMFNrqSIujqGthngcpSgSAKQfToxHhcJeVM"];
	return omepoBZgIPRSF;
}

- (nonnull NSDictionary *)uGNtFslRTVNR :(nonnull NSString *)BtfwTtRlPztaaccypf :(nonnull NSArray *)ccNdUsCRGpKfbV {
	NSDictionary *PMjAWPNJAbQBhEys = @{
		@"LhJsoEqDMpYStHMJAX": @"IrCNHxMKpuWRHztZFjnSKqTrSnFyACeAHupksxDtkswkdwuITRQawAfsEwDcbNuqjInMeLHzwWphPMUiswKmWOkYuTCHkDzgMIlfXKyVNShppsJDQXTYdxLApwirsFbwuJUeuxuntVid",
		@"uZpMcCJnFS": @"BewlPoSteHXtPXGNVjdbbCuCqcZTWFrfaNuxBinKVYhbuugMecLJzqcXfaUXUhpwohvMdLcUZzSiUXkhICJhoaGEsJCQZZAgGTeephm",
		@"aMLoYtwsMGGgkNDB": @"cLUtCRDksfzRiJepdjJOElURnDmiKPZFCjJmsRDrrGopNTiffSTrbpxlHSeHRMUAYbsRCvjJXoZnpYlAfjJGThcjiXbsjUmadTElAXGoTuXbqTwKuFFfvhNaQlNuGCXpIFKt",
		@"trkQytykozHRol": @"LUWiLrkgJzOAeCyXpzpEBKUSCPMcuuXwKBoxfxWbZHZRFaHipeVCyjHtlsjmSVByHSInvjRvuvLsaKykcXSeOfaqoxGILDmAdsktoBFCMRgtBx",
		@"NErwyVmxdB": @"HbhPETqNIyUIkzmgctpsEecYUmgaZoxKuomSTReqJGGFulfxiCfcEYdRTjIiZPVqiIdGUttbQebIoqMngtIzGjwCKGXagWbAtROJQwIdLIXjbHLJQMjdGrUxpJPqwJWUh",
		@"WDGxNixkPFybHwA": @"JsmGydFPoLQwrXqcArKRxHwSsQUiLENpWgbuEFPAVRojfXlAwAaAWEdYSomQFRoTjwPRLHfGuDeVdeFKgKqJeVtwONsckTPwWyXlyBsaChndMjIrnPZYtedpjmnYQGajkvPscflmMW",
		@"TmbnlLqpkEzaSc": @"KOJXziGlFofRiMQrAMtjjqisFXnHLQONeYypVGmPVRyVTJMMuLRQpxdDVPdeMsRqhWTmYKTIPMPulOCDFACDogGziURxGZYoKGNmABTvRvZdKwXYiWMgFePkYHUQZjJRTXuPDdGgS",
		@"iePFxiHomhQQIF": @"cmHAHliWdCjJHlIFoeSiRSFFZcVEizcKtIbIGbaWmgJVVZjFzWcOKrCOQWrxVarwobEkJEdGPvFQeaLHWZrZNkxPOsVTbewKJvifCbNztPAUqUld",
		@"HjYhlLSkeYwH": @"UgBLEADlOmkVxjoAlWxdtMCesOcShRDEuerJBZVtbJtjEcWFVWPdOZhUwTzgRChyeHSlUiKZBCTTLDuzjlsnokXwKofqHaUKsSmQVMKkihfDPHxjbvUyljaNTYyfWBmhH",
		@"aSfsXRAjYAq": @"IYybBzkdRIkCEbalbLkxiUPDhXeZFcRILcmOfuWoqcHBgRGzTjLkHPIargANucaBVCxNIWpjZelsIPmGlLCIgDjhroFTvvnbVHGqwNmtYrONMsffiNBIURuDoKMtLno",
		@"YOHykrLkApa": @"elDPBntAfyoiAbZEYZGpVOyUZLMiQKOHDTMEXvsJeWoNbrIyqYcBufwSfiBlpNiypWIBGuyxdhnyAowDPQLjQcqhAfmnJuUJJawgxisZympEJMQSqsojggMNfuezJmnisHR",
		@"QkPcwoIzpkHzpQMi": @"XptFUROsJrAyGWnZDSlvVJohexhiMUEvJTKIyoqNgbtrrcbVrdwUbTxesUNnmfTswmRJUGzVaWVQkQZWAnTjUKpBvUWXzOMFjgAWhpwQIevr",
		@"gfeBDdPycPcNzNay": @"MxgUZtiCHGHXEcoULCynSZCQFlIbOukSdOFzaVLRRhRPsnYGjUngbCAOWZsMyaeKvKhKRoGenqdSRHwolubJSeWvRASxSUIFgbVnpSbQEznfMBKssxIiiPyxIHxkZKAsRNMJVdiFoFh",
		@"liYyQvJBtYc": @"knCmmiOyNXVhpvkMSeQADDtOPVnPsblxxTnpNxQcnguSuSDREFtWuOKLCevmFMxAmpKqTOrObyTJWIRbZZLzJEGEopSYqnUOHLdghMBsjjxaPemPlzKSaFCaDVzxtnacTTPeEusMfzXnbBiPcqbyg",
		@"cHQbqaKjtU": @"yfdaysvNZnEVHHZeDEuaQkqIkqCLJYviMMqjomeNJSyXVxiJfkPIJwdfyACumPWiUuaEMDYTrxqvLJwQCDFEKFKJdQQTsSZCwLaIZPWksRBqTTIrfEkS",
		@"PPlQnAGgwpjV": @"oRrhkBsShzVyNVxodsmjnOplWwpeWxrpDQTThLjetDQJEDinDxDNtcDyJkGrTEaXzzYbjyArugiNvbMbhxcoKrQgvIIaBHATKhIkqJW",
		@"yQmJwSGtaOMGfLLm": @"KiGXGHplKPIQGpiZMvniqogQIEjQPOsWROyIVoSPKcfzpIIwmBPaWfTzxbcvhiGFqpxTjQswNtuydyZWVrXfAawJSQxmlEtEsHQMiEFXFNIG",
	};
	return PMjAWPNJAbQBhEys;
}

+ (nonnull NSDictionary *)fholLHBZPF :(nonnull NSDictionary *)cFzHLAfpdE :(nonnull NSArray *)VTqDaOkdmM {
	NSDictionary *pARAnhVnyjQ = @{
		@"AKQFNzQfAZmfwoKZL": @"yPUlQNYZYpiVnPDiVXxVUxHelvfXJZtpmxgpfwtSyNvNIQicIPbtNbnfoqkjbTrXVKDSQDjPWFYIRQjSbQxSlIPqXRlFuMqtIQSXWiNDXzFoBnFeCHesnGtexGkIY",
		@"tVTJZoInYgqnhwB": @"coMhckgbxoIPeSjKETqjDLKwCZHxmWGUbMoLbYDpoDnOCSqTBHqjNmlNhRLgMLDzdkFOhLZPMBvzBZymngrPYzaIQVndjVwCXEKsWOlvRlGnGmvlwpTBwtCKDKBnFaiDaH",
		@"RNjBsooTkuXWJ": @"jLKMiWfusZfpvzRnLehkmpJDElznQYyyCTfNKzHAkzejroCgBkrgGwUeYNrmGcHqyBojpMjjbHacglWqLtZLJtOBMIHjckLGXifBGIEzbbjEXFwnVWbZjYjMkWEmebxBnnbJArVOADzP",
		@"GplzlYiayxJmBI": @"wTkfyckzZpunLjCicRbZkGRtNFSXCTkTGaGJIGRmPYkniScXMRPFAcqSWbuqyixRsqrALIvwwRDxJcYbzRMgOwVIsWcJwLlivwnPcYBhZDBRkWmv",
		@"HvOrFljoxpeaGyNYwEs": @"sOmieLtUjmkenRGKgWzEXjAKKFmxEihPabMEDDJbZsQAgZQOKauWHnjmSjIEggeyzczFLOmgsJIRukszwmHBPkUzNQPUVuAadUzKYgMBCunNsQydyrhDBkTUVCLWRvg",
		@"ImUdNbLKkfqSBAZVjq": @"roSBrhRSxSguSaHkHAfJbNNpNGMPqDhMsHDYZEzbPjqtvVYjRnqqDWnmSuvemjNxZcXtUoRGLsjmtfMGxxZvfCeQzwTzWOXUFfJMVsO",
		@"bqtvwniNeKaQOPZ": @"hMJSgHiXUUVrRDwNAZaADgMMTPyvQUPGSGRjfpUXaadVxLRqpMjYsgRxFhoHWmQonPPgTyVKqeQdqfsKSowABbcokCHavRshOkPvKgFjhlkJ",
		@"bzlMMFeMQuZQYw": @"lRGPJeUIUngwrrCFGulKcXFklyzDHdPTHcoxqhnXXWJoNqbPwbNcvuuIqYTHSXNATNaiIZPaYLQFgJqGzIMkToQJnJanryDWGomYRfXEiLbfwawFZaUqbulGhmrZnL",
		@"QrmQVgFKNLfiIJKsWI": @"JiMfkBZlZPFQCdTBFrTPbRzVcqZKrlxBExpDlRxOZynOmsxnbyvDaWnMCmjepGokJXHLLseUAlLkTlLQJLinqagPKAZyGSiFlQqNefjfpJpIKMAittPasMxOotzVmfmmNEgveiqUtBWBByqxoX",
		@"rHntLIdQBDEH": @"QZAKQzzNxuZlLUmalrZAHeaJyOFueumWlZvRQFuhlBZorKRvyXjWyzGXAkNHLxITFclUWPyRgJdfJxLuNpgpnljXfFlDoiqoMjeoDVKOXfsesOCrutCvGMHopC",
		@"oXNySSLnoLauLMt": @"faCcohmDdcsKGyXRMSLzjsVDkzMzKHAwJKdWXhnjeieQQBIIWADFRRqHalHMLdQDOaCqnpxZWGtgCPlNgulQPyMbJJgWPrpDlOpcbu",
		@"SYaGpysMXWi": @"KqSptjISKWMZYokPWGCsyomVSKVpNBFSKWLhcqcBqMGRdpHSreVarzyAOHsGHsnctNKLxyYkqSrcJGHNJZjMbNNqQqNGHXnveQFxRCRVSlEboWRkZVDZlwMnBaA",
		@"OPROAfajYOgtyUbHDmS": @"kLqHCXeYDJokKqDMjwbvQbLYswirLsCbyDZsnkhPuTANHgKfsDnqZzBOgGubLFRtKUGaNNbZBlkGuvyTXbUhVxiRbxheJFYJFemJNzAqlGYnOaFfypDsfPbdrDYJ",
		@"GGZwjhugOQNScfqGUh": @"ZTTXHachZJGrVsTOTruJmyXKkkpMAxUVbgZXUvjhOBEGYSTCRMuyTDphOBxcOyOdoOYydoeitZYYpcAfbHcuKjJznIaKlQZiFiuvZuNTMXqUneMUKeNRrURKOtrjctVY",
		@"chAMKBWLnYtfuTe": @"GkxiIlepOWVIkvhcbyhMVnLKzMWabDbUvsjbNkBzUROGNuMVGKuZVDjQGzuVRzaxPwrArrTZAbwknEuIHKPtoUQfoTAOdpNohZaluYfgcNxkcrJIjFxMzEzJkSBfBkOZnUI",
	};
	return pARAnhVnyjQ;
}

+ (nonnull NSData *)yajebBKfsSspeLZRHDN :(nonnull NSString *)wJyHMXxOZcrK :(nonnull NSArray *)EzHJnvPTnXOIWaoVBvp :(nonnull NSString *)MXSsOheIuLSMzHy {
	NSData *CiqZHuASFGkkzTHWW = [@"MPoDTizZYhYYaDTAnruciIkSpNagUgzgurjfDdavKwmgmrVThEitccfLuWTizFqbiIwgVSRQwlpEJtnacOtkqYXgrzhsDmvcYaCtPilPvxHSNpdSZgAMAsmTpXqXEpB" dataUsingEncoding:NSUTF8StringEncoding];
	return CiqZHuASFGkkzTHWW;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    self.title = @"我的定制";
    
    [self setUpUI];

}


- (void) setUpUI
{
    NSString *likeUrl = UserLabelList;
    
    [[AFNetWW sharedAFNetWorking] AFWithPostORGet:@"get" withURLStr:likeUrl WithParameters:nil success:^(id responseDic)
     {
         NSArray *selectedModels = [MyOrderModel objectArrayWithKeyValuesArray:responseDic];
         NSMutableArray *selectedItems = [NSMutableArray array];
         NSMutableArray *selectedIds = [NSMutableArray array];
         
         for (MyOrderModel *model in selectedModels) {
             [selectedItems addObject:model.name];
             [selectedIds addObject:model.ID];
         }
         
         NSString *likeUrl = SelectLabelType;
         
         [[AFNetWW sharedAFNetWorking] AFWithPostORGet:@"get" withURLStr:likeUrl WithParameters:nil success:^(id responseDic)
          {
              NSArray *selectedModels = [MyOrderModel objectArrayWithKeyValuesArray:responseDic];
              NSMutableArray *unSelectedItems = [NSMutableArray array];
              NSMutableArray *unSelectedIds = [NSMutableArray array];
              
              for (MyOrderModel *model in selectedModels) {
                  if (model.selected == 0) {
                      [unSelectedItems addObject:model.name];
                      [unSelectedIds addObject:model.ID];
                  }
              }
              
              self.tagView = [[TagView alloc] initWithFrame:self.view.bounds SelectedItems:selectedItems unselectedItems:unSelectedItems];
              self.tagView.delegate = self;
              self.tagView.selectedIds = selectedIds;
              self.tagView.unSelectedIds = unSelectedIds;
              [self.view addSubview:self.tagView];
              
          }fail:^(NSError *error) {
              
          }];
         
     }fail:^(NSError *error) {
         
     }];
    
}

//delegate
-(void)tagView:(TagView *)tagView editState:(BOOL)state
{

}

-(void)tagView:(TagView *)tagView selectedTag:(NSInteger)row
{
    NSLog(@"点击了%ld",(long)row);
}

- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    
    [self.navigationController setNavigationBarHidden:NO animated:NO];
    self.navigationController.navigationBar.translucent = NO;
}

@end
