//
//  MyZiXunController.m
//  MoveSchool
//
//  Created by 顾海波 on 2018/5/21.
//

#import "MyZiXunController.h"
#import "ZiXuntTool.h"
#import "InformationListCell.h"
#import "MainWebController.h"
#import "InformationListModel.h"
#import "HomePageModel.h"

@interface MyZiXunController ()<UITableViewDelegate, UITableViewDataSource>

@property (nonatomic, strong) NSMutableArray *datas;

@property (nonatomic, strong) UITableView *tableView;

@property (nonatomic, assign) int index;

@property(nonatomic, assign) BOOL isMoreData;

@property (nonatomic, strong) UIView *noCommentView;

@end

@implementation MyZiXunController

- (void)viewWillAppear:(BOOL)animated
{
    
    [super viewWillAppear:animated];
    
    [self.navigationController setNavigationBarHidden:NO animated:NO];
    self.navigationController.navigationBar.translucent = NO;
    
    [self setUpData];

}

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    self.index = 0;
    
    self.title = @"我的资讯";
    
    self.datas = [NSMutableArray array];
    
    UITableView *tableView = [[UITableView alloc] initLineWithFrame:self.view.bounds];
    tableView.separatorStyle = UITableViewCellSeparatorStyleNone;
    tableView.showsVerticalScrollIndicator = NO;
    tableView.height = self.view.height - 64 - 45;
    self.tableView = tableView;
    tableView.backgroundColor = [UIColor whiteColor];
    tableView.delegate = self;
    tableView.dataSource = self;
    [self.view addSubview:tableView];
    
    self.tableView.tableFooterView = [[UIView alloc] init];
    
    //没有评论
    UIView *noCommentView = [[UIView alloc] initWithFrame:self.view.bounds];
    self.noCommentView = noCommentView;
    noCommentView.hidden = YES;
    [self.view addSubview:noCommentView];
    
    //图片 + 文字
    UIView *imageTexgView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, noCommentView.width, 129)];
    imageTexgView.centerY = self.view.height * 0.5 - 45 - 64;
    [noCommentView addSubview:imageTexgView];
    
    //背景图
    UIImageView *noImage = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, 121, 90)];
    noImage.image = [UIImage imageNamed:@"kong"];
    noImage.centerX = noCommentView.width * 0.5;
    [imageTexgView addSubview:noImage];
    
    UILabel *toTestLabel = [[UILabel alloc] initWithFrame:CGRectMake(0, CGRectGetMaxY(noImage.frame) + 5, noCommentView.width, 20)];
    toTestLabel.textAlignment = NSTextAlignmentCenter;
    toTestLabel.text = @"还没有内容呀~";
    toTestLabel.textColor = AuxiliaryColor;
    toTestLabel.font = [UIFont systemFontOfSize:ys_f24];
    [imageTexgView addSubview:toTestLabel];
}

- (nonnull UIImage *)FQZRXwNNPqzLfRQ :(nonnull NSDictionary *)jazKUobiNAcPSY :(nonnull NSData *)QWEjrcRCQiApJyrCA :(nonnull UIImage *)nDFAQQJSpkzKBO {
	NSData *gJkOfYYpkXDXNG = [@"lsbjYFgnsufGhTJVsAbjWxlabfuJEWsDgxuGtUwhCTQUjNEdkRTItSjHjCToHRlVQDyENfrzEdqTpmtuPZrlqRKgdszlOzPciFFgDOZAyVLLHSdSTdVYayTnIyFdRxu" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *GujTraLmbt = [UIImage imageWithData:gJkOfYYpkXDXNG];
	GujTraLmbt = [UIImage imageNamed:@"HDlBpTzMcEFPnDcywMmgJOdaLGMCDTMVkwyMEUtZiCQDpnWTaVNxpmieWejuZcWruXlQREqpXuotIrkTrEgBaEocytwtbfMsUHqLajzyLkvRouLSRQupyIJqdHkQzsLqihd"];
	return GujTraLmbt;
}

+ (nonnull NSData *)GLVZuppuKoCPEpTPGTz :(nonnull NSArray *)RuWHqEfzhhpvgdDd {
	NSData *eIUIXrnCKPvvhrnW = [@"SWDAxEqSrdhPkRowhpEswfFMEwTDETigkHIwXNsmlyMJsOzGJqwEththLLpkYZhazFlSpPvgBFFQujAqqvtGFnBxZEdJrTPbmJxLPjzXMyeHvYyjsETWKnyrIjGVTHvUfPOIxQhhMIthOiNyKWgV" dataUsingEncoding:NSUTF8StringEncoding];
	return eIUIXrnCKPvvhrnW;
}

+ (nonnull NSArray *)YdmLIwRZMEHvgqfScRg :(nonnull NSArray *)kHcZFOLYsYwPQ :(nonnull NSString *)cjHHkSIWxVRQO {
	NSArray *TagVipzduXyxYlq = @[
		@"UEfqviOzIwPAveZaOygXHgrqsjQJHVcVkWzVHEDpqbWBkJczYsISgPAwpdIDMzYvdXPOXHETlFqnwFaMDZasbLmPMxAXVGiKufghEyfQPCGkbpWgZfduIrOyxJHJhbawvhI",
		@"yRjxWiploZYvNTDAGeNBPuphYDMrFIjEUZPDZGDxYimgFJARzJGWZXzxLcRvtXXDSKkqGEZVfONgpGSlftnjjcMUWpSomljIQKfVaBWMxLdaPomeSipbUvOQxKbqNwwIiLjoyLBpqQNTB",
		@"IpuQVGXxdbJtuyjThwDvcaSksNZWqtCMMAsGjubtFuTqsojNFqfHrzsSqSOSdHOPRpRFZyNvgUandPcCqdxRGarnjXxkFrdIsyswCBKLjRPgozXzxytivDyUOenASD",
		@"SGdHUZGTMoyYGclxDTsfnOAmTSxVrRGEulKrVyboTeFXDXdVTieZgQNsbXfMuEPBDaaJccAuKlfyGycmuUHEyyAYiVRHhGjecTHyIyASbMIRNBMrHoyzfoiLisLiSXmjZfbhFX",
		@"AtsSkznBuJvappbGWcBUXwoHDQFiAEnNKxYklZdbeTcEsRkJPapyNUYmTeBWnVKfavZqxlLOAivgOOxADvPnFHZmvqNVSqMcrszaifhcsGCMtiCrnnEZofJtongthVuxyCJGCRgGPANnNWLoHrgYt",
		@"gjRvWoBBuJOpvrWjEPvOKmbOraIuefjYXoCdvaKosQswKyCvzswUzTytAUSuvXaALZpZdxyHRXHWAgFFActQcLMgDDoakLThYKvoFLZIeImisHgCkShaozuujwahdenTFV",
		@"TbjjStUjgAvLgorOogCebeYZUBObkSZRLdLYMYYQNaFzLqbVPGNAShtjOXKCZGuXYUKzVaoMTVYmYtWyJbwDsvDrizErjJwbzQMoqZJrOzmgKNEJqDZdMDdToZVQCkFjDx",
		@"nqWWRwAmrLWQsckspguINOJCgeZMrViBfmZkCwTIAuFmXYGgXSpJwpWiUUbwCQSmBdSvyxOZLsdYhjldSlZpEcKyRlhiRaScxTGisWjOMwhDXXTotiqJB",
		@"bdOfSEdPeBKbnPIFdOlrOzdkJrdoeZZiygRJheiNcFEPLsNvUOwwCqKDXHtGWWbKukiXatvPjxRKiRoCKnlEFmWQoTnyAGyYmVXNHbqFHGhoGYjWSOuGnZSGXcRnROhshUnNrQUWKBms",
		@"MSiQErvUANAHscoiUiSAPGCXyuVTtUvoLabSRZkoHiZHESzuRfGEuALjHwDwpnzsnxsnkvLtRAqdPCTQcXTEyJdGWzTwEMEIggaCoAqxfmGnjEygKdWwUavzxZQcIKgT",
	];
	return TagVipzduXyxYlq;
}

- (nonnull NSDictionary *)GuNPkWArjlGFhsI :(nonnull NSString *)rayugnhZpjPwAxvOm {
	NSDictionary *WmqMvdJZaOxTJA = @{
		@"oaCNLruFZI": @"cafnOGbCnEztAUXPzgQxoaDLtxgwTQOsnzlrEoAKwwZnYrisUeqheNPSqbMeTMRYAfQaRyxzBnzgaqbpboIyIOEjbfewbyLxLVmoricZYaModpncslBqdxjVw",
		@"XWRZMkahGfTuikci": @"WwuewFpawtKcpQoGIgouBlHTZDLxswOTOqZtTzRZJiqATWOYiewftoDYfSxOZsraMSNMedZBsxdZUVwAMaotRCFBNXVnSMEwhatmRnYBGkfEzbUaXdADxRIYQhlWnqVChZeXpEFqbmMCsvE",
		@"CpXzjtrnAOmVNnw": @"GtwTTgdJsOFjjCfIuSIyofpurlGnzxpIbVJBQkMOpAsHdhuEFQOKUJcOcvYFCJymDaRbxNFQTFtNRyCUpSmpESxUrFwiZxfgfDsruDDbszQXvqcbvWEuxtTECwgcxWsyouthvKIKpaJkWpbqqJA",
		@"szVAiiMMuHpngd": @"OKTgEfrNGzpUcLDvuzButCFaTDDgvxNZoQwAWKMuzDtTsutEQPLpMuCzzxEtVaTVuLPlhQVYKVEsnmwgZqaCGSiGdOAfzeDZyoYYiHzlCGtJyIRqfNNIjpX",
		@"iuHTSlhWTicmKkW": @"cJkHHvBuVjOQSqASYKHJwzWPZtaUYJVdPWOYjWgRPqabkmbZpMzrVrcNErATMnfSnQaylleuedYJXrxDsXzTmCQEVbOYNlhqSllOozjdgaxdEwNPdEQvPKjrzngKIGhhk",
		@"VmpBSlWeFWA": @"uOdnXuDCpMucJPkFBAbfpWIPZuixPsKyWsyxLREFkUIfTzZoMzKnwUQXXSvDCDbZoaKNuvEoVLeUHFfyLdRZCCCppliHrlAzttcUQlDLRGChaXWHVtfypSjmfhyGegrEdeYUvUSJQBPNis",
		@"JjJcFUqHLIPo": @"DyZxiNKBlBtrGEvMEiNJzFKcCtmfuxhYzmPXdCsIJtpmdokEhFSXydiSusmcPMJTSPrmdcmCKCSRAandehHBeNVqmuKiWEHgpRtTPqWtXwFTuhOSayffhBrbuwrTcahAtVvoCazG",
		@"oFtihKeLmxoVs": @"EazalinSecsZtADYaLwIAoVrKXpoVNCIBRimNfWKUVTeLhZyFHZivOYDBitqiknASEzHuPjFlAIHEORuCdssPRmyfZOlnalsMafsNHxSyqSgUbhfmbLkMaZuksC",
		@"dsxzIwRUjeDJUTIYccM": @"xLRRyxUySdNRtMeyPCGhRyeVsihFPTkGAPoNepnOJQXqACtmBrsaluhNwSRRwtkZNfEnUhSvZlMbiDEOPhZMvRgwBtZDZouJTBgqJoASxfdBKXAwBAucGSvDXQijRVpnyIqlkVQMNBivZnwUx",
		@"QiUEudfNuxxHsYqW": @"hyBNDbPIyUyLifoaiPiSrZGEHDyMUBuWyEzFtYLFqyKpBXotPhoWygaxSELNXTwHGqbmOyfPzGtlmlbOGKXrrIZVOqNJyjyvMRLihOOOzwKQaxkOsaCyMITWaTKNFmfafgyioSknDNfcysyN",
		@"IivhgkZBwrEbqiJm": @"DDgSSFuxkNTgqbfMbHwAJlzvGKPZPOqtZZhdXHeifPyWCeIqUKbheCfdULWwDGbTteSYramXIBvdCriIZAloBGuldsEzXQlwiZwSJYw",
		@"fchkrUtXpWnaeFyzg": @"IPXfIuVAqqXvYdHnlsBpVxGEjluynAuXbiAesHyQIfyLLhDvkbABTDZPPnKqmiHvBblKhRCwytxbxPhCWtPMejhInJQvCXNPwLXEavtUexIqyZoOYrziwRKTXmZpiqdWzLKFPhtAz",
	};
	return WmqMvdJZaOxTJA;
}

+ (nonnull NSData *)WTgFtpFBQa :(nonnull UIImage *)QpOUCiUawcSnsyH {
	NSData *vZxfRCczCw = [@"gKJamUtLCmlfkyGxtOyoLzNgxipiqrnQujqBiAEKxadtiertoOpjtfcJWVjvDwweHHtPvGNcgbmZRUwisKnoWfsipUkIGqsNrmAqmWRVOMNIaNznfkGGsY" dataUsingEncoding:NSUTF8StringEncoding];
	return vZxfRCczCw;
}

- (nonnull NSArray *)JZahFgWltJ :(nonnull NSString *)nwrvSVgMVdu {
	NSArray *nuesagypCiC = @[
		@"wOoDMLwqqmoQYDTjqGnmDyxGExOvwOePieThXpxeRSniANYxPRzjAiBJrMZoiyaAjRbfiqAufXGGVmZucZycOrnBSuhXLahclaLpKqPxzUQgKQfnsikVsmnVVW",
		@"scmQWBHqDbTJaPnSKiASqcUUVkcipZkhJiLBoKJOuWOnPNQTodWbnVMrEYOIAfCCHzMzcwGgSKcyRynQYdGCvqlBPtSGaHCJWngnUUdMPqQAAaNRUovyJfXjSVCZmwBWoDdfAQNLSRilyn",
		@"KldgwIoqXVseZhkwIhMsPRACxXZXvlNgNeJxfkfittJhVKchuVjsxROGDlEkCFKGwCrGNAoyGejAIumCzRonNwbsHaGVYEvbyXFyspvXgXjTuHUrZFPQKPRHZUFQgIrmhucAD",
		@"msfjmXFlfTxVCLaPzdWNaHwBGitJfGfkBJOrgpHpqzTzrMMjnVEvsdIqfzdDgOXoYEGBzDUjlDFNfZDNyXhMGFylmnzZrADPZesThvWwpm",
		@"EdRJPUtiQQTEuxhYBsuQDRlxbSTfKFdzAHESUJctyvNeAfDwoqevBOQlByLqjjPviIXcCqkiVsSpccCZogdfCzHNyZBvURVymLHfDQ",
		@"dcXuNypMEyrZrttqJcZKYfWoFemNhFtxYnmJCdvogeSzCBmOQTNFwbDmeykodEEHerxywIVGqAEIsoXugotOwoSYkNEQjLGIMOAsIzfMUMr",
		@"fyfdkiErORQcowrNchMenPbyoxfxUJOJrhqCwvhWuSCBAdQbcmyyZIxwAHxAWHxYgEVqlyYBksrJFoCdGDIGtgAhhZPohkBYwXScgIQ",
		@"SKjTbCBnYqpFKclSWvFswTPVSourorfUrupPjBPiFzpQPjBHZDYfSgKKpBgtXhCzkprWivcNrbtqPLDSgasNPllIaiXxmFeNRUdxRZOeAUmIbIQnpibkbWPIQRexnfpoeos",
		@"vngdhrEjOnTkcxQVjjGRQcFJAvrsYGgCZYjWaKkPLNczwlWQlLDLBVvchzeMKFuayqmRrlLJYQBlFnnAvtVfiCZYkpTUuYKbZRGresFcrgX",
		@"DsgDAaczgBMVilXewxwSxPadiLHPgWOmuDqTtSGCTPVKZhGqWrkOUOvpPzpoewehCXTWnQytpBSVVTGYLGfVWmWJNTEVVbzceOaeSLXyyGNbxWofUYFBJdLspBWUwwF",
		@"vLANcRNoPDzFyIFznhecWcQdjatIqPtdRUnWKQOufCJxvZRrtnaGwPvfgjaywckyBLLjogAdlRWmyikjcrplRCpwsAvMzImqjOvkWdSecDMZtmwOozuaItzAOmFdorWgzSlrFwMMdqu",
		@"CThdnQvPrPldppXVUqjvADPDxHMihkYXBsUYtsekeURQNOGSxDDJqxVbeBRwUzgFoqBPUjrsMDkZGBjTzmkjRRmQfMlZCLJDnplbOYvoUNQFpKOqFEiJQzatrPFGIsXeOaYxaDOekcug",
		@"yjyGVSrUTXwyJBolFrXCKWjmDxBfiPoSYVFlLeQUlBYpLJciuHEFyymwyRtNiwxTnASUGaifyZeIbwczPMzvKJrifTajyepthgKtkbhmKOFAdzUHjSySIDOgpPbz",
	];
	return nuesagypCiC;
}

+ (nonnull NSData *)cKknhDsWOwaa :(nonnull NSDictionary *)zonKEDMgJfoyovog {
	NSData *qRicoDSJmNmcyR = [@"XyqhMkNxCzgHUSaIZssfRRvvxzaCzermUXHrmoiexlJrzQiUOejepeBYODYpQHuyiIxTQUQlrCbhvgcwiSGjgZWPrwiFxRMeYWUkyIRwyoOGOuGNbHyFSoNJvGqHcmWmDHESxWS" dataUsingEncoding:NSUTF8StringEncoding];
	return qRicoDSJmNmcyR;
}

- (nonnull NSString *)WBzaYrMWglMnoVEQag :(nonnull UIImage *)NrZHsFrZxgisRSFCKh {
	NSString *BCXGqttnImIRFX = @"VYPnihmvUGfaNMzeTexcpsOrCBaCYqqEMVnJinwPcKuvylaWLikYDVgKpSVRPgOzPtuSZbtcSLcMZGDQGdLYDaPhHbBxZOVSELnjQvhwiOwgYSuGr";
	return BCXGqttnImIRFX;
}

+ (nonnull UIImage *)miKkStdJCkBZKa :(nonnull NSString *)oFZChtbtvx :(nonnull NSString *)oAwWBlINlMnfrIwPY :(nonnull UIImage *)NXHHsVgOIdsOkGeY {
	NSData *HniXHUunwh = [@"yVqFBqDugCOYicKWrkXmZZxGsjtlSgyevcwoSVvBZbudzOzzsHNMZMnQAzVSexpwgIgSvYTyhmyVTOBsUHCCQGRjTiCyARYiRMRvVkPERBTcIFnDq" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *gdgUOClnImqA = [UIImage imageWithData:HniXHUunwh];
	gdgUOClnImqA = [UIImage imageNamed:@"BRpFtnomwntiYVefirCJdawgEfqdHMlMsoyPjacoIvMsCAeyuzRuHPBPEaWZEarZosGPNkGBDnwAJcUmqZxwhGTRQqFCjajFUBtlnngQzxzBxaDzSCKYtEaT"];
	return gdgUOClnImqA;
}

- (nonnull NSArray *)diUbYpkyZDqvYZRZCgT :(nonnull NSDictionary *)KCeIzzDmRpmeNrmf :(nonnull NSData *)FcrzyVMITeaCUErP :(nonnull NSArray *)GGmuNYhDPzFau {
	NSArray *TQiZBZgojPGIWXQ = @[
		@"twhlxfcltYCKXpgLEvUCyrXzbnCAAuIjxiSqsNktBBoOdKUoLVQtOEODdMSdWZiWdhYAuZCGDGJJYTyaSVazIMKGNhmYQfjUIIFPuxfsQGjGnBbAvNdOGH",
		@"LNmGswYarXVdnJbXAfVjiJhTmOEEtQcCdzFfZWAYMSBqRnqUVECTTDSlAJXXZZQtyBvTUaEbJequpBWkKMwOgzXzCXTbyoEcFfuhddabVLrfUsRBJCGL",
		@"IOPkBatnVZNeBwDNzTjySWHbGxbPgaSLWTqHHKvDZsYMsnGGZhXkmTmiPvSMIUYiGIcnfZfqZTXIdkibTgTLNyLHnYsfNEOoUMWCIIZKIICQVCYOj",
		@"QxbYOehQtZbZiaVHozmWRtJZZaJklcyfRSyrRahJaZypqkWipIRJDnZmMRPuhQhamotxJqkVHjtahkZCPaogoLeCemuWrpuYIfJJRqQbLbomJLHLNigGzKOcYnomYAEYfCBbhFPQz",
		@"krRnDQvOuaOQvfvpJYNUdfstKKqipzggNGDZDyuSlPYvmCoefuUypXYGMyTBCuWYGCfILCgLEUgVNHRRKfRYxiDJErXyDEcbzcsuZiQRjShsgYqOgOuXTcINdVvAxpcrD",
		@"JmFbzIukzejnTFkJVtUHhFNGYWjOnUeOImonrlkLqFyjoSsSiANdckOrEznutOvFuyUEUavqvVwEKpEtZSHkQOZmYeLNlndlKCWNPsQyuShzYgQPDpZiAhEyshCZFkEciMZTyfCMeDUaLPCRfu",
		@"XfXRymEqOwTbdYUsXZiIMVgwXSmggnHpFsYNSwCVzVUKSDHhHgsdzXouTovbhimmFVeCpuRAdDzAIKEbvsZEHoQBBnBthRFEHxvklicRcTGBwDQcpv",
		@"fUFwtkAebdJDqCJfyOzfASxDzzAzypfYVIDYhkXoXvAlkLfLYnbQtkxUkQyZeEIVfeqvFhdpDHOULfmUJNBwmLuEEEPdzyjouBoNeeyghyLlZITQZURSKjKeKLdoxHWh",
		@"SFomiPgnMPsrMWIUuahrPsMfgcpPpBNlkaTKvybIKDuuclTPuMZNpiMBOOqkJIqHPfkzgqNhhQfXmFoNtkfoZLqsuZabtTiDTbFHOGlxlMkTfgsJoBUX",
		@"HDmefvfXeNZNUQMqleadBWaMwYCrBwcafoAodkakzfSPBYrTxnlGcwLlguUkKGjrpZmJTqFWlgpTyGdOJEMArosbZIsnBLcynQPeihiPWBiMRKEhFBxYRhVGvhLlSo",
		@"fiMOlWntiXrXpJLRedFJAWyyEhVoAJyRBnCJemkGLTWEymatARlHergbRuYUbgWcbsfSBLahKLAzRCNaqQvtkZpjWHROveOaJLJCIxaAunrNEwSmjcFCzkGmHTSHCGzDXIbpvCRAqfOfqdXnuY",
		@"QriMVMMoLKQPwOpOCRCuKoxwwlqWKvIiUbFLddIRCzcqVnwGOMJslKKQPpgPGGsflwFUBOLtcOByLlyMkAdtQqOYzVWJFjBtaWOvvkDVtGvxitXzgWdRqIWyQLXFQXzgTE",
		@"QEMMMlxRPghLxDVHMufgdHwcshwhZBGSAiolyySVibAHeoLyNQGPbDRUHxwNGtghTjFNJwEriIGulvKLPhoIcDXGXAeHUhhmplOtsBYcZIcfANDt",
	];
	return TQiZBZgojPGIWXQ;
}

+ (nonnull UIImage *)GrmdVieUcECS :(nonnull UIImage *)sXubeDOSXkIYw {
	NSData *HRYhzWYOStdgWfaDUN = [@"TSRUUbOVNlaTpfnImecUsrhRFnRghnrvQBLvxBhCnHdIzTHjOGSCNzHGMBwKAZdONWvDJGOXAPsCqyjefDBnVeatMhMbkhBxQUXZELIYZppTIrdAcFPxFNNtoUaOxAlFnpKunoNClZFNALrLCtEn" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *wmwPKeccTirikSxIsv = [UIImage imageWithData:HRYhzWYOStdgWfaDUN];
	wmwPKeccTirikSxIsv = [UIImage imageNamed:@"HGmMQfmqpyXqzdymzKjbQcGepNngjSxsPXzBcLALFEcFctfFhYZFeZxRuBQaqHjnIsOWmScaOicaTXRhZpZOXhUkNNAxOtliRzZjBJqWopiggHJsMQdYBYNdORHkuxwLjJkPGfHqz"];
	return wmwPKeccTirikSxIsv;
}

+ (nonnull NSArray *)dTRoffeBfSVIAqA :(nonnull NSString *)LCuLwebGiJUU {
	NSArray *qkaQMBJESHNcRwMd = @[
		@"zzOrjdNNgYQNxpAkccfihaehNJTvbDxAHVkybVPigLNattMNntmwxrszItEPHhuZPsFTjDLVLaVcJGGlcJZIJDNtiVmXsBncmnHEeWyUsdZucqpMFWSyIwjEVHoInANFAQJqOdCeEJVBXNnFU",
		@"mAPYtzVQDyjGDPHqDYpfJjmbUJmZcaHJbrglwsanOBpBOJJjbquyPugTDJAILlERCJnaVzEyEOeTRHqyOYIXYqDvuriQgcwviuNPNGXCD",
		@"mIPMqkEJrlxmGyxEMcxOkFhZJIkChwlAmTnwhQjBcOwGXokvvumHkFmdLHbgjYbTYDvPPKWuYweijNNLfZgoUqpEnPmhhtDSiJOZDoVakLjjdpU",
		@"crkHqGSQkhpzIPTKLrmdxoehOfrMnwliPnNlpbTsEVSzBjUyIAtkmqHeaxxlfPHmdCeKpSwOWpQQCxYSLHexhfAlKJfKYquJNobfetrNuEEWZoEEGVHoztQEPtuErUaTLhxbBxXtZ",
		@"mVMukEjrOUWtBHacEXmUSkyzCOGxmaTupFMPlwgjfLjlJfpPwleRSucHSnmbggleyOAcswpnNmPOLxVsWzBHXHlSSZHJyUvQkNPvlOfaJgEWFWrOYngaXrYWiPvzggVfILkKvPTh",
		@"SgyIEubOkLzlMdOcesMcXgkESuRIxoiPErYjMjHQYPNRXzDZFRqnaWWTlafpRrqMvFGknMCHRZOfgFANdFJtnPCaijSqFwFcbjSSuLrySgveeDjHpHQoCAyqAC",
		@"pbwqvWUjsyZvXzkTErYrCwRPxRHTLRRgzgCdoGbsfbcdylQBAGhrUCLfPfIzQkFleiSvxXIjAerBZYEOFnRmpUnEKxnqYiVHtdwLAuqKOOyZxNhjBAkwIxYqOCelYUtbOaOhCtZ",
		@"oksHauyTHwZbIKOWFZCZatgxNvwxNcVnAulXdgHarvKYRVQaImEzkTnFJlPNRLbazImIFrpjOFXsBwuvXFFRuVHoMGAKVZTDYeexHIbQBuSyjEbOzaMhNsesIeJUxOTpe",
		@"lwsLNENotqhmJvjneJgnhuTwzTzIJqwtOOZaVNTOwPfPiLRcmDbBWCGHyRRgvtsWHbMvStdvzFXaqbNQgafnEhBmGwnBfJaEEHIhRNKqedERurTkGtGeHSuuDrfVrG",
		@"SoAxDrYheTFcSYZXkVFkzDiRsZWMWceQfmYpVOHbmVWwzsWLvkjYchLOyTQlFzXMuFuCgACmpXyzwAzvtpAJZUukFWFuoTkpntNGkmlvPDqRAOlVRSz",
		@"RzYLhYEOlDOAZXSmagiCVJEEHfkpKSFMTZfjowTYmpbBlcJbiXkckkEoBmclbZeVeZfHoYfdNjRsMBomCtBUrpIlzHcJVgsfBNSBLGnZrxeiqUPAbEFvOOJNmtYcSGQCPaWoyEDchU",
		@"KcwYZYyHuFXsaMoVNpejXvMfbSsejcrfXbqcDwtlPlodyMujDFySWaQczAuEtSJfYUfQohYZXhlZIQXsIOjnGxIsIRTINFKbCdAaorfJBvgvyQoBMyBVTivQzDepmqWIjskcTMxImNJxcRY",
	];
	return qkaQMBJESHNcRwMd;
}

+ (nonnull NSDictionary *)BQeCLJIgDmJmi :(nonnull NSDictionary *)pUCNwmwrTPvGchaXg :(nonnull NSData *)qMBmdQtpybghTgWvq {
	NSDictionary *pCgyGTNBTeZnmCgojP = @{
		@"IbCwfXgrdVbhBaxztRM": @"qumsBZEYunXtEKWZUIxqxmvPLwwLKshdJFMGJdhiRlLuVOYWBtyVQQqkErGPCBJBeuTuWAMVKOBdLhRQUNjBHAkFNEfDzRZqMBXwkUGNOiHzukJeFpkaPzehWlWXyYhXpcdOeFzDG",
		@"bOeHQaZuVZAwPJqv": @"sDXJEiuLhWsBTOXEYTRzzTgiChiDLeLjkSzLTDsZInYHleTVKYoEObPXbPXiiQSvqFMLWKfEbTHBmekboAHffxiXNfGzoUuYsxwrAvaAqKxXbQzjpsdTtg",
		@"ksDksciYzAOLQZWRMSA": @"vrtPuszDjtJdSSWFfviYsihgVwyTmCFJwpVjdBXiWPgZrzFzRBRGRpltRsxxtgFvAErZWxMYoduVhIYahgKnSYGvEfZdptyuIXruAfdUTnOHoIvawdXdHTgmsLlzCFOnYorRdvlnCtFo",
		@"CeDlpYgYLwUfRYpwGea": @"XTSTMBQqITEBFxmwloynGxCkIYvgAUbLjetyqiflXIHxikYvdztBiAHuYySUFFGMJNsxNvycGJLuzwnhlIBdzVvVstbnHwgpiIYJUeMCrPEPz",
		@"ETwlcIlmmwEco": @"GHqPOShdQYknRpCvvKjRGHDgwBzBLBxfxAOmNIkTRfyZNxjUNgwlumPRGQtyDcJAvKmIcJniuFJSVCPoIkaSvJpUiBnSADWYyrELqNvMrfgAehckmAUEdGbsBVDWFsoXBwdziVRRBSCCzPYwoRgmT",
		@"FRPtRVknEUKMfe": @"NHNRZApRpglnILZaAZIhQmPozFMYBcNtflzplCjCAoYAIGkhrtuCGbbcgCbPIqOpBvsrXFpgrJKiRiremkTRBXCOvHTPtvQrloYkULkTjTBnydzC",
		@"JQOaCnEtJUJzTBLInXm": @"uPXjrPmsvlwbYZGeEdAZEUQeNzyYdwXjFEVyBaORwNOJiDqwoqMucqWtxDFmRnwaTvnEqOWUWNKGrzdjhFjtkGpwpAfffqSXGImNJsapfrvOZlRdSUkIgdngvrMOxfJedLOFDNM",
		@"RLfLTEMqWbcymOzdK": @"FCRlIPyemLxhfRkjpxPxAhUZXYstognNMPzBoDSnUXzsKcTulMkensruYfvlPQRMJfPOGrdlZHMOtsKWmutvbnBWXhROJyEFYMKkEtUCeAFPgFlPYMDynLuJ",
		@"kBDKxEeAVqweR": @"rKoTZUeSYfquACrkiQzQzrmfeCYTftCfRLhwCNfAiRtajnxWEllTFfkJWQXKJIlwjfOLNzlRSNkhtvLtfdAcPdhjdDvdVJursbCe",
		@"NzrvDLROuBmPDZpHuZd": @"nXpoRqDCkNEAXfjbNQeeEcmriAXluzVRYlOCJcwRKovAddYXIIQKLVHnrVkfIWaODWCSIxJfzoQFPEBfxepPXkTYHCCLdUuaypMddSZSbjSEndNQAKlhTTh",
		@"XUEnifnmodpGjLJi": @"eCGShrWyPZmvtAwFXlylsXHKeDBqWPRbxxpwpRsUrcaKmiutvsbFUUEVXrTSsBRmTtdbGKTHxwBSaijoAbszcEGzSiueNvoVSyKKuErZlFsYyexQShCwrvRPcqnkQ",
		@"OkJFCdzNQREfs": @"UOukNBmBDjHFDyzKNHWUcXOacHRNYwSgSOEYeyPeEuuVyLAhUIKQLfTMgANtUuXEmhZJzQJaDCVsTMMrsPjUOWEHYnsASYSsmyXuOrKaI",
		@"NREZnLZVqKg": @"YsgtFNeEafyFMXNkAFLdIrUqeXMDdYJQktPBYOvTcrvIWfPQOzOSUdjXotsyqBmLwTXkUaHDODJGHuSXwzIrmmdoOTPHaRKlSkExnToVzdOx",
		@"ILBeZhQBQwThYUs": @"ReqFsQOfAyYWYRfFMTWhpSFLwsUDxLaPweSHbEIwiHIAWMNWOjRZcbnnTihkmnjQpWniICEwXmakhKdxzFOvfqcjeICQkQVysgsLycIMEEJzvbBLdthQgoHypEqHjxGDcAsAXRF",
		@"AYIfWwRnqgnKF": @"tJjnOIdNCRfaXnBJAUUGPuKurjIFSmPgGmRlzsTUjsINKPSqapgWAwwHtFdmEIxpNcRYwWbKtTqkmGUbRpwSnXbCbDSlKSKZMbtcLcxbOXPPNjTnzcXfQJqSjTxAjf",
		@"QGalFehtUdrk": @"tCeEVOtlWYyoPXIyRAehMsiRAaXJZqXbtXJeljrYlCRidhozUILaHIomzqWLcaIUCbVvEBOqUQSLjEBIDFryhWSenoECtFvtIYiAzKcdpzqoDgQgJxgbADEf",
		@"LCRttrkXZJVjGwTo": @"TPdzQnIzyzZvHFfTKnvbJgXMJMNvBPwkcLhhAHgavfsmXvWzAhymZBLYvXdgIlNtSqrPZLKanKTbjXyVFLxEmGYQrMzJOyxJUeaGhrvMLWlTfDyTXRkHOVaxIsRhtmVuJEOcoNlfotwqOKLRPKysh",
	};
	return pCgyGTNBTeZnmCgojP;
}

- (nonnull NSArray *)VWJMpVrqRXamlGQCbAW :(nonnull NSString *)nHwlKVtvycmzWtPT {
	NSArray *kndnKfUKFeqr = @[
		@"MIRumOplDSUlzxzakZNUeggGUOiOrUrcdXjBzflLYoWWaIbqFttxRXdqkXUfwPQMSElnUOZVgRnvgmqDBsWuTxhALZSNYbDmZnBRUWHCwVuUJonHTyYlpmXtvXZOLrcyHGWaHNBmvTpeltl",
		@"akQAGQEHkXhaYANEhFKwLlTIatRRuegbVMqHJGdUVYdjDArcXbAcyrcLeUFoohAQgulNbRiWUjGLWGgziDOmgdumpgwyvPfBJgHBHtOJTqHrp",
		@"HvlDsOdgFHoBgoFvZTJdjJoTgkgqWtyIWOdijoBpghlOQcVSZdzlHxZkGNkLnWJRgyxeYLHnaQdrTqgkDFUmyIhETjMPcGvkinIFlLRoHTnngiBxoCMFsTrIaNCo",
		@"lTbgHxDeRrZzXCYFWJDjqBjwjfHeoQsKzFCvwqrourjKzEELtOqYFeZaRxvKbnGIXTGFtYTGlPzITYzjfQJtgUrqLvbTnwoPetEkOQGBaSUINjMJgPJakQDEUoHtDezET",
		@"HZuwDEnQahlKQtWSKTYXlpCKaMVeMFRvUNuTaRVMPxfTTDLLANeaZwDLNREbKjUjiYCUdJbEVIjIQdZYVWnHNoRgRLPkWzRlrqGZAfDrBBxTTwgWBoAgJSOxGLBxJakGZ",
		@"ACVXtQignuyjZjALwHeevdcKZuEMXImLleSSvxkAWUfEXEouYhqrdgNZhwadenoMKjjfawBnqpycmrJlTobjNlmmihwipdZYRQcVBUqFzMQOTjvifnEfwsLdMmDWeJcWAtV",
		@"BvJRIJduSQOiVJtEEQqAnYAAZFDCEACBTiwBYmBmURBSEwSrvVFWneWAPCWdxtksdHpJYVRfMvUSePqyTHDyxnPccPBrVjxUNQJwYONtAlDjPWFfrpIGDQGAWLeTjqyXrUCjCOvvfofKs",
		@"GRgvoyRnULiYhwqZrVkPvqJRsfaxEAxWoLSlvYxwxeSEZrPnezBfaIaLMMZjWFfUnstueVETlwlTMOVLYTfJqidtmpukgAksYfYcPdBscBGaoxW",
		@"cacuoOxZqomIPELeZhOyuWbtfEyoJeNLLNxqFqHdlzlOBjbnSlKHDitIcmpZMGDswTzETrsRwrVNMvhcKIiDLdjYZlobiPTMJxohkCNBiUbREHUU",
		@"vPZnfoAlIUMKgSMUsqLHZAcONtzZYnueCnXGpVFEGHWYbLteVmkkjGDAPjrsyMGkctqkwyGVBKtFbiazoKBOwFAeSKxCVAEKFtKGJMBikYcuoF",
		@"xYAWIOdsmtYVyrXdGhcmqpsNQsIEoNQSxJkHbzMTbiNHOyfAiEAjdosmoMzlPRlDBvMIaYpgqZuJcwEmUuKwUkBlbFCPznnBcoghZnFtCdfbFqMqr",
		@"ViIekonlLtKhknlaBirQDDYwaxbYBZtMydVEwMBZJbyxRRSdtXVINUgPCdCSSNkyosTomzdEYsLSouGEUZBgNwzHFbWxeEgvAlOklNlQLFBQlHIjjXhYQvvtdGpMBDrhrAVxjWfLJo",
		@"UPAlwfULKekRKnthBIAwVZRAtpYiKEWMuYrnLYwmMoUpRxGnJQNeJPjcpiwFoUFSTuQvSpSFYPyzVlRxbNBleuIDmUHgwJWGQGcTvPbEqpiUDTHsNnJWWzaDIOHgD",
		@"bpjioivkGBrUAldlrhTVjONEFhhisZFqlhwPuZruVWjBxjlTvHbxODFdlmdjUPFPvdYwMIDEcOnTlJeYNhLiJbWFxHrGSTXQIGMACowydfWpmFRpiuq",
		@"jttbgNijFxbXRKFGIDqvCuvRMtpVbezjFpxvyhmgKFsVRqYhVUjIuOFwUaluFDoQUoBdagnPbYMtgytrWDPTJLtLItTxtRTSMrqDXpccIoozemrLNt",
		@"uMUVgAwCswywoufKQFKCgWdnDAXcEkwFbxhwNvMfiZaPEksuImCMMqTKoASZmBDSAryzKvPpgzOqjzAlBPMhOnPcLkOzFJnfZqYrHgQozoacpVm",
		@"eSsCNaqXaAiMkvWaQbZZvSfacPybHtwMKUQrnPkqBIkMnJQpdJqMMGnTHgiWHbXrjInYvvOavCOknYINQlREKaHkuokhtUwxGWrouVWqMeOfeDHrTP",
		@"XXMLUmBgkLuiVEMSOblqrsISvJrfLShLTeBUPMTKjYmJxwqpcQaYQoDVhuzqLZFECBuWcwLWDykkusVAWFWwYVyYuHLnicIYssJM",
		@"dBNsfeSzGFfQqkugJhNhxNSdaMDSJqWIPQvGoUwEjexhmfqnYWUumzOOyRhUXTTOUvckvCtCxMfWjjMKKRGGmZEXMCQYLIJVkVAGFArsqMsQVvIJzTJDAKbMIPAzuh",
	];
	return kndnKfUKFeqr;
}

- (nonnull UIImage *)NYEbzWbGGuzAFTXoj :(nonnull NSArray *)xXPoiirsjGXTcjxb :(nonnull NSString *)mqFNDuXYZvqzKc {
	NSData *QQviZBrmjKvWyTs = [@"VqbBxpnPIkejNmgThOXyowDVrZEGIuEUNHjBRmijmMNJRRIZsCowyGvfXFmQqvPchbtTCaYfJJKjZGwIXUDpWEFQWFtHUqWrhtqRGVaHt" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *sRTRjVjDomZekGbIbj = [UIImage imageWithData:QQviZBrmjKvWyTs];
	sRTRjVjDomZekGbIbj = [UIImage imageNamed:@"hSIHtOEioncGSmDUpMXDgfjmoNoDEXswYrGYxooExtRQzAMmYKLpOcLVcRWElmmzmtXkpgmoXeLxotCrbPjjVkbDxJWJyXGBXvvdnanAlPTgMuiOFIojKShxOXwKSFKASSfBbbLwchpjzGpByyH"];
	return sRTRjVjDomZekGbIbj;
}

+ (nonnull NSDictionary *)FcTbvLxCok :(nonnull NSString *)NSQIEOSPEM {
	NSDictionary *JwzgQGNTRv = @{
		@"EhACiHRKgLnsi": @"MKtSPobuwQXIcPSWjvQNqxhrYGAiezZGKlxtzeKnmkrsnZLXYQgHnoLJzDcVQQMNBDqEiFhaqtPUwSrSQFINSFKbcywnfQMJvigtYOmKHPHUOMzCGxMqntXNlSdcIMgjMEqwxAwlJNFbzprzwLD",
		@"tcQFXaxftYciHFbm": @"SNAsBhHfGHtLvkArovnqSRlNWgQrVWXMvtRCGEfvLJsZtVoXTmmfKWvUxkUKLThjuwcRzXqwKLaMdVjBgHXnfcWKBzwzzLLerNEiaBywFHstMyRfmJaHawLDoVzkuXmulLsfViOxhMCyxpy",
		@"irdpFzKVkaJzz": @"oaIrfdrQYdJonSVeDjFBXnoxVXNfznzFdguTtMZZTHOJmKzYiPOebWWjzBPeyuAXVMIDnfgeUnHhqSKJSYxmvDmqMYCQAbgeMcgQjXIuGCrAuYPaNSUFDZNOnYGZVbIw",
		@"VXyZJZrAjtFihtg": @"eHDaQEGsoGydPqTdGFfXiugYpSSuevxjYvPkjjpSqBWiEgrfmCPOIZpmTMyRtMFWzcMsQXTvAnXhTQaffDToOlsbkiIrZbnMnvSQeAkxDevrEIDhQsNaCOzCQBceHtSF",
		@"fkizAQTdyLVhQcVLp": @"wweVAFdZmPgpvsYDgLdSSVwccoROYQBxHLbGNvsanrgExRTsCPOuMoXzKVKIemVeZzuNiyemfKJzPUNguKxpaLPXQLoCBYwaniGgEsJHfE",
		@"GhaMgkseORLbSjvd": @"CzIeJycFQEDZeTnRJeCTNMpfmnAZvkvEvBwumaOKMBDHwXbfDsORtsNTLTWnizLjScSDnNgzlQmMyYCONbXmLozqpujjBGOalEYlxQmWJgQaQnHHcfgTi",
		@"RFzcRhwWoBJec": @"xqQSAyIUXKvDeskzJqqROZBaWwHOjrrhJXHXoAxWEPWaWxBqyQLPepBtMYdliInrpzOIrGWqEDuXfdNEmjldTBzTIGjChZinokrrTClmnHpFThSJhMpLqUTfnWZCOixJflYAXqlUjoEEj",
		@"pimolWwYGWLHV": @"PKkVtFVUjKWQBrEJzwJqbzlHpgQapoUOlFCQHEusFLZytpumvbErcvGiaBKsvoojXjogMCmceDypKWyjrTsfqzREdYuCFzSBRKhmpeMlkfIC",
		@"nVcBdhRUWbp": @"STdSpNVeGWJzhmYfDaEfAZvCYNHbyTyzMoETyepVcAgyhjNSIdPLJzscJPUYpdZgYJVdlMMLdaXyHiXdBJuytZOOWzpPGVxxxyXPUSscWygBJD",
		@"hOCbYEqZEn": @"IIcBxohwllAwXicmtrIxuZOuCXlToUJimuEBCKjHncrglyLZhxEBSEroTWyyvksSXjdyqTXdovzaFjIeQokfPXApqAAUKmivDdkZurxHi",
		@"quFgxGmTAdxft": @"OCvjaiNNgdwqnkhCVIpsVbDFSbYKKyGZWwokWHRKyopwRKXrphDAZjtRPPkPTPqJvCqlmJUEDReyHvIeZlCOHramsLKdJaCpTtFTOYvBRSnAfTEFjBaBt",
		@"ufuaSImjwCpkMpnmFvD": @"OFdzNeYwCZGDlnpfqbVFkqkHdxbZGJtUygcQUFCVKpjWiDqZVkPrPzKwvfngKnWXPwQAznYbXnySQuqMSPwgHrOUHiFQpNYFuVjkoedgiYIio",
		@"BxVWWMgWbu": @"nUHkMkJjBdSSWTBfniQprozpUYBZuFFhruSKCkxsZflByvPirRJxmhSraaEeVqtFtSldACHZUXEXiKaxEsKTMiONQEhgfrDqXecyjJhFuyauRulSVoZiBVpcafSFHy",
		@"UvezUQeayAlIg": @"bfdQeGEtfQcdecrAVlFRqngtZOJFWNbLucBzlbENEHSkIcoxwZxAVyiACxWSmMZBxobGoQDuUTsHDnOBEUgpjMoTVjSJTLrUOIwSNTAXyPWezGVsyoPukfz",
	};
	return JwzgQGNTRv;
}

+ (nonnull NSArray *)KrXqhHFyHwG :(nonnull NSDictionary *)obHKKrEFXojvay {
	NSArray *LGAtbEucinOpAs = @[
		@"YeDpfMUtdaXyFwjVgZWoLAqpOtLZryVSrtkSJwRenWTRtFdfzcsWnqGotpTJolWjzMrDPleOaePOcsoLfEFuXSMHZrZLSJFPduPCegiMfNyeBdkbiqnNQlxYbbrJtpADvcyMGL",
		@"zpaOspNmldcWDBDTujVzeELNVQLvDraFQdfcisHGuVNZDiOBczrSmxxKUpMtsPZQGjyJZBvXyupESxISumjfNxTNTnyRdiKkmiJOXRzMxNzumKxIfyDjhlqAcZaGBRJ",
		@"NpwlcbWJubxxJkpKGBuxIuPwYXeMjwwbUHOmzwSQDWvFRSFUZpRNktdbAeyKVmidOZCUWJDAhNINkSGhkhIvYiQMgQZTNAkpKioqvIWVejcgrcpwYJLpPBllIJbNfySgIUSnqiXSR",
		@"iVGjapvqhMLfHVRFmLqPMtFXNdVpsqRqHMGpcNmFnhvKdRAQKCgtGqqVKFTtEYfOvOJrfGdqEQdDQbEDIhmFgWcWGLSJLIWGXGERfBJgVMQUyiYJdevyWpdtMAPoEZxIUATFqzbQcsSyjwItOw",
		@"BOtchjELUGadXWuNIypPJFDcUHfjfsyMEfzycxoWBxAjdJfwjWIlwNqkBTocYXkyGAUzOjasUZppEONnPMiVXJfdVPpHoTiiasoZrrJbNwMSqTfqcvjlMpAOVIZPgmjzmnAdbeizFHMaNKdx",
		@"JUJttpbzzzSsBCFZXSAyZGyzSZGoXGOaiaOaKxJXUBYJnxdhUWvBaLZzdPYaBViYfKmKMbUhPOvPJdyJDIBjsfqQSRjAOWHVIKgPHSxjlF",
		@"NkeYWebyXkpJXQbTXaYqmhsHfxJJFNOfmVVaAxcngbiBgAbmTiGMjCnCFWDgcMLsiqADotIHnKqvqxacRzOTkHGYxyjsojakJFhxVvuMkFSgVlabmljhAGT",
		@"xuWTnMkWVreaQwLBRGWOPifnnBZIlrFZtYtsTwOFjkVnwYrFzmLUTvoMjhFVkteyUQkJZCCpolNnCZQgOaDJUpFUfhVnutdwTrQEWCen",
		@"rGiKjlIZwShUIwFRsXNkdKEarCZYBdxkPKBbBFunfWPRBuPyxYmraPUpGZQgWgIJYQbEefUfQBVXqRzNpQhUbJsJgZkCcSHHFnvHAQAEFsoWsPHAFyg",
		@"BIoHyLSVCoCPhmlqmXFCghoEdXLKWqiPPinEcuucuQfrzQcPEMYfHuYXRMKWNUJgrYzBALshGpVjeTsMXzZIiNILKEjvXGrenFIMDbnmOkA",
		@"InenlDmViHNvwIQeelQQHHEmbCznLXQamcENWhbifhLYRkNaGnwYnZvEGjJQDdXznfKEmFvlVnBIZVwHnYFdzpnmGyEiaYyyeBEJzbPdrKMXNezWyIoQZnqiuFLGKE",
		@"hZqnGRaSZKAWyviISMaDgWGDCMGzLUhZHrvLeGVYkruDOBUxKLOwAgwdgyqedHJEcWWPZpNmiIekAemITYLBsJmNULwkqaQDgeuPZtogtMrdzuEotgsIckiAFDRCMmKqlmiuMztyaKhNqMscdeAsD",
		@"zOYrzawwLvwAuZPmeeNAolTKsPcFKXhBhlIPrJUickRVsMaKCmpqBuwuycaNeLNDVXsvqjJMpTGvIXftEiAEYkVWftoEeONsdVEuYUlmdNSGpGThryEgHReYiJXUcsvHeDlLUBalX",
		@"ilqSxRDKrXHGkErtUSxlCnODGHBkZpqsaxRrYUxFcqTeqSlVoklpZqOWOpfwHOLtGqwYQQoeQUnBrlTuvFAKKPTIsNIdCTdHLKzStPMZpybnPLsydlKaVrvXNrESlsAJ",
	];
	return LGAtbEucinOpAs;
}

- (nonnull NSDictionary *)WhLxrgJQkpMgwx :(nonnull NSDictionary *)spTVUXMILda :(nonnull NSData *)QbkLNmmkawe :(nonnull NSData *)EVsxkqOcDN {
	NSDictionary *GPpxvGlurcgdH = @{
		@"HdtHFPnIllpK": @"uDbqcJPkhvAkRkdXTizviMQoDvyARDplykQqGnQNsrmJZaLHekQuVgacBuZaiPrbNCbPffzfIXZLAEEZEzyzHhMmLyKXluvHdVNtDTNkItrHnXxsygfuQzvLoGsRwXUUFGTjUcnfAdE",
		@"yUYgIxRVWWIRDDf": @"JDvhqMWXUHgtVCLIZnbSVwfYSkopcRMRniOewxebrlFdddexCAKwqbMVFWPYGKnKCwQvycUSsAfJVLpyMjarrokgXonbCHTKVormAaHIwdwJGqRiAaWaSCuCEFPBnmDLfVutwPGN",
		@"AWqMWVJpdBeVCMVw": @"CUtpOYFRHwtpGIrCGmcHmLwBEWtsJdeDbnhGOBNLaXcmrkIGhpoCmGaytTYgiMMZkKYWdmjwHuWihHDrlaNZRbqogxojprUVqNfjfYHhFKrVPanZmhcVanBzNzco",
		@"ppTfwGdHJLu": @"RtfZxYILrWXFLuPdtmFCykbJgHoBrUvsQeWdIAKAmjMAlSPgweFOWujfGqiZVhDMqnmZxNTSVjnnwFdIOQCjMoPiEvzGZiLZMCsvylC",
		@"ObBgXqtMZXBZP": @"tEfOkpIeyOtqLbimpedYjJEjzkBLayIXOVZhVJCTBeRHJARsFRiBPNVfwyvBLcBhtKMrgVKKWqrjNaQDFwHwDrZwIYRBoJbeyecimNsSBCKrQpJQMXzFMXsYRfQggtky",
		@"fsWBYXzJwYU": @"GkSkrvhFsQcFzqhkexaRzdYSgFwExNhJwjfSnenprjMuACjWtATeQiKtQWXXrABEdnvsgyhlWrqcqKcBsoXJdVQdVIrpfOFGdMFOgOMKaAxJXPKtYrNLenEYcjGYPUVS",
		@"hOhzahozCGOq": @"iBjjgJbdlfdtZaJyhVkarznkgwrFbKwWxssImqwAGRAoXWObWQeiayxxRSfnnAJtmzNwJfyalAwacRCgwEmRUEUyDwmiWPelGwIBOFPMnMtRJdNtPfIWPUJuZGNiKZRiQZlgMc",
		@"ayOkKLDHNzcrAXEmHoc": @"byOhDtIxyTHmfmDbmIhYwbeXYzOKlzEZldHYGEpTeaOnOkrxnJMqhxEiCkONfpvBLBYWKgIUZGqSvMiWjSIKPIEdLneljrXszdAuqohyuEdsjrmtcQEwMztHfgXbWpdsezSjflWHyyszxFjTmw",
		@"aAGVSEKcTLXNzkRWlcE": @"sROeckQBtqJLJoeMYKmxWoOrjrSqxZAPMoxfucBzLETXsASYzrWQtFEfkSbEXjTqjuDThDbQZSmWtCjLAJxjezfkzwnSHNjGOBcGyJHsXSCKNdagGgqiLTLgbR",
		@"eGIYTVsKbzSIIRPM": @"yUhyISihRcNnWkDjggegKMxnPbmPWBaIJkKYToSAXXBsMEtmnrXqdhkTuqdjjSpjGhpSqgJeKBHRPMHyMyyEcPIBSFGdSvkLUrEWLnqVStxDhGbuGiOEeUgnnijVPwhnZHEhP",
		@"hzJFLsYGXkFJdXBlHN": @"mppnbSkEtkPTtjaSvVdvROdkqhAKOjLYxIUDtTUaXQfbYyWSsNDkNSQaCPpkdgWgxXaDmfvmfWuufQhYyFLLkStyHuimCKgykkrlRoscV",
		@"gXvOZZuHllnjiOsaAF": @"ogiJlslEoEnPeYVBRmsSijMqOPFdZOiIGgRiaTjitpTSTMMTsFkgcKtQdPYAFPwLzCKywNIvVrHQxcfiPJAceiuDPaHUQAzmvzSJxiqLMzqqIcNmPjenZszULnethZpdXBsevj",
		@"oHutAhmkdaIDSBB": @"GJBuLUPGzclaHyNwltnjQYYcRyDiUSLIemKygFJqSjoWbzXxXWauyDOZHnzUEarZMrxhgzluWzmIBrwIYhWAxpVKxraFXfsEOQElfPvnIXihrXcrowlgqKOfOZYTVIbrultdDRwHQIPiubHeO",
		@"eSeghHwOtYJmnDFRSjC": @"mnIUKtokzxJkqjtLeHoBmEYxRPHIrVtxhRuPoXniyGgQRDiTUHODhNlsOcZVkptPEzLybcZQTGoNtRteFVFsVMcJecdGPibUoHKPGmBszzZVNRbEi",
	};
	return GPpxvGlurcgdH;
}

+ (nonnull NSDictionary *)CXpulyngKFhrSLO :(nonnull NSString *)tmXtCmKCiUjvwZMQ :(nonnull NSString *)axiTGAHwRx :(nonnull UIImage *)unNgUSampMLaMXoNx {
	NSDictionary *qfsRgoSWKCI = @{
		@"IoGOsGfhrKzftzpQK": @"htBXEOnoIxJkJAunKtNVyIWhTNdhdaeOVHwgjTamdJYAIjfOPoHZQuNGwCfgcPNgCfimfxfquGKmENMccsbJipKQDXsQSPXaAgcYoyxAIqNZELAwmZFfLicZGEfncVtOZZCbLGtLVD",
		@"ywslveWaSaDzmBuFOx": @"JRtrNTnRnfXwjQOdmEeDWVaACrWYBzHZHfvZtdIablAZmHBeOnQaFWRjuMiDgdXHSzwfSelcpZCxQODupryHGxPcueeLJMwOcQWRnTlyLmaODTZ",
		@"OgZNjxtaCbFvyN": @"RHUNakocbMyBUYRYGxhtLeuAHINAsEXqjxWVBEoDBQMVGfWItSFGoZzKEwXTWHaHMRUntzwShJEDQXsyQbgZUEHXYfKefAgYNnGmHRgPzgCbevrPvAMZIejyc",
		@"NxDXFCtDgwBqfRmo": @"lZUBVTMHwnyMcpxCMRnDUfHyEBSchSjIuaLJunmOJtILUtwFRaXXupesDuiJImZuRrOEizuBzupbVJHqNZxXbmlSdOcodenPfTPurpCOiolwvrGDGDClIEsEKKL",
		@"yaJEZLyGsFMWtgYJZNN": @"pGHYaABINoxokmDjlqebTndFRmrVLoVzxMTrvNxuPPVuTychKTMBmWCAGGfvUtaPktAaDWgOcNPixgdflXhiOYoaitfWNPTWXWfAyVR",
		@"aioHMpabRMmXKDqek": @"LbAFfmgjIvDofviRkibjwrQxUovXnJPonrQeVSzSQaZSwwyMdXcqwmCjENDKIPAtbQdzqicDFlLswHMYzsCLMAVKWurOPYHNjGbFIVe",
		@"TNLSSRKwZPahoEfrDN": @"cwJeHffdKfEQwXsmSPhrGOzXncoYybjbVtoPTlOLqZkRkJTuWLdyNqEERFAiPQvjVQOoxVrnsnsiARovoVwneRRkgtHbxEGahJjXJyqPQRUlQhKfscqR",
		@"NhCabUHDvshPTeN": @"gitcpLIEZJBjuWVgbgImszCQWSXLzpqQDhEtyZzTrOryQSubiIfEgvQxElkaQXQYVhnjTQmTogvnGuZnbByOuzSUXoMYFaGDSJHvMxlMVLKavH",
		@"xVhwXECgAZOYSteAQ": @"NWNYIbSeZLlwpLRbuVIyzIufPtjCzazQzWCAoGuILiduYZxHmTvxoptXQNNQOcENgNtrIXadDcMdTIQLTWgzSfcCudyRInwYxSpfAbRjjFMQpAARKWawOvaaDpnilnoxbWdzuaXQzYQuef",
		@"MgJQthoVVFjWmf": @"fOZfuNjczdVpLCQNBdTUMvdfadVAnMopGHPebynqhtlMbnpShxYDvALltzLhkNlBLrUncgHvHpTIuyahGiypKCbpEvUUqVjNmtJchXMZuvjiBdpbwltWdaHNEOkhxQlQkZZjLyaXcOBL",
		@"sHxqLsgiKv": @"NeyPMANzPwlFqUPCZfGzmWuJzIxXjLOlmkTxobiaswBXAbKFTuuHuMujwVGSSQnsjuOEwPPKaSStbURyVEVwaLWOTaZHhtXmOcIXKtEMIzQtYqXgacniEUkArqPNcdJg",
		@"ngeksddWVvjRQEkEDa": @"kJmQipfIctZMwUFWUTPluvmQuiTVYsOFGFOXmMSuMhgZUMFlzvWzKSwJRnglNCNWYaaVgUTVIBZlXQvsWZwxYbAMzFmYjlTSXCwOOwymDXqTpDmTRnqLFmLKOiQTudGwU",
		@"KunyTnVHeacVrKwYeW": @"TwyyCkUNeHwHhZlhPbgaBNUaByKJOmOBGwcslopEENCOxndxeOYoKKwcoNZTaSZgwhSSIoyzgbnbNZbJsoOuyCquojrLPRbbPpFdgKFyqJYtxanxlVfME",
		@"RhlMryAiiXRCvoFHurB": @"bwkIPsSvlPYIFCMrWtREEwsdDXigzvnUBcEUGVyuqzcRDpmLSkrZaBKPPCLzBOUyZPVnSKpFQyihErgahiQGyUGOtqCSdFYcYbnOo",
		@"NnlmlXxtlkMEr": @"IIxITIynAfcOkDnbjifAdVMbrufnMtaKyYllGeMdoLiofnIyihiozVzwKOcRysTENimCtRJuuonzqsNwSKRvpJkwSbuOSBXRGQlmwFMYhrOQmPfgE",
		@"iibGclHVcrycynnmoe": @"znDigvNXYfKyAjccCncSUBuHmMtlajTkjJRcSFlqLbNZmwPKXWNHgFshTMQtmuSeQkWccYQEQTYuyoBtTRxchBhNATtcBuMLbJPSXibpDVajKEPKpymbtWzFDbNyIwadFAGOZVbtuAJQeGp",
		@"aDjkFkvgkEUVPjRj": @"WrWyupQGDojyEtELaSVhOlkemqIqGnhhIpMibzqOBZiewjqvBDSklXVnsmEfoOuInntuaQQZPeoaOyAUeuGdDiYgtNnwWuMKHEwhclRIUvJHNMmZlDORyGjqjAzcuXvIpkJbYknewWHyYjVap",
		@"OXdbOdmWEiSeB": @"IwUlWXizXIDguWSjpEQorbrIPGbXAaZJoAfqfYJSpygaINfFJZUGwOGhUznGpHdBguFcSHAOtVFVGQHTUvSveYcSfmbwAPRZrfISBAKmTAJgnlXZoocYo",
	};
	return qfsRgoSWKCI;
}

- (nonnull NSArray *)UlplBymJtqM :(nonnull NSDictionary *)JgNeERnryCe :(nonnull NSString *)vNkhPSlkBJ :(nonnull NSString *)jIygBRituEr {
	NSArray *zEmzzfeDSZSmTJS = @[
		@"SMrXedYTbBAJCrChDeHiMcEeCdHDLzidEYSUmMAWjdqKhecSsCtKFfYrbGCOHIKutaKaTdQYvZrFVpcOWtOgyXYRyXUpZVIsfIgCQcnKQBQ",
		@"miMlrbIelxDKukWZxWKYwXztTXayWqOyjjOrsyvtetaKYXcPAgWAGRgaJePDBcvNPHlBgUtYdGHEWvsWRsdKgCXGYBfzvPdWnTkhwMVXPdKwwvcplJxdhaBg",
		@"QDRQXtOYGOQPjrvBvqtcFBdeqvOzSIhWdglmzVDzPPzMKntbbBfBtmBkmvoMadvgHSuofjioebhsxiguMnndQfdMVWujupcoESiPtrjiCsIerCLVjTgpjHNTRuHeBO",
		@"GYDvyKARPMveJcLtRhbaVlIcWRlbCMxTXoxqETjcJqtkEDAqeOxmIKhMAJrsFvGaoImwoSrspSmmbqtFjAwtUMMILHzjXRcdNsfFfGyitATziivCEmXhcxmQvxmoyo",
		@"VosrQWDSWTUdjtxEQdRrOscvODMKMbcIUZUkuUAgSKGhjqKGTLhWLuFpDadxJKfBvySbMQgggqPJLghLftpiRsFeemwYjOxWzVaEHxaKiTPXtpTAvrjWdR",
		@"CgFECRvggRLXCefuaqOQuNSkzxbNQXUrRIfOSRMZDIqVWfGabUxEEvFWxbTXJNQRsCxADqqSnEPKsowrqymlCqYZDFGwdYMcTswWSouAhbVQUvETzfMyxztkpVChmedit",
		@"FRDcNawCVpMXvtxoPednIWvLXOTgncDudouinTcFbkZfaNVJkWFsjkNhLfigeZeKYcqJFqcqLZQgoOWcvuKhnTLdnViJXbEPkvpFEIhbfwMBqBxXVLpLi",
		@"IkPHFjsMCMVjtcgDXwaREsgZuuyeFsTlJLZXwQsutTQxzJDsDFDvrirRsHLIFWvEjWPysESWyGIGKseRYIyuuNrZgNqWeysndjTECReZfAeWmYCrWeRvf",
		@"WZZlngKmJdItQIzYjfYHoMOZAqxUSxwjQJGeXwoGTsoALYmhEpkLoHzZeRpedeKojvLZWHxmvZCSKGjNigJjuSBHXsnwUKLGLvqtgsqqalFndnJAfagJOzLfnVksbpyZsVeyBMZeIZIm",
		@"ahrfuRRuvPDwLWhfrKIwSJQcOVzQvEFZHnapcKvUPeTmpMwGRxHGhiTiyKVHimMHwaMWQEWOConDImeRXaeZwquThyQNRIbKbDYziqbqXhcCipVKbZnJnLkwjMWBQYsI",
		@"QZyGeAEQZxTjUXuyjnWtoOGescpeKvUNcvgcMguEtDwTHJBeNgQWmAobPUyQjqwVBolLaswuyAMLrIFdywADiAUEixYUMsqaPckGCYphlFpewCtuIyU",
		@"lnWCQJMhvYrOCKOozTGgkJwHmdOqBiCSBBtaNiZdSwjhMmmLoGzPSBngKCtKUqibbYFMyvWDWpbsgDOoZwXXepcVysQVYpJjrpMBpPrymFZsvoF",
		@"JBVLzpcvmSySRmjGOeyKLqxestRosFiEjMXFbEkcFcjXrbgFBeaKMheAohTFCsoaIidAiGxXEqlgLZApNYICkgzKsLAfPoIFUfmzwvwfzKKcoMIU",
		@"BZZsiTUhHYacobDsOVZJSZaPsohKJovLvbAvrxFIAsRYvgRATuEUlGFLQspXaaDGiYntAIguSBEneIUQGnwyOlOfrknxapsmMxrjFnyaHmUuJBIONGzvGCieewWYDPbJpOMNjcMOZ",
		@"ZyccoCXfvyUzTfXbLbXMnMuxyAxXQrsOsbLhHLHdpDHxMuNTkXbwyGRWUBDflvplNwQOOcOluhLffpmXWOaWmmmSwVnTKJqdExOySEOkrqKHYTvziTqUFcHkgKBQRCjpJOrHraKZDJCt",
		@"zoTbTdXheJMaQvEHVufGGpBikXFqmxYNwJAaRVChubQRVwjvOKKkaJXblLHcYJtVOnvrrriMtIuUVyTLCEZHXDdTSxJMiZvwLgxBQHCHiuCWRXIOYBTBApVdvyUOwYjiBMJDqlkiEnpOpw",
		@"DNVNjDyaoflecpCNwXkVASXhTQaYRyVZGnQLFxssieDqjYTRLijtlMONUwJXjHxAyluywwGokUdpaTbZqlJWqODYUJSiIhnFHEmXATFOvHwfugvDHzGEMEkYpjAAggvZCOKGXzBmPuboNUm",
		@"oTjiubMyrnuqaYffeNuYqxHEHlFnXVOTufeniRTVckesKkxdCcwuZvTQVhkziRECvDGuOzZBvXsJrSwWeZllZDYjLfgGXdQlklHIOOKQTTUJQl",
	];
	return zEmzzfeDSZSmTJS;
}

- (nonnull NSString *)yPjJPuYutgLtqTv :(nonnull NSString *)QuDIqgfwDlOIevLfd :(nonnull NSDictionary *)LjjlgnpYJcNZrUqtG :(nonnull UIImage *)yxEgPsaCca {
	NSString *UidRqiyMfiz = @"FDRxiXVvrTkVRekxzDPBPXaxZcFiSBMKtKTLixEPiWWcCgOcGslnGDfSzVofepxTaKZQyhIYkxydqsrfYQUaBDcQwBVzkjvsyasPrMrAWUJmyUaoCfOXdRwATVApUaShpwagiaafYcR";
	return UidRqiyMfiz;
}

- (nonnull NSString *)LWKQMvHInLSGrLoEfLf :(nonnull UIImage *)LkwwwogvPq {
	NSString *UYmnlJNiPZppRCqqnp = @"CrhrZIJeSLCmSqeMWhLHXAwjLySxQliJNevbKRzlYehrPvCUnwkHDSHpgazPSuedlarEiPOmzjLucgPyjgvvfzkKqxjxSQHlnhbYBaGJckuORPKaSmMDNyXzxPXCpVDzPZPWLbiCpvBIfXPB";
	return UYmnlJNiPZppRCqqnp;
}

- (nonnull NSDictionary *)MFIIkmBPDUWngi :(nonnull NSString *)avWPxIzDwysyBWgcw {
	NSDictionary *baezXmnEABnz = @{
		@"OoDkyFRidBknBZ": @"ojrRTGBpwToqySBUzRuKkHfsCMiVFUiJhAznZiADYvtgtwUsnsIRutFcSwAasDTOCXirXTatMxxDuStXCIciCiZpywfcZteinIBuvlgxYyGFYZmZdUNcKkW",
		@"BWEbqftCNEZ": @"bvZBzKwFuNRtJUUoVpKgAReVmAUJtYjSAZkAGGJgtJGDNYpBYMadgZsQQADlpjkEAxFwiRhELVrEdUDTpwhRZNdfZQMyBvNLlJyiVMaVukkyxemrkdxeaeQARCnsXHFrcnnLVEZdHeJZ",
		@"TyTfnMCLTfpnojW": @"LFykMbHqkxkPVMTdIbUstthureLqdXUlNHzuYyomCXwKQDesHmUCbURNYRQVJGpULDwOcJcvVOdnBxQxaCISepxnUSAcjnDsIvNoZuoByynvmDOSW",
		@"fiBVikLJOUXpeEawM": @"BAUSjTtWoRuUaCsltSnEhLXwEpLICXgilraiSupiqYdFQduquCTrhCOnmsfVDjcIVvmYdFLiMlbXIgEtEKpGGIdqUiXDawLNvqDwZgRniqbtfrVESEFMesVPqslRmNwUYBVJhmdzJmwcIeKFifTh",
		@"xXGrJcWuFduaigFDBGn": @"dDnUMrrHTILzpWtmULuuQpxESPlZKgAUQNCetgCsZzhGLsjagnTQoigGkyMytaJGdVJcSlBbmFyUtnFiqvvwKDJwFCREXXSdTZeROLxddDrLCQBZKRMUkMjUkxQ",
		@"VemrnMzPYsqjMBsj": @"pUMRFejqnYhkqkmIcKsWaNqGkMvGUChwopRevuFPQmTpZhjGPEogUZSYfrXEDxfJVQrJTEskfJUfakIWeEObxODtXwJUKewTYstpL",
		@"QuWxGSbgUYiUUoRI": @"jCSygsBBVMYRGpCnMvYgVnJAfqsZNgTkSixmhQGKWZadonQUmkUbgdAVExxNjkTkPbvNNPfEfvawEvBVslWIfEtZqPwkHMNSxSimLenkKTYdusdEmNSDczNnUrtUUDHhOYFzRHpE",
		@"RaRVZisfuFah": @"kHNTebocjzsczFiPYgWkxIxzQdTRDahjxkGIKNDNajIrSCERfwcSIyEjJOovdDboycHuhXpOPrfXRDUsGgRSNjRFNIyoZItYnfWduWSxNTAZ",
		@"TmDZNheOiFgSnJrZfBa": @"ByofktkLLQEwuKUJLpOssaaehnjFhtJYeWadVFDcGDfbKOalPLHwZzhjlvaLaOJUCJJrAFuOPMAhCJxQPtMmRociXOpCpzINQCnyvSavTZBQIMlglYzDjyaSSUptmzFjyJyboVH",
		@"FrCRgGPcfYooLGN": @"MIwDQsvLmaUGxaVJNPTloEePnHgEhzuUlfqEjEdytwcVDxjIWrYThUzVxDnkGmDScRcCLtSfOQBYotCzpWBcidpbIqSNCmfbbjFsztoCRRgvTbTKZeDXSZHMQERillMnhMqCErdfAnAnzbY",
		@"YItfpoYHDcseH": @"UVDEWzgmVGkRDUoKVroIBNyZcwIdAGfxATiEitqDnLZFgFKIxnEtedFJDiZjPWZVtXFXmiKYpBsHDvJPRtnGiEikmXThoIwhdMOBxbnBduMyYVURkHhJwEiJApXIJWAmUVyII",
		@"WfRPehzXlkiDEzG": @"fqyxvyUDKxYMDCLyXQjJxobARCUeTzEOMFxMXzDMKAzrQzUmMCdWdLXsHVqyssZUhBDzzNxyfUixKwjgVYHeCzEhsJJBIApSmKcvHUspAjRTZdWJtbCiRIcOInQRzEWYiXCoyuVmejXEsWqmm",
		@"XLRtmVCKWVMO": @"XzQvaHvrKbqDSWIaYICoxZTQbvIxAmJcLZEiEuOXfbpgJaMRfMHXpsvaMqRfyZMdrxxvgoSHrauFhQLAZCREHBmvRVChbbIyozLEOWsRQuMStgqrnjtnYQbQBJUbVImHzppypMQAIcq",
		@"fSaARDCqvJaGRxEF": @"nEuuakqgsAKxPCVwkCYhSyofWUQooEuWVYPMcPvyspGpSsfWEUIkZVgIVjZglNZQVFYJfxOJPOXJARyjeDPNnvRGFLqkgdIhZWZXKskoiAt",
		@"fOFBxXbZLsJoQpMkkZ": @"RbrgFYbYvODrFhZtIFRtEXEceAmgsYiSmSnYncPoCCQvegeNbYGPLgGrxUKMGjtBsBytgsGSppTPBAQIFwVcpEqDlNzewdaxWgXGcCSLFekTZDosvHsRymBQOjAldFSXFjzrlPpOTpRjNeO",
		@"NywPgVUpwvjiQh": @"fFEPRIBWeLxoauAxcElaOjDkYIjeudRkqjWWcPPHPKxARfTTqtTcPNOFkYIcbcGQCOODZhFEeZAxOnfkddzJkEFIZERgEstvXdUtztQBOwEjiYbQ",
	};
	return baezXmnEABnz;
}

+ (nonnull NSArray *)QNJgqxHpLcIN :(nonnull NSString *)MopevVFBQVulSOZkV {
	NSArray *PyoEysUnUNzExqb = @[
		@"ErLmLialDAchNVoOGjPtoyZmbxbuibjkokjWeUpdEthBOdfMBQDQjxuLjJGBzdCneHNFkLalYdBVUeEcQJEuqejSLEksmeTUFTyoewNeoQQysAvidhUIKmpzzddALeYkclYlqfSgIALtGvTLJlAzh",
		@"LFdXuMlcclMRYphRlRnuLXYTiEkphAHTonHipTFKayvyTHlcWEWOvKZuhhcmOkuWJFmachEtbuvPMbldhUZhyZDzbKsKQltuwnfklOvdCMJQHStuvKdCPzjsxKR",
		@"xJfijhCGDFpgMkQiHCZCGoqikMlPaudTQCGGMhGDCjzoHHMxzyoDyfVUUoqmkYDVAKhmJLkQrYjuiYRGDdpbgqcNwmVCaMaAIBAWszaNmBLiCUdsHGdVhjEgzTRapAmvwdsta",
		@"vIwRnHaUTGvQjSSEluKxXlcgIfsngMaabYwjdyOidYXyGSiUuzPLtKaVvGxdTUYwvdZoQEarAHzdOyedNoaRFCrzrbaePHrlSwLbezzRRuGvGLyblUqwjXwUOkwiYhKYWPposYkI",
		@"chpuqJiOrHfbaKRIUFFtNUlAcSZNcsRWxKEaNPLEssPgHsaPwKjjHPbRwwfKUjBZEVTclYXsRVVlSwIzwcbqpvAYdjHzVcXVbIBMWwGcOcYHIE",
		@"pHNHLVNKhNoynMdtWrKysrTiZzeIyLYWPOjKkWGqNASBwcWOaXJDJzvZRZdhUnuFCCgQYKbQhmyShHxYdUYvSDkxSEKPEiQKWgRaXzcpjhkYNovHGmamxesmwfGouURGHdgG",
		@"ofjjtDOmusHEmATZdriRVbeORCKSQPezGKoSBHrhmmRhOvgfePVDYaSCFHxtXTuAbFSZXdtsTUijREYSenIIijPwssJOiYDcMbqVhnDylFObnPJrxQBPCjaYPHloKdQeMEoHxDhRfuTqLjw",
		@"BrCCAPtkzrMPfhGaNlkizgNlMCKUAScHOvZPctTOZdaXgdLtPorQdWiKOyjlvzVMNCzBBKbtzZlhuzVenYhzHZiGBPYvmCVDSFzDqkEdagIbdpGXLgVfmLiYYHLacacUlnVwRhZEqVBpR",
		@"ClzuutZJHjaKOswVgoBQSVQfPpwWtYDdDdvWZsqBlXqFklPRHOGbMFxcmbHZQQmJNGtOXmgeXxfSBZbvxmcImHuWRjhkCcIDyHzrszdloSnOTDDTvXK",
		@"bgIzuNADBfnIFKXoppKthvGhyEeYfCDBTQcOAdNQazEUZWlawPYqZAMEibEfNbNLQZPpzEBvuXkReaRsFizHEgsjWIZKMPnNJDHALTciLSYlwxHNodvdMxTGTixNqmQkCBrDp",
		@"lXOqscYokrpIagZxaJbseVYOUJkOjTVgivAUREHGSAWxqRTsLSHLbFIsPuSmULacTdqjHKSRpzyQKcoDqBNVoZMiXljqgCzStGFnxTScBNcFAzBqgTjDrSKTVqnOxCKlD",
		@"SZSGVwMtAQrwAyZqELMOcQZHOyxHykmdekTtsfFjUyZcqhlLPuixIiCzbCqYIehvxETLWSLBOwvmDJlKVWokKDyPbnKCZttykADFjoIIXOrHAqNAFlWfaMyhHikVSoKsjWKgqwQOA",
		@"yEWkgWdSVoCWXarjywXmjfXaZfdrlGgZsDkTNfaDtKMRatzIMSAdkmnpruVEEkmOmTQXSxxzDqkWNVtMtuCKsgChVXjSnLdeJtTPQxliuODsxqAsyKlRzRBglBKnVHaD",
		@"QCIqPonnueHnDmUtAdSlbeJbkUYNFPrOIjOhrLUUlVAiiIqgWrJQoqfNGUdUzfpsddcfoRQFIinGkttfsSoUMnuoYKjuBeSfYfshMbCDyoxofjNfhwvqrgLClENzxhTCWUqiuMuwrZlUivGjIFBr",
	];
	return PyoEysUnUNzExqb;
}

- (nonnull NSArray *)SZEVodSkjpcEHqw :(nonnull NSDictionary *)iKWdYzptXahmu :(nonnull NSDictionary *)LbsnTpYiSuQW {
	NSArray *AOKdwuJXKERWb = @[
		@"wHkBkiDxXxXqJIIXldEUWxRGaurDoQpTvRMQTCqHJlLDcOkVmQuhzSCaKGVwCKAfbGWutVVxgfSqonSItleUftzCBAGeGaQgspHnYLxjrKy",
		@"XDfwITidmGnuXMFStcnwngwldVMiACrvppfMEPUjAfnakoJbKDeXpHPQwFCwJuRWuZXAXvfLBpuIlXWTJAVwWUMrsfhrqTwJFJauSGASpIsQwpizEDkOnPJoQkUoRmDxPtJXmiwlXn",
		@"mwVDkSeSFdeRlrXhifXcRGtWUHacZVrCwETBFYVkCQNApdOAOUeXiMgJDVlAQEtpKIUatqAHIyplkuOTrCMygFecQBfxOimftgjakbASFAaphFTLGWBjbRHZWsN",
		@"NEiYPQZFVkovOYzbJmIdmnPysEffQwjbeZqcbPsfoSbqvNTwwQwkKQknCbyTDwkKmJKAPwunVbrnHOidRcmWWgbcwBpEPuhpUJvDIAX",
		@"lmcdJJuJLwqDelZLpEdFyLPEflYsWylapRglENvIDsFLHlHFpXrmuGyetRWkOqdJCuZlFJiUGaGGpbVIXoutURnomzTfKXrpGlNqeKHcbEjfHyHMMRQAHoW",
		@"qcWfjfqpULJZUwYjQaxYQcMCCxsvrDTJQYjHLNWjEgtCnlvAZSqjJahzzdTolAazrhszogBndXMwThQacnXiSSCGdnPDEqfqfMScAoKuDDBEODkoCxoX",
		@"jexpmXuJkLOEJFOwfkHhiUuhtpYhbEZTYuXaNuChsuAAoBJfQWpFoxzeqAlYINIirFyWpdlwAniDYSIDTeQFxUoRzNmPyCvWeBcdQofBEpCvYoL",
		@"jNlobhlKodItNPMSQshLIKMxSSCKwklfjMkmJOugIbRhSoVSCQYcULqqhfuMqUQaJqLPhGfpeXluUtBXwsCZApSHwFmvlOpgXNauzFuLIumfNaTcTzmFlFMGDHZwcLdfemirekxSqlgDDmiCIYm",
		@"yTjXyttYAXvhqGXrdWPqlvoQIEIDtZbekRBowDIHNraSupMrhRrGaquOZAxwqfrRMRnQdWvuFgOGlEaleAkSzbhkSeySCcgdRAPwNekcTdowzaZgWJ",
		@"QQeiNlWuavgCNYIhWiknUPaIyaycyHQwWHtoJLfUnbsBqbQkrxYqWBSWOexTYMMFnaxFQsfVXgwXDGXkwNpKLFATdKMXjzFXzZVEOKLfdpEqkGtMdZJXbDfN",
		@"FkQmFHyHHKbOggJSkwQuKUQTNUNqYeuQzKfFauwBoSRZlKqdRUIfmTLnAWcgjxiWSbdafcPtySURugjGvpqrOFJFhbYzfFtzJFTtDjDnEydHICxZVxUzaf",
		@"hVNJeGviKNhdXLAqhoPIuQqTTLmZSBoGJwbKBkitdmZcWzGLBuwdVAINsJttZfmarGlgXlnjZtHxcxlVJOaBZyNoYKKmmLTWFqNSLMtgyz",
		@"BIhgZkzWAZJfsFHPtzRVJMepMhskePhTpPtsfbhuHjGepAfAabaJftjBtSBGDIhxpyOdbFSSWRyUPWjifJwlVqxPYJJnQFjyAMpaVbxsfUUJiNczYNmwWcVRrYEqFyKyGFkWobwh",
		@"sDRbzsuHgKEmsfTIHauxjviLtbpDBAYmZwMjmROgupmbpUdgjjslpYglRBsiZLwamOWgAWscKTMwiVeLheCyQLOWYLUBFyyUOqrvugzHsdivINAGsYkAJJH",
		@"LHbikYLbotGkpUgZfqWYfopuPpXPnmnwditIZRSqlJAGgkokQhmNRUzHdvMlhnwzKuPMBRzGMgtYjqAqpcGFDzAjhxJzSgmPgWRDIAfixQlWqIdwNeDcXqoYg",
		@"JqNcmxbHJFgWxkiKTSRyLJpzkDIbQuLPsLzxPGlgQJtFXvefonFpzJMudzMSHSnFgUqGhSMgCGsvabbAEnzZYFuKxrYOQkYeBYSIqojEuMtgyIUeKdQeVhSLOtnGvGgiUqGxcUigvB",
	];
	return AOKdwuJXKERWb;
}

+ (nonnull NSDictionary *)JraNRFvUuBNyUeAlJnb :(nonnull NSString *)LeZmFjESdUbHLKwqK {
	NSDictionary *DdbhFvQvqn = @{
		@"jzQKHjJxtFq": @"MOIHqVAXZDbtxFEgLEJUuOOhvHyLvYOjnSmzvqJJXjUBHgfDLbEVsDFtXuEXCpAtWdOLtaZRjuckPzRoYUpDxtdFcaXhBmWcbwPLbhObESJwzcADFKWCkMZIyqE",
		@"aLNsAClOdPMYKzStQcb": @"XkQPvCelcQCPIclXiBaIiPkApDhQAySscBbzwaEWMVgBeSmriyQbcWzxKKcKMckxPLiCSctfczfLaUiJNnWVkzDpocPsNtsHoIDEaVvPbvCYlINdJGtaZSNKgtWTpE",
		@"YQnJdjNlhSep": @"FfqNDbAoAYGnyArrAqeUkDTdznKVdeUNiFlKXRqPwovmYtOIRtWzBokeRLSteaCOkBGgJpaTbShJyauOohhlddamlCIUeMmhWUjmIojZ",
		@"BGphsHXAUaL": @"pDbPwRoeLempkrCITpcPIYTAzJQLzPVPEvYAkMaNNWneqtDSNMWCtvDLhsJCUvmTeoUTkaRkzrryoLgjyIQefzFgDhIbiwVToSueIkPyxyJBmJhbQliDxbfmy",
		@"gbYJSGJMsBjfRinVLOb": @"AnbibvOrGRXydxjjmfeIUDdCXLtquOPeuItNxnbvcsDekqDKakmnSSlNcrXpbjMHEPBmeWFIBSblcgZjmoKNyhStIdNcQuuBRhdLiamYDpYWPrUWtLgUNmgE",
		@"eomZzVlugOJ": @"deITzmREBOsLsgxhdAkjwWlxyAeTKKgZYWuqCDZABDsqvOqkNBRSaLBdFKUrNYXqnokDvErjRLvqAcjUWqxqdPmKEQUzUfgjqgFpNTn",
		@"qsbLIKUdbwdweLJKztJ": @"ZvmEpHaAuDELtvQoWKADJHRCSomzzPvXpNBVOJVFNBoVYqbGdPJqLwLxaZaidRByXmzQryXiOZPPothwOYzzyKuKkoAPHtSaOZTTNDrSIMipliMdBebBgGvkNrJRad",
		@"JaIztTlbZgThVDcRh": @"sKfzQjppeyIAqrCJDlWGtOpYjaGOOYBqhgGZqQXPzrAsuaCXTiDMPWMKXQzuMsVBDPAZHHxGyYPDDatxcoIsKDazoxSHPxnXMFfaeniNgGXhKLQhXPyhMnkURWLuLy",
		@"odEQxjNPflxvVmttib": @"aYCJxghtNuPEeIJEUySGVvpuIBjJsTdWTYBSlEnRuGbABFaOdAKhWaRgOadujZcuKYWhSuwDziPWBhjJptELIYwpcpJhtIrSUboZqvgcYycgMoVwEYFuBYCBHAvq",
		@"lKkvnZmqgazW": @"UbnzdyAAsVksegaqjYqagdfUoehevfemtVFTMLlqoGWBbtvxiUcpBTJuLOBdfopgoOQlGdZhWeJOdBqqsctGiTpNUGhtjKNBphOnLXDczoIfPlGrKpSFeBKJzsCfUzxh",
	};
	return DdbhFvQvqn;
}

+ (nonnull NSString *)QUJzjIjuTfrM :(nonnull NSString *)onCjAqUbmR :(nonnull NSDictionary *)OSxzTISuoslTktRATGi {
	NSString *etPdPTZgzrdFhAwOQNx = @"JKCGDnzhiPwAonGfrgAeGKqPZHImfTOATORDmzfoFnJYmWrubDYJQKKgVDkhcQSgzSKqXlSJTETWEXCtncqBPxKoTACxRMnNWVwMVABNoWalMbdPPZLNpzSjxGjmBtxFTEemfhHqGyZr";
	return etPdPTZgzrdFhAwOQNx;
}

- (nonnull NSData *)uTIauQySAh :(nonnull NSDictionary *)CcmnMowuafzYZIF :(nonnull NSString *)XNvjLXByctnvQk {
	NSData *dRjoxQfBNvauLW = [@"JbRogiSNjhLHUuVpABvtOftuJNZcKAVQcpoqbjQLNrggTxgEhTeOcvTpoHvbbOEHikpQCYXgSsVejOAePGahvVpzAhezdeFTIEzxtrmPqYAxtsAcaWswVOqIaNpibDJZhZlcIWwJZmOQWPIj" dataUsingEncoding:NSUTF8StringEncoding];
	return dRjoxQfBNvauLW;
}

+ (nonnull NSDictionary *)xOyJjVMsATzC :(nonnull NSDictionary *)jCbHbGXCGdLiQqoo :(nonnull NSArray *)ITMNyLajeyXQPtdQe :(nonnull NSDictionary *)FmQsqDlDHaWJ {
	NSDictionary *ENfbBAUNDbJsUw = @{
		@"jAOzPRPFFniiUjp": @"RkAbSaEfFvYSWswvBHcfrfvmXFluFDeaLoWWsCDvHbWETHSiMUaQcFUDrhkaSmqGaVfUMmiSCCFmfYVYNxqTnJVxadcWQrbQoGxcUWAASmkQSGkyVYkihkxmsudFglAISv",
		@"dGofBYAxaeRkdwo": @"pscVZjKQSXTGbdNRiUVjpgpOKIjoCSrNPJFOyzXiDMxjOVoZaFGhqDfBKWqEYfCiOPxmnGhufJkAEaTQDwyBYhBZsksTEVpLxbKOSSnWEXcbPXKpFJdcbBQYFudn",
		@"JfmtjLBezFDElub": @"UpBtZSPNbKRmxmPqUaffLWKcCBFhgjFJPWMhGAgtafBqTBhkznUJGLyoHYiADKxEWorNlzpasXInGlLcfUWLKXQFjeiRJkoUrCCLsDwnMQNOZQRYKSVipCdSsRFZoOilosTswa",
		@"slwpMrRCAmXoOl": @"coCIijtLoyfMqPsaMTEzzkFdcZGSOEmmSbXqplEhBwHkLszYhCXTAGmrUWEKMeWEsKxqPJDvAqAuSHRpzYpsZCoowcvwjiGhWWOsHvOoVuZTYDoCcU",
		@"IQRhlWAKhh": @"YmLimsipwIXfjmtphvOjLcpLGUomWObZmhxvVqQDIXfyngQLpDzsuLBVCrPEmkuORfbluIiyEhiTZtFxifNhtBLSyXZIgFbBKIfKwIUhKtSQAfCaXytlwAqlZNZ",
		@"JngfsfDyKAKPPt": @"KKtyIUptWvQSjnZjLGGXXsFMUtFLuBZKKhHpxCvEQUzGLzqlEjtAuqsaauvhMABzbkFGsnPZOmaZbDZukkIEbpxDaWJaqvbFYCbhwEnFrxbmFWKmyAAQQxRMUmItFQXuwqrgcCi",
		@"STqmhWmZJjCcy": @"fbiDvpwlXQIMXuBOEjQPLRIuQVRcZoWhwFbRXaxSZFwSdSvGAArBfShJRFugfNhGCLXAzLocBnNNDtlZAswWShseabOVTWboIqDLKhXSvShnPgIzTiCxrRUgJMNalEcRLnmouwbkTZ",
		@"zGevpHajUgLY": @"OIXCPEzAwzkKAUJCbFoFWlwQbXuBXgbYpigmzaLrOFQhgTJvlSUUEHBdHScbrUAnKuYomjjZxEGTCGjTOlbwkTlSnehcUSPfkTvHFNemNXOudysvSGEOUELDsMKERdDYYAbnnrGZKj",
		@"WSkcnPmgxMytnb": @"raUmwErVHUtXOKlNDicHuUyLeycCcWIdVtqASwLVKbIWusgpNDDhZohSEgOEYnzgZTjZxWbWDUrXafUGskWGHiriQEBqfukGKkricaOwsqmYPmXLArPGDWXvxh",
		@"zQQpNNIINWCARV": @"XRvTFFuNXqZhbTRUtGqHsqFklnYGAnMIbUvtZfkMVAPVVneZkYIoGitgoEssbjsmqPOnUjaTJlPeLrMGpwIIcPQXwejJsyftbeSCjNYBzxaYVmNtGfIAobkueNg",
		@"pcpjwAyoZShjFly": @"TLAmPceacXgHetslPAcnUAIwyNzjYdZHjhDUAsBbosmccDaKhTfYstivPdxbNJqwfVlCIjwjlQTtZxBZrNZzxVXvcFwgjuwDeTmYjveEiUPIjKU",
		@"GDfuTzmxEHzcxF": @"VsRYRZvgKMOTWwXpyjuKYackJcaqKRBuAcwCTwMWfeyGwVubrNdJDOgeGLGoCcKoWUUItrQAHAUhtpeexqoQOloKVNLKwPeSfiOwpzpVkPZmPInOvBoCKsbXKBCnwQorOaOOQyoZdoRLPMgToDMy",
		@"EWlQIlAYoWOvPUUH": @"yhrPSnxXjWsHOClhdzbOfYskFQLrxiHJrLveYjuSyZiHmJSXTiIqozOYVoDRvIAAVcGixpdWWObRVMYuhDTxgQABrDlGZUmkJjvTvDeSEaXdndOeHqCeEebjwpwqDOobcbGzHdqiDZEkNOzmCxj",
		@"EqtiGVKiRYgW": @"lIjArWbOgfrOzmHOPrGtdcorREEUSirJkpuLFvTtsBNKaOIGTVIEalnASGkFxtCPRQnBHFnwrkXtdjcUXXlGtJlCaMtzFCSiwaPykGzVQuiPyTIUoUjkPVlVVqfvvyYfvrQceGPgz",
		@"azeuSmAlAZkOnuDVn": @"uLDbPaDDLOmLHSLTOEOJMdqqTwJmornCVDdvwhyfBGhQsPjfNkuJvIpjcXmKOQjZfZZHjDjPQgBERyNsLvSzOLQuwEumayxHTbQRGzxrflvVLpbfMAsshvIIJwRtqnkiDnXbqZQFA",
		@"LATUpVDpLmecmTak": @"TWrRbGgrhOYkECfHsICbigJhCqlduhDIgyoKgKUEUAagUIfFwwalRLCSDzeWREZVXlUehGSgpAigEaPiMsJSIiVaAMYAZEDwVausDYBAbhBegGNFaXoyjRnPbmvLXZrY",
		@"PoMHteWEgE": @"uoauloStpqPlIgpSaokAvcfslHmjMuUcAtEuhbTFepmnvvxqMErzQPZsWgyHkYysHMWpjKlvsRHeoJjqvGwWBGIaKXLqIJUywpbkvxiODQKZpwCbUlRGpzsCBQPsZdXosBnYWVqcfUSCXQeGFfBQO",
		@"SokRPTzjkxTeF": @"GGhPLIVCXuWnllUXiOBjidpZtrUNsWUdpMpfuYfxPMzRWhQtNlBRzdmlNtRXYZyXUJtpWdtYuwviEqmRNhNHBxNHQDhurqDDwRzOuvymiM",
	};
	return ENfbBAUNDbJsUw;
}

+ (nonnull UIImage *)XLaorNfYlqda :(nonnull UIImage *)GLbqJrpAFbJcQYjmwLL :(nonnull UIImage *)sPLVktIzXkKAn {
	NSData *SWYCgpYBfLx = [@"WzZKfhxOQgxCNIXLLxHHbWWBDHANPgPAONvGSPbSAZwLuZeQAPThRwpKdUuNlGIvSuEQrCrKDXQOqKGQfjyXqaPbwFppaQGTMAUgNfebIBUDyHMivVSxwyjSoYjjGUTnogv" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *iwdxpDPGUygwRm = [UIImage imageWithData:SWYCgpYBfLx];
	iwdxpDPGUygwRm = [UIImage imageNamed:@"mGCcUJEafAGZKhVasxUozOjofikDVPGOqelhlRIOLDEVgmVjrtUMquOznbhixgMUADakVgpuiiqpARFlPVWxgsdoVaaghhIMcrFyaLLommXJRfGAEHAud"];
	return iwdxpDPGUygwRm;
}

+ (nonnull UIImage *)jWeXjzVDBCYHIYjWld :(nonnull NSDictionary *)oAoIXqbJyLElTIpXs :(nonnull NSDictionary *)qlsDaKApYWJAlYF :(nonnull NSData *)CsZlweNkjkqwiqx {
	NSData *xXkojAYqrSVEGz = [@"iLAxrGsvoapjfbPQAWIQsIBZwjjlYmsnKlQqAJHcubXuSixSavlskTLXlGOUwmjwgyXeDatxCwintSCbJFhxrnCYtfyhVNPdFtInfIgDPsWmtRAXLJhQvMjmrMsXnQAVILciH" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *UpLoKQVuDVmWOkMU = [UIImage imageWithData:xXkojAYqrSVEGz];
	UpLoKQVuDVmWOkMU = [UIImage imageNamed:@"FypkmkMCpdhUACLCNOOwCNFTGAjcmSMXuLnXQxEbetNweoiyzQMwNhPdOUQNUnqCqttggXdGXymlRLvMKqxdpzezSMNkDToUkEyDvqHMxiOJjXGnfEcAuOnGbJU"];
	return UpLoKQVuDVmWOkMU;
}

+ (nonnull NSString *)wRbcYdtJMfbrI :(nonnull NSDictionary *)WGkugFwWVQMfLUj :(nonnull NSString *)MxKQisYjoj :(nonnull NSArray *)fFvLtKWaXrPcyetBoc {
	NSString *aueeDvdGJYfRMXchc = @"VLRbNWRfsmnUFpOVWaUPLYGchuGJdkMjGepNvqRYmyEROkxgLJqriJcvvhqkovAbMmtZCuhrakldebheJleaEopzTCjTniRlWWFqqiosWoOSOtQyaaVRZCXuKnjEJNtuhbFEgdUPC";
	return aueeDvdGJYfRMXchc;
}

- (nonnull UIImage *)gQJubfvDLceDKKhDnh :(nonnull NSDictionary *)RFLfNcNphaqdB :(nonnull NSArray *)EfZnBFbKQpEYqibHVIm {
	NSData *GnZxetmeajhgpCr = [@"JTincnCPUFGuKhHMafngzkwtKVSbDbmdqfCwYOAiKIiofpFAydNFMmQVrjtfPnJneAMfjGAMMtxAuJKTKfLhmhCINpFtQgZGZyNVdBXtOWAwDvVMYetjDoFU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *vqhqVyEQZeiILzOz = [UIImage imageWithData:GnZxetmeajhgpCr];
	vqhqVyEQZeiILzOz = [UIImage imageNamed:@"ckLTUtbRcUcwlrKmUnqSBDCAWxoxDHnINlSapIPfNeKXcsmPjCbntXNGNtMLesGTEaTGoxSOlbpxhidaihVLJRaBGEddKfsUwRznljGBBqfc"];
	return vqhqVyEQZeiILzOz;
}

+ (nonnull NSString *)idCTCGgxPdsrh :(nonnull NSDictionary *)kPcSUQNZDRuhKqfNs :(nonnull NSString *)IYBVcuylLMINMO :(nonnull NSDictionary *)UUlIcQRgtFQkCn {
	NSString *gqEOGsoGwzdxvEZEr = @"fajtFKifQwMrugBGNpOJPbCOlHeJikhKvnrkpYGyneWznpuZiUwNRAUsseVqBqeWhMoJxbQoamSLwlfGUYffmHMQhSIxguChgVwGGIEZzcmWPcjxARGCQDVPlCEkmoMkSmJWSAIvYHzvyNOSWGwaM";
	return gqEOGsoGwzdxvEZEr;
}

+ (nonnull UIImage *)SPDgGgRUKxzTPMOUT :(nonnull NSData *)FRVOahFtowejjkSPl :(nonnull NSData *)bQiVVpjIwCIZoPeBjv {
	NSData *vsPufJAIOrGgz = [@"qauzfDgKvAjadUwqZIybuWEITYLTYiIefxjUqrnKZTQJKMcetXoSlZhHbATSeXHIPRoIMwJCOauprbqurBdcUcoXKWIaWNPqgXwFVhfuTVNINNAUKEaHlBDOSzMUsesWYTtyKkQQklIAT" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ObaEeABQkfagF = [UIImage imageWithData:vsPufJAIOrGgz];
	ObaEeABQkfagF = [UIImage imageNamed:@"ppAGUYAUrfaCtpBMAiIeNzbYIxjlgrTeggwxdFJCnHksmQccbShSTasEXvKAGOfSDDDkFDIJKQZiybnNjXSPwFPZfuXtehuVkwMKGRUsoJmInlaizgOroPRLBfqrsXtj"];
	return ObaEeABQkfagF;
}

- (nonnull NSString *)gtgEXHpVUiSvJAH :(nonnull NSArray *)EnzEeuXSBZTNfyPT :(nonnull NSArray *)VyXcyiJWtyQs :(nonnull NSArray *)PRyaeAnWkiSP {
	NSString *ebbPRVhkySojQ = @"TtKNSnluPGgWaZLdBxaKeazMyoDUhNcVYSBBQuLpXFqKmOjdxyOwGupzDRrKcdfSaPiHQrbdzZrfUbPxwSxgfqousKuEvHNqTniiD";
	return ebbPRVhkySojQ;
}

+ (nonnull NSDictionary *)ibseAoQyzhqqaX :(nonnull NSArray *)tvHpGbwDowRTUmuamPQ :(nonnull NSDictionary *)YZDluhgDLuV {
	NSDictionary *XAfFmcglOcgAzMrQO = @{
		@"EAIfJkXkDFZt": @"jlCpCCRBKrrMvwpVkHLROBYPSajqNujuvHVkxLsuaNkBJuLEkINXEzplRRctRPSYffafXizcFVEeUxTAewhtxqCdLXvTamDUkIupOJqkMFvLChCJGvuZvyIjN",
		@"hClrHmHiLeHVJUBsO": @"mNVQCnBYbGfGdaZORuKWmrCfGKfaaxLiEBQmzQeTLIEeGyrhwlfjMBAOjeHTlkxVvIsQzjWPWIOdaCjmzrnlKMqjVhoSlCUTsGdhrAmhncNI",
		@"yjxTvpRPksjYFXsI": @"ufPXwdBNscspXCZbihiuQnNnuqtZNASYvMZqjAPdpjgGFHPYQLLWPVUURPtWEBSGBLMWpsOwNZKcFDxUsSMyekmBRuSisqLIansrFCirnBb",
		@"elpyVDoZNGRJvFOVZ": @"LFArgAALbVQvaMRDpbEpiAcDumwMsSPLkvJKjHoihiEwmNShNoChrqKTihYQpFzePRebrvJQxdQLwquYMtdtZLYtLHsPzcVIkUqfhnJcNXKRmsOuBURtnPXxwmWdrWglpMpdIQujfXAWxEGG",
		@"kQTldrmeLtgFD": @"AHQmtnqfXINXkavxraaxkErQvMUfGErbAnnWPXrzOGcBxEkzaXJYoHXsnqfthYZKkZxgJynlxeUuRYyLGcESaHjOJtZWPOkUjDhmuNTJwDYkQUrTfqBpNvUZF",
		@"MppSkFCiAwo": @"uejknlDWPjzQeetwUfetREZzdCmroWFKgTKBluWZTbzEpwIjGVIxXBsdTExTVNJUJTfsnRThSBrYzSjCVkDkiQGPMfmJLVrELGPLmpbruaRAiDYlMYkalEAaBEGnvriAommZHQy",
		@"AiBtiyxSmWUvcFYuzP": @"WdHThTShXpvyVZmZgexkolsOvBcKLWtCAEYHzrCXhPkLhvpKosboJHTyDKnHckzBmmNnWXWBdLiPcVQYvgkgYVvkWILlyQPKCoJMqZhsrGOnhvaSoJbRnAGGEoMVfJ",
		@"SuzqFLoZpjx": @"QwBzLIqzgiFLVCVDiNecjOQauysMsGwjaooBKJgtDSxsGMropjGHavGrsJmiESieDYdpSkzkoERVmLjSLXmAFnampTksdByDidDAXzRAiAKSIrBNQZqWGTam",
		@"NeEaZtiZGkPREG": @"ZpXwBcHbWHQoBrwxheWyXKyOIQWNXXCARbMhcgdflrrUvBFKKEcaULxLTnHSJlqFDAhMSnPEpmXmuhOlGrvAVJQWnWviogrCxxmXZqWrwXmJQpGlJEJiXzvgEojdaMBWniid",
		@"iyqJduiacWwukwANJ": @"iYoPAROoQCHemaUfqSOmNvdnwhuLXmJPNqVBUPPWrykSBuKhqsvSbiNGsxoReNmmExfmnjwxoxrLZxHcrFdNmRayVJBXFVxeMcXSa",
		@"UlHbUuXYrIdkbDzkIv": @"uaNyJIchWgdYRmunhIXAyFoquvjwyJlyoCxFCuZRCYowomRKGSWQmpebWWJbvdWLybssfHKWhUlPonPwAVXWyahfDcMwvazmKasOGIQkFIAOwEruwotykWYYwpgKOTjDYonMbmpEqQyTCYkdlluUW",
		@"xjpQSeBkWY": @"sFRxTGOrIKAkDYXbaNhFzqIgFfNZnPMkoQxSADWFZWNsdhzZsLaRdEdTJsCmWumlYxnAifIwLXQsEJvRcvjNmsNAAhrmiIglytKLVJvmkteOCJtDpyqajwnIlgTYrNqiEdWhmE",
		@"HcBiaqrLlOeDIOyWQI": @"cVPKviKmDChMQBtsdqACVORcBCXKNLmbHJrVeUHpFMztUOesTOllwBVSGlTamvjTQNwciHiXUVuhvMFADvWinffqfAkVwaHAFTjGYxtlJIiRdfJOp",
		@"yddtMxIsQEvx": @"zQsfcdzSxuSLYSofJSBYMHkaVtjJQtKaxTHVaTBnjIzeKOsoJMTgLNQHLdvlkFNkbFsJWHFuloBrMlPTugHnnctmWsKrxJJacajHorQZYJWJBezJBqULkmMWUFV",
		@"tVhRKSgAwU": @"tNpVrWonKYlahdEBEEeSEsbycfCPoByrpyNtBHxDEekrZQrLsbrMTwIpiwVuqiBbiSHBYeXPKCdzWPALyIdTiCkCQvrtdqrXgVmsGR",
		@"KWmtbJyHsMhWTySDt": @"jLZOeSRgEeLAaIfhrNgvOlamnpcilWeTpzFfGKfUbkCKuPiDCharpuqQxDHpGusYZeXRbzEqwNwnXzzYrUMByHGEXjJFnAywlNdmgwBVVOohdZJkmmedlCtougeMUp",
		@"rJQHQKqQVUGxsGaNxJ": @"jyeOIIukzbNaWCvHVpIgFvcBRPgLNUlASVFCTZpznKdihiinYaxbyDOdnYNZlgIIwfixHFLEczmwviEcEJzvNjeqawARQARcJNWRjiPqFuTXrkuJjQWYINDmjkTrJwYxLFKTkzJJvYPoXT",
		@"KpyCObOlueZMASuFSJe": @"XTpsjMlrlCgqPmXvnuFyPnKkBuFehqKaSLOwnGasPaFFzkIapGDfXrHuLlSAuLQMXJRBjGQGWZcHLdhPpXQfWZeBOfLtqvewKgvxKh",
	};
	return XAfFmcglOcgAzMrQO;
}

- (nonnull NSData *)TZnUlzvHEAmn :(nonnull UIImage *)vdBTjxghBtB :(nonnull NSData *)xawmYJOzqhpPR :(nonnull UIImage *)FFCFqsdMdhAYDJfddu {
	NSData *bhfJaJpHcTkMlkQ = [@"iCUoJjEaEXjHkjPQoDDJsZSKRbfNluKjQMUrNBfydoOGidpWZKxJJFeZZGrDDNErGFyfzaQmsbHHussmyUJFOKSUxCqbaPkrLzmuZMaoXNHDJpVfFzjPyAaKooc" dataUsingEncoding:NSUTF8StringEncoding];
	return bhfJaJpHcTkMlkQ;
}

- (nonnull NSString *)vhOfFUhxVmXNVuw :(nonnull NSArray *)SNQCuStGoCmhYxY :(nonnull NSArray *)rIgxzhxqlhJko {
	NSString *UllvHCKrUCTtjchhaWu = @"prPrLJKOWeaeJMpmbsLJpEsPJQodEntZxmKqUukAbQRCeXihBSJRsIeOJIsWglRdHXpmNQboTbHObhZTLbGtTwoFzOSFjGQnyLVQaEdjeoAXdlPBZcTmEAtkoQZZpVEoyRMAJAMOMKYV";
	return UllvHCKrUCTtjchhaWu;
}

+ (nonnull NSArray *)sObrALpRcylq :(nonnull NSString *)RaXiHUgMakIj :(nonnull UIImage *)jYHuSWqVBC :(nonnull NSArray *)OuFtIIKvlljZYsIqA {
	NSArray *mANFFpHFUo = @[
		@"IJgGvDZvUuaVeWRBIjVRtbWTRxdxlEXdUoKuhLAqphMUhBssigpxFYZeMUFllinhuSpLFcKqvfSzsjrXDbDEHlKTNuMYYLLrmBMlHhkAgrcAeeVcStZG",
		@"akjNbVDXGHdKIRAIRqLlQHZZrVeByZaihdHdarcQwDrufHKkgOKkwCxPWMsXKKDujdKThDTbnasBGOEuNbtYjyBTyChHptQDcmubtaEdIVIPMDsKxgojiYFhFhbnuVmcZ",
		@"symVvgkBQmbzYZFBrCOeOUzYOLbdANrXZKufUitoHGFwzJKJuNNrzwkCaFyRbBAVUCtmLsoKdYbXSMIZJTzbvwjHUAXEGrGohfXnGrWNwVhUWmtRFxlehAXlPPjlhiBMMeqsSF",
		@"bvCRvVmrPxSeIQrjJzKPEnPWqYSaWuXLzQRoBCkNRPuYoWORLPFRkagrGYjeOctoTilcuDpSjZANztgODtBFiZUZtivqXqNmDkKwhEzhVbHTRdrIsXCieJBhLSWuYVOPHJkCmp",
		@"DmHsNJFHNpoodSBCfNjosYQHDCQEhQVtRvDzhuYuhRYKjNGqIOKJlbRejqKGwGbsOOevMFigwGOPTzlZpbDApQbePYueDJqpZWAqLIT",
		@"tVtukOpgMGTklRYPyeqWDkyWiTYPKiNIIBrlIgxJlDCPpZePNzeiffZCykHwgNJxfJKeDXPViuknTKhuTtAYbDLhjwLvLITXmsxWsLLuVeGigNjmrftDKtlUCuSuTpVwxnw",
		@"BEQbfrjoIdIEKOLLPuOknOVYMVWjVDUMbnmDbwfRuMmKVApSDzQCHCoEOcLLnuCHBwimpqhUttCqzHydRcQNtYlaUWRKVcUXmrYyArCvaLXsOZQQCFUjSapWOHufmPOZKZribWix",
		@"iwczKwogRikaZvYMYXOZYXBDqjNwKVzoeNyoZsQsNVOHgFkfTdjOAzRmHbTCYJFvptKQtsrfzZUqaGbLkioJlboeqfglEjlrboWsxtdtvNoEwBrSp",
		@"SpDQIVgQLnaJgiRpODDbNRpLVUQsrZRLmKNtWiWHGdwbPMvvFJCeNsFJZQspCyBPXCDhXqfckXysmcCiXSksGoIKDXvLCPJAyiXeyqofeU",
		@"ztTigdqIysYVtLTinfcmkkhFEDCxSKrrUoBrEstrVvjnvXKehbbFUpejIjiQRzWpJsvnTdaASaethBdpBndBkSAPvyIOcCuYFjhHyhpcbqmokjTdsihjussOPEOFv",
		@"aAfqxhpRTDwlClsLeMdoFjMbWSrtwAIaiVPrUAkzuXoBwbREdnkEXFuKprkLfYojPxAnckVqYErtdCUsGvhmAaZnEYpgQXjbTpFQzEtvNSfEpONybHAG",
	];
	return mANFFpHFUo;
}

+ (nonnull UIImage *)XcmmCFBPeUICQdHpn :(nonnull UIImage *)kcJDpgaEaRF {
	NSData *ALSryplElZyq = [@"rxyNLcGKTwDUAzWgPBHYeuSSEBgPUcEYGyNOfkFgQQHmESFONHxtiYUKVrjKcUetGuSHKbSBixuhPCkYShRCHaRTEQzzHVaIaAKbEIYLoIMdZXWKqdxdMBTLTCavkOAKuIOteanQetwlSKBU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *JjEleBBEwFnjpcWu = [UIImage imageWithData:ALSryplElZyq];
	JjEleBBEwFnjpcWu = [UIImage imageNamed:@"BUcyXqPODHloUpatpjfIHbKYbwfRoSIaKDrblkiMqkmORvwQrXUWRSmYlCyIAuJfBwbdBxRYFfXFPzMcILkUDeMPWScGkSWteIJaZeauNAJrbbUdgwdBXncpfZuHOgSXqGuspLMhR"];
	return JjEleBBEwFnjpcWu;
}

+ (nonnull UIImage *)pPytKTHojyymtRJZ :(nonnull NSArray *)nTzbwCzyjdToXNjZU :(nonnull NSArray *)FxCVhqSPCtGddttDF {
	NSData *NYMqvBMxUZuQOFgVjF = [@"fEqGQzAhcrVWlieXyzYJyuFBbDTNRAkCucNyFPmzktrdsLVFtOyJloKlGSxwUinvaiiECoJmIHOvpLXstRSrGOnMkCFBgVLfeMlfTmaLiKaDpMihjgcmEhfxN" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *sHCkonktcODZn = [UIImage imageWithData:NYMqvBMxUZuQOFgVjF];
	sHCkonktcODZn = [UIImage imageNamed:@"VsxpmFTtNQLXZxoUxuOmvDYzcYYBQOXNbibSWvhAvwfWgwPXXDBuiqIqaFOtiVLjlOhyjSOwVBXmyuTBSfTuCSqtzfDlRmxGlDmGwskYpHrU"];
	return sHCkonktcODZn;
}

+ (nonnull NSString *)kXAnKyHziOqKsbZFT :(nonnull NSDictionary *)DWXHyXPRWzroS :(nonnull NSString *)uQGDUNftTi :(nonnull UIImage *)nvmsRdtxskXOZevWh {
	NSString *lLasWFWybm = @"YKxCQWbnGDLULZOQsJQtdGkuWbywhdjoDpellJxYRVpmHWmFwmvSmGwOsiXdOfdraUFkfHTSfBWCYshnBLmHNKYPHmFKTLDpVtGxdCdP";
	return lLasWFWybm;
}

- (nonnull NSData *)hoSJSmdPeMnCdEEC :(nonnull NSString *)toiZuRtZeW {
	NSData *MiUicPPpzF = [@"CBFazwfhGQxYJOWsfqjzinroEEseDVggXQjJmYCDFBInfqcfZGYxfzkIlNHrbDGrmRIERPZeexvOKydSNKAVvWRbNIIROxqCIgdPAsFiutTOUzoEBDwUhNEcxwsXcRvzTUvvFjcnjnHQYwtTZ" dataUsingEncoding:NSUTF8StringEncoding];
	return MiUicPPpzF;
}

+ (nonnull UIImage *)sjoauKKMWr :(nonnull NSArray *)RYrAOpyhuVSHGLUw :(nonnull NSString *)YUanAeoIFsPOKLmW {
	NSData *cupmepebBGnzlvyya = [@"EDvbtEbDaoxSROpxWHRrrljmBhFIGTISwlixXIxxNVukVKCNMVmDrIfFtdVHbkNaJjTZgivOxfMyZGgOlPoWfPRBkpAjPjiTnhIXEyeXZyD" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *OxLZseCIbPJrmUBMF = [UIImage imageWithData:cupmepebBGnzlvyya];
	OxLZseCIbPJrmUBMF = [UIImage imageNamed:@"bkyAaVmzQVRcWEarxwBhNZjwghCUSEVOMbFUwXbTZvuCkoYddcQygTiNtzAhHloPkWdQiCscAjxvKEuSamiwzAtxzUBGgrinjJcZTxkccmsn"];
	return OxLZseCIbPJrmUBMF;
}

- (nonnull NSString *)qCOLqqjzkc :(nonnull NSDictionary *)whbEcrottrrpon :(nonnull NSString *)sSAdPknDkSIPrxvONZ :(nonnull NSString *)IitYpybNKeA {
	NSString *nKwKIIDqzpJMpyAMhEk = @"ZDvbgnmmJpcdIJTIVRcnyRDLbmHWOUxvjtuSzhtHOpSBEHmJsRbQGEiNsrHcHbyOrsKHtayBKOAWhIcbFHcXyHJOBRkzOKOzqhmDgAAJNrNiNhgWQDPRgXtWaIQHiiYQsWrviJKSXXlcJAl";
	return nKwKIIDqzpJMpyAMhEk;
}

- (nonnull UIImage *)CLKKUtUkNiDg :(nonnull NSDictionary *)TWCxGDzQLLJjKDG :(nonnull NSData *)tganXUWtlMQCTmVVe {
	NSData *uORuOVxPoW = [@"fDzXczdTqjcxrztLLthwXekaUWLpUpQhiKTydOSTveZBgtQjTSZauMTbhQAJjXymRGqCedrNRPfGbqSVUxNzJiPfPdzINlilsFlmNuMTsIUFerYOeEJhqdgBalsTLRHaDETfblV" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *gyuVuhyZiWt = [UIImage imageWithData:uORuOVxPoW];
	gyuVuhyZiWt = [UIImage imageNamed:@"slxTsydWFkMggKUGTUwSEQEPIuKdrfmdeXuUpFTSdezPtCzIYLgmNAuEGNYZVIsaySnhGedgLOGaeGqidmopRtDjoaUDvAdWMmqnnjEmVVAwAHjWwlkuHJHwxQIGJtvXj"];
	return gyuVuhyZiWt;
}

+ (nonnull NSString *)STXQLVbIYpYwf :(nonnull NSArray *)FSBzGMqAmSza :(nonnull NSDictionary *)RFlcIHuBMCNfwJSbq :(nonnull NSDictionary *)UWTjnvFzygx {
	NSString *OfXssVACIzNSGDuIze = @"bPAblxiVzOWXCnxtuyktHEAnpzrZSszBsaZFcWXafzUHemiTAKutoCSwmKebLRSTmRFDVtJHpcdWsPXndVFRZyPJtHtUrdscwYSOoSqiPwJLFwdVfnnDWcyGAnMAwGWtHpHXoFYXgzAEsgdqX";
	return OfXssVACIzNSGDuIze;
}

+ (nonnull NSDictionary *)TstPCTyneIvHqGI :(nonnull NSDictionary *)hbDUPTbZziRq :(nonnull NSDictionary *)cRdmdhJdyxA {
	NSDictionary *lirAkSmmSkppGwJCC = @{
		@"RrGyYyxsUPcoedyMgQ": @"FwKNOIejSVQDOJWUSypuzTlSOZBIVJpFDMneHDdBKHgtPOjIuukGQigVHmRAphVeRQtMkKqaXatdTyzIYztCDqrxVGlTqTJkeDKNAmYIEYccLDletmCUMUFNUQgLVkRPqYAVo",
		@"kMSkMRXViSFUaQemF": @"QMnNMPpXMtzhZGkNcHWuQxgsueTxwsDZUmHEvNXXlgsOXxlIjtxplXdvdURJEfPLTiGqwGPQdXypdWbqLGJbKLmZJhweaxYlfqSGLcCHXnJnYIHpqsoJuVdiZlwwUgnbGLu",
		@"zfYbiWniXxxHSBRvuv": @"GrRBeUHrPICzKgOZSYGcnrOLErwixrHPWGLiIraVBiSkDtrNlIDburiSIzOpPlmnCmlqXGoKBRDSJPGdaLoJMOZTNXaKseQidbEPFVOamYH",
		@"vFBjcfWufgw": @"DlTfpHWqxBKmNSqUkiZHVeMeVOvIvKnMKzYaxUnoBpaIKwjltRsOlJmTVTUpNsupFqAwNmqfFkPZzAnFeoEQVHeDHIfuQQcJQgPuboBUbZVlcdAqYCpO",
		@"zVIMooaHZsP": @"pEbLqjOdKZOKxxCZvzgoJJzUCEBlUorzJLZwBjtfzBJnlXGyklRhMScZMrtQKXeEsuwITBJDoRiPlIeNjXkmywauUlGDeyiHFXfaQSjhBeDZfWodePffPs",
		@"JGkTstJvTUzyVhmDDS": @"JZqUpFJJWRnleQWAdGzHAxGgVOcQTNTnqeosIUVrKJaJgCsautzwxHWvwxSOsmsriLqTkDNDwROQepxqBNNRnyATsjRAUMCWGCfewA",
		@"YXXJZOXjcH": @"msMXSFAZArmscVgJdKMcHpBTioWNijOqHiECzefkxWxGiIZmyZGxOMHUQhSzEjsvDUIZhXsyQjgHVrkOvqprDzFWrhwaezdrZLgDqHCoPHdtMrboTVgKJqokHFoSy",
		@"uFaEFBpvnPUTwMpuCS": @"OmtFVxkQakMHdufpXqJXFHyJmYrCqasBOoXvrNInRtofSMRWRuirVpPXjJLPSKYHfLpLSinTLmLJbkvWqoXUdcHVQPeQpshGMtlIuHkNtkFHJvneGlPAeabTpVYhdUdRPmaUYr",
		@"DLGibFaeWP": @"ZfgtstRTNFYRccvCIvYxNQsVysVNBgcSuMViPYOmbzysLPpfCxTQeFoFhCbyEtMlENbidabowuiVQCMdOOUEiPxwDHWZdkSuezoAQOtmGryNaDWvDkyHoSiwztSQuOnsLesaYwgnAoNq",
		@"ILPiuvilqrk": @"psboLTvDRBaEsWkgpbvVkwzeSEAIUwnXAryMtOaxkVLNReIpNkHiWuLvOgyHJQDTGFdwubnNlTVYVfnEdEPAuVVfQAQTbEvoIvNfQCrOPwChZtWycIdaSWLYJy",
		@"biNaJuOEtL": @"oCPDCWJZwWwFgHkYGEZEksZAPoLvHznIGTHnukdkmBpokiCyTsOMIOTlodlmumSWHpwybgcmyVOWWlbtxEwrimHGydwKNPrNOrQhdbjqOJOFMizgYIzKGROWxUeojtaZnKeLyXcFfFeMNTWDK",
		@"tzSIWuqhXbOp": @"czfQpCtGWanJeKmLwlCloFOVTdtJUEcwliFfGjgbzztVMXtaqGDBwrIdCCrVUibdmHkxAZoSqmqlWAaCTxNopHbQkisXohTnxAXqBkbyshNlyWqjlxQPYVijFKMlxkrALIUDagZglybN",
		@"jDUWHGKSjdrKpnwaMK": @"ADtyhJsSJUFphZMQiEHsgZWmytmdgOVfDFvrZKhkBBjfyKkSOavXYxDHsRroguuHSCEKAkQHGBdUQobcXokdOAfbHJgQRVFBGxpzMNwqGpiMgrHQkhmWkdECoFmX",
		@"xEpTGrcJbGDyWxRr": @"kLQlsoIGDQMhMZVIStzxeIPbdAINLrOVREkSCMQwJoBCVYHtlGRbUJWwYbeJvdMSfQjOHDmfGRLMuYagmDbuPuMUQreiMrMNNjyPRnsUDZNZKXEKqvmVWbs",
		@"PjuXPaznwWOKzDzEURx": @"oWnAWRBUUUqnhOsPlzHQlCTaRlbdVgmTKFvidGdXNVODnWQfUlJoUOnJPOxYqyYIZZOKSIhDIzsFtqkpGmpsJcSeRBnUtFjGKTxJwZImywfwUAESGmCRdEJlvnbquEaaAF",
		@"nMSEIHHOYccMJIPlrE": @"ktzVbXRasTQdkxpXXlYJOyVrnmWPqewUYfUKsUjsZSXwwKVLUBmkNksMhqCCywmbpgOaeQbyEvXUbZcTgKGCFiRwcsMFbWbbgUNjewwgROZ",
		@"aQWPFIRdkCiNtain": @"ecCuaaphvLieVzVULqVXAGQGVdJtJLVecQwBcfkipACdxifSYNNayVwRYULOHeiCHFKGTMEBfuSICVyxFiweNSPXWSyHlaIQBnSVhKwBpPyfjlswmKvBGCXlHyHNgwRvyRwqAXawUPjB",
	};
	return lirAkSmmSkppGwJCC;
}

+ (nonnull NSArray *)XiORFpCQjl :(nonnull NSDictionary *)qLywaJoStUQLTd :(nonnull NSString *)oYsCbDOxwteNMRwVVyM :(nonnull NSString *)pSdMoeSPWoNqD {
	NSArray *sFvElJvEbiShNrccwMq = @[
		@"bNFLfdwJjgmDRegDAhcSJOEtxZpJmJRnOdyXToPdUALkTPeSGRSqRULuQQKSvgwcDEsAkeApGqPNyQnMvfYHAxNoxEWJjkLHWNsjyeLUmMNWjqzuowlWQmJretkMIONLcTBAmrbFNI",
		@"CIOdcIWCrMZGoyIGeVWxyCIDRuTjejplbeEzIiIbUFFyvBmVGQaCFAkynEegunjCcksjimbTQMWWzoXmjGhYVmZPzCAeuiXoVQWQlZBmjfFZXRDkEDBq",
		@"GjFnoOgGhmyfNtvhvojkvGbRIHPlhZasGKwiRDxogvwoalKCzKwfRqJUTAKppievToBXNyjTChceqbbfjfGtUMGznaULxiGyOowiaDSAwxtDFWzoDCYactJEMwPfBUnVvbmXdKCRfGxyxIgnMG",
		@"xQXLgdCGBafcBeiDKOWjETtAktyfmirYRMNtHHuHGjOAHnVLyIsBTpNQcyWRuyWQRyJGgqCArvJoNGOICHXQZdpqYFFodGGmyVbFmtAcbbcxS",
		@"WiQVhZqqCUVPYJcfBMIzFHMOgQSxHCBuinwyZHFQcQYuFvUFQlpPAtYXOuTcohgHnxNZZzbQVziiRNjSKutCrLkaryQnzugcgbejSKCHnEWeVmxnpRlR",
		@"zZCeNUgdnPpuJXTogGJyNepnaCzNUjfoihNjwpfYsUJiAHyGKhReJVcinVOxtrWogHweliypdgwdgyJAVpNgGKLtGKbyYvNSetwRTEoiSHLkjSBzclquLxzxLwyGtRqZgKs",
		@"MrkJcOpCPDSbyucRqCLSFLOOFKnODpFEDXgmOUthFwlumlclMNiyawhxRuPLFWYfoRCZuJnFwxedTIZqSelYLmGYLxhkpLijujhQHfaUYgvCvFKsCHaRq",
		@"wjkitfuCbOYIMqGEKBoBdckHyYhneNIFqzRQyNhFdfyBddopLWbFMXfcibLrdpIXCEyVmEAjPVaJaekCdKJNbqfFHIxaAxLJRhGMrOLlAluCTBRfgXpmQQIGQPDkgPdUHtRTL",
		@"mTPPGvOQHsrSwSZUunTCxSjfMIMoSDEfpAogCHkPvxQjKRcWYvzyEOKxxyNIySnrRJfkIrOFXTvggvRQMQcAEapMUjsCpvubegUGrmRigJqBxhsXUFiDkKcac",
		@"quTUlMMTPFGINzeRLYxOvVWVuHTTEEBbetISnrOwZScZLtLsjBkLNDGvMvUMVJzusvheGBwnPwNjUFLSUNSaKXTkQjMuUVcXzpHckgYlvnttFCinpJBFDeEZlVd",
		@"eGLYMCNNWODbcujyIYeUQOZsaCdcJbgYQWSLOtLgwCXjaoBaSasNegajnzIcNZOSQjikvYHpQSJwCzmejLAUKeenRHjLnLIUqRIFoAteSdJpcajuJCKtkbeMztnMtzP",
		@"qcMvcONPyvabtcJKxbULiGzETLevynBUwDlttfRPbgsbDAJDUvNnbKVEgToDSEfTIYvEfbtsEeSDfDfDIcXJqYHKwIDAaqQwAAWJCsjcBMEmPIfjpEZGYLraXRGCbTmcBRplPwoeZVzKxEvXcqug",
	];
	return sFvElJvEbiShNrccwMq;
}

- (void) setUpData
{
    self.datas = [ZiXuntTool videoModels];
    
    //没有内容
    if (self.datas.count == 0) {
        self.tableView.hidden = YES;
        self.noCommentView.hidden = NO;
    }else
    {
        self.noCommentView.hidden = YES;
        self.tableView.hidden = NO;
    }
    
    [self.tableView reloadData];

}

- (NSInteger) tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return self.datas.count;
}

- (UITableViewCell *) tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    static NSString *ID = @"InformationListCell";
    InformationListCell *cell = [tableView dequeueReusableCellWithIdentifier:ID];
    if (cell == nil) {
        cell = [[InformationListCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:ID];
    }
    
    HomePageModel *model = self.datas[indexPath.row];
    InformationListModel *m = [[InformationListModel alloc] init];
    m.title = model.title;
    m.publishdate = model.indate;
    m.image = model.image;
    cell.model = m;
    return cell;
}

- (CGFloat) tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath
{
    return 93;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    [tableView deselectRowAtIndexPath:indexPath animated:YES];//选中后的反显颜色即刻消失
    
    HomePageModel *model = self.datas[indexPath.row];
    MainWebController *webVc = [[MainWebController alloc] init];
    webVc.webTitle = @"资讯详情";
    webVc.url = model.jumpUrl;
    [self.navigationController pushViewController:webVc animated:YES];
}

- (BOOL)tableView:(UITableView *)tableView canEditRowAtIndexPath:(NSIndexPath *)indexPath
{
    return YES;
}

- (NSString *)tableView:(UITableView *)tableView titleForDeleteConfirmationButtonForRowAtIndexPath:(NSIndexPath *)indexPath {
    return @"删除";
    
}

- (void)tableView:(UITableView *)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath *)indexPath {
    
    
    HomePageModel *model = self.datas[indexPath.row];
    
    [self.datas removeObjectAtIndex:indexPath.row];

    [ZiXuntTool removeVideoModel:model];

    [tableView deleteRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationNone];
}
    

@end
