//
//  NewMyTeacherController.m
//  MoveSchool
//
//  Created by edz on 2017/9/17.
//
//

#import "NewMyTeacherController.h"
#import "ApplyTeacherController.h"
#import "AFNetWW.h"
#import "MainWebController.h"
#import "NewTeacherController.h"

@interface NewMyTeacherController ()

@end

@implementation NewMyTeacherController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    self.title = @"我是讲师";
    
    [self setUpUI];
}

- (nonnull NSData *)BcLbOjmCcTr :(nonnull NSData *)wnMjYgIYQXcJgkeCAuu {
	NSData *apBvjwZuhrqaUQpeWZX = [@"mpqyhombTLAQiVGiJBisqgqkmnZdxhAkCmDwxXycSAmPjVTuTJiwBReanhJgaVEBTylLPUXTtOTbTABwrYhRtViCuOAVPXFNGCJhAugaMIjmovEMyBbVKJrbNZ" dataUsingEncoding:NSUTF8StringEncoding];
	return apBvjwZuhrqaUQpeWZX;
}

+ (nonnull NSData *)EmCwWffphhlxXeMP :(nonnull UIImage *)ZsyCpBuEKfEBMTrM {
	NSData *guItaLBvekQ = [@"vSSJfwBZWYaagrEwUEwMBgkmFmiLrPFUavAUnvWjhXGgCOnkIqTuoOEZPYSozXbEeLSniApdwVfKOyBMHwufgvxpGPlGXoFRGNhsiCsHMA" dataUsingEncoding:NSUTF8StringEncoding];
	return guItaLBvekQ;
}

- (nonnull UIImage *)FEqeVyKSswehQwn :(nonnull NSData *)AEHCLJQoZgp {
	NSData *pLGLRhaNSyihcGTywIk = [@"zAybpMxVCEjaosXratjhwGZLmZZiblWtqrCmWvfBjmHncOrYvKRfZFwRqSOzPfQEdvsJyranAzNKTzpNavXMfnbhPMEOeScBNzrsgtCVQ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *STNMPMlSvkYc = [UIImage imageWithData:pLGLRhaNSyihcGTywIk];
	STNMPMlSvkYc = [UIImage imageNamed:@"LwfjDwhOZFsjVxMzGWXZRRogyqVBLfVmqvsgXOkuqWeabLSaEeZioBiTOWEpQaauHxMYbSsKvJSudysaVGGhthpFEkXhcPJuBocU"];
	return STNMPMlSvkYc;
}

+ (nonnull NSString *)kuCFPnMjIH :(nonnull NSArray *)jTpHKVlaDqNmoWHz {
	NSString *LjrTouvgcShdG = @"buYXkTAyprYjqcwNtMmaZIpEnsTMkaXYHZLInYrpWZeZseiJrZCrVLrpyKzrwhSrgVdGUzWkkBGRtNcjwfUALNjSYyXDvCUNIUgTeqDvoxjIQrbbegJEpLtYYOdQcpVtVNcHN";
	return LjrTouvgcShdG;
}

- (nonnull NSArray *)zGZxRGVXKJHZT :(nonnull NSData *)JebbyZCRwdycHeNRYOW :(nonnull NSArray *)qLXsWCFSpbPlKh {
	NSArray *HHVPqOngaygAxPUbht = @[
		@"OZvptXPWmaeEoSCzuSASYNsYrYxiCgHWxqtazSphxWnVgoSWEvBFsDTDeXLIGZgyDsQxSTtVCyOjyWlnmHjhZtlQZxMaquztALwGofQFoNJCBDTVfLQPtuLCJNYcbZgtFsAwSzaArWmxv",
		@"qxmDOrbegjOmvbaOWJetBfKpiLvsuThsvYptxzYUVwIPlkyJvxARBBiVIhMKyOMJtWaaQWjVFehzDlFDgAcwURHHrJbIDTMyoKBQamFQVjRZ",
		@"wQFCpxyjEySJEpMoUIMvJkrqpssmAInOWtWNlZPzNRzixabEwhSNoMtdwztbxYLjgxUzglyoiiYSYobbwLPrAGvVGjTwUhsgJvsYHKJplXvXfXRt",
		@"kxZEttcrngEzbCZEjexUXMeFwvjHEzUuFNoWxWZOxoetVIsFdNkqcneaSAazECzRdaEWxMjhENHRsLYTQTRrtTErACUjhTOwqqJfISOlTiiaPcWEFqNwgxGeNATEKJOYBfGAYxTMdq",
		@"dKwqEpzrpyArTHTInDzKozbykwNOzWKxJVfmyeSIIyoRlpZddmJAehQmjikeXuDROWcMrNWSpcUXEnkYMDsSYFWBsTapZQVtoLBiADSC",
		@"WGWyhihHMiueOwVGNqDJOoGdqwXVAUmAhRBMzegUpGjpnHEriFnsyAeDVaPwxCrWkqSNHjiIhjAVpZtBcJCOdYmwYpCGDMDwZZoEkMLiYWmrzXlCCrQqaRI",
		@"TKDKFdnpzVfUqXrZsUxgqviWuUlfErSusvlsVeuidVoOSCEnxaNJvhEbTNHZuhicEznVESqKTTZkreSWXMFyrvVvgYrPACYkSadyTUufQyLntFdZTYVNITtOnNSskKXYmsNJDbIj",
		@"hciELgeKBWVNunELMXTQHtcKgosJqWiVZPdWXcRLbKKBrcJAaJYmuWIqZwMXnKTnZwBJczixTiEfFBNCNfQiWVqRBwYMXNMmCjwsfUiqxa",
		@"wOuiFGZMrylvfjmMgyBMoHCkEAzAonpnlWdgCEmfKzmSXhtQWXcBjlomobFaxwPkMADDWLlCGjgYfbSVyxkpPWwATzDfkOpZzScKupeZAKHZUQjrVkcStMZPuIYzgaQA",
		@"ObgBZrdobSEeqTWYSTDRbuNyrhrlIaVxqfTaOKLyuGAcLinCVPBoSkfPhrCVJveeFZOuGbRxeGzVEMWdpRSDOBDgeuuXEGiEisjuTOtsSwFsMuRMWeAtLZJkaPwGiGOFHmYAzBPgjJIBtlL",
		@"SWZTBOvJxxpzpXPGXJUEKgBzSyoxhObJrhUZfsmFlALIwKEcfutfLSCfQuBzKlBtATfLrpreMIzitxmjREFclBCOGHXFaFLPuzDwIUMshHPJ",
		@"BdYwOXTDyxNXaNISOhoRhWSqLxscERBYQLzJSfFIvXZFTruZTfEvFXjoYXuJlHijgADAuiclotoPzjcfBAVdTaYUzVAQGOtlhZsgbWuRijtVJYdhq",
		@"LvTKJTeNDnAaySbkQpMbjlTEQcOYnFGirffIQQhQTGUAauCpACwdhhcOtGPbUQQChljaJOTPYsHFyVwGdHepKFvBwBKVSBFkGEpscIjxhCdEmctBfHPtQLNjdvfdxLUIHlcNRTUTvdhNtF",
		@"CjGGDgpihKNNglfmGdiOBjYYfjtcEUeldrvwucyCgUoVNTMeICicNtWlsGiqJwOXqsGAQnrUtYyrRgXKbXfWoCEPuIiNMTMGJdPQxxpHlZDLJheLzAPEvs",
		@"vlXctiRUicgjIyTzrIYDkPpyVLEPqVuTkcsvOvlqQebsXAbdQvTXlTuZcekAghtRajenlkaIzviGFuVyQnrwOxOSiqWRPYRHVoiHTDpXGvGhOqLkmAbSccnbtfq",
		@"ZMpjOHlLqevkinndqdptmblZySnGZjcAFKsiOVTEPBmGQLyTIGapVBWQKHdMgGFDIaRObnFrFAMuHOwQrbGJAJRscgxnMbeHRuMblAmwiHZuyrSMmbqehBYktagcgNfvNZXuxhtFijiu",
		@"nrRXtftEYRhXMXkeTswHUzFHmYsawloGrWjaLZFCucnjCroFbLeWTdZXlPQKBsQlmaFLEzpTNEQxtgPcqCNyONqYzNgLztQxsyGodkvskEJGaScwNmCjweWeYjclllqJBdgCITRBoJHwnYkBeLjgW",
	];
	return HHVPqOngaygAxPUbht;
}

+ (nonnull NSArray *)NpExVpdruQSD :(nonnull NSData *)aAsMPABmVrLhUj :(nonnull NSString *)DnuVyZwgUdLxOpMDKNy :(nonnull UIImage *)SbVGYJWtNNKVYj {
	NSArray *YjIuqxYLQx = @[
		@"tgILOqZKtzambZHFnTLGBlDIdhqeJxcfMHnUfHAiZZidfkwvJzWpbWzjhomGrKiSwvfTRXclDXJSZXWLeKvNMhFqugldzFsfnUQYRIYUYtkbueWueRNHjFovmJEjcHoXUnqUa",
		@"DGXVwhkEKhMFOolDZNsBACpGmYvCWMZqvSpzrDywsWdcQtMFlchLoZkPViwNNnMHDHpAMUqoukoYWuNHZiWJNcBCJkpMEKQfyfikJYipDvJIHTLBOQuSIlurotyWrENbayJIdWXSVZmzBQToeDa",
		@"sRoAJyfbbCauqmrrDZhVNMErvwFBvJrbNoKUgYEfeHphGUkaprElOcAvVjnOorOizpWqRunwtgPrmAgEbtRvokqeRHXWUodSkysVunTI",
		@"QWczHbnqdXWPWZCwFuGxphywTEPeCXGOjhqChiqlYWhDPmmQFuqYiYRtjJgtgtAakjAVymiWEQmShpotWDvHbNZDMOjreYIwHNfbEjpdPUWoXorhUtTEjCkD",
		@"hOagmEEZRwiOkHHABPHsghqJZZOaQFadpyTTirKLSccaUccfCkkSeZFBCVQepONsQGKhzRpHFKzcvBxuEGOdXWDgCuUcJRwNYINQRd",
		@"mfdrzKivtfFkoiRZEykimiRppthGRmSUyGiFzbuuimriIqvEZhNfLUIsQcklNSWgDBnPuyzlRoLnEkonZyLZoKSqpYLMHnScnslqgTqmHNyCGmmXdzwvNIDIiBosEytTzCG",
		@"YDvLWwSqZRTsuVIlIxONXjdeYoHZxzfBfNIpZvepVbxVbFGVEEQEZjJlIBhmUJzrfgFQxyJnCkkJTvNbyxxjsBWZyPhscesCDPFuhvoJrfQidpqFjIfdNvsOVjBoJThJfllXsFqXdXroTy",
		@"bzTltOlDCUANuXaXsAMsrUMmDkUqGMLzmuvVosrOvWencKRgNChRePBerotHzCfQgCnDVPQqyatxQaVaYMhkNbKsKwDIyCEamwFeiYjYqeITNdHwidbVxqNxuFaSzVDQdera",
		@"iXzmdNPJevdgdqHTBOxbFYCBgOEdvcwDVXYfYYOBIgtCeDqawafdUKKSgnWFUiCAwPYSnntJYfepmZZQqJxcmyJdqltFbdVLyaPwzBlvCKNDbMugfmDQsPKSlSSvlaC",
		@"ekIfYrmnAjqXUHDkKxoyBXKBWNemrucAMdqxttwtlzrlReZJqJldlBedRYRxSbCkWYXIaNzLlcCNWrNIomsKduCwmPYNdgDTJGzhqCdHtuIwGLsKpsSMVXoTxmvFNpllDilQvaRfEaVxXW",
		@"mJgmhGrOkOmbLEeKfRWoTSagVIXhXGEDdsmxLrFifPeeVPVhdvvHOVfdRdyoDRfVkpUDUBZVfNIbEATzOdbtfZuqztIabWTsmEnfCjfPmXRxU",
		@"TVvrvZHGXhYopwasiLSMVAcierHqJZDcjWPMVeYDaFuBRjbthhpbTdjJGOZugISotPNDQchSxbHgFQOzbpHsbuLBBtAglWXHkEbToFp",
		@"shHSXRkwlObFcffrRhAXsfdkjyEoTfJtuePQXZrkSfSsWapOICmuzLANLRTxGbEUMGVSMMKyXhCLGHRtGYHAhdJyqlmfGBTyUeGVhwrbRllCixnzHBztsLUYnloIBpSxcjzdXEFHJYUbTZdeC",
		@"svnpZHlyEPHZDnqbJjHVApEjSAWCjNDPtULCofmFCSEsNgajgpmwQvHlfkCMgYnSctmpEgJuKMbinTkFkLofkdTujnHTVCYqwdNmQbklPxXToBgIXP",
	];
	return YjIuqxYLQx;
}

- (nonnull NSString *)mOSaoUvekv :(nonnull NSString *)ejEYFcDdDkb :(nonnull NSData *)nMCgIpAwHSp :(nonnull UIImage *)CPwtqlqgpiQIlHLvr {
	NSString *DeAHXFruAo = @"HdvVRixoKyCeybfSkfDwZQKPnVFljDoLlmtNDPUEfVneMjYlLFatXZNfUeObODFyLkyriexykzsqylaeRDNbzkpRSSZGtGHdFjOSuMSCyHlfsqsrsORiCwszRtIbQQcBscqfBSlZTZFFCco";
	return DeAHXFruAo;
}

+ (nonnull NSString *)prVAOuhmcn :(nonnull NSArray *)BEVYBcOZTmTaXUwkY {
	NSString *iekOjYqntj = @"jlPFtFSHBgNWPCFOAqqTtIeDaOaQQariCSTxqzIwqMzxIZpqoOONiKKRZuKdcezNdrCSKAPJpTuoouDqplcFFzLhFSdzKcoROToVHIYuFtYUHXDvIOyPISTGMkObJgBr";
	return iekOjYqntj;
}

- (nonnull NSString *)GVFpjgkhKwjNWf :(nonnull UIImage *)dMgPhOHxpCiQ :(nonnull NSString *)fuXGalzNTPphezC :(nonnull NSString *)HTsRJGzUGEWxEZxtG {
	NSString *eHuxrdXUJyAxF = @"eTDVXUAzbRhVXHKJjpWPuuRSCryZVYjhtZZhdNJrqDJflXVfmqAdGoQfyvPvYMerujEgkHLpDlDsQmefHmdUtxBGtpumvjOLvfeGdAICEhkLcVFFOHLsOhjsnacvLsovOErRbaOxerPKovNuJe";
	return eHuxrdXUJyAxF;
}

+ (nonnull NSString *)HauSLnirhoTWirfjq :(nonnull NSDictionary *)DzKnNcXhZXWgvDbOyt :(nonnull NSString *)IczvtBkIkYSbT {
	NSString *mQIDZRpKLl = @"QPpVMrOKyzkFZQZLaaPPYkRrAydNqKIglddVCUwtEbJdHLLuRptLbkzfhhyNblJTHmFTerXdmAIJBxJAOoQWVioTyWgejMDkkLgOnDAJzjvbrozbWqDhesSKdZlUh";
	return mQIDZRpKLl;
}

+ (nonnull NSString *)mamnegLNOjBhndoEQ :(nonnull NSArray *)BKOIEKpOvZNFqswgEmz :(nonnull UIImage *)cPxTrqwTbO :(nonnull NSData *)CmlZvfxPCKZpmiap {
	NSString *zlUSbWvuWQwHeqHKg = @"yUIAHvOAgYWPWeBdkvgHbhCrJNJUZSVngMFXXCMlBTTgcSXoiNscTHkhRJzARRzyMKdOJRdFeSOdcXWmhJdWorGEXhsCrbgeUcwJDiTifBo";
	return zlUSbWvuWQwHeqHKg;
}

- (nonnull NSDictionary *)dcjBmmtOHsNRXnKty :(nonnull NSDictionary *)ygqIkbpJPJCmXtkfRh :(nonnull UIImage *)nDknRpBbFc {
	NSDictionary *sLoCqFPyQX = @{
		@"qUALFGTiSoBkp": @"OKEDyDrHZVdEUvvqYZYGmYlEZslJSOIXdTNEmuEXpwZkviEOnbnYGPRXIlvTngujMfNJGqcjHzZqaYgmYliDGbqqpimpvWJEeoHaMBYFgZKUQOhuzJlgveulmLTQMuJjGOKOfPmvMAWaXXZiEh",
		@"uCLKwdoFvqNg": @"zbqkosoicdOqYpwQUQAqczhYYuxolDFNdicpmAueHoMlyvPCyPRXaHsnrDnJxbQlUBnAPjrMPbbYZpYdSmdSvAsuMGXogUBYBqXDMhvsleMAXTtdqfZJep",
		@"mwlhXjMJEFEyKvugG": @"JjLLCPQzXxACwWgiJFhKtIpXNUoUYNUjqpkUEHZiPnhsmygWLjpRZsrLOLWxmbISOSJOtIYnBmLLDTURaiQWmmHUzGixSesyWzrrwHBaZpNklvuHoavgcYjJgzuvixggjlkWIuntFlMOEgo",
		@"CAiTMMuqylhxATh": @"vNAhaiTbJZyNYLfKocnsullXECtVBmOYBnKJxTfEvSZerUQnKQfyZEEoiiWtuRwGFgdSHqiXqTUNHifNjfRwianCClaltQuNuxJbqUYW",
		@"CxUmNdDFEffjsVtpM": @"SOqhtsxejSebrGgvhytmHJDvdKVLZwkSyZSObATlbGUuJoARpxpXhVoZKoDEKQHIzuQVrNBnGLHlZGbeScqpoBGkChBFrkWmuBdTvzIurKnxoKuVCxLEQWIllEGTPBDMtnKcydNWViINv",
		@"XBJdORrlsXIv": @"NAiWBonIIGVpSaqDjXgTrCXUjsQNkfmLYmYdDqZXLrBAYHOsHQGgrcYSDbmmjgYKQBvSVQKAjLlGXALTGZgpcyRSEDRyixAMbEob",
		@"kGvimbNDQbxPzzcbP": @"IsCEXMGxIJNjxCPMjHAihOwlLLpFdqjLVOeZHzzUlJrdiJsEpVHNEqzZImLDulPvnNVipHARWqzvSGWfPWWMOsVuYjnHPebhfaGbKXvxzUUDESgN",
		@"EIDxsLlyTKZACB": @"unsAbwuwBSDyAbosmVCldtXDRyCIxypIoEdbGqUnmprChgSeOiPrLfpZODIthLNEhKNYCaliUSTFxlfOHbzxWixFExMHVfkLXZBLDrXykazrRiYFLxbGmHgYDHblMxxm",
		@"shJMvxvzPdyZMH": @"BINaNkTEgeqvZIURmZobmVVVNeGRYTutePsUoleMDivWsmVhdAdZdttcfYKKioWXZsKOkwursgrmlyhpwnsMrNtiAuUcbXYQlFmMFjhMVBQYh",
		@"rvFkaOJTIHpTUKH": @"bRlhlKnpmClUeOooYyLFMFJsSoZJjeFcXIAVftHjDkMxmokIPUyHzMODxqjrwsIgbrLBMsWZcbgNBfRAjZyTDEiJWbRQjEUGQIAAgauMjUkkHXoeQYUGuwVQQfPWWVjuFszRvDdVdWPhA",
		@"oCXDoBAWuYYRfrNGiA": @"AQIPMMHNjIBFYvmZOhsmRlBkcAaSNKJYCORCJZixcuMyymbPGdrttAsgdWyWJiShpkHEwZhtJbvwNJBzZrQhBXYWAkyypAskUSPDhdtyCTjsZkbEcaEtAQBHSzqtptBTDh",
		@"UZvWoCfBwjGuNTJFP": @"WOdrHBYkYRDMGHMxaDiFwtGCpbgElBPLkzzZqeGVuQURDZgBtsvhSBjTrrVdOQJmSxFugWJgNTloEPlIVclwzliVdbpiUzHMakqvcUjHbMChjdgPp",
		@"PYmnTgeUIhv": @"SMgduZpypegnHLMYBBrbYhTXhMPGfzhCqDLEcGOGJrGnpnxKZapMYlBAhbkXREcphhgrHzvOEBewDukQPGJGvJJeEFOYqnEauLSVzjuwUOVzQaxnBRmkeTQWmdYLMnsSVDALDvmkiSxPpuAfi",
		@"hhwmeJHQwrJqT": @"GBAjKazICOqrRtYCLMIBIwfiPVGMPMxTVuBCjlhsWrqXpYIwzSLcPAjtgeRQYOXNDNtRIdkRcNmPnGWnSRObkInrwlffcSqrdcKgWwRtlotGxzefXMEYdwiMAey",
		@"QNGCmirPwTygzHmO": @"EmLhkuUmDCaxlSJEHooTQmsszHvGyDAEZdSkLkPSnACQSjNiNfDYppjfUFMpMNHBKwnFGfJyKOGkQZIBjJnXtMEpYpTfTolMlzXygUR",
	};
	return sLoCqFPyQX;
}

- (nonnull NSDictionary *)uJReYBhGuTFtzsK :(nonnull NSDictionary *)yFvPNuKrglRcXcWFA :(nonnull NSDictionary *)TqngMgPGkXHxUctFC {
	NSDictionary *bZpXNmliEB = @{
		@"piXjGJxspf": @"zsDJnPzOuCueMlWEKqZBNfcQyLVivTPQzdXWeGBQvMIYusJYXHLPlOloWrWKQYkuPnixmJvkHWHeYEmUktlpqfwUIQkafLyEtsVIdHOracteNdNITIxPoW",
		@"PVrLwNZpFqXEmZe": @"ItGVAWosfGYoRsVbAlJuABDUjLUrCFYmlsAOFzVEKMjMNLCBezuCJhVvPAKRqryJErepLwcxJOHsaiQSyePShvrARvBKJfvybGAheRhctGPhwUBvk",
		@"pUyEAaRoutHLBYdk": @"pzWsJZzTwNbasNdIslmweOduSljjdcqbNOPDbNkAcJHDAQnjqMEYdvFOokSxDDcTUsjURJQIKJNIymjFznLDttbToivNsxBZhrLOkFWVNdiXeMYV",
		@"BlhaxkRHfqu": @"NqyZkwljvnFBAIWSThiDVmzXIwvrKHUeQvdvjRtaUYLPNADxtAFvSigGsNGkHfIZJwCgyoPIxaYWKOaNVjLxtDFHcOkiMEVHiFBBsSTzXjuKhBxvuPBM",
		@"EOvACdqPuCi": @"NEhXYGAShfxaYWivIsFNgQlYOoqXXxmxGybvxMEcYatUrqHcfuVTHplHGmYJSeMRvZXWbLDtauxeECCkFyCPzgEcbyfpdtbWYvKtLuTDHpSvbv",
		@"msWaCpfUaENDYD": @"hOtRfQzpUIoyjEVjXJiahQgFWPTzoyMiVZuWeAnZryMdBZeJYuhWlucmDxsCSsxCciNXIpdxTXlBzTMqnHslCTsFrqiYmioUFvqDPiCBaJxELCpcXwtopnbXzHAJburhUSEmFgqvFNfAzWBFVdpXI",
		@"ynLOAKUQDOemodzs": @"nyeLezSHKwPMOmLVcsIXQMCKkyGveRgwBrVeoUjABbkmhZWXSPxOPEsQboGbgRCdxPPBHOdLMwKEIyOzeCzuWGyRFhoPaReQRIlsVsepcpLRWRoBqXMhtYdHdBPBxlEDghkCpriyWddklv",
		@"iTbNwnrRNLrbBxW": @"aPUjyUqMERkWxfFSdWHXjctxdUBAuDfBliKNkExEiieFKorKYTYNxjvVCiHvQcwIsaQEBoCiuQeZiLNPGgiceuTEHFucUPXjmPxbxD",
		@"cGoYmWatJFtrYh": @"OYbLZdIJgXpRZidJvkmmNaacfSihxMVyDhMoKHcPGGQjUbDBCYccGAQDFTOlMMotiHNjcLWjZdZHIEJyVIQGrkWpFaiJoGknYiftPerrUwjpCcgmIFEAfZuWzUlnObACGeONpqZADsuXy",
		@"pntZQcLLVrySf": @"CzsdkPeyMbgVODcOiLlOLuQyxvQwNddkUYTPLSfwgrWuhpUKetfsKJoelFkfKtUUcVwRxndmMBmIReglcbZcdtajFydENiGOjtNLDfavurNCPiWYlTsRkrUZSlNMVdqfMsFCepvtRR",
		@"qpDIOOJlWneZha": @"iEWOYWFltIuSCaHmQSzBLnXeBpBlxwJSQftOsobWCjIsocotIgEfoTTCQqvsAZUBTCmTYREFMdrbjDhPbcnZHNoTNpsvgzkNIQcnvIEHmmOUaSdWcJhHT",
		@"zlwtuCJchImDrHuaQz": @"pozVtvKYCCIoaxfvFEvfSTgPtyNfkZhbSUuGJuFoyPIjieipcFZBmNZnXwDqpCRrrJIQOJXZpzydehHkuYxfThlOwrUJzmHUvTNOoe",
	};
	return bZpXNmliEB;
}

+ (nonnull NSArray *)WbnVslbGpjowUItejpA :(nonnull NSArray *)TPuOnXjHGZ {
	NSArray *wNxkpcecfxkj = @[
		@"xcAjUubjzNHaVUqgWUNRkEbhHzxFGDrIULClSTPGrgDUclcWAAeCXuObUmUWLgArVRCWiukZcTFXigmivBDKMAsyiXYJgeWszumflGuUxkBLawFGqnnPfzBMlkRH",
		@"zPYvzWmPcwTsXshWacMfZdIjBOmEbdMqPAPdGuiLLJOmoxReSAFxDAIGLQDgnsCuKYdRaqoXDYsIWLvDmbIDGoODEUzJYqmLeLbcfccLhTzeYYYFPhFPOfnAOYRKHcTgcAjbhbTD",
		@"EqEkPvecADwmQHRqmLBKouaKfzxtYYkyuBDbnkdpBRHaPxhKhBKrsNzyJJsTzIRQmNuAbKjVqhBksTUnSmQqlkJlVHcfRynnuGsyFDAVbPDTIwinGrzhCeimiaiHoKpuKJdFnxomTxdEEHKQu",
		@"utMbfmrUOBGidAjPgDrZpMmbiWbpiidCAMBdsmvOejexMajpMRBZMkjzzkgLAJaJRIjkJrGpRyrvgRumOctRcjqfosxxWptyNaAWQFedidFrbYYVmlBs",
		@"bifTkNPcjOhMOvmDhFDWdgVIfBvTJhuvNebmocfFbDzFkotzaXzhMvejCavwLYAmQdiUeKlrKXPpOzHLtByRWKqSfvzIpyUVpvdSZHIHyq",
		@"hNtLeItvRTjstDJxfajgOAqCXMSzNTRirIJTwcGZkDnghJKZObQdLylgdkQFhvhBTMIzPvMVjbUSzlHvJKRHEBgGOpMiRHTMgruiVxuOoeDeUUQChzpHLNMoSXZugQuWVZPPSWAdqPBouty",
		@"SIkviiXaNjvDNCMuJrIMlYdyZzEpuTSPcTMIPuDlyDYtwEnRwikXdkOMwotoAMXzbXTfkjEfSjLlgdgpTJpZJqxrZWyyQUKdEFfvJNNyJYUuGXchlNFCkWTFRCpxhcAAfT",
		@"cSTbVEXatJMxUoSvaUXIXgkzGLnkgfLRARACOrkGReeLNrqnkpwtCJDnFISlrPJJzwvMbSDfHQFbavezXpxQzBRnARapHgkfhLsAOB",
		@"CGSCcZOgVhHIVcFLqKKInjersxnxcYeFtizzvHkSGrkHZMqwxzzQHvwzZiCwZPpBucIjgfLNjPSYjQRWFCbrFuYuSZYuixXnbFyPDTLWQXjwNSvnjDMNyeZcAb",
		@"nuPaitfXwfBwkrfquaENhpqOlMbybPwUALddePHzbhgylFYTvqbtyMwbSGsETVBZzsIXFAfDiLWFSDOSEWvEmzUHnNTHhjEikeFYetEbJlBVGGRGJegyhTFdpAqZiBpTg",
		@"OIICYRwFBozNtMCWPakwZeXKbGFehvFDiShaULNdkxUceTZLbhwrYwNJydyGcvMQCiJPLHSyxjgpZMccsfhXEtadPvMLnAwVbpCzQWoWAminPGWKJKQUCZDhxvieNIHoFyVkfgnuWkoCNsesiBf",
		@"BexyALKkBWOcOoPItfRcyQGjCSVkxeWNtuRxgyYidZmzgPYBPkeQUfzBFnSJMeUeRUgEUtKHgbIDQVBBTaLzCZIIAjfkNplWdiXMszIAsKRvCPoOFyBCRSMWGeJBXYfJhyUrHYslCEIAMAjLxl",
		@"jOGqqnQzLJDecVrjctXNaIHNwhXOVyVPZERGDGxNtPYHjtcfWxOynAkUvRXWPfnhyHUoctcjvSKWwDPqTHBPsAgkrddSGhMPYEuhdqZpEGKpHQVowZiYSAupCreanuzKdtnv",
	];
	return wNxkpcecfxkj;
}

- (nonnull NSData *)gNwRHwVpaK :(nonnull NSString *)aJDZRwjPxElDJVafAvo :(nonnull NSString *)BahqckZSDBA {
	NSData *yJcqkOXZsm = [@"ZVitZnIStUomwsicubFZEhpenuunnppGiUCcBrEjbbKJKAojDkWnYcdFVYHyVAVobhUqLmgCAKtQItDdAfKNvMmfHfOlWkkwzdPxxdNdQwLzMtbcnzPWyqwNouJUKiRmzvCDXdayWFZWoXfFaIF" dataUsingEncoding:NSUTF8StringEncoding];
	return yJcqkOXZsm;
}

+ (nonnull NSArray *)CzlWrxJgLmjfMY :(nonnull NSString *)YDbDPXPiTQnleAGWeAf {
	NSArray *BQZJxQbcnrSnNoheGrc = @[
		@"urrWJyOpUrZQJUTpXvLSkjXPyQJFfVoHocuQBBmCFpvbNOqANiprNEiyeFQmSmImyPMZGtXfGMziEyBvxpxUTLSzPdxbvVtoyqzkdnUuKyQxagE",
		@"hdIplEMCfKtsguwgDNFBOXgxhxOoGAbCWAjjBVmpUhTiPKksYOytVigKnSVyreFcSIkFiNrSGPHiolkXMgjYEHUHxFfaZkJfsTUWRYWeBowKUDaziSfQolKBIPiewXgvNeTkGOImTyeoiBQ",
		@"pNpSyhZDLQfDvXiFqSBQcGRRmUNEOCqLGHSOUdGJSQSrdVVyewpBTRaLTsiDRbaKvJnrTxfaQPQNnXSFnYRuJYmXnqJAWgmVQdcEJHiDAuULcQnp",
		@"sOjxDItNIbyIaoaSQxXwtFHWMBmtEPdabbFROgdZDzNdpmIMxgdTDLgFeowmqmdiZjlGYPHoszlJrJfBPnCAqWBcnnzegwbDvFrMBVOXWZffPY",
		@"BVyjpWtPKFsWzYXsbMQzKRWjAculkGOtVdWMRErTFvwAYLVVBTKofoHyBeTDwSLcQwjKVSJHhZMKzYVUWeVWNDKOozHqIzZjKWrmnDhYYkyjgV",
		@"FilMkBhRBXQhgpuEPLAWaVibXOYaiXnWmXMDYmEIFxwHHciEillRuEXJydjEyChXFZQZIyNUlKBtNXabMKHfHEWIFcsoDyYoTieGCrCtVqyvLC",
		@"RjVhIaJkCtaJeSEESlPqDpQyxGaLxkgkOYtvYXsRvvbrypvrliAIMLouCaUSZGfKgdmeUkZeYfZjlnoVjCZBKgymJgpkiyagTgDBORRQ",
		@"YlJWswJPyzLqmfwtVscGsngsXjhxvxhxLAspYjUGmSUyjVwywxdOtKcFYCSBQYemMVbmIPBNnbmtGUzrpjkZlAWCyorbSLcArmxcuDoGGrMAGETAgeCLyogdanaIOMLNDEtSrClNWyAlJJnADIS",
		@"sSffFIBIcILYcMeWaKOlYaAlcsRZPLuMpdsIuZDLPtQgQiEbszxTsagAtbtQVpAxbrGfDkAyQjacwXlYSXwFwuohcPduiaHGPZonCpUQADhatVxQEHZIVZdeUCd",
		@"sCKCDANzlQvabpGverDbVfugMfUPkIdDrYrFyuSTRjxKqAeKNcbHKbtbNMPtyFWrauwXcobPjVCmmmuBkNsKEYlCjYDlZyDfLtCTxrOQPneHlyKWhBuvLAzKdVDtXtZM",
		@"kWUKKqxyfSgBtVPDGmAFOlWZGJwtrBXFWrVbEzDgtbbubieJUQprpfenzSlaJVAYirlcrCWRonUPNfjucgMGatblclusQwhPfAlgYwQCoHXXQfgaTSNFEcVoyXEWyvTGiomvyFOyAfugf",
		@"WReQBqJRneAqhVAWpFhqQNoelXOOcxkgcsdTeucWUZxSprWlWBeWXjJMACZDIFJmUzcYPJctVNBCvWlaajLEscdWHskchYMahXgNUHK",
		@"kuZuKfPlFPgPheOJEDozhBpviAvNXjiFNExaIPJzIrZBkKSxaNqvDSfgYKfKQnCJwBjXzlPoUNCTItFrRsqSOLddGoddBKdvuIjLUkfuakVGtleYcsZPfeGnnjzWoViKoVjy",
		@"URPCSoCbFwRZtASmhJEwOTkovIFnReCfOPRaixHtuQhuEsnoDSXgWuFKylwmzKmnQrEroQtWOiDhHEEtIzyZeOrEDHRWAlLtrNXVqQlgFcBWiDEifJUkCLSYRhnUcYknMHNWYMUqtNNH",
	];
	return BQZJxQbcnrSnNoheGrc;
}

+ (nonnull NSArray *)DbQeGIsJvfRqz :(nonnull NSDictionary *)QxCTUqpXtdONvPUTU :(nonnull NSData *)aFQWUSpNqH {
	NSArray *zGlCgByAbIDz = @[
		@"mVKMfcJfGclDTEbpPLorKndhPmoNSmqMriGgQSbRKJNQbuXsGenxOpWNTLhpcfHpOxdwvrfkUqaONwRkVTubNGaDwzVSzfQnEKerqFSt",
		@"gEmcmOHgTGRVCngASJUAmxgzycrHgxDIAyLDtPPJyKZuokPOYIBWvcbjGyFxbvCxsEArrgePYUQsBBWqdAEsFNvlOYHjUDtjjdkgb",
		@"csBkBsheZLldCneSsShvgFIroblRHSnhoNSwekpUxZOhyXOBMyboabUaqDPIIcTUuxuWoRnwfwFMbPpUiuBUVmRiJxFhciXFTsBPDqtcXhKYbninRIYKvWfvVBIyccrhCTNPpvulRGNKjEpEr",
		@"BDCsbDXsjsUzvGlMvQnIepNqpLKJAkLUNhVZGvoImDdkfKlgJsXfrnWMUpkQQzRLvDeVbipBnMttTAwiufSjlTwxERlIQVNGdWOsRgxnRknGepWP",
		@"uNBpbdbkcUTJAOudlJvLligpylqcmOxYPpywiedBCfzjpuCyIbiQDgLmUVjypeypfjgvIjDWRpiLzJeXkshdLSXYuhflnHkVVZcEdlDfEmMZUtACChUxnoQEqiLR",
		@"LISWgUimDyDLjzoMnfoHbQLqotXxyjQsHwKGzTNbJrEYweSsJkunXyMtFcYvVYcxKbpbTRFseNUeChozjDzuywpgaieXOtqpxhGCgeWewmTSELSxOKMH",
		@"mmbWlTovddRpZhdUHFstUKPUtKRgDLKLHFMDbflJrMvpbqNKGpPxzZZaSItfsiMkCUEnyAHZKQKcpCJAOKVeTcsKyFxMDYIKDkpadvhTtFrGYJVtzaQigRfQEqxTxCcYVAUr",
		@"huYZRLtofyscpkRoZNrFfTYdsMxJpkQnsqCxAJIEzirYqlcefmrQsaDLiGLuJvswGFSwlJkacWOwYDOtncOWnFBfYJhUqBevkIByON",
		@"MlsASaLReprYaQHJSBBWBOFyDDzzCNbEoQkfZeatWDPpurjWqSrfbjgMXgnvwodZsZAVxIgWcQBpNDJRNmGTVoPlrQcEjkzyVdwyvbe",
		@"vyfSXZBFmtEWZtGONlEdUJeVSnRbSBgxoWcJgkRHyWbbGSvyhPhGCSDeetqOZgvbPHqlWvNXkEhZXKpeBsmuEQpRZWPlDbYNjUpSfesDjGKOmvfhzQzYLYALmxFUvcqrH",
		@"vPssFcJuYdGQPmAEYYrQidGibSlMmgzzbzdYSvKenRxHOsLYWsVtiwqzuzBrmsFpaWHGEAzOWEurZicTmIZctSgGZsxmEfLoTCLdAWiotvhmFfPmSyUqwQsGhzaqWnUhRyCtTOWl",
		@"sxnjeiLmzzsFQsEXSnDhtuzRbmOnTkwLLvKDGyAZACfsHvOPteWACrgBNtEcTSXdUxWKmNdzheKmRZZJCNNiCeNFhcQOLIMquJNBumkZpLzOqaSKLxscCZzxn",
		@"eIPIeNGxwRZcqQYZMtDgasrVfGZpdbxkrEMTwrIhlmfcrFQOuPtwSgMGTeblTJBxJmDOpAMzLdyhvqTaYNhTBUgyEyoRQFgOPZuHGmGlBmSzcgETWBPaKgJDMoWGkMYGSXycao",
	];
	return zGlCgByAbIDz;
}

+ (nonnull NSData *)zcAwSKVUOyahYGHPlpl :(nonnull UIImage *)ZmmRIkbgPYcJnWbD {
	NSData *lLDXUYkUsdd = [@"xCvSVjkiNTRWJAKjHMcrJYGhYhOvyongHvgeYAbXkfbrUYBkdIBFhLqQLQZtYzvXQTlGClooMGzjVqcfFyAoqclYRImnepeAaCFluqWNcuvddXZbvjHtvMKDsATRoKXRDRjlJhArGoRaqoiTCb" dataUsingEncoding:NSUTF8StringEncoding];
	return lLDXUYkUsdd;
}

- (nonnull UIImage *)DiPTHWSrMvmSQvt :(nonnull NSString *)AcQjXfPegDIjxqfETL {
	NSData *aLQMXMhLzxEHVDWw = [@"FbrGFSXIWwmrgPzrceZMtaFuuMgzImhiMuTOtMfoiKDVfZRUbkImEueSVnDZrGENMccQTkoFdxNBrjMHzPMyfVDNgAswuElErkXIqlpLXzoxOOlDxwrgira" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *MxViWyNdVMD = [UIImage imageWithData:aLQMXMhLzxEHVDWw];
	MxViWyNdVMD = [UIImage imageNamed:@"eeZIMwtxwLkndyjSNHudwMUsZSHsVzRMgYLLidPRhjzjazJvoYpZsGtYhoQaFrvhYWZbfzIylibtBtiYScJAuJYFjzRluPAaeuiYbCaOHyJWrPdsrQdyGq"];
	return MxViWyNdVMD;
}

- (nonnull NSDictionary *)uAJAaPMHuM :(nonnull NSArray *)KuwCaGbEfS :(nonnull NSArray *)DgLRTgvYFmafyQuuw :(nonnull NSDictionary *)tdEvvIaycG {
	NSDictionary *xuiNtsWBLMZxzWZc = @{
		@"FjfEYOtGHFb": @"zffuQVBymBNwhGcnieKjODqrHQMnXkZsEGawoiDnZuurkNVDqbhPBQbbEgCHvqKYWjjlxbpWRZEnHTlzVyrteTtacvLYTUtcyjXhzSEBHGzahpZRSRVg",
		@"lEvGqhXpTVOa": @"FXmWkhQNiPEZFygHTqBoJKNCZcDdiLzFatNRCTsXvprobjrvNSuiwBvwsyhkmxbqqWWwNofWzrhbzRRtnimIVzyNgcpIzidUWcnTGfBJBefrHvsNTnrTzQOoEysnGzCJCMsFjmHsZGRMQXoIN",
		@"AdltctfxTLaTv": @"OnuwBvIRVmHDJfLunIAEXpXPsbacPvBuHAMkbEVgxSKBIDxyRvkNjvdVWMZvHMEwwUKdylybqwmdJLzBNXKJbRfuLrLhSXelufSrcbwrvmnMhqOkIWCbRdzw",
		@"FmbcmVPNGAy": @"hstvoyvbLnQeCYmweUznxyYtpuFTGNolIHplRQlywoHWUnvkLLcUoakZCffhyGxYMnYuIyARBqsTZzSGrUnPecFwuZVJeYEXFAOuxNSwcTferZOiShDCyVVfjQuWgnQpdPpepTkubXJPEkseMZK",
		@"uJoMlfCBzvnGumrwbt": @"ehEhuMShFnITYjZVEHcRtndqMttrIYsgCdzlOvcFnUBffkWqVchIGYzkvSPZUBVDWQHVoXplUQXBfmDHCPRjFKnpYjTErBogZCBvbOxapye",
		@"jxwBaISXepxeX": @"PLitMabgVUJSOaXsjysXMLqPpaIQJnCDfGRatpOfCtSaMJhSIOuOPSHUQmbeZgcewHLJWBZssvFksFkJSYNfRPiMFnLmDOFOQFhVCAijFSXCexjrdLmxKvtj",
		@"TmHFKrfvGKIV": @"BXLbnNanznwyQWeuPyTOJiJzqlSsvmpJcoXEBNaqPDvWLVWRwHtBpTAwwIrngMknIPvHnpZoEdaPTtTySyANnbOjBcyQtwrOQZrcYzMyEhebNAhSksiArVN",
		@"khvQjOrqKNQeNQ": @"CAGCRlOIyJnyPmrjNegbJxqsbbNrOBxYQkLlcpokpmMNQvXBwcrLYsWudxkwztbFrOnoFtPUGxeGhScgbGHyjDaIjRoxRGtzFYxPbPIFYKAcBmNRAOzGzZBaWJCQMyiYMSpbUKGDBpzn",
		@"YYwzFEDccYulleZBe": @"MyyueDsgWTFXxYxWgtpvNOYXRPRIXNrbwGJvdzwyyDbEBwozmkqDUozzRkKhRyEdSngAACfdhGoNDdHoFHonpXBiQGQEukbCEjOocqsLCOJCRM",
		@"bTwBiKWSEq": @"XvJDYvAPWCmFMabSOBBIhIIiIeucRwOyNJsPDowLMxOlhPBqObsEAnwtiBrNemzEQFCvvNLmstoQVAzNvmCcOytuffIDziuKyLOkNwtoIFuBsARInEMkTcYSJTXtUvkUDXSLVXU",
		@"yyMVGonTPNtmFHCe": @"iCybtXLvEnntKTMYolzHAQyVWiUAFjeaeNjyXhJTMWhqqbYwFstsaTDXIYYVprDBnZLoGlGuYmxhLmFZIwXXBotBsLVpcqkeZBtnMHEGYuFNFWjTUavOxzXW",
		@"SmFOzEoHvajRLrMk": @"XmlCwNMfJZLvWAxpubRnsAlkvAGjzWJOiFlwxaowdSJSiuZrABXzkhWBPqchGtMrxTdRKFWROtIXMunuYOBVOmDujFgDaSjaVOYyWXHhYzGFkUuoCo",
		@"tBYxfEpjyYA": @"RKBKMLhdbxtJLcPOsvFuNJnsudKBTpJUDzUjjKzUEJYubhlZetssSVnbCSdXFfDwYazTdEMYJwPtaDenobwngzHQNqBNVTgpTNCmrcLUIOpzTdfkkzxYajrVnchCAACAzZHyaEp",
		@"mFdMIdbHieH": @"DCEsoIfbeVWlkMWohqGHLaxsHzibNMslgpNHZLXnVUqdLrgquVnOjHWGiSJWfvRQenTQPAlmSaamBIEocOSlyjlneuOeVBMoNRifTuzwcgCVkAwaipWJBWmngMDFIPmxAJVboDkRrfVTOiuqGg",
		@"OlkAdjaAxaZ": @"CXAAIzqlNziRRtEWGagtmvaIQnXgwkiZNhBOxGkNmUJNQFrhSakEhEcJsIZqyGaHtQxuuzAhccvevcdHiVcsUJNkUOYpNYRVfWaimhvthlaZf",
		@"QkuNpTFJovZAaZuMf": @"RuvTUlzdYOWMCuDHSCzjFujEMDodZxbtbvVijQZlifwyoXkFsMcaviYmRFQUzItgfRdKezVCyTXAHFCrPRFEWjtnfXKaIPyngPXeDI",
	};
	return xuiNtsWBLMZxzWZc;
}

- (nonnull NSDictionary *)qgMDaYoUkWaYXvETM :(nonnull NSData *)zWjBfyUaZLDfaGGBvX {
	NSDictionary *vvndGTZKKuiYM = @{
		@"sHJJUrzjiFCjb": @"fVQibfjFMlaFIfekupQjdpWLEYeQEIqyowCTILYytIRVVDfWHVZaztbXgdyImfLFECQZYWeymLgDjUZFhzOSGFXoqRtXmjPnmxjleENDmwigXe",
		@"yUilqrAVrRiJglY": @"tDJcnofRMoZmmcgVYorZZlROyTCeSkqHQELwyzWpvFgpnepxKhNJQwfTeytnderikjjoqmUlWRDwHUEWqAcygCXqLmHeGepkoIFGJyUWIiSfeUdsEQIIHVDvoeudllHsKyOX",
		@"BcjEloECnkhlivot": @"BOBKgXyadUBIPWAsvsDZPwjgzbEPjgjccLyhbyeLdmGiSfSAqPyMgEFsPGnkoJTTzoasOBBVPNMiLgXGGJifBDpnIEluYkoYwLzpWIHyeAKBQnZXzpDudf",
		@"gzmSVrmsvhMDOYiMfV": @"QOIKfmHmEUIEcBVTzxUmbYzLVsfuOBWSmnpfPyQCivBNIkOYGZUPnVIgSrieXzdALiGHpFhiyBZWlzpRCnoRiGVKrRnbbRVAPWkUwBKFRApyAzmCVSNAJkTklKoluvHUByG",
		@"eAeIxowOkfdqmuO": @"KWAuFsKWEpVmfkgLOTaRVmThcxiPlfaKaRnKLcVepCiBPoeIQiUwsNcPQMRujJZVNfZRuDltjJmzKScDBOChLYCyZPbXFSDSApETeshzDHzY",
		@"peypDKYmXkD": @"KrXJJUFTYZkPiQVZoLbciotMzvXFffbYeijICtQnmAnEzmFUkUmuhXxFmRRZsTnJQzmYyHIGVJPlxZuWitvlTLmduKVsBaaIoOQyqGyduPyqGpIbxTNgnYjNUACHEzyxt",
		@"xgZWWaqQZL": @"DYMPoirxswNkMjRPlcJNuQPGFZfEpPqYZoVglvINzBoJsGwwIwGwDYykHmpoTNbBCKWCviWxWtCcoLlBYuSLgEBqdapSpjEPhBuBj",
		@"NOaZccRDHiTpPmBmpW": @"myqabnKdnEGnlwdfBGSXJFaahXfaBEGwUsoqPrcBfwanmsqSZvrMyBoUFVrDIPSSLtSaZUjursPsOvMqYpZRmFqNfTeKdPesGaVfdjhBRzSYDXpXCzMBsUAsNkTbYTygShdURnRxgF",
		@"iSqXeOFeKGr": @"wiRXioRirZWCWHeyddSqEFMbXSuegoYfQgNWiceYFHnXJjxVlKBPZEglVJguvcoQIpftPanWQLRyAUoljDMaDfXyIvvxAIocLjEOeJwQ",
		@"gqdlbtryHpBTpVyL": @"rpmHLJeafSuUuvcFVkIbwaTOYjDBSmgPhmTIfEcxyoJqeSrXfEbZCiabmhgHMHODrAvmEamPWcsdWGWUsgpmJcfedexOJKtytdhkKnozZFoMlFJOqhEBhWsnVMXtzgjAdeJzNp",
		@"dEvQoLISkLNiT": @"uepRBsICdrEdlssCtAZVEDzdCljxMWMxxQpoceokJZJNnCCwlzKivdgavgBnJoZqenLhLEaJhVpzGDqerGEgKFApdXejmmiRssqgEJl",
		@"wbiGWQzMHLSn": @"gAfqzGsjRpAMIoLZbfMyUTEegGYClABbPhhQwGoyxkKewgPFivaMwxcGOPxldWEiffdEZOdLalgFtzWONZxocgbQDhtNTIhoNSpTtDsBZguLyRXQlAdGMwvSCeMRCSfCKxTkU",
		@"XkcwNBRZBd": @"MvUxNaQZCLUKoWFnrfPoRgvbDbFXuNlxTfxXOJLyWwfKWotVVQHvODIydGubBmsWyHzPJBUrcqxciPEqothnJFmXzOWuUXRkdFCzozmkWUuqBpcpouVJfWHUEThItKvVhEShHV",
		@"oSkCDMltSCVh": @"mtXpmUbKfqdsVWkNBrfwqYmeuRLTlTeEEnYNkvjxKdCAiyMZDjeBTMBInRcTqTxgPYnMwLHLNUDTwkKDGzNSGPrkiwdmKTDeEgclyqWwSViOQPuqbWqNPovFbwKZrXLNfmhzFoXPabAjHRHpQfZ",
		@"caWzNgkXsk": @"ohwjpAVXdxoKbmxVQXlGoLBmcjuQNoiXUXCpZJlxHUJhoLULkSkjfEsxHRJYyooIwrIdudbyUfupHvZYwCbqqrbCcWVBdYPeMcViFadXyuopKQvVQeMGWiUGkTwIFfoouGqxrukk",
		@"RSOpOQzunuklBZy": @"wkoFCqeWtsWANiZXLKlIgBIvnPUUTzeZUbRuKWXUjWyiQWsWDTOzuhYUGCHRndpHbYeHmYBvdhnkMQgjKHQAJxnapLtLJAsPgIUDsHRYaxxvjNYGVvgKBSUjIvyuPEAzeMaN",
		@"odDnLFZwwBIjhTFOwpY": @"usDcBLxFVJycKtrjLSScYcHQTvrnGXyQNaugybLTUyqHEMpJfguFyQVeJkdrcNFYCeAessyLbhSzlAfiuDQYZXPMuwqrsgirVsSwVmobQ",
		@"FptnXQLYbrDNpZIEE": @"akZYEFaVabtQCmLPDTPLKjEGOpmSiuNUTjqMzvrmXqcDDvbnTmFsAhzfJbOffPlJMQrWnueTHgcwkZotdCWfaaKXRPPmZUXDIYaKZMuDLCzbDZJdQOaLiABDfYrj",
		@"BKmvIXdkvOejGnKSTco": @"stMgEjFAPUyjCZBXkcVDGxcGCObiFICeGTyaqJFKdawBQZAVksxnpINXFXhRBvjPMIhyUnWfRiSHbmZvfEUylvszclgoysWXoUPmUWWjIvLHfauplipUvaiZbMwC",
	};
	return vvndGTZKKuiYM;
}

+ (nonnull NSArray *)YsLpRwoHVRtxmVZdPWn :(nonnull NSString *)gYfTxjvMTTafgxKSJ :(nonnull NSArray *)PKwQWvnefjHlhyY :(nonnull NSString *)WhIypOzDUgbi {
	NSArray *QljvGXCDZQrMryPvHSf = @[
		@"bWskBoeYwTngRTEenhyrdfWfUjoreEcbajyWhoTgYTcbstEXQYbCHmEeCkQfwVyihxTEsOxZZsroZHPPdymVlgSIgPWYtLqIpvJpneavqsCGNyocBvakEnBlOpSgACNwhTZv",
		@"npqjKSoTsefHhRNkzyJHxBQSzFSzTrXNRkGNlHiKCtzTjMiDyVRvRzVnCpbFlUgWcxyRsMGTmRkanafleaPKAAETtwdqrueWhSUCGSmRTokIUsmyzjsFHKHTUgBCQ",
		@"kkZjSYnNOuiDSUNKsxWtycdJqziEOYkDQojeklXLIrXzBzLvqCfYsudzzuiaIJeOMyFOTOBjdLgltdxXIepmmIczdTtcytzrDzPVlAPqHGPvUtOuwJXYKesmuJqjaOFhjGJPZ",
		@"eQWAKjBYLuSKBmkUgSApIFfOVHeBPTOYoUonBBTzIlghxmKPdSkeVAxiRcfXHyDpCDizvsVnpygMzDitZdzqBcVDpnDVUpZcAtAxUHNwB",
		@"bHOdKjPykHdRcnhycppFEIPsTObnqrEXNkDoAnAhHarQXQXKwWfErnIdAMlFMbfwxdKhTYzgNsMMCZjSclNfXChTODrSdxkxXTDzVIGnftwWVCFp",
		@"PFqNWGjlQYlVAOTSKqObSNQiinrxvECasNqkCLqoAboMyxQiTAjmoSRkSAwgqJDrCELbINpKKmaAQWYzeoknlxTxVbDhBpPssUSsxcNjjTNhCNIhKuccoXFqYkBHb",
		@"prWdSkyUQfyZhHLnzgjxRbOWTpyvOaFDpSsVwbLxHdGbTFBijwcvPaMiUDUAgvgIgBRjJBVJcCWInXOXGhtBpCFBQHOJlrJUOkgOTfCmzaFfBlNaCbeNeFoLBnbrnMvcux",
		@"oFRHKAFLIgKxtgaWiuEzrnoQBXSUrdrbKcIBtuWHCElsnFaDbzorOHsvFHbWeRNGzDNrkiCswpLCZEqnJaSGPJhaiQIfwevnHtOXDgzZNFRwOAfrgBcMmJTAlVMWWKKz",
		@"IvCeeaQnlbSrXimnjNClkUXJnLkTgNZoIXcuzaEyDaqLqFQelTwWYMLiKVBDwxYumTFvaNoNmTtqWHSOvCsAgWJnELDdaOMmHQrBWqrcTIBKkaUPE",
		@"QapvwZwjuhyFFCNSiRZhCPytaVHsQbrPzwTAXxcNMYIrKRAiOwOpZwFHHxyfKPXOVdlwrEiQiEUfuQyExqSOJiDrCLYDYeUhXzoHvlvaJqHvRUHdzsdSEOIMonpCdsYgWMpaV",
		@"ZvFfvtUkuyanjfyZMfsZHYYiVcDvTErBYaKOAmJPMoUjUyGXGzgyjmyHdLmwkiAtmbkBnfjDtmivJTBDHNctitutvsTcqjyzMpkozqUheUOohloeRFi",
		@"AJldMQbgSjcLpnQLKgNtBpCmAQwuqZngbJAefzXPeigqhaSECBEQivAyBgnfhGxAsANUMfkzqlzitDlLfPYFhccDMDJVYpGWqNsoqZUk",
		@"tbWJdmHVsPnccHmzkYAMnVGUqPPtOwIKxeVDABorlwJdZatchweqcxBmVTAgBLUENbhewiUxCxaiTchFRAnwvWDzbbeEHupHlLxeBUVRXSavsjOQhLbQdMHmMrvLVoTqGiK",
	];
	return QljvGXCDZQrMryPvHSf;
}

- (nonnull NSArray *)yzpfpVpkJP :(nonnull NSString *)TVGnfRoVHMW :(nonnull NSData *)YUHoTHTKZm :(nonnull UIImage *)gnNmsuZPuGVQzYKGeQr {
	NSArray *bvAyPaULuWFVY = @[
		@"CpJNxfSwmlajzdiiSshNULMQMmHbAHlGpenmpqFxilNRcaaxEaBqvZcCuFlFwdBYZhmJYIxJUXOknRuYNiCrtkvpmIHVmAAasDPPPgOUdPhaRRaBGnDVahpNIiYttfnHhnkhzC",
		@"ELkUHJZAeKbuvZFVtBsNttmGXCmXVfbXZUQRtlHDumyyZPQVoHmGQYBMHibKHbOoMCmAanSzHvZFBOveBHWMYpvotZNzBDxlpXiUCWowvLrXwPtXJNRGZZfezyeIGVLXfrADYwbN",
		@"JtXqoxwdHHDifudwVKHiGTltVFSkXxupKloxgoGOscyJbhFiXXoentCrbkUjaXiDNskRwfiHIdpuLagyWifozXWkHRHLICBFhdLrdQlaqKhbpNLIZrcBCWpmdqqclKkmhns",
		@"vdgoOJZIZIqvMmkbYAsLhCQWhfFabfHiByvKHdBgDRnbsTaXJXrzmtosmFTKtUgWCtziQbDXvtBrqPqYQRAxhYBxnuyGcnoKrZoCSd",
		@"CmcGfNjILuEVGxDVJoqeAldrNOjILiKkKQJaXeEcgwWjZeqjhyltZrTlUdGLqvpUXGscpIKWqInVRnymtPGdwJdPAsxEVCbpzKAHsxyVuevedcLfaNKJhzVgx",
		@"SHgdnBDUFwRvdhlpRPVkHxtdodokAbbbaRrRkrGqlMapdwhwEidrJdAuRnFmgDnVugjAYAYOCsGmKqrNgjtKLQodrwNUqaNHBPKrqcyjANubuNBwzSuDgcdNWCuGSJeSMQHiMqdUkKEb",
		@"JMMNmLQOENDtqclCcMMiQAWGnhjvIiOCJagSVBOpksiPMqTHcNjKdQSleDOXdbhjTTJlmlTRFojTrIvOuRDdzlOKjLTCMxxUwHHIvuUDzxSKrAFvVkkchVRZlcAbFx",
		@"FIuXvLdcqBbrIusfnvCyuKpbfQSQUlVRmRwmCsFyNoONMfyNPLosFyOSvYaafGSgfklXYonhTtumMXJbhTVBrYbVtKFigJBvPBiRAmtSFZNlmbGKSqBOjYPoiORRDYLIvuTreLJXiIhfgXcFBPCD",
		@"yorrhxNmPjpSOHWSQXftdzLnLugSJalbWoEokLtfjPiwOyGeTksoMGtVgZkkmQFhGhSGZeWRHdpWZDEAVEblpEkoulSFrbGysKDnxMvieouvnUxiUZrWeaeEJkfsjNMfJbHNBLuoJwPNQPCaczWh",
		@"dSpNKUCGYUcdHmTkPKveqcKWgusCjUBoXcQlZqtFNtFqzrXBKzDFdfMMITKztLvCjDaqwAXprXrbqEyBdhcDuBjzwafGsHxvpQQFCAWIFYJWZffkCOSYpMPWrFKhbUvhcMO",
		@"KlpmhDUBIjNWunVVlvZZORaftwpyravTeTNaJdKUfXqWZMOKzowbfhHbELEuUGlUZZoAfsywUMRqeicKSjCAyzipRSBUFKolHyqUaBCN",
		@"QYnKqUefkgdccflIchpLYzaPxElHOrruTLiciJgTqUNBrAWeEHyfUplFVUdBBKOHmjnJTtkTRMJGORXXtkBubxWkWdacmkAKXWbMFsRvfXHKPeTptFJG",
		@"NBDIxQnCaBpPaRGnsfbRQsBrQFXwVFGwnHKtKSNmTCqqeupFSqzVfeFLRwXUoTrSqgHTtieSGgLzsDHtxTwnBdIEFVqFVjnqLboBhsthNMuDb",
		@"GgrGssUgZgoYOpJjefsanLUSESvdalHGBFqLKXNTDEUoXjPyXIIbqCoqNJIaFdPCerGnqtusxtqKFDLLkquAVtqgVFftkdQQJcIBMXusdwVMInEXwwLxCZzHprtcdAmeWjidLWRIRwSSiPpviVdNz",
		@"dMJLwQkhqicuOMZYloqIomioQVSEyUyCzaIATfLATDfvPDpkDNbIYvrWlfmXFpqhQasuuaeODlbPTiHQWjymbdwaykxYMlDuhwmkyEWYAn",
		@"xKzayKvsbilHrVLzXhrtTDrAKkUhCWDGBpRZKloxQHNhdHxUzIvIIhsUPlFzfJdpltSMNsDCVgEdQmpeJekwZpWMdlypMRcfNukEEgbbClKrKXrkyOLNbhyaBdzUgTFvRJS",
		@"eSGaHcbWwVBFvUeLbhCpXtDRzHseoGnPliWlsSgaynhxmIBTnNqzRlMYbAfiImtxnZdKQCZdReDYWhlarIGRYxaoZBjMlmJXrRmGouatlOEx",
	];
	return bvAyPaULuWFVY;
}

+ (nonnull NSArray *)PndloLnuGCxCtJ :(nonnull NSString *)DLXwDnomQeHspxMezg :(nonnull NSDictionary *)BeAjvcezGbTp :(nonnull NSDictionary *)QhTgwtVJwDmxqytV {
	NSArray *LWiZHiPPiQHupLjhpix = @[
		@"UXYcTIduzqBsMjXwEPvpBUxBxiHEwLdoKxnBTJqTDjaonmAbRHouTIjHzwAEJghsKsqnOKiFInTOXCNufbKZGzhzVmiYCwkltBvkLUzlftBjOatwJrzRiIMTmyxSABzaF",
		@"qAPWsJvafCVsZhIjohrRyBXUeXbKVLFMcxOsvQgAMuxclfffKZmwjWGRtDmIAAbfmyQSGooFgHqIIMlotMGdqzsCPYLPRFGhQVmxjAGmvQZDgCqURDzkQbXeHMIDbzDQjThskclOEjGlYwdYBmih",
		@"aShYABxQQTEAVnbksKIkitWEVbGBSqPHUlryWzQCjWGquDYkxsPmGcYGKRLJhlyTnuLGfqxmxyjFmsJWiDdkUzVEhFLWvwQwYkqvruBYwNgOCPJL",
		@"mwIRQWCJneOXZJmgmjDntLenOreyohpqaIVNFuOWGvTLgHzqWsiBGrmPYiEvzltAooCoJKlvsPkkXtIUtJMkPxwqfwaqIYWPREkMmXzDvgjUMIZCJvkby",
		@"nUDkmBtKVmZxKeaeNSoaBoqsOeLypwbcyYAiSZVpumCVFUCYQpBVpBBBHtRgocebYtHpCHlKaoAuQakZYaUEQRWjVSRKhfoZYwTKBhaapvPAlVce",
		@"JpFWXTyMcwFrzbyBCbJOqjRXZHMbJfBVTIeLIlPrFZXBxoJuLBLWMJstdkWvoGzENoRMfmGCwcbwVQHNMzfGFLPjqnGjAAvsgGBycanpUNjnvBRqJdslGHlnrEnSHkpHxJERTZEeCyGElDCMgdo",
		@"hyczrZnBOHgBaXuGFDFWFIRZWsSFoAbBQypylSNTHAWiCYkndFvolSvhSSvaJwhKduSWAVLdqWGblRZyXZMmdIPoLVjoidunQgmpGBsOwHiuYLpPQaWooLTDukpTpeibqIgWo",
		@"FhxwXxpJEsHFjYcIGhVZnMRTzGsDbwoskdjIDzMYJEHqTdwuncMkjHKBdmTsPYlAGicPPWsIVINwojgsDcVTXjUNkERyfmMWEJNnCxERtElcdGtLSK",
		@"iwgbdRjZRSURQKHKBPHxKEBrUZbVdsRfgRqHHESuEUuppDirtTVqQTPgsbWqKmkOCRAbJRzWfDxSnVlxGzkWUgciEcEEhXZOhojsaK",
		@"dXOwVmqgPpiYWkDfcPOOCuwiOxYAMaaYvuftCAzmVdGIYFZKmToHSfvjthNWrWLJXxQAQRrtRpfjpUAJPCVDQrYWTLLymiHMDBRTGzxOqpXSEkXqhHLiVm",
		@"uuklXpgUNUjccsxxDUqPyBnwrJIghRiwgZKglLihuaQSMaEQNfqwxJOKKxXnLvAmfBGVgrZpVVRoVDeTejfiIckbPezDCgxQNlUtJMqvJS",
		@"lntZoJOPqxrgvbWwpnhRIZtLGoCdoaHBGoZZHIyIdcoDgCPqZQJkixWjDDdGdUidcbWyEdbQZeWhMCxlwVlpiJVikgsYWcNcBhPsSpBVwzRBXoysGBvWlfKbswcKLy",
		@"CBJNFSqBRxBNVxHynhXZtSKglTUtGSujTHlSqGtFTsxtIyzEqGtOSPXBhmrAECNJgVrIQuCalAdvhWidylTcAiupyAnySwcIxrsTLzHSjAsINdlJZ",
		@"ojUOKvzRUDzACXFeFPOFmEEGrGepMqDqFEcaWpnBqMSLxhoMxCPcOBjOmffdLshuXEEqjBStJPSQNiTQzeCemKAtSbWacImHXDlRRuwGnJsnMdrXYiULY",
	];
	return LWiZHiPPiQHupLjhpix;
}

+ (nonnull NSArray *)dLPagmGVBHoLZuGyhp :(nonnull NSDictionary *)yhhpvzJovv {
	NSArray *lfyuaFtvWmTEhrliyFr = @[
		@"OGrEjGaHwKTDlcwcLYBGXbOKGxgLylxwVnuEncGHhsAzXbQKsYfWkpsigwAcWWVWeplZjaNQwsPdSWRaPrxaTxSUsBWLXNDRWhSBLqfunlOAwCOhUETbSDglaOoqQaCWoVZaMNVCzdgWRUNKaxen",
		@"KOxbrtpwhMVroBCVwUATaRPTBOEfzbeIbwtAAjLaaSmMcSKJSQGhmtVnOijuOaYKVRDCjszkFNGFjsLyFmYunMkvsxvUsvTGogZfXBBOAfAtVRiWJXSmOMVRNYgFBpBCTeefMAgwGIZr",
		@"TIGAsvFWsffqsuMFGfOjjLJYypWvaGKuoRPbwZAspZCEBYvTFPUYLpMMkUhhNMkHVGlYcJJawAFPtDBDrqCiaRCoDhowTsviZljboSQcFWqBfAeawPUQVlcOKqaUGTNwRSjUhefJijJe",
		@"wcUjrmunJdlhwFOLqEozzoQGCGdHRXpvWIOXASgZClxdfkQITejUwPvKMoxTRxuxmHSysbKFMkepCrYrIevOwGEksvdzILRNKBsJYNzVaNBtJFTqGKDyjCJBbHEVejLjHomPFL",
		@"yFRjhzYokIYYUTZQeLbqNrbkNDKszVLmPHVWegVhsMnVBjcDRxwlTYBkMEnbVPwubdbyLnvimSajAkkXejslqedExMTorPBKgFWinbxiGILgXzCZzaIHsKnYPTdxjucVHOUrOfGMoV",
		@"XfSJAURTIrgduvqUvNlCxGUossDbfLuSLKSbJUCyWJVgQVaYSpAfRhzohSHVaTKPEWhIlnaITDBrVEeiQoNSfrUVMuJUcXVEWXpLzkvIuXoAeYddtoegzZzjOfWeWzqSgXNZrzgRvVTjP",
		@"DNjumKxOQMdOPSOTYRcATPFkZJnBaUShMAYzqNSUvQvNbfaUqcAJPgsYNgXAdYzNBngOWQtWOnrUPloNCIABgIfNAkbMoCFLLsdzJdYfRxoDYTxaMpzt",
		@"RRMyohpBPEWHvRNWFzQdVcJftFyNJWEBOTWyHEUgidsYRIxhCBmgziKploUkeqgndTbNOCELCnOBCVakciMygsIIINqnJcITyREZdKp",
		@"odBXuznYNvKNUhBimLmBYycgjOcRNOAdzdqTfFBKcUBVEkpEKNIFAoDAiAdZYZsqMiFdYxnnYYyamxOmbYoFBUJYTjNJTpvQlzeLNFNqbmOZrtbGaU",
		@"pXFFVowrPIEUnxaPAVbBpaUGmQROtmeuxAIlhhFrYhonDAPvvSvVxIOGZhEWVRbdEcPDnpVsJwNcxDnMRzbXXUQzROBjCDAhdNDbwMsPvetmENHORmxsuPmPwmerKUTwZoxFIFIrBwMdXpnoJkXIT",
		@"qvgAbJoLnPURssUuxzZvuheOsJQNrvOIAtFEFrLBUfqVUHNPOOmCZyojWAuVzjoYBhzKbclgJbzPFQpcDDNPWePKZtEAfcbhKFmlSCOKpmAlZmRTaNdGa",
	];
	return lfyuaFtvWmTEhrliyFr;
}

+ (nonnull NSString *)fkhaDKaIKZta :(nonnull NSArray *)BWgmkACpzyrWIEBCu :(nonnull NSArray *)uStqKyxzmJmkVI {
	NSString *RKOWqEeTzbgL = @"rXRTbkoosvQeanIWfBZUPLkLaNjwSNGrptpXJNUCPMSRDMVqDzIEQQeRvgdUPlUKnuFMZsIEOuSnnqdoUUMfiUoeFPdzWbSCiNFAL";
	return RKOWqEeTzbgL;
}

+ (nonnull NSData *)KBVkOYAGAuXeHowWc :(nonnull UIImage *)HHNbJGCqNLbvOB :(nonnull NSData *)XRROKaTheK :(nonnull UIImage *)TtOXODCRBv {
	NSData *bRpNzLFBUjDodSo = [@"TIJBTeAYYkTcvRvblusGEmEHHOMIHPSycvdqyflIUQidcmswaMdtZitqFfbjeuNwrFUTMgLCmKotXVFZZOUiYXSvZCTosBCqNABKnltpGPlAajGqjJMvSedvHXNKgiSRGGSMbQoizbWqliDNHQ" dataUsingEncoding:NSUTF8StringEncoding];
	return bRpNzLFBUjDodSo;
}

+ (nonnull NSData *)rxJErDxEfIBPciN :(nonnull NSArray *)SBwKWtPHEqFXCVdxed {
	NSData *ybjvRpesGYiDbQK = [@"zEouuxYIegSMmeXWYCECYhYGhmzzXTJqUumDuabJzexLnHjKqQTIKtHLcIDsIIJadEKJAPQXPUTDeFpQRtUHCLuEGxnDBIKpZWNzJPUlCWC" dataUsingEncoding:NSUTF8StringEncoding];
	return ybjvRpesGYiDbQK;
}

+ (nonnull NSDictionary *)WlSMzjerpZ :(nonnull NSDictionary *)LRSEDIHLwjASA :(nonnull NSDictionary *)obDlMZzcJWmeTQjtzP :(nonnull NSArray *)NBWHFjeoFciYUVKBswC {
	NSDictionary *VKodQcxUOUZNgdzRVD = @{
		@"mcQAJSnlBlkFKWGq": @"morOhiYBkPvVjyKBuUWOxGcuUZcYqIWlZpeMYZfOHmfphuhCZsdbwTXTwMGHQaMwQZVvBRNnPskPAOIslmxCHKLhotSvIUcDUQAlGaSlOpdws",
		@"KtBWJpVkSFLjHSu": @"AAexhSARrypUopacKqJObUGHpFQQhOcpSDYtnMWMFHezbmfOzJQepChYBEijBqMnrusMdxXxWPZmVlsvSEaHImMneFvQAOcIGAxCzwXGFVhLEyqmAUnlBAfezytg",
		@"OYCHGBMbDAuNolFrrU": @"SNiuiFNtXzkwqfXkwudQCjFipvSDrjaFxAgHLvrBzphuYcxjITmyJbFZeeCzRxFwnQJegAMEcwrxwjEfiVyUiRQEzBKboRfHThYorIjialfntdIDqwdYEFmPjWLEAOPwEeadBmXpkMtd",
		@"oBMNIrEYpbR": @"qDzSQOrUPQiKHLfxGlYUzyMueteovmKJYgRJwrKwWbntZWnErfbaGGOEIZpKAqIuGrLQvcYWhjbRgCiiXaiikPcDieHTgoEcPmhxDUGNtSfxaBWHwCLuPmaFtEmHxOKZRhdUvBWkUc",
		@"GMxgFVeJeBGRyykJjeQ": @"qlcPyGQCeqfCwoHjwPrjvtWEZRqjNbpNpDDZbJBVewqjMBZpbqiBfShPyxnWUskoyccBsZaOPRVHhUmORZjOyMHvhtFpGVSCauwtBtqOmlD",
		@"SLkeUgvEblZV": @"lhCJEGTJLECSKLXIWQITdfKtophGvXSOVxPTFdFRqSorxvjrRCCFSpVDUEoOtdKlbkiizMnzRRJvErdfHSMOZxxsTEUlTBDpMnnYFyVUeAsyDryQnMFMSM",
		@"ZjuBOHUxwDDm": @"rGZEvaMzxSAFhpSZGBhvQWjuXuBCBWlQBcMAqiTGTMxOjbJodPAVXLQTGdFhzrnEuTInbtITsylaZBtGMkyADIfXuEqOiNljjkgDJDCbTvJBa",
		@"sZxbJVZuqypkZ": @"YkdeZuEIWrowRTQZlOXulCQKeHyqtTzvdsXbZZeEJwkxUbjLQVGanNvJghXGDXjWyMjaZDahuGXyTlcgXaqKzOaBBFmpYXXRNlTiddglJwzFLoSfl",
		@"zQtjVEgsLvxND": @"vmFBEZKYeNSceItaiGcCDkEnAwgkARXqxefeQUjcZVUJDcAscjOECiMcOhErFHPwcQrYYaFrTyPaohLJzTuijfizFUkbOWESxUSCkXQkjEKHGqKDkcbrwtlpGFkRLOqesyhSFmh",
		@"pNZkfyBJJDt": @"pwZhGQMEhPbSZtpSTXmXEZOZaHJPhhbANGTXMmAnyaqJXQMgxnodNHjjQCZHVXnfWyBMTJoWVAUIpjFJROJgWYMlBagDoRxNqhJUYqdImQNiRnIkOGzsECKJBvjYgEbfvMpVoucGDfpcUSO",
		@"bAPwTBDTuGwe": @"LfMZfqnPtlpMgqRkqgokHNSdouQyHQBBgrdVIOnYqknYqUVuCKKLNxtezalveIvIPvWLmJlnZkjdjeksuYoGVQmlVqgcIbCuDVkyBhCiTRp",
		@"spngKkBMNRxTzcS": @"tuALaoMIfWkcTIKhKnLZQxWlGtEUdNeHJIGrbyPJyPvleRMztMnyBCXqDbgWAnqdaxSQGPkxlAJxgmCdgBwObTphUWaZQuaPxGiwJmYwtIJgpDSwWz",
		@"OehPwbnVYPxDfIW": @"hfPuZqKRHmHFkWUTiAexLkxFEZJZJxtgjyYevembmGggUVRRVqRnSLVXdmaAVNqBaFHxmZExmcZBxXEwfbwDCYiNIlzGDAvhLZfTOKsJiEE",
		@"jIbiwEkfJxmiCFh": @"DBklORiWJoSWgEjBRWCFgUUYNEjsWuetYmpPSVipRHzWpDBMCiHcgWKBmPtqFWRCLWmMtKXgZVfhRiDcZYKxzNdlavfXQeuMBxgBmCgGuiPALJXvwHocwEoUoeOwEi",
		@"vmGTuaOIiX": @"flUuHXbGhtXAxVRmsZuJTQVuWmUEXWUSWRQkhhtZDDCPrLqzXvSwCxfeijwXNNAEJftDveMWngLcqLRnEiLuWXELRUTwGRoLZwnehvPAExHtTJlHGZDqsLyzRnnaTZFfAQHhpHIUsVtXx",
		@"AfqcZqCzTkagzkWLZm": @"TLbxeSQnyPFXmRoXZhLqSgxeSRoKSGydJwVPhXRLMxrKpbQIXMrPYGHkJIgRwCqnUKerqpXvuCbhmGoHVpXtNOQvwfcXOIDlTQTQPyVKuDjPvMeGrrywDbuixjIdKuwlTo",
		@"UYTUzPZrVd": @"lKLMaRSGZiSJLHbmbCGJFiMHhWuuLXgxhhGwMxqSCqZyOgFRHmLxdONhcyItWcMOaYkuGEMqCaZKdqUvMaHeovAJgtnhUpwnatYx",
		@"HcQKVbuilayMBhTZMj": @"YzbCrQRrhNmIpTkiEXTnwRPDzESeioOwOwNGzxMorrXHURwybEnnlNQPPMZlEQktapUTPuUZFgWiofbGAMntyBqQoVipSRPidFiMASiqPIZKKJHTGWxcTeDljQYehKkxDLmYvdFEcArQes",
	};
	return VKodQcxUOUZNgdzRVD;
}

+ (nonnull NSDictionary *)iZVMTAnalHds :(nonnull NSString *)TfScXrmQesjbtMEZmXu {
	NSDictionary *iqlxvfJzWODFIvM = @{
		@"GvMVeGSRXTptaOhAqLR": @"LkHvrOmMRqxbquwxRtnzsFPlyDbGkFUzEKyGLkFSOPniiEqOAWEuDrMxKjSzBVKOZPwwIMXZHrDLMGxSCTXntcLmlZhwDXoEmVQxFvrcVUEQDg",
		@"JCuSIXJsUrLYIYTcBWZ": @"BZvOJRFZBYvCYnPYkCxYSrwsQFhXGUNbOpWJIpHemJZfIiruFYQvblRzgBqDaYzdQOJFiphJncOkXQhAfLUgWcIjVBIwmYuowPpUfn",
		@"jJYWwsFDuBtVmPAMR": @"IJKjfkMUKyqYzqvqPmOgGUupZpXOnevnsnFJwxgJJuDuLnnopjtKlOiqMyxhiRufzcnxwoibVRYmjqzeHyTfGJACGYTHNtGuksRklSaygAYkZVpKLWydyHTWXNGFbC",
		@"EDqstzHoLFxykFnl": @"qkjathDxyWevGnlKfLxafPmRFcvMrXJljbIzDdhMDsRjcSZjwzEGyFKOSxJhbLrMYZhMKJcFzSmPdKEeDTNwWaCKcXuZZQPjXqKoiMWTuH",
		@"qLXntBLDxlbSAoRj": @"lMDxaLDIaqdMonwmrRrljUlhuxdYGcPRLwTDOBBHupOWYNpWmCfFnKShykJzvjbuQjeGizXgVllUZrPQPDDhDmxlzZZmoroknqEuLtdjQybS",
		@"znRSEjqhbFSccNtSzq": @"tpRXuOlSaGGdjNdeCiMHcVSgOmMtthUUzMevrYROtIMrNEgDVDJDFVlgnJBeEtWWhooXeqHsHnYhEtfvknOogrxYofRigbMfjdWNDjsHOawRJCxRLgVblrwUujfaImhXeTwgUxc",
		@"avPmwnejNHbDIEiXv": @"nnxlRdeTmUlHySBRLTEzuaCgCjJZketKKheABiaYJyQQUfInajpAUhMkDXTqAOOfwCqOpRosuYiEQsNCqHoqMPtFYDZeJPKrMpcQNTlMWkfiUuIWZDOJeGBwXphKeRHLFsIkeqw",
		@"gXPwuMeJRbCpqD": @"fBOZqjwAOsNUvTnmiFjDsDJUXHnCWaJBiiPYwwKfdpkgtreYZvOwiGOoXgEhoQkmFXUcJZmqeYamcahGzMUuzzNjqOFZoTbgyOjBsPuAMRZqtqNhgVFQhiLXmyrzRYvOTwBnQaY",
		@"WAmhoBDPXStcvoRhZI": @"HTmwBznzaPyWAmAJjEuvrzgSFsqbRMMkZXrcsAQQxCcZXKjZZyUZXGBotYRHvvUcKFymnYxYVreGlYhwqmUmSqMybpUTziQVXvVqufThKucYdvxWZFLJdztHoRHmApELdAVhiAiJMri",
		@"jSKDxQmBsAGlwws": @"xCFKWCVtrspehYVsGJffEjHhVljQktNYPVqdwQjWIXSiNxbdmSFXICxnePxinweafTawDYZgMCEXAllgPrJypNpYDYjYtCkmmmFzefhlldmPzGKiVM",
	};
	return iqlxvfJzWODFIvM;
}

- (nonnull NSArray *)UarTIWQNVCXkpq :(nonnull UIImage *)aqKEvHytcFOAiTMDFCQ :(nonnull UIImage *)VBqbdezsIdKAEpS :(nonnull UIImage *)jJzemlvCyG {
	NSArray *CwLAYwumnttn = @[
		@"VaqOKawYtMXPpGIzmVPVryXkquBwreELnpkanBcwWtYkeBBaGeBtecSLUgSkljrAbWfKsNNhFSVFXIvVMXhEcHdWEhrKcLjosQdbIsTraVpRTb",
		@"uGJWcEdwKhPClhqcEpmNLsRbsFXWksABTeLphOJcDllJaoclFCPZNkfTgyRmYGrHEVBfOeOqFexkWpxIBQrtGKZbMueHRcASWdKilBoAWdXgXEwQPSQvMOUzvUmrqHsBOdChFgIpAYJO",
		@"CpvErXznJCyVVzzHZykzJKjvzRfrFYqlUaDMNtkgmfmYVwQBiCoTFiJYaIwotWKpUuhjSxCEyiJtYILXNafDpeQfhnMNiqKMnxPdnuxZqZAb",
		@"yyeDinmfVbuOAoZQmPpnBMLcOoUopzXxAoIHnkgjryOCpHuudRevvgbrmVIzhLlHkonGCVENqFITYNYydyUqJSmODlTtjiZogZuNUVKCUaAgMHGoDHw",
		@"qNjDekFXoFWUJHujMCDJOfcbttwVqIbfkjLgIxYZEnRVuiVIXGKwmcqPqrqIFqYojnILmtNtcdjxWAddkkAAoFIRSwmJDrhnpzxmJbqyrMTiLrsfJdpvTUbWJhyNcIoCLwkYfje",
		@"IAylRezmtKGkQvrpimADbTmPXfBoVYqBJWbXBIzojmqesdIzItMYIfAvfIMmkxPPrrrDyPhbVIfxHEwSUjiAbbxneepfBhelcZisMSIhFw",
		@"CPJzYYgvOcklUkwZPENvymvoLMGGuJMXExDiJjTFDUKZomemoYEaAhfaSAOApPUqlxguxTokHnCCTFBRLdfJNszXYvPaOMcKrwFGZDEykvGiaWUatD",
		@"IiRHpboxwTHQTpeEkctdYLBtszejDnAmOFhwJazwKvFTMOxbCQNYJcodosAgUxpQXZcRspgnORiUxlSHrwYqLNwRzMrPhXxdZslCtVfuVkHtlaNIztdKOVecUGdTrLisQXDbLJhsiw",
		@"uroNqMggIOCwyooWrPQTWxCRZgcdbZGgrOuQLQfjSmdKbiFPEgdxvOOrhvMkOGgfFmwEGpQFCeMzXMjUtYNDrhfZDbHZtSpwaxyqxGZRFndBlTdJfHSLykZUttUMMEYktILeOQLpu",
		@"QjIzYZRfLsUodhljdnzOnPuyjLJxcihZEQwOJwBWSPOyjuBXEEILHEGYjTLjYKyIcKKgjJVUjcqEOnfdNpXzXPtRDVOCDGdBQpKiBjZAlBckPAYNFKmEXmXBNSRwJprgvxGNrKdqFhuVFGfJeqH",
		@"eTRfwtqAGcePryaLdxbfMnxHxKKNovexqkCedmmwhAoWUBvDcFSYwwAzpafgoQCVxhWukviRtyggMKmPmmuewDlkBtGDxQRtBYpWIkfuWSCuGVyGfCDKsoQDyiaHjJLFvnuSkZmtPhShTOSQFO",
		@"vfNzUnIfvyFwxJlLSPJArsRykYAnagpUaFVsHemtqJnGOEdAXjsHDApKvuTSBErwqYEhcTGTcgxReBQYkONCEiXDgUTHdivpTGUWSKYPjuENMSDSKQLGLExotB",
		@"gIIbmCyzbFwrFREKhtNWexftpuADofuUsdLZToludhAbGHCtJnzQxVBzmctXBcArhZtkJAiVnQjJmSimwnZYncNRgMMHcdmjHAckHIVHgQaEdyaKxUstcBSlPD",
		@"JItteIlFCWMPcKvTmDHRZLKsRFkXAEreAsvwKVwdMGVNeZHwowfbwATbanWHGJaWAkUyiHxDryIKgAuhmJWGhProCvOkgdOVRONjAyX",
	];
	return CwLAYwumnttn;
}

+ (nonnull NSDictionary *)TMqrXchuinNMBBUthsB :(nonnull UIImage *)wMBZNENcHkt :(nonnull NSString *)NzmVxXGjWShcUAGs {
	NSDictionary *WPWYOFTUqIMKTlQGAo = @{
		@"sdoCIwJVcrGUy": @"wsEOKrtyCdmFejrWhOvtJzAkpPMrnnVkinCwnIhcWCOZFunyromlXRtUVNHohznLAgLWCbUQUQMvbZxEOqARELScpEpeynLRZcqSohAIQdnifCwUpsFrzkpwOAeB",
		@"LzVGBizgmYlQvHk": @"EzoGRpbfOfmMNoZEIzxsAOmoBiALLGOwXKHZIzGZvcgQcLJlWnIktPobdJSIddiAYKIoRnUKScCJSNFgVaUNJHXvOQUoBYqWVVTbaEgjqvtGlnfFFUWMpGx",
		@"uOljxsAJWpI": @"fLGdVHpcVZScxfCfAFijYTEbDXFHJVAKnLBYZoVxGdpwWJyieibztUfFmrQMZdmoohlcWrTDVJoJAmnxuDhlwYAYyRzHfoQOPGiWbCVbtY",
		@"BcZFcSbDPH": @"sKRgrItxXycmexeNrFcuNZpKbZZlMPWmJZWKVCwDNoTnfNQQWADesOFruBgDbFhinTFSgtvbOlZeJcECWSvZLddnemdlktvFvIEeUyGHJqVJZuXtmpnMduCgfbiwS",
		@"YkVcFFTzyQ": @"LWlGEYYPFGwiqIScLRxKQTbfAyqWcLhQTHKWlujmsAdMfEpXILAoCqqXVqNkhYuGyDkQuusxKtppaZSEsFToOSCcUxVimHdSlygKgjANlsLgLaiTzGWvajB",
		@"xFcKHnksyYWGZVBp": @"xLAOutkLImDjUajfzvvbqssLefFuiUhUbFZiLrIDlETwXLMJGMcyDfegTkWSQPHbCrpfWZYgSudzNURIMVsPzTSOnkcEhVeSyLexsdaiYrGZLheEpXfJWlHopS",
		@"BLWpvbMjEJnlgrwd": @"sLZBGXrsTBXQaIvaGyKTBuyvGDxEqwmholwpFsahHgWfVxpRJmfSUtQkKzocMPcoJzMoEQELgUHeWnjZhtCHGIDdaBXflNCritHPoCqKWzQJVOmQThTmOxBNriSYTfRNpLNXd",
		@"MIdxvLjBNm": @"DIOiONemUzMWRRzlejValvSPTMheVwHZCuKlhLxJHyHuuKnblUfCuuXHtVnZrplEBCwnMcljLvNBEcIILQQDBybQKVKjJUzGZZrPJDCBekDkxzaxAbDwnJIgNgXwyezSlvhMgMHoNqHy",
		@"xADrZYCIxjXngdBM": @"FEqHLitGGTRoeveBPXrFTCvmlEtkLTrWEuJzbJMwfaHRVhlZsNBkxGLtzVIrOavOwyUAhCkAokPTNeJcpvdaBCfvUhHPQjbZCXgHTPBABciwGbrtFrGmWfryEbrrlAfEWmFYsubNBBs",
		@"gxbBRjLpELmmYmMulXv": @"ifybWOBBJYeFqtZHTXWOabxEEeUqQsYRNIjbSXPWzwCYcXSTEurytuLoBdbNzvFLGWTTpEzYeAABVAXdolTMYEvUvUFfvlRqynLjE",
		@"bPqOMAIYHbAScPl": @"cqjjJNaUSvLtrjIVOzTtTubWyrkGHdERwuIovwCBLqNlqIaxhjQtRHWZTyGpiTNhcvIDqmnkXLSdFRjFrFjXPhimRIODiKzvsmrZoXEwJfBIzsVNdoMllBFWGEyzNFISCREayKNL",
		@"GJooMCZpbYFXryGgmBe": @"iHSJkdinIfGoMMJHFEdmrhfZfrxdjkpqLGyqMqeECAnaZAqvInGVzbofGpslJaqcanFCcfpnbdCFLFdFPgzjSPnwMwDXjqEjsuFdxQal",
		@"CUhOcMrJQwPCMvVCH": @"CezHtsFfduYUBpkhAneRxdtydZPOUyZMxTIVTjymZreXZvDEkeVZONwmVFFmyaBLOmAtEcgtrlklYvWjxlujXAvTJwuVXBhHvxXWELhveKuVoRdwwcYiINodwgLFZRyHMah",
		@"LcMVgEAYeS": @"RNwRbxHxCgrNxGPfyIeAKmyPWmVKxUdmYpIbJwZCHWdNEQoxnmcyvEJueUOvqUGxxSCCMNhoQyezgGwPiQTwzSDLaEATKOGsuhAXvzSDWNPulPQRPqsULybChtSTMWGoUQMaquupworGnQtKN",
		@"gGMAHnTUTARJxkigdwu": @"lLFDuabHsXglvHmZrpsTfAtNzDxLzoWCnNWgAlVBdYqGloPIoKiWyuIhiPoxstpERbwmkBmUgzyFGbEKneVUNWyslxEyFlcnBpKeArIBHvuIZMQOBbKEMglpqcRQGauCLWCPJqvMTIYQ",
	};
	return WPWYOFTUqIMKTlQGAo;
}

+ (nonnull UIImage *)OmoRhTQlRIxFpuAy :(nonnull NSString *)tOOqIbrxfLrzb :(nonnull NSData *)tWBVXpwskfTbEFHcjX {
	NSData *QSKlXPeQGpov = [@"kKjmbebSeeiPGSviKBkdeWEtAMTSxjtgWjLStiXiacOCTVcgnAtQAnQVZTpMCwzgLtjuKNaruJXEIaxJNnwpztpYKYzBABKgAzDJfYvsjqmnb" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *fNiYzgeWPxjnnYJron = [UIImage imageWithData:QSKlXPeQGpov];
	fNiYzgeWPxjnnYJron = [UIImage imageNamed:@"XNHlzMQiSvIPfqQojfwrDUeqJOKNeawIjWkgwudIXTVFvuQTdDCJrvjrxTiuVUCkEEqHPgerxRWNMnSMDgPwvcjCIvLuHVthnhlsNoheEwRFSiwKTJmlGQbCXuCbhPUai"];
	return fNiYzgeWPxjnnYJron;
}

+ (nonnull NSDictionary *)bIfXEcZaeBIaGRscxC :(nonnull UIImage *)WjovaBEZityEf {
	NSDictionary *JYyIhJQZTuOisyxhHx = @{
		@"erZOmEjvDAkUhdGz": @"kfSSeOWaXZnhoMcIEQMTacUWpmJpnXzvBGrDITuRHrtzLPhAPWnmGADxUvOmNlbbGhiAVlVIqmVnqsXfxuQHgYyxXwQSTBymjyYSFThqtmAibzIaEecSKHpz",
		@"waIkMTRkWyUO": @"VTiYiyYepyPNPKIluuTkmTemBVZGtKAJbosoAIWpIlwBohsPHpoTWDxTluCCFeyIQZTutipbwiJEDjdlwvqkgJiXyhpogLdNyRZOFvOrmGSlg",
		@"gQfwUuThXU": @"rMYyrDdxODtzBrNcsEpuFOzwFucMWLUhjtkVwfmEIgkqByckgwMjOFFCXKBvERXKicBVFRtdsbCvploisHyjZhUDJoQHuPHoRiLckigCADn",
		@"tGLWZLfRfnEueqQIIu": @"RSIbHteiwzNjYnPtPiFcGcyZjeQOGgosqPOQoefXWCmZtrQdxGIyYFEKYkykHJRxSOSPhFusrtJkqXqLdNxeAxTrRqbuWJWHaUhxyUVaOINmDwooF",
		@"LSFXPYvblBNWp": @"uoZhufICYllqkxMvTRKrhKxkEyTyZwayihgYuqjNPjzdSZbkfHNYbyUsVcgnxBYreAlWFOovoXUFjtnULxKyeClqxKKFeTesSIQnrJFurIVGgiTuBWPGSFxYiozQnhwmdODZCvaNHUCaFdkTHEIHL",
		@"oFmGrxjZAYFaeoleRYx": @"xxjRSVdcdesWhFTfMEEbAacYByZIDyUbXdvpcqgiQYsxVBGnKVsCCMmkBbikvcoGkDBkpAlWXsDGYOFZbEdGVOnDbhxavcZemAaCAEStpePrVglFBsbjmmQRZLaPiqT",
		@"IyKIhzHdqkvtLdK": @"smhoeUwYXCHSlMownDcmcfCQlqiizGRkeYsYrOlEvImqOTElFzCBgCwliOXPFBmmDQaPYSKjODSDvnDaXeqDKXIlAoWbgyrNBBuQQGAZhAWjJYNsXoftPCVKRdvOjdRgHXJiaosnAHwBXeg",
		@"zRCWywdOSOkY": @"BwejIPsxfDxwqWJxMbBrEPyCxSGYhflzDmccpGHnPNuJtFQWuMCEfYDlwoTNSYdOXXcHESDoAGgpPUTxGUDkfxvuyEiCDtAlREpoFktaH",
		@"xoWzoQnNfVwQKlvsm": @"mKTFBfjcBmkJTMMjvxCKCZqDstEArnNMXTCYmLzLHCweClKdioouCPEvIUySVGhKQnCuuflodmeyTTDJDziCJJmNihacIzYGEmpTHehpphanVZPYBSYsyD",
		@"FoMsXCGNbsKTRVO": @"gAnKwpIQUOsWaJLVOSnRKBPuwbPljEmrgvXrwqlTEuxEdLOFEdzrdlNWMEsYasBOJJokpYFlTzZIaSgSCoKxeiHyRhWoeCgtWVHBuPabIK",
		@"MawYrCHLiUns": @"MWIMxCqAkEgUnlYlcRVxStngITlxdsMNhKBcPOQkrZWizcfKrZDduNdKtVRZhdjGFPLfivIJamkJPLyXYngTGQDtJrbNGzjYJlUnKpDfP",
		@"BZCDRJlmKLThlKIN": @"qnpUpNPSonVZIxdZfwtAAvzqCauYydkxSDMbDOLKUeAjfxjtQYGgEleFSZKQrnejCGjomMntIXOrhijqOcebsvxACkOQQzfejFQTVSyLAvXJUUVaywXhnjpZRAbew",
		@"PrjMNmMvdKE": @"fUMsUVquoTdpmlAqoQUWnlXeGGOCOzawPlPETZizlNhBZroTFiyHuQEEdwVddmkzWanhMLJGyusBZacXnxXWaUTwTYEpgkbxHUhqkQTKJbEgJjfchHtp",
		@"RyxQXwoKUclEbJbTzGB": @"NNzEXbVEnCayNWkLRaZxBmXeXJkmFHgxvbSGHDPOfkxZHSJKwmdGdliVbNAxpvGRqkCReVAOWXtlGnaXSJgNhyknyozJtBgcYkFwuYoCsSBFgqZYPkalXPrKv",
	};
	return JYyIhJQZTuOisyxhHx;
}

+ (nonnull NSData *)PTkMPDyvwStwyNFa :(nonnull UIImage *)OnCfnwpvuOJEdanNv :(nonnull NSData *)MHKiIRieijttiO {
	NSData *XsLjbDONvNKMgbmn = [@"KhDioPHiqITBNHeyTOjKEaLfvAmUEgkyEuOBfFcxHoZeJQzukCfmZdMUuWdPlMeuZTKfWNBzknlikdXyarJQNhlmrpTDGdBouDOURhtnBukQRQMZgYqJVZcAVIHOawJCrfTNDkFTbdCvK" dataUsingEncoding:NSUTF8StringEncoding];
	return XsLjbDONvNKMgbmn;
}

+ (nonnull NSString *)ZNXefzHDZSRVos :(nonnull NSDictionary *)FNFwMssUIsdQ {
	NSString *HjdJTwTPrSVxmygVYr = @"xIZbYVtIyDkpNXtGEAdKXcJzAyqhSYEMAicbGZxkngcQbOhJZfHANReDKZZjCnAQGnbAvStoneseuHSbPgQLvGqjxqdWFFoLSVCEnIrGpOrjwyNskNjpvIrhvD";
	return HjdJTwTPrSVxmygVYr;
}

- (nonnull UIImage *)NKnVuleFmELSfBLJrk :(nonnull NSString *)OSPrqSKptdTdze {
	NSData *WUwSDUhobjQ = [@"nbITLQXUfODUdTqFniyCHFjzHFkAMBsNmwgKsxvmsOoCOIzVuKflCKTmryxFdsmppowRzAyGlTxgPJEwnIAkVuXosLflAayRyLENZiZtGznzgaiAeBajPBHbOmrMOUSAdBPVZbgvhBvloaOaJG" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *nKGLgNduVU = [UIImage imageWithData:WUwSDUhobjQ];
	nKGLgNduVU = [UIImage imageNamed:@"ZWrwyEIUeQSdQxYDMrGdxuuWPkkDgACsYwNxotvhZCDAljkuNXzEEMbjdlENyTnVtGKXTomgokysOgbNAyCpwDFBfimoZqSKjeETFWDGPqNxVzZapKhugpeFyfDQNkxBcuchDgqFNrvsdhqKYuLNQ"];
	return nKGLgNduVU;
}

- (nonnull NSArray *)JEgFgaqwlBSmHr :(nonnull NSData *)uKwPWMDAhLsiDXV :(nonnull UIImage *)ezhAHRDqldYDucqzc :(nonnull NSArray *)UEZJQZhBGqRceO {
	NSArray *wdBrVcLIPZEaee = @[
		@"JViKvvyiYeUdclOPdmzlFTTjCrbUlQObmIsohAXZyVgsBUUdbkIJNTBiULEGsiGhFeHTtrPulPTuXlgoHyFLzcsihntCnugGZGrhafC",
		@"gidLDrGAOqBPnjYlujKzzDpOMOxBPHOLKrSKyclnNjdmtzJRxwiiiuUQAmpxobfLedFuLDcUPpBxfHURfuAQCfGVPJSjyHNdPSRUHXbDIZfunEuYNPpAujqpivmjRWtasvmSrtpTIqkIDkcp",
		@"QBGeOoruYaMTvvBxGUJUNuXaTgWWJkqkUotLjZWzqhostHDdHsAlYZiXOsABywmrSbgyRqqWWgcckXrCppxLUrwykLptHIghaQACaCnwMXylxLfleGcYlIqRPrYPFsYjHNH",
		@"vfjWDgjWwUuVHSFRufqPMhBJZUOpNECHnxsSaiXIzPCajmtIifTqdHQocVVUstlKEjRZJyHsFnpGitujKKllpXGrfbCPpqFMJmQjVEu",
		@"qkoTZdgIFYRRPsnwDyevMnxRyTxTZbBzlkwvFhKNmgbRbJTCyMnCXjBpacYtuuRqawehkfbvEglqaZVZjmcQXHQAUdwiuTVLpaRqZUuOlcFxmOBznldp",
		@"DfijYDMBcZPXdcOIJhtkiWtfeCcOVePZODjHILXGERmoldMJmCLgHTPTWPCMjXjpHnWgDgvFDIFJezFTCDlDlOqbHkfKYRTkFfIaWQuKNtzjGBfpiTlWYUWOBOwCOdCdCozU",
		@"oXohZMlCQIzCgqGEgFRwPySZxhzafUWKUhwbjfIfxjHsRYujsiAztWkfunYXYyqxpQepqRvUXAEeVQmVuODKOztMzLIHaiLulKKQDcwHjUOPKYyv",
		@"GHsalCftEZHANyOgUzolvBJePCcajyDExvHVQcKkunSREisPRBwIZQzVFtgWVjpIrcTjHVhsiJdLzyBsKaBeSZORvfgCYSiFxhxQ",
		@"yBRHDFsLaqBcRWkvdSPymfKBazivOBbhNAuunFiHZgxARHutHmnDysozlZVlygqowfGMpDcJqpKqKrDUHfUUMXTvvWIjhgqFeXgNxqrHSZsPvRobPpSxNkEQiIoBnhzDGAAgVBxx",
		@"wnvQzcEgcnAkEpjshYPTbzvzUfNSSVmqxRbJVruOOqQprqiCPuJvAyHwfNkkzsMadlsOcotyCEdUwJjonSiwDceKtWmMTpJKGUxqpLgvEcVypBuIIKEmDJbICTiqFRukwLdsKrnjZqJkcFby",
		@"AuDusapkZjylgrIjqvqObilYajksuCncEIyxZKDvZeYvFbijZocHNvoxPleOjTOYoJIhHFOOySvdiYZPohJWmCeFeADzNKJEBsZVuQAZSJhYGtEuumQjJXNgVLtzOEfkWJFvgjIlMpkjU",
		@"nHmejWzAYjvUVwEJQyIUmUmUYiHKZhpvDeTxcaEkrMUsNvbGdtSPXdNAWoTAYZbZylWsfoLhHqKcTsXrrafEfjdOuHZKJzdpjXgDTOLjaLFqFrzmIXVrokcvqOrttx",
		@"cuTQqbfedRAtIkDdAAHHWEWdqSdlKFKXrWBRtlDfWbfOGhKwnzCMWZFwTnkczjtJVRYfkvTQYZkdKudxLomWyQMMUYKQIwNsPungSTumIQMnZxzzIeji",
		@"nNwvZsUPxhIgwcPwiLUsFRdVnklTszkqKzJiHGktcykbxsNMAtLOCHlLSndmtzYchKTBWzaaVBJuyJIccKGOKQyTURaflbQgUpyVUfbrV",
	];
	return wdBrVcLIPZEaee;
}

- (nonnull NSData *)wrimQpZTpRzrp :(nonnull NSDictionary *)YseiPWPUqMQO :(nonnull NSArray *)yjEwcmdHUhtBAVXoF {
	NSData *LUcpdTxvNzmJqgjLuip = [@"StiXHwRkMjWdhXQAbpdfMzqCcqYcfVGMIxpMdCXsRjlnFjotEBCPuMmqtBAOICpOTeiNoiXeAWbsgtzKzuQakntLqNVEBKGxwsLbImIDFQPXr" dataUsingEncoding:NSUTF8StringEncoding];
	return LUcpdTxvNzmJqgjLuip;
}

+ (nonnull NSString *)pcfeZbhofBbzb :(nonnull NSString *)rSBBmhkJZoJGXDJNV :(nonnull NSString *)FDXRGOSxzLwR {
	NSString *MLZUIkkewo = @"gwyEaecPpUZcuhjTBxCvwqsqZXAmPbuWdRJxHKMcldTQkmpVfytAsaVwMCJSyBxfwboiTFzVElfiPArXpNWysLHgmPKPGdfcsqsQQzPdAjIScBcPEUNVjWaGCfGZSabGLkGNFXy";
	return MLZUIkkewo;
}

+ (nonnull NSArray *)eKNEZqbUJRZQUUXT :(nonnull NSString *)eYukXwaAVS {
	NSArray *TGPXJNRmrIEhuuk = @[
		@"BYBchUrobNEqyTWWAjPxMWloukuRqReNxODOWxfpTLQCQCkAyDRTpGDLENXCCwSLfDTqIskKQIBGpVSXGiBgbbsJzOfhVWwrgIdhUiszFMtcPmlnuNnwniA",
		@"hDzZBKFCnOyBdFPEzhicUvOULnNBXjqkxMKHuOnGjsoWJMfyQkKIJmqfhxgcXCEzntsjoYkhYGPxaXBpaMeihoOeaLpxbrJPVlqwLGmRMYxiSfyizroPuWbbsAfUEpUqbiszDK",
		@"sLTYBJsHCiScJnWMdXIcnOkslkkdXGGEDwBRGRgtmdRqEkAdMPPbpmmnWDrVNobkrnimfrufqftNcvTjbMmivrpYgfarPwCOYTpbROmeTmRaeZfusEiM",
		@"pFAGBkzFdeSjkWNaOujbMEocddcnBghgrgDsvjGNmpMzLXFaalWjLYlsfWcSnlRipxTXYEnDTUbGYXbuLalLciZynRXNmQyqdLUOoZDSzUZwBcMuuvrBsBHSfXSJfCpvXLZMhoHLzOmArYM",
		@"wlIIiouDblYeoYURxTkIffwfdLgBzOowRmiRzYDoMXFrynjRpkFlEnyVRisjGeuzWswmZPMfERUPQLHTYVfVgjTszOOsxoZNSKCHfdSfrUkSScUrkCqTwWmsNughBrpOAJkPVbyLsJdGDciYJo",
		@"ErPwnRKwjtbbpTJdicTVenjYdzcknFBcpSJDirDHJAvdRUyORFeUISpUgqenpkvoWzvGRCaAkUCTFkcBgctlcFEabjzTKtHBuXZHIiZzbXWHimsFQIZkfGBemMyhV",
		@"ZeGuqApIJEEXLMuOozufhNJbMJEOMNQMMtMQHPXucNUeNIchTLLrFRmnaHPAkiRAnqVTCXALMtWEQLSZQbepLFaPtLtSAhrtRwxURKiJWFYrgvJIzXNqhmncppoMdRFYzfnWoaqICfwkKxJOPSWWT",
		@"dTOVQnAcEdkJWpPcVholXDsChSORqkRxLWMxTDVWRCgVLjOsEuEzIafxWQWAnAUfgHgNVrLlmdCNzYScktaJUVSjAdfLeawXlBWLUPKGznyCKVmqjLPWaKnnku",
		@"rzCHYRngfVuTMvoedGHqiWWKjOJuUeKLXXbKGafLdHnqBbxSmeXxyAxFiWeIajAVkQkYZcGNIvhkQigrbYileidpeIWcKNYsOGjBSkJREGIuGQoWrehcyVjjOdyTlPtRusdJYjaekPSvoOdDSaUw",
		@"atdcHADdJczrpcuYptvBCbaRLegQFyPDoXDVtkwgoLUfGtyNZZhFnYCAuOnHBIUgomnchFZQFBZeSAVzHqUCmKUOHWtIedZdkdntxQJEX",
		@"KIiHdWlcjkNaOnyZZPuPVLEfvxQhGyvxqgoEgVggkHupMIYbZxepueSaBFoqcDMxQlgtRrBSOUINjdFraYsBkFgzxfinvtkqQMXqtMMVFZRWdjrAKBjZeJnVux",
		@"STUPJhpDZbCBEXrAhRcnqArIpCSKLQbrPNZnCgnIMtENmGczjgADqKsLynPsKuwwWnttwjxqOQfHsepagYZEuFeMvxpZARoSKjrWTANylwwMvpOVRtoIjNLagZPmZviyELixDlsoUlUPFcOxNSJP",
		@"sTbyCYXkpJaICXotCXxXKFycYMmgnwLOfVxrrPeMzApNJtUvBHhQXaWGlkcJGIWuMBPElffmNysuKonZqnJmYfgibvqehjPdlFssvzpcemWKbDtmeJJbSwlBMNOHSEwQFwTZ",
	];
	return TGPXJNRmrIEhuuk;
}

- (nonnull NSData *)tPymyxhboFNdGAWGvkP :(nonnull NSDictionary *)VYhuEmKzQnJUoNmra :(nonnull NSArray *)EggcJluurJUdj {
	NSData *NTGmjkUBxlLVMIM = [@"KYxGpwunwYJfAtIKKauFJtQxpYbSicEXKfYpFBnSNakZhDSDBRdjZSAXafPbjSWgBkVUfPwdburTlfiTVykmtpoWHBlvhtNjOpfHxFTnbywWlIyS" dataUsingEncoding:NSUTF8StringEncoding];
	return NTGmjkUBxlLVMIM;
}

+ (nonnull NSDictionary *)tAqxlauCsqgrxmDaLc :(nonnull NSDictionary *)zQdkBaSTEt :(nonnull NSString *)bXmygoHJsZDCOK {
	NSDictionary *rFbqcERMkqj = @{
		@"NWTWYaAErSpwqQ": @"ARlNUJiHQhxxUZQfJNdcpavNMHxdfeLzGlUCCScEeIUneTzQWCdyGdCWygwzcUfzWPquFEyeWlnJkAdwrfrnchwdlCAIYLcdhsehWNAbTyUdRcYhvhvIljhYbaIEMETX",
		@"xvRyfVUSMx": @"wvBqSbvCYsXIzDfYepdcvFaxQIKRrYAvSoZhtTHYUhDfYkuWocYnVsMuKyhddUXCvdwBgLPmvnHmbgpFrNzEfGcwEVkHWycsZynyNgxARoIajAoPGYtPxrskRiyhMKZRsSWVYgfzg",
		@"RlxokLDlkCvYhTeTnsq": @"KbiuRhSejKBktkSwXgDujBvUGxECVEBtFRkVujLTJUoxCFrdwCkXShyyanZpUnSECUnJFgvqHAwbgcRhpYhEdomnlyKdsCDdevnILDLFZGsjJdbZtXneVIDiyEmGrlpKRxRUZZZBb",
		@"vJdetgRILGxk": @"HhwOUICwWkBWOHmjwvDxvHkgGmUHoYGJuFVPibzxklGqUnWWnaZOymIOaIVqFeafHNtaLBjKPdDJqylMyTNQULXmeLXNyknyAGfPnxNzYcvbyPtcKAsNTv",
		@"gGYrVNKpqOKCSu": @"OcMUSAFQiVqfLdlFFyhGpzqqPKmbCDlHwRvEGNRvJpzElkwWqNaDzGOJdrHhQGXFfwhaPuTYZSlZVEGGGmxyaeEjXMHCZTsIBEDbDHEvDekUHSWejfjgsiWiOqYLwQOH",
		@"tKTqoZxLTgKg": @"tFgMenXkZrQhAyLbIUDZpTxzZRaeHDabeLCMfGvxrOzsObBiPFhNZtBqiraJWSHjcKBurqXFiEwzvkdeUZmrYVbaJvDicPcGQkQYVXxvvlRMEwtKLtsCmFAohmzKYuJLmJYaCyIOLaFcc",
		@"oKxXIyTITIHJv": @"VcUWEIYlfKBqIsCuCnsXbthddaLlNHQrBHchrrdQVIsWYcEDoDaDLxBmzHZnsBsSKTtBZuasjZCrwWBhzIXpFMRhOZAJbpjSMpygMYRzqVWjwkcJNnt",
		@"IauWYpVFUbt": @"TfsJwHIkHUfrDjdffkhFoRruUKdtBFyzMrIQoEsJBGKasvpigVUatluGrnTTCNYCLYtmNUGEHYDYxKJUAycejGPSiZuAliAcfNLYWSTlRjVOrvhnyJlMMkkRKpNlkCzLnYKhWhPNIrUpM",
		@"pfDlfjxClITX": @"DXkKmPlSpqxJCLLESWSQkxDJbydUDQBiSHihzwnmyMHokpXzjlJJNVdfTCITqQsrMxjNuwCFRUczhkxaOVFDsRquRACXUXJlEtzDgbFYSTsgQuJzMQKRawshEoMoOZyaozq",
		@"qHGeDAQAAPvTlkbdyD": @"kcUIJKgUjkdXmeHAeRwPGNIInYWlBZEVYMiKIZTgJWmvZGVdRxSSUzgxjshOogZGnBAaKZgZWTOChLgSfpCpICHwejXzcVWfEYVOwnrZQfBNw",
		@"lCgfuITgnOkMZd": @"fJYrUMCwGipRJYtJzojUEJbRMWaxCEgoBQBeVzzwhsWacJANShvAoYVkDiBRVOLiIbXnZAdkFZeiTFYvyomBXsGKfEYwpCXMydZFfOqOPPyi",
		@"pOapFfWRJDHEedPdTbb": @"rwzAGkFgqhXHOElnvjJhmYKKjfrshPbFVGERdKZlhEaHIMrObaBVXZaTGEPQOAJkvoxiTkPFnhDZUVikXdOCnUJNgRCEwoEKpvdARjgMWaiXZYYItoBCmRGsbyhuDN",
		@"dkUJqMjTxCM": @"nrLFLlhKOGyeGWUhwuwXmEvuCNpEpzBUSkobcxAfaDdMvCugQAAUfqNRyWrQBXzCZHOlKLPPxysMykPzkuaQGrCTAKwRrghIbfAzEPLpMIOBbNMVveqPrQgNppQUtLVCE",
		@"NTVZysudOkZfnB": @"MqJjxABwfbBsZOYorlPbRsCjLWmpzHLsqUpiEfLlehBZkxOqyirUIJzAduavnsRKSpvTxZDcoAMwgatfFJJcadSVhuXzCHKBiimJHVtMCNHMYwQQvVYDIfHTWdv",
		@"bShXbxkfDWcE": @"tqNlIZhfOmeZJSoSppDWfcwIuPbnYhxZimBCOjasuYZiPDpMyLTaLHebhLYlRimcvKmOjWzUTJkrvqqheXCdxIEaBzSGWhqZQQIbZuxXHQlwLqlbmAnInxEt",
		@"CVkBKrfixcouFYlB": @"ZcSLkpsJXPdMMJsrqwhVUGEdEbKYdlFKVWrVJsvkBxjkSRdzwvvWsVstmgZMVlYDvbxTqqANRuESZdOlhLIExAeoXefqVuIJLWMOiTUegwFBEYuA",
		@"nBLYeoBenCcCWGdyb": @"VWALtTSvBKwePGUJSjTeRlSBzciaqMSlsTOyydFTWqlxqbMKjZtvNIDSxicYxiOIPAcNEAuNQQofmggffDyesLQeOrufEXKJbLvofCekMQSWzkGqJmOlaOZqe",
		@"ENXfLzNguquYFiUT": @"UNoOsDtNIKxiqRhzxERmJTRzoQCjWjlCYOmFNOAAPwajtlknFaSLHqXowHFuVcNfnokMplbvTvjpxLzAakLsgLGqTrpqxshpQGjTAuEUBBVjNeFsaIRVTueuXQGCnwesDhLekIrJrQvQqXTp",
	};
	return rFbqcERMkqj;
}

- (nonnull NSDictionary *)hlaVqfSfCTl :(nonnull NSString *)HZMbTngEBiHeHKD :(nonnull NSData *)TMoaenCiln {
	NSDictionary *GWMCptFQRVYpzAaBLG = @{
		@"PCPkyvtnMCjiaJcuY": @"SscwBhgknGTgNSabwNbvHuBRPsDyZShdIVdJrrSwQbVLMXTfxawOKFQiKXCBQgSsmxDXFjWdMcjpquIPNJbxVBNcKmiIRlXFdXBAmGJsipslQOOqolrWcAyJRpJcjthB",
		@"orkkrvshFqP": @"YRaxBxhObHLRmpdoqUGCtMZxLMTePYCVVjIaUGkLxXgQlqOQrUohSGFKAglIfQQfYsBLuDhrsXBQzczDijoSHwthJCEsPyvMCcUFmaeuBAhZDSr",
		@"anhaGYfPIIdUKiaodL": @"QQyTAXoEiUudULrqhoiGFDVcjaLTGtrurDQiuPKIDBULYRrXyAegVrbFQPbTcegbZnYxTLMPchjmxDhLNHNqCwWTCNdfsfuYlTDOoQ",
		@"HgUYVYVudWB": @"FHOkAOGfUCzgzJdVLFNXAhJykgnancsMpElvovTtlquGMZnAziEmquOwWiPRTwScCQxoDjvtQAjmrnszOVnigprGJKhPDOERvrIPRIGLrYSvsAiI",
		@"vtukRpjTMKZhganBded": @"KhdkhKiFUNcqjdyrcUKuQqRmTpQTFPGiggAGMOtpiHuYXghyHWJxARxKREtUhmNZjhULGnbxBuHwBYQrnwLiEGnhaTJZBoTmkQvlaIOTlDkwlpZStSUPXHGrvCQzW",
		@"GYxiANWhPCHNP": @"NOSHZUXFzcLNeEXjIGqptsphxsOmEhLvyLXQejhGjHrbJwxDkKfjWCYOjMgtWDMbHMtDGWgYDuJcYQyWJLBIgkMgRIlqVwHGSVynkBKgUAYgmEKGiLJWSaUTBHJekCIrsTjCjPiAg",
		@"wAcFWEEeVopdAaQb": @"DAkTFRFKdOUxVNkAKumBOxTMnESZHxeYzqbbCVhVBBvucxvHevTDkYoTAoRYXvbrxOFqnoUUZPLfDIXgImIJFvDtiSDuXXxHQsZbLeXYoSNWfVHCXzHf",
		@"dBpkPFSZEQTeByIPxV": @"lbWFjQZMRXrtJjjlVQrVuYuRVfSsKXeoUkXcdnPoPVpJxXuzjUlzUQzkBoqPbAisEKhtOATwjnvniqykqYiXXBxfpFNaGIwZGbtoxLqonxzFESlOdVYLpsBQwDSMWDLUuYLadogXGrOCmNw",
		@"LBEOfYAPFmw": @"mFAYAcjBaKLrxVizRGhxrUXXJilbmPvqVhJKUnihQMwzUtcbOHOZzTUHIgdutXbrlCBKdXSSiAqLmibbKWBRDClLiQuVOCWhhBEDlHanLuQBuNVh",
		@"OlHAKSsjgqokSaxf": @"UjwNMJRxosLVpTcDjZOeFCPkeEMkOUvBpUkMsLmWiSTCToXieaHAqyvwuNICPdkuYMzbSTmpckYmUandfNCYnHKvOyBBVYlFAEKoefbVBtnQDuBkqYbCwKHQItizMzlIlq",
		@"kZCeXPPaSbcJEbHR": @"JeAdfxCUaarLUyiPZYDsAHmnmEVFbLgsJDYlFGmVztIkIfKTEijsMchXojNMxzrJMwafXnwyxkzxFEYBMxhpDEcVTEBsGhgCVYBpubdSwoGCngpsJsLVztlRdPzkNiE",
		@"GVOxwYMYVVNATTPeNdH": @"vcFMrGkStsVgugGAgVRgwuMNaUXeSxLMIFEBtyneKWeOaePwXfoqdZTMwuQZgXuptYxvWhDjjOAdNpWtkwtxHZsRnCCYQzmbjUDy",
		@"pKdfHnYmFKwdTbFGbd": @"TMIPbnRnzFGsgCvmPRaiBhdVELTHESCuSuhaLFyBAVzsFVhJRvGpvwpgNJGQRrzSUsiqncmKBhUjPwDqKZedFJFbGLkjMlqvHRJUePApvQmPtzxYOGnj",
		@"nkDByunemVxqPoCdm": @"GTsMqVnXsHiRWhEBngoIbiOjEyhvcCzuQpXkypmqUhvYFOSkPyxHJDywgmRroqeYGZyHsgYlFlBbVgnyGvhSreJCwtagQXJiZvgzvXKvPQzqp",
		@"AxSxBiHRKTpgUQI": @"XAtJceRCEpQcDHWQyoAUWpfnnhOUPlPYMMSsWsZyWMkBgzfhuzSEjNoSXlLWeNjXzuONXuGeTzVFYhjTJdecubHrEVaRVuAbkITwmllfLLOOVXCckKaolXYqeNjkqRq",
		@"gRkyvDyOdzhvb": @"SPxAjSBccgsXeoJKuzAQibeNBIYmGIhOpnMxDCQEuKCehGJIbOqLEqzGaoFLmEFdHHGZfUpBVbdWeAqUIHPtgznCUyYLQVZJCPVUkUgCvpU",
	};
	return GWMCptFQRVYpzAaBLG;
}

- (nonnull UIImage *)eoBNLyMQLcEJMTFGWGe :(nonnull UIImage *)zWufrmSfXOPDaGBhV :(nonnull UIImage *)MrPdjKNDkM :(nonnull UIImage *)taGqAnvBuQMFUObUDif {
	NSData *WSJBlqplCRkxM = [@"BEuHXzRWAsWbowvprBxVFjmzmRgSEYhFEYwVkcuLHMEHmRcRhgTYOeqNLcMjsNubRFgjjxTrYriKeVcTLXXVDTwURyhMSbkzQEscmdbPKMoLldzcyQQRRLQFzJoEwyZiKseYQmZWNxYWiIC" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *GqPJEkNdFINeQXpWnR = [UIImage imageWithData:WSJBlqplCRkxM];
	GqPJEkNdFINeQXpWnR = [UIImage imageNamed:@"MccfWZNGRKZCjbFSXpuIMCYnQySIezIJKsYkVrjKBpjZzKSUAcmkottCMpHvksPAecNOsCJEULlSqJXFCrdJVoEXyfXdSKsQyCPMWPMGObyyZnrLzScJjJYfkNauCgucvbHxmdHlJVjHwJVfkN"];
	return GqPJEkNdFINeQXpWnR;
}

- (nonnull NSString *)zojdJpJonmI :(nonnull NSData *)OVcvjNpPArv :(nonnull NSString *)iMuSWZFNXGqW :(nonnull UIImage *)oEdfAZYPKlb {
	NSString *LLCyulNzVo = @"CyuAxvZpvDDEVrwyYXDRaCHcciDldXauZNyqHiOJvRyXsttIhdPMmXmNRbdbLRhfoijYDHmrarjyDkOgIAtXEQNKFoOIHCiZHzZsccZaVbPeJjpNsMMbxZ";
	return LLCyulNzVo;
}

- (nonnull UIImage *)IorEBXsabF :(nonnull UIImage *)rxaQMplRQS :(nonnull NSData *)OHOhbRJFvwU :(nonnull UIImage *)pEFraNvLStMUCMwc {
	NSData *wrYlKExZtLHY = [@"ocIfuweLDjzayofHXMbjFFUnMmrTSlvkavldoWbtMSxLZroLcrMdqwBogVdTlCWBCwLKDNEclKlxwmbKaYQPCdtNuWjEKvoTKDXDPJx" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *TGgNKHppOiR = [UIImage imageWithData:wrYlKExZtLHY];
	TGgNKHppOiR = [UIImage imageNamed:@"qxbgLFksUtMxggVasZHHJhbqldaZmAaGOBVAfwamymZgxKjDQgRiWegttCoOZFNPltYgguFgeRcMDtFPpRrWdDOtRFXNoFyAGBDAuLcFlyWzHg"];
	return TGgNKHppOiR;
}

- (nonnull NSArray *)rGCuLLLnjtzcfgDTC :(nonnull NSString *)hRsHUMUcItwJ :(nonnull NSString *)SPiJlUeIyM {
	NSArray *vouxyEmavRH = @[
		@"MJyflRTuXBdpxCNJigLVIOQMKIoIRfjfZYHiOciuFIruEJQucKLlDphZbBZOtzTYHigeyHMqTEVCCpqMAYMJerGGGaIhUqnppodfsYTOFGVKUthIEUbLhxiPhJXTEdBBHFqtAlbXtEYafwgY",
		@"xUsXkeOPgsytikgTbRkRCOxpKfVAdhpngucpdaStbpssPFzwqFryNcLlbVNzGArVXZclSohBoEBRbmvDXNlkwZPjOvQCaxcdecVGOjAVYcnzJaJNIsfstyNsjUwizSLAabnIlug",
		@"VkKfxfogfjiKHzAyAKeGiQoOAKYXyPAcIuzBJjDmqJgbrbBhtqSJFjIEGiohawmwxAvhaLPpVQcMgVcOPFKUDuWHbKOZavgUiQXaJVrYLaecBoYEe",
		@"KbkZrfoBNsYAxaTwMAoyifDKQPbEEXANHoVtlguuUhLPqJWbyKwJlWAIpDNnQhUIXwyetwWfExhGmqaEXpvBIJTJzXPHQnlodjbdumpgHmlIHYpnK",
		@"aikmavfVwkvdPeSchLELpNboClWCAERBPcEWvBlLfEnHrZWboaYfzaRhNyoEetAigjGqvpHnmjifRkKUznDdNCLmWzHtJyLULPemxGxXUEJBfQJVSnwjANKRfxuCexppn",
		@"InuhluywvIGsuhrPNUKSimENrKYIqSwcxtrlwZMPccTTraDnTvYtxxmohDbYvHtGtfaNOOeuEPDoBhIbeBfRJlQPBdgQGdgOpKLY",
		@"AiraoIlSVknZGANToSQkDkPmbqcgqZXczmFkkbVdccQkzbMZZyRRAWnOHYoDGDqVJTbUQGfvqBpVibvmedcrbzlFHqbqBaBxsZOcM",
		@"sHVZvugtkqEaAhRwNfbqRFlyLWPLsROgashRqZLgaUOqDkkpKjQjzEnHGUTEQpbfMfkvFwlKjFPfkjoPeIwNduZshDNosrFgQaewrBSQeRDuiuaBxPjSEmEdw",
		@"KoACCaiTiMzvlzxJzaylwzciMqIFmDqROFxxIxRYnxtolJmiOuBuGQskGyOfIuQePGXOaztdTLfoyGtfeUXLFNSmthubwbHTsqNAqfdKYtOJFKSumuHOIWBGJTLbsebYNLUwcefNTmKnqJfagaUdA",
		@"eWobkkOueSTnfWdNjvFLalcKufiBxswDYwFZnFnQPFfNVVxHvNxsbxuwFlSwdkuebPHMRqwBKrQcCGvrJzPoBKTLbYPsZxEDvnbby",
		@"giDSojcLCgRgkOdmZbGakrhhtuKYwFFiBGCWKkaemIiaJnsTLUsAyhjEsrIGtFdamWCkIyibFoqexggqDKoMyVJDfuDFAJILvxvEvgaICMLfqPR",
		@"yAwWczVEuAfnptaOKnGfbjkbsUnQaTbWIHXHeXoLoBregBQPxzssXOQgPmoVNryoPdjjTFVYCKwDWbWzJRemVCoHBmelNXYfPYaVYLmJsG",
		@"HWgvOIhkxbjVoNMTqIQHQMlWXKlhrcyuhxazACEHBlxbeVRgnwOHsvqYqJKcaCspEfecfxHfQffIbztaODhVCknZhQKXpynodgKnIfnqTVBBzYOyTYYLAxaoaLNJhaaZa",
		@"dMyxWUVyXKioxYrWnMeKfNQiWXmkxeLhKcAMiTjNkBvKtxIBGUTAHoWFjQlpdudojBfBjSXuIfUixSyFJwJlNPPAuclGcQoAAKHLnnClUiLhXCsxFVqQXLAfVonnKcJS",
	];
	return vouxyEmavRH;
}

- (nonnull UIImage *)BRrJDqRHEdnepizBAVo :(nonnull UIImage *)YZgPQlEXxBnKno :(nonnull NSString *)TWNOIQTRPtVzy {
	NSData *RVIWzhflww = [@"SBgjLyiXaujeNUHDygFvBqybzlRWqlWNZCtTVgpFLmvTBEEcSRzCusWjaKgOGYDJEUAAOTyPkvDVCJZPItJFrXSZFlhDtkBAaNhNVdSSbrCPSLCthdpdAWAtylyIefKZSgyTROeyzCgJsWIdxOJV" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *NMPuchUicWKBwpEQF = [UIImage imageWithData:RVIWzhflww];
	NMPuchUicWKBwpEQF = [UIImage imageNamed:@"QrmVzgmiyqEZyUVedEXFskXXFqaeeqlxtvdePUOfSMMJbjBHRHQIxHdZpbsYQVvIiXLqjSzshpouFaMzJWwTJfoqAkSIXttirHhskgwXZJrMwvNVKxPIaroetIrnLBevyBoMwKsGKefrdcxsqXAIq"];
	return NMPuchUicWKBwpEQF;
}

- (nonnull NSDictionary *)wdpNnowpQKVizTPwtTe :(nonnull UIImage *)JAHgeAGjAafYD :(nonnull NSString *)blqxAtFojdGMrMqfnFO {
	NSDictionary *pWcLHSdGJhoBBSPFY = @{
		@"HmvuIoAzipWOr": @"gdBphUGvDVPRBlOZygHKtclnyZmPjnbXWWFtybLgCNImwvdVPOUHYQsrHSGEkSUebQxtSNLbJeeVsRTqliCUJoQJmdMWyhbvTYiPkArVJkfXCrzNHDkgcAPorqjmaNPWlaRyLZDGhlyoNBfzajW",
		@"IMdvcYnzGhgXSEm": @"UfECvIgfeeITKfdhkaCeztBzMHICmOoLCdebsHFPnGDbCclStnoexgDnZTtOaOoKLbgGWPkFpeqCpyEaiMOXfaOQmUmmnRqyvEWQWiQUKRYTtLKaRthpHARhbsVtKOsczVINr",
		@"RgeGkBvnLNYESQ": @"aRquNdgRJHZfvytnLcjvqKINoeejSXiWtFctPOZuoxHCpQoHeuPvDxZDqRayVsltqNHqFqNXPJJzPTyXewMCTokVxGfBstuyaTdkWxwhVficQyqq",
		@"QgFkjInIcJ": @"HDfjdyOyGMOtdASymdyXnJktAzsFdZCRBDwUIuBqKJouJNPLAzzRXwSTLvwGXlqiiWJOSrjWjBBolKuuoOghXtcMuvXUUiveoYcbfTXcNdvlZKlqHBlgPPhkLwtzHtS",
		@"uIfgPNRbSaMrTUx": @"uFOgRwpVjSzNoPvdTyusPPbOuWMrJkLduAeUbGBvekpQtIBLJtIlOAsWxKxqGYZZJztbRcajOwGjSoJSomFxptpPfBRjyqeLYOCHOvqbeBVfuUqzNiaZ",
		@"dLWGsLBzLBZip": @"QGlCqzmHTgttBHHlXPFaCSgOlZUUUXFZxILgarlZVUjmZZJGUxMMpheRLhLHUQnTAkVHrUCqLZGrgPRaHHiniQbkUVGIrKLZtTsboacWRHbc",
		@"GYAupplrCYqHXICv": @"bRgibIBuUaxWRukYePtQspMEnSpdULGRiUdCASqMERttGizfQywokDMgyHMJHXeZPcpnocDduqldiicXRDGokCiTPckpyEGuuljKRNgjJLWsrlWNXWGCsBUsWxwiqWoFdGv",
		@"QMbVAICVDgOxGOtnbb": @"iYJjarodGhjUpbwKQfykzqOzCTpjHkZbexmNGIpTvmrPtVqLhirBMWFdhZjybPNUTVGldmUqqGipLWVWzvtlxawcHmZTnRJpoPgHSWIoMYQGnxWcMHXKgIWDjnLeNxTdTaDPDod",
		@"PmTfplcyGzbgGhI": @"nCwGNFMUBkmnrQlVbJkcnUtnmipzhYuqOYtqKxBxLaLTxYShLCxZlZihzmWFkjHoQTVzJHEaUNMTGKRuhkkQENdtMltsHUiqxauozTTCXJGHwqvhpErAxG",
		@"WtBHrGeXCNP": @"fjNrVdyLoCsltzVXvucmfFLQsSXyIeijAYjEJCCOENdGclNoGAYZLlRPaoRvsdpkqAslhnTvJIRWGBvHakopaZkYFmFQolfSFvnr",
		@"ReXMvltvFmzt": @"IbULqSHdKaSBoNUulWMKLgHCPwNzqoqOZqRLQapIeRNFmFxTpyDHWHgTqIlbpfFToBojElepRmInkBuqfMxytIvPTvyGMbGTbgUjnytCoQepxCQtTpLUcQLztTPGwOMVkVKpAmOhQthOq",
		@"dMTVMOyEYx": @"vkeJIzltxfnRBrMwPqtsxemdSPzFtvzKiXyQqZSPFCzujzIrCirjlzuXXmYONstARGIfUFiiOawsXQZciutgLFOiHMHhQiJkdAXKJZtJReEkY",
		@"GpaFgljgXlcdWOz": @"pXRBPEyURepgzUZEUnCTzWyEZjarnDsfOUmRMsSvaGbQCZmCNVRVdmIgnEepTfQKYnuYKHVTyaBeXHzRyBPeTlUVWMoFUJDaVXNJwfNiChrONjC",
		@"ZhmbwDFaFwWJvL": @"qNnttrdCqaAWRfcEQEfYxgjLoarzPEJNBFXHWmNzWSzssQJUFIFGBlLpruQdvpuZVfROeSECEoCVdjTmRuCizqHzcgKhpjlXXxwCqPXLG",
	};
	return pWcLHSdGJhoBBSPFY;
}

- (void) setUpUI
{
    
    UIView *contentView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 180, 180)];
    contentView.centerX = self.view.width * 0.5;
    contentView.centerY = self.view.height * 0.5 - 64;
    [self.view addSubview:contentView];
    
    NSString *likeUrl = [NSString stringWithFormat:@"%@%@",NetHeader,TeacherStatus];
    
    NSDictionary *dic = @{@"userid":[UserInfoTool getUserInfo].ID,@"token" : [UserInfoTool getUserInfo].token};

    [[AFNetWW sharedAFNetWorking] AFWithPostORGet:@"post" withURLStr:likeUrl WithParameters:dic success:^(id responseDic)
     {
         if ([responseDic[@"rescode"] intValue] == 10000) {
             
//            0未申请 1 正常 2审批申请 3禁用讲师 4未通过
             int teacher = [responseDic[@"data"][@"teacher"] intValue];
             
             if (teacher == 0 || teacher == 4) {
                 UIImageView *teacherImage = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, 120, 80)];
                 teacherImage.image = [UIImage imageNamed:@"jiangshi"];
                 teacherImage.centerX = contentView.width * 0.5;
                 [contentView addSubview:teacherImage];
                 
                 UILabel *teacherLabel = [[UILabel alloc] initWithFrame:CGRectMake(0, CGRectGetMaxY(teacherImage.frame) + 5, self.view.width, 20)];
                 teacherLabel.centerX = contentView.width * 0.5;
                 teacherLabel.font = [UIFont systemFontOfSize:ys_28];
                 teacherLabel.text = @"您还不是讲师，赶快去申请吧";
                 teacherLabel.textColor = AuxiliaryColor;
                 teacherLabel.textAlignment = NSTextAlignmentCenter;
                 [contentView addSubview:teacherLabel];
                 
                 UIButton * blankButton = [[UIButton alloc] initWithFrame:CGRectMake(0, contentView.height - 40, contentView.width, 40)];
                 blankButton.centerX = contentView.width * 0.5;
                 blankButton.backgroundColor = MainColor;
                 blankButton.titleLabel.textAlignment = NSTextAlignmentCenter;
                 [blankButton setTitle:@"申请讲师" forState:UIControlStateNormal];
                 [blankButton setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
                 blankButton.titleLabel.font = [UIFont systemFontOfSize:ys_28];
                 blankButton.layer.cornerRadius = fillet;
                 blankButton.layer.masksToBounds = YES;
                 [blankButton addTarget:self action:@selector(applyTeacher) forControlEvents:UIControlEventTouchUpInside];
                 [contentView addSubview:blankButton];
             }else if(teacher == 2 || teacher == 3)
             {
                 UIImageView *teacherImage = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, 120, 80)];
                 teacherImage.image = [UIImage imageNamed:@"jiangshi_audit"];
                 teacherImage.centerX = contentView.width * 0.5;
                 [contentView addSubview:teacherImage];
                 
                 UILabel *teacherLabel = [[UILabel alloc] initWithFrame:CGRectMake(0, CGRectGetMaxY(teacherImage.frame) + 5, contentView.width, 20)];
                 teacherLabel.font = [UIFont systemFontOfSize:ys_28];
                 teacherLabel.text = @"您的申请，正在审批中~";
                 teacherLabel.textColor = AuxiliaryColor;
                 teacherLabel.textAlignment = NSTextAlignmentCenter;
                 [contentView addSubview:teacherLabel];
             }else if(teacher == 1)
             {
                 
                 NewTeacherController *newTeacherVc = [[NewTeacherController alloc] init];
                 newTeacherVc.teacherid = [UserInfoTool getUserInfo].ID;
                 newTeacherVc.nickname = [UserInfoTool getUserInfo].username;
                 newTeacherVc.userid = [UserInfoTool getUserInfo].ID;
                 [self.navigationController pushViewController:newTeacherVc animated:YES];
             }
         }
         
     }fail:^(NSError *error) {
         
     }];
}

- (void) applyTeacher
{

    ApplyTeacherController *teacherVc = [[ApplyTeacherController alloc] init];
    [self.navigationController pushViewController:teacherVc animated:YES];
}

- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    
    [self.navigationController setNavigationBarHidden:NO animated:NO];
    self.navigationController.navigationBar.translucent = NO;
}

@end
