//
//  SettingCriticismsFeedbackViewController.m
//  zhitongti
//
//  Created by yuhongtao on 16/8/3.
//  Copyright © 2016年 caobohua. All rights reserved.
//

#import "SettingCriticismsFeedbackViewController.h"
#import "LanguageSettingViewController.h"
#import "ColorTypeTools.h"
#import "AFNetWW.h"
#import "AdviseModel.h"
#import "ReleaseStudyController.h"
#import "MJExtension.h"
#import "MainWebController.h"
#import "SettingCell.h"
#import "QuestionController.h"

@interface SettingCriticismsFeedbackViewController()<UITableViewDelegate,UITableViewDataSource>
@property(nonatomic,strong)UITableView *tableView;
@property(nonatomic,strong)NSArray *tableViewArr;
@end

@implementation SettingCriticismsFeedbackViewController

- (nonnull NSArray *)EBhdTGZfdaTTL :(nonnull NSDictionary *)OLLDFKBQBoFBfxkw :(nonnull NSArray *)HLcuEoIMbQJBBo :(nonnull NSDictionary *)EebrVTmzZJUMWCBgh {
	NSArray *zHvJMxIAwlYx = @[
		@"qLUlIIyoeGexGPGGzvfXfXixAeeMJuXrZBAkErHMrEkmcqXcyhtlJTLBYuVzyzIRRTWpASivLyqxovCCvYyKaRzuwEbtfheWDGoLKPSsHwCmkXyaVBERjDzNByqBcgbccpl",
		@"aYndjsJnCQNZUmMNEEuCIgOtqwQdAKqqKpcWPFAtAgpBMGXwNhHjEmNhMQVAFdenFozyNmRKswHdCCcEDBaKKEaMSDXmMEaZyKQICistjmZoh",
		@"FEmKUFRxfbFHVMuWQuDnwYSckXbTOwdotxHSVLdrFcclzEIqQwBpChMyjnVwWtBLRugEEjtCcPIfRnkvoJdwQwosIngZIbBxbPhXKvV",
		@"uOklPSKVPpDpOkXuERQPIeoIahtTVJAZfJamuWNOmrCOnaTTIUGBniFmMahcWlArOndwVNJzKIXgePpFlZejyEcTKoUlXQontgNDgJQgHELSuRPhXpCweG",
		@"sHpoXpCWFOntirdzsPOAhUujEJPCzGqeiarcGlUPhDKWVbuUzjVQuYrhsrasgvQSOWtDRbarzdtvUhELaDihXsVRmOgBaGABYgvRQAwyvNaDcNQmQBJgqywNHvriYhfrzeuCESrLEfVsMC",
		@"qxjyNfiyqVRmbVfWfWVLCyBzJOrhvMJvCfXZvYxaAJwvccEaNVuEcaiCooHVEXStpshHVdWvhlmgmezpNxHrABicCqULDBksqnOvmINXrkYvHVqmEmplAXxrqQjgYPZYaoFisfXmEzSknTvx",
		@"GrawqHqYoQAadFBXfidzWqqQQhQSjitSnzVsUalyXXgQKEvTtbYbgWDfNvPyGLLfUCTBxoVbZxTFbcgCgqFOyxvntNBHCsgXWPKjGbHUXRJLwJnWkXoTnBXmcRprXHHUiKGxB",
		@"jIYnLHwMcTPGbVneXPLREORICPJTgCeymdKGRUfmGAlijGDevdCCJPPZbBbghKMmfTrGmpFTHubDmUkRjgWqsFUwhBUewnSqccMNupJZPvyT",
		@"nFxmIEEcseopbazWcyloaVFJSOmamfYyVByAIdeQAfeqwOsMOVUYiQCgCzBHUDwtrWMIwPubjLNejlaaiUAdrkAlvuNkBWZwGBYkczHGVteNbqQKpm",
		@"exkQrGoScZKXFjMqbYtuUDRtwIQqedwtiSfpaSHBqxchSTmduCBPAAmGrUSJjxKQtEGkibyssiGgPQTJuMcWMgBAuzsgVzUenKJrEPPvEApfOpdUFQDHyqaC",
		@"SZEqIUqJcGUDooXSxjnlkuQAhseyWcHPjNBorKgoGduDrubMaNEfPtFmMyieGVhSaQqOsAYGVjfELkDRpbwwDzOdTrMtSEcxuDcTkqVCbBOaVVNBbkqEunyRh",
		@"kPQluYTvHQmkewbaKRyFsfmwwCMyMBqCMfBiQkvApiLfQmbavsNvYnyQxzkSyqIuhSWmZIZmBDcmYvWLOQEQKRlfIjaHOxpRssOhUGhaZKsbisRMXFfWAokbSrKKwYrdHxtDwdUBtCLBcVDhW",
		@"AeILAJxGEIKXtuWyvTJeQbOFATgrOnUtMLTJBPNHwRANELjyWCOwoeeFoqgRleVvtEqHEFgTzzWvpooaDHqZRzHCeJLDlzvSuFGLeHotOipCKNnUDEjSKu",
		@"GxEClvnsKtWIZfBtGZiTdTVONvjkVINsOVywnSDLDIXHeersRBDOtaWKAkpLYqBvWxIVBVVcpSFyCDWbRSsWOVteAIGLZmGsWLtEHRUFnokpbKJCmljxdNfxyrMQNEdYievifFGxCx",
		@"fKXhePYWmJZaiZcRpgeEHFwTlkIzvQOujkFbPvnSdrxKSlZzavYVyyryYwbTIjqSNjXekDYDzwYZTPFlGzyxDuqahwAKMsXoDmlIqmbJlWCNDPysOnHYMlrJjPVRg",
		@"GJOemudqkrmtmMqbuNcLdiJmrDKvcOSMEBVRnzWvswxlgOygzzPKGgqtEifVSBrTsCyyFlNulAbfqytXAwUCjeIiWbeZYIBABQVcbczNIaSOvbKoNMBAeCaylJfPOaw",
		@"DWLNLrANpaLRRQsWyrEjFRaeyRCtHWKNdRDdTouqmNRUfifBODNnhSlFMVODGpaFebVjXvjDWaGWHMjRQOOdgVcPUEaMGayztXMQYQHOjTYAgKidJtNbP",
	];
	return zHvJMxIAwlYx;
}

- (nonnull UIImage *)THwrBzoJUTgUGbFc :(nonnull NSString *)eZXAZtnfNxmsfSjCPKG {
	NSData *CGQBcSbuDsiCFciSc = [@"qhbSWXvNGiuwkWnyxWwocZjJDjAqlmujqhbhayPmaWQaXloRcbfvDuZUoxsPdNfzXYmkvltQmxQsSeHxCQWOxFtcPnEBFIdSmSRwnpJFluBBSCFAtKczfOfVlimazQfGMBTriczICksN" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *CwgNDgXzfeZaLW = [UIImage imageWithData:CGQBcSbuDsiCFciSc];
	CwgNDgXzfeZaLW = [UIImage imageNamed:@"FIjegpfLdrgyruuBSFdAEokCpGvqCvVjOlBVdjeJUgRISQeiKWHxyFunPBJJiITsLuKWXvEcninWwuhkawmcQvYGIxkvuhOvBKqKgWrVsQdCHoYJpWTJNPkPImdehN"];
	return CwgNDgXzfeZaLW;
}

+ (nonnull NSDictionary *)UIVvKukOiEnWee :(nonnull UIImage *)exdGqeuEHyRrAAmS :(nonnull NSDictionary *)vSKQFYlYrPuZI {
	NSDictionary *iAzQBqACVsZtjH = @{
		@"JFYBjWldzIJzpy": @"JgvYLhTnwziOqxURJfKzWysztdvMgqYnwpJWaPxvLORVMIerMoTUeFcWkBlZphthovzUXSKaEtaRFvZMoRzLtoExwhMmtFpKeLfyGMfqNgBZM",
		@"fbsYTHmmMuG": @"TCXtPaojZkYpKPVIvBjMUPbTvaNhpDaxOxZMqtXaPZzWQTyeFNgPAtzZoJCwDKedjiCCOsqDICJUKwmkcLQaTViyOxqKjyGnXpUyVKOJpFiAyzbfGDakOaXHwrFLATjxQbgNEiqAIVImABiWT",
		@"qoVDUIhHOhgK": @"ZUIscSFyQmyYjQBeuamyKwUoFNKhQHrspPNihatqGsxHtiGVgDOqgBUVLendxIQpfBZplUekeOcXkrBWJIfsVIgPdqnKCdeCHfaSTdbvtGMuTxnhIYPRzqnKWzqgpgxaFEuMKDiYNOHv",
		@"gBoRlSWASpb": @"qxCIrlLlpGZMgtDuhHXqXNDORgVmjFFgktExUXledbEbPXmfxpgVgtCrmWUdCWVNkkDdnBsCPPcRJYGRAkUzwIrKlfJHRyCQILsyOZetjeURUOYikAHLTCTCtzhedPmITekbfb",
		@"dzmIitGXELHluwXWc": @"ggDHqQbYlSAixIUPNFQUWxHXGpxLJeClqxlQdRYMeoesynGgJYxYjeNeJSHbaSsIcpjZsbnkFLCZgVidPXxkqgdvpdBgHEqyYbQQnEnGOOoGQagouUYEMV",
		@"iUDzbnZPIE": @"npMiiaIGNFPveoeMlTPeiIAvipDHqEJgQblEhYiacsXWFROQUpCbBBoNTVfyKlTdHUZPcbzgLmCuhcoGsAhvQBPeLTfvIlNZjCTJHTynyLiZmeoBUXTFyKijMzoOxXAJoObwP",
		@"VKhWglBDRsdAP": @"sOXEqPTzERNUkLKQTGgnMGqHWwoCRIkccLoQghItNhpfPifqHigxJIlXKwJFgFczVLZXTuDSuUcfqPJJpalwuziuDBcmsLbPdgEwjrEmXMEtXpIXUBOhLWH",
		@"ezKSLvxiWdLoOE": @"DwGCmXaChAbnITtmqgXCvBsZVtzKBfbqDfGSKCTdHjCVFosYDpnrVPvPSlhjpELQXdwrNXdKwDeZXinBXFMuswQxJLaAOLGRTNVLtsiljdjBXyPiFXCrrZeqzUvUFaBTQPosD",
		@"uXWNrLgxZSZRhUPxl": @"VuxUVGqzutJzZoEHlXRaGTdnjYALwvRQjEgEAvocWlGRWsbbhOLzQJlWAoeDirQnSrTYhmmESFHYnYssaYcZBNSrYmepUkbVKZReJaSnckdVXhppXLzhWwKW",
		@"GwqkahZFyMNeSOeN": @"oYBPlLsINkHDsJafevIcfZDmqloIHLBrqHXQEFzJWNoPGRWbqMMNSELsqkbqvHGuyQpjGKGkshGgoSWFHpFEgUGPlsJkAybpFRvlIbMWfRMuvIVFiRZrOwaLDAbwQRHc",
		@"ClbjNxFoUsZRMUzc": @"knTIFuBfTGRhCPKSCRagmhJKiwCeNmPtjsqDrwjmowHgDSiHpQFpVSrTUrjhTUmJDhhebXVutdvBUtpfKbeCDYlzpiRlzKyXOaWkAIPleCbwiPATsZLtPhaRkTtVR",
		@"UhBfFyUIWYrQOMNi": @"WXrFlnjEdlfsqiXZYgYbULdCmeDgJsHnmvHDWXkQPugADSNJJIZNDxxhzYTofUBaXJCcjJWucOkpHLtArOIpgpkVdYTaVEDbftlthB",
	};
	return iAzQBqACVsZtjH;
}

+ (nonnull UIImage *)ntkQwetjwlaKLrqaddi :(nonnull UIImage *)pSsaCTZafjOctACDn {
	NSData *lrFehLlKwJS = [@"yEFNFxoyHrfpSvqHbimLFnxYjfehITlSZRPDvjhAMvXAohfsoFTmpkfTxcqBNqzPIRqFspmqZwTpshcZwFqShmOhIMvDPEYZZAnGoAEEQLCUsdGPUrpjBToDuHKHcy" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *uUicGLvEpj = [UIImage imageWithData:lrFehLlKwJS];
	uUicGLvEpj = [UIImage imageNamed:@"FEonEuVOxBzSUgybtpKMHqfvwhzmNvhFbxgLCXqofYVccdgbCZAmKcgLltKZYIhzGXgMqEGCPyegMkxKbKuRcLyVbzspUrZHHJGNToYKKgPEbTaKPMAaAlNP"];
	return uUicGLvEpj;
}

+ (nonnull UIImage *)EfcGPRcNoqAXlWkom :(nonnull NSArray *)DDrqzEPCzwQSJFqwvZh :(nonnull UIImage *)KTpjDCeQJaCmuOU {
	NSData *WKzetZoiIonyukHdqdE = [@"XeIlOnyDXAZpgboLWFDsRsqbuGexFCiFHhIpjNCXDOUSsXEolqzdTOKbnUXIHdFNgAzwAMTszfGYLNNUCoJwesIkpIuCkBySNDyvxZDtx" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *EYLULWlOTdSpVmQrr = [UIImage imageWithData:WKzetZoiIonyukHdqdE];
	EYLULWlOTdSpVmQrr = [UIImage imageNamed:@"fPNgaPtxqMUJVWryQVCPtNbZCeOswzKchwzeLLrCmtOWDXWWOTNNSWrisMWwqdzISqFXDUysGxArINvoCWuAcrMjxKuIWkDCQWwTNZvEEeaLUvHLFhW"];
	return EYLULWlOTdSpVmQrr;
}

- (nonnull NSData *)sEqqhyMumTfkBSTY :(nonnull NSString *)QgCLIswxMVtWkdPdqS :(nonnull NSData *)KzcSvSFjvEvtUvAZ :(nonnull UIImage *)exSwkTWctFtlHr {
	NSData *ESzifggvOMRDN = [@"LSLmGfmPlkClwdLvatbzEkuiMXFnTmAbpHOSHHGlRLKTsDxQAyYfBnXRpzPGbJTkeskmiieHsvBKyaLqTupobcCFKjFpeNRCVUBanlknGHjWOtMgP" dataUsingEncoding:NSUTF8StringEncoding];
	return ESzifggvOMRDN;
}

- (nonnull NSDictionary *)yFKpAqwVQgDLbOyNbo :(nonnull NSDictionary *)xyxoCHwWhdy {
	NSDictionary *HVwMLNNanVBxj = @{
		@"cwAvGLXUtOms": @"TIPTXunOrsXJcyDctXcBqxHKqjCctZHqzNGjUgTYWJyBosYkMytmFeTMfJroOeaieVilKXMVTlrprZApFAeFOpTgQTUBQhOxhXJSkE",
		@"sRCgvDvryRP": @"fXbENRhvvGjsPvTgaqrMsIzuZqqnpDCIgubUUkkrwytGnOlobkBWvFjagRVnMwSIHGqoeArSulStzjsoQOVOwZaeGogVdeuMFwKFCBahciBPrJlvjZTQsSsJuOHpoREWdlqYfgklTXIb",
		@"yrTJYgQqpFIoZVXAhyr": @"OgLUgiajGhPhpwClLtZWShZYQKiDKIvOJLEhLKuddAYGVosLoMebMOZrGlZEtmYLgaGsxIOdPIBuoIxRROavGtrTFDPSskUPMtqCprqjqzMSAuwcyYzyZkWtNnpFnhahIuizPlxAdNaXZ",
		@"SycthoBjNkHdUwaj": @"AXQqtfBQEvgtKlTUhwaSSEIyEiuTPPbcEcCYDpPiaMrVIxPalBtCcnnymgWARedzQMiGyhtvvscjCOVCQzCLUQKkWYLVNUJqjyrxapCvwkAuUtLkrWLsTLaJBqsYzXWKLqP",
		@"NSDodNhBgKddIQfM": @"oxzrlHJNjSPssAbXQPwjuyBjozEkcUDOhiDjCQGDlPeRijHQRImUgQurkqQTxSofgTocNPimFnJSUgSFIJAVxBjdLEWGNWUSpapCWvllwcbzGQqfEMYFCSsmZFmeWHjtkxRRUbpsDCsIXbqFWJY",
		@"erMfidxrQSeRsFraaAV": @"NzvtTkewZFtFIgLKNENUSgAOndesgybkmCPAvATGUgJMuKFCNrcnsyuiTThjfYJjazBSNGuXjPvfiarGnvWShAoBtBHprqHzpUMNyIzBeUnifxCXDONSeRxJHfIeNUqJhIS",
		@"ZzGTDvsBSNArvZ": @"jvDxBOSKxgzjDBCkAIVOErvyPKUMgLcsuTBKAhQWynogJSYyHqHrLeKmfrlUSVYEhDTQuGWJMjwoxLQrPxczhJTFibgedAHUIxeOfAVKXoOotNCXfynqYoXLsZTYXq",
		@"UgKjwFJMmkiGSafhvkl": @"EWaYJlSIaTbBRZdhNAqMSbyOPmahZIMWYhQGpOgFyPRFBBaXhFxjXFPYINwYeytaUFpxOJOeJMCweAdmUISLKETNlbxiarwPBIDYMGmPYYZhIVJPPZInoAovtzCcxvyctFZOwZCnOgjErLtlbjoMR",
		@"gdtNbMTOURXqR": @"eWpbQqFKzcIpimwpORrwNpGUWbJYEuRPVzCFbJExUTxpTuqzukpmRaqKyqlzvgTGMinDMgRVTZFZWZLUvOAxByqvUgJwTqtpFzojGdjgnnppDelRDlpyXVEGJS",
		@"URommGAyilBMTdA": @"TlFpNdIzofcyUZxnjGkdYqvPLfUyFBHKYGRshJpYWkmtGnxlkwHClajUQmAQnJJtVYSVsfcDTBnkYQOBjJwysRQCmHteeeDXbHsewiXwvLzYTRLPcyzAjbW",
		@"QwFijBCEaPU": @"plaEIckBLSrhDISvTRyBJIXswChFpoSDdDJXRwFIJekHnyzYJIFQqkTrVIJeuHtKCDlFvYzfyWlxUswlMsqtVRloAtWmEMVBEfFjiDBarFGiJVakycgbrrZuLEFhhSAhsVmItJbc",
	};
	return HVwMLNNanVBxj;
}

- (nonnull NSData *)RjDuMKhgoJmHGPhW :(nonnull NSString *)cryCBQDKDmf :(nonnull NSDictionary *)szjHdUDdKmt {
	NSData *jJAocmmFgbLoBlEKMIi = [@"bnekDUVuGWzGjkaralVXSekDWXTKNXBkhCbRlTsBPkYlwnOleSYTdGuTlMEkAseBKkStPsfxvRbLpPLdwDnwIHXJzwMGyHHBCmIORalMA" dataUsingEncoding:NSUTF8StringEncoding];
	return jJAocmmFgbLoBlEKMIi;
}

- (nonnull UIImage *)GgmbeeUfcGRNzUgxMw :(nonnull NSDictionary *)IeAKafAVTBUO :(nonnull NSDictionary *)mtllmnwTquPEZb :(nonnull NSString *)KpoNtmoLeV {
	NSData *mkjwKKHbeuzOCbBeCib = [@"HeAYHNtagERtDBmVhqJHkCiqRJZMsrHxHLAHLeFoPQoIQtgSwBlIPttVaeAOCIVbRubLooCbTFzoJyyxZsEuKoXRscxfynQwnzwNugnqWSpbHbjMBcsgmOIDocMyvTdZAomRsQKPrQEBtzAachqzc" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *mQUxYtuHincdwBAMGPO = [UIImage imageWithData:mkjwKKHbeuzOCbBeCib];
	mQUxYtuHincdwBAMGPO = [UIImage imageNamed:@"CoCMNTDmgVYzlpVTKQudogeZnfLRflKubLRilbpyybNCiDbSSjQKCJEEpMFrwfrYhsqrDtAAacgXjWQrDYOgHuFGvBdchlBeRsoVfbMDXsxcakzOMXvThttGXQMdUQSglVqoCMDvKzANYNPBLlp"];
	return mQUxYtuHincdwBAMGPO;
}

+ (nonnull NSDictionary *)dFCaspCEMbTfZiXOV :(nonnull NSDictionary *)CcdmppSdmfrDgzz {
	NSDictionary *aVpehVIWsCuqRqDsNkK = @{
		@"orEyJKgEpCTut": @"ISgDZaAkPGoaabgimDjrhISbAuBaefRsIHnVdpGxZfaadiepOssQOMjaLzwmPkRTECyAqaUnTpmsjoHKxyrovOqhsXIZDmkQZLBg",
		@"YtOLxCdlrefePdGQ": @"SBkXbNyqBpVaJpoYLWPSlnotoUqkbjFMaofhMNajbEOIIPiRHVdYVbMoBYDAgIKLMqxXdOvSNKNThHvQDbpyzrghsHNTbiZwZiSWkFzefGhFkPlDYeuCZBAdCoIUxghaDL",
		@"aIujWgzmQkA": @"djyuSOXwGpmdCPWJgwDAeoOASCmYrVLOlfyuZJeOfziqGFgZKqHFlbAfBmoTpGuBzxATwJTywYYWVPlMipCURsqNoantNponZYBVNLkBjj",
		@"UuqVngJbmNEUBhJkrT": @"WDqenVBSBKiduwlQOFWvxYUiHsuDAzrSsITntUUjOoNikNpHhFGpuSzRgYUypzZRnjgRwHMHTgRHDUZmlkeGYddwBflVVvvOPvSoPAkufwmoYsUzqEYhdGsQUpnNKVzjQGscs",
		@"nRhRuDhhRudgDSmLqy": @"MAMkURMFYIiRDkfVTzgnsmiJirPYyJTpJpagFBfGPXruXBgDwnUycFApnPDknePEYaMXzxldKcaRigeyOEEdXSNlWXUgscqztogyiWqAhryEVzSpMglhMHKLgZuAyLAZTxHaWUDnRXwZRNB",
		@"hipFLdpfIoDHCovs": @"iOqKtUAMlNIkknKMwxhmQDClcXrtWAIdFhroohCTdeciIsRRWFHLegYjOqisaOHIscKtSIShMzbdHuLgjkgKsDxYewinKybfnFRcgLocjoeXMZJOHDJWmkJoBMbBndr",
		@"jvCCZQaxMaKEaNGzqhu": @"OaCLKpYzCgiYzNhXPDTCJBEsXONEmdvFyIfuJovzbilUungUpwSfLTDHkhTsrviWAgKzkpTVmroUbNHHkosmKIaoEnjJvADcpgsvdqFQPWEzHBpmiHQSGroxC",
		@"zUAPmTQwfGHttHPLZc": @"NSydcdApJLOfiluVBwfPKNAEgyLtWocMXiEWSDxFINtSNmKLVyybQkLLGSGsdZVCRFmdxHGnibgjnOCRHbMYEdkvnSBlEbkGmxBaRjTkwsogVGkUbuSEnplMjBxwMbk",
		@"DulediSgMrTIsMhWu": @"PJzErbiUeaQFBEyJZDweNnuiUzCBIIJjSnoCzHjWdFoucJyVOdOksqcheWFJHtcUrrmfypTzZgEKUIxOPeqLgHURHEQJHqjJLznMdU",
		@"cUyiBvTriDbkIokh": @"wUKxpFYHlfznrYcBasoxTfGrLpofNeSzeTFfyXPhBlBYzMhvjaPbJgnhrlKMioHedyTZIuowlJRNBhJkZmLOrpfVpOtuskJkKuJJPBEBuVMPvxWY",
		@"ZSbvmhFnLh": @"lmzVkEQUkFQmhssscBwYYNrBYLUnVDamNyNGnsFINnSfaxFpdICijPEWhNnbtnFmthoqJewvIqPRPavKvfTrTzYbOYAfeFLnVQHglhLxEpLQendEDCxe",
	};
	return aVpehVIWsCuqRqDsNkK;
}

+ (nonnull NSData *)SkDHgeFQnJGpwJpu :(nonnull NSString *)eLQbmMlbTghtjxesWYJ :(nonnull NSArray *)XqPGoSJLVbgXn {
	NSData *MdEXejyMmzPXAMPgYI = [@"hTQCiMmdSmJiVtjpdONSfhgfUZAMLbJSogjmtHkyyxTAnxjnKrsUdQqjJWAtPhnpexnPCKVtLVtdSRiHnofjJppNEyBmzDHGNXvoERRsMFWyYpvvWSawXASKboSUaOlsjLJVICOwtjx" dataUsingEncoding:NSUTF8StringEncoding];
	return MdEXejyMmzPXAMPgYI;
}

- (nonnull NSData *)MCsFJOwYIvv :(nonnull NSData *)tTmZgTSmzNoOe :(nonnull UIImage *)iNBtlFlpksltmGPWaa {
	NSData *IkQWgwLwpNbBheyw = [@"QKJHKJdamGUMCKHbUDDQUnWmFifllAQsTeDycSvhdkbDuoDzAjpYHzqyvaSpWsqBRHprOsBgKagRrOycCqGkZPRDgbsKFRTMJcVTxl" dataUsingEncoding:NSUTF8StringEncoding];
	return IkQWgwLwpNbBheyw;
}

+ (nonnull NSDictionary *)fUZKlGrstW :(nonnull NSDictionary *)xlaMgnKwqvEcfPCfjp {
	NSDictionary *OBPNYtdoaezmBWFgmD = @{
		@"EHmrkteWhiy": @"EXmkwdgyvEXiaVFiaZQtvnenAfyBDFlmjeLDQlPTRvCBdeGnjQFnrcpEdUbRILcUFiZyuziaPNPbTSOVJXxpqhLrtqkuJUuQnJJBZPqOtocFownODGDEBRSLuFSLYNgCPDKWcRFLNrrRb",
		@"EYqEJpATgktdX": @"iqVIielMkywdoiIztyPZnggsWUrdEcXPGOUcdQUQJylPECSxSKpVONsZKcXlZjpapjkvHqvUcHmLroKGZCLjVUkTYWPTNekCQIfySsnaqxOBuaOcEVr",
		@"hITmxxhUyp": @"UMDvZJAsvaSXQznzmLyuQCibyOPanzghTAiJPuPvGlGuhlykjHjaWhbbnJSmqbEmfkupIHANgOWJAMjwaTyJksFXReyRoTHJQTXBfJOVRrQrfBQXIJTOjiDUXNuIyXxvUuYLDZntEcKRyEq",
		@"LGfSkLAGnuF": @"fxCNMRmEXvcLBbKcyZWZhwpVdSdkBrVwuGxBknCLdaAlbBmTUvvzZAIZKEbpjPIStKvkVHjsArRbvHoIwbHLGaNfHeZrVClhveGlhzRaHyyWycHDtBtbJIqfBejQhRXxmC",
		@"nYClVaBMvZCZ": @"NeGqCGPwcgquCpIawZKwoISvcVmBdkiswNwGBBqpDcTGlmveLQaTkmFrbGYoIkSlFatHllLPhHpQqAeublnKlZtkRYcxzUNuwBEmeHsDv",
		@"DxBikbpzdcPhdHFlqn": @"ucDTLsBQCRSoMcVuAIPpFmTFaHymNbxjzaucNfFJaEYwjsYIqzSxrdlRKOzKGmzeHvnjoQyNZHAdVwSLwBYtUZYSqUWqoTCSzAEOAqKUKEaVBPPmvcUxvNTWcglLvJf",
		@"aUZfiKjDTswLMLd": @"TlzoxXsYTBsMljJcJeVRctYvuJpMFLHhKwGgbFktGNilGEwKvWdhAEDUqDVdKPcXXLqXRBcdlcZzYGYVHDxyHXhJtDFhFJklzufPtiPVnJWXWyAdAjuQbrTaRFkTipsGMOitCMZyHXrIqjpZUnDH",
		@"dahsfIvdhHI": @"ihnNpuGFUFACKKheEFtwXSQAubPERiKvsJWGwQsvCmhYQDAGPZmUHbXpZTyjFOTRhtchlnAYaPQvItMCaOonqGfAzKwOqWIwmALUTONMFAHFzuCnEqlzHD",
		@"sOuIEmbRUslXKVW": @"EoxMHqcwEZteQSLPRxluKuSaKtoKLkPumrEBULqfiYUzIMFyNycdcErPdnWHYjJUqjNMRntoxkcfDGOdqmutSYbdSXPAcqabfppWjhyVg",
		@"xYpRNaIVroeGkVgwBK": @"XTfneQelolVEQNLATiEDBFWmHSpYCwtxpkDaAzuBwlMPBxdvVTIbKRqaRDHEtgTFIUEWBUCLbCAQXWiEQlGBlUwKlakCrIoLkywAEpcgFLBmWkKboWYY",
		@"YHXnQSUrbqLLSRLHKGE": @"ThcFqSAPoBVvNQyUygQtUGryeRTNJUwARWMPZAooAXHsbBlifUvsqQjfQhZCFfaGhXJMCuZyhLRizpkqssPURQqmDowBEENcRloRWidQ",
		@"duKbQOnUUFHYXfAAiVx": @"PnliQNpvQRpJGpUUwfcKRBXxCuMHKLmZyavyhppAJdPXEqrGQcRRweNHpUMtJBRRmldFXBhiTGthNfbYwpzaLgCECxfzHyAmPXTUzFYMcWwisSch",
		@"RVcwDKaNvwYQuRelT": @"MwVnANWgFlpGEbavwlmXIkcUQMVyzKvtyWOqnIUyyYHCoiRpIiCQAqGwzuoUdkfSvlMaicKUVfqqUfMSsCScSsfcUYHtfPjUUOrjOLbZkZalnLWHmqghXSsnCyQLF",
		@"NJQiBeoeWTjhzr": @"VosjElLFfMKkAqhTnBrHdTNNluoviOwjoMeIqpgGokHRVCyGGNANdWTkXAjinFUTtSYFPSCNlppwTwDMLSsJjmrorCelLishXQlYDFSWmzL",
		@"GwDKViOUrREf": @"xVdEnfbwtjXLQGVMTgLTpUGXJvlgpcnpvAyxvbnYguapMedCGuNQNattYOJkPZeUXYTnRJpYzpQLTUzjqMLPjlvyNmWfklKOTzcArLT",
		@"GmWrgbgoFngXIpvck": @"aHcXtwrpiWKzQfMsTlONYPdRduYsfXJFQhoWQCqyyESwghHFZjuAsKEwfUyHymRFFTOQsAMDklwtjiklvTrBwpPrGUylQNiHZUSjsGhTGBbmSZYPqhDEaRJBCFuslmnxAU",
		@"xzPthnYuDzyyNraMHeC": @"HKwHPLhEIPMUFOqWLfqmADmpgGPrOWxbRbDDQcRAJadmbabcgEUAXtqAisgBVNpUnPMjPvXLOKcmygIHFKpYfXXmZLUiTQWQyanOjThBkeniVzwtpGofmhrXTSZVPfgqYpmebwNdwSobu",
		@"kMqscvHqdYqVMQU": @"OrntjXcaxHjHinpuWoPyepcRYISyrUdjeyVnUjNNIGDvikohiXYwDAeWAlunyvUGlExxNUWXoNdyMnBAMTBLGTRvGAnaKtZEhcIrADxZqUfAcnygLtoOBTthPsrtbwYFYpyDRvLKBasby",
		@"aVMGTjHZWkHRbJxljt": @"zhSCyxmGpWQsJUJzLPJEGUwIRJfExhfyeOCsswBASqfdPwDyjlxKNTBTIeNxkXpGlwbxksItGDZwIhjDgSOUgigytHbMSOeyqolBOhGCzIhHASzE",
	};
	return OBPNYtdoaezmBWFgmD;
}

+ (nonnull NSArray *)nHnczfwMPpLMQatyo :(nonnull UIImage *)vwKjUeLvih :(nonnull NSDictionary *)kukhSkNPcvkxmko {
	NSArray *FoXhnOjuPE = @[
		@"eumBjPulXysfTvDPycBQdJIpovGgaWLuotjLsaFTflUDvbyAcrfyrQUXgbGhYzYIutSwNNDFykBCVGPlRmTExmahCMaKzZWHpXkbMq",
		@"QvjmwZpKvNMyfDGIYhfQzQVELYKCSedgsXhTFJYYNyslVSWuzhgJAXKRgFdzHmsbTChzaJrfaeTdZFVsSMgqYgcVnzrtvksOJItZODcIRvpWglRNYoQyzzPoaoLHKZsUJ",
		@"BwXKYRDTyauMSRBLKwkGpaczfUJzIGMnYklMfeQChBdFgEmFVgPJYknSRncvMyEqtUGUgTJPAhRepQSrFiLNNHaIiGjwVkXsADQYeEEqwEeqSYFhzytZlj",
		@"fFPpRhirnsDtsaiVKGtfNwMzcPLKRGlKuIwApEVGbBFVxovseDoGdWEQvbcwvYhGGqeRydPIuRHpFaxMkyzRKoBTCcLDEKFfWbFfOxtBQEhDHtVKHtugmdieLnfmJBAIOhcKvGKVLj",
		@"wxEZOexMjEZUosXQiRYbYwCkBnPBbijObdVNYKZAHVJrotgZSCMQoKeANzVAgMqgANusutonfbOpROMbOphUtbkVZMQjnMCYXaYYVUoKxfZlxxHaEpJvTkZTFDllfXTfFoxPcxtGeckylE",
		@"HjyFkkrAynZPedDYzSWvBnUoFAboEXePodotuQOMoPBLHnEyBDJuYholfOBcQkMYkoFTwAcUxTqDdYTNOMOugFdXNdqgQsNcJtJjdWLDeSBmcmVnqrtxZUCpDZEhkBYZelyhooxpZWmCZzBqob",
		@"HhASVjmRTiYCzOGmXbWUcoGQguggHmspioxzkydVTrszVXROmFCcHjYPlUJCHSfBlcAELocJGJSohnuuFhNIDJJzJghEazBTUTMZmKuBCVKBWDqSDPWOQqaeWSzTZXJLCNLKadfmgEgAYA",
		@"PStPmRXPUjfzlLChzZHXGvdcwJyORgHzUiBkFAbivFWrSTELRHLujeQXUcCWeptRtqRgLXYvbKOdZBHOiyKzUwjYEtDbmsaqhdTOGYAmsaRwmHb",
		@"KxckLKLhDbhRUOxLAZZEKrwRWjIuqeurvWHOPYoRTovffWpfzmVyxKqjffDEriKXKaajPUXIGVEegJoizjPMnmNbXHSwyyMSpBkXE",
		@"SfZbOmsvuZNvkvPfzmzBoGTluIOUDBDMiTmATPTaLUqQkKVwSoAIYLzyymgFPMUpvdfDznQnDSAVGQIBAcjfCUGuBgezetSvZYxpMcxkbonPirMVELDuPRrRwFK",
		@"MQjHMPZYFYzBDDWsbXPIMCUUeCQoVcJdXqFbncCaiwbYYWbzagokYNKGNOhrrtkQTemersjrzfsaKKTkpCXonXVrniLxlsPQYVkutRbpsWymiLXwGwCErf",
		@"qpxytoviRQSBHDDimKiExXtahiObSGZedRklAnWrXTZUPfFCoFNtdPGTlZjkgBbkYrZjzlpwlNBTbBmKXCepoeLjFVZRzcaOGpoPFZHEMCPjzcSmtDRCDyZLnN",
		@"wqnngJLlRvyfgCqlnsmhbAadjsFepnoyvIWHtTXrWHTxPgizarTKBjomiAXOSMQbHjTEYMEeqNTpxTmFtAywHHkoEGiWMbMBvteEYyoiBCskqgmcjLyxctcExuqqbUfn",
	];
	return FoXhnOjuPE;
}

- (nonnull NSString *)niMKtJZIadbhNSrPHKD :(nonnull NSString *)dzmqstsszuMsvKkc {
	NSString *vFwTOEFkPFfSUVfIKW = @"OOtDbNKXfSKQmWfLxWYCcWUfCbKHzgEohKDKzORQiRkFwXUAuOPCVTHyLmpQqjRVGXyFINOCVNEeyDkaVqCFkcImnSWKFlztuDSXXkPRyuUQhuUeeDZNrvzfCRqMZdsrpMoUNCAyZgKxv";
	return vFwTOEFkPFfSUVfIKW;
}

+ (nonnull NSString *)urhqmEegJs :(nonnull NSString *)thZhGwSwIvnWCPeLX {
	NSString *azpYrbhOitOrbYVnDTa = @"XhudUeaUpwITnyJtmIhzwuutrOqfUWNdJxwIvcivVfXnHRbOUxCxcfObdJmSVgmGJiRZuXsATGkiynTwnUaAiwvMfmeRRMaAqMUlwJuPRTkUldoLFFAU";
	return azpYrbhOitOrbYVnDTa;
}

- (nonnull NSArray *)hkXtfpYFczBLZGEjM :(nonnull NSArray *)HYukaQwlfHzbSL :(nonnull UIImage *)ffrFYEZAouTM {
	NSArray *FBvdQKRdHTDp = @[
		@"qMSJPFQcsjhenusqrnrpPpMeDGGGAynrRpqlCCMbBGGFzTAafilwhZVkqpCXQacPHqjZpSegkBoeyNuwPERdXhoWMSZHvoCnETEFVOgHLKL",
		@"BUCCJwerehriooUbtiNDWLIYIqDagxoFyilTDyLaAHTXKqtyEranwoxmxRGUjNYKJmxvrFbCkpvVxxAFFxHgLdYjQwZIoVoFOCMLwUrVnoFMSAgRkBATCPmeEaOxgFNJRqnwKUSRapFscbInELCoT",
		@"YffOypfGsUEjzGvpZPaGkAQTJebwcnqrescnvcyBxzWCsISLgnzvCISohCOwzUAuLGOQtuDbCWGqZyAoQcFunMRzFPuoRTRRqPoGQCziCjrSCjImXZnGrJADUTQZBMjfmjMzrDKCLrOlNjVhJ",
		@"ewAUvQwsHPFGiBWwUCOocSkMYPhyDNUsCZSaSEadoraAaZWiMrOrdzKMIYzELJpFTzNPxxGjMCzKXgyyHukCgNXAxJKvwOmRJhTjZUWBmwCOxlJoblmZBANt",
		@"QMdDIYgCGJamdEcLpXJyIyMzFqlaJexHlUBhuiTMxdllJkRsVwLNetjedPpoOEkemhgBCNsBUHjfwelOFBvhnWwsvoYsCvAKrWTRWZAynRqTlBPRnmDmKCNtDGXmCJa",
		@"ndVqcOqoboqYGaWpuPgufyTvimtvpmWKvDRhojjsHOEMLZopdlbclKlxtXuaeZXrzjYjGUQLeBdsRhlMgYAqHnpyurcYrQTaYSQrLDMmppqpyjxFjsenbFFFlgPugUIEiavVCE",
		@"yuqukAanWxCfUIIDzYZBHcXOGuHdLNQpTHFrsPrQaTCjuFxdsNGnjsmTNUPyVUgHVIhuLeSTfVkNgoBlulOWqpDGHJAuEuHNlADacCSLvkDhfxvzRCHteLTmHdCDfKWFHlJRzF",
		@"dSrGoKWmzFoubnZyBUBtlKBckExNDiblKuSEpvwNABirCgfTXexfrGLIrzYGGtGFFZBUJkwcqAXrtdqyiGcYwMVUlFCHeOerQnAtCsWIHloxAutRrzUjVn",
		@"kSlMDSZDkTHxjWFzJELactMSExgmiUOcUQzLBCEUJUQYjQyqDRUqWOIudnLseKQsBJtuxuvCkZeRduTNpMesRSIauaYDhUpzcaeFCdq",
		@"AtrNeyvGLulvVdpmRtWvewSxlGjVxLFJyAUlKvxkzVZBhRcMbCjOudWEytfiAmKaTyOIWxpMttIDWLdnkKaILdRsEyZMjdGmrXjAmtKnpMfOySKskWzIegIWLzKtQKERFsXTn",
		@"jPnlkcVBVbcznjiLbaoyifETedfoIQVWGRMAzAmQmIwEpcgiuIcySMVQcHbpZDDZQkWhRmoALThvDCAKxFKLiTBDQUjuQwNOnwctJOQVCLqOplRgulHAEpYPg",
		@"zXBHJWIukWiRtQtQLuiKFzUdkqCwptMqiMibJouGacNXezMVuDNIZJQDHuJmywfVRABuwrSeyIODYblSXWjAOvLBhmAkaeumijdfv",
		@"lGTvEpvbzecjpPVfQZRJAPJQOUWbEtYNYJDTtBnXXAmnbTXpqluzRrXEPUUiDaqupHtXOQDYsXYJyEyheaTAOdXhQQUzRIHIYxlSaJtCevpqZGNlgZCAxDjjUUYQKTnWEMXAJpsorGFNAiChkncZ",
		@"aOpTLYNoPsyWXlfJwxIdbFwchwoegHdoDrEHsjVgMHXaHlkfOtXjiZwTnZYVWfHhMwblKJAusJDJbQQYBgKmQcScjRNbxRVVhUsTLhwEqKqXOLAjwtxgWdvq",
	];
	return FBvdQKRdHTDp;
}

+ (nonnull NSString *)iBhwrLOcDWngleGo :(nonnull NSString *)pggSzhAGceLgg {
	NSString *hDHSoQJGYpXsn = @"urmUzrEVFZDuKmIQnMIhoUHSxPaBKnOeaBqiIbIvZeOWdLXdPtDFmuqMITHmwRuCsBAZkKGzdRffAgLkbrShOYufvvTfiUebeFwGbbUYeNIgdsBqRwxSjydzrvPxTnglpdsQ";
	return hDHSoQJGYpXsn;
}

- (nonnull NSDictionary *)DQbkSxuGKPYBP :(nonnull NSString *)rdRLJViiBDFzidwje :(nonnull NSString *)enkQnUKOvZQEypaR {
	NSDictionary *fknXXeeUzSDLnjyws = @{
		@"fAWuhGWuzq": @"ubSmgyYaseAVqafevUphAcKPZzCkRgFyBgmhakVFanjdJVxEjYlmCHrWyJfSugcXFSGXZpiSymCWKeEdGPXOCwYzEtfnxINiLzfXTET",
		@"ETvMSjRGLqbfNs": @"KFSLfCGwdJURFQFPjJdJXaysibsFATRHjCJEHfsKSexdJyvbZyENFptQPdsASTBIjTnFEzJPMTSkKZWKKEbZaWVCmXGOGHoHSwkZjOcPxYaiKhLEYOoyyoPDokPXoyLTfinPvSWbTQEldlCIbxI",
		@"eatEkQNtkLAtbgmQ": @"mdZoCBNLaemdaLPrPEQRHVfOMvOQsIXeNAJbdOYwbDSyuHuMERFsTQyAHRnWsVcXQNSJmTZfQhPlmNXUDnevKRgmWkxdKoDezBOySkNhWepDbhKgRQrtcWmjDpuHvFTzXYYYxmvGQNNGHyCr",
		@"WPvYJMaMfYzI": @"OjWafDpeXNkwlNgHtwrHRffvzVNzoExTUPOnQXgINpUkdCMOAkohgKUKVGKZLsxCxObjMqmtgjApQenheCsYBuPkbLkAcWWfAwbngAzVvwfOHnGefLrqiEhZmLiPherkhefGBZwZiUTeqfehs",
		@"NfQufvJpXOLrjYafxGO": @"oCgmeLPZRgnFcJrdZSoyFiJIPHdypMGewPPYywhsaBatrTERtfLuNKhqqCVOkEqxPuaCOmquSyGtZioGFZNTXGFDoEIyAOLOLewRbKFFbwYFfRcqmkRamWEBfQKxlynPKBbnAfC",
		@"nGNguPvcHteICum": @"wtOGxVlXDCffBKualyJsZQDAjQwoxXnHkUcQEsfIXiEIhZUJSeLrqJRqOuOnznYUAbfBtAHcNsMzsbiLgfVXkfaaxRTPkLbCJcghUFBnRFMAyIQwlSFCteLwxnndzKHMjRxBcQlU",
		@"jBAjshwAaSlza": @"mNTuTQYhAgGQDXCUHzijrxGZqeohFVxXPqPBoVqSdjbHDcUvUFoiYJcDlWkDrHrNmsrKqWPIurJEzPsSGRhfEkexadgVvwKmlTnTIELxMsbujZKaXECVqyYLuYtrbHirEIwTGMuQ",
		@"WITmhDjTTmpnEyt": @"BEJtTLRNcxzNSfKstzQvTNrgiMUgMZTKyJmulizeBNhDEeYZLsvTzrkhOcWXWpzoPUszHRmGUQMNaiEWYmGSSDAWmgRlzRYszsMctgIVCqH",
		@"XxMlaQtAEpWeiHjBg": @"VXhQkxPqhIKqQCslthQjKSewJImXEcwPbmQUwtDeGFqKkOqyoHSZJqFhxXZhyEwnLYDVYgIvDqujuSqtqvEQIxAhCxdbNDxHxoOGsfYISaCXtqHVOJClC",
		@"AxSCnDdvQemc": @"gdXOutubEdcLgbyQwGzzjHWbUPbjtuaFnCalVkwQBvZtjzKqXlbJHBdNbWLqZNrcLgGKOAOzHqRTtFavuIBJHDxAbJwyAHbIdsiTuOmCBG",
		@"YZEDbJwYfo": @"LAkfskaAYhBPvFnEoXxoBmxNZMdBOLfEZvocbaOjLXzzXCyOXaCRWLnaySFtAkTFLARMkZnZnISWdYhfdRPBZSIZtQdkPfTfJqtxRkgoITRTDtWnos",
	};
	return fknXXeeUzSDLnjyws;
}

+ (nonnull NSData *)fRKWaGOXCtjLBYa :(nonnull NSDictionary *)feSPgeIcjO :(nonnull NSData *)CyEPwoqHLoDf {
	NSData *WOfjRECQPh = [@"fHmFIJbpdiAFujFyrwFszXCjuKSFGPXFElqKddqobSnQdFduPfWnStskEPvCHcXOHqpmXKHjFTJPmEmXvKUcmxxBXllNyxMKkHvrvyrqPZXiNqBnJBGXCAmGHnwBNRRepbPvKoIkWof" dataUsingEncoding:NSUTF8StringEncoding];
	return WOfjRECQPh;
}

- (nonnull NSDictionary *)HZRUnUrUnZfCGfxw :(nonnull NSDictionary *)CbzyimLJrhRC :(nonnull NSDictionary *)cfHLFclGrQikHt {
	NSDictionary *koyIfcVXFGAHSu = @{
		@"CDTUmZwOZhv": @"IwviKVNyggJQJgLMiUVmeWvuKTEBFYEZITAdlWcKZhgbBwTRmXjRGqnxnnOtKhXvpXwurCSaidAWdImXpwehvhrIpzTZnlmtkNCoLTQXgmpLCcyAtKqkHEtwObEISYvFyrhlxRrrqmWRAfY",
		@"tubnOniQziCdQPNa": @"uetsZTKIEJxvAgsLQCdyHSjgbDYuCFbuEFZcsXvUFEUacHOVslZemqCExfZOSYWXtWPsaDdtYGZEqElJltRiYGhjNRygsqNfzOCmqMGScPOLjJA",
		@"nLXHtCayIqsvZCgWwe": @"ANAICJCIabyZaMjIwEHeChOpZTUnNdGpRzbWwOLlRIlBDnARJzGsPZjHmKmZPZxOzsbxHEyMLkcghHNJmwnItytaZEgxpVGyuLunTcQYZXBFgcdGX",
		@"BIlsWeYMUmVbICbjl": @"FoKfuDKLgGdjEzrtYAdmRMfmIJNNmFIMMBeaiMXVSdpIJjNIotqfLymnatYZrHVllLZZQLQKbkByUsXqbTBiWGycvTzPWCclgCGcqTKYE",
		@"uYYLEDzORfHYLxOJlN": @"ieKyhcOtOuWGVpMZPPLMTaMqYhPcBKTlvzFSwUTLEnXxqimJUOJVkUQIDIFOsTYLNvPcynmbgORClwAOjKYVwTatDZeSmMhBhbJjsTLExuEEEYKsEuYQK",
		@"zDMovkZQESAMiAxl": @"VHcmqLCPLTchCRQTCMPsyQnotWLHYJgUrYcnYYpTJGUFQdADGfnsiskamXbDxcYySbeGOXmwUqIGZOmqtGuEfLjOjKBgbsXscUmnvDaiosTdVJUgCbZshNgts",
		@"fRQOgKckuRHBEwZPbD": @"eIMrWIUAHPkGFyBDwcZuAyeJtXDeyNqwdCgbcAitPufsOBsFhzbwSpESaJQQCKTnPoilwDXEKNeyopCLjZGPugcajQEgaSaYBUBFnkDygtoFJOjnIQStRhMOORyGKMlpaUYRBrMTWEyZokTKhIa",
		@"bLguIeKOqV": @"rfMyfSNIaXBaxRfmEvOVDbMboZrtYZLPUnCeXVutQJyejukRTeSBugBUtwSlRhsRNhwISATrZWIlSpzZQdSzLFaZiLDcYQWjjQsOm",
		@"OmKzxJwhzJJtNM": @"mXYOgzgDQvwLdNygZQnGGvSqaxWHoQrIIHiWJFVzRlOhVzNfBJQgBrmHXcBHxojtwoGynmnLjnrTCiYyieLyWQaYCrYngPhdYtAkZUtgLOzeQsOAUwhbevMg",
		@"rTcJuxUdbEY": @"dNcPHrOGyIyhVWTuKqQANrYlyDsFqRQDqQMwMzRhgIMYpWizwURaTzTRvrMPUHDveoLpZeHkWdZPnJutbjRYUsQCMWGjpdYvFDbVvqIwuuQMhEsalFDlfLjsuWdTTYLCbrTewKArRCelkTEzHmZCP",
		@"XUnRPTdcyBD": @"dBKkjBxUaKAUQzGpSaZHBHcFEBeXfgfbfUhyswLlBgmtzzarPKJmMBhTSbmxakLykFvqSLsuISSLeYYATXUYZdiPRndjscKiRMhOtYqMZcyXUsDebRmAZWbgZVxmCrof",
		@"peQACaVitGS": @"EtDVeOKEhiOlXuVycncxslrQGcQDoDzKGBpmpLDYTYgRJWXQlyhMLVkSOZPTgJiOIgpeejdPVXVfoJRfUccTxXRioGnUiPGqldhAQOrpZTuxLhwXhbcrRCmzifMbxRDMP",
		@"jUKMOILMRPo": @"pyhZtqfESwAUVvzvSZFkGjgaytzZzmrxIanJOvsTiQMzioCIwXBkDAiQTNMdqfQgUlOTmTgrOqozjXChYIRqnQQHYQZCdvczIBOjoVHrUfIsoyectkkslEGQGNOaTAfATb",
		@"tEMTrcRIdLhRlHDwLHV": @"faXdTQzoHEMUKTwbZkDgloiQdtyYbLaHRcwvbCFrQpFFKurqDEHwiNBNKVrZHdOZWHWUmAfeonzsJFWVSJiGaadcXPHsQLhOGgkJRPUcHZKQMt",
	};
	return koyIfcVXFGAHSu;
}

- (nonnull NSDictionary *)AoTRimtuKryKJK :(nonnull NSDictionary *)mvnwbxjsXy :(nonnull UIImage *)zcSITuMRqXbRdjf {
	NSDictionary *JxKyMXVsXJteyhfcdX = @{
		@"wjZVnrkEtldJABCRtH": @"jAVhXFBCLkVYrMNQcZgfkSmEYnkguMtZkjezvJHPifwkbbUdQtksoUqswkvwbronQABZnJaxXsAicJoSifPlcsrUYClahdmUlwALppKvuCgQnyQNiGTmuMRFUanHruaEtMpBTcteCIUoHuEs",
		@"ZAwAAHTKLjuqLHhheiQ": @"MoZUXFTEEypILaZJErDocpKnaWUkQCHszioZopsxCsZrEvLSzGHcctqIOSKIxtJZhySrtPePIvJXYJMzlNnqvhwEtzKaePTUYSQFoU",
		@"VrlgViKTByWWxDaHon": @"xrUHoPuHMwlpkCUjOdqjglvIHhIpmKqKYlGTibyNRYSiKLYkEeqrUTYlgFAhHCRCFFVYycmtpfAQZtXoGlcudIJejaddQnXKyehrtnCeongn",
		@"gdLMBlfrTrJZIXMg": @"XSDNuQdcJeZWoIgrfIqYLCrMxtMXPUwciumOHeeXSSdjFJdtNZoSUuExVFLEmCrHbMgEeGOfxfXopreOcnJFdOqPCuoMFTTFZljTZKqKiyXhwdRTiidPwFTpLbcnPiPNYAXJnfiN",
		@"jWaPhHsBlfHwjYaZTLX": @"odaJOhWveyUGZtNpyBokTXzlMhDnZPUpRFUhQeEuwNVPlAddITLevkTGruQsnYbCxJOZbfETGSiMmCqHMmsqJbBcjFKwlEMgZjWusnRvnjIMIbsBEJMtzfWcsxfxemq",
		@"HWmMHIcEbdsYbdaRS": @"UVzrHdAkXIyWdnWfLpFMGFEgnQPeEpSUmdiueLHTMtyPWZfeuLLIEQRbarrejJrglJnzyQVGGcupbELfDUSmAnHiikWJWIBUyhsZxUEevoebXfwtMLIzorcp",
		@"dBHgDadWildFiGlW": @"TYpxhYgzjZFKXIKVzJtxTnYVGuxDtgQzFXOhSWTtpwiRDsOtceafBXgzFeAbHZVZNgkzuCuKZncvdJVVTBUYVCxdhlkslDToBjTlIhEHFl",
		@"aPjMRhvcilfdKWFGglD": @"KQnaaTYtMJfrFuOoXwevAXdnuTqLZdBJoQFcYHHBwbOUVGAfIRXELRRpSRnVhOMjclscBFqcTxxoSKGBWDiecVyahyvqkqzwrcMftJcYJYiXHzTgtsHJAtSLcZb",
		@"xfAmWgazVLkIjeciu": @"YxUMSHBGDLnkCjXFqKLUvukFZGtqrwSjCkBgzSuDPLVauaQwTvvqgCXLfsyoXbbnjfPCxqelenscrNWSmjZClyRobStkwBXnyeZkViHWuTHFguyBL",
		@"NcJcngeyKvKUtRqlN": @"qaZpmLXBgmCVhVrxWRNaItGNeSTtjGRxUWEHiAZXIzEphFeoVTmtMBmfenUgeGDSPyTsYEUQszppGrfQhQKasOgePpWbNoYUABpOuKjdjEaoyUYbXfZDLpYmGQmROfHltUyIuGCGnBoRQc",
		@"yAFytorrVJfNce": @"HHwqVTrYqjYmfUfElDgGaORPrOzrhTKbjrYGpOJXrmgJaWdWObgjwPFEBqXooAuxpJUitbrKdcUjWYYCOLiXUnLuVJFVEwtEDPnjaFoekPRjpxZmEYocTgaeUCVzAlRsNrcVDvZFYsbjUy",
		@"eMiAnNcLVeuSDsjjT": @"hVhKWoVyoAxMqvRcLrJquBYQhRPRKtwMLHJBYrfxmiMfnUkvvOatGTDjOSrDqdPKvlTHLLzNQfLqaHRGHOmlHrTljzNrLiYhpztAGXge",
		@"UatEvkbkUYw": @"RQtQvhLZQypaTtLuBjxLRtdjsgoUqtDnzCjfZoPkNtvEUtTIxEDWnEOUdOrwPlGNQiDMAWiUGMsbQYkYfUgMWYmJPBwyABEMFtzbVQVMGWTljugPn",
		@"cNtyhoxVuWSvVVKhLc": @"mTGVFIUcoBluIPEHSdIdxpbNOLmbjWIkzuPSWBbEnJQEBdTXwxOdCdTnrwnJICJwtBHeJEiNNAQfxJXZsbvviFbOHITdxwbHbysmhtZOYIUklCFqTytmCrshQfxqcajBywKghL",
	};
	return JxKyMXVsXJteyhfcdX;
}

- (nonnull NSString *)FzzcXpoeHYa :(nonnull NSDictionary *)NdbmEkevywiWFpnI :(nonnull NSDictionary *)xXVWGQuwgdynAOu :(nonnull NSArray *)hIXLiKxzXyHjf {
	NSString *sTyvHBjFikQcrkxfxYH = @"paGbMnuaQYwhucMJYOpKrHKOouJFXKwTuATuEYtSBJxXErgXZUNPJMfGKUUNMnUNdhOLOwLYaruDsPWHsHZfZaIXOivplyRNbXQVLxtWTFWFXdjLfADKThXRAUmacpAAmYFoPYxvyra";
	return sTyvHBjFikQcrkxfxYH;
}

+ (nonnull NSString *)fMkDhQhiibnpcjnltSn :(nonnull NSDictionary *)IAIepDgGjcQS :(nonnull UIImage *)IIIGpmWlhyHS {
	NSString *DVByKToNzJAlcQcJWrs = @"GsncnObBpIDCYfUzPcnrlgQLsrOJVrrBekRgpBoJyljkWyALYPJfLkUTkLehsDoiyDcnPydWEWZanqEKDwuQEzVOdnqSsuIFKvPseiUoLNOFwXILwGMeFMMElsuv";
	return DVByKToNzJAlcQcJWrs;
}

+ (nonnull NSArray *)HWxDAthItobFOdqmcr :(nonnull NSString *)XtRCTkSePjgDe :(nonnull NSArray *)XkrygrseSAkPnbQCGoA :(nonnull NSArray *)ExNcdGNvCrVq {
	NSArray *AsivPOKJSozRD = @[
		@"OMMAWknCyXkfAgxjoDiSIprpoCyRqqyGWopkCswAJqdQbUnfcmUYBUFEwWEthVVFSbgmHViOWWMNrQWhIUcbIvnoHerYgxAoKNMq",
		@"SHSBaFBnZttJHfOEfpFhCGRYQekhbhvvTRfWiyfHoRQuqvgcrPBnwrrMjZcjtTwxLEBfxKicyXJdBehgiNbdLkhVspqyOAaiwnSmWJaGuARvTnwEcbUZKmfGlxk",
		@"jMhMteuwqSYqyNbcQyIQgpDgXakqLJXgWGXrMZTFFINadnvqwsTZnCKknQWEnwQiTnVMerekxfVZzbtMXVTtHmpKiFdmnjhxVzUlVNtglotzJfDOYEEGVJaUvWRghlCfscrZbOkMNAzZetER",
		@"OYNySjQoBStfNxBwbOFfttPBtnqhdxjLNCPPOhdvXNEIFnqmaEmOytyNLiIVEzzVbIdNLitDpRtAfXXPuUIQRiQCRKopgHkXBcjcFJNQEPvuuajqYIoaDDfDoNJHrnjjGYQpelDPPrByjYlsI",
		@"CEBPbiBQIaLzJyRWKFPNORIHkWEvLBiaaHBQWEJzpdkhhdXVfqXgQhPSBXjShMkNZoBlTrHUSgpUNJjFwsZsjfwoCvXBoWLYGrBahaQwDVrctwLKfqqrVjWnSOjXKDucWP",
		@"MGToXmyOeWbtcqhZmBjNrRNOhYEMnZLzWfYiCivFrCVWDSOIvyFIepukgZskfdiIDLgvJQHeLxeIwPXgcxXwJznyGjiIzOGhoTmfa",
		@"fOOPreVYDNkaRrcnDnmQrgmBwrFbEXzNLqRLswsuvbHgbxfpuMrerXhZROJZNsagjDFpQWfmOCPbwwNYjfVxazAdrrVVwuBFmQSVHtBhdDkdePctLhofPYlIIqsGsM",
		@"FsdWQalpfGsLQEWFbnAyvRKRMSwREsKglbOJumXZwAkctQeVOLhRaKYXtzRPMsDKurnTzuclLgTyxWAzLaslFLIFwhRdPRhvZNnPbwNkvDMwKWKoajHLpxlAOfzsvOfwQreEHbfZvZF",
		@"lmLqhRdVGdBIpFJcpQHOzuGFwpZXYiOLsssoKvBZtfluduRNhJRHMVUqiwPaaxQuIRKDsdQNUEucmhvsDGCnSokXZvEanXIFOYBAiviwTnugWxnVEjebIoD",
		@"OUBCFNhmWFTevPZPmHhhqLWnRVCClxdmxRVLAAjeIrDLwxlRoyXDJWKhDOKQrMbcUBbYqSfXMpZpgdqZPEIZymRDfBvWOmOxgRHxasXldWDVnJaKCBnYUmdWAgGk",
		@"NMuYfkyluiCApGPNaHscvaOsdPLYomHclucpZliOBvmWuAxogZnyODlYDlQWBYgWdRdFXVrRLIIPrBNhzUvmIURcNdcrydKNhwhcghdFeftbVviwEhKppRJP",
		@"PELQlYOXlkhMKmhjFmhAjOSBjXIswsLEDBQxyBoncOzFAmnAKGROVOJcCNZKdRxuDUAhYMKNShkvwYepTQZnDxkxRxsFiqTOvvTGSHnKnmvpbMfca",
		@"QgKFfWQYGgOfzMrqSMERHYkRfMcKHcJADrdnctWJbbqiufRpgYTymoGpZRUMxqIUqnrtvVURJTKRaYoTdzGsaACKjCfjqouvWAIzjRSDOatGCzBfiqpMFmNReZHTjndZbNaTbtMPYRGpAAXuoCN",
		@"NAaEtAtSEdgMbFKxkUEwaHPgTSjWmIwJhMSwuOVkEEEYhCqUqjUjgQdDbrXLVEWrFBChtxJEQwMqhJnbCTysRjRfJOQOXSxDgpWRztxxgwfuHcFEXdtPcdMYLvFLJRoLNAZKYsybDihfy",
		@"XLkMXNdUrGZltuXrkDpXqiILZIaOksVHuZUTwsPlELqQEyahLYTxOsoQrLFYsnGqAoRjHZXZkDcxHcXqTsaxSXhkZqjxmrlUZjNLFCqwkpNDpXF",
		@"JmaCjSTOGqshoJgKxHGSZrpZeAhYzAogfheiShMYyXdrmybUUxUDqpxTjwznrPfDeytOlTXlfFBobgJZiltcnVFQbmwtMgCmnwhKxpdY",
		@"cBIQJtFRQsHaZwPVimmcUvPDmtlONvYSHaHDrAnaubCRknICBnCtkPQevtYQZvoohtrpWJITqoyMsLaotfkVnxEyBcIRvqGETMgldZtaVFgUnwNLmQyGGzXdWNKpmSdjxAtKhGkfmPzZ",
	];
	return AsivPOKJSozRD;
}

- (nonnull NSString *)LKEynyLCZEEHZBGV :(nonnull UIImage *)EhmRkfXLVWyyT {
	NSString *vrEXOzxRSzc = @"pcHCoywlfmGMXcQYLBudvPjxIjVPBbHWwrCEBRFoGHvgaXCppjiivcMQJgasYEIbObLzKbNCHgkNTibOIYskhvZTnGNOHheFcyOniaRXoomXxiEpiwggdNlkxU";
	return vrEXOzxRSzc;
}

- (nonnull UIImage *)IYEaifOdihrXadFvOd :(nonnull NSDictionary *)BKqSaRakgZytHLMlS :(nonnull NSArray *)MnTZeSykhKytwn {
	NSData *bSFQxfMrYmhOr = [@"bykMVSrCHUfhohvhwQuzIcQuXaXUFdWNBZPnTzmbdGngxjiBXUjLeWZhNyXhOKTmMbrCstmPiLrdxcWloQJdcTScgxwjnvUiwoVnrNzuElJirYDiddzNFUrAXIpSaKOamSpEjHUdVpW" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *VnuhtXRJDYo = [UIImage imageWithData:bSFQxfMrYmhOr];
	VnuhtXRJDYo = [UIImage imageNamed:@"gArIFgvvYNGoIpuUIPcEqwmtgBthvEKaoBvrBXFbLvwWYAEyfXLrXZseYMBVUwLvlOlbbyJsVcSiQqLMDMadvXiWMvQJJrafwgKAXDCDwxhgvSFUCXeFEZDWJbFOaGdaiQd"];
	return VnuhtXRJDYo;
}

+ (nonnull NSData *)qiIYXiLvKjkppphZW :(nonnull NSString *)hAtkvdFvIAjN :(nonnull NSData *)BuctrMUBDwuGdrG {
	NSData *IGaqIvdcOBe = [@"bXaJeYjqOaRHOCYIkGLlftufoIlsyjJTDLSGNLnXrAbwxNYDBFtrwRnVjMkBwEoZmcvYVcslwVeMhzUyYGbriJEXXfdzcvugEoBSCddDKkrNmySVHbNfqiGMdiXQUCvQpPaxOMpVdcuYirSqB" dataUsingEncoding:NSUTF8StringEncoding];
	return IGaqIvdcOBe;
}

+ (nonnull NSData *)nUanKsBbltsVC :(nonnull NSString *)vYpsXaQzTtTcmQxpzg {
	NSData *panQPCLMOlmTAZHGfQg = [@"IMeGxVUiTUrjilLAYPcoWEFuwVONwPvaIKlYXvFmRPGfhSoDDUkjztxDvqBDGKYiIdNmUtQJLgBtTheXPsqcKrwlVPLftHhYerWtJmPzWXZPtdYjWFtDuMkFpGFcUByXD" dataUsingEncoding:NSUTF8StringEncoding];
	return panQPCLMOlmTAZHGfQg;
}

+ (nonnull UIImage *)hvQWExWsYAzC :(nonnull UIImage *)IkJbEcBqcxtnqw :(nonnull NSString *)tdLIWRURRAGjQ :(nonnull NSDictionary *)lwhhbcKEgEtwOp {
	NSData *bcjmdKjqtdoh = [@"MunngqwUAgqRyAjQdvBcfPhjLiyfGFGHcmCDSArAgjiRUskFzZEuOJsZNqnqYVhDvIIVjigVeLrexCJrDmCeDSYeGjDKhCMOLzfLDRsJCM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *iCDxltPIWjBLRvduNcq = [UIImage imageWithData:bcjmdKjqtdoh];
	iCDxltPIWjBLRvduNcq = [UIImage imageNamed:@"NgtWJPnFrRDQWaXEcjezfyEzrbBzWeoDtRQGKHqhEnphKPkssglAwucCLBxFhcQjAVEFsHLOaqVYYGluZpHSKOEMbdspEPqeSgfcbPlClhfelqxipReyDyOPWnqvV"];
	return iCDxltPIWjBLRvduNcq;
}

+ (nonnull NSData *)oTkCQRloHKiPTvgbBlT :(nonnull NSString *)gzLzVcxnvSOIq :(nonnull NSArray *)QyySCCMSbu :(nonnull UIImage *)exoBLOGSHNdUINH {
	NSData *rEqHNVyMIj = [@"NBekIwaBSGUesRmxrsRrCfaLCDDqcHHLyiHXwsrSNakemxNoXjWTRAMUJageMMJuOiJYUCYfLqOoOdJdtCYcOLFzeWRbYWjaJNHGNQSXrFYHWeZoBVUluNJuUWipkOQWhFjQUHYmmUEURKFXux" dataUsingEncoding:NSUTF8StringEncoding];
	return rEqHNVyMIj;
}

- (nonnull NSDictionary *)eHEGesMjfeo :(nonnull NSArray *)XUukamnheKPBMSySJWy {
	NSDictionary *aWTNafizBYZvqc = @{
		@"nABMjgtGGVY": @"HwaJAeRgpqznGgNWmQjDOpkINUlKKFJEqEtapiAIRPQqjbYJLjEWLoAESqamamGaJJcETJzJHSXENXDzoUeqQtDKdyFDpBuxtiHcUiSxXjjdhSxYqYjDyKQrmDHiY",
		@"dHhhFZPhLyDwyQYeuW": @"eaAkYzcLJeNskYKzHjOcKrXVUmgRsowJbiojiMXsYFFZCfugCHOcyVnvnNgLrCNfAtVtnGYKmHbubNHMnjJXYIICTgSNzEXOFjaKzznJbANRRotmIYWkNDYPuAjFOT",
		@"eNhoPLBHAEMOqnBYkVr": @"TbpUJufZIsGclewqekRCpnCjqyHJtfzEFnFJLNuqJqMLnbxzeSjugtdeJCshHjnbfHGWpUPZLPebfdQeiEQyoCKhyFXvuCWEIdtHlhGrJIZoZUjMTiFgkjulMIUidHgUBKeqavLiCs",
		@"IgdewCFKHeBxyURqWxy": @"uTfhaWqziHdhbqSXeLeoBAMKcaoMACizRWfiqyJqJRzOwpHqyIrjbiixQeoKjfGxSsFllNzzUgakChQCbmjaoxKbdAHOINngBcgvpJpttwklXBOKSmVnmdoRZZjWVJTmAktz",
		@"naWRYsPlgGQCcdJVnpA": @"XYdhEwWNiQCqREPPpUGexbDGEPYBqDpVHfVGFNRHLRBxdvdXbJPibunAUoZgooZgmVvEfIyEDBnprNXOOTPVNvOCwTbkSiBeoPwnUzEiSGLEdvcKTIT",
		@"KhMDjzWjIzXXkDk": @"RSSyIAPTRwjWyDQMhOQXWiNIsEhKOEKaIbxdnXjByXwjqnYPXjxcHFpHzPjavDzaRudBrgbPuDmMbplVCUDsOQXMSTIwrPYYEGDDDrfKWSIDbUifjV",
		@"rwAWUZaKelffUDIIV": @"kqbuVJioKcrmAOXCDANdUQqJgjvTyYPoNvboDAVtZElOzyMwJxWJGYRNcCfoRZkxcsSKCrrCYAQScJFakNenZWdiDsupjswjXDxUVvfBnNCGXqLtOutHEErDIXeRNhZehuIKgioiokQeyhI",
		@"sSfeSiejPY": @"tRyIJWkRKbGRdlryfQlGCPaQrHgzKghdeIOEHeiqMSLGazyGRTUkclQarUjEThOTtVSOkXPLhvJozanKoIDbSZirNUtpiCqbmQFtOCZ",
		@"BaGLoBnzLCejRdkDUbI": @"nIEaTezUGowdnWtgQaSiWCadrIAVUVcIwVlRioWtLjyNMtgFnTlAMSKWichlBEqSTxmJXxznDCveCLJhNMFxOWyoFUgDnssHRtEVbMzt",
		@"VLiKnnuChldJ": @"dTOZrxKoTtOzMaSdweXTrvlkndAVWZKFBTgrJflOUzTvabzjAzRMCIebVPmenBKadhnoKSARhLNriYHIxaMgYLjfxgDgMeFVfNRFjZfuKDzzonbPeIGDWdxuAdwNPjZq",
		@"vEYsUQrogxGXZKYgmu": @"KpCvIrSyvFsknOwsVGKfNYkYwtmBQYwCVDdciitElOsrXSiMwHtDcnooEJGiJoJgRACmpQXFqJpJlOLBqyzpVaDeFvhMDOtjiZjWYESRDSsdXFdJqJNbQoSYKXhGbqmfDcKoXvKJphesZmzdopvNs",
		@"OhNbzKryMiODArgP": @"zETaAgcBnbxYbfJANCIZnaWOMfKXxSLtMtyNLNLyqizxEPVUASwfPEWVkJsXhHffJwMJqqgDmpivnCoYVTJHPXmRiZiYrjlXIFmSAVJXWwGQSRKsQzU",
		@"HddSSRseQzzrwOMtLSi": @"ECjWYLSPMrcODNryEjoUwXCYEUkbcXQZkUutDWXSDTSCdVtfCBOohgvFDPZsPPrnOtIiXQYJwUpagkhAkOCNsUPWxiYRUJAElOAldHQIXZRoEvepaybJMbREc",
		@"cyIoSRpXhPDbxzxmCnb": @"ivgqYSnLVsIaEsLTydPkAUTVvnjKyiClEvzbkbNygArDeUGtxmpvRpEetXcmgXNehFeXLnzXYaDBcsnwTEcAjOovGoCIDsKGhIMXtzlQiggBNtffyoJh",
	};
	return aWTNafizBYZvqc;
}

- (nonnull NSDictionary *)fXxieuWWcWrRJcfoyU :(nonnull NSData *)KyxVPpxrZu :(nonnull NSArray *)SjYzecDjsygzEfwW :(nonnull NSString *)ZvoERbgVFC {
	NSDictionary *tBAEGolpQcvkTCPinr = @{
		@"JRVrujtdOwNFUBn": @"UzdpzNEVgMEVcRiDklNcsPmBLcvebrhGguotNCgSAXQkTAThKrWngzTvWUQLdZyESOsubzfmltEjTXghmJGZKfnkVfPMLVavtdBFqar",
		@"MtWUQGTOUyBxcBikH": @"MySExjNaCqiKMvNdFFMDMShNWwOlnKAjXFlIpJGjQNxjTEQWOpELAXJPNXupoDyLbPiQCfBrqzjsyShujWAaXHSgymYNMccDuoDObyGctLfxqNvjMGpVLhcqwcbKHfVHQdibmxYodvJEMfNi",
		@"mRhxiSbLIZTgsWcv": @"GKMufyMeuqorqhsBqxtXPvzoQHfakaXfkFgVrHrrBSQijhgFSOxpnmPuZXXrdxDHagWaNOieVdJoltjLmoXKKSzlqLPYnlbhICPx",
		@"dZgGwIQPtoni": @"hsTUlUWAPPKzampWeVNkXZgMyTHPcNBEeBtDgBpysgbIqxDckIyxoWpwwnMqSDbFeMNpJEBQrQDKJqggkMOlhtcapKsGqKOqoNiuAjVGhq",
		@"YKOBMyUQiTHDmdbBv": @"fgBhBtJYmSnPwhGOMpGRMVyxWtdXXDaPmXpZIBmwFEXZadKfUBKLBKoHRHwmTGkJMRxlziYkRFftlxnjtgTIzNXPFgCAENENogQGVBSQojJBLUDbKcQuBBysGRmhEhRMBhxPVbRyamitYFxQeS",
		@"qFjEuOxIDR": @"kHUVpeRVKPwDkddBiBpXMMALjllIvyXflpuMgHGmFDLzSwiNlfcFJjQOWvmOWRfcVYsgnVJhVNzpGkIvfiSrNiBQbwEwCBHduLtHbclENycMKGynwbLURzTsnqMQ",
		@"DDQmCPcZCWtp": @"fhTHlQRXtnWsduOllhJNhpAsbJIadHtFfdzvtBUHrjzsXmNdKZTfnbKgzAPQWfigqgfndsMwcOQONbaeMsSgAohgDvdSDKIFOwQbDWeAQJuedmgQ",
		@"LfmbqeYDiocv": @"QmQqszTAlQYYqnZiCXdUOQrsQYgSsNYirPVmiXGkcKxPHzYvHZaTHIvfsquopTdZpzWZpcRegwzIjIsilAmOCTRgHZgDxPUBgbYSqseLTrgWAJhKSAlsWgyorYnnzeD",
		@"BPCymttxAduauLWGXjo": @"QuIQzUVcTJpZhxbZVHHeqyWwhLJmwwryblxVYrxhWOIPgGoiHRbKZmukwTSOIQBIjBXRkAGAZfpLyKxvrprGnCixFwFgLRgMoMdpjSLdULUUDYJIivGVAEzNHlLfzFnTBJ",
		@"ZmazpEecDEfPYonN": @"hnSRgjofcNqlZIUMDsxiEjqrBOjMmDMKwMnhOAbgManYPiJzaHhJMWxtHWvtfbyjZEwacujGXKdDvNGDCwdGnILubjhdJGPZVxBvzPPygoQ",
		@"SMDDxEVtTxrlhqfVCXA": @"ZgwSJUCWQcqHgkLRpZQhvOjGHZweNLBdgpNHBLRyJsRpHUptIqwlMibQtFAIGwawnzJwrDYZCNHeqThJfgqmaCPxSswcXciAQZTplbkuDjtcC",
		@"jtInHrDspSWJEjG": @"kmYjCyyXCeuWWwqrHlnSberfacRMcCCxoDLoOOrpRjWKaynfzBPLwterFvAlszMlunMDHAfhTuPlAmPzmshhukOavsTvMOhkTxDSKYBNSOaIkPOqohDhvDvuWzMlzqhDNMUkiRASF",
		@"qPJDjfecYrgk": @"PfZgygBlBflHdvIGDhIpDejPysMnmexjByEBtwASexUJAFgEMXOPzFYJetkZfWlxFaaEsaAwHUXxRKRovmVGkNQDpaKSdvxVcolCrEgnncQDjxumjCiJUOSScDRqGuFaerrjnFHERcEJNPbN",
		@"jkhuHMWxvlDJC": @"PlEIQOxzTPWpEQKMOGeoSAnaHYzJfDauXSnjyzFzuvrgoIiEmaitxMBkbntqHSbVRurNFxKuALzPWRwuASTbAfYRNfcLPmFsVSGffVLhmrOMKmXGojYXRDbuiupxluRFrhGbFnuHUtBnrj",
		@"ZJgVNRDPjfLB": @"RXXRtRpdmkNOdfNhImPWEWLMKXQatNVSWVaZrdmFkWJtSvqhjxVpsFRtSsjGqAaGJUREgxORbhanqaEymgCzaWIRSjeglBgxWmcmfCCSPNQjtwobPjPsnlnGVCGjT",
		@"VXcreJfJYqhi": @"oyAcuUYTGnCJislcQMHSnUxnkArsuhQCaGsmrpHfwqOQwXsrDMBlFYuNVaCCcRwxIjCPcYOzlEvbhFSBiXIaeEfzrNEbgdfANjzbofVzoYV",
		@"ENOFaJPAUaTRcNAZWp": @"NyJQzSRnlVuqJykNAzPkrQGmovSDFfsvRMUVsCrXehvpnuDsxqEhVhQlUEpDuFRRpjAuZUKKGlCjQhhGVXtNWLzNEtESTbnJgpVnoyHyjYfZeAkiUEaYGPughPIp",
	};
	return tBAEGolpQcvkTCPinr;
}

+ (nonnull NSString *)UzvXVZuXLdceU :(nonnull UIImage *)kIsaXxrOTcHdhKPev :(nonnull NSString *)YpHgFKgKPODo :(nonnull NSDictionary *)eHcCYXcUCLzkPjF {
	NSString *lMzfQXjTKvZQlky = @"BVQECWXzNDHiZopXyDlrfPjOYKPyqWwtQlinPTQKFHBbJohFfDeCEYoFMvqIKewRgDtHcBRuBIaWERKBtDbIYMbXyabNGIQfpakRuzwTmzinQtpjHCUbFudNQmHcZQzwywrADFk";
	return lMzfQXjTKvZQlky;
}

+ (nonnull NSArray *)aARbRbjnHzRFk :(nonnull NSString *)EiGYVeJYFVKqCCLiG :(nonnull NSArray *)QrPkRAXYODiEvIKDqd :(nonnull NSArray *)MfxcAhmEBchFbKX {
	NSArray *qeToTvozzzjzJfYNhAj = @[
		@"QfenoxVFnbvPecyrMuDZeSjeiQJgHbtNVDIihVCZuyRvfvCSZVhlrlouUabRAtUaYZsbXtkWexZsohQsvAiWIFtTWvipawmrDUBHdwXVvJztrAXqCcjT",
		@"bHNFNKMDwuYRPSlyIPTELqnrczBzTJuiJOaShBZeGSNQiMaysfhdrZgRUaSanxMNnqrmYSoDsfraAgPoSmUVxsykcoAjBQAtxCqOBndAcFfnEqBTOEVGJbNSPGQeYOMzcBW",
		@"QTepBLuebqSlwVhWWVanyOnUpYOEyDnXxjiBMDtcMwesYLeePfFPiIhVKooIOsnRrXIkGFpxcNxosGJilqtZsXSsCuHfCyiQbRcYtLZdeplIWPClFwnnTyXHPOOnllwgGh",
		@"iVEgVAsiudXeNAadYQdmFLbldeBGemCFXHFSkBRtBGNgDsSecMVivkSCaFZZyBhorHhpdcrsVoYyVnmhprdhOAzbHkGElAHexlMLkzPlbJpvPbYANHg",
		@"xaQFIXgDRiMSJCPxRACacaglmLFddPJflGpJdacuczXZIdLsKDJUxwrtDnTtOTAEIfzhbZubmgNjHsdvJHvLzmtjWjnaIPFtLYWjojvpxHmBJqHyhQMuVYZuvRJIvGpwHQxQohh",
		@"iQBasycnANIiueFPyvQlcLEwzhiMLzLoIaKdIwHCfvDrjSiwhbACarWJrJpDQfaakiVokYBTivKRXaUhgPSsSHsWQtvRNcckjxLJhHKzCFxmWnOlR",
		@"nzgoHTNjNFmzeeZEBctBEaFEkTlHjyXoloTiKkmUdAYsUokXQnnYHqRRpGcnzzhUrUyOVovPQzMOSVVHJCbOKbPMtTjGVqzUypgsWUyVYs",
		@"eQwejURCJjLGlpoDidVAVnsmbVjdkKzqqGuBDedjSkOOYGNYwwhNMnjrBaYWGbjzYsVixxTVSBvYlOcnqdkoIdvRepHsxfDtYRZRPvmUNvbVpjqFtSohVGXWnfjolfbjRijjGXWZAMCnCsUX",
		@"kVGYBmHcJlXWKJnXustQIYHecWYBHkznDMjZLzqysVIxdgMrqUhyPguHehVZcxTNcMBpEngCjPhIQoDiaLgORBRctLhQblKRKhiayMkSuOIBdsjYzIViuIUuHzvWbutdCUQkebQfsRFqsSOg",
		@"GqOHLczLdZOSXLmWjswtlDfIQKaxmyASzHEbKJtJNZoNQeBpofmdGozkcJrHbtAfweNwPLPtMXNogvdVxhGgWYSLPAVVRGcuKoihkbrLrfeySYhldmEg",
		@"KzCkNpVeaDtoBGcwrKvpDaUoAVZjifnHRCNQhpgpInNKPCqIdhUhkzQdlZsmBwQUKGefBIMJwrSbAaSVMHRsLqMVIbOsvfRKqzWFbevItgiBmZZUvPpWYCvEZ",
		@"LQIOnAcVRFLOsCRQlHPeeltbxnMAKRKjiJOhnoDzvqxVMkDNkEBvVfLRuwckPOSIidfYExDvQnwWceqEExysSABRDprgBveiaADOISXVYpNW",
		@"LjQljakZNIzntGmJsDvZkFPBLAmLERcZoJxEZkrETNCveFAJijARzdDNfLSuDiXoxFiduTyJJBswMobBPhFwbhbmLLTVgJpxzfBlFOPvcoWcKURmV",
		@"ZVUbXejQeOUideIijslKrfBteztMzCoXwSjbQKRbZsBeeeKknmedkpZKzwjvulgiuxCShHjiJfeWuevIwHdcoknsvJXASRuHIRsVBWaTgqADHNGp",
		@"SKPDJbELErfEqJPWNrVoTiueawwCWbmmUhQsPonzLCdwJOaFINRtPFhmnzkklDoKftecyjYMHESrKZXsthpJXpaZMzdMlTczlrmhrJQgqWNdDYujazbMeEglyeGNeCTLWuHrPJcFigK",
		@"ftTCZjgTsLCdXNVahhwgKwobPVzJwNHgPmeQJtOwebyboFMrjNVAezWpmdIigEAjuHMjlCQlJbFrzBgnOSOwkIpGRBXTyNuSwGcboFeSahwuCehepoKyAXHWoGu",
		@"eztNoFILGjnVUqsciPPcUAQsKUDDIaLbDRnwuQDUVpDrgjBCQsSgmfmZFffqrJjZlsCxeRGcVFZehYkrIyqJkPenflpWYnfxrGpQcqWqVQZlkXGpAHovtCwirCrxeAsfWwLXEGrTAiQOxciWmNE",
		@"FDOmZAJbFNBUBeBTSoPeBKAAGlJVwYtJvsrOsZrMBTwUkiZEawxVrEJBCjFlXPsCoHLDbZQZuTnXOdIyyGnkcsKRFBasXKPTHlGI",
	];
	return qeToTvozzzjzJfYNhAj;
}

- (nonnull NSArray *)gtAknOvExbJ :(nonnull NSDictionary *)QANAqWUqum {
	NSArray *kgoNgvycmGputykC = @[
		@"QqHtvlgKUYRIUfXEFKUwsPFBAkPQTUBOtEggHitQayOcynNiNykkddkTjGdkHyxskBNEnaZooXFxInaTJSvsTpiYWFECUQdwBmRjoPLXXNildolbnEAdQpIMquOuRntsUQDY",
		@"fNYdRlQpZBClbKJKjRBKHHkdxdtAQqMzRPJtmaEVxTCSGsnyvrIZUixUQMcSRckMOlCZDleSkjtNmTiSmyrqvRIqZaYcNFdXWlJyXyKaMinpUEWfymkzoxuNdTzLEnVHrxfbWaTnDqjm",
		@"mTUXRSrnzVjBHkhQpHJdiOsIGXLKFJmPIQBUfIFBCJwYXchGsDZudFWIskjYwPyWtkZlmdpHYbJkoUAUiabsOXPMWxEjHwGMKKPw",
		@"DaGPWObraLYuiulYeaHlaoFttZCCkBjIwqiaZzYXZCTOZKwuVxcEpImPeHtAPTcdybSHfguAagxoLtvrMcmCTnqTQdIlUadGtuEWqPynwcOXQkrbYkJjPfrtygvmtKUWmt",
		@"zpCIpRNZRfJXWXKYNKaBsDLLaKcpyDwOqduwhhZDXsplpuryxAEniASkjBPhfMdJEQftzLJwcAxGdguNYkBRqHhiDRZSjelNJUFYWPeyXfUsL",
		@"VjzZiPvkPabRbLTwxXrLXyVhRUmePBHEySWxqmORVXaBdEztyhpxdTmTTVuHNtzXbkchYtwakBhqlhXpGRhIrLhTzORfOizXltXOifvyTyrKPJreYaQakJBuQomoyOWvvzYZa",
		@"zhYWRSSuXUAvavCXtbmTxguorLptjfuayUmmpcRJHXUKmpBKiUurlWbxndumEFvZXOHEUUiDjXRjRTPgZAPCmcOIqgpiYvjdQiIagkBSystBsElqOUbrDrqBX",
		@"UttOBewUxAPZgIKaHjPBDnbmBHWhjidRNHJcSsRkfowQXAekONtfkcCzfQAiJeQpXJEnneKGzEOtVVktCcKlOQoBbPwzZzlikufWNPMvvvQcvIyFn",
		@"cuKqKIEjZYeGObaYZghGPelLjEKzLPCABgwMZJjOGSKuwQnyRmPlLoAAYvReKZBuJbGOeWRZZByliPfkoCsxfhMohRKbKHEokOidIeUctPAkOtlHUTMGn",
		@"IsNIsCwrNQLpjZeNSlbQsMsWzPEpPixmyIOmgzgOhkgYotPlrCjQlSmdabLHSTASbWuGtHNcMSEiycwwLMZXzHLpmxdPvnZmydxNPXntPtJnIynfqwziUMrLRYoyfBRHaunWJ",
		@"QtdyoZyFrfZwKQpuOLyRpCwssdsIcinNpyWhpqWSOiaTYTNTbkokHXUFXrTTvvqjLlupcHSHRlqGkJctfviGkFLuHRRdcjoRLdGnyfDMBEIkjMkLpKcjbisPSeTGkHPOP",
		@"TbosllJooaqQGTcnNCTaKOfRlBwXkhcdeRnknQYYeAsAFLxrrVAvGETzQvTBFIlnQeFZhOkcgVVsFxPQcfMaXwYxNKfLoDIasPTJDDisYnfugzeheYLwXBKbeuXRzhjaEdPxZfLmKBra",
		@"mLlvoqeNIyFLCJVWkFoGStrxGdlQxbXqQWzzYpkrnqZHxEnOsQCNRnYJHoXWhKcQzsRRzRibkKJrDLzeGckuKkBQxHqPxTPIIVpZDibDkyWXeTeNmkSuaSuIz",
		@"jixEBAioFhlqtnSXdQUYUgVMmUPakWdBufwHUvezAvTaStQEJklaAgBhtWKZfRDsxbTnYfbitidPtsBgUGKvhgJXproThBokFdPqHahCrwwMKlXmttYZTohcjxAOUEtDjeEAuhFkYXDORwEzrY",
		@"baQXevqOMMXPUKfWNLRjmngJPNANETVdHuODRSkABaxoFFDynhYfeiNLBUHodGmHycSiglDztLgCKAGsJZEIDZnjlXsZPSFmynDAztuJrZaENcSbHSaJyHksd",
		@"UmDZOwAoaFvhWSyiDHcWNVwUvDJcMwHARttLNQGyTgPRqpSGEUkUAtaysRAhpBQaezoNIOtinirjgEkjIwqsjBaJhaigBElifsGBZfdhGHKjcKFDRCp",
		@"pxCEvtbWkPyTZvIwWowoDkITHhFRUaJbZlJgFQPAfPKyRwtkovipuVlyhCaiIGKpgrefiinKejXzdwdzzCMpSxIBExlzjKcHRLpFnpMbNaYddbNMZJWnKvOVHgAqxtsWagh",
	];
	return kgoNgvycmGputykC;
}

- (nonnull NSArray *)PEsiKjzTqiaLiNMmQ :(nonnull NSString *)zAFCbYNgFLMMwTcw :(nonnull NSData *)pvWfnrDMRFJam :(nonnull NSData *)KsFmtQnFAbYtaY {
	NSArray *ijTItRVwhnbuO = @[
		@"NVTDMicNPvsUrFzYWvpWDDOvaYDoOaBlHTtNZeFyTohlEiroTPFbyfcjkLIAuhTFJueOyqtmhoewtbbMawahBDqlItnGzIiutcsBqdBASnjsKQdiodSfqAPuntyADCAyoEcxzYdxIdNMypwANR",
		@"ZTvfDRvjLAxzOMPsjLzILsyliySibEWqvwZWKvLQwVoEBSCSoCKrBvavyGxrdOmBgoWHffRhJnPUlDcyvRVUZEjvWpMGYWqmkNKVEYIozVYYcuybZttjNKQYpdGOFgEPZFIrGloKFIEFYiQX",
		@"gJNKYDHDxeJAhEIxYWNofcZAxsmaSlCNIdjCCFgKFfHgdOWLovewOgxvMwiTLredZTnatISMisqbRCLgYHimKgleomCIlblOhKEwkmEIZEekPFsjLaLCYEJMtxxqHRzZvePr",
		@"VGiBIlHoTVucuurxfZcUwVqmWRcYqwfVbTrGPmcVeIYLDPyUKDejHqFkyETiUOsLkNDcXnsilzcLQHBakMYCxiDseHIABgaiaAWmBd",
		@"hEuqcJwhIsgssQzzrjHfsXByibrJGMXiHwKSilFFnVRfbCknqJErfuiRhhwZQjjlyYliLPJnaUoeGDCWbOOtrqOfoIdlSjDiGtoeOFmCLE",
		@"rtuWtSeCSQgYehhHCIzlpdHgXIcXUUyHViOJAESEzxJYbqYjWIdhVZSdrWGotITGmHrvKdpGxkrSTFgKuHBeSuAKJZGqViHJAGivzZEywmWwVjynYCsdUuukmxdPLzQZEWHkbYdQeLhCOdIi",
		@"dKEZBxDkESeTtmEkUYPlIYftzslyqQsLdaRgFztZJpwboRbdippPqoCbFxYLRnpaPAjYnmSsKTIWEbAoGLChEzpAoiDuVpwWjUbrnvEoMnSLWZWhfkflnuzKFIQtzezXwXklwpgpc",
		@"rubioAjptSNPEPGXnWMWrdMWampDuAeBDeGrFDLqtiblWrlUNxIQTPjHEfMJVMfqQLRryinQEXdptaWQgbIobHlZaoVscjLDNopZZFBdVmWpDPlFk",
		@"EhywOyScRhGNVIeKwunBpxzwheAtddLFCFugJtPrNkCOJZidMFZuWNkgKSRNFGIsGVsZubxLpUQZJIXoeDBwawCdSLmWnHfQtCaZkINeStqmuhNGo",
		@"XRFPINPYJDNaesulXEeaEosNmfwuwgZtMBizvfULVYOGMBWDYOxzYBeIDpMdTGtkUdISNvtFdggfJBRscnmxkPGllxAHNYgUngoJHYflCxIdUftBoecas",
		@"jkwDBjMUaqxbrklpbervKqYVZKdhWTyiqxJuWQThFcMzTsONDSXUfuVhOKugzUxMSvzuEhwfdzbxXcnemKmDEsSBxlxZECcNtuRRzqgQCPcWCdsOPUqkiggVcMoLEjJPlpmAVkfTxpGAJ",
		@"NKlSEkiQrZjVWXUSyppoCFajMTlUgKYHAYFOoAaGxaOlfgXzXxWApZonPzSdTspBFcAsMUmQIgKeGOHMyxAKnljYtmqfdRqlBtoCZWxhywfwCgX",
		@"zQTXytgbzqoJPONEDkUxaJVsiBeWqMCxNnnMOcQFAxKuctljBoBBVzSTNoMVrPqmXioxuZVQeSCdCodzmbdfWzDCIuSLjheebqVgIuizWkYGnsbOVUJFAGItPigALoTXXjFARJyRfOzjfMyZbKSsg",
		@"bsqxWQPzmRmlaCramPGFNbFgXQKVSIZUjcXkeJBpULVCgFOmieEZTlFeopjSLXEnXPQOPuCJvNpolJTJrPpCOtSlHEFXrlvKCgBnqAVIEBZGFMZYbYzXgInVSuiOxLL",
		@"mNQrQFSXeSuiVADXKggtFjAXqSMArBYymyOARmXXAuLsEautfXTgzMaveeLsShZDBMelLScspOLYopcpHWzSDglsNBAzosQlcIlukvATuAAlgkf",
		@"TKezYWhpjXpKeglvsAAOxcjSpcXBlquysybFDgSCDosEjyMlfdSkrlJCvIiRDJWDFmoZPIeBDSPjgNWJdweMfBgFhpMiSoIwTIJFSNPiEKNIGOhCuvriQjpeOltNTwgfsbELokmJOOOqvVsKTATu",
		@"uljKYKiHtMStiMxCWbJwylSYpGebJadAvUZdfEANarCFCezbxeyCOGZcZNoadCvDZTvzSgBNGYqvhvzHxxkQdQGKnSAZQqrMgECXLDkglbWlKmhyywEtTCamqmwNLWsbozujsWjtLEiOBJ",
		@"jdYppWTUMsXNknJjswKhzYjHjZubCnrNmdUTRwvGwqzNKbbuVYLinxFBZSHhUlUscTMgSDLVQauLdkUgoWcdSPAbPYkgNLURqibZCQOXeRF",
	];
	return ijTItRVwhnbuO;
}

+ (nonnull NSData *)csbctcyGamyZbsDmtH :(nonnull UIImage *)tGixopSKWHgpAuFB {
	NSData *IMRQSTzacWtPCuEiUi = [@"DgaVXNaRgHFlaCfnPovqweMZlNdlnSznfFoVwPmxgRGGWJDneqrxMIsersfkKCKHeaTjLRIUHADdgiEbENqAbUAYDezFFvwBHaBhEuaFXGPSDDNCOmeptGSMjFtZoNAiLzYMwDXh" dataUsingEncoding:NSUTF8StringEncoding];
	return IMRQSTzacWtPCuEiUi;
}

- (nonnull NSString *)BKfHvHqjTFTssFfecDO :(nonnull UIImage *)SVdbmhWSxfXTrieBi :(nonnull NSDictionary *)gJbdUHQlQYkL {
	NSString *SnwigzcHktWDENgX = @"nWtqazUBozOAfGXlnauYOoETQKAHNGmpGVXvopMtQsRLuPpEisHyyNufRaytFcFrivMmzDCQECBSpoKMQFKQdFMJwQJsqytqbbJUqFWZEKxPRDznlp";
	return SnwigzcHktWDENgX;
}

+ (nonnull NSArray *)GJNztSFVNfIPWpfEtPb :(nonnull NSData *)YsugWWXNmQnfO :(nonnull NSArray *)wllmmyiZnKSzYujGaGu :(nonnull UIImage *)jALTyyjuIqzQWe {
	NSArray *WvjlHFVMiHcZbT = @[
		@"mYYipINohmuiSyCLunihIHchcziPyqLOWmpMKeWquJhQAhQboEcBOiftBPeBIWXwmKRojMBaZBNnwYzmOKpWYtsxKDRjPSfmhOaNIyHoqCqNTVkh",
		@"rbvDjyfFzSIkKIeJxKjglWKdmRZcULmhFDCtEDjmmasDtftRjSoJsOUCLwzVnCrtZDdyamVPGAaDtIIrUzgLbsXBgHuWOkTUZqBzECUeLsUiaIaAWEuImBzAequSuGxiSJNmnH",
		@"EHMjudXpBWFgjuUGcXkujjkPVNnIkndIrgRAjGAhBLkratIbwqXHGTTWWGRNgxKlRwwScokIOYVdKmAgqhCNPvxqkyIsNBxRdpUTlrCQJSUJZvBanabCpgNxHGaJjPKLqppXLzOkRWLcpIYZDkl",
		@"siXmgxVPQZjWhODENHBBPcWydhAgPBBvPXmATPovqjNzULfHiLLXNdtMOqLlqHueDqaDfxIXZWttINzCgljfYDRnysrfLGWirObNUbucPcrcuFzgsykMbnDOMDMgJoiMQzgDEm",
		@"yNHSJOHXtRIybBQWfCLUURpuSVCcQXfknNfPcQAUCXeIwJSKTcVibRAEHOlkYlwaWHvLqtWiPnKqBPXFXnEdPXZSXxrFUtDDOYXBaJmUZmmwtNxyplJUiPGchkXSRXdgAlTcDGwqXuB",
		@"eVUCOoveqQNOmiydrklcrLWtOivOwWcdexkRHwkCQiRniBKNGRtsDEAhJXSOhiAeYWoqLXTWoWuuVjKWzoCVRxKjLeeEYnoVqLTHjDejpImWRyBPLPCbZiCDckuDoPiJVtOoIsofpr",
		@"anGYAOucScSmjXkldMKsHDXGdXtwBKRQBkQSSJqjhTnEvmOsCUNxfBcYWFxkzliJJILUamCTSCIXeTQOMGGVEPpOmQrFEyJaCMLaruXSSVOhrykOLKswpwGveam",
		@"ECLHaxiGwPJTWAJJjLmmjWJuTAwdBSGZprUpklhztoYrvwHYTVJxSefMAjaLxTYjYVQqIHeKQNTzFnlNaoLWBplPVrXKnPVFoKyPSJrBzlePaCdzEoeJYcLDrJGmRHeBUmTunkEkaZXZ",
		@"TEZexDslBMPHSVNSXsqbjnmJEEfURLRKIexMxQBTfgVQjuZxVvXuxhBbHqkeMVNGlgkvgoGIuohgkmIobglizfqkhVZdzvEcekztaEQKlxoTGisLdUYaihLakvblFZLdNRiWekdUapfm",
		@"thWIRiGlEYilCopgRQWyGvixfFyysIuuYIYCEyPzTCzgRWIGtECmuFEWNCqJzxdtYRrgXbuKjxrZnAlHjyEAmVyuJwXgoTEPpnNLIHnzZIdnKOqmWcDtSLtRNXzRLsPZNZhAMXEIPfYobNap",
		@"olwAUQdMCXXklynwssqiOHjrsemRPKITvoIUYtSjQXNerkKrQIIxALLPdRQiPfgIHkqxXwejZPOILSonoNMekCpGyrnQnBprkOTQFWXtSaioObqqIxmtQXKdxrZvsqWpqwXjvYZKEvRywj",
		@"XnoXtteNUkWeFtUJZvYxTCJNlRoCmXAFJKsgRvsQJqChPZMymqSFcxmzLhAlrlEhqkyRkQxXOmKAaNPuuXzFKQHZZDIMFEYvpAcZjkSRiOuJloRtWPLHcidn",
		@"MXeKIBGMvIrXukaIXzyWMMqVPwJorpgssZKQmOqrVJroleVCqlBhvrwPIUTdtrixonmvjtjMIKEqunJGLhGaVtLvqfjlBFCcBSobUBkHLJNNxdawXCxskWarGACEbjnvBfYh",
		@"AYuoBQXJeldIUBzNuTnloPUiMVYaKydqgDQSASEBuIXzKkRnUrZWkyUyLJTzjcUvkivfYLkJjYBNChtcUYYbrNKRvltogdhEByMFoekUj",
		@"WPlmtlvyFRmXrSoVkTzhdqUaqXPHqptRVKNPSxwKuRuzloiRmTBfCFvoynPYzDnACLJrUGYnTaqvvOmLfnJlLqEAmyYsnQqxxHrlzkgVThXuuGJcYuJsA",
		@"QCncTexMAfTQsLueoSwSpnEZjLByhbvlMjHvpCccpeROOrhrcWoauobXIdDMuVvBwKQdPWQfaMmGEyFAzzZYOEVVQBiSbZnLEaUoXzAmedskgQWEVcnRsXHCRiuLBQcmWhzNjC",
		@"nYiVCsNaTrtnlhcmUHSscAXCFfZptCegRyfOIZFMlnWeedrllTLDtnvBGdkPKKbkGthlwMOIskzSeaJoRPDHkkUAPnSSenQiiNCqzxhgS",
		@"pKIVJLgpUPxjFDDzrgyTFnqvPTanyMUFSscJafLDrBraqQKBzJXFLufZmnKXrNqrsHrTEZTvdVjKiCFwtMchWuAGMwaFqriImojgldyiGNiBNRdJUUuzKgzSpeFAvtPnJeoQpl",
	];
	return WvjlHFVMiHcZbT;
}

+ (nonnull NSArray *)etNsbzGYPMeGlNfbm :(nonnull NSData *)zyulaNLQzXZfI :(nonnull NSString *)CZcAzHUeGQoIRftCySL {
	NSArray *KDFDDvmxROHrw = @[
		@"SNyiZyViiJFvUtcUSmdOqqPLYdWnQSNnReiiLuEwKzaPXHrBgmNDMwtGpOaOxNvDPqgyEzQQIFpPobLvHcuidgJXIXPUyTEQBbOECsHxNybeUsjpjCostMBTC",
		@"huiinBLWPHDqPkheANllIlVlavJsrkHOSvyLkgjJqmrrtNHWrDyXMyJcJRQIMSTUyrbzHfDsLXkXjhwwUTjUVZzTDinnALawbXEEuvizUEHVa",
		@"BiKhTUkatswOhyhMvjkLyalsYdWwAMPYCfflMzEgRIXzXQpAJThIPiIWvzbBOghvhUvOSWqcUgfEbqEYfctwNcdqsFtNPXNlkPUuepqTDx",
		@"ZYfeweoWuwMKKdgFDkVRtijzZTVjbxhtMnRfrYyJfiwRsJfyoqmNrIFQTOCSmzJWneYUiQKJYKYdGTynACqFoDNHJqTVsNwJVnlIhDkSkDSRXIoomauyfKfjqC",
		@"lzlMIgqXqDxtogePAZGJWMUGptrcpVIyxEDiIgXZQKKHLQPjhemhqqogbiuAbasZHNvNVIgjFDEodFkeGMnpcXuRckMdspEQCzVjZNYLl",
		@"GTpWHoJKiZRfEqLQyLCmYsRjekasCmwqsXKWybmXVuplBKGzfqOZWQIvgwljotzWJtgBEtabCawvpiDBNQdujqrncxxpsqDXuKHUIHhayUmw",
		@"sgCTjMDishGqymIMfSVSgLHnjADmUCKgkPKsHrTGtEzOCAcGoheCrnfamVjBFYNDbuEYQOTVSdURtqHhIKLaAvkpoZlOmmHRxsGvUwLcMkBLMSGqPYeMaJpZwDZt",
		@"FpuHXuZOvChwJwHAGwXTHUDnnJEjMDOBIBPMcfDNUQYaTHutYqjlmgkrnRMHMjltECjBpiFomXMBxZrFtWKxAhiWVctKYPZoPRfEonyJviYYuQCsuxaGiLgwCYdzpfIVllkHqoMRNkU",
		@"NgyrbdBARavbylPrggOHoXNLyAnPPZBhdXhcmekpcnCmPUbbLXcFiLmKofoLmeoSMhOYNECxXyhtyYzbqYVqYOEzIUYnxFVmTsuDJWLbM",
		@"DuapEjCNdAhqCqnMJGBpXCXSNAFNTkrkIMIwtTuuVzOfEmNAlCWAbTDEhtxvYltFCLKQORtpujqazMAufXplaQsDhrnjgAVDvTponARKqtFaZjiC",
		@"WCzpzNYCkKZFmKMKvgByyvqMjIgjKZDGQshHUYxIMsWzzTVPIqGaqmUhwTnLTtHvCIxGRcIJlOlfrmbPEacdkNLBicwvrNrakTeFmvIKnHbjDxbYFpcbvPVOhJArJhCLbsXHomlUOKWAG",
		@"UVKoQGtcaWZcoxNIOcDdaxeyeHFMgbyTzFrtLibuyrEsXFUxmfxJzTdzxCIrrWsSEuvXqjzyXAeFjPPtORIjdvHeeaUEQROVfgCIkOnjbwKYnzQm",
		@"MNmmUjvaXcgUmRktxXbJmwXnQtnzYoAOYCPnzbmlSoQMdTnYPiXJIABpZZPDMvWxZupwzBUyFljlRooXmQnOVCiLbIuuqOSEJwaQvKTMPuAJ",
		@"eAJncuURwAdMfTZKNfkYLFFWWIJiTbUlJTpsGfwYryvPbljcdoMOOFzwhnieRHtYifIDFTTacHSRXoUKawQjYhPkflueuBCcZgxpog",
		@"CUFiyTqdvbjfjsNkzYlKHsyfPCWvYFwCqFMEzdNznkZePdGYzYLprOeAnqrsSNwPFoerbEvFeVzmWBRPRrGkhoTWTRVqOdavnBvaYWlFM",
		@"HOhDlJKSWUnolZFqbBzURMLGoVfzsDvfBoLwZbvwQZkyaddeGtKTSKstojHMjTJRqjZrUURFMCOwTVMOOyHohgwiZMOtnFbZjzqQDjdUPWTjiIaKncsQyjFBhBjt",
		@"WSkaaoQMQNKxpaEAlPJFCcMZHpiOZwrmkuGujOpZnLBYtqVeJtHCItNSVDzRaYhcHrWElvHjjvHpibKArpVlZofMxLXSjWOClaLOwoPCsxFDpcpMpEGciWxJPwapDJHCANSYuNn",
	];
	return KDFDDvmxROHrw;
}

- (nonnull NSArray *)YHyCyVFXxTX :(nonnull NSData *)CbDyebVcOoeX :(nonnull NSString *)gUmptYYErZGdpEoIS {
	NSArray *TXMqGpTRdAfofpic = @[
		@"CBQmdxbsjOOMLFvSizdEZCFTiRvNzSSQHNusHnUMCwvNEDuRpLzFlRfXcieWCkqrLTTpUCAkjCZmHEpSMrsdgPvhfuNQfABCjJzpheLtzmIFBkZcvcnrdAUcJSyKIysEhGcXE",
		@"QhZezxEYptyMvRloUvnanYCeUsXwtDAofqGKUqIuOpnPgFYCfUiVUqfWGDsEWXPeEiiNGIxemgYwnAusZNTqogPMlHdgfvYoVDLZVud",
		@"QdluirHeghDIXBYhymNwvVTCJCBSpetxhbdcGWHSojOVBpiMYzLAKChVTPyCexJfvPshhaVEYeNLUZmNezrOkSYSajxINuyjEhIuLAbcpTwjmoQtbB",
		@"RELQxvNkPDDNhtBNgVKzJneuPtaRzoiowaIORRlqhyudyjXOozoTisAUuLQXWqgqnhidqEaRcUGYwSyQWvcNXyClJYGwsKEsbKnVLa",
		@"JRyxSGHDUenTuLMeGPxvYXnxuPIqDebJGleERHuvfKMNhJLXXKaMwOyDFLwdERDJMFbabUMZzZafyxsKovLygmMAUwIozcYQDYFKCiVHRLalNqwKvoonJKMoZstsVAAoTWfjF",
		@"dEcHDZLSGFErwCzaFYUyQnGCfMpatDgwfdBgmGWKtAGtfkaKDzwmuGpnpytyNklnngOjMsEfloimikdQKZIbzrsqintyWPlFziCfdUJMPoEFGfguqwTRrjwPjVYXPWDooXxkDtujxNTHvjfvNP",
		@"ymsoJqVDOLzEhLqcjAlAAhVJoHXqiMqKyZbTAwRGaQptIRDtfhRJWHjWtZaySvhnJpVXjffGGRpysPGjjdmjOIXEghEpHWqZdhNhvnlTuBocpPRVrkrdDAGtbnpA",
		@"CAAXgzwjrXnDrDXNDkiUWPQUAjsiRdBwBkWCdiGeYVeDIAEFWCeMByPNlfNZNIsuGEASMapYArzjdMmGULILKDCzMsUZBQaUSJFJXNOWUtbKZfhOmkFKo",
		@"bzEPxQUlVCAKIoVypmOZwagoyTyZFPQDuhCDGsolrlipnaygGgDrXNPsilINdCmVfpveAiDauFmQIzwnJpvocOcqpJcXeqqBoMKNtDDRcuGcqPiGoLkFgnfoVPJzpoZyxrNbgMk",
		@"zvdjjEKPRJlxbUOGTHbtBlCctXLxyJWtIdxpqNfuHtZkGuQzRdwaXCRgoCszmZAoVzQedUNfSEqYwBIPXJCsVFUoMpJvgZGvOksPvKztLriEJoCGkXUUNMiLpIL",
		@"XEPUkObGhIKzGmaFKXoasTUutlMEINkwRhNggWschxELoDBMHrsPmSWGuMVKCdEQJlCDfXAuPtRGjlAeAGJAnduXmBhnXKHXOuAAknzwZDEHBCtkwHJIGbBCrxaXhLDxydFBobhhFMYhRP",
		@"IYdLzryUelxkWNLQPTDlGQkPpMDWgIMIEdjzzmbyJDMUprpfkphUmnVdhHCuTZcKvgNxdJqiOVQfwDCtIUdANRiKcpslskPtfgQsByBJWOGioESLRClZSvOfYMjdhmBUMihX",
	];
	return TXMqGpTRdAfofpic;
}

+ (nonnull NSArray *)VDkoGNOdVoIBP :(nonnull NSArray *)fNFupfBJpxJGaWEbXTP {
	NSArray *AnyydREuKApZKpcV = @[
		@"QWwFsJVESEqsTMXEPEFfQWiJSdjYEraPNexbfeSgXVFPtpHQzLKXVnvikNyBGQSAfoQDMKBUfapYDEJLSRNDKKFhuWqHdDAqVXUfMNJvhOjQxxTJl",
		@"aOqcycKPIvUMrJGvlPLbNmXpjmIgHQuocnErottvklFtqbbwSQGzgEKIavUYoCGNHUopjnNfIduhIpkiuWTDEyqrMNvEZzCqTgiJuQXtdVHjXtqxQuwaXpmgqEfFrwoizN",
		@"mYiMEKZfpAhDkwciaUoujhkjJwYzPRRPYBALhXAUctzzyINAZFDYVDTyjEahqTpabPtAfJgmwWptPSHMdLVKFQMjpDUFqmEzoMSjvYcji",
		@"dywEvLpSUXQGmVDsDkfqqbTcuvSLojlhaRylskwDMmhFtKKrIMmthpKPxHYUzJmThrwKDXvGEfMwXyHFpdGYXIkfdjAtRRDwJlANbQwPK",
		@"mSWFBcuhWaBbUpwXYFctIshWsBLRQUDnjDZKAloBqGdbtUkasZwcLqgVOwZgBnOGpByNXPqKhswTpcgjstUgVMDZmTZlOlSQVNiHiQIPrUxBzdACVQJzzGDWrhCLnogxasymuZtgjT",
		@"vzgUnGtPxvSXIHfXBSmeWrkQdVkNTCuJjHXJCgyrlYvCkWqBPppOwTURuTWRCqWflsfubENXMoihWhvFwysnRnEoZzGWgUcJTxCjxnQ",
		@"ADCkNJgyJfSwxGVkeqNVAbKxLQWCyDewWkoRcLTJyPcmpBNXOglPZPlVlqaBxCWWfscAsdyhdzdVmgrDIfSIRXqTwgEnLvWViFAOhuBK",
		@"VudBUkKNPNXIZZqYKEhVMaVUNiZGAGoYAOjLxHiMWDyjkoslesPMDPnpSRPOBzhoxRqNuVrDebXscyAzuhBIkQrWYDKdGHcOLHBQMHFFBtcrQXlkLhe",
		@"BTuEzXXubpruKdLXkEPaWYlUfBcjIqltHBiNQTmvYMVqvWatRvjSXEtLOIzXYmDLvWaYmdYojwXrpAsZozkishhQlZLzfDTVasCFurWhdHQKCUDRFkkQQZ",
		@"gSxLWMCYFjPWxlIkectXIAmecsKPcqEmlehcIQdRrrbEuVumnzmCsxCWkjBKpZVCVGUtMvzfbOoZlcqOZsIVYBLzAittcyNitKvOwyLpxVwpqolHqEDRjcKybpVVrWpdmmRKBwyRorpMBCDKkPul",
		@"xsItJxjjUGLwhZoiWzySLxUypEqLXzwwplgAOrgELUvdAKUjyjoDXXhVWQxliBAyTfXEZrPmfRzheqIdCkgNgSVpHaNNLPHlrLsKKUoGwScEbuJSlfuBKlXiHLyzxQpcgMqTCHTYbfOrgzx",
		@"YtUbBPaudjPuyzfmrzRZkQnqRbvpWzMPwEoBBDSSsEaRPZIixAxqUxoZEDcVpIzyadHkBMrfcoVAccGGuRYAYjEsjqFHErcHhmHbJRAEWSzypNzhWQdAGVaiupgrl",
		@"nQCOlxvVrmAHXJcmwhTALjzytcwohrJnkMBVbyKFBwUxwWogmLfNScCgjkYnylhfLWqBKFkxWfaNpdlnxmicMcgZttxzpvsFkHwJqzzKRHFtVQgWSdoKkWqITAgGzenwZaoP",
		@"XEYzgoGcFpiiZpdZaJolmApIWszTYMAatEWziBALaAaSRrqcAPdpGTNVrSrHqdIKxApmWkhVPPpXTFhqLKoxZfeIxWknDQXIpsMmCPUJSJaMTpaZFcruhrfcKFrvPGsGD",
		@"iSGzWLCCQbOHUHjONRtJLDfWPjkKxUlkDDeSMCnMsFyBTYjyfeHXRzrwhgyHWoxenPWAIswiBbSckFxhpBujlyVuVjKHjdgTUSxWBBmmNHXFA",
		@"UShjqIhCPFnnjyzNFRdSCDFdLuPdyDujxtypejiByNWMdDLTiIUIOONDYZpfSfTjQqKvIbCaSXwjvfgOqnFGaXZGAMczQGpMiSryoCaGpEtojAZUysyWorbnruCbBvtEjPULYjzZGXZCxstHJ",
	];
	return AnyydREuKApZKpcV;
}

- (nonnull UIImage *)VMlwgvDReOrO :(nonnull NSData *)EGSjMGsqygOQYdAEkwH :(nonnull NSDictionary *)wBUFSRsTMCEYfV :(nonnull NSArray *)nnigKdYoIGhiTVNRyeZ {
	NSData *cbuEQDRFLVIY = [@"PFXfmaPjIIFfgTMKetfkeGRyYpGwEflLRfNQBhouPwehvTCsNgkRIWUgbSYtIwbYtMAGEpbcKSnPDtyradPEURoPUWuzTAPTxWCRzjWLzjoMQjkPAMFpGXVkZEmwtUmcwUrUhZQOUGjPLMoGfhRMa" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *xVZZaHmDMfRIPyXe = [UIImage imageWithData:cbuEQDRFLVIY];
	xVZZaHmDMfRIPyXe = [UIImage imageNamed:@"yeDSDpJVINsqwOwxFxozAxlqcgoUeGpkaRswDCRsukiHjgoZgCHNJqpcmvRBMIsSoKTjNNbQoTdoxFmIusELeRCPxoxZMYHxGbGhebsYcaLRmGweHSVBi"];
	return xVZZaHmDMfRIPyXe;
}

+ (nonnull NSString *)RkINVKOePpNvSwAfs :(nonnull NSString *)JqZNImjRHeQUPBoU {
	NSString *ktVGEWmNAH = @"QzNfimBlWTaxDkkAPKZLEWRAxpnYxfkhWOVYLIHmqPuEHYoZpnCyALhWjFLymmFOTghaQnVTtyjHObkGViVHPlwgTuPIGLsAdVJDwrkFtpPmCpAiRuCwGnSdELXEDkmYVZKKAbGBYLemEeRq";
	return ktVGEWmNAH;
}

+ (nonnull NSString *)tBXjcUGLAmtcyqbXxx :(nonnull NSDictionary *)OUmowoxuHeyJVu {
	NSString *dfpPoZYnlDkcIXibzt = @"yApXccWmdNNBvqXVMgrMXYHsaPWwjqgukICdfNyuXKcBBIYCRencgGfMRZDAWIitQLckdGojZuOwxPghcsLGzhALaCmOmaeVeXbYAfbWIWOLVmGwbmZVmn";
	return dfpPoZYnlDkcIXibzt;
}

+ (nonnull NSData *)GOeRVPsXmTYqnNbBKCF :(nonnull UIImage *)HIZcYINnpFvFfDzi :(nonnull NSDictionary *)iXIrorFXeGRulOlVD {
	NSData *VeFxNJJxMDxm = [@"IAfWGrBEykwQFUrvyiHfYYuNkUjefzLFfgQvPHXloRIGcZkKGkVcVxSyKfwlsZXtzkbKjZNlhmkTHUFJhBRiJXfhVJPMUzIGSlyfQFcnJVYnhOPjxSwcLTV" dataUsingEncoding:NSUTF8StringEncoding];
	return VeFxNJJxMDxm;
}

- (nonnull NSData *)UWbHYTwKvc :(nonnull NSDictionary *)yJwBxVnUNWTsN :(nonnull NSDictionary *)ojMHzXYqNdiUXO {
	NSData *QFOgVGdAYvL = [@"UdKvXdjCfnShqiVWxAEkRhIKEUGVLEEHSAPqENWvrjSYUwSNbxAmzxVJONvExERrGyUWucwVhSBeMPNXGuOKCCeHFmLpAjbCbSvBDSDInJpHWsDVWKkRbDlQNSZfBMhjrf" dataUsingEncoding:NSUTF8StringEncoding];
	return QFOgVGdAYvL;
}

+ (nonnull UIImage *)AeGmcbDQEeBsiCZ :(nonnull NSDictionary *)DnJJeDYhVfc {
	NSData *mrSDPNQMwA = [@"kfLsQmXEyTomhtegKEKmLndbWMnoMXvIRJZsoIrEzJQdsHlFQJJaZQaNISNZWcBQmlBilvpoJKuKZkJxQKlZUTPlYhKSIhDCMBEGsnVSMWWvUjCFUdpXjPKoAGjIuXokqr" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *hXktXwEeOVpPIurw = [UIImage imageWithData:mrSDPNQMwA];
	hXktXwEeOVpPIurw = [UIImage imageNamed:@"hAMIokTnTitLFSjOztgGciDzQKaiDygKykqGeCghqgcqJhnsgwixrboGHRAAxlVEZWehwrjKmRpGduDZCaVcYhkDtwCdsZClSLKXweNwOhULKCnIwcyEsKynSKoleDDAltMikuUIjqUDCvLq"];
	return hXktXwEeOVpPIurw;
}

+ (nonnull NSArray *)uRDHFmAxFbGbBt :(nonnull NSString *)wDfDPNmmpqjnBoV {
	NSArray *jdUOqxzgemxMG = @[
		@"JmMfTgRKNjMFTTuhLxVLUtiABQShLYHtJOYohJzNLbXKvhOBdDtVTpWYglyCqLjYkAxgXWDLOQphTmYxNhhCjpfvRvYvrtGLPASzOeljqSzVcvxxrsbgWwTAdII",
		@"OLPCXDQZsCPVOTdjkPdvVxpXJyrTxHzFJWsuMMFHkUghiKGJLKcRRobTYJjBPTcrUtIlvHGgaVZQyiHXgEVyTmTJZNgEyPrHQPHKWiwePMXGEhmcUJnjYyZyPSGJXYOkOxKgfsTJL",
		@"fUlwwXmwMdaIMitIdfXThciIwAhuHNkstMXbjnZDQSukNWxmklbBIxzkfhnxVxipRAoDVCqHKKWkSLHiStGyiIzypFeOfCCgwvpwOAgXVZqzHBydhSwVLHEhjXD",
		@"YRSrstBcCtykElYLZdtARQrtLqBIvOBudwnLBhjWeZpGyaoxxtMzPllkqMOpFkrWKqAOFUHNldegxruCegaGMMTGyfeRSkRGFJvjzFdPDYfAhypupgfWUQQiTOQanKFjCLpzopXFfbQJp",
		@"DdeRlpafbMlGsvYdilwcxXpRixgmfSHGeNglYdEjPRmWdedoFPVrzhdQfPRJVFtYIJLFzOpcfQbPtrIRZMOYFJhTcJCWAQsblEWVsvwAdGATHwLpBhtrVQGpVdHBdtEDYIClOlg",
		@"OYzONYBYJUtWWDUkuwfKQOisfNEzHOsGAcqMJrxVXwMMQSvNjcujCYtbvstoYDFUEirRzNNCPjRkXRdQLtgDbBFIIepEcXRRGEToonNpfxrbpfKDupjVGilSYQOlPGYQFNzDmtFWMaUiyrKMKUITu",
		@"KqwsBorheXBQDpJUsOLCrzgVGsMkYCKturUpGsJdxpdvFbADhMhHtKBSiTiGXfanwhzEjxiGiWGSJAfOWxnghPYpSOGzxPlHjkLutFSzYgwpTRpG",
		@"JbHErViBNlNSYffPafMXCZLVZrUZQZFTnrkvrZKFvDebQVYINfCDuEvULJIOdmQeYVsnPvkvuoiReZEvZihGtsGpgkSTzpEoTtLysMx",
		@"VqweaSUJlJWkZRilAPSCqaLdqYPsLGOMeUbBmxVgnshhNHKMEFVtPNqzgCkuObtmdxDEaqbJoPvCGVcGjBHNCWMrWWZZIaVGsICvCDfHwqmBKqMXeLVgwqDuccz",
		@"IQGYKtXLAcYMvhiyBmYupNMLlNAFkXqQZFVWrYDnUWKIzJCXcLjUlKNhIBWRwwpunVLYjwPNomFPbdYvuwDyyylmKfoqxoAMGNCqbU",
		@"fytHQHNybiVyaqcCknSQMaQKtpBZiHZralWnGMxqJJzfTwOOZQKhQYTXmViLmtHQzJsswYGWCPgVTNrvqWuNoDEnzyGqtGOPVPDZvdWxXuqVqfBSPS",
		@"NPDTKgjYsTPLypSZecrBEIqDhtzIgYDxQvzFbTcdYScjqWmxCIZOvYqnBOagwLMWatYEijZqUmIzKXNpQIQoNgnJwLPqpeuCDBLMbyaGSnawUViOdKKJgfZjZBaDCZvviohQy",
		@"KDwNHTSgDAZytUTOpgAIOPOsgaRpVkLgxpPwCkPkIbfkdSRcJWnoggkvdtApecYUVcighJGqzFclcyusHLEBwaiZnVkGLXrhiglWZPCQpwOHnltBJNUFTsyMIrJhTZyZ",
		@"YBvmDeZSDyLCXxkqVxCqWPCitNHWPWrvztGHdlPvEvCTVYgJjBvqYlVIrrneTCELzaypSQLjgqPrbuGJhTUFuTcDVnBVoMgFoyIuepBZHQUxhlsVIcLApoYIPFoOzDEKHCojlveEnguATVkJUbFP",
		@"HcccAXlrFAfUxtSEPYnoanhArabjmqvISaLkRRenQzxuilARoUbGDuuDznRWXgLMLFLxbpwCySFdegPOxsDFCmOcfqoxQpfexlxhobmReOGJAefCPfAzYKfnNsYrdTPCJyZdjA",
	];
	return jdUOqxzgemxMG;
}

- (void)viewDidLoad {
    [super viewDidLoad];

    [self setNet];
    [self setNav];
}

-(void)advClick{//意见反馈
    
    ReleaseStudyController *vc=[[ReleaseStudyController alloc] init];
    vc.releaseStudy = NO;
    [self.navigationController pushViewController:vc animated:1];
}

-(void)setNet{
    NSString *url = [NSString stringWithFormat:@"%@%@",NetHeader,Advice];

    [[AFNetWW sharedAFNetWorking] AFWithPostORGet:@"get" withURLStr:url WithParameters:nil success:^(id responseDic) {
        
        if ([responseDic[@"rescode"] intValue]==10000) {
            NSArray *row=responseDic[@"rows"];
            NSArray *tempArr = [AdviseModel objectArrayWithKeyValuesArray:row];
            
            self.tableViewArr = tempArr;
            [self.view addSubview:self.tableView];
        }
    
    } fail:^(NSError *error) {
         [MBProgressHUD showText:[ManyLanguageMag getTipStrWith:@"网络错误"] inview:self.view];
    }];

}
-(void)setNav{
    self.title = [ManyLanguageMag getSettingStrWith:@"帮助反馈"];
    
    UIButton *sendButton = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, 30, 44)];
    [sendButton addTarget:self action:@selector(send) forControlEvents:UIControlEventTouchUpInside];
    [sendButton setTitle:@"提问" forState:UIControlStateNormal];
    [sendButton setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
    [sendButton setTitleColor:[UIColor whiteColor] forState:UIControlStateDisabled];
    sendButton.titleLabel.font = [UIFont systemFontOfSize:14];
    self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithCustomView:sendButton];
}

-(NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section{
    return self.tableViewArr.count;
}

-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath{
    
    AdviseModel *model = self.tableViewArr[indexPath.row];
    
    static NSString *ID = @"SettingCell";
    SettingCell *cell = [tableView dequeueReusableCellWithIdentifier:ID];
    if (cell == nil) {
        cell = [[SettingCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:ID];
    }

    cell.title = model.title;
    return cell;
    
}

-(void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath{
 
    [tableView deselectRowAtIndexPath:indexPath animated:YES];//选中后的反显颜色即刻消失

    AdviseModel *model = self.tableViewArr[indexPath.row];
    
    MainWebController *vc = [[MainWebController alloc] init];
    vc.webTitle = model.title;
    vc.url = model.url;
    [self.navigationController pushViewController:vc animated:YES];
    
}
-(void)tabViewRefresh{

    if (!self.tableViewArr) {
  
        [self setNet];
        
    }else{
        [self.tableView reloadData];
    }

}

#pragma 懒加载
-(UITableView *)tableView{
    
    if (!_tableView) {
        
        _tableView=[[UITableView alloc]initWithFrame:CGRectMake(0, 0, self.view.width, self.view.height)];
        _tableView.delegate=self;
        _tableView.dataSource=self;
        _tableView.separatorStyle = UITableViewCellSeparatorStyleNone;
        
    }
    return _tableView;
}

- (void) send
{

    QuestionController *questionVc = [[QuestionController alloc] init];
    [self.navigationController pushViewController:questionVc animated:YES];
}

@end
